### ISSUE TITLE
networkStats always at -1

### ISSUE THREAD

**Issue by Buzut** [sebhildebrandt/systeminformation#10]
Hey, me again!

If naming scheme differs from `_darwin ? 'en0' : 'eth0'`. For instance, with [systemd’s predictable network device names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/)

**Comment by sebhildebrandt** [comment]
Hi again, I do not really understand your question. Is it about different naming of network interfaces in OS X or is there a bug that states network is always up (as stated in the title)? Can you be more precise on the issue that you discovered? Then it would me much easier to fix that ;-)

**Comment by Buzut** [comment]
I have a (Linux) server on which the interface is not `eth0` but `enp1s0f0`, and with that name, it doesn't return any stats.

**Comment by sebhildebrandt** [comment]
very clear! I need to make a small function that determines the first physical network address (which is anyway used only as a default value). You anyway can call networkStat with your interface name 

	networkStat(‚enp1s0f0‘, function(data) {
		…
	});

Thank you for the provided link.

**Comment by Buzut** [comment]
Thanks! 
Calling the function directly with the interface name is not as good as letting it determine the interface all alone for automation, but that'll do till you fix it.

**Comment by sebhildebrandt** [comment]
already have an idea how to do that ;-)

will try to do it next week …

**Comment by sebhildebrandt** [comment]
Finalizing V 3.0 of systeminformation where I implemented a solution for that.

**Comment by sebhildebrandt** [comment]
Done in V3.0. Better detection of first external network interface (as a default value)
