### ISSUE TITLE
Windows 10 memLayout - missing space

### ISSUE THREAD

**Issue by Pancho** [sebhildebrandt/systeminformation#102]
https://github.com/sebhildebrandt/systeminformation/blob/e93789ffb3a937897c01d06a6775853a66c7b5d2/lib/memory.js#L296

It might be just me, but when I'm calling this function from my app in Windows, I'm getting an error that it cannot find the right file (system32\wbem\wmic.exewmic' is not recognized as an internal or external command, operable program or batch file.)

When I put in the space then I get a new error: wmic - Alias not found.

Alas, when I strip the "wmic" completely, I get the data. No idea why though (I'm oblivious about wmic). Is there anything I can provide further to help you with this (per chance this is even a problem that's not simply my fault)?

**Comment by sebhildebrandt** [comment]
My fault! After the getWmic() I forgot to remove the `wmic` inside the string. Will publish a patch tonight. Sorry again!

**Comment by sebhildebrandt** [comment]
Already published ... v3.33.13 includes the fix.

**Comment by Pancho** [comment]
Thanks!
