### ISSUE TITLE
Access system information from docker image

### ISSUE THREAD

**Issue by yannickl** [sebhildebrandt/systeminformation#104]
### Issue Type

* [X] Bug

### Expected behavior 

When node runs inside a docker container I would have access to the host information like that:

```javascript
{ manufacturer: 'innotek GmbH',
  model: 'VirtualBox',
  version: '1.2',
  serial: '0',
  uuid: '43E2596B-4C3C-4FEB-B8DF-0E9B681C4B3E',
  sku: 'Not Specified' }
```

### Actual behavior

But I have this:

```javascript
{ manufacturer: '',
  model: '',
  version: '',
  serial: '',
  uuid: '',
  sku: '' }
``` 

### Steps to reproduce the problem

Run the `si.system()` method in node from a docker image.

### Specifications 

- package version: last
- operating system: ubuntu / docker
- hardware: mac with VirtulBox

### Problem and possible solution

I don't think this is the appropriate place, but I would know if it is possible to use your library from a Docker container (with docker-compose) to have access the host informations? I need to get the serial number of the host to identify the machine and I don't know how to do that from a Docker container and node.js running inside.

I've updated the Dockerfile in order to install the *dmidecode* package, and I've configured the docker-compose file to add the *devices: - "/dev/mem:/dev/mem"* and the *privileged: true* options. When I use the bash on the container the *dmidecode -t system* returns the correct infos : 
```bash
Manufacturer: innotek GmbH
	Product Name: VirtualBox
	Version: 1.2
	Serial Number: 0
	UUID: 43E2596B-4C3C-4FEB-B8DF-0E9B681C4B3E
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Virtual Machine
```

Best,

Yannick

**Comment by yannickl** [comment]
It seems the *dmidecode* return contains some tabulation characters:

```
[ '# dmidecode 2.12',
  'SMBIOS 2.5 present.',
  '',
  'Handle 0x0001, DMI type 1, 27 bytes',
  'System Information',
  '\tManufacturer: innotek GmbH',
  '\tProduct Name: VirtualBox',
  '\tVersion: 1.2',
  '\tSerial Number: 0',
  '\tUUID: 43E2596B-4C3C-4FEB-B8DF-0E9B681C4B3E',
  '\tWake-up Type: Power Switch',
  '\tSKU Number: Not Specified',
  '\tFamily: Virtual Machine',
  '',
  '' ]
```
It should explain why it does not work.

**Comment by sebhildebrandt** [comment]
Will have a look at it this Weekend, ok?

**Comment by yannickl** [comment]
@sebhildebrandt yes this is not urgent. 👍

**Comment by sebhildebrandt** [comment]
Thank you. Working hard on FreeBSD support and will provide a bugfix for this on together with the FreeBSD enhancement

**Comment by sebhildebrandt** [comment]
Bugfix published ... Thank you for your contribution
