### ISSUE TITLE
Doesn't show temp.

### ISSUE THREAD

**Issue by cowboysdude** [sebhildebrandt/systeminformation#106]
### Issue Type

* [ ] Bug
* [ ] Feature Request
* [x ] Question

### Expected behavior 

- Would like to be able to read CPU temp.
- 
- 

### Actual behavior

- Shows temp of -1 on windows 10 machine.
- 
- 

### Steps to reproduce the problem

- Just install and test
-
-

### Specifications 

- package version:  Latest
- operating system: Win10
- hardware: 

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
Hi @cowboysdude 

As also stated in the README, `wmic` - which is used to determine temperature and battery - sometimes needs to be run with admin privileges. So if you do not get any values, try to run it again with according privileges. If you still do not get any values, your system might not support this feature. In some cases we also discovered that wmic returned incorrect temperature values.

**Comment by cowboysdude** [comment]
I kind of thought that too...but was hoping :)   Thank you!!!  :)
