### ISSUE TITLE
fsStats function is not supported

### ISSUE THREAD

**Issue by sureshokp** [sebhildebrandt/systeminformation#107]
### Issue Type

* [x] Bug

### Expected behavior 

- display fs speed information
- 
- 

### Actual behavior

- return not supported message in console
- 
- 

### Steps to reproduce the problem

-
-
-

### Specifications 

- package version:
- operating system:windows 10
- hardware:

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sureshokp** [comment]
Error: not supported
    at process.nextTick (c:\Users\EMDnew31\Documents\MyFolder\node_modules\systeminformation\lib\filesystem.js:329:21)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
(node:6224) UnhandledPromiseRejectionWarning: Error: not supported
    at process.nextTick (c:\Users\EMDnew31\Documents\MyFolder\node_modules\systeminformation\lib\filesystem.js:475:21)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
(node:6224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sureshokp** [comment]
@sebhildebrandt pls answer me

**Comment by sebhildebrandt** [comment]
Will have a look later this week

**Comment by sureshokp** [comment]
ok thank u @sebhildebrandt for your quick reply

**Comment by sureshokp** [comment]
i think this error is fsStats() is not support  in windows

**Comment by sebhildebrandt** [comment]
As stated in the docs (README.md) this function `fsStats()` is currently not supported for windows.
