### ISSUE TITLE
memLayout and diskLayout requiring admin permission to work properly

### ISSUE THREAD

**Issue by calvingerling** [sebhildebrandt/systeminformation#108]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

Acquire the system memory information through memLayout() and disk information with diskLayout().

### Actual behavior

Getting an empty array in both situations.

### Steps to reproduce the problem
```
const si = require('systeminformation')
si.memLayout()
  .then(console.log.bind(console, 'Memory'))
si.diskLayout()
  .then(console.log.bind(console, 'Disk'))
```
Result:
```
Memory []
Disk []
```
- Run the code above with Node running in a regular user (without admin privileges in Linux).

### Specifications 

- package version: ^3.33.18
- operating system: Ubuntu Linux 17.10 x64
- hardware: Dell Inspiron 7460

### Problem

I've looked into the source code to check how the information was being gathered and executed in terminal as a regular user and with sudo privileges. 
![screenshot from 2018-02-12 18-48-50](https://user-images.githubusercontent.com/13140497/36118832-6d660d0a-1025-11e8-9b95-11d0c1ffceb8.png)
Result from memLayout script.

![screenshot from 2018-02-12 18-48-14](https://user-images.githubusercontent.com/13140497/36118894-a2859686-1025-11e8-8f85-125deb6762a9.png)
Result from diskLayout script.

My user just have sudo permissions and isn't a system admin. I don't know if this is a expected behaviour and if it is, how it's supposed to execute the program to get the desired information?

**Comment by sebhildebrandt** [comment]
@calvingerling Unfortunately the underlying commands here (for linux) NEED admin privileges. I did not found other ways to get proper information for DiskLayout and MemLayout. There are also other functions (for other OS platforms) that will need admin rights. But if you have any other suggestion, I would be happy to hear about that.
