### ISSUE TITLE
si.processes(data => console.log(data)) gives TypeError: Incorrect value of args option

### ISSUE THREAD

**Issue by mc6415** [sebhildebrandt/systeminformation#113]
### Issue Type

* [ ] Bug
* [ ] Feature Request
* [x] Question

### Expected behavior 

I want to get a list of processes using the processes function.

### Actual behavior

I get a TypeError.

TypeError: Incorrect value of args option
    at Object.exports.execFile (child_process.js:201:11)
    at exports.exec (child_process.js:142:18)
    at process.nextTick (C:\WINDOWS\system32\node_modules\systeminformation\lib\processes.js:496:11)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

### Steps to reproduce the problem

I was attempting to do si.processes(data => console.log(data)) as a test when this cropped up.

### Specifications 

- package version: latest
- operating system: Windows 10
- hardware:

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
Will check it later this evening

**Comment by BethanyBerkowitz** [comment]
I also got this error today on Windows 10 for `si.processes(cb)` and `si.disklayout(cb)` but not with `si.mem(cb)` or `si.fsSize(cb)`.  I had no trouble with anything on Mac.

**Comment by sebhildebrandt** [comment]
Sorry! My fault! Bug should be fixed now (v 3.37.4)
