### ISSUE TITLE
[*nix] Use 'ip' instead of the deprecated 'ifconfig'

### ISSUE THREAD

**Issue by GitSquared** [sebhildebrandt/systeminformation#114]
### Issue Type

* [X] Feature Request

### Specifications 

- package version: Latest (3.37.4)
- operating system: Debian 9
- hardware: --

### Problem and possible solution

SI's [network.js](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/network.js) uses the `ifconfig` command on *nix systems. `ifconfig` is [deprecated](https://serverfault.com/questions/633087/where-is-the-statement-of-deprecation-of-ifconfig-on-linux) and not installed by default on most major distros, where it was replaced by `ip`.

On my Debian machine, this causes errors in the console (_'/sbin/ifconfig: not found'_), and no mac addresses are found in the output of `si.networkInterfaces(...)`.

EDIT: Proposed fix in #115

**Comment by sebhildebrandt** [comment]
Just pushed the fix - version 3.37.5. Thank you again!
