### ISSUE TITLE
Error: Cannot find module while browserify babelify

### ISSUE THREAD

**Issue by rip3rs** [sebhildebrandt/systeminformation#117]
### Issue Type

* [ ] Bug
* [ ] Feature Request
* [x ] Question

### Expected behavior 

- When doing a gulp browserify, it should get all the dependencies from systeminformation.

I read the known issues and say the temperature part. However that is not the problem here.

by doing browserify it is trying load all of it's dependencies.

### Actual behavior

- missing modules:
 ` Error: Cannot find module 'osx-temperature-sensor' from '/Users/yyy/electron/node_modules/systeminformation/lib`
  After independently installing this module via npm I get another missing module:
  `Error: Cannot find module '../build/Release/smc' from '/Users/yyy/electron/node_modules/osx-temperature-sensor/lib'`

### Specifications 

- package version: 
    "osx-temperature-sensor": "^1.0.1"
    "systeminformation": "^3.37.7"
- operating system: MacOS Sierra
- hardware: MacBook Pro

### Problem and possible solution
shim systeminformation section from browserify

**Comment by sebhildebrandt** [comment]
Hi @rip3rs,

as mentioned in the `README.md` I had good reasons to not explicitly include this external dependency for osx temperatures out of the box. 

I just again testet to install systeminformation (with npm), then call `si.cpuTemperature()` not getting any errors (but of  course no valid values). Then I installed `osx-temperature-sensor` with npm and called `si.cpuTemperature()` again with now correct values. 

My suggestion is that your installation of `osx-temperature-sensor` has thrown some errors during installation. As there is some C code involved this happens e.g. if you do not have xcode command line tools installed. Therefore the sac in the /build folder seams not to be present.
