### ISSUE TITLE
Switching Network Interface Doesn't Change Default Iface

### ISSUE THREAD

**Issue by sfraise** [sebhildebrandt/systeminformation#120]
### Issue Type

* [X ] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
When going from Ethernet to WiFi I would expect the default or current iface to update to show the iface now being used.
- 
- 
- 

### Actual behavior
The original iface at time of app start remains the default.  Restarting the application will show the new iface correctly however I can't find a way to get it to recognize a change without restarting the app.
- 
- 
- 

### Steps to reproduce the problem
I currently have the network stats running on a 15 second interval.  If I start the app connected via ethernet and then remove the ethernet cable to switch to wifi ethernet will remain the default iface and simply start showing 0 RX/TX and -1 RX/TX per second.

This is also true if I start the application using wifi and then plugging in the ethernet cable to switch to ethernet, wifi will remain as the default connection until app restart.
-
-
-

### Specifications 
- Node Version: 8.10.0
- package version: 3.37.7
- operating system: Windows 10
- hardware: HP DV7 i7 8Gb Ram

### Problem and possible solution
Problem is I need the current iface to switch to the other iface without having to restart the application.

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
Hi @sfraise 
I know where the problem is inside systeminformation and I will try to think of a solution for it ... please give me some days to find a proper solution.

**Comment by sfraise** [comment]
No rush from me, I'm working around it by just calling networkStats from the networkInterfaces only on ifaces with a mac address.  Good enough for what I need for now.

**Comment by sebhildebrandt** [comment]
Now optimised `networkDefaultInterface()` detection - released new version 3.37.8 right now

**Comment by sebhildebrandt** [comment]
@sfraise : Maybe you can test if this works on your side and give a short feedback. Thank you in advance!
