### ISSUE TITLE
networkStats

### ISSUE THREAD

**Issue by codeniner** [sebhildebrandt/systeminformation#125]
### Issue Type

* [X ] Question

### Expected behavior 

Is there a way to get networkStats() for all interfaces at once?

**Comment by sebhildebrandt** [comment]
not yet but this is an interesting enhancement. I will have a look on it.

**Comment by sebhildebrandt** [comment]
@codeniner : as this needs a change in the interface, I will add this in version 4.0. I plan to finish that in the next few weeks.

**Comment by sebhildebrandt** [comment]
Should work now. Attention breaking change. `networkStats()` returns an array now. To get stats for all network interfaces just call `networkInterfaces('*')`. Version 4.0.0 published
