### ISSUE TITLE
Flow and TypeScript definitions

### ISSUE THREAD

**Issue by jorgegonzalez** [sebhildebrandt/systeminformation#128]
### Issue Type

* [ ] Bug
* [x] Feature Request
* [ ] Question

It would be awesome if `systeminformation` provided Flow and/or TypeScript definitions. If you are not interested in creating these yourself, would you accept a PR implementing these?

**Comment by Chifilly** [comment]
You can get TypeScript definitions from `@types/systeminformation` ([Repository](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/systeminformation), [NPM](https://www.npmjs.com/package/@types/systeminformation))

**Comment by jorgegonzalez** [comment]
@Chifilly wasn’t aware thanks!

**Comment by woodgear** [comment]
@types/systeminformation doesn't update for a year  is there somebody update the define fine or we should do by ourself ? @Chifilly

**Comment by sebhildebrandt** [comment]
Will update it this weekend ...
