### ISSUE TITLE
si.system(cb).sku does not seem to be working.

### ISSUE THREAD

**Issue by GrumpyCrouton** [sebhildebrandt/systeminformation#129]
### Issue Type

* [x] Bug

### Expected behavior 

- Model HP 20-c013w (Windows) a SKU of V8N95AA#ABA.

### Actual behavior

- si.system(cb).sku returns nothing on any computer I have tried it on.

### Specifications 

- package version: latest
- operating system: Windows 10
- hardware: HP 20-c013w

**Comment by sebhildebrandt** [comment]
Hi @GrumpyCrouton 

can you provide the result of the following command (command line):

```
wmic csproduct get /value
```

Thank you in advance!

**Comment by GrumpyCrouton** [comment]
It seems that SKUNumber is always blank, no matter on which computer I run it on.

I am developing a new version of a program that I made a while ago with HTA and Batch, but developing it as an electron application using node.js. In my database for my old program, I have the system sku's of thousands of computers, all of which have been retrieved by the following wmic command:

`wmic /namespace:\\root\wmi path MS_SystemInformation get SystemSKU /value`

Using si.systeminfo(), none of the computers I have tried (10-15 computers) that all have SKU's from my old program, all generate nothing for the SKU in my new program using csproduct.

**Comment by sebhildebrandt** [comment]
OK, thank you! I will think, how I can improve the code to also get the SKU. Please give me a few days, because I am busy right now ...

**Comment by GrumpyCrouton** [comment]
Unfortunately I did not have the luxury of waiting for a fix, so I fixed it myself and made a pull request @sebhildebrandt  :)

**Comment by sebhildebrandt** [comment]
Fixed ... merged your pull request
