### ISSUE TITLE
EPERM error 

### ISSUE THREAD

**Issue by leonardodalcin** [sebhildebrandt/systeminformation#131]
### Issue Type

* [ X ] Bug
* [ ] Feature Request
* [ ] Question

I am getting some permission errors with `systeminformation`. Is this a known issue?
node: v8.2.1
systeminformation: 3.37.9
<img width="812" alt="screen shot 2018-05-25 at 1 55 04 pm" src="https://user-images.githubusercontent.com/15152138/40556564-83e33f46-6023-11e8-95a3-cabceaef7a6f.png">
<img width="821" alt="screen shot 2018-05-25 at 1 57 23 pm" src="https://user-images.githubusercontent.com/15152138/40556600-a560501e-6023-11e8-9b02-0553eb8f3a88.png">

**Comment by sebhildebrandt** [comment]
How exactly are you calling your code? Directly from command line or maybe pm2 or from within an electron app? As this is not yet a known issue, maybe this context could be helpful for determine the reason for this error. Can you give a little bit more information on your calling context? Maybe it also would be helpful to try to call `WMIC` directly from commandline and see if the user can run this command. Thank you in advance.

**Comment by leonardodalcin** [comment]
It is within an Electron App.
Running `WMIC` directly on Windows CLI works fine.
My application runs fine for some time making those library requests. Suddenly i get the `EPERM` error and it crashes. This only happens on one server and I cannot reproduce on others.

**Comment by sebhildebrandt** [comment]
I now encapsulated all WMIC calls in `try ... catch` blocks to avoid any crashing (published as version 3.41.4). Anyway the behaviour is strange ... can you test it once again with the version you have installed. What do you mean with 'runs fine for some time ... Suddenly I get the EPERM error'?

**Comment by leonardodalcin** [comment]
I make those calls with a frequency of 1 minute. The app runs fine for a undetermined period of time and then i get an EPERM. I will try to update the `systeminformantion` and see how it goes.

**Comment by sebhildebrandt** [comment]
Closing it for now. But I will make further investigations what the reason could be.
