### ISSUE TITLE
Wrong information about processes

### ISSUE THREAD

**Issue by coderaiser** [sebhildebrandt/systeminformation#133]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

```js
> const si = require('systeminformation');
> const ps = await si.processes();
> ps.list.filter((a) => a.pid === 774))
// returns
[{ 
       pid: 774,
       parentPid: 1,
       name: 'node',
       pcpu: 0.0005601836671352227,
       pcpuu: 0.00039621942534122644,
       pcpus: 0.0001639642417939963,
       pmem: 1.4,
       priority: 19,
       mem_vsz: 1194952,
       mem_rss: 14408,
       nice: 0,
       started: '',
       state: 'unknown',
       tty: 'S',
       user: '?',
       command: 'node /home/coderaiser/status-io/bin/status.js'
}]
```

### Actual behavior
```js
> const si = require('systeminformation');
> const ps = await si.processes();
> ps.list.filter((a) => a.pid === 774))
// returns
[{ 
       pid: 774,
       parentPid: 1,
       name: 'coderaiser',
       pcpu: 0.0005601836671352227,
       pcpuu: 0.00039621942534122644,
       pcpus: 0.0001639642417939963,
       pmem: 1.4,
       priority: 19,
       mem_vsz: 1194952,
       mem_rss: 14408,
       nice: 0,
       started: '',
       state: 'unknown',
       tty: 'S',
       user: '?',
       command: 'coderaiser' 
}]
```

When I use `ps` I see:

```sh
# ps aux| grep 774
coderai+   774  0.0  1.4 1194952 14408 ?       Ssl  May01   0:16 node /home/coderaiser/status-io/bin/status.js
```

### Steps to reproduce the problem

Call `si.processes`.

### Specifications 

- package version: `3.42.0`
- operating system: `Linux cloudcmd.io 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- hardware:

### Problem and possible solution

Problem is `name` and `command` is incorrect, looks like [processes](https://github.com/sebhildebrandt/systeminformation/blob/dc1d6e5035c19860e9ba34f6fbc4f2c60b39a737/lib/processes.js#L93) should be fixed.

**Comment by sebhildebrandt** [comment]
I made some corrections to the parsing functionality. This should solve the problem with shifted (and therefore incorrect) values.  @coderaiser @willvincent can you test it on your side?

**Comment by coderaiser** [comment]
Looks like everything works good, I used `systeminformation` in [psedit v1.2.0](https://github.com/coderaiser/node-psedit/releases/tag/v1.2.0). Thank you :).

**Comment by sebhildebrandt** [comment]
Thank you for your feedback!
