### ISSUE TITLE
cb is not defined

### ISSUE THREAD

**Issue by dxf** [sebhildebrandt/systeminformation#134]
### Issue Type

* [x ] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

It spits out the kernel version

### Actual behavior

cb is not defined- 
- 
- 

### Steps to reproduce the problem

run this code:

```const si = require('systeminformation')
si.osInfo.kernel(cb)
	.then(data => console.log(data))```
### Specifications 

- package version: l8est
- operating system: w10
- hardware: i3 4130, 4gb ram, 500gb hdd

### Problem and possible solution

Just make it spit out the kernel version

**Comment by sebhildebrandt** [comment]
Actually this is not a bug ... If you just need the kernel you need to do it like that (see `README.md`):

```
si.osInfo(cb)
	.then(data => console.log(data.kernel))
```
