### ISSUE TITLE
CPU temps incorrect

### ISSUE THREAD

**Issue by moriczgergo** [sebhildebrandt/systeminformation#135]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- `cpuTemperature()` would show accurate CPU temperature data.

### Actual behavior

- `cpuTemperature()` returns incorrect data.

### Steps to reproduce the problem

Not sure about what to put here... but here's the code:

```js
si.cpuTemperature().then(function(data) {
    console.log(data); // {
}).catch(function(err) {
    console.error(err);
});
```

### Specifications 

- package version: 3.42.0
- operating system: Microsoft Windows 10 Enterprise 10.0.17134.48
- hardware: https://gist.github.com/moriczgergo/37631c53698174d1dadac912179edf4b

### Problem and possible solution

 1. My processor has 4 cores: wmic & systeminformation only reports 2.
 2. The 2 cores are always at `27.8` and `29.8`.
     ```json
     {"main":28.8,"cores":[27.8,29.8],"max":29.8}
     ```
 3. AIDA and CAM reports fine:
    ![screenshot](https://i.gyazo.com/a60360b167436d81b7146b58502d0040.png)

Here's `wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CriticalTripPoint,CurrentTemperature /value` output:

```


CriticalTripPoint=3922
CurrentTemperature=3010


CriticalTripPoint=3922
CurrentTemperature=3030



```

**Comment by sebhildebrandt** [comment]
I am relying here on Windows and the WMIC result you posted is actually 27.85° / 29.85° C (WMIC-Value / 10 - 273,15)

At the moment I did not find any hardware independent (windows build-in) solution to get more reliable temperature information. If you have any ideas, it would be great to lern more about that.

**Comment by sebhildebrandt** [comment]
Closing that for now, as i cannot find any alternatives ... but still: If you have any idea on that, please just post it here ...

**Comment by sebhildebrandt** [comment]
> Same issue with the "13th Gen Intel(R) Core(TM) i9-13950HX". I have 32 cores but only two will show up, the values will never change: { main: 36.4, cores: [ 45, 27.8 ], max: 45 }. One thing I noticed is that the "os" library will see all my cores -- sadly does not show the temp

Which OS?
