### ISSUE TITLE
Services - toLowerCase doesnt work with Mac and Linux processes

### ISSUE THREAD

**Issue by mpathy** [sebhildebrandt/systeminformation#139]
### Issue Type

* [X] Bug

### Expected behavior 

- Want to search for "TeamViewer" for example - service is written with capital T and V 

### Actual behavior

- Searches for "teamviewer" - no process found

### Steps to reproduce the problem

- Start a process which is not lowercase

### Problem and possible solution

The parameter shouldnt be parsed trough toLowerCase, but kept as is.

Maybe at Windows it doesnt matter or has to be lowercase - I dont know - but at Linux and Mac it can be possible to have capital letters.

_If you want to include another feature, that I came up with while writing.. Allow "grouping" a service, like "Teamviewer:teamviewer,TeamViewer,teamviewer.exe" or something like that. If it finds one of the said names, the function uses the name before the : and displays the rest of the data. But thats an optional idea._

**Comment by sebhildebrandt** [comment]
Problem solved, version 3.42.3 just published. I need to think about the additional feature ... but I am not clear if I clearly understand your proposal. Maybe you like to describe it a little bit more ... closing the issue for now.
