### ISSUE TITLE
si.currentLoad race conditions?

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#14]
Hi Sebastian,

Before I start posting massive debug log output, are you aware of any potential race issues with this (or any other) si call?

The basic conditions & sequence are as follows:

1. backend https server (Node.js, express.js) periodically (every 5 seconds) drive si.currentLoad using promise idiom (see below).
2. client 1 web browser connects
3. data pushed back to client 1 looks correct
4. client 2 web browser connects
5. data pushed back to client 2 looks incorrect

```
si.currentLoad().then(data => parseCpuLoadInfo('cpu_util', data, cmdProgress, responder))      
                         .catch(error => logMsg('info', 'si.currentLoad error=' + error));
```
When item 4 above says "incorrect", I mean that the several metrics returned by this call (currentload, currentload_system, currentload_user, currentload_nice) are either null or incoherent, e.g., the client 1 data shows currentload of 1.004 but 5 seconds later currentload for client 2 shows 100. Note that there is nothing else running on the node. It might of some interest to note that the avgload property never shows a null or incoherent value, even if the other properties in the object do.

I realize that this could very well be my problem but, for the moment I don't see what I'm doing that might be causing this.

So I'd be grateful for any light you can shed on this.

Thanks.

-Paul

**Comment by sebhildebrandt** [comment]
Thank you for reporting this. I will have a look on the issue the next days. 

Regards

Sebastian

**Comment by sebhildebrandt** [comment]
Is it possible to send me the full source code (or make a gist) that I can have a look on and test/reproduce it? I am not really sure, if I understand the problem... would be very helpful. 

Thank you in advance.

**Comment by moonlitSpider** [comment]
Hi Sebastian,

I very much don't want to waste your time with something that may prove to be of my making. That said, I suspect you understand better than me issues concerning promises & race conditions. 

Let me see about creating a gist and how much of the code I'd need to include. 

If you prefer, I could send you the full source, but would want to do that "out of band" (so to speak). You'd need to give me an e-mail @ or some other private location.

Thanks.

**Comment by sebhildebrandt** [comment]
Not sure, where the problem is, so it would help to have some code to reproduce it ;-)
You can find my email on my website in the footer (which you should find in my github profile, right?)

I guess having YOUR and MY code side by side would make it easier to identify the problem.
Thank you.

**Comment by paul-bell** [comment]
Unfortunately, the code in question is part of a considerably larger system
that requires both a client & server piece.

It might be helpful if I try to extract the bare minimum code that is
required. But this could take me several days.

Could we do a WebEx wherein you could see what's happening and we could
look at the code together?

Thanks for your help.

-Paul

**Comment by sebhildebrandt** [comment]
OK, no stress ... lets do it this way: I will try to find the problem within my code ... I will come back to you in the next few days. We will find a solution! All good!

**Comment by sebhildebrandt** [comment]
... means, you do not have to extract a bare minimum code ;-)

**Comment by paul-bell** [comment]
You are too kind, sir!

But I will work on it at my end as well.

Thanks.

**Comment by paul-bell** [comment]
Hi Sebastian,

I may have reproduced it in a very simple case.

More shortly.

-Paul

**Comment by paul-bell** [comment]
Hi Sebastian,

I realize we have time zone skew to deal with here. So I've published the
gist here:
https://gist.github.com/moonlitSpider/1de196234568babd4d7ecc90f98b4367 and
will look for posts from you tomorrow should further explanation be
required.

In summa, you can run this stand-alone node.js program. In so doing you
should start to see null or incoherent data returned by one of the two
timer-driven metric collectors.

Please note, I may be violating some fundamental laws about Node.js and,
frankly, would be happy to learn that this is my error. Please note that
this program is not a wholly faithful reproduction of my production
program. In the latter I start one timer only, but a 2nd client session is
created from a browser. The net effect is that two collectors
(si.currentLoad) and their sub-functions are being driven. In the gist
program I started two timers (setInterval) each of which drives a
collector. Finally, the 2nd collector starts about 10 seconds after the
first.

Output from the program looks like this:

[root@localhost ecxmon]# node --stack_size=8192 ./sirepro.js
2016-11-10T22:26:34.047Z - info: Log level=info
2016-11-10T22:26:38.076Z - info: In parser with CPU
data={"avgload":0,"currentload":1.8587817889271392,"currentload_user":1.2852628011474136,"currentload_nice":0.00000304958451232745,"currentload_system":0.5735159381952135}
and cmdProgress={"entity":"node","sid":1,"collNum":1}
2016-11-10T22:26:38.077Z - info: In
responder={"entity":"node","sid":1,"collNum":1}
2016-11-10T22:26:42.076Z - info: In parser with CPU
data={"avgload":0,"currentload":0.6273525721455459,"currentload_user":0.37641154328732745,"currentload_nice":0,"currentload_system":0.2509410288582183}
and cmdProgress={"entity":"node","sid":2,"collNum":1}
2016-11-10T22:26:42.076Z - info: In
responder={"entity":"node","sid":2,"collNum":1}
2016-11-10T22:26:46.071Z - info: Starting 2nd collector
2016-11-10T22:26:46.078Z - info: In parser with CPU
data={"avgload":0,"currentload":0.7518796992481203,"currentload_user":0.5012531328320802,"currentload_nice":0,"currentload_system":0.2506265664160401}
and cmdProgress={"entity":"node","sid":3,"collNum":1}
2016-11-10T22:26:46.079Z - info: In
responder={"entity":"node","sid":3,"collNum":1}
2016-11-10T22:26:50.082Z - info: In parser with CPU
data={"avgload":0,"currentload":0.8771929824561403,"currentload_user":0.37593984962406013,"currentload_nice":0,"currentload_system":0.5012531328320802}
and cmdProgress={"entity":"node","sid":4,"collNum":2}
2016-11-10T22:26:50.082Z - info: In
responder={"entity":"node","sid":4,"collNum":2}
*2016-11-10T22:26:50.083Z - info: In parser with CPU
data={"avgload":0,"currentload":null,"currentload_user":null,"currentload_nice":null,"currentload_system":null}
and cmdProgress={"entity":"node","sid":5,"collNum":1}*
2016-11-10T22:26:50.083Z - info: In
responder={"entity":"node","sid":5,"collNum":1}
2016-11-10T22:26:54.083Z - info: In parser with CPU
data={"avgload":0,"currentload":0.8793969849246231,"currentload_user":0.5025125628140703,"currentload_nice":0,"currentload_system":0.37688442211055273}
and cmdProgress={"entity":"node","sid":6,"collNum":2}
2016-11-10T22:26:54.083Z - info: In
responder={"entity":"node","sid":6,"collNum":2}
2016-11-10T22:26:54.084Z - info: In parser with CPU
data={"avgload":0,"currentload":null,"currentload_user":null,"currentload_nice":null,"currentload_system":null}
and cmdProgress={"entity":"node","sid":7,"collNum":1}
2016-11-10T22:26:54.084Z - info: In
responder={"entity":"node","sid":7,"collNum":1}

Thanks again.

-Paul

**Comment by moonlitSpider** [comment]
2016-11-10T22:26:50.083Z - info: In parser with CPU data={"avgload":0,"currentload":**null**,"currentload_user":**null**,"currentload_nice":**null,**"currentload_system":**null**}
and cmdProgress={"entity":"node","sid":5,"collNum":1}

**Comment by sebhildebrandt** [comment]
Thank you for your code! Helped a lot to reproduce the problem. I think I know, where the problem is. Will give you an answer on that letter today.

**Comment by sebhildebrandt** [comment]
Hi Paul,

you were completely right, there was a race condition problem! The problem is the following: I had to rewrite the currentLoad function for Linux, because the sum of cpu utilization with ```ps``` did not returned a correct value. So I switched to ```/proc/stats``` which is anyway the better approach in linux/unix. This is returning the amount of time the CPU has spent performing different kinds of work since startup. So when calculating the ```currentLoad```, I need a reference point - something like: "last time overall cpu usage was like that, and now the it is like this". This lets me calculate the most recent CPU usage. So each time you call currentLoad, I am refreshing my reference point and the next time you call it, you get the usage between those two calls. Therefore, when you have call currentLoad from two different points of your app in a very, very short time, the calculation gets wired. 

So I now debounced it, testet it and it works pretty fine now. Sorry for the inconvenience and once again thank you for helping improving this package!

But I anyway have one suggestion:
I would only start one singe ```setTimeout``` function for getting the current load, then store the values in a variable that you then can read from different places (whenever you want) within your code... 

So a wraper could be something like:

```
let _currentLoad = {}

setInterval(updateCurrentLoad, 2000)

function updateCurrentLoad() {
	si.currentLoad().then(data => {
		_currentLoad = data;
	});
}
		
function getCurrentLoad() {
	return _currentLoad;
}
```
The ```getCurrentLoad```-function returns always the most up to date currentLoad values.

**Comment by moonlitSpider** [comment]
Hi Sebastian,

Terrific; thank you very much!

I think I understand your explanation as to cause.

In re my use of 2 setInterval calls, in my "production" code (as opposed to the gist code), there is only a single timer running. So I don't expect any anomalous behavior in that regard.

Speaking of which, I see that you've posted v3.9.0. I will download and test it directly.

Thanks again.

-Paul

**Comment by moonlitSpider** [comment]
Hi Sebastian,

Tested with production version of code (multiple GUI sessions). Looks real good.

Question: would you expect any other si api calls to exhibit this race condition problem? 

Thanks.

-Paul

**Comment by sebhildebrandt** [comment]
I guess there is at least one more possible place where race condition problem can rise. As I know am aware of it, I will check it.

**Comment by sebhildebrandt** [comment]
Hi Paul,

I now checkt all possible areas, where I expected same race condition problems. I just fixed all of them (in v3.10.1). Now it should run without any side effects, when calling same function in a very small period of time twice. 

Thank you for pointing me to that specific problem.

**Comment by moonlitSpider** [comment]
That's great news; thanks, Sebastian.

As I continue to develop my monitoring program (which, pretty obviously, relies in large part on systeminformation), I expect to make significant use of its container APIs. I might also use some of its "networking" APIs.

Thanks again.

-Paul

**Comment by sebhildebrandt** [comment]
Curious, what that one looks like. Will it be open source, a (payed) service or just used internally?

If you have any additional ideas or suggestions for the systeminformation package, please let me know.

**Comment by moonlitSpider** [comment]
Well, at the moment it has no look, per se. I mean that it's a back-end component only without a front-end GUI. Also, at the outset, it will probably be used internally. 

I will definitely contact you re additional suggestions/enhancements for systeminformation. I've a long-standing interest (and some background) in monitoring software and remain quite grateful for the work you've done on this.

-Paul

**Comment by sebhildebrandt** [comment]
Fine! Good luck for that. 
Suggestions / enhancements: to avoid making all communication via github, you can always contact me also via mail (as described above)

**Comment by moonlitSpider** [comment]
Will do, thanks.
