### ISSUE TITLE
Cannot see if block device is SSD or HDD on Windows

### ISSUE THREAD

**Issue by mastercoms** [sebhildebrandt/systeminformation#141]
### Issue Type

* [x] Feature Request

### Expected behavior 

`si.blockDevices()[0].physical` returns `HDD` or `SSD` based on its type on Windows, like on Linux.

### Actual behavior

`si.blockDevices()[0].physical` returns `HDD` for all local disks on Windows.

### Steps to reproduce the problem

Get `si.blockDevices()[0].physical`, see that it returns `HDD` instead of `SSD` like on Linux.

### Specifications 

- package version: ^3.42.4
- operating system: Windows
- hardware: HFS500G32TND-N1A2A

### Problem and possible solution

I'm not entirely familiar with WMI or how systeminformation accesses data from Windows, but some searching has shown me that a property called `MediaType` may return HDD or SSD as expected.

**Comment by sebhildebrandt** [comment]
Trank you for your suggestion. Will review it later this week.

**Comment by fabiaant** [comment]
Hi, I was quite interested in seeing this issue resolved, so I went looking for a solution as well. I found some information that is probably quite useful here: https://www.pdq.com/blog/determining-disk-type-with-get-physicaldisk/

**Comment by sebhildebrandt** [comment]
@fabiaant thank you! Will have a look at it!

**Comment by fabiaant** [comment]
That information might not actually be enough to fix this, but I'm fairly sure it can improve the si.diskLayout() function, especially considering this line https://github.com/sebhildebrandt/systeminformation/blob/6b0d90062ccf1527700c53f298184c57bd6e67da/lib/filesystem.js#L758

**Comment by sebhildebrandt** [comment]
Hi, so I now went through it and found a solution. On windows I only get reliable information or the drive type with Windows 8 and above (using a powershell command). This is now implemented in the latest version (3.45.3). 

One more thing: the type of the device is only correct when calling `si.diskLayout()`, for blockdevices (logical disks) on windows you only get back `local` (or HDD)...
