### ISSUE TITLE
networkStats always return -1 on Windows Server 2016 standard

### ISSUE THREAD

**Issue by rajamandava** [sebhildebrandt/systeminformation#142]
### Issue Type

* [ *] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
Return network stats for given network interface 
- 
- 
- 

### Actual behavior
The network stats return -1 when polled at continuous intervals of 10 seconds
- 
- 
- 

### Steps to reproduce the problem
I am using module on Windows Server 2016 standard. I have 6 ethernet ports but only one is connected. When I run si.networkInterfaces, it returns the interface name and ip address. But when I use si.networkStats with the same interface name, it returns -1 for both rx and tx continuously although I poll at every 10 seconds. Also the operstate is returned as 'unknown". Any clue on why it is not working ? I was running a video in back ground so there are positive stats to capture and windows resource monitor shows positive stats.

The interface name is 'OnboardLOM1'. 

I have tested same thing with Windows 10 and it was working fine.
-
-
-

### Specifications 

- package version: 3.42.4
- operating system: Windows Server 2016 Standard
- hardware: Intel Silver 4110 CPU

### Problem and possible solution
Refer to steps to reproduce problem on problem details and no idea on solution.
If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
@rajamandava 
Can you provide the output of 

```
wmic nic get MACAddress, name, NetEnabled /value
```

and

```
wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPersec,BytesSentPersec,BytesTotalPersec /value
```

(for this last one please provide it TWO times with aprox 1 minute in between)
on your Win 7 machine?

The specific network interface you try to track is which one?

**Comment by sebhildebrandt** [comment]
Found the problem. Will provide a buggies soon.

**Comment by sebhildebrandt** [comment]
Sorry for the delay! I fixed it and have a working solution now, will add it to version 4.0 (will be released within the next 2 weeks)

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
