### ISSUE TITLE
networkStats always return -1 on Windows 7

### ISSUE THREAD

**Issue by starsoftmongolia** [sebhildebrandt/systeminformation#143]
### Issue Type

* [*] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
Return network stats for given network interface

### Actual behavior

The network stats always return -1 on Windows 7 
- Tested on several PCs
- Tested on Windows 7 Ultimate x86 and amd64 version, same error

### Steps to reproduce the problem

`si.networkInterfaceDefault(function(ethname){
        si.networkStats(ethname, function(data) {
            console.log('Network Interface Stats (en1):');
            console.log('- is up: ' + data.operstate);
            console.log('- RX bytes overall: ' + data.rx);
            console.log('- TX bytes overall: ' + data.tx);
            console.log('- RX bytes/sec: ' + data.rx_sec);
            console.log('- TX bytes/sec: ' + data.tx_sec);`

- And result of above lines are :
- { iface: "Wireless Network Connection", operstate: 'unknown', rx:0, tx:0, rx_sec: -1, tx_sec: -1, ms:0 }

### Specifications 

- package version: 3.42.4
- operating system: Windows 7
- hardware: Toshiba LX835, Dell Vostro 2421, several Virtual machines

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
Hi @starsoftmongolia , the first time you are calling one of this functions, you will get -1 for transfer rates. The second time, you should then get statistics based on the time between the two calls …

So basically, if you e.g. need a values for network stats every second, your code should look like this:

```
const si = require('systeminformation');

setInterval(function() {
	si.networkStats().then(data => {
	    console.log(data);
	})
}, 1000)
```

Please let me know, if you then get proper results.

**Comment by starsoftmongolia** [comment]
I tried above above code before, result is same.

**Comment by starsoftmongolia** [comment]
here is video : 
https://www.youtube.com/watch?v=LyIyAu-2vKQ

**Comment by sebhildebrandt** [comment]
@starsoftmongolia 
Can you provide the output of 

```
wmic nic get MACAddress, name, NetEnabled /value
```

and

```
wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPersec,BytesSentPersec,BytesTotalPersec /value
```

(for this last one please provide it TWO times with aprox 1 minute in between)
on your Win 7 machine?

The specific network interface you try to track is which one?

**Comment by starsoftmongolia** [comment]
Here is the result : 

C:\>wmic nic get MACAddress, name, NetEnabled /value


MACAddress=
Name=WAN Miniport (SSTP)
NetEnabled=


MACAddress=
Name=WAN Miniport (IKEv2)
NetEnabled=


MACAddress=
Name=WAN Miniport (L2TP)
NetEnabled=


MACAddress=
Name=WAN Miniport (PPTP)
NetEnabled=


MACAddress=
Name=WAN Miniport (PPPOE)
NetEnabled=


MACAddress=
Name=WAN Miniport (IPv6)
NetEnabled=


MACAddress=
Name=WAN Miniport (Network Monitor)
NetEnabled=


MACAddress=
Name=WAN Miniport (IP)
NetEnabled=


MACAddress=64:5A:04:51:A5:56
Name=Bluetooth Device (Personal Area Network)
NetEnabled=FALSE


MACAddress=
Name=RAS Async Adapter
NetEnabled=


MACAddress=
Name=Microsoft ISATAP Adapter
NetEnabled=


MACAddress=78:45:C4:EC:63:79
Name=Realtek PCIe FE Family Controller
NetEnabled=FALSE


MACAddress=
Name=Teredo Tunneling Pseudo-Interface
NetEnabled=


MACAddress=64:5A:04:51:A5:55
Name=Dell Wireless 1705 802.11b/g/n (2.4GHZ)
NetEnabled=TRUE


MACAddress=
Name=Microsoft ISATAP Adapter
NetEnabled=


MACAddress=
Name=Microsoft ISATAP Adapter
NetEnabled=





C:\>wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPer
sec,BytesSentPersec,BytesTotalPersec /value


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Realtek PCIe FE Family Controller


BytesReceivedPersec=20764502
BytesSentPersec=976725
BytesTotalPersec=21741227
Name=Dell Wireless 1705 802.11b_g_n [2.4GHZ]


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=isatap.{A4D8F4CE-9F75-400C-9D18-AF5D8F4FF75A}


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Teredo Tunneling Pseudo-Interface



C:\>wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPe
sec,BytesSentPersec,BytesTotalPersec /value


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Realtek PCIe FE Family Controller


BytesReceivedPersec=28446539
BytesSentPersec=1282724
BytesTotalPersec=29729263
Name=Dell Wireless 1705 802.11b_g_n [2.4GHZ]


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=isatap.{A4D8F4CE-9F75-400C-9D18-AF5D8F4FF75A}


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Teredo Tunneling Pseudo-Interface

**Comment by sebhildebrandt** [comment]
Thank you, and this: `Dell Wireless 1705 802.11b/g/n (2.4GHZ)` is actually the network interface you are trying to tackle?

**Comment by starsoftmongolia** [comment]
Yes, in the video library detects it Wireless Network Connection. May be it detects wrong default interface name ?

**Comment by sebhildebrandt** [comment]
Well @starsoftmongolia  ... can you do me one more favour: please provide the output of `os.networkInterfaces()` on this machine ...

**Comment by starsoftmongolia** [comment]
os interfaces =  { 'Wireless Network Connection':
   [ { address: 'fe80::d014:2277:1162:1b44',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '64:5a:04:51:a5:55',
       scopeid: 12,
       internal: false,
       cidr: 'fe80::d014:2277:1162:1b44/64' },
     { address: '192.168.2.104',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: '64:5a:04:51:a5:55',
       internal: false,
       cidr: '192.168.2.104/24' } ],
  'Loopback Pseudo-Interface 1':
   [ { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true,
       cidr: '::1/128' },
     { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true,
       cidr: '127.0.0.1/8' } ] }

**Comment by sebhildebrandt** [comment]
@starsoftmongolia: perfect, thank you! now it is quite clear ... ;-)
Please give me some days to provide a bugfix ... quite busy right now ..

**Comment by starsoftmongolia** [comment]
Do you have any news about this problem ? Still working or you are busy ?

**Comment by sebhildebrandt** [comment]
Sorry for the delay! I fixed it and have a working solution now, will add it to version 4.0 (will be released within the next 2 weeks)

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
