### ISSUE TITLE
Laptop battery not detected

### ISSUE THREAD

**Issue by GitSquared** [sebhildebrandt/systeminformation#145]
### Issue Type

* [X] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- get battery information using `systeminformation.battery(callback)`

### Actual behavior

- use the function
- `data.hasbattery` is `false` even tho you're on a laptop and it's running on it
- cry

### Steps to reproduce the problem

```js
const si = require("systeminformation");

si.battery((data) => {
        console.log(data);
});
```

Script result:
```
{ hasbattery: false,
  cyclecount: 0,
  ischarging: false,
  maxcapacity: 0,
  currentcapacity: 0,
  percent: 0,
  acconnected: false }
```
...but battery is plugged in and powering the laptop.

### Specifications 

- package version: Latest (3.42.9
- operating system: Debian 9 "Stretch"
- hardware: Laptop with battery

### Problem and possible solution

I read the thread on #42 and tried running the script with root privileges, but that didn't do it, so i really have no idea what's causing this. I'm going to dig in the code to find how you retrieve this info on linux, maybe i got a missing dependency or something?

**Comment by sebhildebrandt** [comment]
Thank you for your investigation. Will provide a bugfix on Monday. Ok?

**Comment by GitSquared** [comment]
Ok, great! :smiley:

**Comment by sebhildebrandt** [comment]
@GitSquared : Published a fix for that (v3.44.0) and added some more properties for battery (type, model, manufacturer, serial, timeremaining). Can you test it on your side?

**Comment by GitSquared** [comment]
Will test and report back tomorrow. Thanks for pushing the fix.

**Comment by sebhildebrandt** [comment]
If this still does not work, can you please post the contents of the following path on your machine: 

```
ls -lsa /sys/class/power_supply
```

**Comment by GitSquared** [comment]
@sebhildebrandt Sorry for the delay. Everything is working all right! The additional info is great too. Thanks again.
