### ISSUE TITLE
Network Stats Packet Drops/Error

### ISSUE THREAD

**Issue by LiveAction-SunArc-Op** [sebhildebrandt/systeminformation#147]
### Issue Type

* [ ] Bug
* [x] Feature Request
* [ ] Question

### Expected behavior 

-  In Network Status, our team requests to see packet drops in interface. We generate report with current statistics on network interface. It would be good, if we add drops and errors as well

### Specifications 

- operating system: CentOS 7, Ubuntu 16.04, Windows 10, 
- hardware: AWS, VMWare, Desktops

### Problem and possible solution

`netstat -i` produces required output in BASH

**Comment by sebhildebrandt** [comment]
@LiveAction-SunArc-Op :  I started investigation how this can be implemented. There are several ways and I need a litte bit more time to decide which one would be the best to produce consistent outputs across all platforms. Hope to have this implemented next week.

**Comment by LiveAction-SunArc-Op** [comment]
@sebhildebrandt: Thanks, waiting for it.

**Comment by LiveAction-SunArc-Op** [comment]
@sebhildebrandt: Is there any workaround currently, to fetch the packet drops in interface?

**Comment by sebhildebrandt** [comment]
Still working on it ... no workaround yet, sorry

**Comment by sebhildebrandt** [comment]
@LiveAction-SunArc-Op : Thank you for being patient! Started to work on a reliable solution ... hope to get it ready next week!! Should work for Linux, macOS, freeBSD, Windows.

**Comment by sebhildebrandt** [comment]
I have a working solution now, will add it to version 4.0 (will be released within the next 2 weeks)

**Comment by LiveAction-SunArc-Op** [comment]
@sebhildebrandt Thank you and waiting for 4.0

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
