### ISSUE TITLE
[FeatureRequest] Add current speed CPU speed of every single core

### ISSUE THREAD

**Issue by fahu** [sebhildebrandt/systeminformation#149]
### Issue Type

* [ ] Bug
* [x] Feature Request
* [ ] Question

### Desired behavior 
As a developer I would like to be able to retrieve the CPU speed of every single core to be able to work with a more accurate data set.

If desired I would like to contribute to this project and add this feature by myself.

PS: Thanks for the great work! Awesome documentation and very readable and clean code :+1: .

**Comment by sebhildebrandt** [comment]
Great idea! If you don’t mind, I will add it. This changes the result object slightly but I have already an idea ;-)

**Comment by sebhildebrandt** [comment]
Just added speed per CPU core in cpuCurrentspeed(). Version 3.43.0 released

**Comment by fahu** [comment]
Oh wow, this was fast! :+1: 
Thank you very much!
