### ISSUE TITLE
si.services() & si.processLoad() return static data

### ISSUE THREAD

**Issue by Bruniz** [sebhildebrandt/systeminformation#151]
### Issue Type

- [ ] Bug
- [ ] Feature Request
- [x] Question

### Expected behavior 

- si.services('node', 'rethinkdb') called with interval return static data for pcpu, pmem
- si.processLoad('node' 'rethinkdb') called with interval return static data for pcpu, pmem

### Actual behavior

- Calling either methods should return the current values of process pcpu and pmem.

### Steps to reproduce the problem

- Call either methods in an interval and monitor values for changes

### Specifications 

- package version: 3.44.2
- operating system: CentOS7
- hardware:  Dell PowerEdge 1950 Server, Intel(R) Xeon(R) CPU           X5365  @ 3.00GHz

**Comment by sebhildebrandt** [comment]
@Bruniz Thank you for your comment. I need to check this on my machines. Please give me a little time to provide a solution for this.

**Comment by sebhildebrandt** [comment]
OK, I see where the problem is, I started to work on it. Unfortunately it is a little more complicated and will take a few more days to provide a stable version.

**Comment by Bruniz** [comment]
> OK, I see where the problem is, I started to work on it. Unfortunately it is a little more complicated and will take a few more days to provide a stable version.

Is there any update on this?

**Comment by sebhildebrandt** [comment]
I got stuck due to a litte work overload ;-) 

will try to make progress on that this weekend (maybe next) ... thank you for being patient!

**Comment by sebhildebrandt** [comment]
Just published a new version (v3.50.3) that should fix the cpu calculation on linux.
