### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [sebhildebrandt/systeminformation#152]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by sebhildebrandt** [comment]
@mansya never thought of creating a logo for it ... good idea. So I just created on on my own but I guess have already a better idea. Will replace this initial version soon. Anyway: thank you for your offer!!
