### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by digitalnature** [sebhildebrandt/systeminformation#154]
I noticed memory leaks when using this module.

This is the code I have:
```
        const load = await si.currentLoad(),
              processes = await si.processes(),
              mem = await si.mem(),
              du = await si.fsSize(),
              net = await si.networkStats();
```

I send this info with websockets to whoever is connected, then run this function again after 2 seconds.

Basically I'm displaying system info every 2 seconds to server admins that are connected to this app via the browser/ws.

After a few hours of running, the app crashes with heap out of memory errors.

If I remove the code above and send some bogus data instead, the mem leaks is gone

**Comment by sebhildebrandt** [comment]
Can you specify the platform you are running the code?

**Comment by digitalnature** [comment]
Ubuntu Server 18.04/Node 8.10. Happens on Ubuntu 14.04/Node 8.6.0 too. 

Here's a sample script to reproduce the issue:

```
const si = require('systeminformation');

async function getSy(){
  const load = await si.currentLoad(),
        processes = await si.processes(),
        mem = await si.mem(),
        du = await si.fsSize(),
        net = await si.networkStats();
		
  console.log('.');
  setTimeout(getSy, 2000);  
  
}

process.stdin.resume();
getSy();
```

I'm running it with pm2.

`pm2 start script.js`

Then watch the memory usage as it increases over time.

`pm2 list`

**Comment by sebhildebrandt** [comment]
@digitalnature thank you. Will investigate the problem tonight.

**Comment by digitalnature** [comment]
After some more testing, I think the issue is not in your module after all.
There's some memory usage increase when using SI but after some time it stabilizes (at least in the isolated test script).
The weird thing is that if I don't use SI in my app, memory usage increases at a much slower rate...
