### ISSUE TITLE
Swap value incorrect on linux when system lang set to fr_FR.UTF-8

### ISSUE THREAD

**Issue by dorianboulch** [sebhildebrandt/systeminformation#155]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- `si.mem()` should return a correct swap value however the system

### Actual behavior

- `si.mem()` returns an incorrect swap value on a Ubuntu 18 with french language

### Specifications 

- package version: 3.45.5
- operating system: Ubuntu 18

### Problem and possible solution

The output of the `free -b` command with language set to `fr_FR.UTF-8` installed looks like :
```bash
$ free -b
              total       utilisé      libre     partagé tamp/cache   disponible
Mem:    16493608960  8633393152   553746432  1686532096  7306469376  5828517888
Partition d'échange: 12554596352           0 12554596352
```
so the splitting with 
```js
js mem = lines[3].replace(/ +/g, ' ').split(' ');
``` 
doesn't work.

**Comment by sebhildebrandt** [comment]
@dorianboulch : I guess it should be solved now. Version 3.45.6 just published. Can you check it on your side?
