### ISSUE TITLE
getStaticData changes the name of the terminal title on Windows

### ISSUE THREAD

**Issue by renambot-uic** [sebhildebrandt/systeminformation#156]
### Issue Type

* [ x] Bug

### Expected behavior 

- Calling getStaticData should not change the console/terminal name on Windows
 

### Actual behavior

- It changes the name of the terminal to "Windows PowerShell" 
- 
- 

### Steps to reproduce the problem

- call getStaticData
-
-

### Specifications 

- package version:
- operating system:
- hardware:

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
Will try to check it today

**Comment by sebhildebrandt** [comment]
Hi, this change should be just temporarily, because I need also to make a call from within PowerShell. After running the function, the normal terminal title should be back, right?
