### ISSUE TITLE
networkStats does not work as expected on Windows 10

### ISSUE THREAD

**Issue by asokolsky** [sebhildebrandt/systeminformation#159]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
On linux networkStats returns:
{"iface":"wlp2s0","operstate":"up","rx":579044142,"tx":33127758,"rx_sec":238.5321100917431,"tx_sec":283.56964136780647,"ms":2398}

### Actual behavior
On Windows 10 I get
{"operstate":"unknown","rx":0,"tx":0,"rx_sec":-1,"tx_sec":-1,"ms":0}
Repeated calls result in the same behavior.

### Steps to reproduce the problem
Issue a call.
I use [systeminformation-api](https://github.com/asokolsky/systeminformation-api) to issue such calls remotely.

### Specifications 

- package version: 3.45.6
- operating system:
osInfo: 
{"platform":"win32","distro":"Microsoft Windows 10 Pro","release":"10.0.17134","codename":"Microsoft Windows 10 Pro","kernel":"10.0.17134","arch":"x64","hostname":"Duo","logofile":"windows"}
- hardware:
networkInterfaces
[{"iface":"Ethernet 2","ip4":"192.168.1.50","ip6":"","mac":"70:85:c2:66:f8:7b","internal":false},{"iface":"Loopback Pseudo-Interface 1","ip4":"127.0.0.1","ip6":"::1","mac":"00:00:00:00:00:00","internal":true}]

### Problem and possible solution

I would expect the Windows behavior to be the same as on Linux.

**Comment by asokolsky** [comment]
```wmic nic get MACAddress, name, NetEnabled /value```
gives:
```


MACAddress=
Name=Microsoft Kernel Debug Network Adapter
NetEnabled=


MACAddress=
Name=Intel(R) Ethernet Connection (2) I219-V
NetEnabled=FALSE


MACAddress=70:85:C2:66:F8:7B
Name=Intel(R) I211 Gigabit Network Connection
NetEnabled=TRUE


MACAddress=
Name=Intel(R) Dual Band Wireless-AC 3168
NetEnabled=FALSE


MACAddress=
Name=Microsoft Wi-Fi Direct Virtual Adapter
NetEnabled=


MACAddress=
Name=Microsoft Wi-Fi Direct Virtual Adapter
NetEnabled=


MACAddress=
Name=Bluetooth Device (RFCOMM Protocol TDI)
NetEnabled=


MACAddress=
Name=Bluetooth Device (Personal Area Network)
NetEnabled=FALSE


MACAddress=
Name=WAN Miniport (SSTP)
NetEnabled=


MACAddress=
Name=WAN Miniport (IKEv2)
NetEnabled=


MACAddress=
Name=WAN Miniport (L2TP)
NetEnabled=


MACAddress=
Name=WAN Miniport (PPTP)
NetEnabled=


MACAddress=
Name=WAN Miniport (PPPOE)
NetEnabled=


MACAddress=D0:BF:20:52:41:53
Name=WAN Miniport (IP)
NetEnabled=


MACAddress=D0:BF:20:52:41:53
Name=WAN Miniport (IPv6)
NetEnabled=


MACAddress=D4:20:20:52:41:53
Name=WAN Miniport (Network Monitor)
NetEnabled=


```

**Comment by asokolsky** [comment]
```wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPersec,BytesSentPersec,BytesTotalPersec /value```
gives
```


BytesReceivedPersec=35116492436
BytesSentPersec=15575330745
BytesTotalPersec=50691823181
Name=Intel[R] I211 Gigabit Network Connection


```

**Comment by sebhildebrandt** [comment]
Yes this is a known issue. I am already working on a fix for that.

**Comment by asokolsky** [comment]
Großartig! Vielen Dank!

**Comment by sebhildebrandt** [comment]
Sorry for the delay! I fixed it and have a working solution now, will add it to version 4.0 (will be released within the next 2 weeks)

**Comment by asokolsky** [comment]
Great!  Thanks for the follow up!

**Comment by sebhildebrandt** [comment]
@asokolsky: the relevant changes are already pushed to GitHub (not yet published as a NPM package) ... just in case that you want to give it a try ;-)

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
