### ISSUE TITLE
Failed to minify the code from this file:

### ISSUE THREAD

**Issue by karangoel16** [sebhildebrandt/systeminformation#160]
Failed to minify the code from this file:

        ./node_modules/<Package>/node_modules/systeminformation/lib/util.js:17

To resolve this:

Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.

Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.

Fork the package and publish a corrected version yourself.

If the dependency is small enough, copy it to your src/ folder and treat it as application code.

In the future, we might start automatically compiling incompatible third-party modules, but it is not currently supported. This approach would also slow down the production builds.

**Comment by sebhildebrandt** [comment]
Hi @karangoel16 , just one question: are you trying to minify it for using it with node.js (server side) or to use it on client (browser) side?

**Comment by sebhildebrandt** [comment]
The line where the minification failed is a valid ES6 destructuring assignment. So this should be fine (on server side - node.js V6 and above). bit for better compatibility with node v4 I changed it to the old version. Closing it for now ...
