### ISSUE TITLE
allow running as non-root/sudo

### ISSUE THREAD

**Issue by rgillan** [sebhildebrandt/systeminformation#167]
If the parent node.js application is run as non-root, the exec calls to dmidecode in system.system/bios/baseboard do not return data due to a permissions block.  Typically if run as a user such as ubuntu the use of sudo will get past this.  It would be good if this module was able to handle non root user.

**Comment by sebhildebrandt** [comment]
Hi @rgillan , I tried to find a solution getting bios information as non-root but I haven't found anything for that. I am afraid, at the moment, I cannot provide a reliable solution. Closing it for now but I will keep looking for a workaround. OK?

**Comment by rgillan** [comment]
Hi,
If you simply preface all the calls to dmidecode with sudo (on Linux at least) it will solve the problem somewhat, e.g. in /lib/system.js line 47:

exec('dmidecode -t system', function (error, stdout) {

becomes

exec('sudo dmidecode -t system', function (error, stdout) {

it will work.  We have done this in a local copy of your library and it works well.  I think you can safely assume that the user running node.js will have sudo privs.  Let me know if you want me to create a PR for you but it should be pretty straight forward

Cheers
Rob
