### ISSUE TITLE
I have 2 displays, but only 1 is reported

### ISSUE THREAD

**Issue by edtguy** [sebhildebrandt/systeminformation#168]
### Issue Type

* [ ] Bug
* [ ] Feature Request
* [x ] Question

### Expected behavior 
si.graphics() should return 2 objects in the displays array
- 
- 
- 

### Actual behavior
si.graphics() returns only 1 object in the displays array
- 
- 
- 

### Steps to reproduce the problem
I have a Lenovo ThinkCentre running Windows 10. The hdmi port is connected to the DVI port of an HP 2511x monitor, resolution 1920x1080. The vga port is connected to a Dell monitor, resolution 1680x1050. Both are active with application windows displayed, but si.graphics() only reports a single display object, which it identifies in the model field as 'Dell Inc.', but with resolution 1920x1080. If I disconnect the HP monitor, si.graphics() continues to report the same information, even if I exit the node command prompt window and restart. It is only if I restart Windows with only the Dell monitor connected that si.graphics() returns resolution of 1680x1050. Also, if I restart Windows with only the HP monitor connected, the model field now contains 'HP'
-
-
-

### Specifications 

- package version: systeminformation 3.45.9, node 8.11.3, npm 6.2.0
- operating system: Windows 10
- hardware: Processor	Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz, 2901 Mhz, 4 Core(s), 4 Logical Processor(s)

### Problem and possible solution
Is there some additional setting to retrieve info for both displays?

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ...

**Comment by sebhildebrandt** [comment]
@edtguy Thank you for reporting this ... 

Can you provide the output of the following command:

```
wmic path win32_desktopmonitor get Caption, MonitorManufacturer, MonitorType, ScreenWidth, ScreenHeight /value
```

with both monitors connected?

Thank you in advance.

**Comment by edtguy** [comment]
My apologies, I only just saw your reply. I'm currently rdc'ed into that machine with 2 monitors, so I don't know if the following output is valid. I'll run it again when I'm in the office this week.

Output from wmic:
Caption=Dell 2208WFP(Analog)
MonitorManufacturer=Dell Inc.
MonitorType=Dell 2208WFP(Analog)
ScreenHeight=
ScreenWidth=

**Comment by edtguy** [comment]
back in the office. Ran the command with both screens active:

Microsoft Windows [Version 10.0.17134.471]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>wmic path win32_desktopmonitor get Caption, MonitorManufacturer, MonitorType, ScreenWidth, ScreenHeight /value


Caption=Dell 2208WFP(Analog)
MonitorManufacturer=Dell Inc.
MonitorType=Dell 2208WFP(Analog)
ScreenHeight=
ScreenWidth=

**Comment by sebhildebrandt** [comment]
Unfortunately as I expected ... `wmic path win32_desktopmonitor`will only give back information for one monitor even if more than one ist connected. Not yet found a way to reliably get information about the second monitor ... but I am still investigating this ...

**Comment by edtguy** [comment]
Thanks. I appreciate your efforts

**Comment by OmgImAlexis** [comment]
@sebhildebrandt [this](https://social.msdn.microsoft.com/Forums/en-US/c7e99a3f-23f5-48df-bb7e-8c02586de32d/get-multiple-monitor-information-from-win32desktopmonitor-wmi-class?forum=windowsgeneraldevelopmentissues) might help.

**Comment by sebhildebrandt** [comment]
@edtguy Unfortunately I cannot find a reliable solution for that. For Windows 10, `win32_desktopmonitor` should return all monitors, which is not the case on your system. See also [here](https://social.msdn.microsoft.com/Forums/en-US/c7e99a3f-23f5-48df-bb7e-8c02586de32d/get-multiple-monitor-information-from-quotwin32desktopmonitorquot-wmi-class?forum=windowsgeneraldevelopmentissues). Here they also mention `EnumDisplayMonitors()` which I cannot use from node that easy. I will close this issue for now as I do not find a reliable solution. But I keep it on my list ...
