### ISSUE TITLE
CPU temp

### ISSUE THREAD

**Issue by ghs** [sebhildebrandt/systeminformation#17]
I was looking around for some monitoring packages for node and found your one. While reading about how to use it saw that you had an issue getting the CPU temperature. Just a quick search and found another package that uses the SMC from Apple.
Hope this solves your "problem" :)
https://github.com/mmarcon/node-smc
https://github.com/jkuri/macstats

**Comment by sebhildebrandt** [comment]
Hi,

Wow, don't know, why I didn't found that. Thank you so much. Will try to make it work with systeminformation during the next few days. 

Thank you!

Sebastian

**Comment by ghs** [comment]
You are welcome!
There are also few which can provide information about windows systems :)

**Comment by sebhildebrandt** [comment]
Now implemented and tested it. Closing for now.
