### ISSUE TITLE
VRAM is incorrect in Ubuntu 18.0.4

### ISSUE THREAD

**Issue by angels2it** [sebhildebrandt/systeminformation#170]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- VRAM value is 4096

### Actual behavior

- VRAM value is 256

### Steps to reproduce the problem

- call si.graphics()
- check VRAM result

### Specifications 

- package version: 3.45.9
- operating system: Ubuntu 18.0.4
- hardware: AMD RX460

### Problem and possible solution
Seems this bug relate to lspci that systeminformation has used.

I try to use below command and the VRAM is show in log result

dmesg | grep VRAM

![image](https://user-images.githubusercontent.com/8542805/47879370-fd1cae80-de52-11e8-984a-ed46adafe4f5.png)

**Comment by sebhildebrandt** [comment]
Thank you for reporting, will have to look at this carefully. If I have questions, I will try to contact you again.

**Comment by angels2it** [comment]
Sorry for late response, This is output of command lspci -vvv
![screenshot from 2018-11-07 07-40-28](https://user-images.githubusercontent.com/8542805/48132151-8885ad80-e260-11e8-9ae7-dcf238431141.png)

**Comment by sebhildebrandt** [comment]
@angels2it I did not find a reliable method to better detect the VRAM so far. Closing it for now.
