### ISSUE TITLE
battery information is incorrect

### ISSUE THREAD

**Issue by j-heavy** [sebhildebrandt/systeminformation#171]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

* hasbattery: true
* maxcapacity: > 0
* currentcapacity: > 0
* percent: 12

### Actual behavior

* hasbattery: false
* maxcapacity: 0
* currentcapacity: 0
* percent: 0

### Steps to reproduce the problem

```javascript
si.battery()
	.then(data => console.log(data))
	.catch(error => console.error(error));
```

### Specifications 

- package version: 3.45.9
- operating system: Linux Mint 19 Cinnamon
- hardware: simple Li-on battery

![kek](https://user-images.githubusercontent.com/38788839/47938574-63163e00-df06-11e8-9441-f1b56a42f8d7.jpg)

**Comment by j-heavy** [comment]
@sebhildebrandt hmmm...
![battery](https://user-images.githubusercontent.com/38788839/47955743-59501180-dfbe-11e8-9225-b355da64afc3.jpg)

![2](https://user-images.githubusercontent.com/38788839/47955783-e6936600-dfbe-11e8-9047-5e597d3a578b.jpg)

but may be this code will be more accurate
```javascript
if (result.ischarging) {
  result.hasbattery = true
}
```

**Comment by sebhildebrandt** [comment]
Ok, that is interesting ... but I just committed a change that should now detect battery, but as the underlying information is incomplete, you will not get any additional information.

One more thing: can you provide also the output of 

```
cat /sys/class/power_supply/ADP1/uevent
```

Thank you in advance

**Comment by j-heavy** [comment]
![final](https://user-images.githubusercontent.com/38788839/47957351-fcf8ec00-dfd5-11e8-998b-0513daac181e.jpg)
Yeah, after update `si.battery().hasbattery` works correct

**Comment by sebhildebrandt** [comment]
OK, thank you. First of all, fine that it works now (partially) ... and as ADP1 does not provide additional information (this is for power adapter) I will close this for now.
