### ISSUE TITLE
Interface MTU

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#173]
### Issue Type

* [ ] Bug
* [x] Feature Request
* [ ] Question

### Problem and possible solution

In linux OSs interface MTUs are in `/sys/class/net/$iface/mtu`.
Can you please add this to `networkInterfaces`?

**Comment by sebhildebrandt** [comment]
Thank you Alexis! Makes sense! Will add this.

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
