### ISSUE TITLE
Extra whitespace in CPU brand on Macbook Pro

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#175]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Problem and possible solution

`cpu().brand` is returning `Core™ i5        M 520`.

Is the extra white space meant to be there?
If not do you have a command you want me to check?

----

Not sure if you can see the issue as the preview isn't showing it, but there's a tab character between the `"i5"` and `"M"`.

**Comment by sebhildebrandt** [comment]
Hmmm ... could you be so kind an post the output of 

```
sysctl machdep.cpu.brand_string
```

Thank you in advance

**Comment by OmgImAlexis** [comment]
```
machdep.cpu.brand_string: Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
```

I was hoping to have a hyphen where the tab character as to match how Intel styles the name. `Intel® Core™ i5-520M `.

**Comment by sebhildebrandt** [comment]
I understand ... unfortunately I haven't figured out a suitable way to do this consistently. The only idea I have in mind to create a reference table for the most used processor types and their "official" names ... not sure if this makes sense.

**Comment by OmgImAlexis** [comment]
Let's close this for now, if I can find a way to get around this I'll reopen it.

**Comment by OmgImAlexis** [comment]
So it looks like this may be a common issue. I've just tried this on my R710 and I'm getting `Xeon®            X5650` for the brand. Between the registered trademark icon and X5650 there's 12 spaces.

**Comment by sebhildebrandt** [comment]
I implemented a little cleanup ... so there should not be any tabs / extra spaces any more. Version 3.49.1. just released
