### ISSUE TITLE
[Windows] CPU temp reads -1 even though WMIC command seems to work

### ISSUE THREAD

**Issue by GitSquared** [sebhildebrandt/systeminformation#179]
### Issue Type

* [X] Bug

### Specifications 

- package version: 3.50.2
- operating system: Win10 x64
- hardware: Reported on multiple CPUs

### Problem and possible solution

Using `systeminformation.cpuTemperature` returns a static `-1` value (on `results.main`) on Windows machines (reported by multiple users, including myself, downstream at https://github.com/GitSquared/edex-ui/issues/274).

Running the command that systeminformation uses internally returns this:
![wincmddebug](https://user-images.githubusercontent.com/35188982/48966965-13dd9d80-efda-11e8-8434-6d320c7b9779.jpg)
(courtesy of @Scylos)

The WMIC output seems to indicate that the temperature reading works. Perhaps there is a problem in the parsing of this data?

**Comment by sebhildebrandt** [comment]
Ahhh ... I see the problem ... will provide a fix soon.

**Comment by GitSquared** [comment]
Crap, i might have got the good results from WMIC in an admin powershell session indeed.

Tried to run the command on my previous test machine but it gives out a "Not supported" error - forgot to mention this one was running windows 7, i guess the data i sent you isn't worth anything.

@clragon @Scylos if you guys could come over here and test the above command in normal and admin contexts, that would be very helpful.

@sebhildebrandt so it could be possible that cpu temps aren't accessible as a non-admin user?

**Comment by clragon** [comment]
without admin
```
C:\Users\clragon\Desktop>wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
Knoten - TWA-14
FEHLER:
Beschreibung = Nicht unterstützt
```
with admin
```
C:\WINDOWS\system32>wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
Knoten - TWA-14
FEHLER:
Beschreibung = Nicht unterstützt
```

**Comment by sebhildebrandt** [comment]
@GitSquared actually yes ... on several windows installations you cannot get the temperature with `wmic` as non-admin ... but this is not consisitent ... some installations allow to query the temperature, some not ... :-(

**Comment by GitSquared** [comment]
So I guess there is no fix for this. I'll see what i can do downstream, perhaps replace the CPU temperature indicator by something else on Windows.

Thank you for looking into this. I guess you can close the issue.

**Comment by Scylos** [comment]
Sorry for my late ! Here are the command without and with the administrator permission:

Without:
```
C:\Users\leoja>wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
Noeud - DESKTOP-UEE2R5S
ERREUR :
Description = Accès refusé
```

With:
```
PS C:\WINDOWS\system32> wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
CurrentTemperature
3262
```

**Comment by sebhildebrandt** [comment]
Thank you all for your support! Unfortunately wmic docs not provide valid data in all cases (e.g. most often it is needed to run code as admin) - see also README.md. 

Closing it for now.
