### ISSUE TITLE
question about list returned by si.processes()

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#18]
Hi Sebastian,

Happy New Year & hope you are well.

The process object returned under si.processes().list contains a 'pcpu' (percent CPU utilization) field. How should I interpret this number on a multi-core machine?

I here have in mind the difference between the top command's Irix (the default, I think) and Solaris modes. In the former, %CPU is not divided by the number of cores; in the latter it is.

As always, thanks for your help.

Cordially,

Paul

**Comment by sebhildebrandt** [comment]
Hi Paul,

as I use a `ps`command with the pcpu option to determine this value, it is the % of how many a single core is used. This means: if you have e.g. a 4 core machine, the max is 400% (100% each).

Hope that helps.
