### ISSUE TITLE
BusyBox's "free" can't separate columns on 16GB RAM machine

### ISSUE THREAD

**Issue by tateisu** [sebhildebrandt/systeminformation#180]
from https://github.com/syuilo/misskey/issues/3409

### Issue Type

* [*] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
get memory info correctly.

### Actual behavior
can't get get memory info correctly.

### Steps to reproduce the problem
BusyBox's "free" can't separate columns on 16GB RAM machine.
run ` free -b` on that machine.

### Problem and possible solution

if get wrong column count, read /proc/meminfo .

**Comment by tateisu** [comment]
https://bugs.busybox.net/show_bug.cgi?id=11521

**Comment by sebhildebrandt** [comment]
Ok @tateisu , I see where the problem is ... will provide a fix for that!

**Comment by sebhildebrandt** [comment]
Fixed. Version 3.51.2 just published

**Comment by tateisu** [comment]
Thank you for your great work and fast release!

**Comment by sebhildebrandt** [comment]
refactored to `to /proc/meminfo`, new version 3.51.3 just released.

**Comment by tateisu** [comment]
(FYI)
BusyBox fixes separating on its git (not yet released), but its only digits line and not include header row.
https://git.busybox.net/busybox/commit/?id=f4709d78cb0c4f54283046e8f86edb9ecd7e41ca
https://bugs.busybox.net/show_bug.cgi?id=11521

then SI 3.51.2 may not work with BusyBox's next release.
Of course SI 3.51.3 will not affected.

**Comment by sebhildebrandt** [comment]
@tateisu thank you vor informing me. So lets hope that there are not to many 3.51.2 versions out in the field... ;-)
