### ISSUE TITLE
Network Stats for all interfaces

### ISSUE THREAD

**Issue by abolinhas** [sebhildebrandt/systeminformation#181]
### Issue Type

* [ ] Feature Request

### Expected behavior 
Get network stats for all interfaces, like si.networkStats(*)

### Actual behavior
by default si.networkStats(iface,cb) only returns stats of eth0

**Comment by sebhildebrandt** [comment]
@abolinhas  : as this needs a change in the interface, I will add this in version 4.0. I plan to finish that in the next few weeks.

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
