### ISSUE TITLE
[FeatureRequest] Physical Cores vs Logical Cores

### ISSUE THREAD

**Issue by DocCodes** [sebhildebrandt/systeminformation#182]
### Issue Type
* Feature Request

### Problem and possible solution

A processor might have 8 cores and 16 threads because of multithreading. If you could add a way to check for this that would be wonderful. In Windows you can use...
`wmic cpu get NumberOfCores, NumberOfLogicalProcessors`
...to see the physical and logical processors.

**Comment by sebhildebrandt** [comment]
Good idea ... yes this is possible also on a linux machine ... will provide this ... maybe this weekend.

**Comment by sebhildebrandt** [comment]
I guess I found a solution for Win, Linux, Mac. Additionally I will provide also information about # of processors. Will finish it this weekend.

**Comment by sebhildebrandt** [comment]
New version just released (3.52.0) - here I added:

- cpu.codes ... logical cores
- cpu.physicalCores ... # physical cores
- cpu.processors ... # of physical processors installed (normally just 1)
- cpu.socket ... socket type

**Comment by jiferrero** [comment]
Hi Sebastian,
Checking this over a relative bit older DELL PowerEdge 2550 dual server socket server found the following (2 processors, 4 logical cores and 0.5 physical cores) ... Following the whole object cature:

cpu: {…}
​  ​brand: "Xeon™ 3.00GHz"
​​  cache: Object { l1d: 16384, l1i: "", l2: 2097152, … }
​​  cores: 4
​​  currentLoad: Object { avgload: 0.13, currentload: 15.764705882352942, currentload_user: 11.294117647058824, … }
​​  currentSpeed: Object { min: 2.99, max: 2.99, avg: 2.99, … }
​​  family: "15"
​​  flags: "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi   mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc pebs bts nopl cpuid pni dtes64 monitor ds_cpl cid cx16 xtpr pti"
​​  manufacturer: "Intel®"
​  ​model: "4"
​​  physicalCores: 0.5
​​  processors: 2
​​  revision: ""
​​  socket: ""
​​  speed: "2.99"
​​  speedmax: ""
​​  speedmin: ""
​  ​stepping: "3"
​  ​temp: Object { main: -1, cores: [], max: -1 }
​  ​vendor: "GenuineIntel"
​​  voltage: ""
​​  <prototype>: Object { … }
​​
