### ISSUE TITLE
relationship between diskLayout and blockDevices

### ISSUE THREAD

**Issue by goapilz** [sebhildebrandt/systeminformation#185]
### Issue Type

* [ ] Bug
* [ ] Feature Request
* [x] Question

### Expected behavior 
Hi first your component is great and offers everything i need but i have a question.

I think there is no relationship between diskLayout and blockDevices  and that is my problem.

I would like to know to which disk (diskLayout) a partition (blockDevices) belongs to.

diskLayout:
(my system has multiple disks so here is only one to explain what i mean)
```
  { type: 'HD',
    name: 'TOSHIBA DT01ABA300',
    vendor: '(Standard disk drives)',
    size: 3000590369280,
    ...
    **serialNum: '233AXZ4GS',**
    interfaceType: 'SATA',
    smartStatus: 'Ok' }
```

blockDevices:
```
  { name: 'E:',
    identifier: 'E:',
    type: 'disk',
    fstype: 'ntfs',
    mount: 'E:',
    size: '3000457166848',
    physical: 'Local',
    **uuid: '2AF15CCF',**
    label: 'MY_DISK_LABEL',
    model: '',
    **serial: '2AF15CCF',**
    removable: false,
    protocol: '' }
```

At first I thought I could make the relationship via the serialNumber but the numbers are different.

Is there a way to solve this problem ?

Many thanks in advance

**Comment by sebhildebrandt** [comment]
Seems that there is now reliable way to determine the relationship betweeen hard disks (`si.disklayout`) and partitions (`si.blockDevices`) in windows from command line. They an external tool (DiskPart) this would be possible but Windows do not provide any build in tool to determine that. Closing it for now, but keep it on my list.

**Comment by goapilz** [comment]
Thanks for the answer.  I found a way to get the relationship via powershell and wmi:

Someting like diskLayout:
Get-WmiObject -Class Win32_diskdrive

Someting like blockDevices:
Get-WmiObject -Class Win32_logicaldisk

With the following command i can get the relationship for the drive letter D:
$Disk = Get-WmiObject -Class Win32_logicaldisk -Filter "DeviceID = 'D:'"
$Disk
$DiskPartition = $Disk.GetRelated('Win32_DiskPartition')
$DiskPartition
$DiskDrive = $DiskPartition.GetRelated('Win32_DiskDrive')
$DiskDrive

Also see:
https://mcpmag.com/articles/2018/01/26/view-drive-information-with-powershell.aspx

With this custom command i can iterate through all disks with all logicaldisks:
Get-WmiObject -Class Win32_diskdrive | 
  Select-Object -Property DeviceID, Model, Size, 
    @{L='Partitions';E={$_.GetRelated('Win32_DiskPartition').GetRelated('Win32_LogicalDisk') | 
      Select-Object -Property DeviceID, VolumeName, Size, FreeSpace}}

**Comment by sebhildebrandt** [comment]
@goapilz : Hey that's great. Will try to follow this way!! Maybe next week I will find the time to make a first version. Thank you!
