### ISSUE TITLE
CPU Usage in %

### ISSUE THREAD

**Issue by PauloFerreira25** [sebhildebrandt/systeminformation#19]
Hello,
I liked your project.
But I'm kind of dumb and I do not know how to make my code look just like you.
Could you please review and include my code in your next version?
Thank you

```javascript
exec("cat /proc/stat | grep cpu", function(error, stdout) {
                let lines = stdout.toString().trim().split('\n');
                lines.splice(0, 1);
                lines.forEach(function(line, index) {
                    let sline = line.split('\ ')
                    let pline = {
                        core: sline[0],
                        user: parseInt(sline[1]),
                        nice: parseInt(sline[2]),
                        system: parseInt(sline[3]),
                        idle: parseInt(sline[4]),
                        iowait: parseInt(sline[5])
                    };
                    let totalTime = pline.user + pline.nice + pline.system + pline.idle + pline.iowait;
                    pline.user = Number((pline.user * 100) / totalTime).toFixed(3);
                    pline.nice = Number((pline.nice * 100) / totalTime).toFixed(3);
                    pline.system = Number((pline.system * 100) / totalTime).toFixed(3);
                    pline.idle = Number((pline.idle * 100) / totalTime).toFixed(3);
                    pline.iowait = Number((pline.iowait * 100) / totalTime).toFixed(3);
                    lines[index] = pline;
                });
                resolve(lines);
            };
```

**Comment by sebhildebrandt** [comment]
Hi, thank you for your suggestion ...

I guess, I already have something similar in my code. Not exactly the same but somehow an equivalent. See function ```currentLoad()```. Differences:

- first of all, I am not calculating those values per CPU, instead I am calculating overall values. 
- second: as ```/proc/stat``` returns statistics since startup, you will not get the current CPU usage back. So my approach is a little bit different. Each time you call currentLoad(), you get the CPU usage in % since LAST call of the function. So this function returns a much more accurate current usage in %
- third: ```ioWait``` is missing in my code, as the built-in node function os.cpus() does not return ```iowait```

Make sense?

**Comment by PauloFerreira25** [comment]
Hello,
Thank you for responding.
I've already seen CPU load in your code, but it does not help me because I need CPU usage per core.
Many thanks for explaining about /proc/stat, I did not know it was a cumulative information.
I'll think of something and as soon as I have a better suggestion, I'll let you know.
If it is not in your project's interest to have per-core use, let me know that I will not bother you any more.
Sorry for my english translator
Thanks for listening

**Comment by PauloFerreira25** [comment]
Hello again,
Looking at what I need and comparing with other returns you already have.
I believe the best would be to make the return be the gross value of / proc / stat
Thus, I make the differential calculation of the cumulative based on the aggregation of the collections.
What do you think?

```javascript
exec("cat /proc/stat | grep cpu", function(error, stdout) {
                let lines = stdout.toString().trim().split('\n');
                lines.splice(0, 1);
                lines.forEach(function(line, index) {
                    let sline = line.split('\ ')
                    let pline = {
                        core: sline[0],
                        user: parseInt(sline[1]),
                        nice: parseInt(sline[2]),
                        system: parseInt(sline[3]),
                        idle: parseInt(sline[4]),
                        iowait: parseInt(sline[5])
                    };
                    lines[index] = pline;
                });
                resolve(lines);
            };
```

**Comment by PauloFerreira25** [comment]
Hello again.
Please, I'm sorry for bothering you so much.
Looking at the NodJS code, the os.CPUs function, does exactly the same thing as I proposed.

> Https://github.com/nodejs/node/blob/master/src/node_os.cc

Only abstracts the name of the core, but before the order. Core0 index 0.
Therefore, there is already in the Node itself what I need.

PS: In both cases, I'll need to calculate the differential.

**Comment by PauloFerreira25** [comment]
Excuse my stupidity again.
I forgot that NodeJS does not have ioWait
:(

**Comment by sebhildebrandt** [comment]
Hi again,

- first of all: all comments and suggestions are always welcome ;-)
- node.js builtin function `os.cpus()`: I already mentioned, that I am also using this function to calculate current load. And yes, iowait is missing (softirq also missing)
- I like the idea of having currenLoad also on a cpu/core level in %. I will add this array to the overall values. So you can then decide, which one is better for you. I will push a new version end of this week. Hope that helps (also without iowait)

**Comment by PauloFerreira25** [comment]
In my searches, I discovered that not having iowait is because Windows does not have this information.
So to stay more "homogenous" NodeJS only retrieves the information that exists in all OS.
To get this information, I am collecting in /proc/stats, storing in a DB on the outside and then retrieving the collection to make the differential.
Just thought about it or make a copy of /proc/stats in /tmp to make the differential ... :(

**Comment by sebhildebrandt** [comment]
To be also consistent with OS X I keep relying on `os.cpus()`. This means that iowait is missing :-( 

The good news is, that I already have the code ready to calculate currentLoad also on all cpu/cores level. I will push it (after some more testing) end of this week.

**Comment by sebhildebrandt** [comment]
Changes pushed ... now you also have CPU % on cpu/core level ;-)
