### ISSUE TITLE
dockerContainerStats should return array

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#191]
### Issue Type

* [x] Bug
* [x] Feature Request
* [ ] Question

### Expected behavior 

Stats to be returned for all containers or an error to be thrown.

### Actual behavior

No stats?

### Steps to reproduce the problem

```
root@Devon:/mnt/user/code/api# node -r esm
> import si from 'systeminformation'
> si.dockerContainerStats().then(_ => console.log(_))
> { id: '',
  mem_usage: 0,
  mem_limit: 0,
  mem_percent: 0,
  cpu_percent: 0,
  pids: 0,
  netIO: { rx: 0, wx: 0 },
  blockIO: { r: 0, w: 0 } }
```

### Specifications 

- package version: 3.52.4
- operating system: Unraid
- hardware: N/A

### Problem and possible solution

Return an array with all containers when no id is passed.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis : Will add this to version 4.0

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
