### ISSUE TITLE
si.cpu(): /dev/mem: Permission denied 

### ISSUE THREAD

**Issue by RobinTail** [sebhildebrandt/systeminformation#193]
### Issue Type

* [X] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

Method resolves Promise with data or throws an error

### Actual behavior

Method resolves Promise with data but exposes the following ugly message to console

`/dev/mem: Permission denied`

### Steps to reproduce the problem

`si.cpu()`

### Specifications 

- package version: since version 3.52.0
- operating system: Debian 9.4
- hardware: Raspberry Pi 3B+

### Problem and possible solution

Have no idea yet

**Comment by RobinTail** [comment]
Found the specific line that causes the error in 82cc7fb84f02eef5508cd1b27b8284e367b06884 `/lib/cpu.js:351`:

```
lines = execSync('dmidecode –t 4 | grep "Upgrade: Socket"').toString().split('\n');
```

**Comment by sebhildebrandt** [comment]
@RobinTail : thank you for reporting this! Found the problem, will be handled in version 4 (planned release end of January)

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
