### ISSUE TITLE
si.system properties are -

### ISSUE THREAD

**Issue by SpaceboyRoss01** [sebhildebrandt/systeminformation#194]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- `si.system` to return the proper values

### Actual behavior

- all properties are `-` or blank 

### Steps to reproduce the problem

- run `si.system`

### Specifications 

- package version: 3.54.0
- operating system: Arch Linux
- hardware: Latitude E6420

### Problem and possible solution

Running node as root and then running `si.system`.

**Comment by sebhildebrandt** [comment]
Did you tried to run it with root privileges? Same result?

**Comment by SpaceboyRoss01** [comment]
Root has same issue

**Comment by sebhildebrandt** [comment]
@SpaceboyRoss01 Thank you, can you also provide the output of 

```
dmidecode -t system 2>/dev/null
```

(as `root`and maybe also as non-root) Thank you in advance!

**Comment by SpaceboyRoss01** [comment]
As root:
```
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.6 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Dell Inc.
	Product Name: Latitude E6420
	Version: 01
	Serial Number: 8ZVK8V1
	UUID: 4c4c4544-005a-5610-804b-b8c04f385631
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified

Handle 0x003F, DMI type 12, 5 bytes
System Configuration Options
	Option 1: To Be Filled By O.E.M.

Handle 0x004C, DMI type 32, 20 bytes
System Boot Information
	Status: No errors detected
```

Non-root:
```
# dmidecode 3.2
Scanning /dev/mem for entry point.
```

**Comment by sebhildebrandt** [comment]
Hi @SpaceboyRoss01, I pushed a change for `system()` to GitHub. Can you checkout this code and test it with this once again (`root` and non-root)?

**Comment by SpaceboyRoss01** [comment]
Root works but for non-root, it still shows `-` for system.

**Comment by sebhildebrandt** [comment]
Yes, so this is related to the problem that dmidecode does not return any info I can rely on with non-root. As I do not have any other possibilities to determine appropriate information here, I would consider this as closed. OK?

**Comment by SpaceboyRoss01** [comment]
I found a way to get the same properties as `dmidecode` but without root.

**Comment by sebhildebrandt** [comment]
@SpaceboyRoss01 : Can you give me a hint??

**Comment by SpaceboyRoss01** [comment]
The directory called `/sys/devices/virtual/dmi/id`.

**Comment by sebhildebrandt** [comment]
OK. Thank you so much! So I actually found it also on one of my installations. Started work an a solution ;-) Will come back when I have something in place ...

**Comment by sebhildebrandt** [comment]
@SpaceboyRoss01 OK, so now I have a non-root version (fallback to the mentioned directory) in place ... for `system()`, `baseboard()` and `bios()`. Can you test it also on your side?

**Comment by SpaceboyRoss01** [comment]
I can't install it globally?
```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: failed to stat '/root/.npm/_cacache/tmp/git-clone-70b88d03': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-13T11_05_31_099Z-debug.log
```

**Comment by sebhildebrandt** [comment]
Seems to be a permission problem on your side (see error messages) ... not related to systeminformation

**Comment by SpaceboyRoss01** [comment]
Seems working.

**Comment by sebhildebrandt** [comment]
@SpaceboyRoss01 
Did you tried all three (`system()`, `baseboard()` and `bios()`) ?
Can you post the results ...?

Then I can close this issue. Thank you one more time!

**Comment by SpaceboyRoss01** [comment]
only system

**Comment by SpaceboyRoss01** [comment]
Tested the other two, works.

**Comment by sebhildebrandt** [comment]
Thank you! Closing it now.
