### ISSUE TITLE
si.osInfo returns invalid properties for BlueLight

### ISSUE THREAD

**Issue by SpaceboyRoss01** [sebhildebrandt/systeminformation#195]
### Issue Type

* [x] Bug
* [x] Feature Request
* [ ] Question

### Expected behavior 

- `si.osInfo` to return
```
{
    "arch" : "x64",
    "build" : "0.2.0",
    "codename" : "alpha",
    "codepage" : "UTF-8",
    "distro" : "BlueLight",
    "hostname" : "osjs",
    "kernel" : "4.20.0-arch1-1-ARCH",
    "logofile" : "bluelight",
    "platform" : "linux",
    "release" : "0.2.0-alpha",
    "serial" : ""
}
```

### Actual behavior

- `si.osInfo` returns
```
{
    "arch" : "x64",
    "build" : "",
    "codename" : "",
    "codepage" : "UTF-8",
    "distro" : "BlueLight",
    "hostname" : "osjs",
    "kernel" : "4.20.0-arch1-1-ARCH",
    "logofile" : "linux",
    "platform" : "linux",
    "release" : "unknown",
    "serial" : ""
  }
```

### Steps to reproduce the problem

- Install `systeminformation` on BlueLight
- Run `si.osInfo` in a REPL session

### Specifications 

- package version: v3.54.0
- operating system: BlueLight v0.2.0-alpha
- hardware: Virtual Box

### Problem and possible solution

/etc/os-release for BlueLight v0.2.0-alpha:
```
NAME="BlueLight"
PRETTY_NAME="BlueLight"
VERSION="0.2.0-alpha"
VERSION_CODENAME=alpha
ID=bluelight
ID_LIKE=archlinux
ANSI_COLOR="0;96"
HOME_URL="https://bluelightos.github.io"
SUPPORT_URL="https://community.os-js.org/"
BUG_REPORT_URL="https://github.com/BlueLightOS/bluelight/issues"
```

**Comment by sebhildebrandt** [comment]
Hi @SpaceboyRoss01 , thank you for posting your details!

Agree on your findings and the expected behaviour except of `build`, this is not really available in linux and I also would not consider the release version as a `build`.

I pushed a change for `osInfo()` to GitHub. Can you checkout this code and test it with this once again?

**Comment by SpaceboyRoss01** [comment]
I get a type error, cannot read property replace of undefined

**Comment by sebhildebrandt** [comment]
@SpaceboyRoss01 any line number given??

**Comment by SpaceboyRoss01** [comment]
nope

**Comment by sebhildebrandt** [comment]
@SpaceboyRoss01 Can you post the complete error stack?

**Comment by SpaceboyRoss01** [comment]
![virtualbox](https://user-images.githubusercontent.com/19699320/51084633-1dce7380-16e2-11e9-9cbd-aa6acb9ee8d0.png)

**Comment by sebhildebrandt** [comment]
I knew I forgot something ;-) Now I also added the codename (as in VERSION_CODENAME=alpha)

**Comment by sebhildebrandt** [comment]
BUT ... need to check ... codepage is now empty?? Was set correctly before ...

**Comment by SpaceboyRoss01** [comment]
codepage is empty and serial is empty

**Comment by sebhildebrandt** [comment]
OK, fixed that also ... hopefully ...

**Comment by SpaceboyRoss01** [comment]
`codepage: 'ANSI_X3.4-1968',` 🤔 shouldn't it be UTF-8.

**Comment by SpaceboyRoss01** [comment]
BUILD_ID is being set too for debugging reasons for BlueLight.

**Comment by sebhildebrandt** [comment]
@SpaceboyRoss01 : 

- codepage: now it should be correct
- serial: I am now adding the machine ID (linux) is this is set
- buildID: so what is the build ID on your system? Where did you get it from? I was thinking of something like "10.1.9234" like in windows ... "alpha" is not really an ID to my mind ... any suggestions?

**Comment by SpaceboyRoss01** [comment]
the build id is the date.

**Comment by sebhildebrandt** [comment]
build id: and where the source of this ... I mean where can I read the date?? can you post the command + result for that?

**Comment by SpaceboyRoss01** [comment]
`cat /etc/os-release | grep 'BUILD_ID'` then just extract it

**Comment by sebhildebrandt** [comment]
Great! Added! so now you should have all values filled ... right?

**Comment by SpaceboyRoss01** [comment]
you need to remove the quotation marks from the build id.

**Comment by sebhildebrandt** [comment]
Sorry! Now ...

**Comment by sebhildebrandt** [comment]
All fine??

**Comment by SpaceboyRoss01** [comment]
Works

**Comment by sebhildebrandt** [comment]
Perfect, thank you. Closing it now.
