### ISSUE TITLE
diskLayout never stops on windows 8

### ISSUE THREAD

**Issue by koraniar** [sebhildebrandt/systeminformation#197]
### Issue Type
* [x] Bug

### Code
```
const si = require('systeminformation');

...
console.log('start disk library');
const diskLayout = await si.diskLayout();
console.log('start parsing disk');
```

### Output
```
start disk library
```
Never stops until press Ctrl + C

### Specifications 
- node: 10.15.0
- package version: 3.54.0
- operating system: Windows 8 Version 6.3 (Build 9600) (I have experienced the same behavior in another versions of Windows 8)

### Windows 7 and 10

On windows 7 and 10 in the same machine and the same code the response is:
```
start disk library
[{
	type: 'HD',
	name: 'Virtual HD ATA Device',
	vendor: '(Standard disk drives)',
	size: 136358691840,
	bytesPerSector: 512,
	totalCylinders: 16578,
	totalHeads: 255,
	totalSectors: 266325570,
	totalTracks: 4227390,
	tracksPerCylinder: 255,
	sectorsPerTrack: 63,
	firmwareRevision: '1.1.0',
	serialNum: '202020202020202020202020202020202202020',
	interfaceType: 'IDE',
	smartStatus: 'OK'
}]
start parsing disk
```

**Comment by sebhildebrandt** [comment]
@koraniar seems to be the same issue as #196 ... found the bug, will release a new package next week.

**Comment by ricardopolo** [comment]
@sebhildebrandt any news about the release of this new version? thanksss!

**Comment by sebhildebrandt** [comment]
Hope to finish coding & testing this weekend ...

**Comment by ricardopolo** [comment]
Hi, any news about this?
Is there something that we can do for help you? Thanks!!

**Comment by sebhildebrandt** [comment]
You van try code on GitHub. Should already work. Will release new version 4 this week. Took a littlebit longer.

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published

**Comment by sebhildebrandt** [comment]
Hmmm, yes. Working on it ... I do not have any Windows 8 machine running so this is hard to reproduce. As soon as I tried something new, can I ask you to test it??

I today also pushed some code (refactoring the PowerShell command) ... if you can pull the library from GitHub and test it with this code would be cool.

**Comment by sebhildebrandt** [comment]
I just released a new version 4.0.7 with some other fixes ... but also changes in the PowerShell handling ... perhaps this works better??

**Comment by koraniar** [comment]
I have tested the version 4.0.7 and it is working well 🎉 , thank you.

**Comment by sebhildebrandt** [comment]
Ok this is good news!!!! @ricardopolo can you also test it with v4.0.7 ? Thank you in advance!

**Comment by ricardopolo** [comment]
@sebhildebrandt i am part of the team of @koraniar, in our test envinroment is working now!
Thanks @sebhildebrandt

**Comment by sebhildebrandt** [comment]
Thank you @ricardopolo
