### ISSUE TITLE
Peripherals?

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#198]
### Issue Type

* [ ] Bug
* [x] Feature Request
* [ ] Question

### Problem and possible solution
It'd be great to see usb devices and other peripherals(firewire, thunderbolt, etc).

**Comment by sebhildebrandt** [comment]
Good idea! will make an investigation on that ... yet unclear how this could interfere with e.g. `disklayout()`  ...

**Comment by ldittmar81** [comment]
- USB -> https://www.npmjs.com/package/usb
- Bluetooth -> https://www.npmjs.com/package/noble
- Serial Port -> https://serialport.io/docs/en/api-stream#serialportlist

**Comment by sebhildebrandt** [comment]
Started to work on this ... will try to provide first approach next week.

**Comment by OmgImAlexis** [comment]
@sebhildebrandt is there any update to this?

**Comment by sebhildebrandt** [comment]
@OmgImAlexis  Got also stuck with other things, never finished this ;-) ... will also try to work on this next week.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis, @ldittmar81  Version 5.0 just released. Here we have some new sections like USB, Bluetooth, Audio, Printers which allows now to get back more detailed information about peripherals. 

Be aware: Version 5 is NOT fully backwards compatible to version 5 ... see https://systeminformation.io/changes.html to get an overview over all breaking changes.
