### ISSUE TITLE
cat: /proc/net/wireless: No such file or directory

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#199]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

No error to be logged.

### Actual behavior

```
cat: /proc/net/wireless: No such file or directory
```

### Specifications 

- package version: `4.0.1`
- operating system: Unraid
- hardware: N/A

### Problem and possible solution

It looks like the error is coming from here. https://github.com/sebhildebrandt/systeminformation/blob/fe0eee258a16991d0743454ee69f188a5719c155/lib/network.js#L338

**Comment by sebhildebrandt** [comment]
@OmgImAlexis fixed, version 4.0.2 just published
