### ISSUE TITLE
si.users() is broken

### ISSUE THREAD

**Issue by glegrain** [sebhildebrandt/systeminformation#2]
si.users() seems to be broken with node v4.0.0. See error below:

```
systeminformation/lib/index.js:683
	result.users = [];
	^

ReferenceError: result is not defined
```

**Comment by sebhildebrandt** [comment]
I will have a look on it tomorrow ... Thank you for notifying me about this bug.

**Comment by sebhildebrandt** [comment]
Just made a quick fix but will test it again tomorrow (and then post updated package to npm).

**Comment by sebhildebrandt** [comment]
Fixed. npm package update already online. Thank you Guillaume.
