### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by dcharbonnier** [sebhildebrandt/systeminformation#20]
The best option is to maintain this with the library instead of having a @types package IMO.
We can provide a d.ts or convert the project to typescript, I prefer the last option but I can contribute to the first one too.

**Comment by sebhildebrandt** [comment]
Hi, thank you for your comment. Converting to typescript is an interesting idea, but I need to think more about it (if this is ok for you). As I am currently doing some more relevant changes to the package, please let me finish this first. 

I am not really sure, if this is really an "issue". So let me close this for now. I will definitely come back to you concerning d.ts or a possible convert, OK?

**Comment by plantain-00** [comment]
Hi, I need typescript declaration file too, typescript declaration file is just a file declaring interfaces of the library, and do not change the original source.
Here is the reference: 
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/By%20Example.md
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md
If you want to accept a pull request of typescript declaration file, I or @dcharbonnier can provide one pull request. when the declaration file is in npm package, we can use it in typescript.

**Comment by sebhildebrandt** [comment]
Ok, I will try to dig into that this week. And if I struggle, I definitely will come back to you, OK?
