### ISSUE TITLE
Chassis is returning the wrong Chassis type

### ISSUE THREAD

**Issue by jcolemn3** [sebhildebrandt/systeminformation#201]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
si.chassis() should return the proper chassis type based on the chassis number offset by 1

### Actual behavior

- Returns the wrong chassis type because the reference to array element is not offset by one.

### Steps to reproduce the problem

- 1) Open cmd prompt.
- 2) Run the following query:  wmic systemenclosure Get ChassisTypes
- 3) Check number against microsoft doc for verification https://blogs.technet.microsoft.com/brandonlinton/2017/09/15/updated-win32_systemenclosure-chassis-types/
- 4) run si.chassis() method in javascript. Method returns wrong value

### Specifications 
- package version: 4.0.1
- operating system: Windows 10
- hardware: HP Zbook

### Problem and possible solution
Problem - si.chassis() does not return the correct chassis type.
Solution - looking at the code in the system.js module, I notice that the value returned from the WMI is parsed to an integer. On the following line, the code takes the value from the integer and returns the value of the chassisTypes array at the parsed integer index without a decrement of one.
ex. My computer has a chassis type of {10} which is a notebook chassis type according to microsoft. The si.chassis() returns "hand Held" as type when it should be returning "Notebook" because the code is not referencing an index of [parsedInteger -1]

**Comment by sebhildebrandt** [comment]
@jcolemn3 you are completely right. My fault. I corrected it and published v4.0.2. Hope it works now as expected.
