### ISSUE TITLE
GetAllData dont finish on windows 8

### ISSUE THREAD

**Issue by gabayto** [sebhildebrandt/systeminformation#203]
When using windows 8, "getAllData" function doesn't return or fail.
could be related to:
https://github.com/sebhildebrandt/systeminformation/issues/197  ?
but i am using latest version (4.0.4)

**Current Output**
doesn't return anything

**Environment (please complete the following information):**
 - systeminformation package version: 4.0.4
 - OS: windows 10
 - intel based VM

**Comment by sebhildebrandt** [comment]
Hi @gabayto 
To be able to identify the issue, (and if it is related to #197 can you try to run

```
const si = require('systeminformation');

const diskLayout = await si.diskLayout();
console.log(diskLayout)
```

**Comment by gabayto** [comment]
Hey thanks,
yes. indeed it doesn't work,
tried  also si.os() -> works

**Comment by sebhildebrandt** [comment]
OK. Thank you! Will investigate ...

**Comment by sebhildebrandt** [comment]
So I guess I fixed it ... can you check it on your side? Version 4.0.6 just published.

**Comment by gabayto** [comment]
Hey, thanks! 
but at least for me it doesn't work.
can i provide any more info?

**Comment by sebhildebrandt** [comment]
@gabayto: so the provided code snippet fails still? Or is it just the `getAllData()`? Is there any output?

I am really sorry that there is still a problem. Will test it on some other windows machines when I am back in office. Thank you for your patience.

**Comment by sebhildebrandt** [comment]
One more thing:

Does the following 
```
powershell.exe Get-PhysicalDisk | Format-List
```
returns any output? Can you post it? Even if this is just an error message??
Thank you once again.

**Comment by gabayto** [comment]
<img width="551" alt="screen shot 2019-02-05 at 9 37 48" src="https://user-images.githubusercontent.com/12225085/52258987-bd6dd300-2929-11e9-92ad-320113a784c7.png">

**Comment by sebhildebrandt** [comment]
Ahh this is interesting ... I thought, PowerShell is not present and therefore we have a problem here... OK. Will check the code one more time ... 

And the `getDiskLayout()` does not throw any errors? It just does not finish?

**Comment by gabayto** [comment]
yep, just doesn't return.
ill anyway test again with 4.0.6, perhaps i did something wrong (i will let know if it works)
Thanks you!

**Comment by sebhildebrandt** [comment]
One thing that I am wondering ...

The output of `Get-PhysicalDisk | Format-List` would return something like this... (list instead of a table:
```
$ Get-PhysicalDisk | Format-List

ObjectId                         : {1}\\DESKTOP....
PassThroughClass                 :
PassThroughIds                   :
PassThroughNamespace             :
PassThroughServer                :
UniqueId                         : 1234567890
Description                      :
FriendlyName                     : Samsung SSD ZZZ ZZZ
HealthStatus                     : Healthy
Manufacturer                     :
Model                            : Samsung SSD ZZZ ZZZ
OperationalDetails               :
OperationalStatus                : OK
PhysicalLocation                 : Integrated : Adapter 0 : Port 0
SerialNumber                     : ...MYSERIAL....
AdapterSerialNumber              :
AllocatedSize                    : 987654321
BusType                          : SATA
CannotPoolReason                 : Insufficient Capacity
CanPool                          : False
DeviceId                         : 0
EnclosureNumber                  :
FirmwareVersion                  : MAT01B6Q
IsIndicationEnabled              :
IsPartial                        : True
LogicalSectorSize                : 512
MediaType                        : SSD
OtherCannotPoolReasonDescription :
PartNumber                       :
PhysicalSectorSize               : 512
Size                             : 987654321
SlotNumber                       :
SoftwareVersion                  :
SpindleSpeed                     : 0
StoragePoolUniqueId              :
SupportedUsages                  : {Auto-Select, Manual-Select, Hot Spare, Retired...}
UniqueIdFormat                   : FCPH Name
Usage                            : Auto-Select
VirtualDiskFootprint             : 0
PSComputerName                   :
ClassName                        : MSFT_PhysicalDisk
```

So I guess `Get-PhysicalDisk | fl` is also NOT returning a list?? Thank you for helping sorting this out.

**Comment by gabayto** [comment]
yes `Get-PhysicalDisk | fl` returns the same thing (table)
could be just formatting or something? ( i know noting about ps ... )

**Comment by koraniar** [comment]
I have the same problem in version 4.0.6
`$ Get-PhysicalDisk | Format-List` return this:

```
$ Get-PhysicalDisk | Format-List

ObjectId                         : {1}\\ROOT\ro....
PassThroughClass                 :
PassThroughIds                   :
PassThroughNamespace             :
PassThroughServer                :
UniqueId                         : IDE\DiskVirtual_HD______________________________1.1.0___\5&1278c138&0&0.0.0:ro....
AllocatedSize                    : 64424509440
BusType                          : ATA
CannotPoolReason                 : Insufficient Capacity
CanPool                          : False
Description                      :
DeviceId                         : 0
EnclosureNumber                  :
FirmwareVersion                  : 1.1.0
FriendlyName                     : PhysicalDisk0
HealthStatus                     : Healthy
IsIndicationEnabled              :
IsPartial                        : True
LogicalSectorSize                : 512
Manufacturer                     :
MediaType                        : UnSpecified
Model                            : Virtual HD
OperationalStatus                : OK
OtherCannotPoolReasonDescription :
PartNumber                       :
PhysicalLocation                 :
PhysicalSectorSize               : 4096
SerialNumber                     :
Size                             : 64424509440
SlotNumber                       :
SoftwareVersion                  :
SpindleSpeed                     : 4294967295
SupportedUsages                  : {Auto-Select, Manual-Select, Hot Spare, Retired...}
Usage                            : Auto-Select
PSComputerName                   :
```

but `Get-PhysicalDisk | fl` doesn't return something, it keeps running
![screen shot 2019-02-05 at 11 54 15](https://user-images.githubusercontent.com/17574419/52290013-290d6b80-293d-11e9-9e9e-8bbfa5d43abe.png)

**Comment by LTBComputers** [comment]
I seem to have the same issue running the 'getAllData' function. Running our app on Windows Server 2012r2. I have it running on one of our 2012r2 servers without issue but 3 others simply never return data. Ruling out the above here, I return a full list as above which is expected from powershell on the systems I'm troubleshooting this on.

**Comment by sebhildebrandt** [comment]
I still think it is more related to the `PowerShell` call which I am doing from node. So the following pieces of information would be helpful:

- exact version of windows (build)
- PowerShell version ( I guess something like `$PSVersionTable.PSVersion` within PowerShell should give back the version
- Are you running your code from within PowerShell or starting from a normal shell.

Thank you for any help here.

**Comment by sebhildebrandt** [comment]
In #197 we now have success with version 4.0.7.

Can you @gabayto , @glegrain , @LTBComputers also an test the version 4.0.7? 
Maybe we are on the right track now ;-)

**Comment by LTBComputers** [comment]
I updated this morning to 4.0.7 :) still having this issue.

**Comment by LTBComputers** [comment]
just before my first post here... I'll run npm again, but my package-lock says it's running the update

  "systeminformation": {
      "version": "4.0.7",
      "resolved": "https://registry.npmjs.org/systeminformation/-/systeminformation-4.0.7.tgz",
      "integrity": "sha512-IR3lfXlruG9L1FtIoXtH2nWwIaWP0jOGP5ojfZzRCPGLkMXazyFGDTCo/bfW3E3ruYZt0hFMHS8EMtn77/u0cQ=="
    },

**Comment by sebhildebrandt** [comment]
@LTBComputers  OK ;-) just wanted to be sure ....

**Comment by LTBComputers** [comment]
Weird... I swear I tried this after the 4.0.7 update and it didn't work... but it is working now for me now on my test system. I'll pkg it back up and deploy out to the other problem systems.

**Comment by sebhildebrandt** [comment]
So once again good news! So if @gabayto and @glegrain can confirm this ... we are fine ;-)

**Comment by sebhildebrandt** [comment]
Closing it for now. In #197 we got positive feedback that it works
