### ISSUE TITLE
ifaces.trim() not a function

### ISSUE THREAD

**Issue by LTBComputers** [sebhildebrandt/systeminformation#205]
Issue with network interfaces:
OS: Windows Server 2012r2 build 9600 x64

Error on network.js:470 ifaces = ifaces.trim().toLowerCase()....
ifaces.trim is not a function of undefined.

this is what my wmic command returns on this box:
PS C:\Users\Administrator> wmic nic get MacAddress,name,NetEnabled,Speed,NetConnectionStatus,AdapterTypeId /value 

AdapterTypeId=
MACAddress=
Name=WAN Miniport (L2TP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (SSTP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (IKEv2)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPTP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPPOE)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (IP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (IPv6)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (Network Moni
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=Microsoft Kernel Debug Net
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=Microsoft ISATAP Adapter
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=0
MACAddress=14:18:77:5B:A9:01
Name=Broadcom NetXtreme Gigabit
NetConnectionStatus=2
NetEnabled=TRUE
Speed=1000000000

AdapterTypeId=
MACAddress=
Name=Broadcom NetXtreme Gigabit
NetConnectionStatus=0
NetEnabled=FALSE
Speed=

AdapterTypeId=15
MACAddress=
Name=Microsoft ISATAP Adapter
NetConnectionStatus=
NetEnabled=
Speed=100000

**Comment by sebhildebrandt** [comment]
Hi @LTBComputers , thank you for providing the detailed information. I will have a look on it a little bit later today. Can you provide two more thing:

**First:**
With wich parameters are you calling the `networkStats()` function?

**second**
```
si.networkInterfaceDefault()
```
What would be the output of this function on your machine ... (I guess it is more related to this function)

**Comment by LTBComputers** [comment]
I was calling it via the si.getAllData function. 

A test script with the following simply returns "undefined"

si.networkInterfaceDefault().then(function(data) {
  console.log(data);
});

**Comment by sebhildebrandt** [comment]
As I thought. One last thing: can you provide the output of 

```
os.networkInterfaces()
```

Thank you in advance.

**Comment by sebhildebrandt** [comment]
@LTBComputers Forgot to mention you ... not sure if you got the message from Github ...

Can you provide the output of

```
os.networkInterfaces()
```
Thank you in advance.

**Comment by sebhildebrandt** [comment]
Fixed `networkInterfaceDefault()` on Windows, so this should work now. Version 4.0.10 just published.

@LTBComputers : more generally (not related to this issue): 

- use `getAllData()` only if you really need this. Especially on Windows this takes really long to get all data. 
- Consider splitting it up to `getStaticData()` - calling this just once (there will be no changes unless you modify hardware and restart machine - and `getDynamicData()`
- for `getDynamicData()` specify the services and network interfaces you want to monitor

**Comment by LTBComputers** [comment]
Thanks! I've updated and can confirm the issue is fixed on the machine that was not working.
