### ISSUE TITLE
Parse Users Windows

### ISSUE THREAD

**Issue by ricardopolo** [sebhildebrandt/systeminformation#207]
When getting users from a Windows System we get
![image](https://user-images.githubusercontent.com/1263856/53267187-ba583e00-36b0-11e9-99c4-e34897f0d8a8.png)

However that is incorrect because its 2:35pm

The command shows the Date correctly 
![image](https://user-images.githubusercontent.com/1263856/53267309-073c1480-36b1-11e9-8153-351d4d4257da.png)
But the parse method thas dot handle it https://github.com/sebhildebrandt/systeminformation/blob/master/lib/users.js#L142-L178

**Comment by sebhildebrandt** [comment]
@ricardopolo ... ahhh, yes you are right, will fix this and infos you when this is done. Thank you for describing the issue.

**Comment by sebhildebrandt** [comment]
Just pushed a fix for that ... V4.0.0.11 released

**Comment by ricardopolo** [comment]
Its working 🥳, thanks!!!
