### ISSUE TITLE
Wireless Network Details

### ISSUE THREAD

**Issue by tonesto7** [sebhildebrandt/systeminformation#208]
**Is your feature request related to a problem? Please describe.**
Love this plugin only item missing for me is more wireless detail.
Is it possible to see more details for the Wireless connections:
* SSID
* SIgnal
* Channel
* Frequency (2.4ghz/5ghz)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sebhildebrandt** [comment]
@tonesto7 this is a great idea! I will think of a solution for that ... already have some ideas. Will inform you when I have something in place. One question: which operating system you are working with?

**Comment by tonesto7** [comment]
I use it with both mac and windows.

I know that the 'node-wifi' module uses `(netsh WLAN show interfaces)` for windows and I'm not sure about mac.

**Comment by sebhildebrandt** [comment]
@tonesto7 thank you for the additional information. Already started to work on it ;-)

**Comment by mwittig** [comment]
On Linux I think it is `iwconfig`

**Comment by mwittig** [comment]
It seems like `netsh WLAN show interfaces` only provides the signal strength as a percent value aka. "signal quality", while linux provides dBm. If you want to convert signal quality to signal strength, the following formula can be applied:

```
dBm = (quality / 2) – 100,
quality: [0-100]
```

See also: https://stackoverflow.com/questions/15797920/how-to-convert-wifi-signal-strength-from-quality-percent-to-rssi-dbm

**Comment by sebhildebrandt** [comment]
@tonesto7 I just released a new version 4.11.0 with a new function to get available wifi networks (with details)

**Comment by mwittig** [comment]
inko, ticket should be kept open as the new function is currently implemented for linux, only

**Comment by sebhildebrandt** [comment]
Will also try to add functionality for BSD. But for now, I think it should be fine.
