### ISSUE TITLE
Change Windows Performance Querying to Calling Win32 APIs instead of using WMIC

### ISSUE THREAD

**Issue by Njanderson** [sebhildebrandt/systeminformation#209]
**Is your feature request related to a problem? Please describe.**
Instead of using WMIC, I propose using a Foreign Function Interface node module to call straight into the performance counters that we want instead of creating a terminal, invoking WMIC, then parsing the results. Then, you would skip a ton of the starting a new process and other inefficiencies that you don't need!

**Describe the solution you'd like**
Use [some win32 ffi project](https://github.com/waitingsong/node-win32-api) to call into native win32 DLLs to get the desired performance information. To show that this request is in good faith, I have a PR out for GetSystemTimes to demonstrate that I can add functionality to the dependent projects.

**Describe alternatives you've considered**
Instead of using an FFI project, it seems like there is also a way of calling straight into compiled DLLs, so then, I could create a dependency on some binaries compiled for each platform, which is sort of what [this project does](https://github.com/SkyLined/cWinPerfCounter). I am happy to work on this as well.

I would love to start working on this, if you're interested, and I can send some PRs to incrementally add this, in a tested fashion, to your project.

Thanks!

**Comment by sebhildebrandt** [comment]
@Njanderson thank you for your comment! Well, I am thinking of moving to native system calls in Windows for some time now. As I want to keep the dependencies in this module as low as possible, this will be a challenge anyway. I am testing some alternatives here already, but each approach has some downsides ... for the moment I will keep on testing different approaches. As long as I do not find a satisfying solution, I will stick to WMIC. Will come back to you, when I make progress here. OK?

**Comment by Njanderson** [comment]
Thanks for the reply! Let me know if you would like help implement anything! Love to help.

**Comment by sebhildebrandt** [comment]
Closing it for now, will reopen it as soon as I have a proper solution

**Comment by Njanderson** [comment]
Any updates on this? I am happy to help!
