### ISSUE TITLE
Race condition?

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#21]
Hi Sebastian,

This issue appears to be similar to #14 which you fixed for us last November.

But in this case it is si.processes() - and _not_ si.currentLoad() - that may prove problematic. I say "may" because I am always willing to allow that this problem is of my making.

My web browser client is presenting 2 d3.js plots simultaneously. In the Node.js backend this is realized as two "overlapped" (roughly concurrent) calls to si.processes(). I will paste in the code below.

If I display the process CPU utilization plot by itself, data values returned by si.processes() seem fine. But if I display both process CPU utilization & the process memory utilization plots at the same time, then the data returned by si.processes() assumes quite a few incorrect values. E.g., "Infinity", "NaN", and negative CPU utilizations.

In the code below, the 2 "collector" functions, one for CPU utilization, the other for memory, run "concurrently" (well, not really, but in the Node.js idiom). Each calls si.processes() and then calls function getProcessesOfInterest .

Thanks for your help.

Cordially,

Paul

```
function collectorProcessCpuUtil(monSessState, publisher)
{
    var cmdProgress = {
       entity: 'process',
       cpu_util: -1,                                                                               
       sid: monSessState.monSid,
       timestamp: (new Date).getTime(),
    };

    var mo = getMetricEntryFromSubDoc(monSessState.subDoc, cmdProgress.entity + '.cpu_util');     
    mo.push = true;   
   
    si.processes().then(data => getProcessesOfInterest('cpu_util', data, cmdProgress, publisher, false))                            
	          .catch(error => logMsg('info', 'process cpu_util si.processes error=' + error));
}


function collectorProcessMemUtil(monSessState, publisher)
{
    var cmdProgress = {
       entity: 'process',
       mem_util: -1,                                                                               
       sid: monSessState.monSid,
       timestamp: (new Date).getTime(),
    };
    
    var mo = getMetricEntryFromSubDoc(monSessState.subDoc, cmdProgress.entity + '.mem_util');     
    mo.push = true;   

    si.processes().then(data => getProcessesOfInterest('mem_util', data, cmdProgress, publisher, false))                            
	          .catch(error => logMsg('info', 'process mem_util si.processes error=' + error));
}


function getProcessesOfInterest(cmdId, data, cmdProgress, publisher, useProcessCache) 
{
	var nodeIp = app.get('localIp');
	var monSessState = app.get(cmdProgress.sid);
	
	var pCache = arrayToHash(data.list, 'pid'); 
	var numCores = monSessState.cpuInfo.cores;   // always 4
	
	var mo = getMetricEntryFromSubDoc(monSessState.subDoc, 'process.' + cmdId);
	var valAr = [];

	mo.pids.forEach(function(wantedPid){
		if ( pCache[wantedPid] )                                                                               // FTI we found pid that caller's interested in                                
		{
			var proc = pCache[wantedPid];                                                                  // get process object given us by si.processes
			
			if ( cmdId == 'cpu_util' )
			{				
			    var temp = parseFloat(numCores*proc.pcpu/100);
			    valAr.push({pid: wantedPid, util: parseFloat(numCores*proc.pcpu/100).toFixed(2)});         // ut returned by si is divided by # cores; undo that to present simpler metric
			}
			
			if ( cmdId == 'mem_util' )
			{
			    var temp = parseFloat(proc.pmem/100);
			    valAr.push({pid: wantedPid, util: parseFloat(proc.pmem/100).toFixed(2)});  				
			}
		}
	});

	cmdProgress[cmdId] = [{time: cmdProgress.timestamp, data: valAr}];
	publisher(cmdProgress);
}
```

**Comment by sebhildebrandt** [comment]
Hi Paul,

thank you for reporting this! I need to go a little deeper into it and will reply to it later. Quite busy at the moment, can take 1 week ... hope that is OK!

**Comment by paul-bell** [comment]
Hi Sebastian,

A week is fine. Please let me know if I can help in any way.

Thanks.

-Paul

**Comment by sebhildebrandt** [comment]
Hello Paul,

I identified the race-condition problem. Definitely my fault :-( 
As I am doing quite a lot changes at the moment (all not stable right now), it will take at least one more week to get it into a new release ... Hope that this is OK.

**Comment by paul-bell** [comment]
Hi Sebastian,

Terrific that you found it; thanks very much.

Another week is fine!

-Paul

**Comment by paul-bell** [comment]
Hi Sebastian,

Any progress on this?

Cordially,

Paul

**Comment by sebhildebrandt** [comment]
Hi Paul,

sorry for the delay … will still need some more days. I will have time next weekend and I’ll promise to release a fix on saturday.

**Comment by paul-bell** [comment]
Thank you, Sebastian.

(BTW: please see e-mail I sent you out-of-band).

-Paul

**Comment by sebhildebrandt** [comment]
Hi Paul,

so changes are done, race condition should not happen again. But anyway I have one suggestion concerning multiple calls to processes. Function like processes, networkStats, fsStats, disksIO, currentLoad are calculating current loads based on some reference point in the past. And this is the last time, you call this certain function. To be more accurate here, I would create kind of a worker which gets those values e.g. every 1 or 2 seconds (or even longer) like so:

```
let processInfo = {};

let worker = setInterval(function() {
	si.processes().then(data => {
		processInfo = data;
	})
}, 2000);
```

And then, if you need process information, you only need to get it from your variable `processInfo`. If you want to stop youtr worker, just call:

```
clearInterval(worker);
```

Hope that makes sense for you.

**Comment by paul-bell** [comment]
Hello Sebastian,

Thank you very much for this fix. I will test it this week.

And, yes, your code example makes perfect sense. Although it can't be
inferred from the code I put in my original post, my code is also timer
driven. I have a dispatch loop that periodically, e.g., at 5 second
intervals, drives functions depending on what metrics a given session
(user) is subscribed to.

Thanks again.

Cordially,

Paul
