### ISSUE TITLE
NetworkInterfaces - Speed in Windows is not displayed correctly

### ISSUE THREAD

**Issue by ldittmar81** [sebhildebrandt/systeminformation#214]
**Describe the bug**
The documentation describes that the speed is displayed in Mbps.

https://github.com/sebhildebrandt/systeminformation/blob/master/docs/network.html#L186

On Linux: OK
![Bild 2](https://user-images.githubusercontent.com/9552828/54959901-ed654a00-4f5a-11e9-839d-6f17ad6a4728.png)

On Windows: Not OK (in Bits/s)
![Bild 1](https://user-images.githubusercontent.com/9552828/54959933-07069180-4f5b-11e9-8721-89a924c887fb.png)

I tried it on a Notebook with Windows 7 and a desktop PC with windows 10.

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**
Windows should show the speed in Mbps.

**Environment (please complete the following information):**
 - systeminformation package version: 4.1.1
 - OS: Windows
 - Hardware: PC Windows 10, Laptop Windows 7

**Comment by sebhildebrandt** [comment]
Thank you for your investigation. Will fix and test it today

**Comment by sebhildebrandt** [comment]
@ldittmar81 : fixed. Version 4.1.4 just published. Thank you for detailed description.

**Comment by ldittmar81** [comment]
Thx 👍
