### ISSUE TITLE
Can't get second display information

### ISSUE THREAD

**Issue by vincenthawke** [sebhildebrandt/systeminformation#215]
Hi!

I was looking for a library to get display resolutions and yours worked very well for my main monitor but sadly didn't return data about my second monitor. Also is there a way to get pixel density information? 

System information:
OS Name:  Microsoft Windows 10 Pro
Version:	  10.0.17763 Build 17763
Monitor 1:  DELL P2415Q   (connected via DP)
Monitor 2:  DELL U2412M (connected via HDMI)
GPU:           NVIDIA GeForce GTX 1070
GPU driver version:   390.77
Node version:            v10.15.3

```
const si = require("systeminformation");

si.graphics()
    .then(data => console.log(data))
    .catch(error => console.error(error));



Console output:
{ controllers:
   [ { model: 'NVIDIA GeForce GTX 1070',
       vendor: 'NVIDIA',
       bus: 'PCI',
       vram: 4095,
       vramDynamic: true } ],
  displays:
   [ { model: '(Standard monitor types)',
       main: false,
       builtin: false,
       connection: '',
       resolutionx: 3840,
       resolutiony: 2160,
       sizex: -1,
       sizey: -1,
       pixeldepth: 32 } ] }

**Comment by sebhildebrandt** [comment]
@vincenthawke: an you provide some more info? Which OS, connected monitors, ... thank you in advance.

**Comment by vincenthawke** [comment]
> @vincenthawke: can you provide some more info? Which OS, connected monitors, ... thank you in advance.

I have updated my post. Thank you very much for such fast reply. Let me know if I am missing any additional information that could be relevant.

**Comment by sebhildebrandt** [comment]
&vincenthawke, thank you for updating your post! This is actually a windows/wmi problem. I still investigate, if there are other options to get information about the second monitor. Will let you know if I find some workaround. Kind regards

**Comment by vincenthawke** [comment]
Ok, thank you very much!

I tried with powershell and it does return correct information for both monitors. Maybe the reason why the resolution is not 3840 x 2160 is due to device pixel ratio being 2x.

`PS> Add-Type -AssemblyName System.Windows.Forms`
`PS> [System.Windows.Forms.Screen]::AllScreens`

```
BitsPerPixel : 32
Bounds       : {X=0,Y=0,Width=1920,Height=1080}
DeviceName   : \\.\DISPLAY1
Primary      : True
WorkingArea  : {X=0,Y=0,Width=1920,Height=1080}

BitsPerPixel : 32
Bounds       : {X=-1920,Y=0,Width=1920,Height=1200}
DeviceName   : \\.\DISPLAY2
Primary      : False
WorkingArea  : {X=-1920,Y=0,Width=1920,Height=1200}
```

**Comment by sebhildebrandt** [comment]
@vincenthawke : Ok, now I found a possibility to return back all monitors with some additional information. Will provide a fix for that later this week. Working on refactoring the window section of parsing all graphics data. Sorry for the delay!

**Comment by sebhildebrandt** [comment]
@vincenthawke I already have some improved code in place here on GitHub. So if you like to test it (clone git repo), I would be happy to get your results. Thank you in advance.

**Comment by sebhildebrandt** [comment]
Version 4.10.0 just released with detection of multiple monitors on windows
