### ISSUE TITLE
SwapUsed is wrong (SwapCached != SwapUsed)

### ISSUE THREAD

**Issue by ldittmar81** [sebhildebrandt/systeminformation#219]
**Describe the bug**
https://github.com/sebhildebrandt/systeminformation/blob/master/lib/memory.js#L155

At this line you use SwapCached as used, but that is wrong. As described on LinuxWiki.org, SwapCached is: "Speicher, der ausgelagert und bereits wieder eingelagert wurde und im Swapbereich noch nicht überschrieben ist. Wird neuer freier Speicher benötigt, muss der Speicher im Swap-Cache nicht erneut auf Platte geschrieben werden. Damit wird Platten-I/O gespart." (https://linuxwiki.de/proc/meminfo)

SwapUsed should be (SwapTotal - SwapFree)

**To Reproduce**
You can read our discussion here: https://forum.iobroker.net/topic/9041/adapter-iobroker-info/256

**Current Output**
SwapUsed is wrong

**Expected behavior**
SwapUsed should be (SwapTotal - SwapFree)

**Environment (please complete the following information):**
 - systeminformation package version: 4.1.4
 - OS: linux
 - Hardware: Raspi 3

**Comment by sebhildebrandt** [comment]
@ldittmar81 ... thank you for your comment! Will check it ...

**Comment by sebhildebrandt** [comment]
@ldittmar81 You were absolutely right! Fixed, version 4.1.6 just published!

**Comment by ldittmar81** [comment]
You are faster than the Flash! :sunglasses:  Thanks!
