### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#22]
Hi Sebastian,

When you are able to address issue #21 might you be able to make a modest (I think) enhancement to the list of process properties returned by si.processes(cb)?

Specifically, could that list include for each returned process object not only pcpu, but its decomposition into system (kernel) CPU utilization and user CPU utilization? 

Not that you need it, but vide: http://unix.stackexchange.com/questions/132035/obtain-user-and-kernel-time-of-a-running-process

Thanks.

-Paul

**Comment by sebhildebrandt** [comment]
And one more comment ;-)

Yes, this is definitely interesting. I will figure out a way (at least for linux) to extend system and user CPU utilization. As mentioned in [#21](https://github.com/sebhildebrandt/systeminformation/issues/21), this will take a little while ...

**Comment by paul-bell** [comment]
Great; thanks again!

-Paul

**Comment by sebhildebrandt** [comment]
Hi Paul, once again ;-)

So also the extension in the process list is done now:

In the process list (result.list) you get per process the following:

- ...[0].pid: process PID
- ...[0].pcpu: process % CPU usage
- ...[0].pcpuu: process % CPU usage (user)	--> NEW
- ...[0].pcpus: process % CPU usage (system)	--> NEW
- ...[0].pmem: process memory %
- ...[0].priority: process priotity
- ...[0].mem_vsz: process virtual memory size
- ...[0].mem_rss: process mem resident set size
- ...[0].nice: process nice value	--> NEW
- ...[0].started: process start time
- ...[0].state: process state (e.g. sleeping)
- ...[0].tty: tty from which process was started

Hope that this is, what you wanted

**Comment by paul-bell** [comment]
And, once again ;-) thank you for this enhancement.

I will this week incorporate it into a d3.js visualation of process CPU
time.

Cordially,

Paul
