### ISSUE TITLE
networkStats function takes 5 to 10 seconds to respond

### ISSUE THREAD

**Issue by hemicharly** [sebhildebrandt/systeminformation#221]
Using the networkStats function, with wireless and lan disabled or using network connectivity with a **HGW-2501GNP-RC** router, everything works correctly.

I needed to connect another **TP LINK WR849N** router, without internet access. Then the problem started, investigating the cause of the problem I discovered the exact location that causes the slowness in the function.

**What was checked**:
When calling the networkStats function it will call the function
getDefaultNetworkInterface responsible for searching the network ifaces. In the getDefaultNetworkInterface function runs the following command for the linux operating system: 

`if (_linux) cmd = 'route 2> / dev / null | grep default | awk \ '{print $ 8} \' ';`

When trying to execute this command is where slow occurs, running the function at the command terminal, slowness also occurs. Searching I found another command that also returns the ifaces and solved my problem in all scenarios.

**Here is the command that was replaced and worked**: 
`if (_linux) cmd = 'ip route | grep default | awk \ '{print $ 5} \' ';`

If it has no impact on the library and you want to change the fonts. If anyone has any other suggestions for this problem I also accept.

I am using the Linux operating system **Ubuntu 16.04**

Thanks

**Comment by sebhildebrandt** [comment]
@hemicharly Thank you for your investigation!!! Will test it here on some machines and if there is no impact this seems to be a quite good solution. Will send a message as soon as I am done ...

**Comment by hemicharly** [comment]
Thank you, I await your return.

**Comment by sebhildebrandt** [comment]
Seems to work great! Thank you! Version 4.2.1 just published
