### ISSUE TITLE
add Service Pack info in os release

### ISSUE THREAD

**Issue by Rodrigo54** [sebhildebrandt/systeminformation#222]
Add service pack information in the osinfo release field for windows

exemple: `Build 7601 Service Pack 1`

**Comment by sebhildebrandt** [comment]
@Rodrigo54: in `osInfo()` I now added a new attribute `servicepack` which returns major and minor version of service pack (but I guess this will only apply to older Windows versions and will be `0.0` now on Windows 10). Version 4.2.0 just published
