### ISSUE TITLE
Get user time and date in null

### ISSUE THREAD

**Issue by ncampuzano** [sebhildebrandt/systeminformation#223]
**Describe the bug**
I'm using the function `si.users()`. The function returns me the user logged but without date and time properties

**To Reproduce**
1. Used function:  'si.users()'

**Current Output**
I printed the result of 'si.users()'
![image](https://user-images.githubusercontent.com/5368137/57328082-13434a00-70d6-11e9-9c84-63b301a7fd38.png)

**Expected behavior**
To get the date and time for user "user". Because this user is logged 

**Environment (please complete the following information):**
 - systeminformation package version: 4.1.6
 - OS: Windows 10 64bits

**Comment by sebhildebrandt** [comment]
@ncampuzano thank you for your description. Can you provide the output of the following command:

```
query user
```

Thank you in advance

**Comment by ncampuzano** [comment]
I got this: 

![image](https://user-images.githubusercontent.com/5368137/57331765-0414ca00-70df-11e9-95d8-9046c8f3cd63.png)

**Comment by sebhildebrandt** [comment]
Ok. Thank you!! Will try to solve it.

**Comment by sebhildebrandt** [comment]
@ncampuzano : I adapted the parsing, ... not sure if this works. May I asked if you can grab the latest code from GitHub ( corrected `lib/utils.js` and `lib/users.js`) and try it with this?

**Comment by sebhildebrandt** [comment]
Publishes new version 4.1.7 ... should work now.

**Comment by ncampuzano** [comment]
I could test in the affected computer and all it's okey with new version. Thanks
