### ISSUE TITLE
si.system() is not workig in windows

### ISSUE THREAD

**Issue by techterbium** [sebhildebrandt/systeminformation#225]
**si.system() is not working in windows 8**
Thank you for this wonderful library giving us elaborative information about the system.
I ran below code in windows 8. However, mentioned properties of `data` is null or empty.

`si.system().then(data => {
            console.log("System Serial Number - ", data.serial);
            console.log("UUID                 - ", data.uuid);
            console.log("Manufacturer         - ", data.manufacturer);
        })`

**Current Output**
si.system() is returning an object with empty properties

**Expected behavior**
si.system() is expected to return all documented properties

**Environment (please complete the following information):**
 - OS: Windows 8

**Additional context**

**Comment by sebhildebrandt** [comment]
Will try to check it ... sorry for the inconvenience

**Comment by sebhildebrandt** [comment]
@techterbium : three questions 

- is this the only function (that should return values for windows) that returns an empty object?
- hat windows version / build you are using exactly?
- you are using the latest version of systemInformation 4.5.1?

Thank you in advance

**Comment by techterbium** [comment]
@sebhildebrandt -

- I just used si.system() for now. I am not aware of other functions. Sorry.
- Windows 8.1
- Yes.

**Comment by sebhildebrandt** [comment]
@techterbium : I tested it now on several windows 7 and windows 10 machines and this works. So it would be good to get some more input:

- Can you tell me also, which version of node you are using?
- in your command line, what would be the output of `wmic csproduct get /value`
- can you try at least one or two more si functions using wmic e.g.:

```
si.bios()
    .then(data => console.log(data))
    .catch(error => console.error(error));
```
or 
```
si.baseboard()
    .then(data => console.log(data))
    .catch(error => console.error(error));
```
Thank you in advance

**Comment by sebhildebrandt** [comment]
@techterbium would it be possible to provide some additional information as mentioned above? Would help to identify the problem. Thank you in advance.

**Comment by sebhildebrandt** [comment]
@techterbium : I changed now a bit using `wmic` (the underlying command) ... is it possible to test it once again with version 4.7.0?

**Comment by sebhildebrandt** [comment]
@techterbium ... as all my tests are fine here and I did not get feedback, I would like to close the issue

**Comment by techterbium** [comment]
@sebhildebrandt , sorry for my detailed response. Yes, please close the issue. I was able to resolve my issue by adding **;%SystemRoot%\System32\Wbem** to window's environment variables.

**Comment by sebhildebrandt** [comment]
@techterbium , ok, fine. Thank you for your reply. I also changed the way `WMIC` is called. So this should now also work without having to explicitly adding this path to your env variables.
