### ISSUE TITLE
getWMIC does not return the correct path when multiple WMIC files are found in system32

### ISSUE THREAD

**Issue by jcolemn3** [sebhildebrandt/systeminformation#227]
**Describe the bug**
I have found a use-case where some user machines have WMIC files in both the Windows/System32 and Windows/System32/wbem directories. When the path is returned, the array of paths are concatenated and returned as the wmicPath. When the wmic function is called with the concatenated paths, an error occurs and the empty object is returned. If the wmic.exe will always be at system32\\wbem, why would we need to do a query to find all of the paths via execSync("WHERE WMIC")? Unless, there is some use-case I am not thinking about.

**To Reproduce**
1. Add dummy WMIC.exe file to System32 folder
2. now call system() method

**Current Output**
`{
manufacturer: ""
model: ""
serial: ""
sku: ""
uuid: ""
version: ""
}`

**Expected behavior**
I expect the system() function to return valid values from the WMIC query. 

**Environment (please complete the following information):**
 - systeminformation package version: 4.6.0
 - OS: windows 10
 - Hardware: HP

**Additional context**
If we know the WMIC.exe will always be at system32\\wbem, why would we need the "WHERE WMIC" query

```javascript
function getWmic() {
  if (os.type() === 'Windows_NT' && !wmicPath) {
    try {
      wmicPath = execSync('WHERE WMIC').toString().trim();  // << Couldn't we get rid of this
    } catch (e) {
     // And use the below as the default
      if (fs.existsSync(process.env.WINDIR + '\\system32\\wbem\\wmic.exe')) {
        wmic = process.env.WINDIR + '\\system32\\wbem\\wmic.exe';
      } else wmicPath = 'wmic';
    }
  }
  return wmicPath;
}
```

**Comment by sebhildebrandt** [comment]
@jcolemn3 Just to be sure, what would be the output of `WHERE WMIC` in this special case?

**Comment by sebhildebrandt** [comment]
OK, I see the problem already ... will fix this - but still with a fallback ;-)

**Comment by sebhildebrandt** [comment]
Fixed ... version 4.6.1 just published

**Comment by jcolemn3** [comment]
thanks for the quick response. I appreciate it
