### ISSUE TITLE
windows systeminformation

### ISSUE THREAD

**Issue by liseen315** [sebhildebrandt/systeminformation#23]
Hello！
Whether there is support for Windows plans？

**Comment by sebhildebrandt** [comment]
Yes! Just started to work on this. First very basic functionality will be available soon. 

Best regards

**Comment by liseen315** [comment]
Look forward to release！Thanks

**Comment by sebhildebrandt** [comment]
Hi,

very first windows support (just a few functions) is online now. But this needs some more testing. I will do those tests plus implement some more functions in the next two weeks. So please be a little patient ;-) and stay tuned.
