### ISSUE TITLE
networkStats responds with default data each time (Windows 10)

### ISSUE THREAD

**Issue by Stetchy** [sebhildebrandt/systeminformation#233]
**Describe the bug**
When using networkStats on Windows 10 the object returned contains the default data each time e.g. -1 for rx/tx per second, unknown operstate etc. 

For example: `{
    iface: "wi-fi"
    ms: 0
    operstate: "unknown"
    rx_bytes: 0
    rx_dropped: 0
    rx_errors: 0
    rx_sec:
        -1
    tx_bytes: 0
    tx_dropped: 0
    tx_errors: 0
    tx_sec:
        -1
}`

**To Reproduce**
Run a simple loop, like the following:
```js
import * as si from 'systeminformation';

let interval = setInterval(()=> {
    si.networkStats().then((data) => console.log(data[0]);
}, 1000);
```
or, in my case a simple React component, like the following:

```jsx
import React, { Component } from "react";
import * as si from "systeminformation";

export default class Network extends Component {
  constructor(props) {
    super(props);
    this.state = {
      up: 0,
      down: 0
    };
    this.getRates = this.getRates.bind(this);
  }

  componentDidMount() {
    this.getRates();
    this.interval = setInterval(() => this.getRates(), 1000);
  }

  componentWillUnmount() {
    clearInterval(this.interval);
  }

  getRates() {
    si.networkStats("Wi-Fi", rates => {
      console.log(rates[0]);
    });
  }

  render() {
    const { up, down } = this.state;
    return (
      <React.Fragment>
        {down} {up}
      </React.Fragment>
    );
  }
}
```

**Current Output**
Object: `{
    iface: "wi-fi"
    ms: 0
    operstate: "unknown"
    rx_bytes: 0
    rx_dropped: 0
    rx_errors: 0
    rx_sec:
        -1
    tx_bytes: 0
    tx_dropped: 0
    tx_errors: 0
    tx_sec:
        -1
}`

**Expected behavior**
Expected behaviour is to return the actual network data, not the defaults.

**Environment (please complete the following information):**
 - systeminformation package version: v4.9.0
 - OS: [e.g. macOS] Windows 10 v1903
 - Hardware [e.g. MacBook Pro 13] Dell XPS 15 

**Additional context**

**Comment by Stetchy** [comment]
Found the issue, submitted a PR in #234

**Comment by sebhildebrandt** [comment]
Fixed ... version 4.9.1 just released.
