### ISSUE TITLE
typescript: diskLayout function callback should accept a DiskLayoutData array

### ISSUE THREAD

**Issue by benjismith** [sebhildebrandt/systeminformation#235]
**Describe the bug**

The typescript definition of the `diskLayout` function doesn't match the behavior of the actual javascript code. The type definitions indicate the function accepts a callback/promise with a single instance of a `Systeminformation.DiskLayoutData` object. But the javascript code actually passes a `Systeminformation.DiskLayoutData[]` array...

**To Reproduce**

Attempt to use the diskLayout function from typescript code. Observe at runtime an array, instead of a single object, being passed into the callback.

**Expected behavior**

The type definition looks like this:

```
export function diskLayout(cb?: (data: Systeminformation.DiskLayoutData) => any)
  : Promise<Systeminformation.DiskLayoutData>;
```

...but it should be this instead...

```
export function diskLayout(cb?: (data: Systeminformation.DiskLayoutData[]) => any)
 : Promise<Systeminformation.DiskLayoutData[]>;
```

**Environment (please complete the following information):**
 - systeminformation package version: 4.9.1
 - OS: any
 - Hardware: any

**Comment by sebhildebrandt** [comment]
Fixed ... version 4.9.2 just released
