### ISSUE TITLE
Plug n play : detect pen drive/ cd drive on connect 

### ISSUE THREAD

**Issue by bebekar** [sebhildebrandt/systeminformation#236]
** As is **
I scan the system and get the information and use it on the status reported. 
** Just in case ... ** 
In case i attached a external devise, I will have to refresh the scanned info to know of the device
** what I am looking for ** 
Is there a way that the system  can provide a event/trigger to state that the change (Hardware, OS, Memory, ...)  has happened?  may be an IRQ

**Comment by sebhildebrandt** [comment]
@bebekar : Thank you, gird idea ... will think of it ...

**Comment by bebekar** [comment]
You are always welcome. Have a great day

**Comment by sebhildebrandt** [comment]
@bebekar  So as node.js is not aware of any IRQs the only way to do this is by observing values. 

`systeminformation`now comes with an `observe` function where you can easily detect changes ... here in the docs https://systeminformation.io/statsfunctions.html you have an example, where I observe if a AC connector is plugged into a laptop ... same could be done for whatever change you want to observe (in conjunction with the new `get()` function where you can define to just get back specific parts of a result set)

Hope this helps. Closing it for now.
