### ISSUE TITLE
New feature "wifiNetworks()" does not work ES6 spread operator is not supported with with Node v4

### ISSUE THREAD

**Issue by mwittig** [sebhildebrandt/systeminformation#239]
**Describe the bug**

New feature "wifiNetworks()" does not work with Node v4 as the code uses ES6 spread operator

**To Reproduce**
1. Use Node.js v4.9.1
2. Run the following code snippet:

```
var si = require('systeminformation');
si.wifiNetworks().then(function (data) {
  console.log('Wifi Network Interfaces: ' + data.map(el => el.ssid).join(", "));
});
```

**Current Output**

```
                  wpaFlags = [...new Set(wpaFlags)];
                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\marcus\IdeaProjects\systeminfo\node_modules\systeminformation\lib\index.js:34:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
``` 
**Expected behavior**

Output the list of SSIDs detected by the system

**Environment (please complete the following information):**
 - systeminformation package version: 4.11.1 (latest)
 - OS: Win10
 - Hardware Lenovo

**Additional context**

The problem is that the ES6 spreadify operator is not supported  by Node.js v4. In the given context I am confident you can simply replace it with `Array.from()` which is also easily polyfillable if you want to support Node.js version earlier than 4.9.1. ~~I'll file a PR shortly.~~

**Comment by mwittig** [comment]
I'll not file a PR as the code change is part of the code for "_darwin" and I have not MacOS at hand to test the suggested code changes. Here the suggested code change:

git -p diff lib\wifi.js
```
diff --git a/lib/wifi.js b/lib/wifi.js
index 64ca3b5..55365a9 100644
--- a/lib/wifi.js
+++ b/lib/wifi.js
@@ -171,7 +171,7 @@ function wifiNetworks(callback) {
                       wpaFlags = wpaFlags.concat(parts[1].replace(')', '').split(','));
                     }
                   });
-                  wpaFlags = [...new Set(wpaFlags)];
+                  wpaFlags = Array.from(new Set(wpaFlags));
                   result.push({
                     ssid: line.substring(parsedhead[0].from, parsedhead[0].to).trim(),
                     bssid: line.substring(parsedhead[1].from, parsedhead[1].to).trim(),

**Comment by sebhildebrandt** [comment]
Thank you @mwittig ... fixed both bugs. v 4.11.2 just released
