### ISSUE TITLE
WifiNetworks() returns empty list on Raspbian Stretch

### ISSUE THREAD

**Issue by mwittig** [sebhildebrandt/systeminformation#240]
**Describe the bug**
WifiNetworks() returns empty list on Raspbian Stretch

**To Reproduce**
1. Execute the following code-snippet

``` 
var si = require('systeminformation');
si.wifiNetworks().then(function (data) {
  console.log('Wifi Networks: ' + data.map(el => el.ssid).join(", "));
});
```

**Current Output**
Outputs an empty list of Wifi Networks

**Expected behavior**
Should output all Wifi Networks in reach

**Environment (please complete the following information):**
 - systeminformation package version: 4.11.2
 - OS: Raspbian Stretch Lite (kernel 4.19.42-v7+)
 - Hardware: Raspberry Pi 3

**Additional context**

Note, the `nmcli` command line tool is not installed on Raspbian. At least, the Lite edition for headless installs does not contain it. Thus, the `network-manager` package needs to be installed. This should be documented (known issues section, at least). 

Running nmcli does not prompt any results in my case. If I query the Wifi-Network Interface using `iwconfig` I get information for the bound Wifi network.

```
pi@raspberrypi:~/systeminformation $ sudo nmcli --terse --fields active,ssid,bssid,mode,chan,freq,signal,security,wpa-flags,rsn-flags device wifi list
pi@raspberrypi:~/systeminformation $
pi@raspberrypi:~/systeminformation $ iwconfig
docker0   no wireless extensions.

lo        no wireless extensions.

veth9fb120c  no wireless extensions.

wlan0     IEEE 802.11  ESSID:"ethereal"
          Mode:Managed  Frequency:2.437 GHz  Access Point: XX:XX:XX:XX:XX:XX
          Bit Rate=65 Mb/s   Tx-Power=31 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=70/70  Signal level=-28 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
...

**Comment by sebhildebrandt** [comment]
@mwittig, OK, I see. I will do a fallback to handle also situations where `nmcli` returns nothing. Makes absolutely sense.

**Comment by mwittig** [comment]
Honestly, I am not familiar with network-manager. What do I need to execute? 

I have queried the nmcli device status command which flags wlan0 as "unavailable" which appears odd to me as the network interface is bound (it has an IP address which has been obtained from the network AP). Looks to me like the network manager is missing something?!

```

`pi@raspberrypi:~/systeminformation $ nmcli dev status
DEVICE       TYPE      STATE        CONNECTION
docker0      bridge    connected    docker0
eth0         ethernet  connected    eth0
veth0695379  ethernet  connected    veth0695379
veth27d6cc5  ethernet  connected    veth27d6cc5
veth2b79d7e  ethernet  connected    veth2b79d7e
veth9fb120c  ethernet  connected    veth9fb120c
vetha58d97b  ethernet  connected    vetha58d97b
vetha7d6142  ethernet  connected    vetha7d6142
wlan0        wifi      unavailable  --
lo           loopback  unmanaged    --

**Comment by sebhildebrandt** [comment]
@mwittig : Will make a little more investigation on this. Please give me some days to provide a solution.

**Comment by mwittig** [comment]
No worries. Thanks for looking into this.

I did some Google-Research on the matter and tried various things I found in the post with no luck. Seems like all recipes are either outdated or not applicable for my Stretch Lite setup. The basis problem seems to it is not possible to have two network management services managing the wifi adapter. I'll extend this post later on with the links I have followed and tried so far.

**Comment by koraniar** [comment]
I have the same problem in **Linux**:
- systeminformation package version: 4.14.3
- OS: Ubuntu 18.04.2 LTS
- Hardware: Laptop Dell Latitude E6420

With the difference that `nmcli` works for me, the command `sudo iwlist scan` also works.

**Comment by mwittig** [comment]
Any news on this one?

**Comment by mwittig** [comment]
@sebhildebrandt What is the status on this issue, please? As discussed earlier the solution based `nmcli` does not work on Raspbian, at least. A solution would be to use  `sudo iwlist scan`  instead.

**Comment by sebhildebrandt** [comment]
@mwittig next week I will have some time to work on this. Now 2 different Raspberry PIs here to be able to test it. Sorry for the delay.

**Comment by mwittig** [comment]
Ok, no worries. Looking forward to your findings! I haven't re-tested yet on buster which you probably want to use as a basis for your tests rather than stretch

**Comment by sebhildebrandt** [comment]
@mwittig So I made some investigations and I think I have a way here to get the needed information. Need to implement that and test it here locally. Maybe I will be able to finish it tomorrow.

**Comment by sebhildebrandt** [comment]
@mwittig late answer but now I released version. 5 of systeminformation and just also implemented a wifi detection if nuclei is not installed. 

Be aware: Version 5 is NOT fully backwards compatible to version 5 ... see https://systeminformation.io/changes.html to get an overview over all breaking changes.
