### ISSUE TITLE
Environment locale gets overwritten when requiring/importing package

### ISSUE THREAD

**Issue by AxelTerizaki** [sebhildebrandt/systeminformation#242]
**Describe the bug**
Environment's variable LANG gets overwritten to en_US.UTF-8 as soon as the package systeminformation is required or imported.

**To Reproduce**
Here's a simple JS code :
```JS
process.env.LANG="fr_FR.UTF-8"; // something other than en_US.UTF-8
console.log(process.env.LANG); // should display fr_FR.UTF-8
const si = require('systeminformation');
console.log(process.env.LANG); // should display en_US.UTF-8
```

**Expected behavior**
Environment variable shouldn't be overwritten

**Environment (please complete the following information):**
 - systeminformation package version: 4.11.4
 - OS: [e.g. macOS] Windows 7 Pro (french)
 - Hardware [e.g. MacBook Pro 13] : not applicable
 - Node version : v12.2.0

**Additional context**

I found out this bug while developing my app : it wouldn't detect the right locale on my system (I use process.env for that)

I often update my dependencies to the latest versions so I'm not sure when this bug has been introduced, but I located it by digging into systeminformation's code : 

In `lib/util.js`, line 36-41 :

```JS
const execOptsWin = {
  windowsHide: true,
  maxBuffer: 1024 * 2000,
  encoding: 'UTF-8',
  env: util._extend(process.env, { LANG: 'en_US.UTF-8' })
};
```

The last line causes process.env to be modified. Note that Node documentation specifies util._extend is deprecated and that object.assign() should be used instead, but it's giving the same result.

It ultimately causes issues for apps on non-english systems. Not sure of how to fix this or else I'd be offering a PR, sorry...

**Comment by mwittig** [comment]
I can't reproduce this behavior. I am running on Windows 10 (DE) with node 12.2.0

```
>node
Welcome to Node.js v12.2.0.
Type ".help" for more information.
> process.env.LANG="fr_FR.UTF-8"; // something other than en_US.UTF-8
'fr_FR.UTF-8'
> console.log(process.env.LANG); // should display fr_FR.UTF-8
fr_FR.UTF-8
undefined
> const si = require('systeminformation');
undefined
> console.log(process.env.LANG); // should display en_US.UTF-8
fr_FR.UTF-8
undefined
>

**Comment by sebhildebrandt** [comment]
Let me check this here on my machines ...

**Comment by mwittig** [comment]
I think I found the suspect

https://github.com/sebhildebrandt/systeminformation/blame/master/lib/util.js#L39-L40

Possible fix:

```
util._extend({}, process.env, { LANG: 'en_US.UTF-8' })

**Comment by AxelTerizaki** [comment]
I just tried on my home Win 10 machine and it doesn't work (LANG is not being overwritten) which makes me quite curious as to what causes this issue exactly. (Windows 10 / Node 10.15)

If I try to use util._extend directly, it does overwrite the locale though.

```
> console.log(process.env.LANG);
fr_FR.UTF-8
undefined
> const si = require('systeminformation');
undefined
> console.log(process.env.LANG);
fr_FR.UTF-8
undefined
```

```
> util._extend(process.env, {LANG: "en_US.UTF-8"});
...
> console.log(process.env.LANG);
en_US.UTF-8
undefined
```

@wmittig 's solution seems like a good possible fix to me, as the purpose is to get a copy of process.env with the en LANG.

**Comment by sebhildebrandt** [comment]
Will test @mwittig 's suggestion ...

**Comment by sebhildebrandt** [comment]
Fixed, together with another issue. Version 4.11.5 just released

**Comment by AxelTerizaki** [comment]
That was fast! Thank you lots!

**Comment by mwittig** [comment]
Seems like you don't like/accept PRs (52 of 53 PR closed, 1 merged)!
Note you can also manually merge contributor's commits

**Comment by mwittig** [comment]
NB. Besides accepting PRs, manually merging related commits, you can let github create patch files to copy in code changes.
