### ISSUE TITLE
[FeatureRequest] Has wifi and current connections

### ISSUE THREAD

**Issue by koraniar** [sebhildebrandt/systeminformation#246]
**Is your feature request related to a problem? Please describe.**
When I run `si.wifiNetworks()` in a computer without a wireless card, it responses with an empty array, that's right, but I do not know if there are no wifi networks near or if the device doesn't have a wireless card.

**Describe the solution you'd like**
- A way to know if the computer has a wireless card.
- A way to know which wifi networks the computer is connected to.

**Comment by sebhildebrandt** [comment]
@koraniar : Good idea! will try to get this done this weekend.

**Comment by mwittig** [comment]
It would also be nice to get the detailed information about the connected Wifi-Networks, e.g. signal strength, quality, frequency etc. It should be a detailed status view on the wireless adapter network interface(s) of the system:
* Wireless network interface(s) configured on the system
* For each interface get the network status, i.e. SSID and further details like signal strength of the connected network (if connected) 

On linux you can get such a view with `iwconfig`.  An example on how this can be wrapped up can found [here](https://github.com/bakerface/wireless-tools/blob/master/iwconfig.js) as part of the [wireless-tools](https://github.com/bakerface/wireless-tools) project.

**Comment by sebhildebrandt** [comment]
Started to work on it :-)

**Comment by koraniar** [comment]
@sebhildebrandt you can also show the saved password of the wireless network taking a look to this component [wifi-password](https://github.com/kevva/wifi-password) 🙂

**Comment by ricardopolo** [comment]
Hello @sebhildebrandt  Any progress regarding to this issue?

Thank you so much!!

**Comment by sebhildebrandt** [comment]
Currently on holiday. But started to work on this. Hope to finish it in the next two weeks

**Comment by ricardopolo** [comment]
Hello @sebhildebrandt. Have you have time this 6 months for doing that?

Showing a current network, current password and hasWifi option would be awesome!

Thank you!!

**Comment by sebhildebrandt** [comment]
@ricardopolo  Sorry for the delay. I started again on this yesterday and I am currently working on improving 

- `networkInterfaces()` ... which in some cases do not show all interfaces (e.g. the wireless interfaces if they are not connected)
- `wifiNetworks()` to add attributes to see if computer is connected to a specific network

Regards

**Comment by nicsaul** [comment]
Do we have a feature to know the connected wifi? Thanks!

**Comment by fgroupindonesia** [comment]
> It would also be nice to get the detailed information about the connected Wifi-Networks, e.g. signal strength, quality, frequency etc. It should be a detailed status view on the wireless adapter network interface(s) of the system:
> 
> * Wireless network interface(s) configured on the system
> * For each interface get the network status, i.e. SSID and further details like signal strength of the connected network (if connected)
> 
> On linux you can get such a view with `iwconfig`. An example on how this can be wrapped up can found [here](https://github.com/bakerface/wireless-tools/blob/master/iwconfig.js) as part of the [wireless-tools](https://github.com/bakerface/wireless-tools) project.

yeah you're right... which one the status of current connected WIfi ? we don't know from here....

**Comment by sebhildebrandt** [comment]
@koraniar @mwittig @ricardopolo @fgroupindonesia I just added two more wifi functions: `wifiInterfaces()` to get all wifi interfaces (then you can see if there ARE interfaces, and `wifiConnections()` to get detailed information if you are connected to a WIFI. Version 5.2 just released.
