### ISSUE TITLE
[FeatureRequest] Get the gateway of my network interface

### ISSUE THREAD

**Issue by koraniar** [sebhildebrandt/systeminformation#247]
**Is your feature request related to a problem? Please describe.**
This is important to know which is the router in the network and make a network map.

**Describe the solution you'd like**
Get the default gateway of each network interface,

**Comment by sebhildebrandt** [comment]
@koraniar : Also a nice idea! Actually trying to figure out how this can be done consistently across platforms.

**Comment by koraniar** [comment]
@sebhildebrandt you can take a look at this project [node-default-network](https://github.com/mh61503891/node-default-network), I have tested it on Windows and Mac OS and works well 🙂.

**Comment by forwardcomputers** [comment]
This is what I use to get the default gateway.
```
darwin: route -n get default | awk '/gateway/ {print $2}'
linux: ip route get 1 | awk '/via/ { f=NR } f&&NR-1==f' RS=" "
windows: powershell "(Get-CimInstance -ClassName Win32_IP4RouteTable | Where-Object { $_.Destination -eq '0.0.0.0' -and $_.Mask -eq '0.0.0.0' }).InterfaceIndex"
```

**Comment by sebhildebrandt** [comment]
Will check it. Thank you!!

**Comment by sebhildebrandt** [comment]
@koraniar sorry for taking such a long time. I just implemented first version, need to test it a little bit. Will release it next weekend.

**Comment by sebhildebrandt** [comment]
@koraniar ... version 4.16.0 just published
