### ISSUE TITLE
How to use import systeminformation on react.js project

### ISSUE THREAD

**Issue by MarkoGolden** [sebhildebrandt/systeminformation#25]
Hi,
I can't import this syteminformation.js on my react.js project. I worked this on Mac OS 10.11.6.
After run 'npm install systeminformation --save" command, I added a line in my line:
import si from 'systeminformation';

Then I got issue: 
ERROR in ./ ~ /systeminformation/lib/cpu.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/smc in /Users/pascal/Sites/key/keytabs/node_modules/systeminformation/lib
 @ ./ ~ /systeminformation/lib/cpu.js 251:18-49

Please help me how to fix this issue.

**Comment by sebhildebrandt** [comment]
Hi, 

not sure, if I understand you correctly. So some questions: As you described it as a react.js project, is this a server app or a client app, where you are trying to import systemInformation? This will for sure not work in a client app. 

If this occurs on server side: do you use typescript? Which node version do you use? On server side, I did not tested the new module support in Node 7.4.

one more thing: do you see files in node_modules/systeminformation/build/Release/smc ?? If not, maybe your install failed ... could you please check that one more time?

**Comment by sebhildebrandt** [comment]
Hi again, 
did you solved your problem already? Then I will close this issue here.

**Comment by acds** [comment]
Hi @sebhildebrandt still working through it, will post resolution here.
