### ISSUE TITLE
Network connection array limited by shell exec buffer of 2 MB

### ISSUE THREAD

**Issue by jhuckaby** [sebhildebrandt/systeminformation#250]
**Describe the bug**

Hello, and thank you for developing `systeminformation`.  One of my users discovered that on servers with a large number of concurrent open network connections (10K+), systeminformation fails to enumerate them.  We believe the culprit is this hard-coded 2 MB limit when you shell out to netstat here:

https://github.com/sebhildebrandt/systeminformation/blob/master/lib/network.js#L719

```js
exec(cmd, { maxBuffer: 1024 * 2000 }, function (error, stdout) {
```

And here:

https://github.com/sebhildebrandt/systeminformation/blob/master/lib/network.js#L810

```js
exec(cmd, { maxBuffer: 1024 * 2000 }, function (error, stdout) {
```

Would it be possible to increase this arbitrary byte limit, possibly to 20MB, or even make it configurable?

Thank you for an awesome module!

**To Reproduce**
1. Run systeminformation on a server with 10K+ concurrent network connections

**Current Output**
The array returned from `si.networkConnections(cb)` is empty.

**Expected behavior**
The array should contain all the open network connections.

**Environment (please complete the following information):**
 - systeminformation package version: 4.0.10
 - OS: Linux
 - Hardware: Unknown

**Additional context**
Reference issue: https://github.com/jhuckaby/performa-satellite/issues/1
cc @asyslinux

**Comment by sebhildebrandt** [comment]
@jhuckaby : Yes, I will do this ... please wait a second

**Comment by sebhildebrandt** [comment]
@jhuckaby Done ... version 4.12.0 just released

**Comment by jhuckaby** [comment]
Fastest issue fix EVER.  Thank you!!!
