### ISSUE TITLE
Full command line in command fields for processes

### ISSUE THREAD

**Issue by mnizhnikov** [sebhildebrandt/systeminformation#254]
Is it possible to have full command line information for processes on Mac machines? Name and command fields contain the same data right now . E.g. 
`  { 
    pid: 432,
    ppid: 424,
    name: 'mongod',
    started: '2019-06-24 14:09:26',
    command: 'mongod'
   }` 
I think, it is because -c parameter in the executed command
`if (_darwin) cmd = 'export LC_ALL=C; ps -acxo pid,ppid,pcpu,pmem,pri,vsz,rss,nice,lstart,state,tty,user,command -r; unset LC_ALL';`

>  -c    Change the `command' column output to just contain the executable name
           rather than the full command line.

It would be great for us also know some processes paths for furthest filtering and have output like this:

`  { 
    pid: 432,
    ppid: 424,
    name: 'mongod',
    started: '2019-06-24 14:09:26',
    command: '/dataService/mongodb/mongod --config /Applications/mongodb/config.cfg',
   }` 

 - systeminformation package version: 4.1.6
 - macOS

I also created small patch to achieve such behaviour. Maybe it is good start point to enhance your nice module a bit
[_darwinCommands.patch.txt](https://github.com/sebhildebrandt/systeminformation/files/3326129/_darwinCommands.patch.txt)

**Comment by sebhildebrandt** [comment]
@mnizhnikov I implemented this now a little different. You now have attributes command, path and params for each process. Version 4.14.0 just published.
