### ISSUE TITLE
Usage in Electron app expects gcc to be installed (macOS)

### ISSUE THREAD

**Issue by zdol** [sebhildebrandt/systeminformation#258]
**Describe the bug**
On Macs without Xcode command line tools (or gcc) installed, an Electron app using `systeminformation` (either at main or rendered processes) causes a popup to appear (see screenshot attached)

**To Reproduce**
Simply use the module in an Electron app:
```
const si = require('systeminformation');
 
si.getStaticData().then(data => {
 // some code ...
}).catch(error => console.error(error));
```
**Current Output**
Module works fine, `data` is returned, but launching the electron app causes a popup to appear asking user to install "command line developer tools" in order to use gcc.

![Screenshot 2019-06-25](https://user-images.githubusercontent.com/17680515/60397724-8b6b4080-9b58-11e9-883b-4dabfe1baf24.jpg)

If user presses "Not Now" on this dialog, it will appear again (every) next time they launch the app. After removing the `systeminformation` module from the Electron app, the dialog popup never appears again.

**Expected behavior**
No confusing dialog popups should appear to the end user.

**Environment (please complete the following information):**
 - systeminformation package version: 4.12.2
 - OS: tested on macOS Sierra or later
 - Hardware: any Mac (tested on Mac Mini, iMac, Macbook Pro, VMWare VM)
 - Electron: 5+

**Comment by sebhildebrandt** [comment]
@zdol : ahhh yes I see! Will try to fix this ... give me a little time to test it.

**Comment by sebhildebrandt** [comment]
@zdol: found a solution, will provide a patch later today. Sorry for the inconvinience ...

**Comment by zdol** [comment]
That's great @sebhildebrandt. Happy to help!

**Comment by sebhildebrandt** [comment]
@zdol: version 4.13.1 just released. can you test it on your side? Regards

**Comment by sebhildebrandt** [comment]
@zdol did you had a chance to test the latest version on your side?

**Comment by zdol** [comment]
@sebhildebrandt I can confirm the popup no longer appears.
Tested on macOS High Sierra with latest Electron.
