### ISSUE TITLE
Could not get sku number on windows

### ISSUE THREAD

**Issue by donzoru** [sebhildebrandt/systeminformation#259]
I tried deleting line 235 and 236 in file system.js, it works

**Comment by sebhildebrandt** [comment]
@donzoru : yes, I see the bug. But only deleting the two lines will not really help in all cases. Will provide a fix for that. Sorry for the inconvinience

**Comment by sebhildebrandt** [comment]
@donzoru : fixed, Version 4.14.3 just released.
