### ISSUE TITLE
Get Full Disk Size

### ISSUE THREAD

**Issue by mskian** [sebhildebrandt/systeminformation#260]
Is this Possible to Get Full Disk Size Instead of Disk blocks in Linux and Windows

**Comment by sebhildebrandt** [comment]
@mskian : not sure what you mean. `fsSize()`, `blockDevices()` and `diskLayout()` should return all sizes in bytes ... is there something that I am missing?

**Comment by mskian** [comment]
@sebhildebrandt  `blockDevices()` and `fsSiZe()` shown Storage from C, E, and F Separately it's possible to show the Full Disk Storage?

**Comment by sebhildebrandt** [comment]
@mskian ... got it ... will think about it!

**Comment by mskian** [comment]
For Linux here, I found some Commands to Get Entire Hard Disk Size

```bash
df --total -h -BT | tail -n 1
```

```bahs
df --total | tail -n 1
```

**Comment by sebhildebrandt** [comment]
@mskian Generally I would use `blockDevices()` here and add up all space where `type` equals `disk`. This works quite fine so the total would be:

```
const si = require('systeminformation');

si.blockDevices().then(data => {
        let total = 0;
        data.forEach(device => {
                if (device.type == 'disk' && device.size) {
                        total += device.size;
                }
        })
        console.log('Total = ' + total);
})
```

I personally would not add a separate function here ...
