### ISSUE TITLE
It's for client or server side

### ISSUE THREAD

**Issue by ssuriyayuvan** [sebhildebrandt/systeminformation#261]
I want to know about the client's hardware information use my web app. Is there any option to know about hardware by using this NPM?

**Comment by sebhildebrandt** [comment]
@ssuriyayuvan If you mean, if this package can be used client side (in browser)? No unfortunately not. This module is intended to be uses only on server side (node.js). Browsers would refuse system calls like I am doing in `systeminformation` package due to security reasons.

**Comment by ssuriyayuvan** [comment]
Yeah thanks!
