### ISSUE TITLE
Users function fails on parsetime method for time formats that use "." as a delimiter

### ISSUE THREAD

**Issue by jcolemn3** [sebhildebrandt/systeminformation#263]
**Describe the bug**
Calling users function fails on machines that have dateTime formats that DO NOT use ":" (colon) as a delimiter for the time.

**To Reproduce**
1. Change  your system datetime format to Finnish. I chose Finnish but it really affects any format that uses "." for the time format.
![image](https://user-images.githubusercontent.com/42102900/61553569-ab3fa700-aa28-11e9-9d96-74aec77a90de.png)

2. used function - Users()
3. code snippet
`Users()
.then(response => {
   console.log(response);
})
.catch(error => {
console.log(error);
})`
4. See output/error '....'
![image](https://user-images.githubusercontent.com/42102900/61553672-e9d56180-aa28-11e9-9173-a889f4de5d6b.png)

**Current Output**
See stack trace above

**Expected behavior**
I expect the code to account for datetime system formats that do use "." as the delimiter for time values. The code assumes that all time values will be delimited by colon ":"

**Environment (please complete the following information):**
 - systeminformation package version: 4.14.3
 - OS: Windows 10 Pro
 - Hardware: HP ZBook Studio G3 Mobile Workstation 

**Additional context**
The issue happens at line 126
![image](https://user-images.githubusercontent.com/42102900/61553804-45075400-aa29-11e9-99a8-8aea8addd8a8.png)

**Comment by sebhildebrandt** [comment]
Ah, ok. Understand. Will fix it.

**Comment by jcolemn3** [comment]
Could we look at the culture or translate using utc time of some sorts?

**Comment by jcolemn3** [comment]
Any ideas on how this can be resolved?

**Comment by sebhildebrandt** [comment]
@jcolemn3 Yes ... was on holiday, back since today. Will work on it end of this week.

**Comment by jcolemn3** [comment]
@sebhildebrandt Thanks for the quick response as always. I really appreciate it.

**Comment by jcolemn3** [comment]
@sebhildebrandt Should the date and time even be converted as being done in the parseDateTime method?
![image](https://user-images.githubusercontent.com/42102900/62578326-dae70f80-b86e-11e9-8376-f652ba65b877.png)

If you look at the screenshot, the output depending on the dateTime format set on the system does not return useful information. It will also be very difficult to account for all of the variations. Could we not just parse the date and time values without trying convert them to ex "01/01/2019" and "08:15"?

for example
Changing the format to Occitan (france)
![image](https://user-images.githubusercontent.com/42102900/62578541-652f7380-b86f-11e9-9902-a73b0d4c02a5.png)

![image](https://user-images.githubusercontent.com/42102900/62578597-82644200-b86f-11e9-9b65-d5b9254ccc22.png)
For example the above would yield:
`{
  user: user,
  tty: tty,
  date: '06/08/2019',
  time: '13 h 57',
  ip: '',
  command: ''
}`

Thoughts?

**Comment by sebhildebrandt** [comment]
@jcolemn3 : I improved the parsing to solve your first problem and should cover some more formats. Version 4.14.6 just released.

But still, you made a good point! 

I need to figure out: is there any possibility to get the date time format from nodejs, then I can easily improve the parsing.

**Comment by sebhildebrandt** [comment]
Closing it for now as I cannot find any reliable way to detect windows date format from within node. If anyone else discovers any other date time detection problems, please provide detailed information here (especially the output or `query user` on your machine)

**Comment by sebhildebrandt** [comment]
@jcolemn3 I guess I found a way to detect the date format from command line ... this will help to improve the parsing. Will try to implement this ...

**Comment by sebhildebrandt** [comment]
@jcolemn3 just released a new version where date time parsing is optimised to better reflect culture settings
