### ISSUE TITLE
si.diskLayout

### ISSUE THREAD

**Issue by jiferrero** [sebhildebrandt/systeminformation#266]
Hi,
We are using your wonderful library to retrieve info from our server and we are stuck with the diskLayout call... even running the program with sudo always return an empty array... no disk at all. We also got the same with the memLayout call but, after using sudo it works like a champ but not occur the same wirh the diskLayout. Any idea? It will probably a silly thing but ....
The system is Ubuntu 12.04 LTS ... we are on the way to update it to 18.04 LTS but in the meanwhile will be interesting that it works.

FYI ... lshw works and return an ATA Disk and cdrom which it correct... 

Thank you so much for your time.

**Comment by sebhildebrandt** [comment]
@jiferrero thank you for your bug-report. Can you provide the output of the two following commands as SUDO and as a normal user?:

```
export LC_ALL=C; lsblk -ablJO; unset LC_ALL
```

and 

```
export LC_ALL=C; dmidecode -t memory 2>/dev/null | grep -iE "Size:|Type|Speed|Manufacturer|Form Factor|Locator|Memory Device|Serial Number|Voltage|Part Number"; unset LC_ALL
```

Then I can clearly see what the problem might be. Thank you so much in advance.
Best Regards.

**Comment by jiferrero** [comment]
Hi Sebastian,
Thank you so much for your quick answer.

## lsblk
NAME  MAJ:MIN RM         SIZE RO TYPE MOUNTPOINT
sda     8:0    0 250059350016  0 disk 
sda1    8:1    0 230057574400  0 part /
sda2    8:2    0         1024  0 part 
sda5    8:5    0  19998441472  0 part [SWAP]
sr0    11:0    1   1073741312  0 rom  
ram0    1:0    0     67108864  0 disk 
ram1    1:1    0     67108864  0 disk 
ram2    1:2    0     67108864  0 disk 
ram3    1:3    0     67108864  0 disk 
ram4    1:4    0     67108864  0 disk 
ram5    1:5    0     67108864  0 disk 
ram6    1:6    0     67108864  0 disk 
ram7    1:7    0     67108864  0 disk 
ram8    1:8    0     67108864  0 disk 
ram9    1:9    0     67108864  0 disk 
loop0   7:0    0               0 loop 
loop1   7:1    0               0 loop 
loop2   7:2    0               0 loop 
loop3   7:3    0               0 loop 
loop4   7:4    0               0 loop 
loop5   7:5    0               0 loop 
loop6   7:6    0               0 loop 
loop7   7:7    0               0 loop 
ram10   1:10   0     67108864  0 disk 
ram11   1:11   0     67108864  0 disk 
ram12   1:12   0     67108864  0 disk 
ram13   1:13   0     67108864  0 disk 
ram14   1:14   0     67108864  0 disk 
ram15   1:15   0     67108864  0 disk 
## SUDO lsblk
AME  MAJ:MIN RM         SIZE RO TYPE MOUNTPOINT
sda     8:0    0 250059350016  0 disk 
sda1    8:1    0 230057574400  0 part /
sda2    8:2    0         1024  0 part 
sda5    8:5    0  19998441472  0 part [SWAP]
sr0    11:0    1   1073741312  0 rom  
ram0    1:0    0     67108864  0 disk 
ram1    1:1    0     67108864  0 disk 
ram2    1:2    0     67108864  0 disk 
ram3    1:3    0     67108864  0 disk 
ram4    1:4    0     67108864  0 disk 
ram5    1:5    0     67108864  0 disk 
ram6    1:6    0     67108864  0 disk 
ram7    1:7    0     67108864  0 disk 
ram8    1:8    0     67108864  0 disk 
ram9    1:9    0     67108864  0 disk 
loop0   7:0    0               0 loop 
loop1   7:1    0               0 loop 
loop2   7:2    0               0 loop 
loop3   7:3    0               0 loop 
loop4   7:4    0               0 loop 
loop5   7:5    0               0 loop 
loop6   7:6    0               0 loop 
loop7   7:7    0               0 loop 
ram10   1:10   0     67108864  0 disk 
ram11   1:11   0     67108864  0 disk 
ram12   1:12   0     67108864  0 disk 
ram13   1:13   0     67108864  0 disk 
ram14   1:14   0     67108864  0 disk 
ram15   1:15   0     67108864  0 disk 
## dmidecode
dmidecode 2.12
## SUDO dmidecode
dmidecode 2.12
SMBIOS 2.6 present.

Handle 0x001A, DMI type 16, 15 bytes
Physical Memory Array
        Location: System Board Or Motherboard
        Use: System Memory
        Error Correction Type: Multi-bit ECC
        Maximum Capacity: 16 GB
        Error Information Handle: Not Provided
        Number Of Devices: 4

Handle 0x001B, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x001A
        Error Information Handle: No Error
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 2048 MB
        Form Factor: DIMM
        Set: 1
        Locator: DIMM2A
        Bank Locator: Not Specified
        Type: DDR3
        Type Detail: Synchronous
        Speed: 1332 MHz
        Manufacturer: Not Specified
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Rank: Unknown

Handle 0x001C, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x001A
        Error Information Handle: No Error
        Total Width: Unknown
        Data Width: Unknown
        Size: No Module Installed
        Form Factor: DIMM
        Set: 1
        Locator: DIMM1C
        Bank Locator: Not Specified
        Type: Reserved
        Type Detail: Synchronous
        Speed: Unknown
        Manufacturer: Not Specified
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Rank: Unknown

Handle 0x001D, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x001A
        Error Information Handle: No Error
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 2048 MB
        Form Factor: DIMM
        Set: 1
        Locator: DIMM4B
        Bank Locator: Not Specified
        Type: DDR3
        Type Detail: Synchronous
        Speed: 1332 MHz
        Manufacturer: Not Specified
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Rank: Unknown

Handle 0x001E, DMI type 17, 28 bytes
Memory Device
        Array Handle: 0x001A
        Error Information Handle: No Error
        Total Width: Unknown
        Data Width: Unknown
        Size: No Module Installed
        Form Factor: DIMM
        Set: 1
        Locator: DIMM3D
        Bank Locator: Not Specified
        Type: Reserved
        Type Detail: Synchronous
        Speed: Unknown
        Manufacturer: Not Specified
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Rank: Unknown

Hope it helps... 
Best,
Jose

**Comment by sebhildebrandt** [comment]
@jiferrero Seems that the `lsblk` version in shipped with ubuntu 12.04 LTS does not recognize the options of `lsblk -ablJO` so there is no json output ... actually also 14.04 does not support this. So I need to make a version that support older versions of `lsblk`. Can you provide the output of the following:

```
lsblk -V
```

and 

```
lsblk -bPo NAME,TYPE,SIZE,FSTYPE,MOUNTPOINT,UUID,ROTA,RO,RM,LABEL,MODEL,OWNER,GROUP
```

and 

```
lsblk -bPo NAME,TYPE,SIZE,FSTYPE,MOUNTPOINT,UUID,ROTA,RO,RM,TRAN,SERIAL,LABEL,MODEL,OWNER,GROUP
```

Thank you in advance.

**Comment by jiferrero** [comment]
Hi Sebastian,

Thank you so much for your answer. Sadly lsblk in Ubuntu 14.04 does not recognize option -V nor values for column TRAN and SERIAL.

For command:
lsblk -bPo NAME,TYPE,SIZE,FSTYPE,MOUNTPOINT,UUID,ROTA,RO,RM,LABEL,MODEL,OWNER,GROUP

the output is:
NAME="sda" TYPE="disk" SIZE="250059350016" FSTYPE="" MOUNTPOINT="" UUID="" ROTA="1" RO="0" RM="0" LABEL="" MODEL="VB0250EAVER     " OWNER="root" GROUP="disk"
NAME="sda1" TYPE="part" SIZE="230057574400" FSTYPE="" MOUNTPOINT="/" UUID="" ROTA="1" RO="0" RM="0" LABEL="" MODEL="" OWNER="root" GROUP="disk"
NAME="sda2" TYPE="part" SIZE="1024" FSTYPE="" MOUNTPOINT="" UUID="" ROTA="1" RO="0" RM="0" LABEL="" MODEL="" OWNER="root" GROUP="disk"
NAME="sda5" TYPE="part" SIZE="19998441472" FSTYPE="" MOUNTPOINT="[SWAP]" UUID="" ROTA="1" RO="0" RM="0" LABEL="" MODEL="" OWNER="root" GROUP="disk"
NAME="sr0" TYPE="rom" SIZE="1073741312" FSTYPE="" MOUNTPOINT="" UUID="" ROTA="1" RO="0" RM="1" LABEL="" MODEL="DVDROM DH20N    " OWNER="root" GROUP="cdrom"

Can this help you with something? Can I do something else that helps you?

Best,
Jose

**Comment by sebhildebrandt** [comment]
@jiferrero Yes, this is fine! Will work on it ...

**Comment by jiferrero** [comment]
Super ... let me know if I can help you with something.... Honestly the tool is looking awesome getting the info with your lib and sending it to web app through sockets and displaying all that info with nice graphs XD

**Comment by sebhildebrandt** [comment]
@jiferrero So I just updated lib/filesystem.js here on github. If you just replace this file, does it work fine on your machine?

**Comment by jiferrero** [comment]
Hey, works like a champ now!!! It detects the disk and receive info from socket... You are in the right way... ;)
![k_snapshot_disk](https://user-images.githubusercontent.com/19981415/68545758-3ece2680-03d0-11ea-97d9-ce759ba5877c.png)

**Comment by sebhildebrandt** [comment]
@jiferrero Version 4.15.1. just released

**Comment by jiferrero** [comment]
Updated and working.... will make some more tests and let you know about it... 
As you can see in the picture sent we are only using one disk, which is related with the other question you marked as enhancement and that will make possible deal with IOPS and filesystem for each disk in the machine and not overall... 
Thank you so much for your superb library.

**Comment by rbent98** [comment]
Hello I have the same issue on version 4.15.3. 
My debugger give me an error that says [ERROR]-/bin/sh: 1: lsblk: not found

**Comment by jiferrero** [comment]
Hi rbent98, looks like you do not have lsblk installed... Just install it and try again

**Comment by sebhildebrandt** [comment]
@rbent98 can you give a little more information on which OS you are working and on what type of machine. Can you also provide the output of 

```
which lsblk
```

**Comment by jiferrero** [comment]
Ubuntu 12.10 LST... That was the problem because older one.... Tested on Ubuntu 16.10 LST and 18.10 LST without any problems.... Not with my older server, right now so I can not give you any feedback of which lsblk output, sorry
