### ISSUE TITLE
networkStats() do not seem to be working on Windows 10

### ISSUE THREAD

**Issue by jeroenm2** [sebhildebrandt/systeminformation#267]
When using the functions si.networkStats() and getDynamicData() the network stats ifaces do not show any other value than their default value.

**To Reproduce**
I use the following loop to get the network stats

```
const si = require('systeminformation');

setInterval(() => {
    si.networkStats('*').then(data => {
        console.log(data);
    });
}, 1000);
```

Here is an example of the output, which is always the same for any iface device:
[ { iface: 'local area connection',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 },

**Expected behavior**
Expected behaviour is to return the actual network data, not the defaults.

**Environment:**
 - systeminformation package version: 4.14.4
 - OS: Windows 10 Version 1903 (latest)
 - Hardware: PC

**Comment by lollobaldo** [comment]
I get some data, but it is obviously wrong as the rx_sent never change and the tx are completely unplausible values. Here is a sample.

**Comment by sebhildebrandt** [comment]
Still investigating. Have an idea, will try to provide a fix tomorrow.

**Comment by lollobaldo** [comment]
My problem seems to be solved, only difference I can think of is that maybe I did not reboot right after installation, though I don't see why that should change anything?

**Comment by sebhildebrandt** [comment]
@jeroenm2 seems that systeminformation get mixed up wit your network interfaces names:

Can you provide the output of 

```
nic get MACAddress, name, NetEnabled, Speed, NetConnectionStatus, AdapterTypeId /value
```

and within `node`: 

```
os.networkInterfaces()
```

**Comment by jeroenm2** [comment]
AdapterTypeId=
MACAddress=
Name=Microsoft Kernel Debug Network Adapter
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=0
MACAddress=XX:XX:XX:XX:XX:XX
Name=Intel(R) Ethernet I210-T1 GbE NIC
NetConnectionStatus=2
NetEnabled=TRUE
Speed=1000000000

AdapterTypeId=0
MACAddress=XX:XX:XX:XX:XX:XX
Name=Killer E2200 Gigabit Ethernet Controller
NetConnectionStatus=7
NetEnabled=FALSE
Speed=9223372036854775807

AdapterTypeId=
MACAddress=
Name=WAN Miniport (SSTP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (IKEv2)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (L2TP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPTP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=
MACAddress=
Name=WAN Miniport (PPPOE)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=0
MACAddress=XX:XX:XX:XX:XX:XX
Name=WAN Miniport (IP)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=0
MACAddress=XX:XX:XX:XX:XX:XX
Name=WAN Miniport (IPv6)
NetConnectionStatus=
NetEnabled=
Speed=

AdapterTypeId=0
MACAddress=XX:XX:XX:XX:XX:XX
Name=WAN Miniport (Network Monitor)
NetConnectionStatus=
NetEnabled=
Speed=

Node output:
{ 'Local Area Connection':
   [ { address: '192.168.10.14',
       netmask: '255.255.240.0',
       family: 'IPv4',
       mac: 'XX:XX:XX:XX:XX:XX',
       internal: false,
       cidr: '192.168.10.14/20' } ],
  'Loopback Pseudo-Interface 1':
   [ { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true,
       cidr: '::1/128' },
     { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true,
       cidr: '127.0.0.1/8' } ] }

Replaced MAC where filled with X's.

I've got two network adapter, one from Intel and a Killer. The enormous speed of the Killer adapter is noticeable. The issue is still there as I am on:

**Environment:**
systeminformation package version: 4.15.3
OS: Windows 10 Version 1909 (latest stable)
Hardware: PC

**Comment by sebhildebrandt** [comment]
@lollobaldo @jeroenm2 can you test it one more time on your side. Made some changes recently. latest version now is 4.26.9
