### ISSUE TITLE
Empty uuid field on linux

### ISSUE THREAD

**Issue by Raepheles** [sebhildebrandt/systeminformation#268]
**Describe the bug**
System function returns empty uuid field on linux.

**To Reproduce**
1. used function 'system'
2. code snippet 'require("systeminformation").system((data) => console.log(data))'
3. start app / code
4. See that response data has empty uuid field on linux (ubuntu specifically)

**Expected behavior**
There should be uuid field on linux as well.

**Environment (please complete the following information):**
 - systeminformation package version: latest version
 - OS: Ubuntu 18.04 LTS
 - Hardware: Asus pc

**Additional context**
I was using another module called node-machine-id which is only for getting the uuid of the machine. It was working fine both on windows and linux but at certain point I required data such as mac address, ip address, ram usage etc. Which lead me to this module. After I realized that this module also gives uuid of the machine I uninstalled the previous module. Soon after I realized that it returns empty uuid field on linux.

**Comment by sebhildebrandt** [comment]
@Raepheles  What is the output of 

```
dmidecode -t system
```

on your machine?

And does  `systeminformation.uuid()` also returns null?

Regards

**Comment by Raepheles** [comment]
@sebhildebrandt 
The linux pc I mentioned is at my workplace. I will check next monday and answer your questions.

**Comment by Raepheles** [comment]
`dmidecode -t system` asks for permission. When I use it with sudo I get bunch of information including UUID. 

uuid() function returns a json object with single key named 'os' and its value appears to be a hash string.

**Comment by sebhildebrandt** [comment]
Can you provide both outputs?

**Comment by sebhildebrandt** [comment]
@Raepheles So, I checkt it once again. `si.uuid()` returns an object with `os: .....`which is the exactly same ID you get with the package `node-machine-id`. The values are generated during installation of an OS. `si.system` instead, should return a machine (hardware) specific value. Linux needs sudo privileges to get this value. So I guess, you can rely on what you get from `si.uuid()`.
