### ISSUE TITLE
Any idea, why zabbix agent service is not detected?

### ISSUE THREAD

**Issue by fr6nco** [sebhildebrandt/systeminformation#269]
**Describe the bug**
When trying to query zabbix-agent on centos7, systeminformation returns running:false, however, the service is running on the machine.

```
 [root@s1-h4-tbocdn dist]# service zabbix-agent status 
 Redirecting to /bin/systemctl status zabbix-agent.service
 ● zabbix-agent.service - Zabbix Agent
    Loaded: loaded (/usr/lib/systemd/system/zabbix-agent.service; enabled; vendor preset:  disabled)
    Active: active (running) since Wed 2019-08-07 14:04:10 CEST; 5min ago
   Process: 350 ExecStop=/bin/kill -SIGTERM $MAINPID (code=exited, status=0/SUCCESS)
   Process: 368 ExecStart=/usr/sbin/zabbix_agentd -c $CONFFILE (code=exited, status=0/SUCCESS)
  Main PID: 370 (zabbix_agentd)
    CGroup: /system.slice/zabbix-agent.service
            ├─370 /usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf
            ├─371 /usr/sbin/zabbix_agentd: collector [idle 1 sec]
            ├─372 /usr/sbin/zabbix_agentd: listener #1 [waiting for connection]
            ├─373 /usr/sbin/zabbix_agentd: listener #2 [waiting for connection]
            ├─374 /usr/sbin/zabbix_agentd: listener #3 [waiting for connection]
            └─375 /usr/sbin/zabbix_agentd: active checks #1 [idle 1 sec]
```

systeminformation returns:
`
{"name":"zabbix-agent","running":false,"startmode":"","pids":[],"pcpu":0,"pmem":0}]
`

**To Reproduce**
Steps to reproduce the behavior. Called as:
        const data = await si.services("zabbix-agent"); 

**Environment (please complete the following information):**
 - "systeminformation": "^4.14.4",
 - OS: CentOS Linux release 7.6.1810 (Core)

**Comment by fr6nco** [comment]
I think I see the issue.
```
  [root@s1-h4-tbocdn ~]# service --status-all
 iptables: Chain already exists.
 netconsole module not loaded
 Configured devices:
 lo eth0
 Currently active devices:
 lo eth0
```

service --status-all returns wierd things on centos 7.6, Will try to figure out, whether it's a bug on my side or some changes to centos.
It might be needed to be changed to systemctl list-units --type service --all

**Comment by sebhildebrandt** [comment]
@fr6nco : just one question: 

To get the satus of the Zabbix agent, vou are calling is like this:

```
const data = await si.services("zabbix-agent");
```
So then  - as you defined a service - `service --status-all` should not be called. 

What is the output of `ps -axo pcpu,pmem,pid,command`? Do you see the `zabbix-agent` here?

Anyway ... when calling it with "*" for all services I should really consider changing to `systemctl list-units --type service --all`

**Comment by sebhildebrandt** [comment]
@fr6nco can you also provide the output of `systemctl list-units --type service --all`? Would help changing it ... Thank you in advance!

**Comment by fr6nco** [comment]
Hi @sebhildebrandt,

yes Im calling it like you mentioned. Here's a quick test

```
const si = require('systeminformation');

si.services("zabbix-agent").then((se) => {
	console.log(se);
});
```

which returns false for running, however the app is running.
```
[root@s1-h3-cdn tests]# node index.js
[ { name: 'zabbix-agent',
    running: false,
    startmode: '',
    pcpu: 0,
    pmem: 0 } ]
```

the command systemctl list-units --type service --all returns zabbix-agent in correct state:
```
zabbix-agent.service            loaded    active   running Zabbix Agent
```

Also the command you mentioned:
```
[root@s1-h3-cdn tests]# ps -axo pcpu,pmem,pid,command | grep zabbix
 0.0  0.0 13038 grep --color=auto zabbix
 0.0  0.0 14243 /usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf
 0.0  0.0 14255 /usr/sbin/zabbix_agentd: collector [idle 1 sec]
 0.0  0.0 14256 /usr/sbin/zabbix_agentd: listener #1 [waiting for connection]
 0.0  0.0 14257 /usr/sbin/zabbix_agentd: listener #2 [waiting for connection]
 0.0  0.0 14258 /usr/sbin/zabbix_agentd: listener #3 [waiting for connection]
```

**Comment by sebhildebrandt** [comment]
So can you modify your code, that you ask for „zabbix_agent“ (underscore) instead of „zabbix-agent“ (hyphen). That should work ...

**Comment by fr6nco** [comment]
oh god..,,
yeah that works. thanks. 

```
[ { name: 'zabbix_agent',
    running: true,
    startmode: '',
    pids: [ '14243', '14255', '14256', '14257', '14258' ],
    pcpu: 0.010129732753413528,
    pmem: 0 } ]
```
