### ISSUE TITLE
size as string in fsSize()

### ISSUE THREAD

**Issue by Arebisc** [sebhildebrandt/systeminformation#271]
**Description**
While calculating free space on disk I've discovered that fsSize() function returns size as string instead of number.

**Reproduction steps**
```
import * as systeminformation from 'systeminformation';
...
const storage = await systeminformation.fsSize();
```

**Current Output**
```
{  
   "fs":"C:",
   "type":"NTFS",
   "size":"239463297024",
   "used":231218995200,
   "use":96.55717518030593,
   "mount":"C:"
}
```

**Expected behavior**
It would be nice to have disk size as number :) 

**Environment (please complete the following information):**
 - systeminformation package version: 4.14.4
 - OS: Windows 10 Enterprise 1703

**Comment by sebhildebrandt** [comment]
@Arebisc Fixed, sorry. Version 4.14.5 just released.
