### ISSUE TITLE
processes.command and processes.params are truncated

### ISSUE THREAD

**Issue by Xeing** [sebhildebrandt/systeminformation#272]
processes.command and processes.params are truncated and brackets are lost.
For example:

Command:
ffmpeg -hwaccel_device 0 -hwaccel nvdec -i udp://224.1.1.1:5201?overrun_nonfatal=1 -filter_complex '[i:2761]hwupload_cuda,yadif_cuda,setfield=auto,split[0][1];[0]scale_npp=1024:720[0];[1]scale_npp=720:576:format=yuv420p,hwdownload[1]' -map '[0]' -map i:2764 -c:v h264_nvenc -g:v 90 -zerolatency:v 1 -preset:v llhp -profile:v high -level:v 4.1 -gpu:v 0 -b:v 4000k -minrate:v 1000k -maxrate:v 4000k -bufsize:v 4000k -c:a aac -ac:a 2 -b:a 128k -r 25 -f mpegts udp://236.0.0.1:5001?pkt_size=1316 -mpegts_original_network_id 1 -mpegts_transport_stream_id 1 -mpegts_service_id 1 -mpegts_pmt_start_pid 4096 -streamid 0:101 -streamid 1:102 -metadata service_provider="RTVE" -metadata service_name="La 1 HD" -map '[1]' -map i:2764 -c:v mpeg2video -g:v 90 -me_method:v full -b:v 3500k -minrate:v 3000k -maxrate:v 4500k -bufsize:v 4500k -c:a mp2 -ac:a 2 -b:a 128k -r 25 -f mpegts udp://236.0.0.1:5002?pkt_size=1316 -mpegts_original_network_id 1 -mpegts_transport_stream_id 1 -mpegts_service_id 1 -mpegts_pmt_start_pid 4096 -streamid 0:101 -streamid 1:102 -metadata service_provider="RTVE" -metadata service_name="La 1 SD"

Response:
ffmpeg -hwaccel_device 0 -hwaccel nvdec -i udp://224.1.1.1:5201?overrun_nonfatal=1 -filter_complex i:2761hwupload_cuda,yadif_cuda,setfield=auto,split01;0scale_npp=1024:7200;1scale_npp=720:576:format=yuv420p,hwdownload1 -map 0 -map i:2764 -c:v h264_nvenc -g:v 90 -zerolatency:v 1 -preset:v llhp -profile:v high -level:v 4.1 -gpu:v 0 -b:v 4000k -minrate:v 1000k -maxrate:v 4000k -bufsize:v 4000k -c:a aac -ac:a 2 -b:a 128k -r 25 -f mpegts udp://236.0.0.1:5001?pkt_size=1316 -mpegts_original_network_id 1 -mpegts_transport_stream_id 1 -mpegts_service_id 1 -mpegts_pmt_start_pid 4096 -streamid 0:101 -streamid 1:102 -metadata service_provider=RTVE -metadata service_name=La 1 HD -map 1 -map i:2764 -c:v mpeg2video -g:v 90 -me_method:v full -b:v 3500k -minrate:v 3000k -maxrate:v 4500k -bufsize:v 4500k -c:a mp2 -ac:a 2 -b:a 128k -r 25 -f

**Comment by sebhildebrandt** [comment]
@Xeing cleaning up older issues. Should be fixed now ... you'd you check latest version 5.2.5? Closing it for now.
