### ISSUE TITLE
Promises pending forever on nwjs&vue app

### ISSUE THREAD

**Issue by blacktxandy** [sebhildebrandt/systeminformation#273]
Hello, this is my first issue report in gitHub. I hope not to be rude and I hope to write all the necessary information correctly and accurately.
### **Describe the bug**
Using NW.js and VUE (with Vuetify) I cannot get a response on any function, either using callbacks or async/await then/finally blocks. I checked the promises using console.log(function_used) and it seems to be pending forever (I know the promise will show on console as pending, but I tested it with finally{} and it never reaches the finally block). 

### **To Reproduce**

1. used function: **any pomise based function.**

2. code snippet:

```
//COMPLETE APP.VUE
<template>
  <v-app>
    <v-app-bar app>
      <v-btn text @click="getAllInfo()">
        <span class="mr-2">List info</span>
      </v-btn>
    </v-app-bar>
  </v-app>
</template>

<script>
  import HelloWorld from './components/HelloWorld'
  const si = require('systeminformation')
  // eslint-disable-next-line
  let win = nw.Window.get()
  export default {
    name: 'App',
    components: {
      HelloWorld,
    },
    data: () => ({
      //
    }),
    methods: {
      closeWindow() {
        win.close()
      },
      getAllInfo() {
        console.log('we can get into the "getAllInfo" function...')
        si.networkStats().then(data => {
            console.log('there should be a response on console log')
            console.log(data);
        })
        console.log('and we can get out.')
      }
    }
  }
</script>

```

### 3. start app / code: 
_app starts normally, everything is working, except for the systeminformation promises that keep waiting and never return. I tested the non-promises based functions (version and time) and they are working properly._

### 4. See output/error:

**Current Console Log Output**

[HMR] Waiting for update signal from WDS...
_vue.runtime.esm.js?2b0e:8423_ - Download the Vue Devtools extension for a better development experience:
_vue.runtime.esm.js?2b0e:8423_ - https://github.com/vuejs/vue-devtools
_App.vue?234e:29_ - we can get into the "getAllInfo" function...
_App.vue?234e:34_ - and we can get out.

**Expected behavior**

[HMR] Waiting for update signal from WDS...
_vue.runtime.esm.js?2b0e:8423_ - Download the Vue Devtools extension for a better development experience:
_vue.runtime.esm.js?2b0e:8423_ - https://github.com/vuejs/vue-devtools
_App.vue?234e:29_ - we can get into the "getAllInfo" function...
_App.vue?234e:34_ - and we can get out.
**_some data from the networkStats promise_**

**Environment:**
 - used packages versions:

Node: [v10.15.3](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.15.3)
Vue: [v2.6.10](https://github.com/vuejs/vue/releases/tag/v2.6.10)
Vuetify: [v2.0.5](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.5)
NWJS: [v0.40.1-sdk](https://github.com/nwjs/nw.js/releases/tag/nw-v0.40.1)

SystemInformation: [v4.14.4](https://github.com/sebhildebrandt/systeminformation)

 - OS: [Windows 10 pro (pt-BR) v1709 build 16299.1087](https://support.microsoft.com/pt-br/help/4493441/windows-10-update-kb4493441)
 - Hardware:
```
Intel Core i3-8100 CPU @ 3.60GHz
Gigabyte B360M D3H-CF (U3E1)
EVGA GeForce GTX 1070
```

**Comment by blacktxandy** [comment]
UPDATE: I tested today a new strategy and tried to load the package directly in the **index.html** of my vue project and it worked. I can call all the functions without any problem. Here is what I did:
my index.html => ...<script> **const** si = require('systeminformation')</script>...
onto any Vue component or view => io.cpu().then(...).catch(...) <- this can be inside a method (accessing the si variable from index.html)

**Comment by sebhildebrandt** [comment]
@blacktxandy thank you for sorting this out!

**Comment by saurabhsinghhauhan** [comment]
@blacktxandy I'm new in vue(2.6.12) and facing the same issue, I added `const si = require('systeminformation')` in public -> index.html, then I'm getting below error

`Uncaught ReferenceError: require is not defined`

Please help to close this issue. Thanks in advance

**Comment by sebhildebrandt** [comment]
@saurabhsinghhauhan Seems that you are trying to use `systeminformation` client side ... this will not work. This library is supposed to be used as a node.js backend/server-side library and will definilely not work within a browser. Have a look at our documentation: https://systeminformation.io/gettingstarted.html

**Comment by saurabhsinghhauhan** [comment]
@sebhildebrandt Thanks for the quick response, it saved my time.

**Comment by blacktxandy** [comment]
> @sebhildebrandt Thanks for the quick response, it saved my time.

Yep, I was using it on a nwjs application... so, it's kind of a node(ish) environment... it's still working today, although I'm not working on the same company anymore and dont have access to the code anymore.
