### ISSUE TITLE
Show DHCP status, connection protocols, and DNS suffix

### ISSUE THREAD

**Issue by juancampuzano** [sebhildebrandt/systeminformation#275]
Is it possible to add the information below?
 ​​
*DHCP status:* validate if adapter is using static or dinamic (DHCP).
*DNS-suffix and adapter specific:* The device DNS name and The adapter's specific connection DNS suffix.
*802.1x (wired/wreless):* If device connected to wired or wireless 802.1x. What connection protocol (EAP-TLS/MSCHAPv2, etc.)

**Comment by sebhildebrandt** [comment]
Will check it ...

**Comment by juancampuzano** [comment]
Is there any update?

> Will check it ...

Thank you in advance for attending the request, however I would like to know if you are already working on the request or if you have a date ready for this?

thanks for the attention!

**Comment by sebhildebrandt** [comment]
@juancampuzano sorry for not responding. Had a super busy time. Will have a look on it next week.

**Comment by juancampuzano** [comment]
@sebhildebrandt thank you in advance for the help, please let me know when there is an update.

**Comment by sebhildebrandt** [comment]
@juancampuzano version 4.17.0 just released. Merged your contribution
