### ISSUE TITLE
memLayout typescript definition is wrong

### ISSUE THREAD

**Issue by emmkimme** [sebhildebrandt/systeminformation#278]
**Describe the bug**
memLayout function is supposed to return an array of MemLayoutData/s

**Current Output**
in index.d.ts, returned value is not an array but a single MemLayoutData
`export function memLayout(cb?: (data: Systeminformation.MemLayoutData) => any): Promise<Systeminformation.MemLayoutData>;`

**Expected behavior**
`export function memLayout(cb?: (data: Systeminformation.MemLayoutData[]) => any): Promise<Systeminformation.MemLayoutData[]>;`

I can contribute if it can help, let me know.

PS: Thanks for this excellent lib ;-)

**Comment by sebhildebrandt** [comment]
@emmkimme : Definitely my fault! Sorry. Will fix it.

**Comment by sebhildebrandt** [comment]
@emmkimme fixed. Thank you!
Version 4.14.10 just released
