### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by radu-iosif-moldovan** [sebhildebrandt/systeminformation#279]
**Describe the bug**
`processLoad` call causes 'Cannot read property 'indexOf' of undefined' js error when `util.wmic('process get /value')` returns `error`.
The error is on line 870: `result.pids.indexOf(resultProcess.pid)` since `result.pids` never gets defined when `error` is true.

**To Reproduce**
1. used function: processLoad
2. have util.wmic('process get /value') return error.
3. See output/error: Cannot read property 'indexOf' of undefined

**Expected behavior**
processLoad should not throw error even if `util.wmic('process get /value')` fails.

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: Windows 10

**Additional context**
Not sure how to get util.wmic('process get /value') to return error so I can't provide clear steps to reproduce.

**Comment by sebhildebrandt** [comment]
Ok, will test it here on my side.

**Comment by yangyaochia** [comment]
encounter the same issue

**Comment by sebhildebrandt** [comment]
@radu-iosif-moldovan Fixed, should work now ...
Version 4.14.9 just released
