### ISSUE TITLE
Docker data inverted ? Container running and stopped

### ISSUE THREAD

**Issue by AdrienCulem** [sebhildebrandt/systeminformation#281]
It seems like the running containers are inverted between running and stopped.

See what I get with the `dockerInfo()` function : 

![image](https://user-images.githubusercontent.com/14331639/65969513-3267bd00-e465-11e9-9fc9-d2eb6b2d94e3.png)

And what I have with `docker ps -a` : 

![image](https://user-images.githubusercontent.com/14331639/65969539-3eec1580-e465-11e9-9b03-48f90a671390.png)

Also it seems like the function `dockerInfo()` is returning an array of `DockerInfoData` white it is actually returning only one object.

I am using version `4.14.8` which seems to be latest.

Thanks in advance,
Cheers !

**Comment by sebhildebrandt** [comment]
Had a look into the code and it seems to be fine ... also my tests show correct info here.

What - in your case - is the result of `docker info` (from command line)

**Comment by AdrienCulem** [comment]
Thanks for the quick reply !

I just restarted everything and it now seem to be giving the right information; Nvm I guess.

What about the return type for `dockerInfo()` function ?

**Comment by sebhildebrandt** [comment]
@AdrienCulem fixed type definition ... sorry for that.
Version 4.14.11 just released
