### ISSUE TITLE
Error: spawn powershell.exe ENOENT

### ISSUE THREAD

**Issue by GerrardAquilon** [sebhildebrandt/systeminformation#282]
Hello !

I just want to let you know that if powershell's directory is not in the PATH env var, the powershell function in the util file crashes the app.

This is because the error callback is not set if the child var is not set and if the pid of the child var is not set. I think I fixed it by moving this lines (on('error' ...)) outside the if, but i'm not sure it's the best way to do this...

I hope you'll find a best fix !

**Comment by sebhildebrandt** [comment]
@GerrardAquilon Will make some tests on Friday... and I am pretty sure to find a solution for that. Thank you for reporting!

**Comment by sebhildebrandt** [comment]
@GerrardAquilon ... fixed the issue! Version 4.14.14 just released.
