### ISSUE TITLE
get local system information from server

### ISSUE THREAD

**Issue by harishksoft** [sebhildebrandt/systeminformation#283]
As of now this code only fetch the system info in which the script runs locally. I just want to get the user's system info who runs the script using a live URL.

**Comment by sebhildebrandt** [comment]
@harishksoft can you please describe your use case a little bit more detailed? I am not sure that I really understood your feature request ;-)

**Comment by harishksoft** [comment]
> @harishksoft can you please describe your use case a little bit more detailed? I am not sure that I really understood your feature request ;-)

I want to build an app, hosted in the live server, which is for showing the user's system information in a browser like name, serial number, ports,battery status, hdd health report etc.. when I visited a URL. As of now when I run the code in the server, it takes the information of the live server instead of my local system. but when run in locally it takes my local system information.

**Comment by sebhildebrandt** [comment]
@harishksoft still not sure, what you want to accomplish.

First of all, there is no possibility to get detailed system information from a script running within a browser. 

So you will only get detailed system information when you run a script (in our case a node script) locally on a specific machine. So you can grab all local system information with the  systeminformation package within a node script on nearly any machine. Then you need to send this data to your server which then collects all information and displays it. This can be achieved by "pushing" it to the server or by "pulling" it from the client (then the client must be "reachable" from your server)

Is this what you want to achieve?

**Comment by harishksoft** [comment]
@sebhildebrandt i'm just building a web app through which user can check his system information. I don't know to explain more than this ;)

"First of all, there is no possibility to get detailed system information from a script running within a browser." - all clear now. There is no chance of building an app as I planned.

In order to run the script user first need to setup the node environment in his local, so peoples without knowlege in programming can't do that.

**Comment by sebhildebrandt** [comment]
Yes this is correct. Due to security reasons, a browser cannot determine system information (except those from user agent sent in the header). And this is absolutely fine ;-)

**Comment by harishksoft** [comment]
@sebhildebrandt ia there any option to get keyboard and monitor details

**Comment by sebhildebrandt** [comment]
@harishksoft As far as I now, this is what you can determine:

- device type (mobile, tablet, smart-tv, desktop, watch, ...)
- OS and OS version (e.g. Windows 10)
- CPU architecture (arm, amd64, ...)
- browser
- locale

by parsing the user agent ... I do not see any possibility to get keyboard details ...
