### ISSUE TITLE
Get empty array instead information about monitor

### ISSUE THREAD

**Issue by CreativeRusBear** [sebhildebrandt/systeminformation#287]
**Describe the bug**
After package update from v4.14.8 to v4.14.15 I began to receive an empty array 
which was supposed to return information about displays.

**To Reproduce**
1. run code snippet:
```javascript
const si = require('systeminformation');
async function graphicsInfo () {
	console.log(await si.graphics());
}
```

**Current Output**
The result that I get on the output;
![empty_monitor_info](https://user-images.githubusercontent.com/37180024/67150054-68a59900-f2bb-11e9-8bea-92975b668bd0.png)

**Expected behavior**
Get array with data about monitor(s)

**Environment (please complete the following information):**
 - systeminformation package version: 4.14.15
 - OS: Windows 10 Pro
 - Hardware: LG L1942SEU

**Additional context**
In version 4.14.8 this worked just fine

**Comment by sebhildebrandt** [comment]
@CreativeRusBear seems that I introduced a bug ... I already fixed it but only on github. Can you replace the current lib/graphics.js from github ant test if this works again on your machine?

**Comment by sebhildebrandt** [comment]
@CreativeRusBear fixed. Version 4.14.16 just released.
