### ISSUE TITLE
Get incorrect data about monitor

### ISSUE THREAD

**Issue by CreativeRusBear** [sebhildebrandt/systeminformation#288]
**Describe the bug**
In the latest version of the package, I get incorrect data about the monitor. Namely, in my case:
1) the `vendor` property must have the value 'LG';
2) the `model` property must have the value 'L1942SEU';

**To Reproduce**
1. run code snippet:

```javascript
async function displaysInfo () {
	const {displays} = await si.graphics();
	console.log(displays);
	return displays;
}
```

**Current Output**
If applicable, add output to help explain your problem.

![incorrect__monitor_data](https://user-images.githubusercontent.com/37180024/67158221-22dde480-f33e-11e9-872f-aa133d3e1e04.png)

**Expected behavior**
Get correct data about monitor(s)

**Environment (please complete the following information):**
 - systeminformation package version: 4.14.16
 - OS: Windows 10 Pro
 - Hardware:  LG L1942SEU

**Additional context**

**Comment by sebhildebrandt** [comment]
@CreativeRusBear 

Can you run the two following commands:

From command line
```
wmic path win32_desktopmonitor get /value

```

From PowerShell
```
gwmi WmiMonitorID -Namespace root\wmi | ForEach-Object {(($_.ManufacturerName -notmatch 0 | foreach {[char]$_}) -join "") + "|" + (($_.ProductCodeID -notmatch 0 | foreach {[char]$_}) -join "") + "|" + (($_.UserFriendlyName -notmatch 0 | foreach {[char]$_}) -join "") + "|" + (($_.SerialNumberID -notmatch 0 | foreach {[char]$_}) -join "") + "|" + $_.InstanceName}
```

and post both results here? Thank you in advance!

**Comment by CreativeRusBear** [comment]
@sebhildebrandt 
![image](https://user-images.githubusercontent.com/37180024/67161126-297d5380-f360-11e9-8c33-4b87c71c6602.png)
![image](https://user-images.githubusercontent.com/37180024/67161180-985aac80-f360-11e9-8f44-7ae91fadcf23.png)

**Comment by CreativeRusBear** [comment]
@sebhildebrandt 
In version 4.14.8 this worked correctly

**Comment by sebhildebrandt** [comment]
@CreativeRusBear Thank you, very clear. Will provide a solution tomorrow. I added code to also cover situations, where `win32_desktopmonitor` does not provide usable information. But in your case this is not valid, so I will find a way to distinguish and provide the best available information.

**Comment by sebhildebrandt** [comment]
@CreativeRusBear should be solved now ... Version 4.14.17 just published
