### ISSUE TITLE
avgload not supported on windows

### ISSUE THREAD

**Issue by OhKai** [sebhildebrandt/systeminformation#289]
**Describe the bug**
The `currentLoad().avgload` property is always `0` on Windows since it uses NodeJS `os.avgload()` which will always return `[0, 0, 0]`. (See https://nodejs.org/api/os.html#os_os_loadavg) However, the documentation for systeminformation shows the property as working on Windows systems (https://systeminformation.io/processes.html)

**To Reproduce**

On Windows do the following:
`require('systeminformation').currentLoad().then(l => console.log(l.avgload))`

**Current Output**
`0` on Windows

**Expected behavior**
`> 0`

**Environment (please complete the following information):**
 - systeminformation package version: 4.14.4
 - OS: Windows
 - Hardware MacBook Pro 2017

**Comment by sebhildebrandt** [comment]
@OhKai Ok, this is incorrect in the documentation. So as there is no such concept in windows (therefore also node always return `[0, 0, 0]` on windows, the only way I see is to simulate something ... not sure when I will add this. In the meanwhile I will correct the documentation accordingly.
