### ISSUE TITLE
linux memory active incorrect value

### ISSUE THREAD

**Issue by i8beef** [sebhildebrandt/systeminformation#290]
**Describe the bug**
In memory.js, a change seems to have been made during a refactor a while back where "active" is now taken from /proc/meminfo's "Active" value. I'm assuming this is supposed to be "actively used memory", but that doesn't line up for me. Based on [RedHat's explanation of hte mapping to free](https://access.redhat.com/solutions/406773), I think that if this is the intention, it should be calculated as such: MemTotal - MemFree - Buffers - Cached - Slab

Further, `buffcache` was also changed to be calculated OFF OF `active`, which then makes BOTH values wrong. To match `free`, again taking from RedHat's mapping, I think buffcache should actually be: Buffers + Cached + Slab

**To Reproduce**
1. used memory.js `active` and `buffcache` values
2. results don't appear to match `free` or `/proc/meminfo` expectations

**Current Output**
`active` reflects /proc/meminfo's `Active` line instead of being calculated. `buffcache` is calculated off of this incorrect value and doesn't reflect any meaningful values from /proc/meminfo.

**Expected behavior**
Expected `active` to represent actively used memory, and `buffcache` to reflect buffer and cache usage. With the recent changes to Linux's `free` application, I think I'd expect numbers reported to match up with [the /proc/meminfo mapping provided by RedHat](https://access.redhat.com/solutions/406773).

**Environment (please complete the following information):**
 - systeminformation package version: 3.48.4
 - OS: Linux
 - Hardware: Intel NUC

**Comment by i8beef** [comment]
Note, simply commenting out the `active` and `buffcache` calculation in `memory.js` to fallback to the original `buffcache` implementation that is still in the file, and using this for active got closer to real numbers:

```
result.active = result.total - result.free - result.buffcache;
```

If the intent is to match with `free` output now, I think you'd have to include `slab` from /proc/meminfo as well in that calculation.

**Comment by i8beef** [comment]
Looking around, this calculation could be done multiple ways... `result.active = result.total - result.available` would also be acceptable, as that value takes into account more than you could get from simple math against `/proc/meminfo` according to [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773).

Ignoring `slab`, or exposing it optionally, could be useful in some cases, though like that link points out, theres a difference between `SReclaimable`, `SUnreclaim` and how it could be used in calculation / the combined value of `Slab`.

Based on my research, it seems like the best bet would be to do this:

```
result.buffcache = buffers + cached;
result.active = result.total - result.available;
```

Note that Active is actually described as "ram that has been actively used recently", but that INCLUDES by cache and buffers, slab, etc. apparently, so we're really missing the `free` equivalent of "used". You're already using `result.used` though to represent the OLD calculation of `free` instead of the new one that reflects buffers, cache and slab..

**Comment by sebhildebrandt** [comment]
@i8beef OK, will have a look at it this weekend! Thank you for reporting.

**Comment by sebhildebrandt** [comment]
@i8beef still thinking of how to get the best result here. I would like to do the following:

1. exposing also `slap` (and maybe also add `buffers` and `cache` separately)
2. calculation of `buffcache` should then include `slab` (due to your link to RedHat https://access.redhat.com/solutions/406773) ... but this is different to what you suggested in your last comment (`result.buffcache = buffers + cached`)

Then you mentioned two different ways to determine `active`:
- the one that I used (and commented out) `result.active = result.total - result.free - result.buffcache;`
- the one that you also suggested `result.active = result.total - result.available;`
Those two versions will have quite different results ...

What do you think?

**Comment by i8beef** [comment]
Keep in mind they changed the calculation a while back. On the at RedHat page they actually list both the old and the new calculation. My PR changes the ACTIVE calculation to the old "-/+ buffers/cache: used".  I chose to use this calculation because (a) Im not sure what the implication is of using the NEW calculation on OLDER distros, and (b) this was good enough for like 30 years... I.e., I thought I'd take the safe route.

I like the idea of exposing buffer, cache, and slab separately... if its safe to take the newer calculation, I ALSO like that idea better, I was just trying not to really CHANGE functionality here for anyone using this library, I was just trying to fix the BUG I think was there in what it seemed to be trying to calculate.

For active if you look at my PR I actually used your commented out version as I think thats correct. I'm thinking this should be the equivalent of that RedHat doc's Linux 7.1+ version of `Mem: used`: `MemTotal - MemFree - Buffers - Cached - Slab`.

**Comment by sebhildebrandt** [comment]
@i8beef ... so yes, ma commented out version misses the Slab ... I only calculated this by:

```
MemTotal - MemFree - Buffers - Cached
```

Actually `buffers + cache + free + slab` is not equal to MemAvailable ... at least not on my machines:

```
MemTotal:       32806380 kB
MemFree:        17977744 kB
MemAvailable:   19768972 kB
Buffers:          517028 kB
Cached:          2161876 kB
...
Slab:             335716 kB
```

where then `buffers + cache + free + slab` = 20992364 kB
and `MemAvailable` = 19768972 kB

So still the question, what to use to determine `active`...

**Comment by i8beef** [comment]
The slab calculation is much more involved than that apparently. I was never able to get the numbers to line up completely and Im not sure enough information is exposed to make it all match exactly. I had found an email from Linus explaining some of this, but from what I understand there is a difference between whats listed and "actually reclaimable". Slab is actually divided into two different denominations on /proc/memInfo one which should be reclaimable and one that shouldn't, but even if you add those together I don't think they add up to the total slab.

**Comment by sebhildebrandt** [comment]
@i8beef and even NOT taking `slab` into consideration, `buffers + cache + free` is still bigger than `memAvailable`. I consider now the following:

1. calculation of `buffcache` according to RedHats mapping: `Buffers + Cached + Slab` (so adding `slab`)
2. calculation of active: `active = total - available` (if MemAvailable exists in /proc/meminfo), otherwise `result.total - result.free - result.buffcache;`
3. expose also `slab`, `buffers`, `cache` separately.

What do you think?

**Comment by i8beef** [comment]
I updated the PR to your spec I think.

**Comment by sebhildebrandt** [comment]
Version 4.15.2. just released
