### ISSUE TITLE
CPU governor

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#294]
**Is your feature request related to a problem? Please describe.**
I'd like to have the CPU's governor setting returned in `si.cpu()`.

**Describe the solution you'd like**
```js
const { governor } = si.cpu();
console.log(governor); // performance
```

**Comment by sebhildebrandt** [comment]
@OmgImAlexis so generally this is what you are searching for?

```
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
```

Or is it something more specific you search for?

**Comment by OmgImAlexis** [comment]
Yep that’s the right data.

Would multiple CPUs be different?

**Comment by sebhildebrandt** [comment]
@OmgImAlexis New version 4.15.0 just released.
