### ISSUE TITLE
Reporting whether virtualization is enabled/disabled

### ISSUE THREAD

**Issue by ssmirr** [sebhildebrandt/systeminformation#295]
**Is your feature request related to a problem? Please describe.**
I think showing status of virtualization support in the output of `.cpu()` can be useful. 

**Describe the solution you'd like**
Get the status of virtualization support. On UNIX operating systems virtualization can be detected from CPU flags `vmx` (Intel) and `svm` (AMD). I wasn't able to find an easy way to check virtualization on Windows?

**Suggested behavior**
```
si.cpu()
---
{
  manufacturer: 'Intel®',
  ...
  virtualization: false
}
```

**Describe alternatives you've considered**
I considered checking CPU flags in my code, but that doesn't help with checking virtualization status on Windows. Also I think this functionality seems like a good addition for `systeminformation` package.

**Comment by sebhildebrandt** [comment]
@ssmirr ... good idea. Will provide a solution for that. Guess I have an idea also for windows.

**Comment by ssmirr** [comment]
cool, thanks @sebhildebrandt! looking forward to it.

**Comment by sebhildebrandt** [comment]
@ssmirr will be introduced in upcoming version 5. Should be available within the next 2-3 weeks

**Comment by sebhildebrandt** [comment]
@ssmirr Version 5.0 just released. `.si.spu()` now contains the virtualisation attributebute.

Be aware: Version 5 is NOT fully backwards compatible to version 5 ... see https://systeminformation.io/changes.html to get an overview over all breaking changes.

**Comment by ssmirr** [comment]
awesome, thanks a lot @sebhildebrandt! I will check it out 🚀

**Comment by ssmirr** [comment]
@sebhildebrandt I just tried `si.cpu()` version `5.0.2`, it works nicely on macOS, but on Windows it _doesn't_ seem to report correct virtualization status. 

On my Windows PC with virtualization enabled (I even have virtualbox VMs running right now), si reports `virtualization: false`. How does si check virtualization status on Windows?

For our usecase, we've been checking the output from `systeminfo` command on Windows until now, and make sure `Virtualization Enabled in Firmware: Yes` is present:
```
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

**Comment by ssmirr** [comment]
Update: I see this in the implementation of `si.cpu()`
https://github.com/sebhildebrandt/systeminformation/blob/cb2c057294c7ce1d94a3f6591d8ee3251ea2e709/lib/cpu.js#L552 
This is actually how we've been checking virtualization on macOS/Linux.

But on Windows with intel CPU I don't see `vmx` cpu flag reported by si 🤔

**Comment by sebhildebrandt** [comment]
@ssmirr ... ok, will try to implement it this way ... 

Can you check if this (from Powershell):

```
Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V
```

output give you the same result as your approach? My main question is, which one is faster ... can you provide both outputs?
Thank you in advance!

**Comment by ssmirr** [comment]
Please find the outputs below. I also included some suggestions from my experience with virtualization which I hope will help (sorry kinda too long).

So my understanding is these commands two _check different things_. 

On Windows there are **two** things to be aware of:

1. _Virtualization status_ (configured in BIOS) and can be checked in output from `systeminfo` command (There will be this line if enabled: `Virtualization Enabled In Firmware: Yes`)
2. _Hyper-V status_ (configured in Windows features and requires ^ virtualization in BIOS settings be enabled) and can be checked two ways, your command above (required Administrator), or `systeminfo` command (There will be this line if enabled: [`Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V will not be displayed.`](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements#final-check))

### Important note / Suggestion:
_You probably know this, but I think worth mentioning here._ 
For VirtulBox to work Hyper-V must be **Disabled**! So one can only use either VirtulBox/VMWare hypervisor or Hyper-V at a given time. Because of this, it might make sense to including two things in `si.cpu()` report: `{ virtualization: true, hyperv: false }` or `{ virtualization: true, hyperv: true }`.

```
> systeminfo
---

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
...
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```


`Get-WindowsOptionalFeature` requires elevation to Administrator rights, probably not ideal. 
My virtualization is enabled here, but my Hyper-V is disabled:
```
> Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V
---

FeatureName      : Microsoft-Hyper-V
DisplayName      : Hyper-V Platform
Description      : Provides the services that you can use to create and manage virtual machines and their resources.
RestartRequired  : Possible
State            : Disabled
CustomProperties :

```

**Comment by sebhildebrandt** [comment]
@ssmirr thank you for your detailed answer! Will make some tests on my machines and will come back with a solution the next days.

**Comment by ssmirr** [comment]
Thank you! Let me know if you want me to check anything else. 

btw this is how we've done it so far, if it helps:
https://github.com/ottomatica/virtcrud/blob/6d239f9c85251d0d13bcc64250f21f4c21ecfaeb/providers/util.js#L179-L222

**Comment by sebhildebrandt** [comment]
@ssmirr just released version 5.0.3 which should fix this ... I added detection also for German and French language as the systeminfo output unfortunately is localized. 

Can you give it a try?

**Comment by ssmirr** [comment]
Thanks @sebhildebrandt, I just tried it and now it works on Windows as well 👍 

I wasn't able to find if a property was added in the report for checking Hyper-V status?

**Comment by sebhildebrandt** [comment]
@ssmirr ... I addd this now to `osInfo()` as this is not really a cpu() property. Just pushed a first version to GitHub. Would you like to test it on one of your windows machines? Simple testing is described here: https://systeminformation.io/tests.html, and inside the test suite just press o for osInfo() and review results ;-)

If this is fine from your perspective, I will release a new version with this enhancement. 

Thank you for your help, your idea and your patience!

**Comment by ssmirr** [comment]
@sebhildebrandt I agree, having it separately in `osInfo()` makes sense. I tested the hyper-v status (both enabled and disabled) and it works great! 👌 

Thank you for making `systeminformation` and always adding improvements!

**Comment by sebhildebrandt** [comment]
@ssmirr Hi again, I would like to ask for some further assistance: As `systeminfo` spits out language dependent labels, I would like to modify the method used in my package. Currently I only support EN, DE and FR, but if there are other system languages, this would fail. 

Could you once again make a test with virtualization enabled and disabled and then running THIS from powershell:

```
Get-ComputerInfo -property "HyperV*"
```

and post the output here?
