### ISSUE TITLE
can't get system informations with board such as ASUS THINKERBOARD, PINE64

### ISSUE THREAD

**Issue by balbuze** [sebhildebrandt/systeminformation#297]
First, thank you for your great work!
I'm writing a plugin for Volumio https://volumio.org/volumio-overview/ to get info of the system used.

**Describe the bug**
With board such as thinkerboard, pine64, does not return info about system (see log below)
**To Reproduce**

**Current Output**
below a PINE64
`
Nov 16 10:02:58 volumio-pine64 volumio[11407]: { version: '4.15.3',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: system:
Nov 16 10:02:58 volumio-pine64 volumio[11407]: { manufacturer: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: model: 'SUN50IW1P1',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: version: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: serial: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: uuid: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: sku: '-' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: bios: { vendor: '', version: '', releaseDate: '', revision: '' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: baseboard:
Nov 16 10:02:58 volumio-pine64 volumio[11407]: { manufacturer: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: model: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: version: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: serial: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: assetTag: '' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: chassis:
Nov 16 10:02:58 volumio-pine64 volumio[11407]: { manufacturer: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: model: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: type: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: version: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: serial: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: assetTag: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: sku: '' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: os:
Nov 16 10:02:58 volumio-pine64 volumio[11407]: { platform: 'linux',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: distro: 'Debian GNU/Linux',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: release: '8',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: codename: 'jessie',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: kernel: '3.10.105-bsp-1.2+',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: arch: 'arm',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: hostname: 'volumio-pine64',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: codepage: 'UTF-8',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: logofile: 'debian',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: serial: '9ae7d04f188c6b64f0ec88a75da9d054',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: build: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: servicepack: '' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: uuid: { os: '9ae7d04f188c6b64f0ec88a75da9d054' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: versions:
Nov 16 10:02:58 volumio-pine64 volumio[11407]: { kernel: '3.10.105-bsp-1.2+',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: openssl: '1.0.2o',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: systemOpenssl: '1.0.1t',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: systemOpensslLib: 'OpenSSL',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: node: '8.11.1',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: v8: '6.2.414.50',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: npm: '5.6.0',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: yarn: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: pm2: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: gulp: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: grunt: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: git: '2.1.4',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: tsc: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: mysql: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: redis: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: mongodb: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: apache: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: nginx: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: php: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: docker: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: postfix: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: postgresql: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: perl: '5.20.2',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: python: '2.7.9',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: python3: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: pip: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: pip3: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: java: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: gcc: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: virtualbox: '' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: cpu:
Nov 16 10:02:58 volumio-pine64 volumio[11407]: { manufacturer: 'AArch64',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: brand: 'Processor rev 4 (aarch64)',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: vendor: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: family: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: model: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: stepping: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: revision: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: voltage: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: speed: '1.15',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: speedmin: '0.48',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: speedmax: '1.34',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: governor: 'performance',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: cores: 4,
Nov 16 10:02:58 volumio-pine64 volumio[11407]: physicalCores: 4,
Nov 16 10:02:58 volumio-pine64 volumio[11407]: processors: 4,
Nov 16 10:02:58 volumio-pine64 volumio[11407]: socket: '',
Nov 16 10:02:58 volumio-pine64 volumio[11407]: cache: { l1d: '', l1i: '', l2: '', l3: '' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: flags: 'fp asimd aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp edsp neon vfpv3 tlsi vfpv4 idiva idivt' },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: graphics: { controllers: [], displays: [] },
Nov 16 10:02:58 volumio-pine64 volumio[11407]: net:
`
Ok with Raspberry 4
`Nov 16 10:14:02 volumio-rpi4 volumio[2087]: { version: '4.15.3',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: system:
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: { manufacturer: 'Raspberry Pi Foundation',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: model: 'BCM2835 - Pi 4 Model B',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: version: 'b03111 - Rev. 1.1',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: serial: '100000002b4d9a4e',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: uuid: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: sku: '-' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: bios: { vendor: '', version: '', releaseDate: '', revision: '' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: baseboard:
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: { manufacturer: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: model: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: version: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: serial: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: assetTag: '' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: chassis:
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: { manufacturer: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: model: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: type: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: version: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: serial: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: assetTag: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: sku: '' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: os:
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: { platform: 'linux',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: distro: 'Raspbian GNU/Linux',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: release: '8',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: codename: 'jessie',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: kernel: '4.19.79-v7l+',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: arch: 'arm',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: hostname: 'volumio-rpi4',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: codepage: 'UTF-8',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: logofile: 'raspbian',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: serial: 'd5e28d677d616afad748b2b65dcd39f4',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: build: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: servicepack: '' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: uuid: { os: 'd5e28d677d616afad748b2b65dcd39f4' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: versions:
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: { kernel: '4.19.79-v7l+',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: openssl: '1.0.2o',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: systemOpenssl: '1.0.1t',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: systemOpensslLib: 'OpenSSL',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: node: '8.11.1',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: v8: '6.2.414.50',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: npm: '5.6.0',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: yarn: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: pm2: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: gulp: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: grunt: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: git: '2.1.4',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: tsc: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: mysql: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: redis: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: mongodb: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: apache: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: nginx: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: php: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: docker: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: postfix: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: postgresql: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: perl: '5.20.2',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: python: '2.7.9',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: python3: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: pip: '19.2.3',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: pip3: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: java: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: gcc: '4.9.2',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: virtualbox: '' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: cpu:
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: { manufacturer: 'ARMv7',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: brand: 'Processor rev 3 (v7l)',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: vendor: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: family: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: model: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: stepping: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: revision: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: voltage: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: speed: '1.50',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: speedmin: '0.60',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: speedmax: '1.50',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: governor: 'performance',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: cores: 4,
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: physicalCores: 4,
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: processors: 1,
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: socket: '',
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: cache: { l1d: '', l1i: '', l2: '', l3: '' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: flags: 'half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32' },
Nov 16 10:14:02 volumio-rpi4 volumio[2087]: graphics: { controllers: [], displays: [] },
`

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: Volumio

**Comment by sebhildebrandt** [comment]
@balbuze I have an older Pine64 here, will try to install Volumio to reproduce your findings. Please gibe me some time to verify and find a solution ...

**Comment by balbuze** [comment]
Sure! Do not hesitate if you need some info/help. My plugin is here : https://github.com/balbuze/volumio-plugins

**Comment by sebhildebrandt** [comment]
@balbuze I testet latest version 5.3.1 on pine64. As OS implementation Dows not give any information about what underlying hardware we have, `systeminformation` also cannot give more details. Basically I ran all function, and all returned without errors but of course if the OS does not provide more info, several attributes are just blank. If you have any idea where I can programatically get more detailed info on those boards, please feel free to reply here.
