### ISSUE TITLE
Please mention `unit` in battery information

### ISSUE THREAD

**Issue by ghost** [sebhildebrandt/systeminformation#298]
{ hasbattery: true,
  cyclecount: 0,
  ischarging: true,
  maxcapacity: 47520000,   // Please mention Unit
  currentcapacity: 14260000,   // Please mention Unit
  percent: 45,
  timeremaining: 24,
  acconnected: true,
  type: 'Li-ion',
  model: '42T4763',
  manufacturer: 'SANYO',
  serial: '13920' }

**Comment by pranavwani** [comment]
{ hasbattery: true,
cyclecount: 0,
ischarging: true,
maxcapacity: 47520000, // Please mention `Unit`
currentcapacity: 14260000, // Please mention `Unit`
percent: 45,
timeremaining: 24,
acconnected: true,
type: 'Li-ion',
model: '42T4763',
manufacturer: 'SANYO',
serial: '13920' }

**Comment by sebhildebrandt** [comment]
@pranavwani Please can you also provide some more detailed information about machine, and especially OS you are using to be able to reproduce your problem. Thank you in advance.

**Comment by pranavwani** [comment]
Ubuntu 19.10, Lenovo Thinkpad

**Comment by sebhildebrandt** [comment]
@pranavwani Thank you. One more thing. As it is on Linux, can you provide the output of the following:

(terminal)
```
cat /sys/class/power_supply/BAT1/uevent
```

and if this is empty ... the following would be an alternative:

```
cat /sys/class/power_supply/BAT0/uevent
```
Thank you in advance.

**Comment by sebhildebrandt** [comment]
@pranavwani would it be able to provide the information I asked for (see comment above)? Thank you in advance.

**Comment by sebhildebrandt** [comment]
Turns out that the units of the underlying commands are quite different (mWh, μAh, mAh). So I needed to make some conversions to get it consistent. All capacity values are now in mWh. I now also provide the voltage as an extra attribute so you can easity also calculate mAh values. Version 4.20.0 just released.
