### ISSUE TITLE
Return drives on Windows without network drives

### ISSUE THREAD

**Issue by perf2711** [sebhildebrandt/systeminformation#299]
**Is your feature request related to a problem? Please describe.**
`fsSize` on Windows returns network drives as well, which hangs for a long time, if any network drive is disconnected.

**Describe the solution you'd like**
You could pass an object with `networkMounts: false`, e.g.
```
fsSize((data) => ..., {
    networkMounts: false
});
```
or, if this could cause incompatibility with other systems:
```
fsSize((data) => ..., {
    windows: {
        networkMounts: false
    }
});
```

**Describe alternatives you've considered**
None at the moment.

**Additional context**
You can achieve this by calling 
`wmic logicaldisk where drivetype!=4 get Caption,FileSystem,FreeSpace,Size`.
https://superuser.com/a/1438110

If any of the proposed solutions are viable, I can submit a merge request with this functionality.

**Comment by sebhildebrandt** [comment]
@perf2711 I testet this option but this does not bring any performance gains. As soon as you disconnect a network drive (e.g. by disconnecting the network cable), `wmic localdisk... ` will take its time, no matter what `where` statement you add to it. As soon as Windows is aware of the missing network drive, both options (with and without the `where` again are fast. Closing this for now. But if your findings are different, I have this option ready to push to the package.
