### ISSUE TITLE
How to use it as module in NW.js?

### ISSUE THREAD

**Issue by Plasmmer** [sebhildebrandt/systeminformation#30]

**Comment by sebhildebrandt** [comment]
Hi, can you provide a little more information about, what you tried, etc. Then your question would make more sense for me. Not clear, if this is really a systeminformation issue.

**Comment by Plasmmer** [comment]
Its not exactly a issue, but a question. I would like to know how to use it in my Node-Webkit app, and turn the infos into texts to be shown. (my app have a UI)

**Comment by Plasmmer** [comment]
I suggest to introduce these infos in the docs.

**Comment by sebhildebrandt** [comment]
Hi again, I am not that familiar with NW.js right now, so I cannot really help ... I would anyway like close this issue now and add some notes to the docs later, when I figured out how this could work. OK for you?

**Comment by Plasmmer** [comment]
Yes. Would be nice know how to get the hardware infos and print into texts in page (UI), and how put it as module in NW.js. Electron is also a good runtime to support.
