### ISSUE TITLE
currentResX/Y seems incorrect

### ISSUE THREAD

**Issue by Suhail** [sebhildebrandt/systeminformation#300]
My goal is to differentiate between native resolution of a screen and it's scaled current resolution:

```
$ node
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> const si = require('systeminformation');
undefined
> si.graphics().then(data => console.log(data))
Promise { <pending> }
> {
  controllers: [
    {
      vendor: 'Intel',
      model: 'Intel Iris Plus Graphics 650',
      bus: 'Built-In',
      vram: 1536,
      vramDynamic: true
    },
    { vendor: '', model: '', bus: '', vram: -1, vramDynamic: false }
  ],
  displays: [
    {
      vendor: '',
      model: 'Color LCD',
      main: false,
      builtin: false,
      connection: '',
      sizex: -1,
      sizey: -1,
      pixeldepth: 30,
      resolutionx: 2560,
      resolutiony: 1600,
      currentResX: 2560,
      currentResY: 1600,
      positionX: 0,
      positionY: 0,
      currentRefreshRate: -1
    },
    {
      vendor: '',
      model: 'LG QHD',
      main: true,
      builtin: false,
      connection: 'DisplayPort',
      sizex: -1,
      sizey: -1,
      pixeldepth: 30,
      resolutionx: 2560,
      resolutiony: 1440,
      currentResX: 2560,
      currentResY: 1440,
      positionX: 0,
      positionY: 0,
      currentRefreshRate: -1
    }
  ]
}
```

The resolution on my macbook's retina screen is 1680x1050 -- I don't think it's possible to get 2560x1600 native resolution on the 13.3" screen.

If we're just using `system_profiler SPDisplaysDataType` here, it won't provide the scaled resolution we're looking for.

**Comment by sebhildebrandt** [comment]
Fortunately (as you have a Retina display) your MacBook Pro really has a native screen resolution of 2560 x 1600. See also https://www.apple.com/macbook-pro-13/specs/ ... under "Display" in the first text line you should see "... 2560‑by‑1600 native resolution ...". Also on your Mac, in the apple menu - About my Mac - in the display tab you should also see this. So I also tested it here on my machine and it also shows the correct resolution. Closing it here.

**Comment by Suhail** [comment]
@sebhildebrandt fwiw, a reliable way to get scaled resolution is this: https://wiki.libsdl.org/SDL_GetCurrentDisplayMode

If you don't want to use SDL, I am sure you can look at the source of how they accomplish it.
