### ISSUE TITLE
Please add info from DMI / DMIBIOS / SMBIOS

### ISSUE THREAD

**Issue by BillDietrich** [sebhildebrandt/systeminformation#301]
Just started using your package, sorry if this info is somewhere already and I haven't seen it.

I'm running under Electron on Linux Mint 19.2 Cinnamon.  Using version 4.15.3 of your package.

I would like your package to provide the information available from the DMI / DMIBIOS / SMBIOS area in /dev/mem (I think).  In Linux, there are command-line commands dmidecode, biosdecode, vpddecode to display this information and maybe more.  Some info at https://en.wikipedia.org/wiki/System_Management_BIOS

In particular, this area contains some information which apparently I can't get through your package: BIOS language, max size of RAM that can be installed onto the motherboard, is BIOS upgradeable, is ACPI supported in BIOS.  But I really would like a full listing of all info from this area.

I haven't found another Node module which will give this information, but maybe there is one ?

Thanks.

**Comment by sebhildebrandt** [comment]
@BillDietrich will have a look at it and will try to add it.

**Comment by sebhildebrandt** [comment]
@BillDietrich I made a little research on that: 

So first of all, on Linux we would need dmidecode. Where possible I avoided to use it, because this needs to be installed and you would need admin privileges. So my approach would now be, first get all information where dmidecode is not needed and then try to get additional information with dmidecode. I guess this is the best way. What do you think?

For Windows: here I also see some possibilities to add more information as requested.

**Comment by BillDietrich** [comment]
dmidecode is a linux CLI application.  My understanding is that it just reads from /dev/mem, and all the needed information is in there, you "just" have to know where to look in /dev/mem and how it's formatted.  So your package wouldn't run dmidecode, you'd read /dev/mem.  Yes, you would need admin privileges.

**Comment by BillDietrich** [comment]
Okay, just glanced at your code, and I see you ARE exec'ing standard commands and parsing their output.  So yes, you'd run dmidecode.  And yes, it requires admin privilege.

**Comment by sebhildebrandt** [comment]
@BillDietrich Added more information (memMax. memSlots to baseband, ECC to memLeyout, BIOS language, BIOS features). Version 5.1.1 just released. Closing it for now.
