### ISSUE TITLE
Please add info from inxi command on Linux

### ISSUE THREAD

**Issue by BillDietrich** [sebhildebrandt/systeminformation#302]
Please add some info from output of "inxi -Fmpxz" command on Linux, in particular the Audio information, and the System / Desktop value.  Thanks.

I'm using your package version 4.15.3 on Linux Mint 19.2.

**Comment by sebhildebrandt** [comment]
@BillDietrich ...as `inxi` also uses `dmidecode` (plus other commands) to provide the output, I will go more into the details of the script to see, if I can get some more information without the need to install `inxi` ... will probably take some time ;-)

For audio information I also prepared scripts ... will try to test it and add it to System Information as soon as possible.

**Comment by sebhildebrandt** [comment]
@BillDietrich version 5 of systeminformation now also has 

- audio information in place ... see docs https://systeminformation.io/audio.html
- bluetooth data ... https://systeminformation.io/bluetooth.html
- usb data ...https://systeminformation.io/usb.html
- printer ... https://systeminformation.io/printer.html

I also compared the output of `inxi -Fmpxz` with all available functions of `systeminformation` pretty much everything (plus some additional information) is available In this package. Anything you still miss?

**Comment by BillDietrich** [comment]
I haven't had time to focus on my project recently.  I will check it when I get a chance.  You could close this issue if you wish.  Thanks.

**Comment by sebhildebrandt** [comment]
@BillDietrich OK, I will close this one for now, But feel free to reply here if you discover any things, you wish to see in systeminformation. I am currently working on adding a little bit more information as you requested in #301 ... hope to finish this by tomorrow.
