### ISSUE TITLE
OS.platform values wrong in README

### ISSUE THREAD

**Issue by BillDietrich** [sebhildebrandt/systeminformation#303]
README file says OS.platform values have first letter capitalized ("Linux"), but in fact the software produces them in lowercase ("linux").  At least on Linux Mint 19.2.  Package version 4.15.3.

**Comment by sebhildebrandt** [comment]
My fault. Will correct it.

**Comment by BillDietrich** [comment]
Also, on a Windows 10 Home system, I get platform "win32" instead of "Windows" or "windows".

**Comment by sebhildebrandt** [comment]
@BillDietrich Fixed, version 4.16.0 just published
