### ISSUE TITLE
Linux si.fsSize is incorrect

### ISSUE THREAD

**Issue by jdziat** [sebhildebrandt/systeminformation#305]
**Describe the bug**
When using this library on linux the size in bytes is being reported incorrectly. Looking at the source it appears it's just running a standard ```df``` call. The call for darwin is working as expected.

**To Reproduce**
1. Run si.fsSize on a centos machine
2.```const fsSizes = await si.fsSize()```
3. compare against df -h human readable output

**Current Output**
df -h output:
```
/dev/sda1                                         50G   23G   28G  46% /
```
fsSize
```
{
    fs: '/dev/sda1',
    type: 'xfs',
    size: 53674864640,
    used: 24288907264,
    use: 45.25,
    mount: '/'
  }
```
size reports as 53G instead of the expected 50G

**Expected behavior**
An accurate return value

**Environment (please complete the following information):**
 - systeminformation package version:	4.15.3
 - OS: centos 7
 - Hardware: GCP vm

**Comment by sebhildebrandt** [comment]
@jdziat This is absolutely correct

The help page of `df` states:

```
  -h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
  -H, --si              print sizes in powers of 1000 (e.g., 1.1G)
```

So `df -h` would be then in your case 
50 * 1024 * 1024 * 1024 = 53.687.091.200 

If you do `df -H`you should also get 53GB
