### ISSUE TITLE
Various fields on Windows 10 Home system

### ISSUE THREAD

**Issue by BillDietrich** [sebhildebrandt/systeminformation#306]
DiskLayout field "device" has value "" for all drives.  Is it possible to return values such as "C:" and "D:" in that field, or some other way to connect diskLayout entry with corresponding fs entry ?  On Linux, the names are /dev/sda and /dev/sdaN, so software can figure out the connection.  How can I do that on Windows ?

DiskLayout field "type" has value "Unspecified" for a USB flash drive; should be documented in README.

Net results for the first network interface include this, which seems wrong:
    "iface": "Wi-Fi",
    "ifaceName": "Broadcom BCM43142 802.11 bgn Wi-Fi M.2 Adapter",
    "type": "wired",

I'm pretty sure the Windows machine has a wired-Ethernet port, although no cable is plugged into it.  That interface doesn't appear as an entry in net.  Do only active interfaces get reported ?

I think I get zero blockDevices entries from calling systeminformation.blockDevices().  Have to double-check my code, but same code works on Linux.  Is this normal on Windows 10 Home, zero entries in blockDevices ?

**Comment by sebhildebrandt** [comment]
@BillDietrich as I now improving the new version 5, I cam again across this issue.

- DiskLayout device: this does NOT map to a specific drive latter. You can have multiple partitions on one single disk drive.
- WIFI: this is interesting as I determine the type from the WMIC address type. Can you provide the output of

```
wmic nic get MACAddress, name, NetEnabled, Speed, NetConnectionStatus, AdapterTypeId /value
```

on this machine with the Broadcom WiFi interface? Thank you in advance.

**Comment by BillDietrich** [comment]
I'm on Linux (Kubuntu 20.10 now).

```
$ wmic nic get MACAddress, name, NetEnabled, Speed, NetConnectionStatus, AdapterTypeId /value
Command 'wmic' not found, did you mean:
  command 'gmic' from deb gmic (2.4.5-1.1build2)
  command 'wmiv' from deb wmaker (0.95.9-2)
  command 'wmlc' from deb wap-wml-tools (0.0.4-7build1)
  command 'wmix' from deb wmix (3.5-1)
  command 'rmic' from deb openjdk-11-jdk-headless (11.0.9.1+1-0ubuntu1~20.10)
  command 'rmic' from deb openjdk-8-jdk-headless (8u275-b01-0ubuntu1~20.10)
  command 'rmic' from deb openjdk-13-jdk-headless (13.0.4+8-1)
  command 'rmic' from deb openjdk-14-jdk-headless (14.0.2+12-1)
  command 'mwic' from deb mwic (0.7.8-1)
Try: sudo apt install <deb name>
```

**Comment by sebhildebrandt** [comment]
@BillDietrich ... as you opened this issue as a Windows 10 Home issue/request I thought, you are on a Windows 10 Home machine. WMIC of course will not work on linux. 

For the windows network issue (Wi-fi) you described I have a fix ready which I will publish the next few days. If this issue also is relevant on your linux machine, please provide the output of the following command:

```
cat /sys/class/net/IFACE/type
cat /proc/net/wireless | grep IFACE
```

Be sure to replace IFACE with your specific interface name ...
Thank you in advance.

**Comment by BillDietrich** [comment]
Sorry, I had forgotten the context of this issue.  Attached is file from Win10 machine.
[Text File.txt](https://github.com/sebhildebrandt/systeminformation/files/5885974/Text.File.txt)

**Comment by BillDietrich** [comment]
From my Kubuntu 20.10 machine:

	$ ip addr
	1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
		link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
		inet 127.0.0.1/8 scope host lo
		valid_lft forever preferred_lft forever
		inet6 ::1/128 scope host 
		valid_lft forever preferred_lft forever
	2: enp19s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
		link/ether f0:4d:a2:b9:b3:c8 brd ff:ff:ff:ff:ff:ff
	3: wlp18s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
		link/ether 1c:65:9d:c8:c1:94 brd ff:ff:ff:ff:ff:ff
		inet 192.168.1.132/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp18s0
		valid_lft 86242sec preferred_lft 86242sec
		inet6 fe80::1e65:9dff:fec8:c194/64 scope link 
		valid_lft forever preferred_lft forever
	$ cat /sys/class/net/wlp18s0/type
	1
	$ sudo cat /proc/net/wireless | grep wlp
	wlp18s0: 0000   66.  -44.  -256        0      0      0      0      0        0
	$

**Comment by sebhildebrandt** [comment]
@BillDietrich ok, so with the latest version you should get on windows correct type ... windows does not provide the correct AdapterTypeID (according to their documentation) but I fix ed this with some "aftermath".

For Kubuntu the si results (netwoerkInterface --> type) anyway should be fine as, correct?

**Comment by BillDietrich** [comment]
I don't recall, to be honest.  I've been doing other projects for 6-9 months.  I'll have to pick up this project again soon.  Thanks.

**Comment by sebhildebrandt** [comment]
@BillDietrich OK, as I checkt the output of the commands on linux, this is absolutely fine and the information I am relying in is the result should be fine. Closing it for now.
