### ISSUE TITLE
In NW.js project, print the infos in a HTML tag

### ISSUE THREAD

**Issue by Plasmmer** [sebhildebrandt/systeminformation#31]
How do it?

**Comment by sebhildebrandt** [comment]
Will give you an answer, as soon as I testet it with NW.js.

**Comment by Plasmmer** [comment]
@sebhildebrandt and in Electron, it is tested?

**Comment by sebhildebrandt** [comment]
Not yet tested. But I guess, there will be problems because unter the hood, systeminformation make a lot of system call ... I play to test it end of May ...
