### ISSUE TITLE
Local network monitiring possibility

### ISSUE THREAD

**Issue by valkondratiev** [sebhildebrandt/systeminformation#310]
Hi!
Can I get params of local network PC (remote Windows computer) with your library ?
I know it is possible with wmic. I try to make custom app for local network monitoring and I'm interested to use your library. 
It is new experience for me.
Thank you in advance!

**Comment by valkondratiev** [comment]
Maybe add parametrs to wmic command solve my problem 

wmic /NODE:"servername" /USER:"yourdomain\administrator" /PASSWORD:”password”

**Comment by sebhildebrandt** [comment]
@valkondratiev I thought about it but I guess this is out of scope of this library. Here I want to just provide functionality to get all data of a local machine and the challenge here is to provide this across several platforms. Closing it for now.
