### ISSUE TITLE
ifconfig command not found on OS X with electron

### ISSUE THREAD

**Issue by OhKai** [sebhildebrandt/systeminformation#313]
**Describe the bug**
When trying to read the network interfaces on macOS, the electron console logs
`/bin/sh: ifconfig: command not found` and returns an empty array.

**To Reproduce**
1. used function si.networkInterfaces()
2. const interfaces = await si.networkInterfaces();
3. Inside an electron app (using vue-cli)
4. Error log: `/bin/sh: ifconfig: command not found`

**Current Output**
Empty array

**Expected behavior**
Array of network interfaces

**Environment (please complete the following information):**
 - systeminformation package version: 4.16.0
 - OS: macOS
 - Hardware MacBook Pro 2017

**Additional context**
I created a PR #312 that fixes this problem by including `/sbin/` in the command like it is done at the other places in the code where ifconfig is called.

**Comment by sebhildebrandt** [comment]
@OhKai fixed... Version 4.16.1 just released
