### ISSUE TITLE
fsSize hangs and never returns if there are disconnected network drives

### ISSUE THREAD

**Issue by jeghers** [sebhildebrandt/systeminformation#314]
**Describe the bug**
If there are network drives that have lost connectivity, then fsSize will never return any data.

**To Reproduce**
1. Coded a nodejs/express route to read file system data
2. code snippet:
```
router.get('/fs', (req, res) => {
  console.log('call fs');
  si.fsSize((data) => {
    console.log('fs data...');
    console.log(data);
    res.json({ output: data });
  });
});
```
3. If you run the app with network drives connected, all is well
4. Now move the computer to a different WiFi where the network drives are not available
5. Restart the app again and try to read file system info
6. Now fsSize will never return data.

**Expected behavior**
fsSize will return data

**Environment (please complete the following information):**
 - systeminformation package version: 4.16.0
 - OS: [e.g. macOS] Win10
 - Hardware [e.g. MacBook Pro 13] Lenovo Flex 5 laptop

**Comment by sebhildebrandt** [comment]
@jeghers Made some investigations recently and my findings are:

Windows needs some time to recognise, that the drive is lost. So when you run 

```
wmic logicaldisk get /value
```

immediately when the drive was list, it will return, but takes some time.

If a drive is lost and then after some time you call the same command, it returns quite fast. In all cases, systeminformation returned values, but yes, in the scenario you described, it took longer.

Closing it for now.
