### ISSUE TITLE
Using si.networkStats () to return operastate is always up, no down

### ISSUE THREAD

**Issue by huang-ju** [sebhildebrandt/systeminformation#316]
**Describe the bug**
Using ``si.networkStats ()`` to return ``operastate`` is always up, no down

**To Reproduce**
```
        setInterval(function() {
          si.networkStats().then(data => {
            console.log("networkStats  ", data[0].operstate);
          });
        }, 1000);
```

**Current Output**
![image](https://user-images.githubusercontent.com/46550127/70922304-d45c7600-2060-11ea-961a-b459c54bd9e9.png)

**Expected behavior**

**Environment (please complete the following information):**
macOS 10.14.4

**Additional context**

**Comment by sebhildebrandt** [comment]
Hi @huang-ju ... I do not know, how you made this working within the browser (Google Chrome I guess) ... so when I try to run this in node this works absolutely fine (testet with macOS 10.13 up to macOS 10.15.2). Please first try to run this in node, with altering e.g. activating 7 deactivating WIFI connection. If this also does not work, please provide a little more information on what you have done ...

**Comment by THROFHR** [comment]
> Hi @huang-ju ... I do not know, how you made this working within the browser (Google Chrome I guess) ... so when I try to run this in `node.js` this works absolutely fine (tested just a moment ago with macOS 10.13 up to macOS 10.15.2). Please first try to run this in `node.js`, with altering e.g. activating & deactivating WIFI connection. If this also does not work, please provide a little more information on what you have done ...

Had similar issue.  operstate field It always returns "up" whether I upload or download a file.

MacOx：10.14.6
NodeJs: v12.14.0 

By the way, "rx_sec" and "tx_sec" are seem to be my current download and upload transfer bytes. What does the operstate field mean?

**I want to know how to get my current download and upload transfer speed in code ？**


```
// npm i systeminformation@4.15.0 -S
const si = require('systeminformation');

var format = (text) => {
  var bytes = Number(text)
  if (!bytes) return '0 B'
  var k = 1024
  var sizes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']
  var i = Math.floor(Math.log(bytes) / Math.log(k))
  return (bytes / Math.pow(k, i)).toPrecision(3) + ' ' + sizes[i]
}
setInterval(function() {
  si.networkStats().then(data => {
    var resp = data.map((item) => {
      return {
        iface: item.iface,
        operstate: item.operstate,
        rx_sec: format(item.rx_sec),
        tx_sec: format(item.tx_sec),
      }
    })
    console.log(resp);
  })
}, 1000)
```

![Screen Shot 2019-12-27 at 11 42 33 AM](https://user-images.githubusercontent.com/13469743/71500048-29d52600-289e-11ea-8626-1e6b04fd2d86.png)

**Comment by sebhildebrandt** [comment]
@huang-ju @THROFHR 
- `operstate` indicates if a network interface is up or down (e.g. when you deactivate your WIFI, `operstate`  for this interface should go from up to down). See also documentation https://systeminformation.io/network.html
- `rx_sec` and `tx_sec` are the - sc you stated  the current transfer speeds per bytes / second ... see also documentation.

So I do not really see an issue here ... maybe I misunderstood your questions. Please do not hesitate to add some more information here related to the issue.

**Comment by THROFHR** [comment]
@sebhildebrandt Okay thank you.
Sorry, I got it wrong with the meaning of "operstate"

**Comment by sebhildebrandt** [comment]
closing it for now.
