### ISSUE TITLE
systeminformation should force code page in Windows 10 Russian

### ISSUE THREAD

**Issue by evrico** [sebhildebrandt/systeminformation#317]
systeminformation.osInfo().distro returns a serie of ? characters instead of russian characters on Russian OS.
It seems that wmic('os get /value') is not UTF-8 (see: https://github.com/nodejs/node-v0.x-archive/issues/2190).

1. try following code:
const execSync = require('child_process').execSync;
let es = execSync('echo test:  Русская сова', { encoding: 'utf8' });
console.log('execSync:', es);
let es2 = execSync('**chcp 65001 |** echo test2: Русская сова', { encoding: 'utf8' });
console.log('execSync:', es2);

2. See output:
execSync: test:  ??????? ????
execSync: test2: Русская сова

3. I've done a quick dirty test mofifying your util.js:wmic function that seems to fix the issue:
exec(**process.env.WINDIR + '\\system32\\chcp.com 65001 | '** + getWmic() + ' ' + command, options, function (error, stdout)...

Environment:
 - systeminformation package version: 6.7.0
 - OS: Windows 10 Russian

Note: this fix should work for any language. We found this issue for Russian but it may occur with others languages as Japanese...

**Comment by sebhildebrandt** [comment]
@evrico ... I had this problem already with another user but forcing to use this codepage did not worked at all for him. I will provide a version where you can test this once again on your side, OK? Please give me a little time to prepare it for you.

**Comment by evrico** [comment]
Hi @sebhildebrandt, any news about this problem?

**Comment by evrico** [comment]
Hi @sebhildebrandt,
do you plan to release a fix soon?

**Comment by sebhildebrandt** [comment]
@evrico ... please also have a look at https://github.com/sebhildebrandt/systeminformation/issues/148 ... here we had the same discussion and `chcp 65001` did not solved the problem ... 

Anyway, I just pushed a version to GitHub (not to npm yet) which you should give a try ... if you grab the new `/lib/util.js`and try again all functions where you expect Russian characters, that would be fine ... then we can see if we make some progress here ...

Would be nice if you post your finings here.

**Comment by evrico** [comment]
Hi @sebhildebrandt, your fix is perfect for us, please publish to npm.

**Comment by sebhildebrandt** [comment]
@evrico yes Eric, I will just make a few tests tomorrow if I see any side effects and then publish this. Thank you for testing.

**Comment by sebhildebrandt** [comment]
@evrico  Version 4.27.8 just released.
