### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by Manviel** [sebhildebrandt/systeminformation#319]
**Describe the bug**
I setup new project, install dependencies and getting error Unsupported platform

**To Reproduce**
1. npm install systeminformation --save
2. can't resolve 'osx-temperature-sensor'
3. npm install osx-temperature-sensor --save
4. wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Expected behavior**
Working without platform bindings

**Environment:**
OS: Ubuntu 18.04

**Notes:**
This code si.cpu().then(data => console.log(data)) does not work in the console

**Comment by sebhildebrandt** [comment]
Hi @Manviel , not sure what you are doing here, cannot reproduce your problem ... as `systemInformation` has no dependency, it should NOT try to install `osx-temperature-sensor`. Please check, if in your project any other package has that dependency. 

I just tried it once again in a clean new project with 

```
mkdir test
cd test
npm init -y
nem install systeminformation --save
```

No problems at all ...

**Comment by Manviel** [comment]
No error. Nothing is output to the console
