### ISSUE TITLE
Cannot read property 'trim' of undefined & ifconfig: command not found 

### ISSUE THREAD

**Issue by Bastiaantjuhh** [sebhildebrandt/systeminformation#321]
**Describe the bug**
I got an error with the CPU function I tried different methods and functions of the Npm package but nothing seems to work. its a issue with the CPU Speed method I think. Oh my terminal said that 'ifconfig' isn't found but this is default on MacOS. How can I fix this issue, is it a bug, or something with my system?

**To Reproduce**
```javascript
si.getStaticData((data) => { console.log(data); });
```

**Current Output**
```bash
/bin/sh: ifconfig: command not found
/Users/bastiaan/Documents/nodejs/npm-rpi-status/node_modules/systeminformation/lib/cpu.js:310
          result.speed = modelline.split('@')[1].trim();
                                                ^

TypeError: Cannot read property 'trim' of undefined
    at /Users/bastiaan/Documents/nodejs/npm-rpi-status/node_modules/systeminformation/lib/cpu.js:310:49
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
```

**Environment (please complete the following information):**
 - systeminformation package version: 4.16.0
 - OS: MacOS 10.15.2
 - Hardware: MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by Bastiaantjuhh** [comment]
If I remove the follow lines (308 - 312) in "lib/cpu.js" the code is working

```javascript
const modelline = util.getValue(lines, 'machdep.cpu.brand_string');
result.brand = modelline.split('@')[0].trim();
result.speed = modelline.split('@')[1].trim();
result.speed = parseFloat(result.speed.replace(/GHz+/g, '')).toFixed(2);
_cpu_speed = result.speed;
```

**Comment by Bastiaantjuhh** [comment]
#313 Fixed the issue with ifconfig for me

**Comment by sebhildebrandt** [comment]
@Bastiaantjuhh will make a more detailed investigation.

**Comment by sebhildebrandt** [comment]
@Bastiaantjuhh can you provide the output of 

```
sysctl machdep.cpu.brand_string hw.cpufrequency_max hw.cpufrequency_min
```

Thank you in advance.

**Comment by sebhildebrandt** [comment]
@Bastiaantjuhh ... maybe I also have to add the absolute path here on line 305. Can you modify it on your side and test it once again? ... so this line then would be:

```
exec('/usr/sbin/sysctl machdep.cpu hw.cpufrequency_max hw.cpufrequency_min hw.packages hw.physicalcpu_max hw.ncpu', function (error, stdout) {
```

**Comment by Bastiaantjuhh** [comment]
I do not know what has changed between version 4.16 and version 4.16.1 (not something special according to the commits) but all data is now perfectly loaded.

Thank you in advance. ;-)

> @Bastiaantjuhh can you provide the output of
> 
> ```
> sysctl machdep.cpu.brand_string hw.cpufrequency_max hw.cpufrequency_min
> ```
> 
> Thank you in advance.

```bash
machdep.cpu.brand_string: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
hw.cpufrequency_max: 2700000000
hw.cpufrequency_min: 2700000000
```





> @Bastiaantjuhh ... maybe I also have to add the absolute path here on line 305. Can you modify it on your side and test it once again? ... so this line then would be:
> 
> ```
> exec('/usr/sbin/sysctl machdep.cpu hw.cpufrequency_max hw.cpufrequency_min hw.packages hw.physicalcpu_max hw.ncpu', function (error, stdout) {
> ```

```javascript
cpu: {
    manufacturer: 'Intel®',
    brand: 'Core™ i5-5257U',
    vendor: 'GenuineIntel',
    family: '6',
    model: '61',
    stepping: '4',
    revision: '',
    voltage: '',
    speed: '2.70',
    speedmin: '2.70',
    speedmax: '2.70',
    governor: '',
    cores: 4,
    physicalCores: 2,
    processors: 1,
    socket: '',
    cache: { l1d: 32768, l1i: 32768, l2: 262144, l3: 3145728 },
    flags: 'fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfsh ds acpi mmx fxsr sse sse2 ss htt tm pbe sse3 pclmulqdq dtes64 mon dscpl vmx est tm2 ssse3 fma cx16 tpr pdcm sse4.1 sse4.2 x2apic movbe popcnt aes pcid xsave osxsave seglim64 tsctmr avx1.0 rdrand f16c'
}
```

**Comment by sebhildebrandt** [comment]
Ok. Closing it for now.
