### ISSUE TITLE
si.osInfo() opening notepad on Windows 10 1903

### ISSUE THREAD

**Issue by oznu** [sebhildebrandt/systeminformation#323]
**Describe the bug**

When running `si.osInfo()` on Windows 10 it triggers Notepad to open a file named `setupact`. 

The promise is not resolved until Notepad is closed. When running as a service user the Notepad.exe process is not visible to the user so the promise never resolves.

![image](https://user-images.githubusercontent.com/3979615/72313205-b2492880-36de-11ea-967c-4a510da0472d.png)

**To Reproduce**

```
> const si = require('systeminformation')
undefined
> si.osInfo()
Promise { <pending> }
```

**Expected behavior**

Notepad should not open.

**Environment (please complete the following information):**
 - systeminformation package version: v4.19.0
 - OS: Windows 10 Home 1903
 - Hardware: Parallels Desktop

**Comment by oznu** [comment]
This issue does not occur when using systeminformation v4.18.3.

**Comment by sebhildebrandt** [comment]
@oznu sorry! Definitely my fault! Hope I fixed it now ... version 4.19.1 just released. Can you test it also on your side?

**Comment by oznu** [comment]
Hi @sebhildebrandt,

Thanks for the super fast response. I can confirm this has resolved the issue.

Thank you 😄
