### ISSUE TITLE
Trying to query the fstype for a given path

### ISSUE THREAD

**Issue by benwiley4000** [sebhildebrandt/systeminformation#324]
**Is your feature request related to a problem? Please describe.**

Is there a way I can query the fstype for the file system path I'm about to write? I basically want to find out if I'm writing to a FAT target so I can replace illegal characters if so. Not sure an easy way to do this with the `blockDevices` API.. I might be missing something.

**Comment by benwiley4000** [comment]
I'm still curious to know but my final solution was to just try writing a file to disc and see if it errors

**Comment by sebhildebrandt** [comment]
@benwiley4000 cleaning up older issues ... just had a look at this again: basically this should be easy. Something like this should do the trick (not testet, but I hope you get the idea):

```
function getFsTypeOfPath(path) {
    const fsType = si.fsType();
    let matchString = '';
    let result = '';
    fsType.forEach(fs => {
        if (path.startsWith(fs.mount) && fs.mount.length > matchString.length) {
            matchString = fs.mount;
            result = fs.type;
        }
    })
    return(result)
)
```

Hope that helps ...
