### ISSUE TITLE
si.cpu(cb) missing multisoked CPU

### ISSUE THREAD

**Issue by BolverBlitz** [sebhildebrandt/systeminformation#325]
The promise returns the information of only one CPU out of my two CPUs in the system. (Win Server 2019)

![grafik](https://user-images.githubusercontent.com/35345288/72679696-e8f1bb00-3ab1-11ea-89f0-4d3207eb4c93.png)

**To Reproduce**
let Hardware = new Promise(function(resolve, reject) {
    si.cpu().then(cpu => {
    console.log(cpu)
    });
}
**Current Output**
{
  manufacturer: 'Intel®',
  brand: 'Xeon® E5-2667 v2',
  vendor: 'GenuineIntel',
  family: '6',
  model: '62',
  stepping: '4',
  revision: '15876',
  voltage: '',
  speed: '3.30',
  speedmin: '',
  speedmax: '3.30',
  governor: '',
  cores: 16,
  physicalCores: 8,
  processors: 1,
  socket: 'LGA2011',
  cache: { l1d: 0, l1i: 0, l2: 2097152, l3: 26214400 }
}

**Expected behavior**
  processors: 2,
OR
a array with all CPUs in the System like cpu[1].physicalCores

**Environment (please complete the following information):**
 - systeminformation package version: 4.19.1
 - OS: Windows Server 2019
 - Hardware: Look picture above

**Comment by sebhildebrandt** [comment]
@BolverBlitz thank you for report. Need to make further investigation on this. Can you provide the output pf the following statement (command line):

```
wmic cpu get /value
```

Thank you in advance.

**Comment by BolverBlitz** [comment]
AddressWidth=64
Architecture=9
AssetTag=
Availability=3
Caption=Intel64 Family 6 Model 62 Stepping 4
Characteristics=252
ConfigManagerErrorCode=
ConfigManagerUserConfig=
CpuStatus=1
CreationClassName=Win32_Processor
CurrentClockSpeed=3301
CurrentVoltage=0
DataWidth=64
Description=Intel64 Family 6 Model 62 Stepping 4
DeviceID=CPU0
ErrorCleared=
ErrorDescription=
ExtClock=100
Family=179
InstallDate=
L2CacheSize=2048
L2CacheSpeed=
L3CacheSize=25600
L3CacheSpeed=0
LastErrorCode=
Level=6
LoadPercentage=1
Manufacturer=GenuineIntel
MaxClockSpeed=3301
Name=Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz
NumberOfCores=8
NumberOfEnabledCore=8
NumberOfLogicalProcessors=16
OtherFamilyDescription=
PartNumber=
PNPDeviceID=
PowerManagementCapabilities=
PowerManagementSupported=FALSE
ProcessorId=BFEBFBFF000306E4
ProcessorType=3
Revision=15876
Role=CPU
SecondLevelAddressTranslationExtensions=FALSE
SerialNumber=
SocketDesignation=CPU1
Status=OK
StatusInfo=3
Stepping=
SystemCreationClassName=Win32_ComputerSystem
SystemName=SRV-MB-01
ThreadCount=16
UniqueId=
UpgradeMethod=38
Version=
VirtualizationFirmwareEnabled=FALSE
VMMonitorModeExtensions=FALSE
VoltageCaps=


AddressWidth=64
Architecture=9
AssetTag=
Availability=3
Caption=Intel64 Family 6 Model 62 Stepping 4
Characteristics=252
ConfigManagerErrorCode=
ConfigManagerUserConfig=
CpuStatus=1
CreationClassName=Win32_Processor
CurrentClockSpeed=3300
CurrentVoltage=0
DataWidth=64
Description=Intel64 Family 6 Model 62 Stepping 4
DeviceID=CPU1
ErrorCleared=
ErrorDescription=
ExtClock=100
Family=179
InstallDate=
L2CacheSize=2048
L2CacheSpeed=
L3CacheSize=25600
L3CacheSpeed=0
LastErrorCode=
Level=6
LoadPercentage=4
Manufacturer=GenuineIntel
MaxClockSpeed=3300
Name=Intel(R) Xeon(R) CPU E5-2667 v2 @ 3.30GHz
NumberOfCores=8
NumberOfEnabledCore=8
NumberOfLogicalProcessors=16
OtherFamilyDescription=
PartNumber=
PNPDeviceID=
PowerManagementCapabilities=
PowerManagementSupported=FALSE
ProcessorId=BFEBFBFF000306E4
ProcessorType=3
Revision=15876
Role=CPU
SecondLevelAddressTranslationExtensions=FALSE
SerialNumber=
SocketDesignation=CPU2
Status=OK
StatusInfo=3
Stepping=
SystemCreationClassName=Win32_ComputerSystem
SystemName=SRV-MB-01
ThreadCount=16
UniqueId=
UpgradeMethod=38
Version=
VirtualizationFirmwareEnabled=FALSE
VMMonitorModeExtensions=FALSE
VoltageCaps=

**Comment by sebhildebrandt** [comment]
@BolverBlitz  Thank you!! This will help to fix the bug! Will work on it tomorrow.

**Comment by sebhildebrandt** [comment]
@BolverBlitz ... should be fixed now. I also corrected count of cores reflecting the multiple cpus. Version 4.19.2 just released.

**Comment by BolverBlitz** [comment]
Now works as expected. Thank you!
