### ISSUE TITLE
Error getting the default Gateway

### ISSUE THREAD

**Issue by juancampuzano** [sebhildebrandt/systeminformation#326]
**Describe the bug**
I am getting the default Gateway using the networkGatewayDefault () method, but it is not bringing any information.

I am currently using the Systeminformation version: 4.19.2

**To Reproduce** **Current Output**

![image](https://user-images.githubusercontent.com/52759609/72819175-c6d77480-3c3a-11ea-90d9-99b5b09f0fc7.png)

![image](https://user-images.githubusercontent.com/52759609/72819598-888e8500-3c3b-11ea-9174-3d48f9babff7.png)

**Expected behavior**
Show default gateway 

**Environment (please complete the following information):**
 - systeminformation package version: 4.19.2
OS: Microsoft Windows 7 Enterprise
Vendor: Microsoft
Version: 6.1.7601
Architecture: x64
Manufacturer: LENOVO
Model: 10A8A14H00

**Additional context**
the computer is in Spanish, there could be a problem with the tildes
 iface: 'Conexión de área local'

**Comment by sebhildebrandt** [comment]
@juancampuzano could you provide the output of the following commands:

in Node:

```
console.log(os.networkInterfaces())
```

in command line

```
netstat -r
```

Thank you in advance ...

**Comment by juancampuzano** [comment]
**1) Console.log(os.networkInterfaces())**
`Interfaces  [
  {
    iface: 'Conexión de área local',
    ifaceName: 'Intel(R) Ethernet Connection I217-LM',
    ip4: '192.168.1.54',
    ip6: '',
    mac: 'd8:cb:8a:25:20:cb',
    internal: false,
    virtual: false,
    operstate: 'up',
    type: 'wired',
    duplex: '',
    mtu: '',
    speed: 1000,
    dhcp: 'true',
    dnsSuffix: '',
    ieee8021xAuth: 'Unknown',
    ieee8021xState: 'Unknown',
    carrierChanges: 0
  },
  {
    iface: 'Loopback Pseudo-Interface 1',
    ifaceName: 'Loopback Pseudo-Interface 1',
    ip4: '127.0.0.1',
    ip6: '::1',
    mac: '00:00:00:00:00:00',
    internal: true,
    virtual: false,
    operstate: 'down',
    type: '',
    duplex: '',
    mtu: '',
    speed: -1,
    dhcp: false,
    dnsSuffix: '',
    ieee8021xAuth: 'Unknown',
    ieee8021xState: 'Unknown',
    carrierChanges: 0
  }
]
`

**2) netstat -r**

![netstat](https://user-images.githubusercontent.com/52759609/72900784-83424080-3cf6-11ea-9b8f-6682bbeec13c.PNG)

**Comment by sebhildebrandt** [comment]
Thank you @juancampuzano 
Will try to simulate it with your data...

**Comment by sebhildebrandt** [comment]
@juancampuzano ... sorry for disturbing once again. As I was not able to work with your output, I saw that maybe there is a misunderstanding:

can you once again provide the output of

In nodejs - NOT using the systeminformation library but using the build in `os` function:

```
console.log(os.networkInterfaces())
```

and on Windows:

```
netstat -r
```

but not as a screenshot ... better as the real output (in github you should be able e.g. to paste the formatted outout after three backticks (and a newline) followed again by three backticks)

**Comment by juancampuzano** [comment]
**os.networkInterfaces()** output:
`Interfaces  {
  'Conexión de área local': [
    {
      address: '192.168.0.46',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: 'd8:cb:8a:25:20:cb',
      internal: false,
      cidr: '192.168.0.46/24'
    }
  ],
  'Loopback Pseudo-Interface 1': [
    {
      address: '::1',
      netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '::1/128',
      scopeid: 0
    },
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 'IPv4',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    }
  ]
}`

**netstat -r** output:

`===========================================================================
ILista de interfaces
 11...d8 cb 8a 25 20 cb ......Intel(R) Ethernet Connection I217-LM
  1...........................Software Loopback Interface 1
 12...00 00 00 00 00 00 00 e0 Adaptador ISATAP de Microsoft
===========================================================================

IPv4 Tabla de enrutamiento
===========================================================================
Rutas activas:
Destino de red        M scara de red   Puerta de enlace   Interfaz  M‚trica
          0.0.0.0          0.0.0.0      192.168.0.1     192.168.0.46     10
        127.0.0.0        255.0.0.0      En v¡nculo         127.0.0.1    306
        127.0.0.1  255.255.255.255      En v¡nculo         127.0.0.1    306
  127.255.255.255  255.255.255.255      En v¡nculo         127.0.0.1    306
      192.168.0.0    255.255.255.0      En v¡nculo      192.168.0.46    266
     192.168.0.46  255.255.255.255      En v¡nculo      192.168.0.46    266
    192.168.0.255  255.255.255.255      En v¡nculo      192.168.0.46    266
        224.0.0.0        240.0.0.0      En v¡nculo         127.0.0.1    306
        224.0.0.0        240.0.0.0      En v¡nculo      192.168.0.46    266
  255.255.255.255  255.255.255.255      En v¡nculo         127.0.0.1    306
  255.255.255.255  255.255.255.255      En v¡nculo      192.168.0.46    266
===========================================================================
Rutas persistentes:
  Ninguno

IPv6 Tabla de enrutamiento
===========================================================================
Rutas activas:
 Cuando destino de red m‚trica      Puerta de enlace
  1    306 ::1/128                  En v¡nculo
  1    306 ff00::/8                 En v¡nculo
===========================================================================
Rutas persistentes:
  Ninguno
`

**Comment by sebhildebrandt** [comment]
@juancampuzano thank you!! Will test it here with mocking your data ...

**Comment by sebhildebrandt** [comment]
@juancampuzano so I testet it one more time with your data mocked ... and it worked fine ... so this is quite strange. To be able to reproduce it, can you go into your `./lib/network.js`file and place some console.logs like this (starting at line 62):

```
  ...
  ifacename = ifacename || ifacenameFirst || '';
  console.log('1: ' + ifacename);
  console.log('2: ' + ifacenameFirst);
  try {
    if (_windows) {
      // https://www.inetdaemon.com/tutorials/internet/ip/routing/default_route.shtml
      const cmd = 'netstat -r';
      const result = execSync(cmd);
      const lines = result.toString().split(os.EOL);
      console.log('3: ');
      console.log(lines);
      let defaultIp = '';
      lines.forEach(line => {
        line = line.replace(/\s+/g, ' ').trim();
        if (line.indexOf('0.0.0.0 0.0.0.0') > -1 && !(/[a-zA-Z]/.test(line))) {
           console.log('4: FOUND' + line); 
          const parts = line.split(' ');
          if (parts.length >= 5) {
            defaultIp = parts[parts.length - 2];
            console.log('5: ' + defaultIp);
          }
        }
      });
      if (defaultIp) {
        for (let dev in ifaces) {
          if ({}.hasOwnProperty.call(ifaces, dev)) {
            ifaces[dev].forEach(function (details) {
              if (details && details.address && details.address === defaultIp) {
                console.log('6: ' + dev);
                ifacename = dev;
              }
            });
          }
        }
      }
    }
   ...
```

Thank you in advance ...

**Comment by juancampuzano** [comment]
For this test the result was:
`1: Conexión de área local
2: Conexión de área local`

Remembering that my problem is getting **networkGatewayDefault();** I made some test and the result was: 
![resultado2](https://user-images.githubusercontent.com/52759609/73386799-7b0d7680-429d-11ea-92eb-820ec8ee254e.PNG)
![Resultado](https://user-images.githubusercontent.com/52759609/73386802-7c3ea380-429d-11ea-9504-a97b2b7a0f7a.PNG)

Check for the logic in Windows at the ` line 1415`

**Comment by sebhildebrandt** [comment]
@juancampuzano ... oh man, sorry!!! I was on the wrong track ... I mixed it up with `getDefaultInterface()`. Well, back to start. Thank you for your console.log-output in the right place. Will have a look at it.

**Comment by sebhildebrandt** [comment]
@juancampuzano so basically I was in the wrong section. One more thing what I would need is the following: in `Powershell` (just type `powershell` in the command line...):

Can you provide the output of 
```
Get-CimInstance -ClassName Win32_IP4RouteTable
```

and 

```
Get-CimInstance -ClassName Win32_IP4RouteTable | Where-Object { $_.Destination -eq '0.0.0.0' -and $_.Mask -eq '0.0.0.0' }
```

Thank you one more time for your patience!

**Comment by juancampuzano** [comment]
The result was: _**The term is not recognized as the name of a cmdlet**_ 

![Resultado](https://user-images.githubusercontent.com/52759609/73542538-e886e780-4402-11ea-98e3-ada49db13f19.PNG)

**Comment by sebhildebrandt** [comment]
@juancampuzano Ok, that explains it. The Powershell command `Get-CimInstance` Require PowerShell version 3 and later ... so this particular part will not work on your system. Never the less, the first one should give an answer. As we here have language specific output, I need to think how to solve it. Please give me a litte time to find a solution.

**Comment by sebhildebrandt** [comment]
@juancampuzano Ok, I guess I have an idea ;-) Will implement it tonight but I can test it not before Sunday.

**Comment by sebhildebrandt** [comment]
@juancampuzano so I just published a new version 4.21.1. Maybe you can test it ... hope that this solves the problem.

**Comment by juancampuzano** [comment]
Now It is working fine :100: 

Thank you very much for your collaboration and quick response.

**Comment by sebhildebrandt** [comment]
@juancampuzano thank you for your help testing it and providing detailed information. And once again sorry for the long journey due to my misinterpretation of the issue ;-)
