### ISSUE TITLE
spawn ENOMEM on filesystem.js

### ISSUE THREAD

**Issue by SwordJason** [sebhildebrandt/systeminformation#327]
**Describe the bug**
Start a server without swap configured. When start with nodejs. It will output the following error.

**To Reproduce**
1. Install a systeminformation.
2. Start a scheduleJob to output following system information 

```
const si = require('systeminformation');

const freeMem = (os.freemem() / 1024 / 1024).toFixed(2);
const totalMem = (os.totalmem() / 1024 / 1024).toFixed(2);
const appMemoryUsage = `${(process.memoryUsage().rss / 1024 / 1024).toFixed(2)} Mb`;
console.log(`
                ---------------------Server--------------------
                CPU Loadavg(5,10,15 mins):${os.loadavg()};
                Memory: ${freeMem} ${totalMem} ${appMemoryUsage};
                -------------------------------------------`
);
si.fsSize((disks) => {
     let diskInfo = '';
    disks.forEach((disk) => {
         diskInfo += `
                ${disk.fs}: ${disk.use.toFixed(2)}% used:${(disk.used / 1073741824).toFixed(2)}Gb,
                total:${(disk.size / 1073741824).toFixed(2)}Gb;`;
    });
    console.log(`
                    -----------------Disk-------------------------
                    ${diskInfo}
                    -------------------------------------------`);
});

```

_filesystem.js:76:9_
```
      if (_linux || _freebsd || _openbsd || _netbsd || _darwin) {
        let cmd = '';
        if (_darwin) cmd = 'df -lkP | grep ^/';
        if (_linux) cmd = 'df -lkPTx squashfs | grep ^/';
        if (_freebsd || _openbsd || _netbsd) cmd = 'df -lkPT';
        exec(cmd, function (error, stdout) { //76:9

```

**Current Output**
ERROR: spawn ENOMEM
Error: spawn ENOMEM
at ChildProcess.spawn (internal/child_process.js:372:11)
at spawn (child_process.js:559:9)
at Object.execFile (child_process.js:224:15)
at exec (child_process.js:152:18)
at process.nextTick **(*/node_modules/systeminformation/lib/filesystem.js:76:9)**
at processTicksAndRejections (internal/process/next_tick.js:74:9)
at runNextTicks (internal/process/next_tick.js:51:3)
at processTimers (timers.js:268:7)'

**Expected behavior**
expect it will run without issue.

**Environment (please complete the following information):**
 - systeminformation package version: 4.19.2
 - OS: CentOS 7.6
 - Hardware AWS EC2 t3.small(2cpu 2GB) (**No Swap configured**)

**Comment by sebhildebrandt** [comment]
@SwordJason What exactly was the problem? Did you figured out, what caused the issue? was it related to systeminformation package??
