### ISSUE TITLE
macOS better memory bank value

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#328]
**Describe the bug**
Too much data is returned for the bank field on darwin.

**To Reproduce**
```js
await si.memLayout();
```

**Current Output**
```js
{
    size: 4294967296,
    bank: 'BANK 0/DIMM0:',
    type: 'DDR3',
    clockSpeed: 1067,
    formFactor: '',
    manufacturer: '0x04CD',
    partNum: '0x46412D38353030434C372D34474253510000',
    serialNum: '-',
    voltageConfigured: -1,
    voltageMin: -1,
    voltageMax: -1
}
```

**Expected behavior**
`Bank 0` or 0 should be returned.

**Environment (please complete the following information):**
 - systeminformation package version: latest
 - OS: macOS
 - Hardware: Macbook Pro 2010

**Additional context**
```
Memory:

    Memory Slots:

      ECC: Disabled
      Upgradeable Memory: Yes

        BANK 0/DIMM0:

          Size: 4 GB
          Type: DDR3
          Speed: 1067 MHz
          Status: OK
          Manufacturer: 0x04CD
          Part Number: 0x46412D38353030434C372D34474253510000
          Serial Number: -

        BANK 1/DIMM0:

          Size: 4 GB
          Type: DDR3
          Speed: 1067 MHz
          Status: OK
          Manufacturer: 0x04CD
          Part Number: 0x46412D38353030434C372D34474253510000
          Serial Number: -
```

**Comment by OmgImAlexis** [comment]
Or maybe split the field into an object and have both returned? Either way the trailing `:` should at least go.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis you are absolutely right! I will probably split it up and add an extra property ...

**Comment by sebhildebrandt** [comment]
@OmgImAlexis just released a new version 4.19.3

**Comment by sebhildebrandt** [comment]
@OmgImAlexis one question: as I see `0x04CD` as a manufacturer ID in your MacBook Pro, do you know the manufacturer? As it is hard to get a matching table, but found some indications that this could be `G-Skill` (I have this implemented at the moment in systeminformation). Can you confirm that?

**Comment by OmgImAlexis** [comment]
I can check. Shall we open an issue for things like this? I have a load of hardware here to test things on. Same goes for the people at my work and we use this library quite heavily.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis ... yes would make sense to open another issue if my mapping according to coding of macOS memory manufacturer IDs to manufacturer string is not correct.

**Comment by OmgImAlexis** [comment]
So looks like they are gskill. Completely forget I had upped the RAM in this machine.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis thank you. Fine, so systeminformation should already show the correct value, right?
