### ISSUE TITLE
Missing Validation in osInfo (Windows)

### ISSUE THREAD

**Issue by fxckdead** [sebhildebrandt/systeminformation#33]
I was trying your lib (btw, nice job) and in the `osInfo` function you missed a validation for Windows logo that throws:

```
C:\Users\Fxckdead\Desktop\testing\node_modules\systeminformation\lib\osinfo.js:43
  distro = distro.toLowerCase();
                 ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at getLogoFile (C:\Users\Fxckdead\Desktop\testing\node_modules\systeminformation\lib\osinfo.js:43:18)

```

In that line i can see:

```
// Get logo filename of OS distribution

function getLogoFile(distro) {
  distro = distro.toLowerCase(); // <-- THIS LINE 
```

For the windows version you don't send the distro param, so toLowerCase is not an string:

```
197    if (_windows) {
198        result.logofile = getLogoFile();
```

I can't send a pull request right now, but its an easy fix.

**Comment by sebhildebrandt** [comment]
Will provide an update next week. Thank you for your investigation!! 

Sebastian Hildebrandt

**Comment by sebhildebrandt** [comment]
Fixed. Sorry for the inconvenience ... once again, thank you for reporting.

**Comment by fxckdead** [comment]
No problem, and thanks u for this lib !
