### ISSUE TITLE
Add example column

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#332]
**Is your feature request related to a problem? Please describe.**
To easily know if there's an issue with the provided function it'd be nice to see an example of the expected output along side the comment, etc. columns.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis ... generally (as always) a good idea. I really appreciate your input! So I need to think how I can manage this without having to much information in the readme/docs tables ... any suggestion?

**Comment by OmgImAlexis** [comment]
I was thinking maybe just on the site? I noticed going to the docs there isn’t a huge difference between that and the readme. I was hoping that was where I’d find example and other info.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis Makes sense! Will add it to the site ... in the readme it would be to much ;-)

**Comment by sebhildebrandt** [comment]
@OmgImAlexis Started to add examples for the first functions ... will continuously add more examples.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis ... done for most of the functions. I will try continuously try improve it. If you have further comments, just feel free to send me your hints ... closing it for now.
