### ISSUE TITLE
Possible work-around for permission issues on Linux / Unix

### ISSUE THREAD

**Issue by CodeF0x** [sebhildebrandt/systeminformation#334]
**Is your feature request related to a problem? Please describe.**
Currently, some features like `memLayout` or `diskLayout` need admin rights to work properly under Linux systems (as said in #108 and #167). 

**Describe the solution you'd like**
There's a npm package called [sudo-prompt](https://www.npmjs.com/package/sudo-prompt) that allows to run shell commands like Node's `exec`, but with admin permissions. It then asks the user via a prompt to enter their sudo password. 

On my testing machine (Debian 8) it looks like this:
![sudo prompt](https://user-images.githubusercontent.com/33719652/73292857-18679c80-4203-11ea-8627-32fb7088c04b.jpg)
If the user cancels the prompt, the exec call simply fails, so there's no difference to the way it behaves now.

To implement sudo-prompt, you can do something like this:
```
const sudo = require('sudo-prompt');
const options = {
   name: 'ApplicationName'
};

// Basically just add "sudo" before every exec that has something to do with linux commands, 
// add "options" as parameter and leave the rest as it is
sudo.exec('command', options, callback(... ...
```

The reason I didn't submit a pull request yet is because I'm not sure if that's a proper solution or if a solution like that is even appreciated, as it introduces a dependency. I'm open to discuss this further.

**Describe alternatives you've considered**
Alternatively, if this approach is not helpful, I will consider to either drop Linux support of my application I'm currently building, or maintaining a custom fork of this library myself.

**Comment by sebhildebrandt** [comment]
@CodeF0x thank you for your comment. So the dependency is not the real problem here. It is more about introducing user interaction when calling some functions. This is - in most cases - unwanted, especially when code runs silent in background (monitoring apps, ...). So I think this will introduce much more problems then solving it ... hope you understand this. Closing this for now.

**Comment by CodeF0x** [comment]
Hello @sebhildebrandt! I totally understand your point here. Thanks for your feedback.
