### ISSUE TITLE
read system info from docker

### ISSUE THREAD

**Issue by golil** [sebhildebrandt/systeminformation#335]
hi 
i have node application run in docker container, i want access to host system information for check some system information like real network interfaces mac.but when use systeminformation, show docker network interfaces mac. how can i access to system information from docker ?

**Comment by sebhildebrandt** [comment]
@golil I think this is not possible directly from docker. One of the main concept of docker is, that you by default work in an isolated environment and have no access to the outer world (except, when you open ports, etc.) So the only way (that I see) to do this, would be to have a service on the host OS that you then call from your docker environment. Closing this for now.

**Comment by ahmadi3d** [comment]
@sebhildebrandt Hello, Considering the new updates and changes is this still not possible ? I need to know 
Ram, CPU, Disk, Running services of the host
Thank you!
