### ISSUE TITLE
Help: networkConnections in debian / ubuntu returns empty []

### ISSUE THREAD

**Issue by cekvenich** [sebhildebrandt/systeminformation#336]
The latest release, in fedora and osx works!
It returns my open local ports.

In ubuntu, also as root, returns []

Help?

**Comment by sebhildebrandt** [comment]
@cekvenich seems that Debian (and Ubuntu) now switched to `ss` instead of `netstat`. I will add code to handle both alternatives.

**Comment by sebhildebrandt** [comment]
@cekvenich should be fixed. Version 4.21.2 just published. Can you test it on your side?

**Comment by cekvenich** [comment]
Give me 24 hours, I will.

**Comment by cekvenich** [comment]
@sebhildebrandt  I tested new build on Ubuntu and I can confirm that it is fixed.

Thank you for rapid response. Cheers, Vic
