### ISSUE TITLE
GPU info

### ISSUE THREAD

**Issue by VolodymyrKalynii** [sebhildebrandt/systeminformation#338]
Hello! Please tell us if you plan to display information about the gpu.
I saw that there was already a request a few years ago, but maybe something has changed since then.

**Comment by sebhildebrandt** [comment]
@VolodymyrKalynii ... currently I do not see a way to get reliable gpu information constantly across hardware and os platforms. If anyone has an idea, please let me know, then I can try to find a solution. Closing it for now.
