### ISSUE TITLE
Rpi 4 - memLayout returns empty array

### ISSUE THREAD

**Issue by jeth318** [sebhildebrandt/systeminformation#339]
First things first: **AWSOME** lib.

**Describe the bug**
When calling si.memLayout() on my Raspberry Pi 4, I get an empty array as the return value.
On macOs it works as expected, returning info about the installed memory banks.
According to the docs, this feature should be available on Linux systems. That's why I submit this report.

**To Reproduce**
1. Call si.memLayout()
2. `si.memLayout().then(res => console.log(res));`
3. run the code
4. See output/error '....'

**Current Output**
[]

**Expected behavior**
Should see information about installed memory modules:
e.g response:
`[
   {
      "size":"***",
      "bank":"BANK 0",
      "type":"LPDDR3",
      "clockSpeed":2133,
      "formFactor":"",
      "manufacturer":"Micron Technology Inc.",
      "partNum":"***",
      "serialNum":"-",
      "voltageConfigured":-1,
      "voltageMin":-1,
      "voltageMax":-1
   },
   {
      "size":8589934592,
      "bank":"BANK 1",
      "type":"LPDDR3",
      "clockSpeed":2133,
      "formFactor":"",
      "manufacturer":"Micron Technology Inc.",
      "partNum":"***",
      "serialNum":"-",
      "voltageConfigured":-1,
      "voltageMin":-1,
      "voltageMax":-1
   }
]`

**Environment (please complete the following information):**
 - OS:
_Rasbian Buster
Kernel: 4.19.97-v7l+
Release 10_

 - Hardware:
_BCM2835 - Pi 4 Model B
c03111 - Rev. 1.1_

**Comment by sebhildebrandt** [comment]
@jeth318 let me check it tomorrow. If this is reproducible also on my machines I will find a quick solution for this. If not, I probably will come back to you for further information. Hope this is ok for you.

**Comment by sebhildebrandt** [comment]
@jeth318 ok, as dmidecode does not work on Raspberries, I am considering another method. Please give me one or two days ... will figure it out ;-)

**Comment by jeth318** [comment]
Great! Let me know if there are any more examples you need.

**Comment by sebhildebrandt** [comment]
@jeth318 so I just released a new version 4.22.1. Maybe you can give it a try and post results here.

**Comment by jeth318** [comment]
Great!! I’ll try it out soon.

**Comment by jeth318** [comment]
@sebhildebrandt It works like a charm. Thanks for the quick patch!

**Comment by sebhildebrandt** [comment]
@jeth318 can you provide a sample output, just to see if we are getting the expected values ;-)
Thank you in advance.

**Comment by jeth318** [comment]
Here is a sample output when calling memLayout().
`[
  {
    size: 3908665344,
    bank: '',
    type: 'LPDDR4',
    clockSpeed: 3200,
    formFactor: 'SoC',
    partNum: '',
    serialNum: '',
    voltageConfigured: -1,
    voltageMin: -1,
    voltageMax: -1
  }
]`

**Comment by sebhildebrandt** [comment]
@jeth318 So as voltage was missing, I made a fix for that. Version 4.22.2 just published.

**Comment by sebhildebrandt** [comment]
@jeth318 ... the rest is not really determinable as there is no bank, no serial and part number for the RAM.

**Comment by jeth318** [comment]
That's perfectly fine! Really nice. Thanks again for fixing the support.
