### ISSUE TITLE
Change in content of si.processes?

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#34]
Hi Sebastian,

It looks to me that the _list_ array within the data returned by si.processes() no longer contains a proper _command_ property. In fact, it looks to me as if the _command_ property might contain the userid under which the process is running.

I'm fairly certain that I used to use the _command_ property to help me identify processes of interest, e.g., various startup flags, etc.

I am using 3.17.0 version of si. 

Can you confirm my findings?

Thanks.

-Paul

**Comment by sebhildebrandt** [comment]
Paul, you where right! Just fixed and tested it. If you discover any further problems, do not hesitate to contact me. Version 3.17.1 is online now (git & npm)

**Comment by paul-bell** [comment]
Thank you, Sebastian.

I will install 3.17.1 directly.

Cordially,

Paul

**Comment by paul-bell** [comment]
Hi Sebastian,

I am definitely seeing the former 'command' data; thanks.

But I am also seeing what might be diagnostic output on the console. I am reasonably certain that my code isn't writing it. Does this look familiar:

```
[ { from: 0, to: 10, cap: '       PID' },
  { from: 11, to: 17, cap: '  %CPU' },
  { from: 18, to: 24, cap: '  %MEM' },
  { from: 25, to: 30, cap: '  PRI' },
  { from: 31, to: 41, cap: '       VSZ' },
  { from: 42, to: 52, cap: '       RSS' },
  { from: 53, to: 58, cap: '   NI' },
  { from: 59, to: 79, cap: '             STARTED' },
  { from: 80, to: 100, cap: 'S                   ' },
  { from: 101, to: 121, cap: 'TT                  ' },
  { from: 122, to: 142, cap: 'USER                ' },
  { from: 143, to: 1000, cap: 'COMMAND' } ]
```
If so, might you be able to remove it?

Please let me know; thanks.

-Paul

**Comment by sebhildebrandt** [comment]
Sorry!! Yes. Will remove it tomorrow. 

Sebastian Hildebrandt

**Comment by paul-bell** [comment]
No problem; thanks again for fixing this!

-Paul

**Comment by sebhildebrandt** [comment]
FIxed. V 3.17.2 published
