### ISSUE TITLE
Get all avaiable values to object by one method/function?

### ISSUE THREAD

**Issue by Mlocik97-issues** [sebhildebrandt/systeminformation#340]
Now when we use system information to get all data (CPU, RAM, Disk, GPU, etc...) we need to call a lot of methods/functions, so I would like to have functions getAllHW() and getAllUsage() to get all data about HardWare and Usage() which would return object with these data. So we can easilly use app.get('/hardware', si.getAllHW());

and in client-side let data = fetch('/hardware');
so I can easilly use interpolation/binding in view, to parse informations, like {{data.cpu.usage}} or {{data.ram.avaiable}}

**Comment by sebhildebrandt** [comment]
@Mlocik97-issues I plan to build a function where you can specify (json object) what you would like to get back. This would be more flexible and will allow to get exactly those values back, that you need with one single function call. Hope this is ok for you.

**Comment by Mlocik97-issues** [comment]
yes, it would be really great.

**Comment by adrifcastr** [comment]
I second this, awaiting 5 methods takes about 5 secs which is unfortunate.

**Comment by sebhildebrandt** [comment]
@Mlocik97-issues I just released a new version 4.25.0 which includes a possibility to provide a value object to a `get()` function which results in an object with just the wanted properties. See example in the documentation https://systeminformation.io/general.html

**Comment by Mlocik97-issues** [comment]
thanks so much
