### ISSUE TITLE
CPU spikes when calling osinfo.versions(). Can we add a parameter for options?

### ISSUE THREAD

**Issue by emircokdogan** [sebhildebrandt/systeminformation#341]
**Is your feature request related to a problem? Please describe.**
First of all. Great package. Thumbs up! 👍 Not a huge problem but worrying that in the long run when calling them repeatedly. I've been working on server monitoring tool for myself. I'd like to detect upgrades/downgrades of the installed packages. When calling 'versions' function, CPU spiked up to %100 on the machines I've tried. I'll using it periodically, so it will be clearly a problem for me.
![image](https://user-images.githubusercontent.com/5866487/75187305-dd517e00-575a-11ea-9baf-c84df7d730f2.png)

**Describe the solution you'd like**
osinfo.versions() may expect a parameter about which package versions are being asked.

For example:
```
let packages = { 'python': '', 'node': '', 'npm': '' };
osinfo.versions(callback, packages);
```
OR
```
let packages = ['python', 'node', 'npm'];
osinfo.versions(callback, packages);
```
OR
```
osinfo.versions(callback, 'python', 'node', 'npm');
```

**Describe alternatives you've considered**
I'm currently working on the solution on my fork.
I'm trying to figure out a way to implement it without a huge change and too many conditions. The function already 350 lines long. I don't want to complicate it any further. I'm stuck. Can you help me out? :) Any ideas?

Thanks.

**Comment by sebhildebrandt** [comment]
@emircokdogan I am currently working on a function where you can specify exactly what data you want. This will not only include `versions` but all functions. So basically you call the function (like the `getAll()` but with a json as a parameter which specifies exactly which details you want to get. 

As this is a more complex approach, I am thinking fo refactoring versions to use a parameter as suggested. Will inform you, as soon as this is ready.

**Comment by sebhildebrandt** [comment]
@emircokdogan So I now added an optional parameter to the `versions()` function:

```
const si = require('systeminformation');
si.versions('npm, php, postgresql').then(data => console.log(data));
```

would then return only

```
{
  npm: '6.13.6',
  php: '7.3.11',
  postgresql: '12.1'
}
```

This param is optional and can be comma or just space separated. Names of the apps/libs need to be the same as in the full result (see docs). Hope that helps! Version 4.23.0 just released.
