### ISSUE TITLE
Wrong vram GPU

### ISSUE THREAD

**Issue by mrTorb** [sebhildebrandt/systeminformation#344]
Hi
I get the wrong VRAM from my GPUs.

 graphics: [
    {
      vendor: 'NVIDIA',
      model: 'NVIDIA GeForce GTX 1080 Ti',
      bus: 'PCI',
      vram: 4095,
      vramDynamic: true
    },
    {
      vendor: 'NVIDIA',
      model: 'NVIDIA GeForce GTX 1080 Ti',
      bus: 'PCI',
      vram: 4095,
      vramDynamic: true
    }
  ],

I probably should be  vram: 11 264 ‬or close to that

I'm on Windows Version	10.0.18362 Build 18362

I use "systeminformation": "^4.22.3"

**Comment by mrTorb** [comment]
After some research I found that it seems that vmic cant provide that information correctly.
Maybe dxdiag /t would work instead instead of using vmic?

**Comment by sebhildebrandt** [comment]
@mrTorb I did some research, `dxdiag /t` is not really an option because it needs to create a file on the target system. I would like to avoid that because that could cause other issues. Currently I do not see an option to detect this correctly from within node.js. Closing it for now.

**Comment by sebhildebrandt** [comment]
@mrTorb I introduced a workaround that could also work on your side to determine the VRAM more accurate. Version 5.7.1 should report better results. Maybe you have time to test it on your machine.
