### ISSUE TITLE
Typescript definitions : string => number

### ISSUE THREAD

**Issue by emmkimme** [sebhildebrandt/systeminformation#345]
**Describe the bug**
Using version "4.22.3"
Currently, some ts definitions related to numeric information are typed as string.
Could it be possible to change them

```
interface CpuData {
    speed: string; => number
    speedmin: string; => number
    speedmax: string; => number
}

interface CpuCurrentSpeedData {
    min: string; => number
    max: string; => number
    avg: string; => number
}
```

Thanks

**Comment by sebhildebrandt** [comment]
@emmkimme Thank you for your discovery. I guess für cpuData the typings are (unfortunately) correct. I need to change the results to be numbers (which would be a breaking change) but currently they are strings. This will change in version 5. For `CpuCurrentSpeedData`you are absolutely right. I changed it and released a new version 4.22.4.
