### ISSUE TITLE
getLinuxDHCPNics not looking in included files in /etc/network/interfaces

### ISSUE THREAD

**Issue by SibertDekimo** [sebhildebrandt/systeminformation#347]
**Issue**
Not all interfaces correct DHCP correctly when requesting all network interfaces using networkInterfaces(). This happens when the interface is included in the /etc/network/interfaces file using `source file`. 

**Solution**
I've written a quick solution for this, that suits my use case so it's definitely not guaranteed to be the best solution or any good for that matter, but I'll include it in this post as a courtesy :)

I have moved the code to find all interfaces to a seperate, recursive function and I've adapted the grep command to include lines that contain the 'source' keyword. If it finds a source line, it then processes the file the same way it does /etc/network/interfaces.

```
function checkLinuxDCHPInterfaces(file) {
  let result = [];
  let cmd = `cat ${file} 2> /dev/null | grep 'iface\\|source'`;
  const lines = execSync(cmd, { maxBuffer: 1024 * 20000}).toString().split('\n');
  
  lines.forEach(line => {
    const parts = line.replace(/\s+/g, ' ').trim().split(' ');
      if (parts.length >=4) {
        if (line.toLowerCase().indexOf(' inet ') >= 0 && line.toLowerCase().indexOf('dhcp') >= 0) {
          result.push(parts[1]);
        }
      }

      if(line.toLowerCase().includes('source'))
      {
		let file = line.split(' ')[1];
        result = result.concat(checkLinuxDCHPInterfaces(file));
      }
  });

  return result;
}

function getLinuxDHCPNics() {
  // alternate methods getting interfaces using DHCP
  let cmd = 'ip a 2> /dev/null';
  let result = [];
  try {
    const lines = execSync(cmd, { maxBuffer: 1024 * 20000 }).toString().split('\n');
    const nsections = splitSectionsNics(lines);
    result = (parseLinuxDHCPNics(nsections));
  } catch (e) {
    util.noop();
  }
  try {
    result = checkLinuxDCHPInterfaces('/etc/network/interfaces');
  } catch (e) {
    util.noop();
  }
  return result;
}
```

I hope this can be useful for an actual solution.

**Comment by sebhildebrandt** [comment]
@SibertDekimo this is awesome! I just released a new version with this fix.
