### ISSUE TITLE
fsStats not working on Ubuntu OpenVZ

### ISSUE THREAD

**Issue by Marcel26990** [sebhildebrandt/systeminformation#350]
**Describe the bug**

**To Reproduce**
1. used function 'fsStats'
2. code snippet
```
setInterval(() => { si.fsStats().then(d => console.log(d)) }, 1000);
```
3. start app / code
4. See output/error:

**Current Output**
```
{ rx: 0, wx: 0, tx: 0, rx_sec: -1, wx_sec: -1, tx_sec: -1, ms: 0 }
{ rx: 0, wx: 0, tx: 0, rx_sec: -1, wx_sec: -1, tx_sec: -1, ms: 0 }
{ rx: 0, wx: 0, tx: 0, rx_sec: -1, wx_sec: -1, tx_sec: -1, ms: 0 }
{ rx: 0, wx: 0, tx: 0, rx_sec: -1, wx_sec: -1, tx_sec: -1, ms: 0 }
```
**Expected behavior**
Values for rx, wx, tx, rx_sec, wx_sec, tx_sec, ms

**Environment (please complete the following information):**
 - systeminformation package version: 4.22.7
 - OS: Ubuntu 18.04.04 LTS
 - Hardware VPS with OpenVZ

**Additional context**

**Comment by sebhildebrandt** [comment]
@Marcel26990 

First, I would need the output of 

```
lsblk 2>/dev/null | grep /
```

then the following would be helpful:

```
cat /proc/diskstats
```

**Comment by Marcel26990** [comment]
@sebhildebrandt 
`lsblk 2>/dev/null | grep /`:
```
└─ploop30758p1 182:492129  0  202G  0 part /
```
`cat /proc/diskstats`:
```
cat: /proc/diskstats: : File or directory not found
```

**Comment by sebhildebrandt** [comment]
@Marcel26990 I read some articles now. So within OpenVZ not all counters are present. It doesn't expose all counters (like /proc/diskstats) to its containers. So therefore we cannot measure disk IO properly here.

**Comment by Marcel26990** [comment]
@sebhildebrandt `iotop` seems to be working with OpenVZ

**Comment by Marcel26990** [comment]
`sudo iotop -botqqqk --iter=60` 
```
17:48:25 31598 be/4 root        7.94 K/s    0.00 K/s  0.00 %  0.06 % node .
17:48:40 31608 be/4 root        7.92 K/s    0.00 K/s  0.00 %  0.03 % node .
```

**Comment by Marcel26990** [comment]
https://www.binarytides.com/monitor-disk-io-iotop-cron/

**Comment by sebhildebrandt** [comment]
@Marcel26990 not sure if iotop is always installed ... need to make further investigations
