### ISSUE TITLE
Monitor for Network State Changes

### ISSUE THREAD

**Issue by tonesto7** [sebhildebrandt/systeminformation#351]
**Is your feature request related to a problem? Please describe.**
I would love to have the ability to monitor network connections for IP Change, Link Status, Wireless Network connect/disconnect events.
Right now I only need this for windows.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I can't find any other node packages that accomplish this task.

**Additional context**

**Comment by sebhildebrandt** [comment]
@tonesto7 With the new `observe()` function in systeminformation, you probably now can implement this very easily. See example here: https://systeminformation.io/statsfunctions.html, Chapter **Observe System Parameters**
