### ISSUE TITLE
Where to get the Mouse / Keyboard Device?

### ISSUE THREAD

**Issue by fgroupindonesia** [sebhildebrandt/systeminformation#352]
i'm still looking for the mouse device info but found nothing here.
Is there any way to get it through this systeminformation project?

Thanks in advance!

**Comment by sebhildebrandt** [comment]
@fgroupindonesia thinking of adding a section to detect pointing and keyboard devices. Which platform are you using?

**Comment by fgroupindonesia** [comment]
currently i'm in windows 7,8, 10 and also linux (ubuntu).
Perhaps do you have this enhancement to be the nearest plan?

**Comment by sebhildebrandt** [comment]
@fgroupindonesia thank you. And yes, I am planning to release a first version next week. Will be great, if you can test it on different windows versions (as I currently only have Win 10 in home office). Regards

**Comment by fgroupindonesia** [comment]
ok goood.... that's good!

is it now availablefor the documentation as well?

**Comment by fgroupindonesia** [comment]
any updates so far?

**Comment by sebhildebrandt** [comment]
@fgroupindonesia sorry for the delay. Was a quite intense year ... I started to work on it but never finished. Hope to make some progress till end if the year.

**Comment by sebhildebrandt** [comment]
@fgroupindonesia Version 5.0 just released. Here you have several new sections like USB and Bluetooth which then report back connected devices like Mouse and Keyboard.

Be aware: Version 5 is NOT fully backwards compatible to version 5 ... see https://systeminformation.io/changes.html to get an overview over all breaking changes.
