### ISSUE TITLE
si.networkStats() doesn't return values for rx/tx when running from Windows Server 2012

### ISSUE THREAD

**Issue by kyleconnors** [sebhildebrandt/systeminformation#353]
**Running on Windows Server 2012 .
Node Version: 12.13.0
systeminformation version: 4.23.1**

**Code:**
    _si.networkStats()
    .then(data => {
        console.log(data)
    })
    .catch(error => console.error(error));_

**Returns:**
[{"iface":"ethernet 2","operstate":"unknown","rx_bytes":0,"rx_dropped":0,"rx_errors":0,"tx_bytes":0,"tx_dropped":0,"tx_errors":0,"rx_sec":-1,"tx_sec":-1,"ms":0}]

Expected: some values greater than 0 for rx_bytes, tx_bytes, rx_sec, tx_sec

**Comment by sebhildebrandt** [comment]
@kyleconnors can you provide some additional information?

1. As `networkStats()` without specifying a network interface provides network stats for the default interface, can you please post the output of 

```
const si = require('systeminformation');
si.networkInterfaceDefault().then(data => console.log(data));
```

Is this the interface you would like to track?

2. to get proper `rx_sec?, ... values you need to do this:

```
setInterval(function() {
    si.networkStats().then(data => {
        console.log(data);
    })
}, 1000)
```

see also here https://systeminformation.io/network.html for an explanation.

3. can you also provide the output of:

```
wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,BytesReceivedPersec,BytesSentPersec,BytesTotalPersec,PacketsOutboundDiscarded,PacketsOutboundErrors,PacketsReceivedDiscarded,PacketsReceivedErrors /value
```

**Comment by kyleconnors** [comment]
Use Case 1 & 2 code:

`var si = require('systeminformation');

const express = require('express');
const app = express();

si.networkInterfaceDefault()
.then(data => {
	console.log("use case 1 output:")
	console.log(data)
});


setInterval(function() {
    si.networkStats().then(data => {	
		console.log("use case 1 output:")
        console.log(data);
    })
}, 1000);`

Use case 1 & 2 output:

D:\kylec_DoNotDeleteMe\jam-resource-monitor>node testing.js
use case 1 output:
Ethernet 2
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 1 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
^C

Use case 3 output:

Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. All rights reserved.

C:\Users\KConnor>wmic path Win32_PerfRawData_Tcpip_NetworkInterface Get name,Byt
esReceivedPersec,BytesSentPersec,BytesTotalPersec,PacketsOutboundDiscarded,Packe
tsOutboundErrors,PacketsReceivedDiscarded,PacketsReceivedErrors /value


BytesReceivedPersec=1289292298
BytesSentPersec=2612089497
BytesTotalPersec=3901381795
Name=Microsoft Hyper-V Network Adapter
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=isatap.{65AB2106-26D0-4ED4-9968-0B32A0EEE0F7}
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0


BytesReceivedPersec=0
BytesSentPersec=0
BytesTotalPersec=0
Name=Local Area Connection* 12
PacketsOutboundDiscarded=0
PacketsOutboundErrors=0
PacketsReceivedDiscarded=0
PacketsReceivedErrors=0

**Comment by kyleconnors** [comment]
Sorry, refer to this for use case 1 & 2 output:

Code:
`var si = require('systeminformation');

const express = require('express');
const app = express();

si.networkInterfaceDefault()
.then(data => {
	console.log("use case 1 output:")
	console.log(data)
});


setInterval(function() {
    si.networkStats().then(data => {	
		console.log("use case 2 output:")
        console.log(data);
    })
}, 1000);`

D:\kylec_DoNotDeleteMe\jam-resource-monitor>node testing.js
use case 1 output:
Ethernet 2
use case 2 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 2 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 2 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
use case 2 output:
[ { iface: 'ethernet 2',
    operstate: 'unknown',
    rx_bytes: 0,
    rx_dropped: 0,
    rx_errors: 0,
    tx_bytes: 0,
    tx_dropped: 0,
    tx_errors: 0,
    rx_sec: -1,
    tx_sec: -1,
    ms: 0 } ]
^C
D:\kylec_DoNotDeleteMe\jam-resource-monitor>

**Comment by sebhildebrandt** [comment]
@kyleconnors so then the default network adapter (Ethernet 2) really seems to have no traffic, right ... Windows shows sometimes strange network names ... So can you try it with 

```
setInterval(function() {
    si.networkStats('Microsoft Hyper-V Network Adapter').then(data => {
        console.log(data);
    })
}, 1000)
```

to get data from the right interface?

**Comment by kyleconnors** [comment]
That's working, thank you.
