### ISSUE TITLE
0 speed reported for Ryzen 5 2600X CPU

### ISSUE THREAD

**Issue by katrevich** [sebhildebrandt/systeminformation#356]
![image (1)](https://user-images.githubusercontent.com/1773894/78787379-8fab7080-79aa-11ea-90a1-64c32073433b.png)

Version: 4.23.1

**Comment by sebhildebrandt** [comment]
@katrevich ... which OS (and version) are you using?

**Comment by katrevich** [comment]
Oops, sorry :) 
It's Windows 10 (10.0.18362)

**Comment by sebhildebrandt** [comment]
@katrevich just released a new version 4.23.2 ... can you test it on your side?

**Comment by sebhildebrandt** [comment]
@katrevich did you had time to test the new version 4.23.2?

**Comment by sebhildebrandt** [comment]
@katrevich closing it for now. Please be sure to test this new version and please give some feedback here.
