### ISSUE TITLE
si.services(cb) not showing  systemctl services

### ISSUE THREAD

**Issue by GuilhermeDaniluski** [sebhildebrandt/systeminformation#358]
**Describe the bug**

I have severals custom systemd services running
When i run si.services('my-custom-service') i don't get any info from the service.

It seens to be only working with initd.

**Environment**
 - OS: Ubuntu Server 18.04 LTS
- Arch: Arm64
 - Hardware: Raspberry Pi 3 Model B

Thank you for this amazing work.

**Comment by sebhildebrandt** [comment]
@GuilhermeDaniluski thank you for your discovery. Need to check it ... will do this on Sunday.

**Comment by sebhildebrandt** [comment]
@GuilhermeDaniluski can you see your service in the linux process list? Can you try to run 

```
ps -axo pcpu,pmem,pid,command
```

and have a look if you see your service there? Maybe the name of the service is a little bit different?? If you see your service here with a different name (normally it should be the command, how you started your service) ... can you then test with systeminformation with THIS name.

E.g., I have a service `mmon` which I started like this: 

```
node /usr/bin/mmon
```

and then I test it like this:

```
const si = require('systeminformation');
si.services('avahi-daemon, mmon, postgres').then(data => console.log(data));
```

... which then results in

```
[
  {
    name: 'avahi-daemon',
    running: true,
    startmode: '',
    pids: [ 314, 327 ],
    pcpu: 0.0015857007846047481,
    pmem: 0
  },
  {
    name: 'mmon',
    running: true,
    startmode: '',
    pids: [ 1025 ],
    pcpu: 6.88405673003127,
    pmem: 0.9
  },
  {
    name: 'postgres',
    running: false,
    startmode: '',
    pids: [],
    pcpu: 0,
    pmem: 0
  }
]
```

(tested on raspberry 4, Raspbian GNU/Linux)

**Comment by GuilhermeDaniluski** [comment]
Oooh i am really glad for your help, it worked!

My custom service runs a bash file that runs a node script.

So with si.services i can get information both of the execution of the bash file(send_mongo_to_remote.sh) or of node script(index.js), simply by passing the name of the file as below.

![image](https://user-images.githubusercontent.com/39890571/79749153-159db480-82e5-11ea-8301-c8e98bba838a.png)

```js
const si = require("systeminformation");


si.services('send_mongo_to_remote.sh').then(response =>{
        console.log(response)
})
```

Or

```js
const si = require("systeminformation");


si.services('index.js').then(response =>{
        console.log(response)
})
```

I am really glad for your help and really glad for this amazing work.

Thank you
