### ISSUE TITLE
cpuTemperature not returning anything on OSX or Windows

### ISSUE THREAD

**Issue by SaintGrey** [sebhildebrandt/systeminformation#36]
Hi Sebastian,

First off thanks for putting this package together, I have enjoyed working with it the last couple of days.

Unfortunately, I have noticed that cpuTemperature is not returning anything. I have tested on OSX and Windows 10 and have confirmed with other system apps that both devices have a temp monitor running and reporting.

Cheers,

**Comment by sebhildebrandt** [comment]
Hi,

thank you for reporting this issue. On OS X I do see a temperature here. So what OSX Version and what machine are you using? On Windows I just started with implementing some functions that definitely need to be tested much more in detail ... so I will investigate why there is no result for temperature. Will get back to you on weekend.

**Comment by SaintGrey** [comment]
Thanks mate,

No hurry I am not building anything important.

The Mac I was using is a mid 2012 MacBook Pro running el capitan

Cheers

**Comment by SaintGrey** [comment]
I have done a little more testing today, please see below for my code and the output (this is an electron app):

**Code**
`window.onload = function() {

var si = require('systeminformation');
 

si.cpu(function(data) {
  console.log(data);
});

si.cpuCurrentspeed(function(data) {
  console.log(data);
});

si.cpuTemperature(function(data) {
  console.log(data);
});

}`


**Console output**
`index.js:14 Objectavg: 2.81max: 2.81min: 2.81__proto__: Object
index.js:10 Objectbrand: "Core™ i7-6600U"cores: 4manufacturer: "Intel®"speed: 2.6__proto__: Object`

As you can see "cpu" and "cpuCurrentspeed" are returning but "cpuTemperature" isn't.

I apologise in advance if it is user error, I have only started playing with nodejs this week.

Cheers,

**Comment by sebhildebrandt** [comment]
Two questions: 

- did you verified, that `npm install systeminformation` did not throw any error on OSX?
- on Windows: at the command line: does `wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CriticalTripPoint,CurrentTemperature /value`return any results? If yes, what do you get back?

**Comment by GoodGuyGroves** [comment]
Hi there, just saw this and figured I'd try help since I'm on Windows.

1) `npm install systeminformation` did not throw any errors for me
2) Running that command returned the following:
```
Node - Russ-PC
ERROR:
Description = Not Supported
```

**Comment by ochristensen** [comment]
I think this may be an Intel/AMD thing.  The wmic call returned properly (though only running in an elevated prompt) on my old i7-based system.  It now returns Not Supported for AMD Ryzen.

**Comment by LeoFisher657** [comment]
I have run the command myself, as well and it looks to not be an Intel/AMD problem. I was suffering the same issue of no temperature data

`
Node - LEO-LAPTOP
ERROR:
Description = Access denied
`

I did notice, however, that the descriptions are different.

The CPU is an Intel i3 4005U

**Comment by LeoFisher657** [comment]
Also, when I run the install command, I get these warnings:

![image](https://user-images.githubusercontent.com/17884586/27194074-2ac7f296-51f9-11e7-97d7-3583815f7d1c.png)

**Comment by sebhildebrandt** [comment]
So, I also made some tests. It seems not to be an Intel/AMD problem. This problem is related to access right. Running those commands with admin privileges work quite fine (if system and BIOS supports it). Concerning warnings on installation (optionalPrivileges) I will change the package a little bit to avoid also those warnings. I will close the for now but feel free to send me any notes / comments on that if you like!

**Comment by LeoFisher657** [comment]
Alright, I ran that command in an Admin CMD and it did work, but I'm still a bit unsure as to how to fix this in an actual implementation.

**Comment by LeoFisher657** [comment]
Ok, running `node .` from an admin cmd works

**Comment by omarabdelaz1z** [comment]
> I have run the command myself, as well and it looks to not be an Intel/AMD problem. I was suffering the same issue of no temperature data
> 
> `Node - [My Computer Name] Error: Description = Access Denied`
> 
> I did notice, however, that the descriptions are different.
> 
> The CPU is an Intel i3 4005U

Same as mine.
![image](https://user-images.githubusercontent.com/59033999/165552615-d5f57ff4-6cb4-4dce-9dd9-7a5e8260581f.png)
