### ISSUE TITLE
Cannot read property 'length' of undefined in getCpuCurrentSpeedSync

### ISSUE THREAD

**Issue by Apollon77** [sebhildebrandt/systeminformation#361]
Exception from user system catched by an integrated Sentry:

```
TypeError: Cannot read property 'length' of undefined
     at getCpuCurrentSpeedSync (C:\ioBroker\node_modules\iobroker.info\node_modules\systeminformation\lib\cpu.js:698:12)
     at process.nextTick (C:\ioBroker\node_modules\iobroker.info\node_modules\systeminformation\lib\cpu.js:728:20)
     at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by Apollon77** [comment]
The line is "if (cpus.length) {"

**Comment by sebhildebrandt** [comment]
@Apollon77 Will check it ... give me a little time ...

**Comment by sebhildebrandt** [comment]
@Apollon77 ... you are sure that this runs server side with `node`?? `cpus` is defined on line 692:

```
let cpus = os.cpus();
```

so this should not be undefined. Can you confirm this? Can you also provide within your app a console.log of `os.cpus()

**Comment by sebhildebrandt** [comment]
@Apollon77 ... I just had a look at the project where you are using `systeminformation` (https://github.com/iobroker-community-adapters/ioBroker.info/) ... which tells me, that this is used server side ... I still wonder, why `os.cpu()` is `undefined` in your case. Can you provide more information about your `node.js` version, OS, platform (VM or bare metal), hardware ... and provide the output of `os.cpus()`somewhere in your code ... need to see this output. Thank you in advance.

**Comment by Apollon77** [comment]
Yes it is Server side. I can not provide more logs. We just got this error via integrating sentry as automated error reporting. So in my eyes it would mean „do not trust that os.cpus always return a value“ ;-))

**Comment by Apollon77** [comment]
Some Infos to sentry: it is a service where we get exceptions from user computers. So it did. Not happen on any system we have access to. 

The topic is also the we can not try/catch it because it runs async. :-(

So sorry i can not provide more info then „it happened“

**Comment by sebhildebrandt** [comment]
@Apollon77 the thing is, that I cannot add code to all `node.js` objects  to test if they exist. In this case I can (and will add some code) but still: 

1. I need to now more about your environment: node.js version, OS, platform (VM or bare metal), hardware ... 
2. can you go into your code (or to be more specific - my systeminformation code) in 

```
C:\ioBroker\node_modules\iobroker.info\node_modules\systeminformation\lib\cpu.js
```

There in line 693 below the line `let cpus = os.cpus();`: 

Add a `console.log(cpus)`. (and maybe also `console.log(os)`) 

This is a node.js object which should not be undefined ... I am using this also in other parts in this file and I need to understand WHY this is undefined

Can you provide the output of this line?

Thank you in advance.

**Comment by Apollon77** [comment]
I completely understand the challenge. But it completely runs on my system. This error is from some user somewhere in the world and I can not contact him.

**Comment by Apollon77** [comment]
If you can not do more without the data just close the issue. Completely ok for me. I just wanted to report it. 

And yes it is very strange that nodejs returns an expected value here :-(

**Comment by sebhildebrandt** [comment]
@Apollon77 Ok, understand. Just released a version which should catch this issue but still I am not happy with that ;-) Closing this for now. Version 4.23.7 just released.

**Comment by Apollon77** [comment]
Thank you very much.

Should I report more such error if they come up also without having more details or not?

**Comment by sebhildebrandt** [comment]
@Apollon77 yes please. Maybe we detect some pattern here. Thank you in advance.

**Comment by Apollon77** [comment]
Ok, second one created :-)
