### ISSUE TITLE
TypeError: Cannot read property 'times' of undefined in cpus

### ISSUE THREAD

**Issue by Apollon77** [sebhildebrandt/systeminformation#363]
Hi, another Sentry report. I think this time maybe because of the other fix.

https://sentry.iobroker.net/share/issue/01a3eda32c874089bf5c3a2e04e8325f/

```
TypeError: Cannot read property 'times' of undefined
  File "d:\iobroker\node_modules\iobroker.info\node_modules\systeminformation\lib\cpu.js", line 1148, col 31, in null.<anonymous>
    const cpu = cpus[i].times;
  File "internal/process/task_queues.js", line 79, col 11, in processTicksAndRejections
```

In fact "if cpus is empty you set core count to 1 and try to access first array element of (empty) cpus ...
https://github.com/sebhildebrandt/systeminformation/blob/master/lib/cpu.js#L1148

**Comment by sebhildebrandt** [comment]
@Apollon77 will check it ...

**Comment by sebhildebrandt** [comment]
@Apollon77 Version 4.23.9 just released
