### ISSUE TITLE
Add netmask/subnet size

### ISSUE THREAD

**Issue by muffeeee** [sebhildebrandt/systeminformation#364]
**Is your feature request related to a problem? Please describe.**
We currently have the option to get a lot of network information about the client. However, we are not able to get the current network mask or subnet size (e.g. `255.255.255.0` or `/24)`

**Describe the solution you'd like**
IMO the best solution would be to add a `"netmask":` key and value for each of the interfaces in the `networkInterfaces()` feature.

**Comment by sebhildebrandt** [comment]
@muffeeee ... yes very clear. Will add it!

**Comment by sebhildebrandt** [comment]
@muffeeee just added subnet mask for ip4 and ip6. Version 4.24.0 just released.
