### ISSUE TITLE
Not able to access temperature information on Ubuntu

### ISSUE THREAD

**Issue by snuffysasa** [sebhildebrandt/systeminformation#365]
**Describe the bug**
Trying this package on Ubuntu 18 with node v8.10

```
const si = require('systeminformation')
    si.cpuTemperature().then(data => {
        console.log('CPU Information:');
        console.log('- manufucturer: ' + data.manufacturer);
        console.log('- brand: ' + data.brand);
        console.log('- speed: ' + data.speed);
        console.log('- cores: ' + data.cores);
        console.log('- physical cores: ' + data.physicalCores);
        console.log('...');
    }).catch(error => console.error(error))
```

**Current Output**
```
CPU Information:
- manufucturer: undefined
- brand: undefined
- speed: undefined
- cores: 
- physical cores: undefined
```

**Steps I've Tried**
- Running node as root
- sudo apt-get install lm-sensors

**Comment by sebhildebrandt** [comment]
Hi @snuffysasa ... this cannot work because you are using the returned object incorrectly. E.g. data.manufacturer is NOT a key of the temperature object:

This is how it should look like:

```
const si = require('systeminformation');

si.cpuTemperature().then(
    data => console.log(data)
);
```

And this would be the output:

```
{ main: 42, cores: [ 41,  42 ], max: 42 }
```

**Comment by snuffysasa** [comment]
@sebhildebrandt 

thank you for support.

However, I actually started with what you are suggesting here. And I get this output:

`{ main: -1, cores: [], max: -1 }`

The reason I used the method in my original question was because I copied it out of the readme for this package and wanted to match that

**Comment by sebhildebrandt** [comment]
@snuffysasa can you post (from the console - as text) the output of 

```
sensors
```

as well as 

```
cat /sys/class/thermal/thermal_zone0/temp'
```

and 

```
cat /opt/vc/bin/vcgencmd measure_temp
```

**Comment by snuffysasa** [comment]
@sebhildebrandt 

Okay great! Think we are hitting the core of the problem.

I do not have the folder /opt/vc  but I do /opt

I do not have the folder /sys/class/thermal/thermal_zone*  but I do /sys/class/thermal/

sensors output is:

`asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

k10temp-pci-00c3
Adapter: PCI adapter
Tdie:         +38.2°C  (high = +70.0°C)
Tctl:         +65.2°C  

k10temp-pci-00cb
Adapter: PCI adapter
Tdie:         +29.8°C  (high = +70.0°C)
Tctl:         +56.8°C  `

I looked up what Tdie and Tctl is... but confused where there are 2 K10temp readings... and why they say PCI adapter?


I am using a desktop PC that I built, AMD threadripper, ASUS motherboard? what else looking for?

Thank you much!

**Comment by sebhildebrandt** [comment]
@snuffysasa clear! Thank you. Yes and anyway I want to cover ad much cases as possible with this. So the last thing I would need: Output of 

```
cat /sys/class/hwmon/hwmon1/temp*
```

Thank you in advance! Will provide a solution for that this evening.

**Comment by snuffysasa** [comment]
```
31000
Tdie
70000
58000
Tctl
```

**Comment by snuffysasa** [comment]
I think that 70000 is a 'max' temp

**Comment by sebhildebrandt** [comment]
@snuffysasa thank you once again ... I can reproduce (and test) this also on one of my machines here. I will provide a solution tonight.

**Comment by sebhildebrandt** [comment]
@snuffysasa fixed. Version 4.23.10 just released. Can you test it on your side?

**Comment by snuffysasa** [comment]
@sebhildebrandt 

Thank you! So now, I have main temp. but cores is empty array, and max is -1.

However, this is good for what I'm working on, so I'm content.  However, let me know if you want me to test anything more.

Cheers

**Comment by sebhildebrandt** [comment]
@snuffysasa thank you for testing ... can you provide output of:

```
cat /sys/class/hwmon/hwmon1/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon1/temp*_i*
```

I will then mock your output an see what I did wrong ;-)

Thank you!

**Comment by sebhildebrandt** [comment]
@snuffysasa One more thing: can you do one more thing:

```
cd  /sys/class/hwmon/hwmon1/
ls -lsa
```

**Comment by snuffysasa** [comment]
@sebhildebrandt  Sure thing.

```
Tdie
Tctl
---
29500
56500
```

```
total 0
0 drwxr-xr-x 3 root root    0 May  1 05:05 .
0 drwxr-xr-x 3 root root    0 May  1 05:05 ..
0 lrwxrwxrwx 1 root root    0 May  1 05:05 device -> ../../../0000:00:19.3
0 -r--r--r-- 1 root root 4096 May  1 05:05 name
0 drwxr-xr-x 2 root root    0 May  1 12:48 power
0 lrwxrwxrwx 1 root root    0 May  1 05:05 subsystem -> ../../../../../class/hwmon
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp1_input
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp1_label
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp1_max
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp2_input
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp2_label
0 -rw-r--r-- 1 root root 4096 May  1 05:05 uevent
```

**Comment by snuffysasa** [comment]
Whats the difference between

cat /sys/class/hwmon/hwmon0/temp1_input
and
cat /sys/class/hwmon/hwmon1/temp1_input

**Comment by sebhildebrandt** [comment]
@snuffysasa so do you have both?? can you provide this? 

And also 

```
cd  /sys/class/hwmon/hwmon0/
ls -lsa
```

Your output is a little bit different to what I expected. After dome research I found out the difference between `Tdie` ans `Tctl` ...

TDIE is the temperature of the die and TCTRL is this value + 27 degrees offset for controlling the fans. In your case: which one was shown by systeminfo (the higher or the lower one)?

**Comment by snuffysasa** [comment]
Systeminfo is providing the lower one (tdie)

also... so I have 

hwmon0/temp1_input (tdie)
hwmon0/temp2_input (tctl)
hwmon1/temp1_input (tdie) again?
hwmon1/temp2_input (tctl) again?

here is the output of /hwmon0/  ls -lsa

```
total 0
0 drwxr-xr-x 3 root root    0 May  1 05:05 .
0 drwxr-xr-x 3 root root    0 May  1 05:05 ..
0 lrwxrwxrwx 1 root root    0 May  1 05:05 device -> ../../../0000:00:18.3
0 -r--r--r-- 1 root root 4096 May  1 05:05 name
0 drwxr-xr-x 2 root root    0 May  1 12:57 power
0 lrwxrwxrwx 1 root root    0 May  1 05:05 subsystem -> ../../../../../class/hwmon
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp1_input
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp1_label
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp1_max
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp2_input
0 -r--r--r-- 1 root root 4096 May  1 05:05 temp2_label
0 -rw-r--r-- 1 root root 4096 May  1 05:05 uevent

```

**Comment by sebhildebrandt** [comment]
@snuffysasa So are the values in hwmon0 and hwmon1 different?

```
cat /sys/class/hwmon/hwmon0/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
cat /sys/class/hwmon/hwmon1/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon1/temp*_i*
```

**Comment by snuffysasa** [comment]
Hard to say, I think a little different.

```
➜  hwmon0 cat /sys/class/hwmon/hwmon0/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
Tdie
Tctl
---
30625
57625
➜  hwmon0 cat /sys/class/hwmon/hwmon1/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
Tdie
Tctl
---
30125
57125
➜  hwmon0 cat /sys/class/hwmon/hwmon0/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
Tdie
Tctl
---
39250
66250
➜  hwmon0 cat /sys/class/hwmon/hwmon1/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
Tdie
Tctl
---
38125
65125
➜  hwmon0 cat /sys/class/hwmon/hwmon0/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
Tdie
Tctl
---
37000
64000
➜  hwmon0 cat /sys/class/hwmon/hwmon1/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
Tdie
Tctl
---
35625
62625
➜  hwmon0 cat /sys/class/hwmon/hwmon0/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon0/temp*_i*
Tdie
Tctl
---
34375
61375
```

**Comment by sebhildebrandt** [comment]
@snuffysasa OK, then one of them is OK.

I just released version 4.24.0. Can you test it once again and provide the output from systeminformation? The cores should be empty in your case but main and max should be set. To be sure what value is displayed, can you also provide 

```
cat /sys/class/hwmon/hwmon1/temp*_la*;echo "---";cat /sys/class/hwmon/hwmon1/temp*_i*
```

one more time?
Thank you for your support!

**Comment by snuffysasa** [comment]
Okay so first, here is this:

Tdie
Tctl
---
29875
56875

**Comment by snuffysasa** [comment]
And I updated to that version and here is the output

**Comment by sebhildebrandt** [comment]
@snuffysasa perfect. Thank you! Will leave it like that. As said. as I do not have information about cores, the array Is empty. Hope this is fine for you.

**Comment by snuffysasa** [comment]
Yep works for me.  And I don't need the max..

but shouldn't it say 70?
