### ISSUE TITLE
Suggestion of feature to show of percentage of usage CPU

### ISSUE THREAD

**Issue by tiagoaleff** [sebhildebrandt/systeminformation#366]

**Comment by sebhildebrandt** [comment]
@tiagoaleff what is the issue here??
Please be more specific when opening issues.  Thank you in advance.

**Comment by tiagoaleff** [comment]
Sorry. It was a suggestion of feature to show of percentage of usage CPU system. When I was looking the documentation I don't find something to show the percentage of CPU used by system. Sorry by my English.

**Comment by sebhildebrandt** [comment]
@tiagoaleff this is actually implemented already. `si.currentLoad(cb)` should provide this. Right?
