### ISSUE TITLE
Process name with space has an incomplete name property

### ISSUE THREAD

**Issue by viegasdom** [sebhildebrandt/systeminformation#369]
**Describe the bug**
There are cases where if the name of the process has a space the second half of the name ends up in the process params property.

**To Reproduce**
Using the function `si.processes`
```
const si = require('systeminformation');

(async () => {
  const ps = await si.processes();
  console.log(ps.list.find(p => p.name.toLowerCase() === 'activity'));
})
```

**Current Output**
```
{
  pid: 34384,
  parentPid: 1,
  name: 'Activity',
  pcpu: 0.2,
  pcpuu: 0,
  pcpus: 0,
  pmem: 0.6,
  priority: 4,
  mem_vsz: 5231412,
  mem_rss: 52956,
  nice: 0,
  started: '2020-04-25 04:56:57',
  state: 'sleeping',
  tty: '',
  user: '****',
  command: 'Activity',
  params: 'Monitor',
  path: '/System/Applications/Utilities/Activity Monitor.app/Contents/MacOS'
}
```

**Expected behavior**
```
{
  pid: 34384,
  parentPid: 1,
  name: 'Activity Monitor',
  pcpu: 0.2,
  pcpuu: 0,
  pcpus: 0,
  pmem: 0.6,
  priority: 4,
  mem_vsz: 5231412,
  mem_rss: 52956,
  nice: 0,
  started: '2020-04-25 04:56:57',
  state: 'sleeping',
  tty: '',
  user: '****',
  command: 'Activity Monitor',
  params: '',
  path: '/System/Applications/Utilities/Activity Monitor.app/Contents/MacOS'
}
```

**Environment (please complete the following information):**
 - systeminformation package version: 4.24.0
 - OS: macOS
 - Hardware: MacBook Pro 13

**Comment by sebhildebrandt** [comment]
@viegasdom thank you for your findings and for your fix! I see the problem but your fix does not cover all problems here. I will try to make a fix here today.

**Comment by viegasdom** [comment]
I imagined there was some edge case that I might overlooked! Thank you @sebhildebrandt for looking it up.

**Comment by sebhildebrandt** [comment]
@viegasdom so I finally had do do it a little bit different ... version 4.24.1 just released.
