### ISSUE TITLE
processes() Memory Leak

### ISSUE THREAD

**Issue by youyinnn** [sebhildebrandt/systeminformation#374]
**Describe the bug**

`si.processes()` will consume too many memories when calling it every second (short interval)

**To Reproduce**

``` javascript
setInterval(() => {
    si.processes().then(data => {
    });
}, 1000);
```

**Current Output**

Without this code,  my app will just use **10M~15M** memories otherwise it will raise to **48M~52M** memories.

This will not occur when calling method repeatly in a long interval (e.g 10s)

**Expected behavior**

The raising memories will keep in a acceptable range 

**Environment (please complete the following information):**
 - systeminformation package version: 18363.778
 - OS: windows 10

----

Is there any suggestion to fix or prevent this?

**Comment by sebhildebrandt** [comment]
@youyinnn will make some investigation here ...

**Comment by sebhildebrandt** [comment]
@youyinnn Memory raising to 48M - 52M is not unusual. A memory leak would be, if the memory increases steadily and GC has no chance to free memory. I detected some spots, where this could happen and corrected that.

**Comment by youyinnn** [comment]
@sebhildebrandt I agree with you. I think the `data` of the `processes()` might be stuck somewhere and still got references linking on it, so GC will no do its job. Thanks for investigating.

**Comment by sebhildebrandt** [comment]
@youyinnn do you still experience memory leaks here? I made some changes and I am curious if this still increases permanently? Can you test this on your side one more time?

**Comment by youyinnn** [comment]
@sebhildebrandt Hi~, I just upgrade the package from `^4.26.1` to `^4.26.5`, and the memories consumption is still the same. I guess that's it and that's what it should be. I cannot demand more from it.

But still, I wrote a little case for you to quickly check and experience this, it compared 3 libs in terms of fetching process list. I hope you can find something.

package.json
``` json
{
  "name": "process_list_test_case",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "process-list": "^2.0.0",
    "systeminformation": "^4.26.5",
    "tasklist": "^4.0.1"
  }
}
```

index.js
``` javascript
// lib: systeminformation
// using too many memories but cpu consumption is nice
// reliable, stable
const si = require('systeminformation');
function processes() {
    setInterval(() => {
        si.processes().then(data => {
            console.log('get data')  
        })
    }, 3000);
}
processes()


// lib: process-list
// using too many cpu resources because the 'WMI Provider Host'
// but memories consumption is fine
// and it's unstable
const { snapshot } = require("process-list");
function processes2() {
    setInterval(() => {
        snapshot('pid', 'name', 'path', 'threads', 'owner', 'starttime', 'vmem', 'pmem', 'cpu').then((data) => {
            console.log('get data')
        })
    }, 1000)
}
// processes2()

// lib: process-list
// same as lib: process-list
const tasklist = require('tasklist');
function processes3() {
    setInterval(() => {
        tasklist({verbose: true}).then((data) => {
            console.log('get data')
        })
    }, 1000);
}
// processes3()
```
