### ISSUE TITLE
Provide contributor instructions

### ISSUE THREAD

**Issue by chuckwondo** [sebhildebrandt/systeminformation#378]
Please provide instructions for building and testing the package. I've forked this repo, and I successfully ran `npm install`, but none of the other npm scripts work, such as `npm test`, `npm run compile`, and `npm run test-bare`, so I can't do anything in an attempt to provide changes suitable for a PR. How are you even building and testing this yourself?

**Comment by ishan3350** [comment]
If you have npm installed in your workstation/server then run npm install systeminformation --save and then you can use functions depending upon your needs. For detailed information please refer to below URLs.

https://www.npmjs.com/package/systeminformation
https://systeminformation.io

I hope this helps!

Thank you,

Best Regards,
Ishankumar Patel

**Comment by sebhildebrandt** [comment]
I am currently testing all functions with scripts against different machines/OS here locally. So I have some test procedure here. But you are right, would make sense to include this also to the repo. All other instructions can be found here:

https://github.com/sebhildebrandt/systeminformation/blob/master/docs/CONTRIBUTING.md
