### ISSUE TITLE
getAllData("", "eth0") hangs without closing the promise (systeminformation >=4.26.0)

### ISSUE THREAD

**Issue by Ks89** [sebhildebrandt/systeminformation#382]
**Describe the bug**
When I try to use getAllData("", "eth0").then(...) I don't receive an answer and .then() is never invoked in version 4.26.0 or greater.

*I read the known issue about smartmontools and I'm sure that I'm not using this package, because I'm working on an embedded system with a minimal linux distribution. So, probably, this is the cause of this problem.*

**Expected behavior**
I expect an answer with all data, eventually, without s.m.a.r.t. information without blocking the getAllData function.

**Environment (please complete the following information):**
 - systeminformation package version: >=4.26.0
 - OS: [e.g. macOS]: Linux (Yocto)
 - Hardware [e.g. MacBook Pro 13]: custom embedded hardware

**Comment by sebhildebrandt** [comment]
@Ks89 thank you for your report. To be more specific, it would be great to identify which function does not work:

Can you test the following separately: 

```
const si = require('systeminformation');
si.diskLayout().then(res => {
  console.log(res)
});
```

**Comment by Ks89** [comment]
As you suggested, I tried to run this:
```
const si = require('systeminformation');
si.diskLayout().then(res => {
  console.log(res)
});
```

but it doesn't log anything because si.diskLayout() hangs.
The promise doesn't complete.

**Comment by sebhildebrandt** [comment]
@Ks89 very clear, I guess I know where the problem is. Will provide a fix tonight.

**Comment by sebhildebrandt** [comment]
@Ks89 can you test the latest version 4.26.6? Should fix your issue.

**Comment by Ks89** [comment]
Now it's working, thank you for the fix

**Comment by sebhildebrandt** [comment]
@Ks89 happy that this is fixed now. Thank you for testing it.
