### ISSUE TITLE
Wifi speed always the same.

### ISSUE THREAD

**Issue by kassimir** [sebhildebrandt/systeminformation#384]
**Describe the bug**
I have an app that checks the wifi speed intermittently, and it always returns whatever the very first value is. I've had it return the same value for 3 days, but as soon as I restart the app, the speed is different.

**To Reproduce**
1. used function 'si.networkInterfaces().find(i => i.iface === 'Wi-Fi 2').netspeed' (obviously this only works, if you're checking iface 'Wi-Fi 2')
2. code snippet 'put that in a setInterval of 500ms'

**Current Output**
First time: correct internet speed.
Subsequent times: incorrect internet speed.

**Expected behavior**
Always returns current internet speed

**Environment (please complete the following information):**
 - systeminformation package version: 4.23.5
 - OS: Windows 10 Pro
 - Hardware: Ryzen 9 3950x

**Comment by sebhildebrandt** [comment]
@kassimir thank you for your findings here. As scanning for network interfaces is a quite intense operation I am caching the results where possible. So I will change this behaviour here. Will inform you if this is done. But be sure to not scan this to often ... getting all network information on windows takes up to 3 seconds!

**Comment by sebhildebrandt** [comment]
@kassimir thank you for your findings here. As scanning for network interfaces is a quite intense operation I am caching the results where possible. So I will change this behaviour here. Will inform you if this is done. But be sure to not scan this to often ...

**Comment by sebhildebrandt** [comment]
@kassimir Just released a new version where this caching only happens where really needed (just for internal purposes) Version 4.26.8 just released. Can you test it on your side?
