### ISSUE TITLE
call to networkStats blocks process

### ISSUE THREAD

**Issue by krishnaBharadwaj** [sebhildebrandt/systeminformation#385]
**Describe the bug**
I'm making calls to networkStats at regular intervals (3 seconds apart) to collect network traffic data for performance monitoring in a node.js server. Everything was working nicely up to version 4.23.1. From 4.23.2 onward, the calls seem to take up unusually long time to get back with the response or / and seem to block the server process.

**Code Snippet**

 	var sysInfo = require('systeminformation');
	PerformanceManager.prototype.init = function() {
 		...
		...
 
  		this.samplingInterval  = 3;
  		// Loop handle is used to clear the interval and restart when sampling rate is changed
  		this.loopHandle = setInterval(this.collectMetrics.bind(this),
  		this.samplingInterval * 1000);
 	};

	PerformanceManager.prototype.collectMetrics = function() {
         	...
		... 
		// Network traffic
		if (this.performanceMetrics.getNetworkData) {
			var totalTransferred = {
				tx_sec: 0,
				rx_sec: 0,
				ms: 0
			};
			sysInfo.networkStats("*", function (data) {
				var count = 0;
				for (var i = 0; i < data.length; i++) {
					if (data[i].operstate === 'up') {
						totalTransferred.tx_sec += data[i].tx_sec;
						totalTransferred.rx_sec += data[i].rx_sec;
						totalTransferred.ms += data[i].ms;
						count++;
					}
				}
				if (count > 0) {
					totalTransferred.ms /= count;
					this.collectSystemTraffic(totalTransferred);
				}
			}.bind(this));
		}
		...
	};

**Environment (please complete the following information):**
 - systeminformation package version: 4.23.2 onward
 - OS: Windows10
 - Hardware Asus ROG, Dell Alienware Aurora R8.

**Comment by sebhildebrandt** [comment]
@krishnaBharadwaj will make some investigation tomorrow morning.

**Comment by sebhildebrandt** [comment]
@krishnaBharadwaj ... fixed issue. Version 4.26.10 just released.
