### ISSUE TITLE
Ability to get system information from a remote server

### ISSUE THREAD

**Issue by davidmoshal** [sebhildebrandt/systeminformation#386]
Ability to get system information from a remote system.

Ideally this would work through regular ssh without having to install an "agent" on the remote server.

Alternatively if that's not possible, a docker image would be better be a preferred agent, ie: without having to install node on the remote host. 

The docker image (agent) should be able to get system information from the host, not just the container.

**Comment by sebhildebrandt** [comment]
@davidmoshal getting that detailed information from a remote server is not that simple across all operations systems. So then you NEED to have some kind of software or script on the remote machine. And you then have to decide if this is a pull or push approach for getting client information. Docker might be a nice idea (will test this) but then you need at least docker to be installed on the remote. Systeminformation current do not specify WHAT you want to track, and if this is a pull or push solution. I think it should be easy to create a little container or script using systeminformation as a package to provide the information you want to track. But that would not really be a part of this package, right? 

Closing it for now but I would be happy to share further ideas here! Please feel free to comment your ideas.
