### ISSUE TITLE
How to improve the speed of obtaining the serial number of the disk

### ISSUE THREAD

**Issue by zj1838277795** [sebhildebrandt/systeminformation#387]
I use the 'disLayout' to get the serial number of filesystem, but it 'console.log' the serial number after 2 seconds. How can I improve the speed.

**Comment by sebhildebrandt** [comment]
@zj1838277795 I guess, you are working on a windows platform, right? 
WMIC is quite slow but the only possibility to obtain all the informations we want in systeminformation. Currently I do not really see a possibility to speed this up.

**Comment by SymbolCsaba** [comment]
This value changes really rarely. In application can be cached by any id or index.

**Comment by sebhildebrandt** [comment]
@SymbolCsaba @zj1838277795 : I agree, I would only call `diskLayout()` once and cache the value. I guess the problem would be still the FIRST call, right? If you use this e.g. to get a hardware ID, you want to get back a value as soon as possible. If this is your use case, consider using the other functions like `si.uuid()`
