### ISSUE TITLE
wsl in windows fsSize return nothing.

### ISSUE THREAD

**Issue by bookyo** [sebhildebrandt/systeminformation#392]
wsl ubuntu18.04 on windows 10 use si.fsSize() return nothing.

**Comment by bookyo** [comment]
![QQ图片20200801204332](https://user-images.githubusercontent.com/20472717/89102002-b7ca4e00-d437-11ea-9d5c-9dd81beff77b.png)
df -lkPTx squashfs | grep ^/ return null.

**Comment by sebhildebrandt** [comment]
@bookyo thank you for the additional information. Will provide a fix for that. Need to test it also on my machines.

**Comment by sebhildebrandt** [comment]
@bookyo fixed now in version 5.0.11. New version just published.
