### ISSUE TITLE
cpuTemperature does not return after resolve (successful attempt)

### ISSUE THREAD

**Issue by akiroz** [sebhildebrandt/systeminformation#398]
**Describe the bug**
The `cpuTemperature` call doesn't return after a successful attempt causing all methods to be attempted.

**To Reproduce**
call `cpuTemperature`

**Solution**
Add `return` after `resolve`:

https://github.com/sebhildebrandt/systeminformation/blob/1564a78d9f322f164a767025aef6346e0eef678b/lib/cpu.js#L821

To illustrate the problem, consider the following snippet:
```js
new Promise(resolve => {
    console.log(0);
    resolve();
    console.log(1);
}).then(() => console.log(2));
```
which yields the output:
```
0
1
2
```

**Comment by sebhildebrandt** [comment]
@akiroz: can you provide more information what platform (OS, OS Version, Hardware, node version) you are on and where `cpuTemperature()` does not return correctly?

**Comment by akiroz** [comment]
@sebhildebrandt This is not an OS specific problem, and `cpuTemperature` does in fact return the correct results. The problem is that it will also attempt to get the same information multiple times using different methods and this slows down my system because the order for `cpuTemperature` is
1. `coretemp` sysfs
2. `sensors`
and it just happens that `sensors` on my system will consume a lot of resources due to hardware issues. But in my case I don't even need the `sensors` call because I have the `coretemp` driver.

**Comment by sebhildebrandt** [comment]
@akiroz thank you for your explanation, I see the problem. Will have a look at it later today.

**Comment by sebhildebrandt** [comment]
@akiroz thank you for your explanation, I see the problem. Will have a look at it later today.

**Comment by sebhildebrandt** [comment]
@akiroz thank you for your explanation, I see the problem. Will have a look at it later today.

**Comment by sebhildebrandt** [comment]
@akiroz thank you for your explanation, I see the problem. Will have a look at it later today.

**Comment by sebhildebrandt** [comment]
@akiroz thank you for your explanation, I see the problem. Will have a look at it later today.

**Comment by sebhildebrandt** [comment]
Fixed. Version 4.26.11 just released.
