### ISSUE TITLE
Temperature Returns Innacurate Data

### ISSUE THREAD

**Issue by LeoFisher657** [sebhildebrandt/systeminformation#40]
Using cputemperature to measure the temperature of my CPU, I get these values: 

`{ main: -172.86666666666667,
  cores: [ -273.2, -273.2, 27.8 ],
  max: -1 }`

My CPU only has two cores but it is indicated that there are three.

Also, I haven't checked using any other software, but I'm *fairly* sure my CPU isn't at Absolute Zero.

Is this an issue with the sensors on my CPU?

**Comment by sebhildebrandt** [comment]
Can you post the result of `wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CriticalTripPoint,CurrentTemperature /value`?

**Comment by LeoFisher657** [comment]
CriticalTripPoint=4832
CurrentTemperature=0


CriticalTripPoint=4832
CurrentTemperature=0


CriticalTripPoint=0
CurrentTemperature=3010

**Comment by LeoFisher657** [comment]
It must be a sensor problem by the looks of it. Something on my end. I did check with HWiNFO and read my CPU temperature as 47C

**Comment by sebhildebrandt** [comment]
Yes ... anyway I will check my code and come back to that tomorrow.

**Comment by LeoFisher657** [comment]
Alright, its probably an issue with my machine anyway.

**Comment by sebhildebrandt** [comment]
Code seems to be ok ... but I will keep an eye on that. Closing it for now.
