### ISSUE TITLE
Listeners

### ISSUE THREAD

**Issue by robtoll** [sebhildebrandt/systeminformation#400]
Excellent module. Good work!

Is it possible to setup listeners that fire when a status changes?
For example, listen for when a user unplugs the power, and the system switches to battery.
Or when the audio is muted. Etc etc.

Cheers!

**Comment by sebhildebrandt** [comment]
@robtoll: so I had a look at the `win-audio` package, they also define a polling interval. Basically `NODE` as a high level programming language will mostly not know about system events (unless you program functions in a low level programming language like c/c++). Therefore polling is an alternative for this use case. 

I just released a new version of systeminformation (v 4.27.0) that includes a generic `observe()` function. See the example in the documentation (https://systeminformation.io/statsfunctions.html).

**Comment by robtoll** [comment]
Wow! Really nice. That was quick :)
Thanks very much!
