### ISSUE TITLE
SyntaxError: Unexpected token ... - spread syntax error

### ISSUE THREAD

**Issue by citolen** [sebhildebrandt/systeminformation#404]
**Describe the bug**
https://github.com/sebhildebrandt/systeminformation/commit/9f1b6ef43d307b05da777a949ab6f6bc35f6e3ab added the use of the spread syntax and it isn't compatible with some of the node versions this module is meant to support.
`engines.node` is specified as `>=4.0.0`. 

**To Reproduce**
`require('systeminformation');` from a node version that doesn't support the spread syntax. i.e 5.12.0

**Current Output**
```
\node_modules\systeminformation\lib\index.js:358
        _data = { ...data };
                  ^^^

SyntaxError: Unexpected token ...
```

**Expected behavior**
No SyntaxError.

**Environment:**
 - systeminformation package version: 4.27.0 & 4.27.1
 - OS: macOS
 - Hardware: MacBook Pro 15

Thank you.

**Comment by sebhildebrandt** [comment]
@citolen ... wow sorry! Completely forgot about that ;-) Fixed ... version 4.27.2 just released
