### ISSUE TITLE
GPU memory max value of the only 4 GB on Windows

### ISSUE THREAD

**Issue by llka** [sebhildebrandt/systeminformation#406]
**Description of what the bug is**
When I try to get GPU memory on a Windows machine, the returned value is always less than or equal to 4 GB.
`systemInformation.graphics().controllers.vram <= 4GB`

**Possible cause**
I suppose that the bound is brought about by Win32_VideoController
https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-videocontroller
It returns AdapterRAM in **uint32 data type** which max value is 2^32, which is 4GB. Therefore we cannot use Win32_VideoController to retrieve video adapter memory anymore.

**To Reproduce**
You need a Windows machine with GPU which has more than 4 GB ram.
1. used function '`systemInformation.graphics()`'
2. code snippet `'systemInformation.graphics()
    .then(gpuData => {
      console.log('graphics: \n' + JSON.stringify(gpuData) + '\n');
    })'`
3. start app / code `ng build --configuration=local --optimization=false --base-href ./ && tsc --p electron && electron . --local`
4. See output/error ''
**Current Output**
![image](https://user-images.githubusercontent.com/22171163/91544841-fcf37a00-e928-11ea-8691-d400a74c0930.png)

**Expected behaviour**
Vram for:
 NVIDIA GeForce GTX 1080 - [8 GB](https://www.nvidia.com/en-gb/geforce/10-series/?ncid=afm-chs-44270&ranMID=44270&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-qWw3DHYeeM.mVFk04FWHCA)
 NVIDEA Tesla T4 - [16 GB](https://www.nvidia.com/en-gb/data-center/tesla-t4/)

**Environment**
 - systeminformation package version: 4.27.1
 - OS: Windows 10, Windows 7
 - Hardware  NVIDIA GeForce GTX 1080, NVIDIA Tesla T4

**Additional context**

**Comment by Krish120003** [comment]
Perhaps this information could be retrieved from DxDiag? I've tested it and it outputs the accurate GPU VRAM.

**Comment by sebhildebrandt** [comment]
@llka, @Krish120003: As DxDiag is not supposed to be used as a command line tool (well it can be used, but the output will be written asynchronously to a file and the systeminformation package should NOT make any modifications on the computer like writing files), this is not really an option. 

wmic will not report vram sizes bigger then 4GB so this is a known issue. But now we have a support for nvidia-smi (if installed) which then should return the correct vram value. Can you verify this on your machines?

**Comment by sebhildebrandt** [comment]
@llka does this still exists even we now have Nvidia-smi parsing in place? If yes, can you probable post the content of the following registry key:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinSAT
```

Don't know if this is a relevant key but just curious...

**Comment by sebhildebrandt** [comment]
@mily20001 @llka as the new version 5 has been released with some improvements, can you test this issue on your machines? There is a simple testing framework where you can easily test all functions https://systeminformation.io/tests.html 

If this does not returns the expected results, can you post the content of the following registry key:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinSAT
```

Don't know if this is a relevant key but just curious...

**Comment by sebhildebrandt** [comment]
Closing it for now ... see comments above.
