### ISSUE TITLE
Network Card detected as virtual while it probably shouldn't

### ISSUE THREAD

**Issue by jeffrson** [sebhildebrandt/systeminformation#408]
**Describe the bug**
I'm running a virtual machine on VMWare vSphere with Docker installed. There are a lot of interfaces (`ip a`):
lo (loopback)
ens192
docker_gwbridge
docker0
veth*

With
```
const si = require('systeminformation')
si.networkInterfaces(ni => console.log(ni))
```

I get output like (somewhat shortened)

```
 {
    iface: 'lo',
    ifaceName: 'lo',
    ip4: '127.0.0.1',
    ip4subnet: '255.0.0.0',
    ip6: '::1',
    ip6subnet: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
    mac: '00:00:00:00:00:00',
    internal: true,
    virtual: false,
    operstate: 'unknown',
    type: 'virtual',
    ...
  },
  {
    iface: 'ens192',
    ifaceName: 'ens192',
    ip4: '...',
    ip4subnet: '...',
    ip6: '...',
    ip6subnet: '...',
    mac: '00:50:56:...',
    internal: false,
    virtual: true,
    operstate: 'up',
    type: 'wired',
    ...
  },
  {
    iface: 'docker_gwbridge',
    ifaceName: 'docker_gwbridge',
    ip4: '172.18.0.1',
    ip4subnet: '255.255.0.0',
    ip6: 'fe80::...',
    ip6subnet: 'ffff:ffff:ffff:ffff::',
    mac: '02:42:2e:...',
    internal: false,
    virtual: false,
    operstate: 'up',
    type: 'wired',
    ...
  },
  {
    iface: 'veth*',
    ...
    internal: false,
    virtual: true,
    operstate: 'up',
    type: 'wired',
    ...
  },
  ...
```

So docker0 is not found at all (probably because `ip a` gives `3: docker0: <NO-CARRIER,...`?
ens192 detected as virtual (which it of course is, but inside the VM it's not)
docker_gwbridge not detected as virtual (the mac differs inside containers from the 3rd octet, but you could use the interface name anyway for detection)

**Expected behavior**
Well, ens192 should **not** be virtual in this case, while docker_gwbridge should be.

**Environment (please complete the following information):**
 - systeminformation package version: 4.27.3
 - OS: [e.g. macOS] Linux with Docker-CE
 - Hardware [e.g. MacBook Pro 13]: vSphere ESXi 6.7

**Comment by sebhildebrandt** [comment]
@jeffrson lets see what node.js internal function returns back. Can you run the following code snippets on your machine:

in Nodejs (CLI)

```
os.networkInterfaces();
```

Thank you in advance.

**Comment by sebhildebrandt** [comment]
@jeffrson I digged a litte into my code: `ens192` is detected as a virtual interface because of its mac address. As there are no real indicators for virtual interfaces, I was using a list of mac addresses that are usually used for virtual interfaces.

**Comment by sebhildebrandt** [comment]
Closing this for now as I do not really see a workaround,
