### ISSUE TITLE
Problem with number of Processors and Cores in a virtual machine

### ISSUE THREAD

**Issue by jiferrero** [sebhildebrandt/systeminformation#409]
**Describe the bug**
We are using the library in a virtual machine hosted in Digital Ocean, and it seems like there is a misleading in the info retrieved by cpu function, mixing processors and cores

**To Reproduce**
When using the si.cpu() function

**Current Output**
{
  "manufacturer": "Intel®",
  "brand": "Xeon® Gold 6140",
  "vendor": "GenuineIntel",
  "family": "6",
  "model": "85",
  "stepping": "4",
  "revision": "",
  "voltage": "",
  "speed": "2.30",
  "speedmin": "",
  "speedmax": "",
  "governor": "",
  **"cores": 4,
  "physicalCores": 4,
  "processors": 4,**
  "socket": "",
  "cache": {
    "l1d": 131072,
    "l1i": 131072,
    "l2": 16,
    "l3": ""
  },
  "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 pku ospke md_clear",
  "currentSpeed": {
    "min": 2.29,
    "max": 2.29,
    "avg": 2.29,
    "cores": [
      2.29,
      2.29,
      2.29,
      2.29
    ]
  },
  "currentLoad": {
    "avgload": 0.02,
    "currentload": 5.955334987593052,
    "currentload_user": 1.9851116625310175,
    "currentload_system": 3.970223325062035,
    "currentload_nice": 0,
    "currentload_idle": 94.04466501240695,
    "currentload_irq": 0,
    "raw_currentload": 240,
    "raw_currentload_user": 80,
    "raw_currentload_system": 160,
    "raw_currentload_nice": 0,
    "raw_currentload_idle": 3790,
    "raw_currentload_irq": 0,
    "cpus": [
      {...},
      {...},
      {...},
      {...}
    ]
  },
  "temp": {
    "main": -1,
    "cores": [],
    "max": -1
  }
}

**Expected behavior**
We think that from DO documentation, each vCPU = 1 core, so as we are using 4vCPU it means 4 cores of 1 single processor so the output should be at least something like this:

**{
...
  "cores": 4,
  "physicalCores": 4,
  "processors": 1,
...
}**

We don't really know how the virtual machine treats the cores and physical cores but the processor should be 1

**Environment (please complete the following information):**
 - systeminformation package version: 4.27.3
 - OS: Ubuntu 20.04
 - Hardware: virtual machine hosted in DO

Thank you so much, once again, for your wonderful library.

Best regards

**Comment by sebhildebrandt** [comment]
@jiferrero can you run the following two commands:

```
lscpu
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
```

and post the output here? Thank you in advance.

**Comment by jiferrero** [comment]
Hi @sebhildebrandt .... yes sure... following you can find lscpu command output

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       2
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:                        4
CPU MHz:                         2494.096
BogoMIPS:                        4988.19
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        8 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_
                                 tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_ti
                                 mer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriori
                                 ty ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx51
                                 2bw avx512vl xsaveopt xsavec xgetbv1 pku ospke md_clear

The cat output for system cpu it is not available far away of cpu0 so I can not give you the route you asked it for...
It that helps you?

Thank you in advance

**Comment by sebhildebrandt** [comment]
@jiferrero thank you! This helps a lot identifying the issue. I guess I will provide a fix tomorrow.

**Comment by jiferrero** [comment]
Thank you so much @sebhildebrandt ... that's would be awesome!

**Comment by sebhildebrandt** [comment]
@jiferrero I had a look at the output of `lscpu` you provided ...

Due to this output, we have a machine with **2 physical processors** (socket(s) = 2)

funny enough that systeminformation gives the output you provided ... with this lscpu output we should get

```
{
   ...
   "cores": 4,
   "physicalCores": 4,
   "processors": 2,
   ...
}
```

One more favour: can you recheck the following:

**Command line:**
```
lscpu | grep "Socket(s):"
```

**In node (cli)**
```
os.cpus().length;
```

**with systeminformation (latest version):**
```
const si = require('systeminformation');

// promises style - new since version 3
si.cpu()
    .then(data => console.log(data))
    .catch(error => console.error(error));
```

Can you post once again the output ... Thank you so much!

**Comment by jiferrero** [comment]
hi @sebhildebrandt ...... oh yes so funny that's a fault of mine .... we destroyed the virtual machine a couple of days ago before and I did not realize it when you answered me
The output I gave you yesterday was in a virtual machine with 2 vcpu what it is maybe more consistent with what you have expected to have... sorry again about this mistake.
But I'm still don't understand how to map this info, I mean if systeminformation recognizes 2 physical sockets and 4 physical cores with no hyperthreading then then info provided at digital ocean of 2vcpu equivalent to only 2 cores are far away of systeminformation given power XD

**Comment by sebhildebrandt** [comment]
@jiferrero OK, but then ... if you run the `systeminformation`code one more time on the new machine ... you should get:

```
{
   ...
   "cores": 2,
   "physicalCores": 2,
   "processors": 2,
   ...
}
```

... which should be fine, right? Can you check it?

**Comment by jiferrero** [comment]
yes @sebhildebrandt ... you are right ... the output of systeminformation for cpu on this new machine with **2 vcpu** is the following:

{
  manufacturer: 'Intel®',
  brand: 'Xeon® Gold 6140',
  vendor: 'GenuineIntel',
  family: '6',
  model: '85',
  stepping: '4',
  revision: '',
  voltage: '',
  speed: '2.30',
  speedmin: '',
  speedmax: '',
  governor: '',
  **cores: 2,
  physicalCores: 2,
  processors: 2,**
  socket: '',
  cache: { l1d: 65536, l1i: 65536, l2: 8, l3: '' }
}

But the question is still that I think that processors in the virtual machine is correlated to physical cores, I mean the other machine with tested on before destroyed showed up 
{
  ...
  "cores": 4,
  "physicalCores": 4,
  "processors": 4,
  ...
}
so I suppose that a machine with **8 vcpu** will shows up those fields filled with 8 and a machine with **40 vcpu** will shows up 40 on all those same fields

**Comment by sebhildebrandt** [comment]
@jiferrero So here some details:

- cores are dependent on what node really sees (`os.cpus().length;`), and what `lscpu` shows in the line `CPU(s)` ... these should be the same.
- physicalCores defaults to `cores` but if there are more detailed information like in `lscpu` line `thread(s) per core` I can then calculate the physical cores. In your example this line returns 1 so cores = physical cores
- processors defaults to 1 but if `lscpu` returns a line with `socket(s):`  then THIS is the true number of processors. 

In this specific case this is the same. So if you have 4 **vCpus** then it depends on the implementation of lscpu or to be more specific: how linux "sees" the virtual cores. If `lscpus` returns 4 `sockets` but physically there is only one, then linux thinks there are 4 processors and so does `systeminformation`. I do not see a better way to get the true number of processors if linux also "fails" to get it correctly.

Hope this makes it clear. I would the close this issue ...
And one more time: thank you for helping testing!!!

**Comment by jiferrero** [comment]
hi @sebhildebrandt ... thank you for all of this information an all your time and effort to make this awesome library, we all appreciate it so much. We keep in touch for other issues and enhancements as we still on developing... 

You can close this issue
Thank you again

**Comment by sebhildebrandt** [comment]
@jiferrero you are welcome! If you have any other issues just give me a note. I really appreciate all comments to improve this library ;-) Have a nice Sunday!
