### ISSUE TITLE
si.mem(cb) - Memory information - Not resolve promise on windows

### ISSUE THREAD

**Issue by TwentyFourColors** [sebhildebrandt/systeminformation#41]
Hi Sebastian Hildebrandt, 

Congratulations but this work, is really good : ) 

However i found a issue on "si.mem(cb)" function because "Windows_NT" platform not resolve the promise, because of this never return of information. 

It would be great to finish this.

Thanks Sebastian.

A greetings. 

SEE A IMAGE HERE ---> https://ibb.co/hir8xk

**Comment by sebhildebrandt** [comment]
Hi ... thank you for your comment! Yes you are right! I just checkt the code. As I am anyway working on a new release for today, I will correct that! Thank you once again.

**Comment by TwentyFourColors** [comment]
Ohhh !! Awesome !! 

Thanks Sebastian, i hope the new version : )

**Comment by sebhildebrandt** [comment]
Done! AND I extended `si.mem()`to also get correct values for swap file usage ;-)

**Comment by TwentyFourColors** [comment]
Thanks so much Sebastian, for you work and fast !!
