### ISSUE TITLE
Raspberry Pi - Revision codes

### ISSUE THREAD

**Issue by chainhead** [sebhildebrandt/systeminformation#410]
**Is your feature request related to a problem? Please describe.**
How do I extract [Raspberry Pi revision codes](https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md) with `systeminformation`?

**Describe the solution you'd like**
Perhaps, a one-liner such as `systeminformation.rpi()` would be nice.

**Describe alternatives you've considered**
This is the mapping I am considering.

| Raspberry Pi documentation | `systeminformation` |
| ---------------------------- | -------------------- |
| Hardware | `si.cpu.manufacturer` |
| Revision | `si.cpu.revision` |
| Serial | `si.system.serial` |

**Additional context**
- Should be able to run on [various supported OS](https://www.raspberrypi.org/downloads/)

**Comment by chainhead** [comment]
So, here is what I get from running `systeminformation` on Raspberry Pi.

## System information

```js
const si = require('systeminformation')
si.system().then(data => console.log(data))
```

```json
{ manufacturer: 'ARM1176',
  brand: '',
  vendor: 'ARM',
  family: '',
  model: '7',
  stepping: 'r0p7',
  revision: '',
  voltage: '',
  speed: '0.70',
  speedmin: '0.70',
  speedmax: '0.70',
  governor: 'ondemand',
  cores: 1,
  physicalCores: 1,
  processors: 1,
  socket: '',
  cache: { l1d: '', l1i: '', l2: '', l3: '' } }
```

## CPU information

```js
const si = require('systeminformation')
si.cpu().then(data => console.log(data))
```

```json
{ manufacturer: 'Raspberry Pi Foundation',
  model: 'BCM2835 - Pi Model B',
  version: '000e - Rev 2.0',
  serial: '000000002a61ec5f',
  uuid: '',
  sku: '-' }
```

## Raspberry Pi native information

This is from `cat /proc/cpuinfo`.

```bash
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 000e
Serial		: 000000002a61ec5f
Model		: Raspberry Pi Model B Rev 2
```

As you can see, the last three lines of output does not seem to have equivalence in the `si` output. How to get them?

**Comment by sebhildebrandt** [comment]
@chainhead I will think what would be the best way to add this and come back later.

**Comment by chainhead** [comment]
Bump.

**Comment by sebhildebrandt** [comment]
@chainhead I had a look at it and as you said, most of the information is already available. As I was not clear about what "three" lines are missing, I went into it: to my mind the following is missing:

```
BogoMIPS	: 697.95
CPU revision	: 7
```

- implementer/part is already decoded --> ARM1176
- features can be found in the cpu flags ...

Something else you are missing??

**Comment by sebhildebrandt** [comment]
@chainhead replying to your second comment ("last three lines of output does not seem to have equivalence") ... well all three of them are in `si.system()`or do I miss something? Closing it for now.

**Comment by chainhead** [comment]
Well, the information is not available as an exact match. For example, `model` is reported in `/proc/cpuinfo` as `Raspberry Pi Model B Rev 2`.  Whereas, `model` in `si` is reported as `BCM2835 - Pi Model B'`. Similarly, the `Revision` in `/proc/cpuinfo` is reported as `000e` whereas, `000e` is reported as `version` in `si`.

Thus, the information does seem to be present in `si` but, it does not seem to be an exact match. And, this is important for me. Because, me and my vendor are using the hash of this information (along with some others) to tally device firmware and application software. My vendor uses `/proc/cpuinfo` and I want to use `si` (or, any other module that can read `/proc/cpuinfo`).

**Comment by sebhildebrandt** [comment]
@chainhead thank you for your reply. As `systeminformation` is a more generic package, I am not happy to implement vendor specific changes ... so I need again to think about how to manage this one. I am thinking of two possibilities (modifying is output OR create a little RPI package) ... will come back with my ideas later.

**Comment by chainhead** [comment]
An RPi package would be excellent!

**Comment by sebhildebrandt** [comment]
@chainhead I now have rewritten the revision code parsing and adapted also `si.cpu()` and `si.system()` for raspberry devices:

`si.system()` now outputs something like:

```
{
  manufacturer: 'Raspberry Pi Foundation',
  model: 'Raspberry Pi 4 Model B Rev 1.4',
  version: 'd03114',
  serial: '10000000cd8c47b9',
  uuid: '',
  sku: '-',
  raspberry: {
    manufacturer: 'Sony UK',
    processor: 'BMC2711',
    type: '4B',
    revision: '1.4'
  }
}
```

The model and revision matches exactly to what `/proc/cpuinfo` returns, further details are now in the optional return parameter `raspberry`.

`si.cpu()` now outputs something like:

```
{
  manufacturer: 'Sony UK',
  brand: 'BMC2711',
  vendor: 'ARM',
  family: 'Cortex-A72',
  model: '3',
  stepping: 'r0p3',
  revision: 'd03114',
  voltage: '',
  speed: '2.00',
  speedmin: '0.67',
  speedmax: '2.00',
  governor: 'ondemand',
  cores: 4,
  physicalCores: 4,
  processors: 1,
  socket: 'SOC',
  cache: { l1d: '', l1i: '', l2: '', l3: '' }
}
```

So the real processor name, manufacturer and family is now better reflected here.
This should now fix this request. Version 4.29.1 just released.

**Comment by chainhead** [comment]
Thank you, @sebhildebrandt . I will try this out some time.
