### ISSUE TITLE
CPU flags not obtained via `.get()`

### ISSUE THREAD

**Issue by williamd5** [sebhildebrandt/systeminformation#414]
**Describe the bug**
When using the `.get()` method, the CPU flags are not returned whether you specify them in particular or `*`. I was only able to obtain the CPU flags using `.getAllData()`

**To Reproduce**
1. used `si.get({cpu:"flags"}, console.log)` and `si.get({cpu:"*"}, console.log)`
2. In neither scenario are the flags returned. Here are the outputs to the methods called above in the corresponding order:

```json
{
  "cpu": {}
}
```

```json
{
  "cpu": {
    "manufacturer": "Intel®",
    "brand": "Core™ i7-9750H",
    "vendor": "GenuineIntel",
    "family": "6",
    "model": "158",
    "stepping": "10",
    "revision": "",
    "voltage": "",
    "speed": "2.60",
    "speedmin": "",
    "speedmax": "2.59",
    "governor": "",
    "cores": 12,
    "physicalCores": 6,
    "processors": 1,
    "socket": "BGA1440",
    "cache": {
      "l1d": 0,
      "l1i": 0,
      "l2": 1572864,
      "l3": 12582912
    }
  }
}
```

**Expected behavior**
This node module seems to have access to (or at least to some part of) the CPU flags. For example, using the `.getAllData()` method returns the flags in `cpu.flags`, which for me are: (according to this module)

```
de pse tsc msr mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe
```

and here are the flags according to `lscpu` under Ubuntu subsystem on Windows10.:

```
fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt ibrs ibpb stibp ssbd
```

**Environment (please complete the following information):**
 - systeminformation package version: 4.27.3
 - OS: Windows 10 Pro
 - Hardware: LENOVO IdeaPad L340-15IRH Gaming

**Comment by sebhildebrandt** [comment]
@williamd5 will have a look at it tomorrow in the morning.

**Comment by sebhildebrandt** [comment]
@williamd5 due to the documentation the cpu flags are actually not part of `cpu()`. There is a separate function `si.cpuFlags()`. So with `get` this means, you can obtain the values using:

```
const si = require('systeminformation');

valueObject = {
    cpu: '*',
    cpuFlags: '*'
}

si.get(valueObject).then(data => console.log(data));
```

Additional remarks: I added `cpuFlags` directly to `cpu` only in `getAllData()`. But I am now thinking of just do it in every case.
