### ISSUE TITLE
Laptop apparently doesn't use a battery.

### ISSUE THREAD

**Issue by PikaDude** [sebhildebrandt/systeminformation#42]
When I execute the following code my laptop that runs on a battery, it returns "false".
```javascript
var si = require('systeminformation');
si.battery(function (battery) {
console.log(battery.hasbattery);
});
```
I am using a Dell Laptop running Windows 10 using the latest version of System Information. Any ideas?

**Comment by sebhildebrandt** [comment]
Hi, can you post the output of the the following commang (in console):

```
WMIC Path Win32_Battery Get BatteryStatus, DesignCapacity, EstimatedChargeRemaining /value
```

**Comment by PikaDude** [comment]
```
BatteryStatus=2
DesignCapacity=
EstimatedChargeRemaining=70
```

**Comment by sebhildebrandt** [comment]
Thank you so much! 

One more thing: can you post the full output of this one:

```
WMIC Path Win32_Battery Get /value

```
Will have a look on it and provide a fix as soon as possible ...

**Comment by sebhildebrandt** [comment]
... and one more question: when running the above statements, did your laptop was connected to AC? If yes, can you disconnect it and try running those statements again (and post outputs)?

Thank you so much for helping solving this issue.

**Comment by PikaDude** [comment]
When charging:
`WMIC Path Win32_Battery Get BatteryStatus, DesignCapacity, EstimatedChargeRemaining /value`:
```
BatteryStatus=2
DesignCapacity=
EstimatedChargeRemaining=70
```
`WMIC Path Win32_Battery Get /value`:
```
Availability=2
BatteryRechargeTime=
BatteryStatus=2
Caption=Internal Battery
Chemistry=6
ConfigManagerErrorCode=
ConfigManagerUserConfig=
CreationClassName=Win32_Battery
Description=Internal Battery
DesignCapacity=
DesignVoltage=12573
DeviceID=58857LGC-LGC3.95DELL 92NCT5C
ErrorCleared=
ErrorDescription=
EstimatedChargeRemaining=87
EstimatedRunTime=71582788
ExpectedBatteryLife=
ExpectedLife=
FullChargeCapacity=
InstallDate=
LastErrorCode=
MaxRechargeTime=
Name=DELL 92NCT5C
PNPDeviceID=
PowerManagementCapabilities={1}
PowerManagementSupported=FALSE
SmartBatteryVersion=
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=REDACTED
TimeOnBattery=
TimeToFullCharge=
```
Not Charging:
`WMIC Path Win32_Battery Get BatteryStatus, DesignCapacity, EstimatedChargeRemaining /value`:
```
BatteryStatus=1
DesignCapacity=
EstimatedChargeRemaining=88
```
`WMIC Path Win32_Battery Get /value`:
```
Availability=3
BatteryRechargeTime=
BatteryStatus=1
Caption=Internal Battery
Chemistry=6
ConfigManagerErrorCode=
ConfigManagerUserConfig=
CreationClassName=Win32_Battery
Description=Internal Battery
DesignCapacity=
DesignVoltage=12173
DeviceID=58857LGC-LGC3.95DELL 92NCT5C
ErrorCleared=
ErrorDescription=
EstimatedChargeRemaining=88
EstimatedRunTime=346
ExpectedBatteryLife=
ExpectedLife=
FullChargeCapacity=
InstallDate=
LastErrorCode=
MaxRechargeTime=
Name=DELL 92NCT5C
PNPDeviceID=
PowerManagementCapabilities={1}
PowerManagementSupported=FALSE
SmartBatteryVersion=
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=REDACTED
TimeOnBattery=
TimeToFullCharge=
```

**Comment by sebhildebrandt** [comment]
Great, will come back to you, if I have a fix ...

**Comment by sebhildebrandt** [comment]
Provided a fix ... please let me know if this works. Closing it for now.

**Comment by PikaDude** [comment]
This fix didn't help, I updated to the latest version (3.23.1) and it still doesn't think my laptop has a battery, charging or not.

**Comment by sebhildebrandt** [comment]
:-( 
OK, seems, I did something wrong in my new code ... can you post the exact output of System Information `si.battery()` when charging and when not? Your output of WMIC is anyway visible above. I will recheck my code then once again. Sorry for the inconvenience.

**Comment by PikaDude** [comment]
Charging and not charging return the same result:
```
{ hasbattery: false,
  cyclecount: 0,
  ischarging: false,
  maxcapacity: 0,
  currentcapacity: 0,
  percent: 0 }
```

**Comment by sebhildebrandt** [comment]
:-( ... hmmmm
You're sure, you have a battery installed ;-) (just kidding!)
Well, ok. I will recheck the code (already have an idea where the problem might be). And I am reopening issue again.

**Comment by sebhildebrandt** [comment]
Maybe you can test the just released new version 3.23.2

**Comment by PikaDude** [comment]
Still no difference :/

**Comment by sebhildebrandt** [comment]
:-(
Can you try the following hack, just wanted to know the output here ...
in `node_modules/systeminformation/lib/battery.js` you should see in line 120ff:

```
          if (stdout) {
            let lines = stdout.split('\r\n');
            let status = getValue(lines, 'BatteryStatus', '=').trim();
```

can you add

```
          if (stdout) {
            let lines = stdout.split('\r\n');
            console.log(lines)   // ADD THIS LINE
            let status = getValue(lines, 'BatteryStatus', '=').trim();
```

and paste that output (charging and not charging) here?
Thank you so much!!

**Comment by PikaDude** [comment]
Ok this is going to sound really stupid, after looking through your code, I noticed how it works and apparently the script didn't have permission to run the WMIC command. I had to run the cmd as administrator and then run the script. I'm really sorry for causing such trouble. It now works.

**Comment by sebhildebrandt** [comment]
Well thank you!! So I should more explicitly have to mention that on some windows versions admin rights are important ... there is a small hint in the README.md but seems to be to small.
So anyway, if you discover any other issues, you are always welcome!
