### ISSUE TITLE
get function for fsSize is not working when specific fileds are given in valueObject

### ISSUE THREAD

**Issue by appvitals1** [sebhildebrandt/systeminformation#420]
**Describe the bug**
`si.get` for `fsSize` with specific fields is returning an empty result object, but `*` works.

**To Reproduce**
1. used function `si.get`
2. code snippet '....'
```
var si = require('systeminformation');
var valueObject = {
    fsSize: 'fs, mount, use'
};
si.get(valueObject)
    .then(function (data) {
        console.log(data);
    })
    .catch(function (err) {
        console.error(err);
    });
```
3. start app / code
 Run the above code using the node command line.

4. See output/error '....'

**Current Output**
 ```
{ fsSize: {} }
```
**Expected behavior**
 ```
{ 
fsSize: [
 {
     fs: "/dev/sda1",
     mount: ''/mnt/drive1",
     use: 90
 },
 {
     fs: "/dev/sda2",
     mount: ''/mnt/drive2",
     use: 80
 }]
 }
```

**Environment (please complete the following information):**
 - systeminformation package version: `4.27.5`
 - OS:`Ubuntu 18.04.5 LTS`
 - Hardware : `hp probook 4530s`

**Additional context**
N/A

**Comment by sebhildebrandt** [comment]
@appvitals1 will have a look on it this weekend! Thank you for reporting this issue.

**Comment by sebhildebrandt** [comment]
@appvitals1 I see where the problem is. As the results are returned in an array, I need to check this also and limit the scope of returned values also within arrays ... will do it this weekend.

**Comment by sebhildebrandt** [comment]
@appvitals1 fixed. Version 4.27.6 just released.

**Comment by appvitals1** [comment]
Thanks a lot @sebhildebrandt. Awesome work!
