### ISSUE TITLE
Not working in a Virtual Machine (Vbox or Hyper V)

### ISSUE THREAD

**Issue by cojocarule** [sebhildebrandt/systeminformation#421]
Hi I have an electron app that uses si.diskLayout() to retreive system disks information for windows systems.
It works great when the app runs on an physical machine but when ran on a VM it doesn't return anything.  
I tried Querying wmic on the VM and it shows there are disks.

**Comment by sebhildebrandt** [comment]
@cojocarule , thank you for reporting ... As you said, there is an output with wmic, can you post the output of the following:

```
wmic diskdrive get /value
```

and in powershell

```
Get-PhysicalDisk | Format-List
```

Thank you in advance!

**Comment by cojocarule** [comment]
C:\Users\AVCOJOCA>wmic diskdrive get /value


Availability=
BytesPerSector=512
Capabilities={3,4}
CapabilityDescriptions={"Random Access","Supports Writing"}
Caption=Microsoft Virtual Disk
CompressionMethod=
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_DiskDrive
DefaultBlockSize=
Description=Disk drive
DeviceID=\\.\PHYSICALDRIVE0
ErrorCleared=
ErrorDescription=
ErrorMethodology=
FirmwareRevision=1.0
Index=0
InstallDate=
InterfaceType=SCSI
LastErrorCode=
Manufacturer=(Standard disk drives)
MaxBlockSize=
MaxMediaSize=
MediaLoaded=TRUE
MediaType=Fixed hard disk media
MinBlockSize=
Model=Microsoft Virtual Disk
Name=\\.\PHYSICALDRIVE0
NeedsCleaning=
NumberOfMediaSupported=
Partitions=3
PNPDeviceID=SCSI\DISK&amp;VEN_MSFT&amp;PROD_VIRTUAL_DISK\5&amp;321A762E&amp;0&amp;000000
PowerManagementCapabilities=
PowerManagementSupported=
SCSIBus=0
SCSILogicalUnit=0
SCSIPort=0
SCSITargetId=0
SectorsPerTrack=63
SerialNumber=
Signature=
Size=136358691840
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=AVCOJOCA-MACHIN
TotalCylinders=16578
TotalHeads=255
TotalSectors=266325570
TotalTracks=4227390
TracksPerCylinder=255


PS C:\Users\AVCOJOCA> Get-PhysicalDisk | Format-List


ObjectId                         : {1}\\AVCOJOCA-MACHIN\root/Microsoft/Windows/Storage/Providers_v2\SPACES_PhysicalDisk
                                   .ObjectId="{350e3988-0382-11eb-91bb-806e6f6e6963}:PD:{4fe2309f-3eb2-c921-7e63-6012df
                                   4b7f50}"
PassThroughClass                 :
PassThroughIds                   :
PassThroughNamespace             :
PassThroughServer                :
UniqueId                         : 60022480329A88D48FF220D138801030
Description                      :
FriendlyName                     : Msft Virtual Disk
HealthStatus                     : Healthy
Manufacturer                     : Msft
Model                            : Virtual Disk
OperationalDetails               :
OperationalStatus                : OK
PhysicalLocation                 : Integrated : Bus 0 : Device 25587 : Function 17433 : Adapter 0 : Port 0 : Target 0 :
                                    LUN 0
SerialNumber                     :
AdapterSerialNumber              :
AllocatedSize                    : 136365211648
BusType                          : SAS
CannotPoolReason                 : Insufficient Capacity
CanPool                          : False
DeviceId                         : 0
EnclosureNumber                  :
FirmwareVersion                  : 1.0
IsIndicationEnabled              :
IsPartial                        : True
LogicalSectorSize                : 512
MediaType                        : Unspecified
OtherCannotPoolReasonDescription :
PartNumber                       :
PhysicalSectorSize               : 4096
Size                             : 136365211648
SlotNumber                       :
SoftwareVersion                  :
SpindleSpeed                     : 0
StoragePoolUniqueId              :
SupportedUsages                  : {Auto-Select, Manual-Select, Hot Spare, Retired...}
UniqueIdFormat                   : FCPH Name
Usage                            : Auto-Select
VirtualDiskFootprint             : 0
PSComputerName                   :
ClassName                        : MSFT_PhysicalDisk

**Comment by sebhildebrandt** [comment]
@cojocarule thank you so much for your fast response! That will help. I will try to come up with a solution the next days.

**Comment by sebhildebrandt** [comment]
@cojocarule can you try to pull the /lib/filesystem.js directly from GitHub ad text if this makes any difference?

**Comment by cojocarule** [comment]
Cool, Its working now in Hyperv, but still not in Vbox.

Here is the output from Vbox:

C:\Users\adrian>wmic
wmic:root\cli>diskdrive get /value

Availability=
BytesPerSector=512
Capabilities={3,4,10}
CapabilityDescriptions={"Random Access","Supports Writing","SMART Notification"}
Caption=VBOX HARDDISK
CompressionMethod=
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_DiskDrive
DefaultBlockSize=
Description=Disk drive
DeviceID=\\.\PHYSICALDRIVE0
ErrorCleared=
ErrorDescription=
ErrorMethodology=
FirmwareRevision=1.0
Index=0
InstallDate=
InterfaceType=IDE
LastErrorCode=
Manufacturer=(Standard disk drives)
MaxBlockSize=
MaxMediaSize=
MediaLoaded=TRUE
MediaType=Fixed hard disk media
MinBlockSize=
Model=VBOX HARDDISK
Name=\\.\PHYSICALDRIVE0
NeedsCleaning=
NumberOfMediaSupported=
Partitions=3
PNPDeviceID=SCSI\DISK&amp;VEN_VBOX&amp;PROD_HARDDISK\4&amp;2617AEAE&amp;0&amp;000000
PowerManagementCapabilities=
PowerManagementSupported=
SCSIBus=0
SCSILogicalUnit=0
SCSIPort=0
SCSITargetId=0
SectorsPerTrack=63
SerialNumber=VB48714f98-fcbf9ac2
Signature=58649349
Size=53686402560
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=DESKTOP-UIBQVT2
TotalCylinders=6527
TotalHeads=255
TotalSectors=104856255
TotalTracks=1664385
TracksPerCylinder=255



wmic:root\cli>powershell
powershell - Alias not found.
wmic:root\cli>
C:\Users\adrian>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\adrian> get-physicaldisk | format-list


ObjectId                         : {1}\\DESKTOP-UIBQVT2\root/Microsoft/Windows/Storage/Providers_v2\SPACES_PhysicalDisk
                                   .ObjectId="{b5e1c14b-04f2-11eb-af45-806e6f6e6963}:PD:{e4b0fe34-5dd1-d02b-3210-8becc6
                                   9d81e4}"
PassThroughClass                 :
PassThroughIds                   :
PassThroughNamespace             :
PassThroughServer                :
UniqueId                         :      ATAVBOX HARDDISK
Description                      :
FriendlyName                     : VBOX HARDDISK
HealthStatus                     : Healthy
Manufacturer                     :
Model                            : VBOX HARDDISK
OperationalDetails               :
OperationalStatus                : OK
PhysicalLocation                 : Integrated : Bus 0 : Device 13 : Function 0 : Adapter 0 : Port 0
SerialNumber                     : VB48714f98-fcbf9ac2
AdapterSerialNumber              :
AllocatedSize                    : 53686042624
BusType                          : SATA
CannotPoolReason                 : Insufficient Capacity
CanPool                          : False
DeviceId                         : 0
EnclosureNumber                  :
FirmwareVersion                  : 1.0
IsIndicationEnabled              :
IsPartial                        : True
LogicalSectorSize                : 512
MediaType                        : Unspecified
OtherCannotPoolReasonDescription :
PartNumber                       :
PhysicalSectorSize               : 512
Size                             : 53687091200
SlotNumber                       :
SoftwareVersion                  :
SpindleSpeed                     : 0
StoragePoolUniqueId              :
SupportedUsages                  : {Auto-Select, Manual-Select, Hot Spare, Retired...}
UniqueIdFormat                   : Vendor Id
Usage                            : Auto-Select
VirtualDiskFootprint             : 0
PSComputerName                   :
ClassName                        : MSFT_PhysicalDisk

**Comment by sebhildebrandt** [comment]
@cojocarule will check it. Thank you for testing

**Comment by sebhildebrandt** [comment]
@cojocarule ... this is interesting ... I just "mocked" your output (Xbox) in a test and this worked out to be fine ... The point is, in my code on line 1009 I jus check if there is a "size" which is the case. As soon I pass this condition, I push a result which should then be visible. Can you once again recheck it? Otherwise I need to set up a box with windows installed ...

**Comment by sebhildebrandt** [comment]
@cojocarule I just created a new windows installation in VirtualBox and testet `si.diskLayout()` ... this worked fine and `VBOX HARDDISK` was recognised with correct size, name, ... output was correct ... can you recheck it on your side?

**Comment by cojocarule** [comment]
Yes. it works on Vbox too. The issue was in my code I was filtering the array by InterfaceType and was expecting "IDE" when it was in "SATA". Thanks for helping with this and sorry for the confusion.

**Comment by sebhildebrandt** [comment]
@cojocarule No problem! Closing it now.
