### ISSUE TITLE
.cpuCurrentspeed() not returning correct cpu speeds

### ISSUE THREAD

**Issue by iamthe-Wraith** [sebhildebrandt/systeminformation#423]
**Describe the bug**
the `.cpuCurrentspeed()` method is returning the same value for all properties every time it's called. for me, that value was `2.6`.

**To Reproduce**
on a machine matching the environment listed below, run the `.cpuCurrentspeed()` method, and just log the output.

**Environment (please complete the following information):**
 - systeminformation package version: **4.27.6**
 - OS: **MacOS (Catalina version 10.15.6)**
 - Hardware: **MacBook Pro (16-inch, 2019)**

**Comment by sebhildebrandt** [comment]
@iamthe-Wraith unfortunately macOS does not report the current speed correctly. This is only possible with special tools like Intels Power Gadget. If you have any other idea, that would be great. So far, I would close this issue for the moment.

**Comment by florisvannoyen** [comment]
same issue here. but i'm on windows 10. its reporting my base clock for every value. also on all cores.
