### ISSUE TITLE
si.graphics() Chinese garbled code will appear

### ISSUE THREAD

**Issue by linlwss** [sebhildebrandt/systeminformation#427]
si.graphics() 
model
vendor
Chinese garbled code will appear

**Comment by sebhildebrandt** [comment]
@linlwss You have to be much precise ...have a look at the issue template .. there you can see what information you need to provide. See https://github.com/sebhildebrandt/systeminformation/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Thank You

**Comment by bymomo** [comment]
> @linlwss你必须更精确...看看问题模板。在那里你可以看到你需要提供什么信息。参见https://github.com/sebhildebrandt/systeminformation/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
> 
> 谢谢

code:
const systeminfo = require("systeminformation");
systeminfo.osInfo();

run result:
{
    arch: "x64"
    build: "19041"
    codename: ""
    codepage: " 936"
    distro: "Microsoft Windows 10 רҵ��"  //  unidentifiable Chinese code 
    hostname: "DESKTOP-V80RUVR"
    kernel: "10.0.19041"
    logofile: "windows"
    platform: "win32"
    release: "10.0.19041"
    serial: "00331-10000-00001-AA213"
    servicepack: "0.0"
    uefi: false
    version: "Windows 10"
}

expect: distro: "Microsoft Windows 10 专业版"

**Comment by bymomo** [comment]
Win10 Chinese version

**Comment by gaozhenpeng** [comment]
my os is window 10 旗舰版

iconv.decode(Buffer.from(data.distro,'binary'), 'cp936') Chinese garbled

**Comment by sebhildebrandt** [comment]
@gaozhenpeng so your comment is not clear to me ... pleas can you explain?

**Comment by plusor** [comment]
#148

**Comment by sebhildebrandt** [comment]
Closing this as this is a duplicate
