### ISSUE TITLE
fsSize() is too slow

### ISSUE THREAD

**Issue by aleksey-hoffman** [sebhildebrandt/systeminformation#429]
Hey @sebhildebrandt thanks for creating the module!

Have you considered turning it into a native C++ module based on [N-API](https://nodejs.org/api/n-api.html#n_api_n_api) (or creating a separate native NPM module)? It would allow you to make every single function faster and add additional features.

**Describe the bug**
`systeminformation.fsSize()` is ~900 times slower than [node-diskusage](https://github.com/jduncanator/node-diskusage):

- systeminformation: ~90 ms (average)
- node-diskusage: ~0.1 ms (average)

**To Reproduce**

```js
const diskusage = require('diskusage')
const systeminformation = require('systeminformation')

let drives = await systeminformation.blockDevices()

console.time('TIME: systeminformation')
await systeminformation.fsSize()
console.timeEnd('TIME: systeminformation')

for (let index = 0; index < drives.length; index++) {
  console.time('TIME: diskusage')
  const size = await diskusage.check(drives[index].mount)
  console.timeEnd('TIME: diskusage')
}
```
**Current Output**
Current execution time: ~90 ms

**Expected behavior**
Desired execution time: ~0.1 - 1 ms

**Environment (please complete the following information):**
 - systeminformation package version: 4.27.5
 - OS: Win10, x64, latest stable build
 - Hardware: CPU: Intel core i7 7700HQ; DRIVES: 1 SATA SSD, 1 HDD (3 partitions total)

**Comment by sebhildebrandt** [comment]
@aleksey-hoffman ... Thank you for your suggestion, I get your point. Currently I do not have plans to implement parts in C++. I do know, that there is a huge potential especially on windows for a lot of functions. I will keep this in mind for maybe a new major release of `system-information`

**Comment by sebhildebrandt** [comment]
Closing it for now.
