### ISSUE TITLE
hard disk serial number

### ISSUE THREAD

**Issue by JobExpert** [sebhildebrandt/systeminformation#43]
can you add support to hard disk serial number?

in windows the command is -
"wmic diskdrive get serialnumber"

it's different from - 
"wmic logicaldisk get VolumeSerialNumber"

**Comment by sebhildebrandt** [comment]
Sure! Will have a look on it!
Plannig to make a new release Thursday. Try to make this one be part of the update ;-)

**Comment by JobExpert** [comment]
cool :)
can you add support for other OS like linux, mac,...?

**Comment by sebhildebrandt** [comment]
Working on it ... also for Linux and OS X. Hope to get an update ready end of this week.

**Comment by sebhildebrandt** [comment]
I implemented a solution where you can get more detailed physical HDD information (`diskLayout`). Works with Win, OSX, Linux (but not all properties are available on all platforms). Anyway, `serialNum` is available on all three ;-)

**Comment by JobExpert** [comment]
Thanks 👍 🥇 :)
