### ISSUE TITLE
How get the total of disk

### ISSUE THREAD

**Issue by leermao** [sebhildebrandt/systeminformation#430]
I only have 256 gigabytes of disk space on my mac 
![image](https://user-images.githubusercontent.com/11629887/97257117-ee094500-184f-11eb-946d-dcad670dc90a.png)

But I don't understand why each size is 256 when use fsSize():

![image](https://user-images.githubusercontent.com/11629887/97257166-15f8a880-1850-11eb-8557-4811e8d49676.png)

So, How do I get real disk when use the lib

**Comment by sebhildebrandt** [comment]
Hi @leermao this is interesting. Can you provide the output to the following command on your machine (command line):
... and provide the output as text (then I can use it as a mock input)

```
df -lkP
```

Thank you in advance

**Comment by leermao** [comment]
Thank you for your reply

It looks like the same as this library result
```
Filesystem   1024-blocks      Used Available Capacity  Mounted on
/dev/disk1s5   244912536  11011588  56842428    17%    /
/dev/disk1s1   244912536 173688180  56842428    76%    /System/Volumes/Data
/dev/disk1s4   244912536   2098240  56842428     4%    /private/var/vm
/dev/disk1s3   244912536   1015016  56842428     2%    /Volumes/Recovery
```

OK, The output that `disLayout()` is what I want
```
diskLayout: [
    {
      device: 'disk0',
      type: 'SSD',
      name: 'APPLE SSD SM0256G',
      vendor: '',
      size: 251000193024,
      bytesPerSector: -1,
      totalCylinders: -1,
      totalHeads: -1,
      totalSectors: -1,
      totalTracks: -1,
      tracksPerCylinder: -1,
      sectorsPerTrack: -1,
      firmwareRevision: 'BXZ13A0Q',
      serialNum: 'S2Z5NY1H853844',
      interfaceType: 'PCI',
      smartStatus: 'Ok'
    }
  ],
```
but This result of `diskLayout` only disk0 one when I mount other disk (eg NFS). The NFS Info appear in the `fsSize `

![image](https://user-images.githubusercontent.com/11629887/97264698-67a92f00-1860-11eb-8aaf-610721783f38.png)

I want get the result is `mount` plus `diskLayout` instead of  only `diskLayout`

Looking forward to your reply， Thank you.

**Comment by sebhildebrandt** [comment]
@leermao so first to `fsSize()`: here we have different file systems mounted which are on the same disk. As there is no limit how big a mounted filesystem is allowed to be on this disk, `df` shows the full size of the underlying disk. So that is I guess from this perspective fine.

`diskLayout()`: now shows the physical layouts of the physical disks - including the mounted physical disks, which in your case seems to be also OK. 

What is missing is to be able to see / distinguish non physical mounted volumes on `mac os`, right? This would be only be visible in `df` Your last screenshot: is this also done on a `mac os` or is it from a Linux machine? So if this is a linux output, here you see all mounted volumes, but in `mac os` this is not the case. Is this, what you are looking for? Maybe I did not get your question right ...

**Comment by leermao** [comment]
> What is missing is to be able to see / distinguish non physical mounted volumes on `mac os`, right?
Yes this's what I mean
 
Sorry. Maybe I didn't describe my problem well. Because this problem didn't happen on my computer.

The main purpose of this issue is to obtain the total disk in MAC OS Linux or Docker and Windows

So here's reason what happens:

The physical disk of that computer is 1T. But mount a non-physical disk of 20T. So If I use the `diskLayout` to calculate the total of disk is only 1T (Because the physical disk is 1T). If I use `fsSize` to calculate the total of disk is more 21T (bacause `my top question`).


So I dont know how do get the total of disk when both physical and non-physical disk exist on `mac os`
The result of disk is right on Linux machine or docker by add the size together use `fsSize` except `mac os`

Thank you in advance

**Comment by sebhildebrandt** [comment]
@leermao OK, will come up with a fix for `mac os` later this week. I already have an idea ;-)

**Comment by leermao** [comment]
> @leermao OK, will come up with a fix for `mac os` later this week. I already have an idea ;-)

Thank you very much.

**Comment by leermao** [comment]
@sebhildebrandt Hi Bro. Can the problem be fixed this week?

**Comment by sebhildebrandt** [comment]
@leermao of course. I had a problem with my laptop last week and got stuck ... will try to do it tomorrow.

**Comment by leermao** [comment]
> @leermao of course. I had a problem with my laptop last week and got stuck ... will try to do it tomorrow.

OK Thank You

**Comment by sebhildebrandt** [comment]
@leermao I was not able to reach the office today due to the current situation here in Vienna ... will try to do it tomorrow. Sorry for the delay.

**Comment by leermao** [comment]
@sebhildebrandt  no problem my bro. the problem be fixed this week is ok. thanks you in advance

**Comment by sebhildebrandt** [comment]
@leermao I just implemented a version that should now detect NFS drives on Mac. Can you test it on your side? Version 4.28.0 just released.

**Comment by leermao** [comment]
ok thank u

**Comment by leermao** [comment]
can u show me your demo? I already dont know how to use when mount NFS on `mac os`

**Comment by sebhildebrandt** [comment]
Just use it exactly the same was as before ...

```
const si = require('systeminformation');
si.fsSize().then(data => console.log(data));
```

So if you have a NFS share mounted (via `sshfs`), the output would now also show this mounted file system:

```
[
  ...,
  {
    fs: 'user@192.168.0.243:/',
    type: 'NFS',
    size: 972577361920,
    used: 117608034304,
    use: 12.09,
    mount: '/Users/...mount_path...'
  }
]
```

You can now distinguish this mounted filesystem by type:`NFS` for mounted network file systems. Does this make sense for you? If this still is not what you expect, please post one more time the output of the following command on your mac OS device: (as text):

```
df -kP
```

Thank you in advance.

**Comment by leermao** [comment]
you mean the total of disk is `diskLayout()` + type `NFS` of `fsSize()` on	`mac os` ?

**Comment by sebhildebrandt** [comment]
@leermao ... here we need to me more clear, what you get from which function:

- `diskLayout()` will always provide hardware information, so only the true physical disks in your machine.
- `fsSize()` will give you the mounted file systems ... NFS are only seen as mounted file systems, not as partitions / disks. 

So if you need to calculate the overall disk space, you need to get the physical sizes from `diskLayout()` and then you can add the sizes from `fsSize()` with type `NFS`. Hope this makes it more clear. 

If your situation is different, then I still did not understand properly what the purpose is. Then I would be happy if you exactly describe it including output of `df -kP`.
