### ISSUE TITLE
services with spaces in name not accessible

### ISSUE THREAD

**Issue by pcnate** [sebhildebrandt/systeminformation#432]
**Describe the bug**
Services c

**To Reproduce**
```javascript
const si = require( 'systeminformation' );

si.services("KpyM Telnet SSH Server v1.19c")
  .then( data => { console.log( data ) } )
  .catch( error => { console.log( error ) } )
```

**Current Output**
```json
[
  {
    "name": "kpym",
    "running": false,
    "startmode": "",
    "pids": [],
    "pcpu": 0,
    "pmem": 0
  },
  {
    "name": "telnet",
    "running": false,
    "startmode": "",
    "pids": [],
    "pcpu": 0,
    "pmem": 0
  },
  {
    "name": "ssh",
    "running": false,
    "startmode": "",
    "pids": [],
    "pcpu": 0,
    "pmem": 0
  },
  {
    "name": "server",
    "running": false,
    "startmode": "",
    "pids": [],
    "pcpu": 0,
    "pmem": 0
  },
  {
    "name": "v1.19c",
    "running": false,
    "startmode": "",
    "pids": [],
    "pcpu": 0,
    "pmem": 0
  }
]
```

**Expected behavior**
Would expect some way to force service name to allow string whether it be escaping the spaces or setting a flag

**Environment (please complete the following information):**
 - systeminformation package version: 4.27.9
 - OS: Microsoft Windows 10 Pro - 10.0.19041

**Additional context**

**Comment by sebhildebrandt** [comment]
@pcnate  Just to be sure: if you type 

```
wmic service get /value 
```

and locate your `KpyM Telnet SSH Server v1.19c` service ... 

can you private the block of this certain service?
Thank you in advance

**Comment by pcnate** [comment]
Here you are

```
AcceptPause=FALSE
AcceptStop=TRUE
Caption=KpyM Telnet SSH Server v1.19c
CheckPoint=0
CreationClassName=Win32_Service
DelayedAutoStart=FALSE
Description=Free open source TELNET-SSH server for Windows.
DesktopInteract=FALSE
DisplayName=KpyM Telnet SSH Server v1.19c
ErrorControl=Ignore
ExitCode=0
InstallDate=
Name=KpyM Telnet SSH Server v1.19c
PathName="C:\Program Files (x86)\KTS\daemon.exe"
ProcessId=6976
ServiceSpecificExitCode=0
ServiceType=Own Process
Started=TRUE
StartMode=Auto
StartName=LocalSystem
State=Running
Status=OK
SystemCreationClassName=Win32_ComputerSystem
SystemName=Server001
TagId=0
WaitHint=0

```

**Comment by sebhildebrandt** [comment]
@pcnate thank you pcnate. Yes you are right, this is how it is done. And this is also how I described it in the documentation. On Windows, I think I can change this. Will come back with a fix later this week.

**Comment by sebhildebrandt** [comment]
@pcnate I just made a code correction here on gut hub. If you download just the file `lib/processes.js` and test it on your side, that would be great. If this works, I will publish It to NPM. Thank you in advance.

**Comment by sebhildebrandt** [comment]
@pcnate Did you had the time to test it on your side?

**Comment by diegoecamacho** [comment]
@sebhildebrandt I was running into this same issue last week, just tried it on my end with the new processes.js file and it worked as expected, thank's for the quick fix, would like to see this on NPM as soon as you can.

**Comment by pcnate** [comment]
sorry for the delay. I just tested this. I pulled from npm as I noticed that other changes were pushed to npm which included this update

**Comment by sebhildebrandt** [comment]
@diegoecamacho as @pcnate said, this is already published ;-)
