### ISSUE TITLE
debug information shown

### ISSUE THREAD

**Issue by BCsabaEngine** [sebhildebrandt/systeminformation#433]
**Describe the bug**
After update to new release, console output contains uneccessary (maybe debug) informations

**To Reproduce**
1. used function 'filesystem.fsSize()

**Current Output**
['/dev/root', 'ext4', ....]

**Expected behavior**
Hide this debug infos.

**Additional context**
filesystem.js line 46

**Comment by sebhildebrandt** [comment]
@BCsabaEngine sorry, my fault, forgot to remove it. Will do it in the Morning. Thank you

**Comment by sebhildebrandt** [comment]
@BCsabaEngine done ... sorry again. Version 4.28.1 just published

**Comment by BCsabaEngine** [comment]
You don't have to apologize, it's in the deck. Thank you for your sacrificial (and quick) work!
