### ISSUE TITLE
Add remote connection detection

### ISSUE THREAD

**Issue by DanielMcAssey** [sebhildebrandt/systeminformation#434]
**Is your feature request related to a problem? Please describe.**
Sometimes people use our apps in a remote environment through a remote session (e.g. RDP). We would like to detect and warn users when they do.

**Describe the solution you'd like**
Simply a flag to detect if you are running the application in a remote session.

**Describe alternatives you've considered**
None

**Additional context**
Windows provides this flag using GetSystemMetric syscall with SM_REMOTESESSION.
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics
Flag: SM_REMOTESESSION

**Comment by sebhildebrandt** [comment]
@DanielMcAssey as far as I have seen in my investigation, this is only possible by writing an C++ extension. I currently do not plan to do that, this would a more complex installing process for some users. Fo Linux machines I found an easy solution but not for windows. If you have further suggestions, please post it here.

**Comment by AdrianoCahete** [comment]
Maybe a Powershell solution?

https://stackoverflow.com/a/28678312/1032384

**Comment by sebhildebrandt** [comment]
@DanielMcAssey @AdrianoCahete ... just added this to `osInfo()`. Version 5.3.0 just released.
