### ISSUE TITLE
Can this library support the fsSize with type is `NAS` ??? 

### ISSUE THREAD

**Issue by leermao** [sebhildebrandt/systeminformation#435]
https://github.com/sebhildebrandt/systeminformation/issues/430

now the lib support the fsSize with type is `NFS` and this is perfect to show disk on my mac. thank you again.
so I suggest you can support it that the fsSize with type is `NAS`.  it is more perfect .

**Comment by sebhildebrandt** [comment]
@leermao `NAS` would translate to Network Attached Storage, while `NFS` is Network File System ... the later is I think more appropriate in the context of `fsSize()` which is about file systems. 

For now, I would rather leave this like that. Do we have another space within the library where I return 'NAS'??
