### ISSUE TITLE
Dome document enhancement on ValueObject:  only retrieve the mount:'/' from fsSize

### ISSUE THREAD

**Issue by GerritKuilder** [sebhildebrandt/systeminformation#440]
**Is your feature request related to a problem? Please describe.**
I am trying to pull all information of a system by defining a ValuObject

**Describe the solution you'd like**
I am sure this must be possible: only retrieve the mount:'/' from fsSize
but an example will be most helpful
**Describe alternatives you've considered**
Document enhancement of providing examples of being able to refine the ValuObject so that only 1 call is needed

**Additional context**
I have been cobbling together bits and pieces together from different modules but getting everything at once is preferred.
The documentation is very good but I am only missing the above.

Kind Regards,

Gerrit Kuilder

**Comment by sebhildebrandt** [comment]
@GerritKuilder this is currently not possible. The `ValueObject`lets you define the keys you want to get back for a specific function but if the result is an array, you currently cannot define a filter for the returning array. I will think of how I can include this to the `get()` function. And of course then I will also extend the documentation how this can be done. Will come back later with a solution.

**Comment by sebhildebrandt** [comment]
@GerritKuilder Version 5.0 just released!
Now you have the possibility to also filter results sets in the get function. Here you should find the documentation 
https://systeminformation.io/general.html in the lower section.

Be aware: Version 5 is NOT fully backwards compatible to version 5 ... see https://systeminformation.io/changes.html to get an overview over all breaking changes.
