### ISSUE TITLE
Empty output using si.system()

### ISSUE THREAD

**Issue by dajpes** [sebhildebrandt/systeminformation#442]
Hi everybody,

First time using this amazing package. The problem I got is that I get a completly empty value if I do si.system(), I don't know if this is a feature or just some random bug.

I'm using systeminformation package in both node 10 and 15 and error still remains.

This is my code where I run it:

```javascript
//Even If I do an async/await function the empty result still remains
const si = require('systeminformation');
si.system().then(data => console.log(data));

```
And this is the output:

```Javascript
{
  manufacturer: '',
  model: 'Virtual machine',
  version: '',
  serial: '-',
  uuid: '',
  sku: '-'
}

```

I'm not using a virtual machine, I'm just using a normal desktop pc, here are my specs: Athon 3000g, 16Gb Ram DDr4, 500Gb samsung ssd with a Linux Mint 20 Ulyana with Kernel 5.4.0-26-generic.
.

The only way I can get my pc serial, manufacturer and everything else is if I do a sudo command like the following:

If I do a sudo dmicode -t system

![image](https://user-images.githubusercontent.com/11248816/99587386-084dc300-29b7-11eb-8e2b-e99b7818b2c2.png)

**Comment by rosen-vladimirov** [comment]
Hey, 
Same is happening on my side with Ubuntu 20.04 LTS - the dmidecode command (and all the rest commands that are used to get the information) require sudo, so the output of the systeminformation call is:
```
{
  manufacturer: 'LENOVO',
  model: '80RU',
  version: 'Lenovo ideapad 700-15ISK',
  serial: '-',
  uuid: '',
  sku: '-'
}
```

**Comment by sebhildebrandt** [comment]
@rosen-vladimirov , @dajpes can you both post the output (as text please) of 

```
dmidecode -t system
```

as well as 

```
sudo dmidecode -t system
```

and to @dajpes can you also do the following:

```
dmesg | grep -i virtual | grep -iE "vmware|qemu|kvm|xen
```

That would help to identify the problem. One more question to both: are you running your code with admin rights?

Regards

**Comment by rosen-vladimirov** [comment]
Hey @sebhildebrandt , 
Thanks for the prompt response. My code is not running with admin rights.
Here's the output of the requested commands:
```
vladimirov@vladimirov:~$ dmidecode -t system
# dmidecode 3.2
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
Scanning /dev/mem for entry point.
/dev/mem: Permission denied


vladimirov@vladimirov:~$ sudo dmidecode -t system
[sudo] password for vladimirov: 
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x002A, DMI type 12, 5 bytes
System Configuration Options

Handle 0x002D, DMI type 32, 11 bytes
System Boot Information
	Status: No errors detected

Handle 0x000E, DMI type 1, 27 bytes
System Information
	Manufacturer: LENOVO
	Product Name: 80RU
	Version: Lenovo ideapad 700-15ISK
	Serial Number: R90LQWS2
	UUID: 6ff67847-867a-11e6-88b3-84ef183c3d8f
	Wake-up Type: Power Switch
	SKU Number: LENOVO_MT_80RU_BU_idea_FM_Lenovo ideapad 700-15ISK
	Family: IDEAPAD

Handle 0x0038, DMI type 15, 31 bytes
System Event Log
	Area Length: 18 bytes
	Header Start Offset: 0x0000
	Header Length: 16 bytes
	Data Start Offset: 0x0010
	Access Method: General-purpose non-volatile data functions
	Access Address: 0x00F0
	Status: Valid, Not Full
	Change Token: 0x00000000
	Header Format: Type 1
	Supported Log Type Descriptors: 4
	Descriptor 1: POST error
	Data Format 1: POST results bitmap
	Descriptor 2: PCI system error
	Data Format 2: None
	Descriptor 3: System reconfigured
	Data Format 3: None
	Descriptor 4: Log area reset/cleared
	Data Format 4: None
```

**Comment by dajpes** [comment]
hi @sebhildebrandt ,

What do you mean by running the code with admin right? in  the case of the systemInformation package I just install it using npm and then with node running node myFile.js

Here is the output of:

```dmidecode -t system```

![image](https://user-images.githubusercontent.com/11248816/100024310-809bf600-2db4-11eb-95c5-86aa15e97816.png)


``` sudo dmidecode -t system```

![image](https://user-images.githubusercontent.com/11248816/100024354-96112000-2db4-11eb-84fb-69dd1e7cba83.png)

```dmesg | grep -i virtual | grep -iE "vmware|qemu|kvm|xen```
![image](https://user-images.githubusercontent.com/11248816/100024411-b345ee80-2db4-11eb-92b7-1267b77982d1.png)

**Comment by rosen-vladimirov** [comment]
Hey @sebhildebrandt ,
Is there something we can do to help with this issue? I'm ready to test any code that you have or even if you have an idea how to implement it, I may try do work on it. 
Ping me in case I can help in some way.

Thanks for the amazing package and all of your work!

**Comment by sebhildebrandt** [comment]
@rosen-vladimirov sorry, I had to solve a security issue. Need to work on this issue now later this week. And yes, as soon as I need help testing it, I would reach out and contact you again. Thank you.

**Comment by sebhildebrandt** [comment]
@rosen-vladimirov @dajpes can you both do me one more favor:

can you try to run the following commands:

```
cd /sys/devices/virtual/dmi/id/
ls -lsa

cat product_{name,serial,uuid,version}
cat sys_vendor
```

These are the failover commands that I run, if `dmidecode -t system` does not return any useful information. Pleas post the results as TEXT, not as screenshots. Thank you again.

**Comment by dajpes** [comment]
Hi @rosen-vladimirov I did as you said and here are the results:

The first two commands:

![image](https://user-images.githubusercontent.com/11248816/100676514-0d0b6300-3337-11eb-97f6-de3695e40a9e.png)


The others commands:

![image](https://user-images.githubusercontent.com/11248816/100676546-1bf21580-3337-11eb-9b14-9fc0b56f9a9b.png)

**Comment by rosen-vladimirov** [comment]
Hey @sebhildebrandt , here's the required output:
```
vladimirov@vladimirov:~$ cd /sys/devices/virtual/dmi/id/
vladimirov@vladimirov:/sys/devices/virtual/dmi/id$ ls -lsa
total 0
0 drwxr-xr-x 3 root root    0 дек  1  2020 .
0 drwxr-xr-x 3 root root    0 дек  1  2020 ..
0 -r--r--r-- 1 root root 4096 дек  1 07:56 bios_date
0 -r--r--r-- 1 root root 4096 дек  1  2020 bios_vendor
0 -r--r--r-- 1 root root 4096 дек  1 07:56 bios_version
0 -r--r--r-- 1 root root 4096 дек  1 07:56 board_asset_tag
0 -r--r--r-- 1 root root 4096 дек  1 07:56 board_name
0 -r-------- 1 root root 4096 дек  1 07:56 board_serial
0 -r--r--r-- 1 root root 4096 дек  1  2020 board_vendor
0 -r--r--r-- 1 root root 4096 дек  1 07:56 board_version
0 -r--r--r-- 1 root root 4096 дек  1 07:56 chassis_asset_tag
0 -r-------- 1 root root 4096 дек  1 07:56 chassis_serial
0 -r--r--r-- 1 root root 4096 дек  1  2020 chassis_type
0 -r--r--r-- 1 root root 4096 дек  1 07:56 chassis_vendor
0 -r--r--r-- 1 root root 4096 дек  1 07:56 chassis_version
0 -r--r--r-- 1 root root 4096 дек  1  2020 modalias
0 drwxr-xr-x 2 root root    0 дек  1 07:56 power
0 -r--r--r-- 1 root root 4096 дек  1 07:56 product_family
0 -r--r--r-- 1 root root 4096 дек  1  2020 product_name
0 -r-------- 1 root root 4096 дек  1 07:56 product_serial
0 -r--r--r-- 1 root root 4096 дек  1 07:56 product_sku
0 -r-------- 1 root root 4096 дек  1  2020 product_uuid
0 -r--r--r-- 1 root root 4096 дек  1  2020 product_version
0 lrwxrwxrwx 1 root root    0 дек  1  2020 subsystem -> ../../../../class/dmi
0 -r--r--r-- 1 root root 4096 дек  1  2020 sys_vendor
0 -rw-r--r-- 1 root root 4096 дек  1  2020 uevent
vladimirov@vladimirov:/sys/devices/virtual/dmi/id$ cat product_{name,serial,uuid,version}
80RU
cat: product_serial: Permission denied
cat: product_uuid: Permission denied
Lenovo ideapad 700-15ISK
vladimirov@vladimirov:/sys/devices/virtual/dmi/id$ cat sys_vendor
LENOVO
vladimirov@vladimirov:/sys/devices/virtual/dmi/id$ 
```

**Comment by sebhildebrandt** [comment]
@rosen-vladimirov @dajpes ... As we see: as long as you run your code as a non privileged user, linux is quite restrictive getting those information. In some cases the fallback commands where successful but here we also see that you do not get any useful information. So the problem is not really related to `systemInformation` package, more to linux restrictions. I would here close this issue ... If you have any idea to retrieve the wanted information, please let me know. I would be happy to implement it.

**Comment by rosen-vladimirov** [comment]
Hey @sebhildebrandt , thanks for investigating this case and the explanation, really appreciate it!
