### ISSUE TITLE
Latest update broke cordova

### ISSUE THREAD

**Issue by RianFuro** [sebhildebrandt/systeminformation#443]
**Describe the bug**
I know this might not directly your fault or problem, but I wanted to notify you that the last update to your npm package broke [apache/cordova-cli](https://github.com/apache/cordova-cli) (and probably other packages depending on this one), because of these additions:

https://github.com/sebhildebrandt/systeminformation/blob/bd5b8abab6545706b7edfbb675a77fa51a07e907/lib/index.js#L24-L25

You probably shouldn't do this, as you share the object prototype with everyone in a project and people might be setting methods with used names on their objects. In cordova's case they depend on https://github.com/kriskowal/q which sets a method `valueOf` on their objects, overriding the prototype.

**To Reproduce**

1. `npm i -g cordova`
2. `cordova create test`
3. `cd test`
4. `cordova platform add android`

**Current Output**
```
TypeError: Cannot assign to read only property 'valueOf' of object '[object Object]'
    at Function.defer (/home/<snip>/.local/share/npm/lib/node_modules/cordova/node_modules/q/q.js:577:21)
    at Object.exports.spawn (/home/<snip>/.local/share/npm/lib/node_modules/cordova/node_modules/cordova-common/src/superspawn.js:64:17)
    at /home/<snip>/.local/share/npm/lib/node_modules/cordova/node_modules/cordova-fetch/index.js:177:31
```

**Expected behavior**
Successfully executes command

**Comment by sebhildebrandt** [comment]
@RianFuro I had the feeling, that this has some side-effects ... will revert it today ... Was in contact with some security advisors and this was their suggestion ... :-(

**Comment by RianFuro** [comment]
Hm. Without being an expert myself, I suppose that's a plausible suggestion if you're in total control of your environment. However when you're developing a package for others to use, you never will be. Heck, you can't even really be sure _when_ your code will be sourced, so a malicious actor could simply modify the prototype before you freeze it.

**Comment by sebhildebrandt** [comment]
@RianFuro ... exactly, that was my feeling. So I now reverted this, Version 4.30.4 just published. Will need to have a look, what possibility I have to manage this.

**Comment by raphinesse** [comment]
Thanks a lot for the quick response time @sebhildebrandt! :bowing_man:

**Comment by sebhildebrandt** [comment]
@raphinesse you are always welcome... really sorry about the inconvenience ...
