### ISSUE TITLE
CPU temperature is incorrect on Linux

### ISSUE THREAD

**Issue by GitSquared** [sebhildebrandt/systeminformation#444]
**Describe the bug**
CPU temperature reporting does not work on some Linux systems due to the library not looking in the correct sysfs devices.

**To Reproduce**
Use `systeminformation.cpuTemperature` on affected Linux systems.

**Current Output**
```
❯ node -e "require('systeminformation').cpuTemperature(t => console.log(t))"
{ main: 35.9, cores: [], max: 35.9 }
```

**Expected behavior**
See actual CPU temperature, for instance on my system it was ~20° hotter than sysinf reported.
```
❯ cat /sys/class/hwmon/hwmon3/temp3_label; cat /sys/class/hwmon/hwmon3/temp3_input
Core 1
54000
```

**Environment (please complete the following information):**
 - systeminformation package version: `v4.30.4`
 - OS: `Linux 5.9.10-arch1-1 x86_64`
 - Hardware: Dell XPS 15 7590

**Additional context**
Sysinf expects to see the core temperatures on the `hwmon1` sysfs device.
https://github.com/sebhildebrandt/systeminformation/blob/7b4693505872b273a87353b339c4b1d6219c4d69/lib/cpu.js#L775

On my device the temps are located at `hwmon3` - and I believe the order of hwmon devices is not fixed even from one reboot to another anyway:
```
❯ cat /sys/class/hwmon/hwmon3/temp*_label
Package id 0
Core 0
Core 1
Core 2
Core 3
Core 4
Core 5
```

**Comment by sebhildebrandt** [comment]
@GitSquared Thank you! Well tags something I can work on. Not a big deal ... will try to come up with a solution! Currently have to fix a security issue in System Information which for me has a little higher priority ;-) Hope to have a fix for this issue this weekend.

**Comment by GitSquared** [comment]
Sure, no rush ;)

Off-topic, but I'm curious about that sec issue, is it sufficiently severe to warrant a delay in downstream releases? I'm about to push a big release and don't want to have to patch it in 2 days because of a CVE.

**Comment by sebhildebrandt** [comment]
@GitSquared So there is a potential possibility to hack some code due to property pollution. I did a first fix which prevents this certain section but I want to make it more stable. I want to fix that tomorrow evening. Will give you an update on the status. You also can then review the security advisory here on GitHub.

**Comment by GitSquared** [comment]
Gotcha, thanks for keeping me in the loop.

**Comment by sebhildebrandt** [comment]
@GitSquared Hi again, I now have a possible solution for that. I did not yet released a new version. Would it be possible to test it on your side obtaining the latest version of the `lib/cpu.js` file from GitHub? Here I am trying to get hwmon0 - hwmon3 data and determine which might be the best ... Please let me know if this works for you as I cannot really test it.

**Comment by GitSquared** [comment]
Hi Seb! This solution works for me but I wonder if we could perhaps use a more versatile bash one-liner rather than simply extending the search to the first 3 `hwmon`s.

One thing I've noticed is that not all devices have both a `tempX_label` and a `tempX_input`... We can use that to know which devices to skip and which are more likely to be core temps.

```bash
#!/bin/bash

# Loop over all hwmon devices (rarely more than 10)
for mon in /sys/class/hwmon/hwmon*; do
	# Loop over all temperatures label
	for label in "$mon"/temp*_label; do
		# If no label has been found bash will try using "temp*_label" as a filename,
		# so this file existence check prevents looping over that
		if [ -f $label ]; then
			# Get the "base" sensor name, without the _label suffix
			base=$(echo $label | rev | cut -c 7- | rev)
			# Use it to build the path to the actual sensor value
			value="$base"_input
			# And if it exists...
			if [ -f "$value" ]; then
				# Print out the sensor's label and current value.
				echo $(cat "$label")
				echo $(cat "$value")
			fi
		fi
	done
done
```

One-liner: 
```bash
for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=$(echo $label | rev | cut -c 7- | rev)_input; if [ -f "$value" ]; then echo $(cat "$label"); echo $(cat "$value"); fi; fi; done; done
```

Sample output on my system:
```
systeminformation on  master [?] is 📦 v4.30.6 via ⬢ v14.15.1 
❯ ./test.sh
Composite
34850
Sensor 1
34850
Package id 0
56000
Core 0
54000
Core 1
55000
Core 2
55000
Core 3
55000
Core 4
56000
Core 5
55000
```

Seems like this should be easy enough to parse, right?

I can submit a PR if you want.

**Comment by sebhildebrandt** [comment]
@GitSquared wow. No need to push a pull request. Will work on it later tomorrow.

**Comment by sebhildebrandt** [comment]
@GitSquared version 4.30.7 just published. Thank you for your awesome idea! If you have further ideas for this module, do not hesitate to contact me. Best regards.

**Comment by GitSquared** [comment]
Thank you!
