### ISSUE TITLE
CPU temperature return -1

### ISSUE THREAD

**Issue by Filaind** [sebhildebrandt/systeminformation#445]
**Describe the bug**
cpuTemperature not return correct temp

**To Reproduce**

> const si = require('systeminformation')
> var temperature = await si.cpuTemperature();
> console.info(temperature);

**Current Output**
`{main: -1, cores: []), max: -1}`

**Expected behavior**
`{main: 40, cores: []), max: 50}`

**Environment (please complete the following information):**
 - systeminformation package version: 4.30.5
 - OS: Windows 10
 - CPU: Ryzen 9 3900x

**Comment by sebhildebrandt** [comment]
@Filaind 

1. did you checked the **Known Issues** section here: https://systeminformation.io/cpu.html
2. what results you get when running `wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature`?

Regards Sebastian

**Comment by sebhildebrandt** [comment]
@Filaind ... did you received my comment?

**Comment by sebhildebrandt** [comment]
Closing it for now. Seems to be covered by remarks in the **Known Issues**
