### ISSUE TITLE
 multiple compilation environments

### ISSUE THREAD

**Issue by lykl** [sebhildebrandt/systeminformation#446]
**Describe the bug**
Well,I think this plugin is used some variables from `process.env`，but when I try to set up multiple compilation environments like create a file `.env.test` , there is something wrong. 
I set:
```
chainWebpackMainProcess: config => {
     const prefixRE = /^VUE_APP_/
     const resolveClientEnv = () => {
     const env = {}
     Object.keys(process.env).forEach(key => {
        if (prefixRE.test(key) || key === 'NODE_ENV') {
           env[key] = process.env[key]
        }
     })
      for (const key in env) {
         env[key] = JSON.stringify(env[key])
      }
      return {
          'process.env': env
       }
     }
     config.plugin('define').use(require('webpack/lib/DefinePlugin'), [
          resolveClientEnv()
     ])
     return config
}
```
in my ` vue.config.js`,so I can use the `process.env` in renderProcess currently.
But unfortunately,I find the `disklayout` return an empty array. When I remove the above code,It can return the current array.
How can I fix this problem?

```
{
   "vue-cli-plugin-electron-builder": "^2.0.0-rc.4"
}
```

**Comment by sebhildebrandt** [comment]
@lykl having a look into my code ... can it be that you are running it on windows? Well there I am using the `process.env` to detect windows install path (and location of WMIC) ... I can change this the way that if there is no `process.env.WINDIR`, I default `c:\\windows` ...

**Comment by lykl** [comment]
yes,I run it on win 10

**Comment by sebhildebrandt** [comment]
@lykl OK, then I just added a default setting for the `wmic` windows path. Version 4.30.6 just released. Can you try it on your side?

**Comment by lykl** [comment]
thank you,I will try it on monday

**Comment by lykl** [comment]
It's working,thank you
