### ISSUE TITLE
Command failed: diskutil list Unable to run ...

### ISSUE THREAD

**Issue by Apollon77** [sebhildebrandt/systeminformation#449]
I have another Sentry crash report...

https://sentry.iobroker.net/share/issue/365735ec7d9448b287d0558bf2140eab/

```
Error: Command failed: diskutil list
Unable to run because unable to use the DiskManagement framework.
Common reasons include, but are not limited to, the DiskArbitration
framework being unavailable due to being booted in single-user mode.

  File "child_process.js", line 635, col 11, in checkExecSyncError
  File "child_process.js", line 671, col 15, in execSync
  File "/usr/local/iobroker/node_modules/iobroker.info/node_modules/systeminformation/lib/filesystem.js", line 87, col 24, in null.<anonymous>
    macOsDisks = execSync('diskutil list').toString().split('\n').filter(line => {
  File "internal/process/task_queues.js", line 79, col 11, in processTicksAndRejections
```

**Comment by sebhildebrandt** [comment]
@Apollon77 just released a new version 4.30.8 where I catch this error. Would be interesting to know on which machine this was running. It seems to be macOS but I would be happy to get more details.

**Comment by Apollon77** [comment]
Hey, from the collected data I see "darwin" (so macOS) with nodejs v12.19.1 ... mor I also do not have

**Comment by Apollon77** [comment]
Thank you for your fast fix

**Comment by sebhildebrandt** [comment]
@Apollon77 yes this was almost clear. I just wondered if this is on a new M1 apple silicon machine ;-) I do not yet have the new hardware here to test and adapt it but this is one of the projects for the upcoming weeks.

**Comment by Apollon77** [comment]
good luck ... :-)
