### ISSUE TITLE
Unable to parse Apple Silicon M1

### ISSUE THREAD

**Issue by kenny-y** [sebhildebrandt/systeminformation#450]
Failed to parse string since the `modelline` is `Apple processor`

```
........./node_modules/systeminformation/lib/cpu.js:418
          result.speed = modelline.split('@')[1].trim();
                                                ^

TypeError: Cannot read property 'trim' of undefined
    at / ......... /node_modules/systeminformation/lib/cpu.js:418:49
    at ChildProcess.exithandler (node:child_process:300:7)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Socket.<anonymous> (node:internal/child_process:441:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:661:12)

```

**Comment by sebhildebrandt** [comment]
@kenny-y I still wait for my M1 silicon hardware to arrive here ;-) ... will then extensively work on making System Information fully compatible with Apple ARM processors! Thank you for reporting. As you already done ... if you discover more issues please add "Apple Silicon M1" to the title. Thank you in advance.

**Comment by kenny-y** [comment]
I manually append '@0GHz` to the string as a quick hack and all the rest works (at least no exceptions thrown). I'll report more if I hit any issues.

**Comment by kenny-y** [comment]
BTW. I'm using ARM64 Node.js v15 compiled by this link: https://www.reddit.com/r/apple/comments/jyfg4m/nodejs_running_native_on_apple_silicon_m1_mac_mini/

**Comment by sebhildebrandt** [comment]
@kenny-y good to know! This is what I am also aiming for! 

Concerning this issue, I now added some code to catch this correctly (not yet published) but of course there is much more to do then as soon as I have the hardware here. Thank you for your support!

**Comment by sebhildebrandt** [comment]
@kenny-y: This part of the code Is now released. Version 4.03.11 just published. Leaving this open while waiting for Apple silicon hardware.

**Comment by sebhildebrandt** [comment]
@kenny-y - I just opened a new pinned issue to track complete Apple silicon compatibility: #453 

As I will get the new hardware the next few days I there will report all findings.

**Comment by sebhildebrandt** [comment]
Apple M1 compatibility mostly down. Version 4.33.0 just published.
