### ISSUE TITLE
fqdn

### ISSUE THREAD

**Issue by celevra** [sebhildebrandt/systeminformation#452]
Hi,

is there a way to get the fqdn instead of only the hostname?

regards

celevra

**Comment by sebhildebrandt** [comment]
Hi, @celevra, some questions  

- what OS you are running
- what exactly would you expect
- can you give a specific example

Regards

**Comment by celevra** [comment]
Hi,

i'm running osx, windows and linux
i except that i get through os() not only os.hostname (server), but also the fqdn (server.domain.com)
equivalent to hostname -f on linux and osx and echo %COMPUTERNAME%.%USERDNSDOMAIN% on Windows

regards

**Comment by sebhildebrandt** [comment]
@celevra very clear. Will add this feature.

**Comment by celevra** [comment]
wow, first thank you for your fast answers and second thank you for the fast commitment to implement my request, and third thank you for all your work, its a great library!

**Comment by sebhildebrandt** [comment]
@celevra Done ... version 4.31.0 just released. Can you test it on your side? You should find `fqdn` now also in the `osInfo()` object

**Comment by celevra** [comment]
tooked me 8 month, sorry 
i get %USERDNSDOMAIN% as fqdn, seems like the variable is not resolved properly
evtl it is in single ticks?

**Comment by celevra** [comment]
this one seems to function
https://github.com/niftylettuce/get-fqdn/blob/master/src/index.js

it gets the fqdn with os.hostname and a lookup, i don't get it completly but it seems to work on windows
