### ISSUE TITLE
Typescript Compile Failure: duplicate identifier`subDeviceId`

### ISSUE THREAD

**Issue by AnimeshKoratana** [sebhildebrandt/systeminformation#456]
**Describe the bug**
Typescript compile fails on due to a duplicate identifier on the [index.d.ts](https://github.com/sebhildebrandt/systeminformation/blob/9d7a3f30c6a062a4659639299ef2414869770b46/lib/index.d.ts#L260) file.

**Current Output**
```
node_modules/systeminformation/lib/index.d.ts:260:5 - error TS2300: Duplicate identifier 'subDeviceId'.

260     subDeviceId?: string;
        ~~~~~~~~~~~

node_modules/systeminformation/lib/index.d.ts:262:5 - error TS2300: Duplicate identifier 'subDeviceId'.

262     subDeviceId?: string;
        ~~~~~~~~~~~
```

**Environment (please complete the following information):**
 - systeminformation package version: 4.33.3
 - node version: v14.5.0
 - tsc version: 3.8.3
 - OS: macOS 11.0.1
 - Hardware MacBook Pro 15

**Comment by sebhildebrandt** [comment]
@AnimeshKoratana sorry, my fault. Fixed. version 4.33.4 just published.
