### ISSUE TITLE
Standardization of uuids in library

### ISSUE THREAD

**Issue by Catutigernos** [sebhildebrandt/systeminformation#460]
Hi,
I realised uuids in library are not in a standart format. One is lowercase, other one is uppercase, one of them has not dashes. If they were in same format, it would be nice. It is not vital, just I realised
in uuid() function
Host Machine(Windows)
`{ os: '4e79641b-5478-4fad-915d-10f5fdda59b2' }`

Guest Machine(Virtual Centos 8)
`{ os: 'f24c5306e4fd4a7b95e076d0fde8e0b7' }`

in system() function

```
{
  manufacturer: 'ASUSTeK COMPUTER INC.',
  model: 'N56VZ',
  version: '1.0',
  serial: 'CCN0BC113160491',
  uuid: '4E435451-384A-3034-4532-50465D40ACF1',
  sku: 'ASUS-NotebookSKU',
  virtual: false
}
```

**Comment by sebhildebrandt** [comment]
@Catutigernos I fixed this by lowercasing all UUIDs but I do not want to change the format by adding characters (this is up to the OS to define how they handle their uuids). I am anyway planning to extend the `uuid()` function to return more uuids ... will do this with version 5 of systemInformation (which I am already working on). I hope for now this is sufficient for you.

Version 4.34.2 just released.

**Comment by Catutigernos** [comment]
hi @sebhildebrandt ,
I thought again, and you are right, I generally use same format for variables. I thought them as string variable not as system variable. Like you said, manipulation of system variable is not logical, and this decision should be left to operating system, so silly me :D

**Comment by Catutigernos** [comment]
And your library is sufficient, make easy implementation for me, so thanks
