### ISSUE TITLE
Graphics Controller undefined

### ISSUE THREAD

**Issue by xddman** [sebhildebrandt/systeminformation#461]
**Describe the bug**
It doesnt find any graphic 'controllers' on last 2 versions, and cannot return a lot of stats that are available on the site like .temperatureGpu (everything other than whats bellow in output) on versions before 4.34.0.

code used: 
const si = require('systeminformation');
si.graphics().then(data => console.log(data));

outputs per version: (versions copied from package.json
"version": "4.34.0",

{
  controllers: [
    {
      vendor: 'Advanced Micro Devices, Inc.',
      model: 'AMD Radeon RX 5700',
      bus: 'PCI',
      vram: 4095,
      vramDynamic: true,
      subDeviceId: '0B361002'
    }
  ],

 "version": "4.34.1",
{
  controllers: [ undefined ],

 "version": "4.34.2",
{
  controllers: [ undefined ],

**Environment (please complete the following information):**
 - systeminformation package version: 4.34.0, 4.34.1, 4.34.2 (also tried 4.33, same as 4.34.0)
 - OS: Windows 10

**Additional context**
Just tried to get gpu temps but all i got was controllers[undefined], then when i went to older versions i couldnt get temperature either even tho controller was found. cpu shows temps fine

EDIT: Also noticed  vram is wrong, its supposed to be 8gb not  vram: 4095

**Comment by sebhildebrandt** [comment]
@xddman sorry for introducing a bug here ... I already fixed it ... Version 4.34.3 just released. Can you test this?

Concerning tram value: can you post the output of the following code:

```
wmic path win32_VideoController get /value
```

As fas as I have discovered, here windows reports wrong VRAM values ... but maybe if we see here correct values in `wmic` my parsing is wrong.
