### ISSUE TITLE
Add avail bytes to si.fsSize()?

### ISSUE THREAD

**Issue by BobbyWibowo** [sebhildebrandt/systeminformation#464]
**Is your feature request related to a problem? Please describe.**

Supposedly, `ext2/3/4` by default reserves 5% of the total size to root user, so non-root attempt at querying "available/free" disk seemingly automatically substracts from the said 5% reservation too (at least with `df` binary).
Reference: https://askubuntu.com/a/249415

**Describe the solution you'd like**

Frankly, I don't know what `systeminformation` uses to query file systems in Unix machines, but I'd love if it actually includes "available/free" disk, as is actually available to the running user (i.e. just like in `df`).
My non-root node app cannot reliably report actual usage of my ext4 filesystems, in percentage, because `total - usage` doesn't add up to the actual available space in non-root context.
It seems `df` is relying on `total - avail` instead of `used` for its percentage column too.

**Describe alternatives you've considered**

I tried just doing `total - usage - (5% of total)`, but that didn't seem to add up? It was more of a cursory attempt though.

Or frankly, I was just unsure, cause I didn't actually know the actual specifics of the whole 5% root reservation thing.

Like in the case of the automatic substraction for `df`'s avail. Does it only substract "unoccupied" space of the total 5% reservation? Or does it actually just do the simple math as I did above, cause truthfully root would **always** have up to 5% of empty space?

**Comment by sebhildebrandt** [comment]
@BobbyWibowo I am using `df` to get fs sizes ... I will add also `available` as a return attribute, as this is not just based on a simple calculation (total - used). 

But I am not that sure, if the calculation of `use%` should be done on this. If e.g. filesystems are on the same volume - like in Mac OS, then this calculation would be the same for all file systems. You are right, that `available` is a pretty useful piece information but I would like to calculate `use%` based on `used / total` as it it done in `df`.

New attribute will be available in upcoming version 5 of systeminformation

**Comment by BobbyWibowo** [comment]
> but I would like to calculate `use%` based on `used / total` as it it done in `df`.

I assume you are referring to `use` attribute that's returned by `si.fsSize()` in this statement?

But hmm, on my machines `df` doesn't seem to actually be using `used / total` for its capacity% column though?
~~It seems more like it's using `(total - avail) / total`, from what I can tell.~~

After some digging to the sauce code, it seems `df` calculates `nonroot_total` with `used + avail`, then afterwards do `used / nonroot_total` for its capacity% column (with some minor rounding imperfections due to technicality reasons, it seems).

Reference (coreutils v8.22 git): https://github.com/coreutils/coreutils/blob/v8.22/src/df.c#L968

> I used v8.22 as reference as that's the lowest version I have access to (with CentOS 7), but I can confirm the lines for capacity% are pretty much identical even till v8.32 (latest release as of this reply's post date).

But yeah, here are some snippets from my CentOS 7 machine:

```js
> require('systeminformation').fsSize(console.log)
Promise { <pending> }
> [
  {
    fs: '/dev/sda2',
    type: 'ext4',
    size: 977819643904,
    used: 793033252864,
    use: 81.1,
    mount: '/'
  },
  ...
]
```

```shell

$ df --version
df (GNU coreutils) 8.22
...
$ df -kP
Filesystem     1024-blocks      Used Available Capacity Mounted on
...
/dev/sda2        954901996 774446500 131925988      86% /
...
```

```
nonroot_total = used + avail = 774446500 + 131925988 = 906372488
capacity% = used / nonroot_total = 774446500 / 906372488 = 0.8544461689353483
```

And here are more snippets from my Ubuntu 20.04 laptop:

```js
> require('systeminformation').fsSize(console.log)
Promise { <pending> }
> [
  {
    fs: '/dev/sda2',
    type: 'ext4',
    size: 966356537344,
    used: 816954343424,
    use: 84.54,
    mount: '/'
  },
  {
    fs: '/dev/mapper/_dev_sdb1',
    type: 'ext4',
    size: 1967922544640,
    used: 1017289318400,
    use: 51.69,
    mount: '/mnt/Data'
  },
  ...
]
```

```shell
$ df --version
df (GNU coreutils) 8.30
...
$ df -kP
Filesystem            1024-blocks      Used Available Capacity Mounted on
...
/dev/sda2               943707556 797806984  97893356      90% /
/dev/mapper/_dev_sdb1  1921799360 993446600 841953496      55% /mnt/Data
...
```

```
/dev/sda2:
nonroot_total = used + avail = 797806984 + 97893356 = 895700340
capacity% = used / nonroot_total = 797806984 / 895700340 = 0.8907074703131184

/dev/sdb1:
nonroot_total = used + avail = 993446600 + 841953496 = 1835400096
capacity% = used / nonroot_total = 993446600 / 1835400096 = 0.5412697766362109
```

> All the above were executed in non-root context.

Though honestly, I don't particularly mind much whichever method the library will end up using for its `use%` property.
I just figured that it'd be even better to include `avail` for more choices in implementation to the end-users :+1:

**Comment by sebhildebrandt** [comment]
@BobbyWibowo thank you for your detailed research and explanation. This makes absolutely sense. I guess I will do it the same way ... will then also be part of systeminformation version 5 changes. Thank you once again!

**Comment by sebhildebrandt** [comment]
@BobbyWibowo Version 5.0 just released. Besides other improvements and changes `fsSize()` has also the attribute `available` and I changes the calculation of `use%` 

Be aware: Version 5 is NOT fulls backwards compatible to version 5 ... see https://systeminformation.io/changes.html to get an overview over all breaking changes.
