### ISSUE TITLE
graphics.controllers array contains empty entries

### ISSUE THREAD

**Issue by ibc** [sebhildebrandt/systeminformation#465]
**Describe the bug**

`graphics.controllers` becomes an array with `null` or `undefined` values.

**To Reproduce**

```ts
const graphics = await systemInformation.graphics();

graphics.controllers.map(graphic => {
      return {
        vendor: graphic.vendor,
        model: graphic.model,
        vramMB: graphic.vram,
      };
    }),
```

**Current Output**

> Uncaught Error: Cannot read property 'verdor' of undefined

**Expected behavior**

Each entry in the returned array should be a proper `object`.

**Environment (please complete the following information):**

 - systeminformation package version: 4.31.0
 - OS: [e.g. macOS]: Windows 10 running in Parallels Desktop for macOS (Mojave)
 - Hardware [e.g. MacBook Pro 13]: MacBook Pro 15'' 2019

**Comment by sebhildebrandt** [comment]
@ibc can you verify this behavior also with the latest version or systeminformation? V4.34.4?

**Comment by ibc** [comment]
Somehow the error just happens in my Electron application. However, if I run the script above directly in Node (v14.15.4) then it works fine in both versions 4.34.0 and 4.34.4.

So no idea, honestly. I did a workaround for my app so feel free to close this issue since I won't be able to invest more time on it unfortunately.

**Comment by sebhildebrandt** [comment]
OK, closing it for now.
