### ISSUE TITLE
If `service` cli is not available, application crash

### ISSUE THREAD

**Issue by Unitech** [sebhildebrandt/systeminformation#468]
**Describe the bug**
When using .services call:

```javascript
sysinfo.services('*')
      .then(services => {
       })
      .catch(e => console.error(e))
```

The app crash, without going to the .catch method.
It triggers the following error:

```
node:child_process:720
    throw err;
    ^

Error: Command failed: service --status-all 2> /dev/null
    at checkExecSyncError (node:child_process:680:11)
    at execSync (node:child_process:717:15)
    at /home/debian/.pm2/modules/pm2-sysmonit/node_modules/systeminformation/lib/processes.js:128:26
    at processTicksAndRejections (node:internal/process/task_queues:75:11) {
  status: 127,
  signal: null,
  output: [ null, Buffer(0) [Uint8Array] [], Buffer(0) [Uint8Array] [] ],
  pid: 3953,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(0) [Uint8Array] []
}
```

I can see here that there is a execSync call without try{}catch{} statement:

https://github.com/sebhildebrandt/systeminformation/blob/f8117d620f380f34b75ada4330e56578cc147ca0/lib/processes.js#L128

**Environment (please complete the following information):**
 - systeminformation package version: 4.34.6
 - OS: Debian 10

**Comment by sebhildebrandt** [comment]
@Unitech thank you! Started working on a workaround (Debian 10) and a final catch ... will be back in 1/2h with a fix.

**Comment by sebhildebrandt** [comment]
@Unitech improved service discovery for Debian 10 and additional try...catch. Can you also test it on your side? Version 4.34.7 just released. 

One more thing: working on Version 5 right now. Hope to get first release ready in aprox. 2 weeks. There will be a few breaking changes (which will be of course documented). Just to inform you. Regards and thank you.

**Comment by Unitech** [comment]
Great! Service discovery do not crash anymore and services are reported on Debian.
Thank you @sebhildebrandt, looking forward the Version 5 of systeminformation.
Best!
