### ISSUE TITLE
Latest version is too cool

### ISSUE THREAD

**Issue by rick-rheo** [sebhildebrandt/systeminformation#47]
Your package.json  says you support  node >= 4  but  you're using ES6 features not supported by  node 4.x

```
/opt/agent/server/node_modules/systeminformation/lib/internet.js:59
              const { statusCode } = res;
```

**Comment by sebhildebrandt** [comment]
Uuppps ... will update it.
Thank you for commenting.

**Comment by sebhildebrandt** [comment]
Fixed, now it allows node 4.x.x again ;-)
Version 3.23.5 published.
In the next major version, I will refactor code to use more ES6 things, so probably then Node v6.x.x is needed.
