### ISSUE TITLE
Error while using the async/await method

### ISSUE THREAD

**Issue by FSCYT** [sebhildebrandt/systeminformation#471]
Error: ```(node:176297) UnhandledPromiseRejectionWarning: TypeError: data.manufacturer is not a function```
Code: ````
const data = await si.system();
**Manufacturer:**  ${data.manufacturer}````

**Comment by sebhildebrandt** [comment]
@FSCYT which platform, which OS version, which SI version?
Thank you for providing more information to be able to reproduce this issue.

**Comment by FSCYT** [comment]
Thank you for replying, I tried redoing this in another function and it worked. I guess its a problem with the .setDescription in the discord.js package.
