### ISSUE TITLE
si.networkInterfaces returns value with key carrierChanges instead of carrier_changes

### ISSUE THREAD

**Issue by LorenzHerz** [sebhildebrandt/systeminformation#472]
**Describe the bug**
`si.networkInterfaces` return value has key `carrierChanges` but the interface for `NetworkInterfacesData` describes key as `carrier_changes`.

**To Reproduce**
Call `si.networkInterfaces`

**Current Output**
```js
[    
  {
    iface: 'enp0s31f6',
    ifaceName: 'enp0s31f6',
    ip4: 'XX.X.XXX.XXX',
    ip4subnet: 'XXX.XXX.XXX.X',
    ip6: 'xxxx::xxxx:xxxx:xxxx:xxxx',
    ip6subnet: 'xxxx:xxxx:xxxx:xxxx::',
    mac: 'xx:xx:xx:xx:xx:xx',
    internal: false,
    virtual: false,
    operstate: 'up',
    type: 'wired',
    duplex: 'full',
    mtu: 1500,
    speed: 1000,
    dhcp: true,
    dnsSuffix: 'Not defined',
    ieee8021xAuth: 'Not defined',
    ieee8021xState: 'Disabled',
    carrierChanges: 2 // should be carrier_changes according to interface
  }
]
```

**Expected behavior**
```js
[    
  {
    iface: 'enp0s31f6',
    ifaceName: 'enp0s31f6',
    ip4: 'XX.X.XXX.XXX',
    ip4subnet: 'XXX.XXX.XXX.X',
    ip6: 'xxxx::xxxx:xxxx:xxxx:xxxx',
    ip6subnet: 'xxxx:xxxx:xxxx:xxxx::',
    mac: 'xx:xx:xx:xx:xx:xx',
    internal: false,
    virtual: false,
    operstate: 'up',
    type: 'wired',
    duplex: 'full',
    mtu: 1500,
    speed: 1000,
    dhcp: true,
    dnsSuffix: 'Not defined',
    ieee8021xAuth: 'Not defined',
    ieee8021xState: 'Disabled',
    carrier_changes: 2
  }
]
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.0.0
 - OS: Ubuntu 20.04.1 LTS
 - Hardware:  
     Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
     00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (2) I219-V (rev 31)

**Comment by sebhildebrandt** [comment]
@LorenzHerz as in new version 5 I made some interface changes (see https://systeminformation.io/changes.html), `carrierChanges`is now the correct one ... I just forgot to modify the typescript typings here. Version 5.0.2 just released with updated typings.

**Comment by LorenzHerz** [comment]
@sebhildebrandt I saw that, thought it was probably overlooked. thanks for the quick answer!

**Comment by sebhildebrandt** [comment]
@LorenzHerz yes, thank you for finding this issue! Have a nice day.
