### ISSUE TITLE
File System - si.diskLayout(cb) - [0].serialNum shows wrong serial number

### ISSUE THREAD

**Issue by esmoley** [sebhildebrandt/systeminformation#474]
Windows 10 and USBDeview app shows serial number of usb device as 070098A2Fxx6AB78.
But File System - si.diskLayout(cb) - [0].serialNum shows serialNumber as 0A7B0708xx80.
Also I've seen the same issue for hard drives.
Why is it different?

**Comment by sebhildebrandt** [comment]
@esmoley this is really interesting ... can you post the output of 

normal **command line**
```
wmic diskdrive get /value
```

as well as 

in **powershell**
```
Get-PhysicalDisk | Format-List
```

Then I can easily see what goes wrong here ...
Thank you in advance!

**Comment by esmoley** [comment]
> @esmoley this is really interesting ... can you post the output of
> 
> from **command line**
> 
> ```
> wmic diskdrive get /value
> ```
> 
> as well as
> 
> from **powershell**
> 
> ```
> Get-PhysicalDisk | Format-List
> ```
> 
> And can you then point me to the drive you have in mind here ...
> 
> Then I can easily see what goes wrong here ...
> Thank you in advance!

Ok. I ran commands that you provided and they perfectly matched with systeminformation output. 
Sadly I don't have the usb stick that I started the issue with. But I have something similar with my hard drive. And turned out it is a Windows 10 output issue (in a screenshot below). Also I could provide info from USBDeview tool, but it does not provide info for my hard drives. By the way thanks for your reply.
![comparison](https://user-images.githubusercontent.com/29107746/106317324-39802480-627f-11eb-9277-9717aa3373bb.jpg)

**Comment by sebhildebrandt** [comment]
@esmoley which means we do not have a bug at all here?

**Comment by esmoley** [comment]
Let me check the usb stick first. I will have it in the next week.

**Comment by esmoley** [comment]
Exactly the same behavior with USB stick. Thanks for your help.
