### ISSUE TITLE
disksIO stats not working on windows system 

### ISSUE THREAD

**Issue by hk4git** [sebhildebrandt/systeminformation#475]
**Unable to get system disk IO statistics on Windows system**
Getting 'Error: not supported' in si.disksIO()

**To Reproduce**

Run below code snippet:
const si = require('systeminformation');
setInterval(function() {
  si.disksIO().then(data => {
    console.log(data);
  })
}, 1000)

**Expected behavior**
It should return proper system disk staticitcs.

**Getting bleow exact error**
Error: not supported
    at D:\path\systeminformation\lib\filesystem.js:609:21
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7) Unhandled Exception Promise {
  <rejected> Error: not supported

**Environment:**
 - systeminformation package version: 4.30.4
 - OS: Windows 10
 - Hardware HP

**Comment by sebhildebrandt** [comment]
@hk4git this ist absolutly fine as this function is not supported on Windows. See docs
