### ISSUE TITLE
CPU Temperatures doesn't return any values

### ISSUE THREAD

**Issue by dan953** [sebhildebrandt/systeminformation#477]
I am attempting to pull the CPU temperatures, I get a response but with no values.

**This is reproducible using the code I have attached below;** 

`valueObject = {
    cpu:'brand',
    cpuTemperature: 'main, cores, max'
}

si.get(valueObject).then(data => console.log(data));`

**Output**
From main.js
{ cpu: { brand: 'Ryzen 5 2600 Six-Core Processor' },
  cpuTemperature: { main: null, cores: [], max: null }

**Expected behavior**
I was expecting to recieve CPU temperatures!

**Environment (please complete the following information):**
 - systeminformation package version: Windows 10 Pro, Using Visual Studio
 - OS: Windows
 - Hardware: Ryzen 5 2600, MSI X470 carbon motherboard,

**Extra Info**
I have already tried running as an administrator through powershell but to no success!

**Comment by sebhildebrandt** [comment]
@dan953 please have look at https://systeminformation.io/issues.html. 

Did you checked if WMIC returns correct values? 

Can you post result of 

```
wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
```

**Comment by dan953** [comment]
Node - DAN-RYZEN-2600
ERROR:
Description = Not supported

**Comment by sebhildebrandt** [comment]
@dan953 Thank you for rechecking - so then if Windows cannot determine temperature this way, then systeminformation also cannot get the value (as described in its known issues https://systeminformation.io/issues.html section of the docs).

Closing this for now.
