### ISSUE TITLE
"available" does not exist in the object obtained by fsSize()

### ISSUE THREAD

**Issue by KazukiSugiyama107** [sebhildebrandt/systeminformation#478]
**Describe the bug**
"available" does not exist in the object obtained by fsSize().
You can see it on Mac, but not on Windows.
Is available not available on Windows?

**To Reproduce**
Tested and confirmed using v5.0.6.
https://systeminformation.io/tests.html

**Current Output**
```
┌────────────────────────────────────────────────┐
│  File System                          v: 5.0.6 │
└────────────────────────────────────────────────┘
[
  {
    fs: 'C:',
    type: 'NTFS',
    size: 255239122944,
    used: 75533164544,
    use: 29.593098296522566,
    mount: 'C:'
  }
]
```

**Expected behavior**
I thought I could get "availabe" with fsSize().

**Environment (please complete the following information):**
 - systeminformation package version: 5.0.6
 - OS: Windows10
 - Hardware: HP ENVY x360 Convertible 13

**Comment by sebhildebrandt** [comment]
@KazukiSugiyama107 sorry, my fault, only added it to linux. Now also available for win/darwin ... Version 5.0.7 just published.
