### ISSUE TITLE
CPU temp returning null?

### ISSUE THREAD

**Issue by CadeK-js** [sebhildebrandt/systeminformation#480]
**Describe the bug**
CPU temp is returning 'null'

**To Reproduce**
        const si = require('systeminformation');
        si.cpuTemperature().then(data => console.log(data));

**Current Output**
{ main: null, cores: [], max: null }

**Expected behavior**
return the temperature of the CPU 

**Environment (please complete the following information):**
 - systeminformation package version: 5
 - OS: windows 10 (not activated yet)
 - Hardware Custom built desktop: Ryzen 5 3600, EVGA 3060ti, Asrock b450/ac

**Additional context**
Currently, I am trying to use this in a discord bot written in discord.js.
I have a command set up like so:
if(message.content.startsWith(prefix + 'temp') || message.content == '?t') {
        const si = require('systeminformation');
        si.cpuTemperature().then(data => console.log(data));
    }

which returns: { main: null, cores: [], max: null }

I do have another command that works:

if(message.content.startsWith(prefix + 'info') || message.content == '?i') {
        si.cpu()
  .then(data => {
    message.channel.send('CPU Information:' + '\n- manufucturer: ' + data.manufacturer + '\n- brand: ' + data.brand + '\n- speed: ' + data.speed + '\n- cores: ' + data.cores + '\n- physical cores: ' + data.physicalCores);
  })
  .catch(error => console.error(error));
    }

**Comment by sebhildebrandt** [comment]
@CadeK-js please have look at https://systeminformation.io/issues.html.

Did you checked if WMIC returns correct values?

Can you post result of

```
wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
```

**Comment by CadeK-js** [comment]
that returns:
Node - DESKTOP-T3PO6T6
ERROR:
Description = Not supported.

**Comment by sebhildebrandt** [comment]
@CadeK-js so this means, as windows or more specifically WMIC does not support CPU temp on your machine, I cannot get the correct value (as also described in the docs). Closing it for now.
