### ISSUE TITLE
There is a pattern in which the value of mount object obtained by fsSize() is incorrect.

### ISSUE THREAD

**Issue by KazukiSugiyama107** [sebhildebrandt/systeminformation#481]
**Describe the bug**
For a specific file system name, there is a pattern in which the value of `mount` obtained by `fsSize()` is incorrect.

**To Reproduce**
Set the name of the disk to a value with a space such as `NO NAME`, and acquire the object with fsSize.

**Current Output**
Disk Name：`NO NAME`
```
mount: "NAME"
```

**Expected behavior**
I think there was an error in the process of cropping the resulting string obtained by the command.

**Environment (please complete the following information):**
 - systeminformation package version: 5.0.8
 - OS: macOS Catalina (ver 10.15.7)
 - Hardware: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

**Comment by sebhildebrandt** [comment]
@KazukiSugiyama107 ... thank you! I see the problem. Will provide a fix. Need to test it on all platforms first.

**Comment by KazukiSugiyama107** [comment]
Thank you for your prompt response!
I have a Windows and a Mac, so check it.

**Comment by KazukiSugiyama107** [comment]
When I checked it, there was no problem!

**Comment by sebhildebrandt** [comment]
@KazukiSugiyama107 thank you so much for testing
