### ISSUE TITLE
Performance issue in MacOS Big Sur

### ISSUE THREAD

**Issue by FranCarrascosaMS** [sebhildebrandt/systeminformation#484]
**Describe the bug**
Promise functions of this library take much more time to finish in MacOS Big Sur.

**Current Output**
![image](https://user-images.githubusercontent.com/32394038/107513841-1e7bb180-6ba9-11eb-9d0a-4a65c13d8989.png)
**Total time: 3.093 seconds**
- system time: 0.029 seconds
- bios time: 0.012 seconds
- baseboard time: 0.016 seconds
- chassis time: 0.032 seconds
- cpu time: 0.07 seconds
- mem time: 0.044 seconds
- memLayout time: 0.368 seconds
- battery time: 0.073 seconds
- graphics time: 0.256 seconds
- osInfo time: 0.07100000000000001 seconds
- uuid time: 0.032 seconds
- diskLayout time: 0.51 seconds
- blockDevices time: 1.19 seconds
- fsSize time: 0.125 seconds
- networkInterfaces time: 0.214 seconds
- networkInterfaceDefault time: 0.026000000000000002 seconds
- networkGatewayDefault time: 0.016 seconds

![image](https://user-images.githubusercontent.com/32394038/107513808-102d9580-6ba9-11eb-8e55-9af75b81dc7e.png)
**Total time: 64.64 seconds**
- system time: 2.114 seconds
- bios time: 1.625 seconds
- baseboard time: 3.806 seconds
- chassis time: 1.956 seconds
- cpu time: 7.259 seconds
- mem time: 3.3280000000000003 seconds
- memLayout time: 1.728 seconds
- battery time: 1.962 seconds
- graphics time: 1.617 seconds
- osInfo time: 4.522 seconds
- uuid time: 1.752 seconds
- diskLayout time: 3.761 seconds
- blockDevices time: 4.196 seconds
- fsSize time: 2.6 seconds
- networkInterfaces time: 19.618000000000002 seconds
- networkInterfaceDefault time: 1.365 seconds
- networkGatewayDefault time: 1.421 seconds

**Expected behavior**
Minimal difference time

**Environment**
 - systeminformation package version: 4.34.7 and 5.1.2

**Additional context**
I'm using `systeminformation` library in an Electron application.

**Comment by sebhildebrandt** [comment]
@FranCarrascosaMS ... very interesting. just tested it here on my machines (iMac Catalina, MacBook Pro BigSur and BigSur on M1)

Not have precisely measured it here but there seem to be all taking the same time. getStatic e.g takes about 1.2 secs on all machines ... getAll takes about 5 secs ... no difference here. So not sure if this is related to `systeminformation`

**Comment by sebhildebrandt** [comment]
@FranCarrascosaMS can you provide your code snippet where you measured it?

**Comment by FranCarrascosaMS** [comment]
@sebhildebrandt, sure!

```
const get = async () => {
  const specs = {
    // General.
    version: si.version(),
    time: si.time()
  }

  const specsKeys = [
    // System (HW).
    'system',
    'bios',
    'baseboard',
    'chassis',

    // CPU.
    'cpu',

    // Memory.
    'mem',
    'memLayout',

    // Battery.
    'battery',

    // Graphics.
    'graphics',

    // Operating System.
    'osInfo',
    'uuid',

    // File system.
    'diskLayout',
    'blockDevices',
    'fsSize',

    // Network.
    'networkInterfaces',
    'networkInterfaceDefault',
    'networkGatewayDefault'
  ]

  const startTotalTime = new Date()
  await specsKeys.reduce(async (previousPromise, key) => {
    await previousPromise

    const startTime = new Date()
    return si[key]()
      .then(v => {
        const endTime = new Date()
        console.log(`${key} time: ${(endTime - startTime) * 0.001} seconds`)
        specs[key] = v
      })
      .catch()
  }, Promise.resolve())

  const endTotalTime = new Date()
  console.log(`Total time: ${(endTotalTime - startTotalTime) * 0.001} seconds`)

  return specs
}
```

This code is run in a web-worker. Doing it in the main thread times are worse.

**Comment by FranCarrascosaMS** [comment]
@sebhildebrandt, it could be related to Electron and how it spawns processes: https://github.com/electron/electron/issues/26143

**Comment by sebhildebrandt** [comment]
@FranCarrascosaMS here my BigSur results:

system time: 0.013000000000000001 seconds
bios time: 0.182 seconds
baseboard time: 0.20800000000000002 seconds
chassis time: 0.008 seconds
cpu time: 0.019 seconds
mem time: 0.012 seconds
memLayout time: 0.196 seconds
battery time: 0.031 seconds
graphics time: 0.314 seconds
osInfo time: 0.031 seconds
uuid time: 0.177 seconds
diskLayout time: 0.513 seconds
blockDevices time: 1.555 seconds
fsSize time: 0.203 seconds
networkInterfaces time: 0.149 seconds
networkInterfaceDefault time: 0.007 seconds
networkGatewayDefault time: 0.004 seconds
Total time: 3.629 seconds

**Comment by sebhildebrandt** [comment]
@FranCarrascosaMS Ok for you to close it here?

**Comment by FranCarrascosaMS** [comment]
@sebhildebrandt, yes. Thanks for your time!

**Comment by sebhildebrandt** [comment]
@FranCarrascosaMS no problem ... so if you have anything to do on my side, just contact me again. Closing it for now.
