### ISSUE TITLE
error when accessing non-existing folder in lib/system.js

### ISSUE THREAD

**Issue by winnyschuster** [sebhildebrandt/systeminformation#485]
https://github.com/sebhildebrandt/systeminformation/blob/f1665e5d1dad0eaedf82b1830d5bb847cdd3973d/lib/system.js#L112

when above line is executed but folder ```/dev/disk``` doesn't exist, an error is thrown. This could be prevented by forwarding any errors to ```/dev/null```

thanks for looking at this

**Comment by sebhildebrandt** [comment]
@winnyschuster you are absolutely right! Fixed it. Version 5.2.1 just released. Pleas can you check it on your side?

**Comment by winnyschuster** [comment]
wow, that was quick! i can confirm the error is gone with 5.2.1. Thanks a bunch
