### ISSUE TITLE
cpu.js: Cores load is NaN

### ISSUE THREAD

**Issue by sergeysedoy97** [sebhildebrandt/systeminformation#487]
**Describe the bug**
The following fields is NaN:
```
loadUser: NaN,
loadSystem: NaN,
loadNice: NaN,
loadIdle: NaN,
loadIrq: NaN,
```

**To Reproduce**
```require('systeminformation').currentLoad(console.log)```

**Additional context**
Fixed in https://github.com/sebhildebrandt/systeminformation/pull/486

**Comment by sebhildebrandt** [comment]
@sergeysedoy97 Wow... didn't see that while renaming variables in version 5. Thank you. fixed. Version 5.2.4 just released.
