### ISSUE TITLE
SocketIO

### ISSUE THREAD

**Issue by abolinhas** [sebhildebrandt/systeminformation#49]
Hi,
First of all congratulations for this amazing project.
I have two questions:
1ºDo you have any example using socket io for real-time monitor?
2ºUsing si.processes(cb) how can I get only the running proccess?

Best regards

**Comment by sebhildebrandt** [comment]
To answer your second question first:

This can be solved by applying a filter like this: 

```
const si = require('systeminformation');

setInterval(function() {
	si.processes().then(data => {
		let running = data.list.filter(item => {
			return item.state=='running'
		});
	    console.log('-----------------------------');
	    console.log(running);
	})
}, 1000)
```

And for sockets: the server part could work like this:

```
const app = require('express')();
const http = require('http').Server(app);
const io = require('socket.io')(http);
const port = process.env.PORT || 3000;
const si = require('systeminformation');

app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

setInterval(function() {
	si.currentLoad().then(data => {
		io.sockets.emit('current load', data);
	})
}, 1000)

http.listen(port, function(){
  console.log('listening on *:' + port);
});
```
(not tested)

**Comment by paul-bell** [comment]
abolinhas,

I might be able to help concerning socket i/o.

Can you state more fully what you're interested in?

-Paul

**Comment by abolinhas** [comment]
I want to create a mobile application to monitor my server, so I need to pass the data in real-time.
On server side i'm thinking use node + socket io + systeminformation + something to authenticate (searching yet) and on cliente side native script + socket io.
Best regards

**Comment by paul-bell** [comment]
Hi Andre,

I've done same (though not for mobile app).

Let's take it offline so as not to clutter Sebastian's site. Can you e-mail me at arachweb AT gmail DOT com?

-Paul

**Comment by abolinhas** [comment]
ok,
Already sent you an email
Thanks
