### ISSUE TITLE
PascalCase? & inetChecksite function

### ISSUE THREAD

**Issue by kerimkaan** [sebhildebrandt/systeminformation#490]
As I can see, camelCase has been implemented but not applied to the `inetChecksite` function, do you consider editing? And, this is not PascalCase. I read [changelog](https://systeminformation.io/changes.html) and i see the changes about [camelCase](https://en.wikipedia.org/wiki/Camel_case). This is a mistake, @sebhildebrandt ? Thanks for this lib.

**Comment by sebhildebrandt** [comment]
@kerimkaan well yes. Forgot one or two. Since this would be a breaking change again I need to wait for version 6...Sorry about that. Closing it for now. Thank you for reminding me.
