### ISSUE TITLE
si.graphics() has big impact on CPU temp

### ISSUE THREAD

**Issue by alansiq** [sebhildebrandt/systeminformation#495]
**Describe the bug**
Every call that I make to si.graphics() increases CPU temp in 10-20 degrees celsius. Is it a known issue or related to my system overall?

**To Reproduce**
1. Monitor your CPU temp with MSI Afterburner
2. Make a si.graphics() call in a interval (using 5 seconds in my sample)
3. Notice the spike in CPU temp every time the si.graphic is called.

My code:
```
const si = require('systeminformation');



function updateAllData() {
    const memElement = document.querySelector('#mem');
    const cpuElement = document.querySelector('#cpu');
    const gpuElement = document.querySelector('#gpu');

    si.mem().then(data => {
        memElement.innerHTML = `<b>${Math.floor(data.free / 1e9)}gb</b> de um total de <b>${Math.floor(data.total / 1e9)}gb</b>`;
    }); 

    si.graphics().then(data => {
        gpuElement.innerHTML = `<b>${data.controllers[0].temperatureGpu}°C</b>`;
    });

}


setInterval(updateAllData, 5000);

```

**Environment (please complete the following information):**
 - systeminformation package version: latest
 - OS: Windows 10 Pro
 - Hardware: RTX 2070 Super, i5 7600k, 16gb RAM
**Additional context**

**Comment by sebhildebrandt** [comment]
@alansiq nothing discovered so far here on all of my machines ... But I would be happy, if you can keep an eye on it on your side. If you have further details, please feel free to reopen this issue.
