### ISSUE TITLE
Cant get docker stats with dockerContainerStats

### ISSUE THREAD

**Issue by amunhoz** [sebhildebrandt/systeminformation#497]
**Describe the bug**
Using the function dockerContainerStats with root user and at least 4 dockers running return an empty result.

**To Reproduce**
```
const si = require('systeminformation');
async function start(){
    let dockerdata = await si.dockerContainerStats("*")
    console.log("docker data", dockerdata)
}
start()
    
```

**Current Output**
```
[
  {
    id: '',
    memUsage: 0,
    memLimit: 0,
    memPercent: 0,
    cpuPercent: 0,
    pids: 0,
    netIO: { rx: 0, wx: 0 },
    blockIO: { r: 0, w: 0 }
  }
]
```

**Expected behavior**
At least 4 dockers information

**Environment (please complete the following information):**
 - UBUNTU 18.04
 - VMWARE

**Comment by sebhildebrandt** [comment]
@amunhoz need to check it here on my side ... will come back with my findings tomorrow.

**Comment by amunhoz** [comment]
@sebhildebrandt 
version 5.3.4 and indicating the ids with comma works fine.

**Comment by sebhildebrandt** [comment]
@amunhoz I think I found the issue, I made changes to sanitizing the IDs and there I introduced an issue. Should be fixed now. Version 4.34.15 and 5.3.5 just released. 

Can you check it on your side?
