### ISSUE TITLE
Cannot find namespace 'dockerstats'

### ISSUE THREAD

**Issue by javelinco** [sebhildebrandt/systeminformation#498]
**Describe the bug**
When compiling after installing 5.4.0 in a node application (mac or linux based container, or at command line), I get the following error:

```
node_modules/systeminformation/lib/index.d.ts:875:57 - error TS2503: Cannot find namespace 'dockerstats'.

875 export function dockerImages(all?: boolean, cb?: (data: dockerstats.DockerImageData[]) => any): Promise<dockerstats.DockerImageData[]>;
                                                            ~~~~~~~~~~~

node_modules/systeminformation/lib/index.d.ts:875:105 - error TS2503: Cannot find namespace 'dockerstats'.

875 export function dockerImages(all?: boolean, cb?: (data: dockerstats.DockerImageData[]) => any): Promise<dockerstats.DockerImageData[]>;
```

**To Reproduce**
1. With a node application running with typescript 3.9.7, install systeminformation@5.4.0 using npm install
2. Run tsc -p

**Expected behavior**
The compile should complete without errors

**Environment (please complete the following information):**
 - systeminformation package version: 5.4.0
 - OS: macOS Catalina 10.15.7
 - Hardware: MacBook Pro (15-inch, 2019)

**Comment by sebhildebrandt** [comment]
@javelinco sorry, my fault. Should be fixed now. Version 5.5.0 just published
