### ISSUE TITLE
CPU utilization is not accurate

### ISSUE THREAD

**Issue by zhaoxiaolei519109457** [sebhildebrandt/systeminformation#499]
**Describe the bug**

**To Reproduce**
1. used function 'currentLoad'

**Expected behavior**
When I use currentLoad to get the currentLoad variable it has a value but it's a little bit different from the task manager's CPU statistics so what's wrong with that Looking forward to your reply

**Environment (please complete the following information):**
 - systeminformation package version:5.0.7
 - OS: [win10]

**Comment by sebhildebrandt** [comment]
@zhaoxiaolei519109457 I will have a look at it but I am pretty much sure, that the way I am calculating this is the only possible way within node. I am aware of slightly different values to task manager but it is still accurate to the numbers that I get from `os.cpus()` where we exactly have values for user, system, nice, irq and idle ticks per CPU core. I have to rely on those ticks when calculating the currentLoad. 

Just to be sure: calling `currentLoad()` the first time will not have correct values. You need to call it multiple times to get the load between the calls (as documented in https://systeminformation.io/statsfunctions.html).

In your case it should be something like:

```
const si = require('systeminformation');

setInterval(function() {
    si.currentLoad().then(data => {
        console.log(data);
    })
}, 1000)
```

Hope that helps.

**Comment by sebhildebrandt** [comment]
Testet it once again, and the method I am calculating it seems to be correct. I got the same values as in activity monitor (+/- 1% ... ) ... If you have an idea, what can be improved here, I would be happy to get further comments.
