### ISSUE TITLE
Add temperature sensor of PCH diode

### ISSUE THREAD

**Issue by Andrey2509** [sebhildebrandt/systeminformation#500]
Output of "sensors":
```
root@dacha:~# sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +18.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +17.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +16.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +119.0°C)
temp2:        +29.8°C  (crit = +119.0°C)

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +12.5°C
```
temp1 is  temperature sensor of PCH diode, please add to the driver

**Comment by sebhildebrandt** [comment]
@Andrey2509 would then be a separate property, right? Need to make sure to detect this across all platforms ... as `temp1` in your case is here 2 times, the only possibility is to see at the `pch...` part of sensors. I will check, if I can rely on this string.

Regards

**Comment by sebhildebrandt** [comment]
@Andrey2509 ... just added chipset (PCH) and socket (ACPI) temperatures. Version 5.6 just released. Can you also test it on your side?

**Comment by Andrey2509** [comment]
> @Andrey2509 ... just added chipset (PCH) and socket (ACPI) temperatures. Version 5.6 just released. Can you also test it on your side?

I can check later in other software using your library.
