### ISSUE TITLE
Is there a list of fully supported CPUs?

### ISSUE THREAD

**Issue by ArshZilpe** [sebhildebrandt/systeminformation#501]
Hello,

I am interested in using this brilliant library in one of my projects. I was wondering whether there is a list of which CPUs are compatible, especially in terms of CPU temperature? In addition, where does systeminformation get the temperature from? 

Thanks!

**Comment by sebhildebrandt** [comment]
Hi @ArshZilpe , first of all, we need to clarify of which platforms we are talking. Then it would be good to specify a little bit more, what you have in mind when talking about CPU support. 

Here a first answer: generally speaking, I try to use functions provided natively by OS to get system information data. Sometimes I also try to utilize third party modules (like sensors). The OS also needs to rely on other parts like BIOS etc. to support certain functionality. So there are probably millions of combinations of OS platforms, versions, distributions, BIOS and other components that make it possible (or not) to get the desired information. I am not sure I would ever be able to provide a list as requested. 

Maybe you can describe your specific use case more in detail? Hope I can still provide useful information for your needs. 

Regards

**Comment by ArshZilpe** [comment]
Thanks for the quick reply! I am talking about Windows. Sorry I didn't clarify earlier. So it would only be Intel/AMD CPUs really.

I am looking to create a program to easily display all system stats in a modern UI (like a better Task Manager). Your library looks perfect for it. Do you need to specifically build in support for newer CPUs (for instance the new Ryzen 5000 series), or does the library automatically get the info using the native functions which you mentioned? For example, programs like Open Hardware Monitor have to manually add support for newer CPUs, however Task Manager which is built into Windows can fetch info about the CPU (like name, clock speed, usage) without an update. 

Thanks again :)

**Comment by sebhildebrandt** [comment]
@ArshZilpe thank you for clarification. So at the moment I do not modify code specific for any CPU, I just rely on what Windows can give back. But there are some drawbacks: for some functions I (sometime) need admin rights. E.g. CPU temperature is one of the functions where on some systems I do get results without admin rights, on others I do need admin rights and then there are systems where I do not get any data at all. Depends here on BIOS, etc. 

Hardware Monitor goes one step further and implements native code and therefore can support systems where windows does not give anything back. So if you want to implement something with full support for all systems, you have to go this way. If you can live with what windows gives back e.g. via WMIC, then `systeminformation` should cover it. 

If you have any further questions or suggestions, feel free to reply here. I get notified ;-)

Closing this question for now. OK?

**Comment by ArshZilpe** [comment]
I see. Thanks for the help!
