### ISSUE TITLE
Get all docker containers using si.get(valueObject,cb) function

### ISSUE THREAD

**Issue by jdbelo** [sebhildebrandt/systeminformation#503]
**Describe the bug**

The function `si.get(valueObject, cb)` returns an empty list when the `all` parameter is passed to `dockerContainers` function through `valueObject`.

**To Reproduce**
```
const si = require("systeminformation");
const systeminfo = {
   dockerContainers: "(true) *",
};

si.get(systeminfo, (info) => {
   console.log(info);
});
```

**Current Output**
```
{ dockerContainers: [ {} ] }
```

**Expected behavior**

As `si.dockerContainers(all, cb)` function returns running containers (when the `all` parameter is `false` or not set at all) and all containers (when the `all` parameter is `true`), using the `si.get(valueObject, cb)` function,  I expected to get the same result.

**Environment**
 - systeminformation package version: 5.5.0
 - OS: macOS, Windows
 - Hardware: MacBook Pro 13, Intel NUC

**Comment by sebhildebrandt** [comment]
@jdbelo found problem and fixed it. Version 5.6.1 just released. Can you test it on your side?

**Comment by jdbelo** [comment]
Hi Sebastian,

Many thanks, once again.
I've already tested the new version and it is working fine.
Thanks for the really quick fix.

Cheers,
João


Sebastian Hildebrandt <notifications@github.com> escreveu no dia quarta,
3/03/2021 à(s) 18:51:
