### ISSUE TITLE
Get all services using si.get(valueObject,cb) function

### ISSUE THREAD

**Issue by jdbelo** [sebhildebrandt/systeminformation#504]
**Describe the bug**

The function `si.get(valueObject, cb)` returns an empty services list.

**To Reproduce**

```
const si = require("systeminformation");
const systeminfo = {
   services: "*",
};

si.get(systeminfo, (info) => {
   console.log(info);
});
```

**Current Output**

```
{ services: [] }
````

**Expected behavior**

As `si.services('*', cb)` function returns all services, I expected to get the same result using the `si.get(valueObject, cb)` function.

**Environment**

systeminformation package version: 5.5.0
OS: macOS, Windows
Hardware: MacBook Pro 13, Intel NUC

**Comment by sebhildebrandt** [comment]
@jdbelo thank you. Found the bug. Working on a fix.

**Comment by sebhildebrandt** [comment]
@jdbelo in this case there is not really an issue in the library:

- first on macOS stride enumeration (all services) is not yet implemented, so also `si.services('*')` will not work. See docs (https://systeminformation.io/processes.html)
- then you test code is not correct: your object should be like this:

```
const si = require("systeminformation");
const systeminfo = {
   services: "(*) *",     // parameter in parentheses: all services, and then: return back all attributes 
};

si.get(systeminfo, (info) => {
   console.log(info);
});
```

This would work as expected on linux and windows.

**Comment by jdbelo** [comment]
Hi Sebastian,

Thanks for your help.
I have just tested and you are absolutely right.
No major problems by not being able to use si.services('*', cb) on
macOS. Although
my development env is macOS, my application is supposed to run on Windows
only. (:D)

Cheers,
João




Sebastian Hildebrandt <notifications@github.com> escreveu no dia quarta,
3/03/2021 à(s) 18:46:

**Comment by sebhildebrandt** [comment]
@jdbelo ...anyway, this was a reminder for me to implement service enumeration also for mac OS ;-)
