### ISSUE TITLE
Volume indicator

### ISSUE THREAD

**Issue by molor** [sebhildebrandt/systeminformation#506]
Hello. 

**Is your feature request related to a problem? Please describe.**
Could you please add a method to get the volume level of current playing audio/sound in system?
I mean the level (from 0 to 100 %) of this **green bar** in the windows volume settings/mixer:

![image](https://user-images.githubusercontent.com/19989717/110157499-4a313680-7df9-11eb-99a7-3c61846b5ab0.png)

I am writing a program to control the ARGB backlight inside PC and for the colormusic mode I'm need to know the volume level of media that is currently playing.

**Describe the solution you'd like**
Something like `require ('systeminformation').audio ().then (data => console.log (data.volume));`

**Comment by sebhildebrandt** [comment]
@molor I made a first research and there is not windows build-in functionality to get the value from command line. If you ave any idea for that, please let me know. Closing it for now.

**Comment by gannonprudhomme** [comment]
Not sure if it's something y'all would want to do, but it seems like it's only possible by using C++/C#. [node-process-volumes]() uses a C++ file to do it, while [my implementation](https://github.com/gannonprudhomme/Desktop-Control-Tablet-Server/tree/master/csharp-scripts) (which I mostly received from [this stackoverflow post](https://stackoverflow.com/questions/20938934)) uses C#, although I'm pretty sure it internally calls C++/C Windows functionality. Have yet to see an implementation in Node that is similar to how this repository retrieves Windows functionality though. 

Note that the above links are Windows-only
