### ISSUE TITLE
cpu function takes 2.7s to complete

### ISSUE THREAD

**Issue by Citriik** [sebhildebrandt/systeminformation#507]
Hello,
I'm using the `cpu` in my script and it's taking 2.7s to complete every time :/

**To Reproduce**
`await systemInfo.cpu();`

**Environment**
 - systeminformation package version: 5.6.1
 - OS: Windows 10
 - Hardware :
   - Intel Core i7-7700k
   - 64gb of RAM
  
Thanks for your help.

**Comment by sebhildebrandt** [comment]
@Citriik ... yes this is correct. As I am using `wmic` to determine cpu details, this takes some time. I am about to improve this a little bit, but do not expect it to be much faster.
