### ISSUE TITLE
Getting bluetooth info in angular app

### ISSUE THREAD

**Issue by weilies** [sebhildebrandt/systeminformation#508]
Does this package work on angular app?

I tried to build one after install the package, but the console return nothing (sample code below)
https://codesandbox.io/s/bluetooth-7-vjh3h?file=/src/app/app.component.ts

Thanks

**Comment by sebhildebrandt** [comment]
@weilies no, unfortunately not. This would be a big security issue if you would allow any web app to access detailed OS and system information. See also docs, where is says that this is only intended to be used server side. https://systeminformation.io/gettingstarted.html
