### ISSUE TITLE
unhandled warning

### ISSUE THREAD

**Issue by undefined-moe** [sebhildebrandt/systeminformation#509]
```
cat: /sys/class/thermal/thermal_zone*/type: No such file or directory
cat: /sys/class/thermal/thermal_zone*/temp: No such file or directory
```

os: centos7
node@13.12
systeminformation@5.6.4

**Comment by mkellsy** [comment]
I am getting the same console spamming on Debian 10.

node@14.16.0
systeminformation@5.6.4

Possible fix. In cpu.js line 938 - 957
```js
if (_linux) {
// CPU Chipset, Socket
try {
  const cmd = 'cat /sys/class/thermal/thermal_zone*/type; echo "-----"; cat /sys/class/thermal/thermal_zone*/temp;';
  let parts;
  try {
    parts = execSync(cmd).toString().split('-----\n');
  } catch (_error) {
    parts = [];
  }
  if (parts.length === 2) {
    const lines = parts[0].split('\n');
    const lines2 = parts[1].split('\n');
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line.startsWith('acpi') && lines2[i]) {
        result.socket.push(Math.round(parseInt(lines2[i], 10) / 100) / 10);
      }
      if (line.startsWith('pch') && lines2[i]) {
        result.chipset = Math.round(parseInt(lines2[i], 10) / 100) / 10;
      }
    }
  }
} catch (e) {
  util.noop();
}
```

**Comment by sebhildebrandt** [comment]
@undefined-moe @mkellsy ... interesting... the outer `try catch` should catch the error (at leaset, this was my intension!). Not sure, why we would need an inner `try catch` ... need to make further investigation. Will provide a fix soon.

**Comment by sebhildebrandt** [comment]
@mkellsy @undefined-moe found the problem and fixed it. Version 5.6.5 just released. Can you check it on your side?

**Comment by undefined-moe** [comment]
I think its incorrect.

https://github.com/sebhildebrandt/systeminformation/blob/0c700f61e4997547a20942bbdb7857d10df311c1/lib/cpu.js#L940

The output will always be two empty lines joined with `-----` and this function will be not working at all.

**Comment by mkellsy** [comment]
Thanks
