### ISSUE TITLE
Problem at linux with other locales than english

### ISSUE THREAD

**Issue by Zerogiven** [sebhildebrandt/systeminformation#51]
Hi,

Your work is great, only have one problem at some of my clients, they have a german locale at console. So there is only one problem at filesystem.js line #594 where you execute lshw to get disks. You are looking for the key "logical name" but i get at the clients "Logischer Name" cause of german locale. So i can't force them all to set console locale to english as default. Sure i can tell all they must have installed english as secondary locale.

The only real problem is that i get an error 'cat /sys/block/' + logical + '/queue/rotational' cause logical is empty at my case and so the dir it tries to cat does not exist.

At least i need a fix for checking if the dir exists before cat'ing it (think those two lines are not to hard to you so i don't have to send a pull request ;) )

But much better would be a solution to get the devices at systems with other default locale than english too. I'm 100% sure at the moment how to solve this, but maybe you have an idea :)

not sure if it's possible to maybe forcing the console output to english (like i said, i can install a second locale), but maybe you/we find a solution where it's not important which locale is installed (maybe catching it not by key, catching it by something like substring with /dev/?... just one more idea ;) )

greetings
Chris

**Comment by sebhildebrandt** [comment]
Will fix that. As I discovered this problem also in another part of the library, I am working to solve this more generally ;-) Will inform you, when fixed.

**Comment by sumeetkpatel** [comment]
I am also experiencing this issue
"Command failed"
"cat: /sys/block/cdrom/queue/rotational: No such file or directory"

**Comment by sebhildebrandt** [comment]
Hi again,

- for the `locales` problem I am now testing another approach, will publish it tomorrow. 
- for the `command failed` I also made a fix ...

generally I am thinking of rewriting the whole function to be more reliable ...

**Comment by sumeetkpatel** [comment]
Thanks @sebhildebrandt 

I have an emergency quick fix for my specific issue with `command failed` from above:
https://github.com/sumeetkpatel/systeminformation/commit/e66af0062fb3b7747fb36b8c1f4bd4a20a34131b
I simply do a fs path check before trying to exec.

**Comment by sebhildebrandt** [comment]
Just published a fix for `locales`-problem and `command failed`-problem. Closing it for now.
