### ISSUE TITLE
Problem with gpu information

### ISSUE THREAD

**Issue by Funminotaur3880** [sebhildebrandt/systeminformation#510]
**Describe the bug**: When using the si.graphics(), I can't get information about my gpu. It says undifined. My gpu is the AMD Radeon RX 5700xt
The bug causes no information to be givin about the gpu

**To Reproduce**
1. used function 'data.controllers[0]'
2. code snippet ' 
3.     const si = require('systeminformation'); || si.graphics().then(data => console.log(data.controllers[0].temperatureGpu));'
3. start app / code
4. See output/error 'undefined'

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
 - systeminformation package version: latest
 - OS: [e.g. macOS] windows 10 pro
 - Hardware [e.g. MacBook Pro 13] 
 - Ryzen 7 3700x
 - rx 5700xt
 - 16gb ram
 - nvme ssd
 - 850 watt psu

**Additional context**

**Comment by sebhildebrandt** [comment]
@Funminotaur3880 seems that no controllers are detected on your machine. Can you run the code with just `console.log(data.controllers)` to get a confirmation?

And please can you also run the following command from console: 

```
wmic path win32_VideoController get /value
```

to see if windows detects the controllers. Can you provide both outputs here as text?

Thank you in advance.

**Comment by Funminotaur3880** [comment]
Hello! Thank you very much for your answer.

The output I got from the `console.log(data.controllers)` is:

`reverse:ƒ reverse()
shift:ƒ shift()
slice:ƒ slice()
some:ƒ some()
sort:ƒ sort()
splice:ƒ splice()
toLocaleString:ƒ toLocaleString()
toString:ƒ toString()
unshift:ƒ unshift()
values:ƒ values()
__proto__:Object
(1) [{…}]
0:{vendor: 'Advanced Micro Devices, Inc.', model: 'AMD Radeon RX 5700 XT', bus: 'PCI', vram: 4095, vramDynamic: true, …}
length:1
__proto__:Array(0)`

For the command it is:
`AcceleratorCapabilities=
AdapterCompatibility=Advanced Micro Devices, Inc.
AdapterDACType=Internal DAC(400MHz)
AdapterRAM=4293918720
Availability=3
CapabilityDescriptions=
Caption=AMD Radeon RX 5700 XT
ColorTableEntries=
ConfigManagerErrorCode=0
ConfigManagerUserConfig=FALSE
CreationClassName=Win32_VideoController
CurrentBitsPerPixel=32
CurrentHorizontalResolution=1920
CurrentNumberOfColors=4294967296
CurrentNumberOfColumns=0
CurrentNumberOfRows=0
CurrentRefreshRate=144
CurrentScanMode=4
CurrentVerticalResolution=1080
Description=AMD Radeon RX 5700 XT
DeviceID=VideoController1
DeviceSpecificPens=
DitherType=0
DriverDate=20210127000000.000000-000
DriverVersion=27.20.14533.1000
ErrorCleared=
ErrorDescription=
ICMIntent=
ICMMethod=
InfFilename=oem55.inf
InfSection=ati2mtag_Navi10
InstallDate=
InstalledDisplayDrivers=C:\WINDOWS\System32\DriverStore\FileRepository\u0363700.inf_amd64_8ddad2898682b145\B363555\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0363700.inf_amd64_8ddad2898682b145\B363555\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0363700.inf_amd64_8ddad2898682b145\B363555\aticfx64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\u0363700.inf_amd64_8ddad2898682b145\B363555\amdxc64.dll
LastErrorCode=
MaxMemorySupported=
MaxNumberControlled=
MaxRefreshRate=144
MinRefreshRate=50
Monochrome=FALSE
Name=AMD Radeon RX 5700 XT
NumberOfColorPlanes=
NumberOfVideoPages=
PNPDeviceID=PCI\VEN_1002&amp;DEV_731F&amp;SUBSYS_23131458&amp;REV_C1\6&amp;174D5041&amp;0&amp;00000019
PowerManagementCapabilities=
PowerManagementSupported=
ProtocolSupported=
ReservedSystemPaletteEntries=
SpecificationVersion=
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=DESKTOP-TB5MIKQ
SystemPaletteEntries=
TimeOfLastReset=
VideoArchitecture=5
VideoMemoryType=2
VideoMode=
VideoModeDescription=1920 x 1080 x 4294967296 colors
VideoProcessor=AMD Radeon Graphics Processor (0x731F)`

Thank you!

With kind regards,
Lucas

**Comment by sebhildebrandt** [comment]
@Funminotaur3880 this means, the controller is detected, but here we cannot retrieve a temperature. temperatureGpu is currently not supported for all hardware. Closing it for now.
