### ISSUE TITLE
Type definitions not available for wifiInterfaces & wifiConnections in libs/index.d.ts

### ISSUE THREAD

**Issue by parthiganesh** [sebhildebrandt/systeminformation#512]
**Describe the bug**
Type definition not available for wifiInterfaces & wifiConnections

**To Reproduce**
1. used function 'si.wifiInterfaces(cb)'and 'si.wifiConnections(cb)'
2. code snippet 'si.wifiInterfaces(cb)'
3. start app / code
4. See output/error 
```TS2339: Property 'wifiInterfaces' does not exist on type 'typeof import("node_modules/systeminformation/lib/index")'```
```TS2339: Property 'wifiConnections' does not exist on type 'typeof import("node_modules/systeminformation/lib/index")'```

**Current Output**
```TS2339: Property 'wifiInterfaces' does not exist on type 'typeof import("node_modules/systeminformation/lib/index")'```
```TS2339: Property 'wifiConnections' does not exist on type 'typeof import("node_modules/systeminformation/lib/index")'```

**Expected behavior**
Error should not appear. 

**Fix** 
Add the follwoing code to lib/index.d.ts
```
export function wifiInterfaces(cb?: (data: Systeminformation.WifiInterfaceData[]) => any): Promise<Systeminformation.WifiInterfaceData[]>;
export function wifiConnections(cb?: (data: Systeminformation.WifiConnectionData[]) => any): Promise<Systeminformation.WifiConnectionData[]>;
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.6.7
 - OS: All platforms
 - Hardware: All Hardwares

**Additional context**
None

**Comment by sebhildebrandt** [comment]
@parthiganesh thank you!! Willl fix it later today ...

**Comment by sebhildebrandt** [comment]
@parthiganesh fixed. Version 5.6.8 just published.
