### ISSUE TITLE
VirtualBox VMs are not shown in Windows VirtualBox

### ISSUE THREAD

**Issue by parthiganesh** [sebhildebrandt/systeminformation#514]
**Describe the bug**
VirtualBox VMs are not shown in Windows VirtualBox, with the VirtualBox installation path has 'space'.
For example, C:\Program Files\Oracle\VirtualBox\

VBoxManage path should be sanitized

**To Reproduce**
1. Install VirtualBox in directory, C:\Program Files\Oracle\VirtualBox\
2. code snippet 'si.vboxInfo(cb)'
3. vbox info is empty

**Current Code**
File: `lib/util.js`
```
function getVboxmanage() {
  return _windows ? `${process.env.VBOX_INSTALL_PATH || process.env.VBOX_MSI_INSTALL_PATH}\\VBoxManage.exe` : 'vboxmanage';
}
```
**Expected Code/Fix**
File: `lib/util.js`
```
function getVboxmanage() {
  return _windows ? `"${process.env.VBOX_INSTALL_PATH || process.env.VBOX_MSI_INSTALL_PATH}\\VBoxManage.exe"` : 'vboxmanage';
}
```
Sanitize the path by adding quote.

**Environment (please complete the following information):**
 - systeminformation package version: 5.6.9
 - OS: Windows
 - Hardware: any

**Comment by sebhildebrandt** [comment]
@parthiganesh thank you! Fixed. Version 5.6.10 just published.
