### ISSUE TITLE
service list is always empty on RHEL & CentOS 7.x/8

### ISSUE THREAD

**Issue by parthiganesh** [sebhildebrandt/systeminformation#516]
**Describe the bug**
service list is always empty, i.e., systemctl services are not listed

**To Reproduce**
1. used function 'si.services('*', cb)'
2. code snippet 'si.services('*', cb)'

**Current Output**
[]

**Add code**
file: `lib/processes.js`
```
try {
 const tmpsrv = execSync('systemctl --type=service --no-legend 2> /dev/null').toString().split('\n');
 srvs = []
 for (const s of tmpsrv) {
   const name=s.split('.service')[0];
   if (name) {
     srvs.push(name);
   }
 }
 srvString = srvs.join('|');
} catch (e) {
 // existing code!
}
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.6.10
 - OS: linux, centos 7, 8, linux with systemctl
 - Hardware any

**Additional context**

**Comment by sebhildebrandt** [comment]
@parthiganesh I made a fix for that ... pushed the code to GitHub. Can you pull it from here and test if this fixes the problem as expected? Thank you in advance for your help!

**Comment by parthiganesh** [comment]
@sebhildebrandt I have attached the fix (zipped the file, as git doesn't support uploading js file)

Fix: systemctl command has to be tried before trying service command

[processes.zip](https://github.com/sebhildebrandt/systeminformation/files/6434040/processes.zip)

**Comment by sebhildebrandt** [comment]
@parthiganesh thank you. Will test this on all servers here ...

**Comment by sebhildebrandt** [comment]
@parthiganesh fixed! Thank you for your support. Version 5.6.19 just released
