### ISSUE TITLE
Non-latin characters in results

### ISSUE THREAD

**Issue by mvarakin** [sebhildebrandt/systeminformation#520]
Windows 10 with Russian locale 

Sometimes strings come in Russian (this is more less ok, we can deal with it)

![2021-04-12 15 46 01](https://user-images.githubusercontent.com/29253114/114396535-5baef080-9ba6-11eb-9da7-f10af0e05364.jpg)

But sometimes strings come in unreadable format

![2021-04-12 15 46 07](https://user-images.githubusercontent.com/29253114/114396569-62d5fe80-9ba6-11eb-8234-5e1152aa9f93.jpg)

On the example above there is no way to find default iface among all the list as there is no ID but only description which is unreadable.

**Comment by mvarakin** [comment]
Hi! Any news here?

**Comment by sebhildebrandt** [comment]
@mvarakin  ... i have refactored wmic that it should now support UTF8 characters. As I want to have confirmation that this works before publishing it to npm, can you test all functions on your side? Easiest way would be to close from GitHub and run tests like so:

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```
then go through all tests and see if results are fine on your side.

Thank you in advance!

**Comment by sebhildebrandt** [comment]
@mvarakin Can you test this one more time? I made a transition to powerShell also for `networkInterfaces()`. Hope that solves the problem now.

**Comment by sebhildebrandt** [comment]
@mvarakin, @Phamier ... as #610 addressed the same problem and is solved, I assume, that this is also fine. Can you confirm that?

**Comment by Phamier** [comment]
Yes! It's working properly now.
![image](https://user-images.githubusercontent.com/24634942/142849835-098a4db3-4716-440d-add8-431d16551e04.png)

**Comment by Phamier** [comment]
It returns wrong iface, but It's a bug of Windows.

**Comment by sebhildebrandt** [comment]
@Phamier thank you for reporting!

**Comment by mvarakin** [comment]
Thanks a lot!
