### ISSUE TITLE
Wifi Connections on Windows produces empty array

### ISSUE THREAD

**Issue by Colm-DO** [sebhildebrandt/systeminformation#525]
When using wifiConnections on Windows, it returns an empty array, even when WiFi is active on the device. 

'netsh wlan show interfaces' is the command used, which works and produces the output like so:

There is 1 interface on the system:

    Name                   : WiFi
    Description            : Marvell AVASTAR Wireless-AC Network Controller
    GUID                   :  xxxxx
    Physical address       : xxxxxxx
    State                  : connected
    SSID                   : xxxxxx
    BSSID                  : xxxxxxx
    Network type           : Infrastructure
    Radio type             : 802.11ac
    Authentication         : WPA2-Personal
    Cipher                 : CCMP
    Connection mode        : Auto Connect
    Channel                : 40
    Receive rate (Mbps)    : 866.5
    Transmit rate (Mbps)   : 866.5
    Signal                 : 100%
    Profile                : xxxxxxxx

    Hosted network status  : Not available

When this is passed through `const parts = stdout.toString().split(':\r\n\r\n');` on line 568 wifi.js.

Variable 'parts' contains this:

  '\r\n' +
    'There is 1 interface on the system: \r\n' +
    '\r\n' +
    '    Name                   : WiFi\r\n' +
    '    Description            : Marvell AVASTAR Wireless-AC Network Controller\r\n' +
    '    GUID                   : xxxxxx\r\n' +
    '    Physical address       : xxxxxxxxx\r\n' +
    '    State                  : connected\r\n' +
    '    SSID                   : xxxxx\r\n' +
    '    BSSID                  : xxxxxxx\r\n' +
    '    Network type           : Infrastructure\r\n' +
    '    Radio type             : 802.11ac\r\n' +
    '    Authentication         : WPA2-Personal\r\n' +
    '    Cipher                 : CCMP\r\n' +
    '    Connection mode        : Auto Connect\r\n' +
    '    Channel                : 40\r\n' +
    '    Receive rate (Mbps)    : 866.5\r\n' +
    '    Transmit rate (Mbps)   : 866.5\r\n' +
    '    Signal                 : 100% \r\n' +
    '    Profile                : xxxxxxx\r\n' +
    '\r\n' +
    '    Hosted network status  : Not available\r\n' +
    '\r\n'

I changed the split to this: `const parts = stdout.toString().split(': \r\n');`

which appears to have worked, and I get a formatted JSON output of:

  {
    id: 'Marvell AVASTAR Wireless-AC Network Controller',
    iface: '',
    model: 'WiFi',
    ssid: 'xxxxxx',
    bssid: 'xxxxxx',
    channel: 40,
    frequency: 5200,
    type: '802.11ac',
    security: 'WPA2-Personal',
    signalLevel: '100%',
    txRate: 866
  }

This appears to have solved the problem, however I can't test for more than 1 WiFi interface.
Also, 'iface' shows as empty, when on the docs it states Windows supports it, so not sure if that change broke it, or if it does not work on Windows.

Thanks.

**Comment by gilisegal** [comment]
Any progress with this? @sebhildebrandt

**Comment by zprjk** [comment]
I'm also getting this issue on Windows.

```
"Surface Pro"
"Microsoft Windows 10 Pro"
"10.0.19042"
```
