### ISSUE TITLE
WMIC Nic NetEnabled property is not  available in Windows XP

### ISSUE THREAD

**Issue by summerswell-ie** [sebhildebrandt/systeminformation#526]
**Describe the bug**
When calling `networkInterfaces` in Windows XP, the `getWindowsNics` method tries to get the `NetEnabled` property of the NIC class, but the NetEnabled property is not available in Windows XP. Later in `parseLinesWindowsNics` the NetEnabled property is used to filter the results of wmic nic. This results in error output to the console.

**To Reproduce**
```
const si = require( 'systeminformation');
console.log( si.version() );
return si.networkInterfaces()
  .then( data => {
    console.log( data );
  })

```

**Current Output**
```
5.6.12
Node - <ComputerName>
ERROR:
Code = 0x80041017
Description = Invalid query
.
.
.
```

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: WindowsXP
 - Hardware: VMWare VM

**Comment by sebhildebrandt** [comment]
@summerswell-ie should be fixed. At least you should not get any error here ... can you test it on your side? Version 5.6.17 and Version 4.34.23 just released.

**Comment by summerswell-ie** [comment]
I've tested 5.6.17 in Windows XP using Node 4.9.1 and it is working as expected now.

**Comment by sebhildebrandt** [comment]
@summerswell-ie thank you for your support!
