### ISSUE TITLE
[Question] What structure has si.diskLayout()[0].smartData object?

### ISSUE THREAD

**Issue by gg187on** [sebhildebrandt/systeminformation#527]
Hello,

I was looking on documentation https://systeminformation.io/filesystem.html
There is:

```
 smartData: {
      json_format_version: [Array],
      smartctl: [Object],
      device: [Object],
      model_name: 'SAMSUNG xxxxxxxxxxxx-xxxx',
      serial_number: '...serial....',
      ...
    }
 ```
 
 but I can't see what [Object] is (or what data it contains), can someone please write here some real example of data?
I need to know structure of these data, but the problem is, my disk doesn't provide any S.M.A.R.T data, so I get only empty array, so I need to know this structure to be able to create and test my application.

Thanks if someone will provide full example of that object.

**Comment by sebhildebrandt** [comment]
@gg187on sorry my fault. Will add structure tomorrow. In the meanwhile Index.d.ts file could help.

**Comment by Mlocik97** [comment]
Oh thanks, I somehow overlooked index.d.ts file,... thanks.

**Comment by gg187on** [comment]
Oh thanks, I overlooked that file. .d.ts helped.

**Comment by sebhildebrandt** [comment]
@gg187on I see that the index.d.ts structure is only partially correct. Will update it the next few days.

**Comment by sebhildebrandt** [comment]
@gg187on updated index.d.ts to select smartData more accurately.
