### ISSUE TITLE
cpu_percent from si.dockerContainerStats is inconsistent with the output of "docker stats"

### ISSUE THREAD

**Issue by haojun** [sebhildebrandt/systeminformation#53]
Hi, 

I'm using si.dockerContainerStats to get the cpu usage of the container. The strange thing is that the output is nearly ten times the output of docker cli 'docker stats'. 

For example, while the output of docker stats is 90%, the output of si is nearly 900.

Not sure what happens?

**Comment by sebhildebrandt** [comment]
Hi, 

I guess I need to check it ... 900% is not a good number ;-)

**Comment by sebhildebrandt** [comment]
So I just published a fix for that ... sorry for the delay!
