### ISSUE TITLE
processes(): "mem" value missing on Windows

### ISSUE THREAD

**Issue by GitSquared** [sebhildebrandt/systeminformation#531]
**Describe the bug**
From the [docs](https://systeminformation.io/processes.html):
![image](https://user-images.githubusercontent.com/24496417/117280008-76514e00-ae62-11eb-87b7-33a82ce60dab.png)

I can find this value on Linux but it's missing on windows.

**To Reproduce**
`systeminformation.processes().then(d => console.log(d))` on Windows

**Current Output**
```
...
list: [
	{
		...
		cpu: 0.004,
		pmem: 0.003, // Should this be mem?
		memRss: 6008,
		memVsz: 1128,
		...
]
...
```

**Expected behavior**
A `mem` value accross all OSs that reports memory usage of the process in %.

**Environment (please complete the following information):**
 - systeminformation package version: `5.6.17`
 - OS: Windows 10
 - Hardware: Some Lenovo 2-in-1 laptop, should be irrelevant

**Additional context**
(in eDEX-UI)

**Comment by GitSquared** [comment]
I think this might be a simple fix of renaming this to `mem` to conform with the doc and behavior on other platforms:
https://github.com/sebhildebrandt/systeminformation/blob/2d5a24068d536cc5e2991108beb6af9eee7edf99/lib/processes.js#L815

**Comment by sebhildebrandt** [comment]
@GitSquared my fault!! Sorry ... fixed. Version 5.6.18 just released.

**Comment by GitSquared** [comment]
Np! Thank you for fixing it so quickly :racing_car:
