### ISSUE TITLE
Cumulative network bytes

### ISSUE THREAD

**Issue by fabiospampinato** [sebhildebrandt/systeminformation#535]
Would it be possible to retrieve cumulative rx and tx values for network interfaces (and perhaps disks for completeness) since the first call to this library?

I could keep track of those things myself, but I feel like this is something the library itself should provide some methods for.

**Comment by sebhildebrandt** [comment]
@fabiospampinato `si.networkStats()` gives you the overall rx and tx bytes since startup of the machine. I do not see a good reason why this to store the values since first call to this function. I would see this as a special use case. What do you think?

**Comment by fabiospampinato** [comment]
I see, that's just what I needed, but I thought the library was providing the current/per-second value already, so that's missing then I think, could that be provided too?

Basically I sort of need the data necessary to create something similar to Glances' interface:

![image](https://user-images.githubusercontent.com/1812093/118185954-0b40e200-b435-11eb-9f5f-d4563170c4f6.png)

And I don't see how to retrieve the per-second values via this library, and the load values are missing too, for which I commented on the other issue.

**Comment by fabiospampinato** [comment]
Wait that's already there with `tx_sec` and `rx_sec`, I totally overlooked that.

**Comment by sebhildebrandt** [comment]
@fabiospampinato : Per second values can be retrieved as describes in the docs:
https://systeminformation.io/statsfunctions.html
