### ISSUE TITLE
si.battery() shows wrong results on devices with more than one battery

### ISSUE THREAD

**Issue by plakak** [sebhildebrandt/systeminformation#537]
On certain laptops with internal and external batteries like ThinkPad T450s the library wrongly reports no battery present in Windows when device is on external battery.

The issue is  that `wmic`  reports two batteries instead of one and systeminformation does not account for such possibility.

```
PS C:\Windows\system32> wmic Path Win32_Battery Get BatteryStatus,EstimatedChargeRemaining /value
BatteryStatus=
EstimatedChargeRemaining=94
BatteryStatus=1
EstimatedChargeRemaining=74
```

I don't own this laptop so I can't check how this behaves in Linux. It was an issue reported by a user of my app.

I've forked the library and fixed the issue for myself. Here it is:
https://github.com/sebhildebrandt/systeminformation/compare/master...plakak:master

I don't know if this is the direction you'd like to take, but if yes, I can create PR with it. 

**Environment (please complete the following information):**
 - systeminformation package version: 5.6.21
 - OS: Windows 10
 - Hardware: ThinkPad T450s

**Comment by sebhildebrandt** [comment]
@plakak: I need to have a look on it. Can you provide the full output of

```
wmic Path Win32_Battery Get BatteryStatus, DesignCapacity, EstimatedChargeRemaining, DesignVoltage, FullChargeCapacity /value
```

And 

```
wmic Path Win32_Battery Get /value 
```

On this machine? 

Best regards

**Comment by plakak** [comment]
@sebhildebrandt 

This is the output when the AC is disconnected
```
C:\Windows\system32>wmic Path Win32_Battery Get /value
Availability=3
BatteryRechargeTime=
BatteryStatus=1
Caption=Internal Battery
Chemistry=6
ConfigManagerErrorCode=
ConfigManagerUserConfig=
CreationClassName=Win32_Battery
Description=Internal Battery
DesignCapacity=
DesignVoltage=10526
DeviceID=20115SANYO45N1773
ErrorCleared=
ErrorDescription=
EstimatedChargeRemaining=15
EstimatedRunTime=15
ExpectedBatteryLife=
ExpectedLife=
FullChargeCapacity=
InstallDate=
LastErrorCode=
MaxRechargeTime=
Name=45N1773
PNPDeviceID=
PowerManagementCapabilities={1}
PowerManagementSupported=FALSE
SmartBatteryVersion=
Status=OK
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=DESKTOP-4J3BIGJ
TimeOnBattery=
TimeToFullCharge=


Availability=
BatteryRechargeTime=
BatteryStatus=
Caption=Internal Battery
Chemistry=6
ConfigManagerErrorCode=
ConfigManagerUserConfig=
CreationClassName=Win32_Battery
Description=Internal Battery
DesignCapacity=
DesignVoltage=11073
DeviceID= 2035SANYO45N1775
ErrorCleared=
ErrorDescription=
EstimatedChargeRemaining=3
EstimatedRunTime=71582788
ExpectedBatteryLife=
ExpectedLife=
FullChargeCapacity=
InstallDate=
LastErrorCode=
MaxRechargeTime=
Name=45N1775
PNPDeviceID=
PowerManagementCapabilities={1}
PowerManagementSupported=FALSE
SmartBatteryVersion=
Status=
StatusInfo=
SystemCreationClassName=Win32_ComputerSystem
SystemName=DESKTOP-4J3BIGJ
TimeOnBattery=
TimeToFullCharge=
```

And this is when AC is connected
![image (2)](https://user-images.githubusercontent.com/13939486/118478443-2c911f00-b710-11eb-9b17-5e6edf921cb0.png)

I didn't get this one with charger disconnected but the values look like I posted in the first post here

```
PS C:\Windows\system32> wmic Path Win32_Battery Get BatteryStatus,EstimatedChargeRemaining /value
BatteryStatus=
EstimatedChargeRemaining=94

BatteryStatus=1
EstimatedChargeRemaining=74
```

Well basically you have all the info from the full /Get either way :) 


With such return value `hasBattery` was false for this device.
My solution to that was to get separately each battery, parse them with the current methods and then if even one of them reports correct status show data of this battery as main battery, and add data of the other battery to new field `additionalBatteries`. 
Probably the cleaner solutions would be to return array by default from si.battery() with each battery separately but that would be a huge braking change.

**Comment by sebhildebrandt** [comment]
@plakak thank you! This is exactly what I needed. Will provide a solution a little bit different to your proposal. Need also to maintain node version 4 compatibility.

**Comment by sebhildebrandt** [comment]
@plakak I now pushed a code to GitHub that should fix the problem. As you already mentioned, for the future it would be good to have the result of `batteries()` as an array but for now I am leaving it like it is as this would be a breaking change. For now I am adding additional batteries to an extra property. So it would be nice if you can grab the code from GitHub and test it on the specific machines where you had problems. Please report back, if you see any problems.

**Comment by plakak** [comment]
@sebhildebrandt Thanks! This follows the same API I assumed in my fix so I won't have to make any changes in the app code when switching back to main library repo. Awesome 🙂 

I'll create executable from the latest version and send to the owner of the machine in question for tests.

**Comment by sebhildebrandt** [comment]
@plakak exactly! But I cannot test it here due to missing laptop running windows ;-) Thank you so much for helping getting this stable!

**Comment by sebhildebrandt** [comment]
@plakak Version 5.7.6 just released, can you try it?
