### ISSUE TITLE
Call to smartctl fails with large number of disks due to maxBuffer exceeded

### ISSUE THREAD

**Issue by fm5003** [sebhildebrandt/systeminformation#540]
**Describe the bug**
filesystem.js line 854 uses exec without specifying maxBuffer. The default value for maxBuffer is 200kb. Adding

``exec(cmdFullSmart, {maxBuffer: 1024 * 1024}, function (error, stdout) { ``

resolved the issue. 

The command fails silently (no smart data is returned), with no error reported. 

**Expected behavior**
See above

**Environment (please complete the following information):**
 - systeminformation package version: 5.6.21
 - OS: Debian Bullseye (kernel 5.10)

**Comment by sebhildebrandt** [comment]
@fm5003 thank you. Fixed. Version 5.6.22 just released.
