### ISSUE TITLE
Printer function not work with online printer

### ISSUE THREAD

**Issue by ferlolo** [sebhildebrandt/systeminformation#541]
**Describe the bug**
When used function "printer" with online printer or pdf printer not show the list of printer and no generate printer property in object.

![image](https://user-images.githubusercontent.com/16939698/118766483-c544ad80-b87c-11eb-88af-d03abd9d7dcb.png)

 - systeminformation package version: 4.34.7
 - OS: Ubuntu and Windows 7

**Comment by sebhildebrandt** [comment]
@ferlolo `si.printer()` is not part of `systeminformation` Version 4. You can try Version 5 and it would be great if you try the following code directly in `node`:

```
const si = require('systeminformation');
si.printer().then(data => console.log(data));
```

If you still encounter problems here, please post the full output of the above code.
Closing it for now.
