### ISSUE TITLE
si.diskLayout(cb)  [0].smartData  Not getting Smart Data 

### ISSUE THREAD

**Issue by khanakhun** [sebhildebrandt/systeminformation#542]
[0].smartData | X | &nbsp; | &nbsp; | &nbsp; | &nbsp; | full S.M.A.R.T data from smartctlrequires at least smartmontools 7.0(see Known Issues)
-- | -- | -- | -- | -- | -- | --

Basically, I want to get Harddisk Health Using this Library is this Possible, because  right now it shows nothing for smartData

**Comment by sebhildebrandt** [comment]
@khanakhun hi, can you be more specific on your environment?

- what is your OS, which version/distribution
- which version of smartmon tools do you have installed

Can you also run this code snippet and post the full output here:

```
const si = require('systeminformation');
si.diskLayout().then(data => console.log(data));
```

**Comment by khanakhun** [comment]
> @khanakhun hi, can you be more specific on your environment?
> 
> * what is your OS, which version/distribution
> * which version of smartmon tools do you have installed
> 
> Can you also run this code snippet and post the full output here:
> 
> ```
> const si = require('systeminformation');
> si.diskLayout().then(data => console.log(data));
> ```

{
    device: 'SCSI\\DISK&amp;VEN_SANDISK&amp;PROD_SSD\\4&amp;62C5D10&amp;0&amp;00
0000',
    type: 'SSD',
    name: 'SanDisk SSD PLUS 120GB',
    vendor: '(Standard disk drives)',
    size: 120039736320,
    bytesPerSector: 512,
    totalCylinders: 14594,
    totalHeads: 255,
    totalSectors: 234452610,
    totalTracks: 3721470,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: 'UE5100RL',
    serialNum: '203582800717',
    interfaceType: 'RAID',
    smartStatus: 'Ok',
    temperature: null
  }
]



> @khanakhun hi, can you be more specific on your environment?
> 
> * what is your OS, which version/distribution
> * which version of smartmon tools do you have installed
> 
> Can you also run this code snippet and post the full output here:
> 
> ```
> const si = require('systeminformation');
> si.diskLayout().then(data => console.log(data));
> ```
{
    device: 'SCSI\\DISK&amp;VEN_SANDISK&amp;PROD_SSD\\4&amp;62C5D10&amp;0&amp;00
0000',
    type: 'SSD',
    name: 'SanDisk SSD PLUS 120GB',
    vendor: '(Standard disk drives)',
    size: 120039736320,
    bytesPerSector: 512,
    totalCylinders: 14594,
    totalHeads: 255,
    totalSectors: 234452610,
    totalTracks: 3721470,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: 'UE5100RL',
    serialNum: '203582800717',
    interfaceType: 'RAID',
    smartStatus: 'Ok',
    temperature: null
  }
]

This is what I get, except for smart data I checked in Know issues, there is was mentioned to install smartmontools  for windows, still, I don't get the smart data array, and thank you so much for replying to this thread, this is a very helpful library, I'm using this to develop an electron app to scan for system hardware and software specifications, Also it would be great to know if there is any method for wmic product get name, version, vendor, install date. Thank you so much

**Comment by sebhildebrandt** [comment]
@khanakhun so ok, you are using Windows? As you can see in the docs. I do not support this property for Windows. 


| Function        | Result object | Linux | BSD | Mac | Win | Sun | Comments |
| --------------- | ------------- | ----- | ------- | --- | --- | --- | -------- |
| si.diskLayout(cb) | [{...}] | X |  | X | X |  | physical disk layout (array) |
| | [0].device | X |  | X |  |  | e.g. /dev/sda |
| | [0].type | X |  | X | X |  | HD, SSD, NVMe |
| | ... |  |  | |  |  |  ... |
| | [0].smartData | X |  |  |  |  | full S.M.A.R.T data from smartctl<br>requires at least smartmontools 7.0 |


Extended Smart-Data is not available (to my knowledge). If you have any idea how I would get this, of course I will integrate it ... closing it for now

**Comment by sebhildebrandt** [comment]
@khanakhun but if you have smartmoxntools installed om Windows, can you provide:

- Version of Smartmontools
- full output of `smartctl -a -j "C:\"` (not sure if this is correct, maybe you need to tweak the command)

Thank you!

**Comment by sebhildebrandt** [comment]
@khanakhun I am reopening this because as I made some research, it would be possible to add this also for windows. I need to work on it so it might take some time.

**Comment by khanakhun** [comment]
> smartctl --scan

Thank you so much for your response, smartctl -a -j "C:\"  Using this I'm getting a  huge object with many data init related to DISK most of it can be retrieved using si.disk(), but I'm unable to understand how to get harddisk health.

**Comment by sebhildebrandt** [comment]
@khanakhun related to the previous post ... "Using this I'm getting a huge object with many data" ... well but this is, what you where asking for, right? This is, what smartmontools gives back and I am attaching it to the `diskLayout()` result as I do it in linux. Not sure, if this is now a misunderstanding ...

Anyway, I currently made some progress here and can provide a first version soon.

**Comment by sebhildebrandt** [comment]
@khanakhun now smart data is also available on windows (if smartmontools are installed). Version 5.7.0 just published
