### ISSUE TITLE
Physical machine is shown as Virtual machine if dmesg has the word 'virtual'

### ISSUE THREAD

**Issue by parthiganesh** [sebhildebrandt/systeminformation#544]
Output of **si.system(cb)** is 
`{
  manufacturer: 'Supermicro',
  model: 'X7SPA-H',
  version: '1234567890',
  serial: '1234567890',
  uuid: '49434d53-0200-7a85-c40c-857ac40c4877',
  sku: '-',
  virtual: true,
  virtualHost: 'VMware'
}`

**Output of dmesg command used in the script:**
```
[root@localhost agent]# dmesg 2>/dev/null | grep -iE "virtual|hypervisor" | grep -iE "vmware|qemu|kvm|xen" | grep -vi "Nested Virtualization"
[   23.783786] sysfs: cannot create duplicate filename '/devices/virtual/misc/xenadevice0'
```

**in file lib/system.js line 168**
```
stdout.toString().toLowerCase().indexOf('vmware')
```
will return -1 if vmware is not substring of the output, that is why 'virtualHost' is set as VMware.
I recommend using `includes` like this `stdout.toString().toLowerCase().includes('vmware')` 

**Environment:** Fedora release 20 (Heisenbug)
**Systeminformation version:** 5.7.1

**Comment by sebhildebrandt** [comment]
@parthiganesh would this work?

```
dmesg 2>/dev/null | grep -iE "virtual|hypervisor" | grep -iE "vmware|qemu|kvm|xen" | grep -viE "Nested Virtualization|/virtual"
```

This should then not returning any output on this machine, right?

**Comment by sebhildebrandt** [comment]
@parthiganesh just released a version that should fix the problem. Version 5.7.2 just released. Can you check it on your side?

**Comment by parthiganesh** [comment]
@sebhildebrandt yes this is fixed now. Thank you :)
