### ISSUE TITLE
Checking UEFI on Windows

### ISSUE THREAD

**Issue by spermlord** [sebhildebrandt/systeminformation#546]
**Describe the bug**
On some PC, the script "findstr /C:"Detected boot environment" "%windir%\\Panther\\setupact.log"" reports EFI not UEFI.

**To Reproduce**
1. used function '...'
2. code snippet '....'
3. start app / code
4. See output/error '....'

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
 - systeminformation package version: 5.7.2
 - OS: Windows 10 21H1
 - Hardware [e.g. MacBook Pro 13]

**Additional context**
![image](https://user-images.githubusercontent.com/37042810/119637320-bdb67300-be3f-11eb-9b61-db4bc09a0efd.png)

**Comment by spermlord** [comment]
> @spermlord thank you! Can you also post output of
> 
> ```
> echo %firmware_type%
> ```

Here
![image](https://user-images.githubusercontent.com/37042810/119661419-7be6f600-be5a-11eb-8355-d2562d4a8940.png)

**Comment by sebhildebrandt** [comment]
Think you @spermlord . Should be fixed now. Version 5.7.3 just published. Can you check it on your side?

**Comment by spermlord** [comment]
Thanks! I will update dependencies and check it in minute.

**Comment by sebhildebrandt** [comment]
@spermlord About your comment to my fix: Correct! did this already locally but forgot to push this change ... anyway. the works hopefully. And in the next push, this is cleaned up.
