### ISSUE TITLE
memLayout return wrong clockSpeed when have two diffenent speed memory

### ISSUE THREAD

**Issue by xtouching** [sebhildebrandt/systeminformation#549]
OS: windows10X64

![image](https://user-images.githubusercontent.com/19708081/121167228-53142700-c884-11eb-9bcb-f637c5897420.png)
![image](https://user-images.githubusercontent.com/19708081/121167273-5dcebc00-c884-11eb-936f-6f4cacf50ff2.png)

maybe in memory.js.  when is  _windows
```
clockSpeed: parseInt(util.getValue(lines, 'ConfiguredClockSpeed', '='), 10) || 0 
```

canbe 
```
clockSpeed: (util.getValue(lines, 'ConfiguredClockSpeed', '=')) ? parseInt(util.getValue(lines, 'ConfiguredClockSpeed', '='), 10) : (util.getValue(lines, 'Speed:') ? parseInt(util.getValue(lines, 'Speed:'), 10) : -1)),
```

**Comment by sebhildebrandt** [comment]
@xtouching can you provide the output of 

```
wmic memorychip get /value
```

as TEXT (not screen photo!)

**Comment by xtouching** [comment]
> @xtouching can you provide the output of
> 
> ```
> wmic memorychip get /value
> ```
> 
> as TEXT (not screen photo!)

can you delete this issue, please ? the picture contains other's info watermak, I will provide text later, thanks!!!

**Comment by sebhildebrandt** [comment]
@xtouching delete it completely??

**Comment by xtouching** [comment]
@sebhildebrandt Actually I don't know. I just want this picture not to be seen by others. Delete and open another one is the best way? I take your opinion, thanks~~~

**Comment by sebhildebrandt** [comment]
@xtouching done ... just deleted the images ...

**Comment by xtouching** [comment]
> @xtouching done ... just deleted the images ...

others can see the images from edit history ? thanks!! Love you so much!! 

this is the text!
[memory.txt](https://github.com/sebhildebrandt/systeminformation/files/6615995/memory.txt)

**Comment by sebhildebrandt** [comment]
@xtouching OK, will delete it completely ... can you create this issue once again?

**Comment by xtouching** [comment]
> @xtouching OK, will delete it completely ... can you create this issue once again?

OK~~~i will create this issue once again!! thanks!
