### ISSUE TITLE
memLayout return wrong clockSpeed when have two diffenent speed memory

### ISSUE THREAD

**Issue by xtouching** [sebhildebrandt/systeminformation#550]
os: window7 x 64 
memory1: Kingston DDR4 2133 MHz
memory2: Kingston DDR4 2666 MHz
detailed information in the text file, thanks!!!
[memory.txt](https://github.com/sebhildebrandt/systeminformation/files/6616037/memory.txt)

**Comment by xtouching** [comment]
maybe when _windows in memory.js
```
clockSpeed: parseInt(util.getValue(lines, 'ConfiguredClockSpeed', '='), 10) || 0,
```
canbe 
```
clockSpeed: parseInt(util.getValue(lines, 'ConfiguredClockSpeed', '='), 10) || parseInt(util.getValue(lines, 'Speed', '='), 10) || 0 ,
```
for these special situation?

**Comment by sebhildebrandt** [comment]
@xtouching actually, catching the second option (testing also `speed`) makes sense but in your case, both are 2133, so I do not see how to get the 2666 as given in your example ...

**Comment by xtouching** [comment]
> @xtouching actually, catching the second option (testing also `speed`) makes sense but in your case, both are 2133, so I do not see how to get the 2666 as given in your example ...

yes.....so can we add other param in result as current speed ?

**Comment by xtouching** [comment]
at least i wanna get the current speed when i get the wrong clockSpeed.
or, do we have other method get the clockSpeed
both is ok~~~~
thanks~~~love you~~~

**Comment by sebhildebrandt** [comment]
@xtouching will have a look at it tomorrow ...

**Comment by sebhildebrandt** [comment]
@xtouching should be fixed now. Can you check it on your side? Version 5.7.5. just released,

**Comment by xtouching** [comment]
> @xtouching should be fixed now. Can you check it on your side? Version 5.7.5. just released,

OK，I will check later ，I use version 4.23.5 now.
I need to check the changes vs 5.7.5.
Thanks so much!!!
