### ISSUE TITLE
CPU Temperature incorrect in Linux Ubuntu 21.04

### ISSUE THREAD

**Issue by lportanel** [sebhildebrandt/systeminformation#552]
**Describe the bug**
Executing si.cpuTemp() will return the temperature of another sensor.

**To Reproduce**
1. Just execute `si.cpuTemperature().then(data => console.log(data))` and analyze the output.

**Current Output**
The current output is 
`{ main: 34.9, cores: [], max: 34.9, socket: [], chipset: null }`
which corresponds to the temperature of a _nvme_ sensor.

**Expected behavior**
To return the temperature of the _k10temp_ sensor.

**Environment:**
 - systeminformation package version: 5.7.7
 - OS: Ubuntu 21.04
 - Hardware:
 * MoBo Asus Rog Strix B550 Mini ITX 
 * Ryzen 9 5950X AM4 Zem 3
 * Sabrent 2TB Rocket Nvme PCIe 4.0 M.2

**Additional context**
Executing `sensors` will throw this:
```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +38.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +43.0°C  
Tdie:         +43.0°C  

jc42-i2c-1-18
Adapter: SMBus PIIX4 adapter port 0 at 0b00
temp1:        +32.2°C  (low  =  +0.0°C)                  ALARM (HIGH, CRIT)
                       (high =  +0.0°C, hyst =  +0.0°C)
                       (crit =  +0.0°C, hyst =  +0.0°C)

nvme-pci-0100
Adapter: PCI adapter
Composite:    +31.9°C  (low  =  -0.1°C, high = +69.8°C)
                       (crit = +109.8°C)

jc42-i2c-1-19
Adapter: SMBus PIIX4 adapter port 0 at 0b00
temp1:        +31.8°C  (low  =  +0.0°C)                  ALARM (HIGH, CRIT)
                       (high =  +0.0°C, hyst =  +0.0°C)
                       (crit =  +0.0°C, hyst =  +0.0°C)

nvme-pci-0500
Adapter: PCI adapter
Composite:    +21.9°C  (low  = -273.1°C, high = +82.8°C)
                       (crit = +84.8°C)
Sensor 1:     +21.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +39.9°C  (low  = -273.1°C, high = +65261.8°C)
```

And in the `lib/cpu.js` file, the stdout if line 964 will throw this:
```
Composite___31850
Composite___21850
Sensor 1___21850
Sensor 2___39850
Tctl___43250
Tdie___43250
```

Here, the CPU temp is in the last line: Tdie, but the script incorrectly assumes the first line is the CPU temp, which in this case corresponds to "Composite", a _nvme-pci-0100_ sensor.

I applied a patch to `lib/cpu.js` file, just adding this piece of code on line 967:
```
            const tdiePos = stdout.indexOf('Tdie');
            if (tdiePos !== -1) {
              stdout = stdout.substring(tdiePos)
            }
```
It first checks if the output contains a _Tdie_ sensor information. If it does, it will start parsing the _stdout_ from there and throw the correct CPU sensor information.

**Comment by sebhildebrandt** [comment]
@lportanel thank you for providing detailed information!!! Will have a look at it ...

**Comment by sebhildebrandt** [comment]
@lportanel version 5.9.3 just published. Should now fix this problem. Can you test it on your side? Thank you so much!!
