### ISSUE TITLE
Get empty data when running service in docker environment

### ISSUE THREAD

**Issue by EngAhmedMahmoud** [sebhildebrandt/systeminformation#553]
I developed a nodejs application and inside this application i am trying to get information about:

1.  `system-serial`
2. `system-uuid`
3. `os-serial`

when running service in development mode i get the information no issue on that but once i create docker image and run this image within container i get **empty data**.

When running the application using docker

![image](https://i.ibb.co/xYRdwht/system-Info.png)

When running application in development mode using `npm start`

![image](https://i.ibb.co/LC1tHW2/system-Info-Without-Docker.png)

**Comment by sebhildebrandt** [comment]
Hi @EngAhmedMahmoud 
I guess first of all this might also depend on which base image you are using. `alpine` e.g. would have less information as this is one of the tiniest distribution. I tried it on the official `ubuntu`docker image and got the following results:

## System

```
si.system() 

{
  manufacturer: '',
  model: 'Docker Container',
  version: '1.0',
  serial: 'None',
  uuid: '2f834619-0000-0000-9f56-2a169af79919',
  sku: '-',
  virtual: false
}
```

Underlying commands:

**Serial:**
```
# cat /sys/devices/virtual/dmi/id/product_serial
None
```

**UUID**
```
# cat /sys/devices/virtual/dmi/id/product_uuid
2f834619-0000-0000-9f56-2a169af79919
```

## OS

```
si.osInfo()

{
  platform: 'linux',
  distro: 'Ubuntu',
  release: '20.04.2 LTS',
  codename: 'Focal Fossa',
  kernel: '5.10.25-linuxkit',
  arch: 'x64',
  hostname: 'b472c5d34181',
  fqdn: 'b472c5d34181',
  codepage: 'UTF-8',
  logofile: 'ubuntu',
  serial: '',
  build: '',
  servicepack: '',
  uefi: false
}
```

Underlying commands:
```
# cat /var/lib/dbus/machine-id
cat: /var/lib/dbus/machine-id: No such file or directory

# cat /etc/machine-id
```

... which means that the machine ID and product serial is not available. Therefore also systeminformation cannot retrieve them. I guess `alpine` is even more restrictive and none of those values would exist.

Closing it for now. But if you have any further idea if UUID or serial is available in your docker image (distribution), I would be happy if you can inform me.
