### ISSUE TITLE
Can not get os specific UUID 

### ISSUE THREAD

**Issue by zhangzhui** [sebhildebrandt/systeminformation#554]
**Describe the bug**
can not get os specific UUID use os.uuid()

**To Reproduce**
1. create a win32 application
2. run under window 10 x64
3. start app
4. the os.uuid().os is empty

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: [windows 10 x64]
 - App: [win32]

**Additional context**
[node-machine-id](https://www.npmjs.com/package/node-machine-id)is no problem
here is the snapshot
![image](https://user-images.githubusercontent.com/7258591/124871574-c7162c00-dff6-11eb-818a-418d49170b23.png)

**Comment by sebhildebrandt** [comment]
@zhangzhui thank you ... will have a look at it. Thank you for providing detailed additional information!!

**Comment by sebhildebrandt** [comment]
@zhangzhui can you grep the latest code from GitHub (replace lib/osinfo.js in your node_modules/systeminformation  folder) and try it one more time? If this works, I will release a new version.

**Comment by zhangzhui** [comment]
It works! Thank you~

**Comment by sebhildebrandt** [comment]
@zhangzhui version 5.7.9 just released. Should work in this version.
