### ISSUE TITLE
How to get system username who signed in machine

### ISSUE THREAD

**Issue by vikkikrishna** [sebhildebrandt/systeminformation#555]
**Describe the bug**

**To Reproduce**
1. used function '...'
2. code snippet '....'
3. start app / code
4. See output/error '....'

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: [e.g. macOS]
 - Hardware [e.g. MacBook Pro 13]

**Additional context**

**Comment by vikkikrishna** [comment]
please help on this 

Thanks in Advance

**Comment by sebhildebrandt** [comment]
@vikkikrishna please read the docs ... https://systeminformation.io/os.html ... here you find the function `si.users()`

**Comment by vikkikrishna** [comment]
> users()

getting error after called the below methods 

const si = require('systeminformation');
si.users().then(data => console.log(data));


Failed to compile.

./node_modules/systeminformation/lib/util.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Tableau\Frontend\tableau\node_modules\systeminformation\lib'

**Comment by sebhildebrandt** [comment]
@vikkikrishna Just to be sure: This module is ONLY possible to use with node! Not in a frontend. 


So if you have a file like:

index.js
```
const si = require('systeminformation');
si.users().then(data => console.log(data));
```

and then `node index.js`... you get this error?
Which version of node are you using?
