### ISSUE TITLE
processLoad - invalid result type definition in index.d.ts

### ISSUE THREAD

**Issue by vvvait** [sebhildebrandt/systeminformation#558]
processLoad return array of object, but now in index.d.ts 
**Current**
`export function processLoad(processName: string, cb?: (data: Systeminformation.ProcessesProcessLoadData) => any): Promise<Systeminformation.ProcessesProcessLoadData>;
`

**Expected**
`export function processLoad(processNames: string, cb?: (data: Systeminformation.ProcessesProcessLoadData[]) => any): Promise<Systeminformation.ProcessesProcessLoadData[]>;
`

**Comment by sebhildebrandt** [comment]
Fixed, thank you. Version 5.7.10 just released.
