### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by pawlox** [sebhildebrandt/systeminformation#56]
Hi! Great package, really appreciate your work!

It works without problems on my PC and even Raspberry PI 2 :) , but I have problem while running this simple test program on my laptop:
```
var si = require('systeminformation');

si.getStaticData(function (data) {
    console.log(data);
});
```
In the console instead of static informations about by laptop I get this:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: not supported`
Any idea what may cause this error? My laptop is Samsung QX310, running on Windows 10 Pro (same version as on my PC), maybe it's something about my laptops hardware? :|

**Comment by sebhildebrandt** [comment]
Will check it.

**Comment by sebhildebrandt** [comment]
As it seems to be an error in one of the called functions, can you try to run the following code:

```
const si = require('systeminformation');
si.osInfo().then(res => {
	console.log('OS Info');
	console.log(res);
	si.versions().then(res => {
		console.log('Versions');
		console.log(res);
		si.cpu().then(res => {
			console.log('CPU');
			console.log(res);
			si.cpuFlags().then(res => {
				console.log('cpuFlags');
				console.log(res);
				si.graphics().then(res => {
					console.log('Graphics');
					console.log(res);
					si.networkInterfaces().then(res => {
						console.log('Network Interfaces');
						console.log(res);
						si.memLayout().then(res => {
							console.log('MEM Layout');
							console.log(res);
							si.diskLayout().then(res => {
								console.log('Disk Layout');
								console.log(res);
							})
						})
					})
				})
			})
		})
	})
})
```

Please post the output (or at least the few lines where an error happens). This would help me to identify the problem ;-)

**Comment by sebhildebrandt** [comment]
Found the bug. Will release a bugfix next week.

**Comment by pawlox** [comment]
Wow, thanks a lot for looking at this! I just came back home from holidays and I wanted to check out the code you posted tonight, but I see that you were faster than me :D

**Comment by sebhildebrandt** [comment]
So I just released a new version with the bugfix (and some other improvements).
