### ISSUE TITLE
converted bios to uefi showing as not uefi

### ISSUE THREAD

**Issue by si458** [sebhildebrandt/systeminformation#561]
**Describe the bug**
i have converted a few computers recently from BIOS to UEFI
but when running `si.osInfo` its still showing UEFI as false?

**To Reproduce**
Steps to reproduce the behavior
```
const si = require('systeminformation');
runcode = async () => {
    si.osInfo(data => {
        console.log(data);
    });
}
runcode()
```

**Current Output**
```
{
  platform: 'win32',
  distro: 'Microsoft Windows 10 Pro',
  release: '10.0.19041',
  codename: '',
  kernel: '10.0.19041',
  arch: 'x64',
  hostname: 'Unit1',
  fqdn: 'UNIT1.SERVER.COM',
  codepage: ' 850',
  logofile: 'windows',
  serial: '00330-80000-00000-AA847',
  build: '19041',
  servicepack: '0.0',
  uefi: false,
  hypervisor: false,
  remoteSession: false
}
```

**Expected behavior**
UEFI to be true?

**Environment (please complete the following information):**
 - systeminformation package version: 5.7.8
 - OS: [e.g. macOS] Windows 10 Pro
 - Hardware [e.g. MacBook Pro 13] Dell Optiplex 790

**Additional context**

`findstr /C:"Detected boot environment" "%windir%\Panther\setupact.log"` returns the following:
`FINDSTR: Cannot open C:\windows\Panther\setupact.log`
this is expected because it wasnt setup with UEFI so this file wont exist

`echo %firmware_type%` returns the following:
`UEFI`
this is returning correctly, so im not sure why its still returning false for UEFI?

**Comment by si458** [comment]
found the issue! and fixed it for you! #562
it was carrying on and returning the last false, rather than waiting for the exec to finish and returning that instead

**Comment by sebhildebrandt** [comment]
@si458 Version 5.7.12 just released. Can you check it on your side?

**Comment by si458** [comment]
Hi @sebhildebrandt sorry for my delay been off work...
sadly ive tried that and NOPE it made no difference its still showing FALSE even tho it should be true!
but again my patch #562 fixes the issue and it returns true as expected no problems

**Comment by sebhildebrandt** [comment]
@si458 thank you for your response. Checking my code I was sure, that there were more issues with missing returns. This is, why I made other changes ... need to check, why this still does not work ... sorry.

**Comment by si458** [comment]
The issue is because it's returning resolve(false) before the exec of the %firmware% has finished...

**Comment by sebhildebrandt** [comment]
So then the current line 400 (in my code here on github)  should be removed ...

**Comment by sebhildebrandt** [comment]
@si458 ... sorry forgot to mention you in my answer ... maybe you can have a look on my suggestion in comment above ..

**Comment by si458** [comment]
@sebhildebrandt sorry for delay, popped out the office haha!
if i indeed remove line 400 completely it does indeed return true now!
and ive tried it on 3 different computers and all return true!

**Comment by sebhildebrandt** [comment]
@si458 Thank you so much!!!!! Version 5.7.13 just released.

**Comment by si458** [comment]
@sebhildebrandt no no, **thank you** for such an amazing piece of open source software! ❤️ 

i do have another weird issue with staticinfo taking 6 seconds to process before it carry ons?
even though the staticinfo is a promise so should carry on straight away, but ill open another issue for that...

**Comment by sebhildebrandt** [comment]
@si458 yes please feel free to open another issue. Best regards.
