### ISSUE TITLE
Improper expected types when using bluetoothDevices() 

### ISSUE THREAD

**Issue by nambrozoh** [sebhildebrandt/systeminformation#563]
**Describe the bug**
I am attempting to pull bluetooth device description into my logger. However, when attempting `systemInfo.bluetoothDevice()[0].device` it provides me with a type error that it does not exist. Digging deeper, I find that the return type is expected to be `BlockDevicesData` instead of `BluetoothDeviceData`. 

Is this to be expected? If so, how can I pull `systemInfo.bluetoothDevice()[0].device` properly?

**To Reproduce**
1. used function 'bluetoothDevice()'
2. code snippet 
  ```
  const bluetoothDeviceInfo = await systemInfo.bluetoothDevices();
  logger.debug('BLUETOOTH DEVICE INFO', bluetoothDeviceInfo[0].device); // throws type error

 // cannot pull device.
  ```
3. start app / code
4. See output/error: 
```
Property 'device' does not exist on type 'BlockDevicesData'.ts(2339)
```

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**
As stated in the docs, we should be able to pull device directly:
https://github.com/sebhildebrandt/systeminformation#15-bluetooth

**Environment (please complete the following information):**
 - systeminformation package version: 5.7.6, 5.7.8, 5.7.10
 - OS: MacOS 10.15.7 
 - Hardware  
 MacBook Pro (16-inch, 2019)

**Additional context**

Should this https://github.com/sebhildebrandt/systeminformation/blob/master/lib/index.d.ts#L941
be using the BluetoothDeviceData instead?

**Comment by nambrozoh** [comment]
Introduced here:

https://github.com/sebhildebrandt/systeminformation/commit/143b1abe86632a3fa652a471cf532938ca7e0de3#diff-cfc7807f6b174e1c3705c5c2747f56e49a889a52999dc96e4080a3af0131a534R839

**Comment by sebhildebrandt** [comment]
@nambrozoh my fault!!! Sorry ... will provide a fix later today ...

**Comment by sebhildebrandt** [comment]
@nambrozoh ... should be fixed. Version 5.7.11 just released.

**Comment by nambrozoh** [comment]
Great! Thank you for the fast fix @sebhildebrandt.
