### ISSUE TITLE
cpuCurrentSpeed() broken on M1

### ISSUE THREAD

**Issue by BitesPotatoBacks** [sebhildebrandt/systeminformation#564]
**Describe the bug**
cpuCurrentSpeed() always (and only will) return 2.4Ghz on M1, even when under light or heavy loads.

**To Reproduce**
```
const si = require('systeminformation');
si.cpuCurrentSpeed().then(data => console.log(data));
```

**Expected behavior**
It should output different clock speeds when the CPU is under different loads, since CPU clock speeds naturally fluctuate.

**Environment (please complete the following information):**
 - systeminformation package version: 5.7.12
 - OS: MacOS Big Sur (11.5.1)
 - Hardware: M1 Mac Mini (Late 2020)

**Additional context**
This problem occurred on a slightly older version of systeminformation as well, though I cannot remember the version number…🤔

**Comment by sebhildebrandt** [comment]
@BitesPotatoBacks so as fas as I know, there is no way to determine the current frequency from command line ...

What would be the output of 

```
sysctl hw.cpufrequency
sysctl hw.cpufrequency_min
sysctl hw.cpufrequency_max
```

on your machine (terminal)?

**Comment by BitesPotatoBacks** [comment]
@sebhildebrandt tried those commands just now in terminal...nothing was outputted, the terminal just ignored them

**Comment by sebhildebrandt** [comment]
@BitesPotatoBacks Sorry ... yes on M1 this should give a result:

```
sysctl hw.tbfrequency
```

... which is `hw.tbfrequency: 24000000`

And also in `node`:

```
os.cpus()

[
  {
    model: 'Apple M1',
    speed: 24,
    times: { user: 6090, nice: 0, sys: 8400, idle: 112980, irq: 0 }
  },
  ...
]
```

**Comment by BitesPotatoBacks** [comment]
@sebhildebrandt yeah that one works...too bad 2.4 Ghz is all it can grab...wonder why that is...

**Comment by sebhildebrandt** [comment]
@BitesPotatoBacks yes, I am also a little disappointed, that I cannot find any other method. Closing It for now. If you discover any other way to determine correct CPU frequency, it would be nice, if you can point me into the right direction ;-)

**Comment by BitesPotatoBacks** [comment]
@sebhildebrandt that's cool. ill continue to research and see what I can find, ill let you know if I do. By the way, thanks for making this awesome package and helping me out so quickly with my issue! 👍 good day

**Comment by BitesPotatoBacks** [comment]
@sebhildebrandt Howdy! I’ve been researching this topic for an extremely long time now (as it is a near impossible feat to accomplish when on ARM), but I’ve finally figured it out. [I made a C++ script](https://github.com/BitesPotatoBacks/M1-CPU-Frequency) in order to achieve this, and [I’ve compiled a binary](https://github.com/BitesPotatoBacks/M1-CPU-Frequency/releases) for it as well.

If you would like to implement this, we could use `exec` from `child_process` to execute my binary in order to achieve a function that returns a truly “current” clock speed.
