### ISSUE TITLE
getStaticData takes 5 seconds to continue other async functions

### ISSUE THREAD

**Issue by si458** [sebhildebrandt/systeminformation#565]
**Describe the bug**
when i run getStaticData for some reason other async functions have to wait 5 seconds while it sets up the promise?
even though after other async functions begin there runnings, getStaticInfo is actually running in the background as it takes about 15seconds to get the reply back ?

**To Reproduce**
Steps to reproduce the behavior: - included few extra npm modules to help out with timing etc
```
require('log-timestamp')();
const os = require("os");
const si = require('systeminformation');
const io = require("socket.io-client");
console.log('BEGIN');
getStaticInfo = async () => {
    let data = await si.getStaticData();
    console.log(data);
    process.exit(0);
}
(async () => {
    console.log('Getting Computers Hostname');
    let hostname = os.hostname();
    console.log('Got Computers Hostname');
    console.log('Getting Computers UUID');
    let uuid = await si.uuid();
    console.log('Got Computers UUID');
    console.log("connecting to socket.io server");
    let socket = io("ws://localhost:3000", { transports: ["websocket"] });
    socket.io.on('error', (error) => {
        console.error(`connection error, ${error}`);
    });
    socket.io.on("reconnect", (attempt) => {
        console.warn(`reconnected to socket.io server, ${attempt} attempts`);
    });
    socket.io.on("reconnect_attempt", (attempt) => {
        console.info(`reconnecting to socket.io server, ${attempt} attempts`);
    });
    socket.io.on("reconnect_error", (error) => {
        console.error(`reconnection to socket.io server failed, ${error}`);
    });
    socket.io.on("reconnect_failed", () => {
        console.error('reconnection to socket.io server completely failed, giving up');
    });
    socket.on('connect', () => {
        console.info('connected to socket.io server');
    });
    socket.on("disconnect", (reason) => {
        console.warn(`disconnected from socket.io server, ${reason}`);
        if (reason === "io server disconnect") {
            socket.connect();
        }
    });
    socket.on('connect_error', (error) => {
        console.error(`socket.io connect_error, ${error}`);
    });
    getStaticInfo();
    console.log("Ready");
})();
console.log('END');
```

**Current Output**
```
PS C:\Users\Simon\Documents\ourmonitoring\nodejs> node .\test.js 
[2021-07-29T13:36:26.280Z] BEGIN
[2021-07-29T13:36:26.280Z] Getting Computers Hostname
[2021-07-29T13:36:26.296Z] Got Computers Hostname
[2021-07-29T13:36:26.297Z] Getting Computers UUID
[2021-07-29T13:36:26.298Z] END
[2021-07-29T13:36:26.672Z] Got Computers UUID
[2021-07-29T13:36:26.672Z] connecting to socket.io server
[2021-07-29T13:36:26.697Z] Ready
[2021-07-29T13:36:29.819Z] connected to socket.io server
```

**Expected behavior**
when i run my custom async getStaticInfo function it should carry on running the getStaticData in the background and the websocket to connet within 1 seconds, not wait 5 seconds then connect?

**Environment (please complete the following information):**
 - systeminformation package version: 5.7.13
 - OS: [e.g. macOS] MacOS - Node 14.17.3
 - Hardware [e.g. MacBook Pro 13] Macbook Pro

**Additional context**
im not sure if its maybe something im doing wrong with async/await functions,
but in my mind it should of run my custom getstaticinfo function and then carried on and let the websockets connect
rather than the websockets waiting for the getstaticinfo function to first build its promise before firing?

**Comment by sebhildebrandt** [comment]
@si458 Simon, thank you for your observation ... Will have a close look on it tomorrow.

**Comment by si458** [comment]
i have also tried using a promise instead of calling my custom async function, but thats the same, the websocket seems to wait 5 seconds before connecting, yet if you take away the getstaticdata function, it connects within 1 sec, it seems to be when calling the getstaticdata function every other async/promise function has to wait for it to finish building its list of stuff to do before it runs? i think its something to do with the `nexttick` but i have no experience with that function at all, only standard nodejs functions

**Comment by sebhildebrandt** [comment]
@si458 Hi, I am not sure, if I understand your problem correctly. Can you pleas ether 2 things:

1. I want to make sure, how long the getStaticData would actually take on your machine, using the internal test. Can you pull the whole repo into a new directory

```
git pull https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

Then in the test script you should find the ',' which runs `getStaticData()`;
With 'q' you can quit the test environment.

On my computer (macOS, MBPro) it takes 1,258 sec

2. Then it would be fine if you go into your own project and there into `node_modules/systemingotmation/lib` and edit `index.ts`. Can you just comment the line 78 and 115? Then run your script once again and check the behavior ... 

Think you in advance.

**Comment by si458** [comment]
Hi @sebhildebrandt sorry for delay, night time here haha 

I've run it and the test shows 9.234 seconds

And if I remove the nexttick it's down to 8.654 seconds 

So it's a little quicker

The issue I'm having is when you run the getstaticinfo all other async/promise functions don't run until after the getstaticinfo promise has been built (I don't mean completed in 9seconds, I mean just built the promise which seems to take 5 seconds to build then 9seconds to complete if that makes sense?)

**Comment by sebhildebrandt** [comment]
@si458 Thank you Simon!! The quicker run could also be because it just already went through one time ;-) Had the same here, adding / removing nextTick several times then came down to the same duration ...

So, this means, we have a clear duration for how long it takes to complete this. Fine. Did you also try to run your OWN code with the removed nextTick? Do we see any changed behaviour? If not then I need to think what the problem might be ...

**Comment by si458** [comment]
> So, this means, we have a clear duration for how long it takes to complete this. Fine. Did you also try to run your OWN code with the removed nextTick? Do we see any changed behaviour? If not then I need to think what the problem might be ...

yes i did and its the same result so its not the nexttick its a promise issue? im not sure how to get around this
SAMPLECODE:
```
require('log-timestamp')();
const os = require("os");
const si = require('systeminformation');
const io = require("socket.io-client");
console.log('BEGIN');
(async () => {
    console.log('Getting Computers Hostname');
    let hostname = os.hostname();
    console.log('Got Computers Hostname');
    console.log('Getting Computers UUID');
    let uuid = await si.uuid();
    console.log('Got Computers UUID');
    console.log("connecting to socket.io server");
    const start = Date.now();
    let socket = io("ws://localhost:3000", { auth: { uuid: uuid, hostname: hostname }, transports: ["websocket"] });
    socket.io.on('error', (error) => {
        console.error(`connection error, ${error}`);
    });
    socket.io.on("reconnect", (attempt) => {
        console.warn(`reconnected to socket.io server, ${attempt} attempts`);
    });
    socket.io.on("reconnect_attempt", (attempt) => {
        console.info(`reconnecting to socket.io server, ${attempt} attempts`);
    });
    socket.io.on("reconnect_error", (error) => {
        console.error(`reconnection to socket.io server failed, ${error}`);
    });
    socket.io.on("reconnect_failed", () => {
        console.error('reconnection to socket.io server completely failed, giving up');
    });
    socket.on('connect', () => {
        console.info('connected to socket.io server');
        const latency = Date.now() - start;
        console.log(latency+'ms');
    });
    socket.on("disconnect", (reason) => {
        console.warn(`disconnected from socket.io server, ${reason}`);
        if (reason === "io server disconnect") {
            socket.connect();
        }
    });
    socket.on('connect_error', (error) => {
        console.error(`socket.io connect_error, ${error}`);
    });
    console.log('Getting Static Info');
    si.getStaticData().then((data) => {
        console.log('GOT STATIC DATA')
        process.exit(0);
    });
    console.log('After Static Info');
    console.log("Ready");
})();
console.log('END');
```
```
PS C:\Users\Simon\Documents\ourmonitoring\nodejs> node .\test.js 
[2021-07-30T09:06:34.730Z] BEGIN
[2021-07-30T09:06:34.730Z] Getting Computers Hostname
[2021-07-30T09:06:34.748Z] Got Computers Hostname
[2021-07-30T09:06:34.748Z] Getting Computers UUID
[2021-07-30T09:06:34.749Z] END
[2021-07-30T09:06:35.133Z] Got Computers UUID
[2021-07-30T09:06:35.133Z] connecting to socket.io server
[2021-07-30T09:06:35.159Z] Getting Static Info
[2021-07-30T09:06:35.163Z] After Static Info
[2021-07-30T09:06:35.163Z] Ready
[2021-07-30T09:06:38.280Z] connected to socket.io server
[2021-07-30T09:06:38.280Z] 3147ms
[2021-07-30T09:06:42.229Z] GOT STATIC DATA
```

**Comment by si458** [comment]
@sebhildebrandt what i have also found is if i comment out `osInfo.versions()` `graphics.graphics()` `network.networkInterfaces()` from the promise it runs withint 500ms now...
but i add back in say `osInfo.versions()` it shoots up to 1500ms,
so the `osInfo.versions()` is taking 1 second on its own

**Comment by sebhildebrandt** [comment]
@si458 Just to be sure ... what is the cpu load/activity while running the code above ... getStaticData() is quite intense as it tries to run 12 functions in parallel ... and within `si.versions()` 30 `exec`'s are running in parallel ...

**Comment by si458** [comment]
@sebhildebrandt it starts out about 5% cpu then jumps to 25% cpu while building the promise then to 96% cpu while actually running all the commands
my VM for testing has Intel 4 core 2.8Ghz (no hyperthread),
but i tried it on another pc which is Intel 4 core 3.2Ghz (no hyperthread) and thats the same,
it sits for 5 seconds while building the promise before running,
it might be i just have to deal with it, as i do really like this command as it runs right at the very beginning of my apps startup to get information about the computer before submitting it to myself over websocket

**Comment by sebhildebrandt** [comment]
@si458 ... not a solution but maybe a workaround ... if you let establishing the websocket (which only takes 15ms?) and then as soon as it is established THEN you trigger running `getStaticData()` ... as this anyway then takes longer on this machine. Would this make sense??

**Comment by si458** [comment]
@sebhildebrandt it does indeed make sense, i think i might do down that route for now
it would of just been nice to run the `getStaticData` as the very beginning and carry on doing other stuff,
but the other stuff would still have to wait the 5 seconds before they can run,
maybe it is a CPU issue as shown it does get to 25% then 100%?
thank you again tho 👍 brilliant module ❤️

**Comment by sebhildebrandt** [comment]
@si458 OK to close it for now? Will still keep an eye on this.
