### ISSUE TITLE
si.cpuTemperatue is not a function

### ISSUE THREAD

**Issue by SlickNutter** [sebhildebrandt/systeminformation#57]
Does this mean that it's not supported by the cpu/os?

The error:
> (node:9740) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: si.cpuTemperatue is not a function

My code:
```
    private getTemperature(): Promise<number> {
        return new Promise<number>((resolve, reject) => {
            si.cpuTemperatue(resolve);
        });
    }
```
OS: Microsoft Windows 10 Pro

**Comment by SlickNutter** [comment]
Works with promise:
```
public getTemperature(): Promise<number> {
    return si.cpuTemperature().then((data: number) => {return data});
}
```
With this output:
> { main: -1, cores: [], max: -1 }

**Comment by sebhildebrandt** [comment]
For some versions of windows you need to run this with admin privileges to get proper results. And your hardware platform also needs to support this.
