### ISSUE TITLE
processes() inside docker container returns nothing - all empty data and lists

### ISSUE THREAD

**Issue by nsshunt** [sebhildebrandt/systeminformation#576]
**Describe the bug**
Running the processes() API call from a node application running inside a docker container on a Ubuntu 20.04 VM (VMWare running on Windows 10) does not list any of the running processes - just returns empty data.

**To Reproduce**

1. Create a new simple node app with the following code;
const si = require('systeminformation');
si.processes().then(data => console.log(data));

2. package the app as a docker container

3. Run the container inside a Ubuntu 20.04 VM (Hypervisor = VMWare Workstation, Host = Windows 10 on 10900K)

4. This will output nothing inside a running docker container. Outside works perfectly.

**Current Output**
No information is output for current running processes on the Docker container

**Expected behavior**
Same output as when running outside of a container - a full list of running process details.

**Environment (please complete the following information):**
Docker version 20.10.6, build 370c289
Running on Ubuntu 20.04
VMWare V16.1.2 - Workstation 16 Pro
Host - Windows 10
Host Hardware - 10900K 10/20  64GB Ram

**Comment by sebhildebrandt** [comment]
@nsshunt thank you for reporting … will have a closer look on it tomorrow.

**Comment by nsshunt** [comment]
Hi. Just a quick follow up; I tested this on my Mac Book Pro running Docker and OSX "metal" (i.e. no VMs - just native Docker Desktop) - same result - no data ... Cheers, M.

**Comment by nsshunt** [comment]
Another follow up to try and help;
I used this lib;
https://www.npmjs.com/package/pidusage
And the reporting worked in both non container and container modes.
The difference is that systeminformation when reporting CPU usage would never show over 100% but pidusage does.
Further, pidusage also shows the same CPU% as top and htop linux commands (within a small margin of error).
%'s over 100 meaning consuming more than 1 core.
I hope this helps.

**Comment by sebhildebrandt** [comment]
@nsshunt made some test inside interactive shell in a ubuntu docker container. 

```
const si = require('systeminformation');
si.processes().then(data => console.log(data));
```

And I got:

```
{
  all: 4,
  running: 2,
  blocked: 0,
  sleeping: 2,
  unknown: 0,
  list: [
    {
      pid: 1,
      parentPid: 0,
      name: 'bash',
      cpu: 0.007227025678632412,
      cpuu: 0.005033286660048929,
      cpus: 0.0021937390185834825,
      mem: 0.1,
      priority: 19,
      memVsz: 4240,
      memRss: 3504,
      nice: 0,
      started: '2021-08-31 20:53:35',
      state: 'sleeping',
      tty: 'pts/0',
      user: 'root',
      command: 'bash',
      params: '',
      path: ''
    },
    ....
  ]
}
```

Also `si.currentLoad()` works:

```
{
  avgLoad: 0.02,
  currentLoad: 1.0101010101010102,
  currentLoadUser: 0,
  currentLoadSystem: 1.0101010101010102,
  currentLoadNice: 0,
  currentLoadIdle: 98.98989898989899,
  currentLoadIrq: 0,
  ....
```

...matches values of `top`

So unclear why this does not work on your machine ... maybe you can provide the output of 

```
export LC_ALL=C; ps -axo pid:11,ppid:11,pcpu:6,pmem:6,pri:5,vsz:11,rss:11,ni:5,lstart:30,state:5,tty:15,user:20,command; unset LC_ALL
```

inside the docker image?

**Comment by nsshunt** [comment]
Hi. Thanks for response.

This is what I get inside Ubuntu docker image from above command;

        PID        PPID   %CPU   %MEM   PRI         VSZ         RSS    NI                        STARTED S     TT              USER                 COMMAND
          1           0    0.1    0.0    19        4116        3488     0       Tue Aug 31 21:22:42 2021 S     pts/0           root                 bash
         10           1    0.0    0.0    19        5904        2928     0       Tue Aug 31 21:22:57 2021 R     pts/0           root                 ps -axo pid:11,ppid:11,pcpu:6,pmem:6,pri:5,vsz:11,rss:11,ni:5,lstart:30,state:5,tty:15,user:20,command

**Comment by nsshunt** [comment]
Ok so some news ...
When I use **node:16-slim** as the base image for the docker container - nothing is returned
When I use **node:16** as the base image - worked perfectly ...

So ...

My _guess_ is that there is a library dependency that is not loaded by default from the node:16-slim base image.

Hope that helps....

**Comment by nsshunt** [comment]
Just tried with **node:16-alpine** as the same empty result;

**_{ all: 0, running: 0, blocked: 0, sleeping: 0, unknown: 0, list: [] }_**

So only node:16 works from these three (3) base images ...

**Comment by nsshunt** [comment]
More digging and some good news...

I tried to run the command you supplied inside **node:16-slim**

**export LC_ALL=C; ps -axo pid:11,ppid:11,pcpu:6,pmem:6,pri:5,vsz:11,rss:11,ni:5,lstart:30,state:5,tty:15,user:20,command; unset LC_ALL**

and got;

**_ps not recognised (i.e. not installed)_**

Inside the **node:16-slim** base image I then installed procps with;

**_apt update
apt install procps_**

Then it worked perfectly ...

Both the systeminformation library and the command above.

Further, I tried to run the above command inside **node:16-alpine** and I get;

ps: unrecognized option: x
BusyBox v1.32.1 () multi-call binary.

Usage: ps [-o COL1,COL2=HEADER] [-T]

Show list of processes

	-o COL1,COL2=HEADER	Select columns for display
	-T			Show threads

So not sure where to go with **node:16-alpine** base image to get it up and running in there...

M

**Comment by sebhildebrandt** [comment]
@nsshunt ... in this case it should the fall back to 

```
ps -o pid,ppid,vsz,rss,nice,etime,stat,tty,user,comm
```

(which should return results) but still it returns an empty list ... here I need to make further research ...

**Comment by sebhildebrandt** [comment]
@nsshunt I think I have fixed it now also for alpine linux. can you try it on your side? Version 5.8.7 just released.

**Comment by nsshunt** [comment]
Hi. That was quick :-)

Yes works now with **node:16-alpine** 

...but still need to install procps for **node:16-slim** as a dependency - I guess not all libs from procps are required because I seem to recall it installs ncurses with the package - perhaps to support htop or something - not sure ...

**Comment by sebhildebrandt** [comment]
@nsshunt Reds, without ps there is now way to show process information ... 

For your use your case: as node:16-alpine (based on alpine - 112 MB) is anyway smaller than node:16-slim (based on Debian buster - 176 MB) maybe you can consider using alpine ... or you need to install `procps` in your image ...

Closing it for now.
