### ISSUE TITLE
Units for the different properties

### ISSUE THREAD

**Issue by SlickNutter** [sebhildebrandt/systeminformation#58]
I'd like to know what unit si.mem.total uses, and maybe add it to the readme.

I thought it was bytes, but when I used si.mem, I got 
> 8494383104
Which in GB is 8.49~
While Windows tells me that I have 8.00

Thanks in advance.

**Comment by lapsio** [comment]
It's in bytes

    lapsio@linux-1ytv ~> node -e "require('systeminformation').mem().then(s=>console.log(s))"
    { total: 4142239744,
      free: 109518848,
      used: 4030935040,
      active: 3154468864,
      available: 152027136,
      buffcache: 878252032,
      swaptotal: 0,
      swapused: 0,
      swapfree: 0 }
    lapsio@linux-1ytv ~> free --bytes 
                  total        used        free      shared  buff/cache   available
    Mem:     4142239744  3136806912   130768896   612843520   874663936   169738240
    Swap:             0           0           0

Windows is inaccurate.

**Comment by SlickNutter** [comment]
Thank you! :)

**Comment by sebhildebrandt** [comment]
Will add this to the docs!
