### ISSUE TITLE
Question : Can I use this library in my react app ?

### ISSUE THREAD

**Issue by AnmolChhabra98** [sebhildebrandt/systeminformation#580]
Hi ,

I am working on a react app which requires some hardware info of users , can this library be used in my react app ?

Thanks,

**Comment by sebhildebrandt** [comment]
@AnmolChhabra98 if your plan is to use this library client side (inside the browser), then you will not get any hardware information of the client machine . This I of course due tu security reasons. The browser would not allow executing functions to determine exact hardware of the underlying computer. See also documentation: https://systeminformation.io/gettingstarted.html (Core Concept)
