### ISSUE TITLE
MemoryType not working on windows 10

### ISSUE THREAD

**Issue by ijamaatlou** [sebhildebrandt/systeminformation#581]
When I call `si.memLayout()` it show type of my memory as **unknown** that my ram type is **DDR4**. I check the source & found in line 512 this code :

`type: memoryTypes[parseInt(util.getValue(lines, 'MemoryType', '='), 10)],`

when I changed **MemoryType** to **SMBIOSMemoryType** , it means this code :

`type: memoryTypes[parseInt(util.getValue(lines, 'SMBIOSMemoryType', '='), 10)],`

it will be fixed and after calling `si.memLayout()` my ram type shown as **DDR4**

This change was in this file :

**node_modules/systeminformation/lib/memory.js**

so when I build my app it doesnt effect on my application.

I have request to add this to next version if it's possible.
version of code is 5.8.9

**Comment by sebhildebrandt** [comment]
@ijamaatlou thank you! I need to check, if this is the same on my machines. I have already an idea how to fix this if also the first one works sometimes ...  will make a fix today.

**Comment by sebhildebrandt** [comment]
@ijamaatlou This should be fixed now. Reflecting both values (`MemoryType` and `SMBIOSMemoryType`). Version 5.9.2 just published. Can you test it on your side?

**Comment by ijamaatlou** [comment]
@sebhildebrandt Yes! It works like a charm. thanks for your support 👍

**Comment by sebhildebrandt** [comment]
@ijamaatlou thank you for reporting and your final test!
