### ISSUE TITLE
Memory usage is reporting backwards - free memory is showing used memory

### ISSUE THREAD

**Issue by julianrinaldi** [sebhildebrandt/systeminformation#584]
**Describe the bug**
I'm using [system-bridge](https://github.com/timmo001/system-bridge) which uses systeminformation. My free memory is showing the used memory instead of the free memory. The developer says its an issue with systeminformation and not their program. [https://github.com/timmo001/system-bridge/issues/840](https://github.com/timmo001/system-bridge/issues/840)

**Expected behavior**
Expect to see my free memory to show 12.19 GB, but it shows .17GB which is actually my used memory.

**Environment (please complete the following information):**
 - systeminformation package version: not sure
 - OS: Linux Mint 20.2
 - Hardware HP 290

**Additional context**

**Comment by sebhildebrandt** [comment]
@julianrinaldi thank you for reporting. I checked my code but my feeling is that the code is correct.

Can you provide the output of 

Command line:
```
cat /proc/meminfo
```

From nodejs:
```
os.totalmem()
os.freemem()
```

and using systeminformation:

```
const si = require('systeminformation');
si.mem().then(data => console.log(data));
```

**Comment by sebhildebrandt** [comment]
@julianrinaldi this is what I have e.g. on one of my machines:

```
cat /proc/meminfo

MemTotal:       65773952 kB
MemFree:        55330152 kB
MemAvailable:   62547648 kB
...
```

From systeminformation:

```
{
  total: 67352526848,
  free: 56620711936,
  used: 10731814912,
  active: 3340304384,
  available: 64012222464,
  buffers: 1218334720,
  cached: 6833664000,
  slab: 718544896,
  buffcache: 8770543616,
  swaptotal: 34326179840,
  swapused: 8388608,
  swapfree: 34317791232
}
```

Node.js:

```
os.totalmem()
67352526848

os.freemem()
56663609344
```

Values varies slightly because not gathered at exact the same time. But still this should be fine...

**Comment by julianrinaldi** [comment]
This is what I'm seeing for the first command. I'll have to figure out how to do the other commands and get back to you later today. But in this screenshot the MemFree looks to be way off.

![CleanShot 2021-09-22 at 16 24 06](https://user-images.githubusercontent.com/492435/134416607-4151e26b-561c-42e9-9072-cffe2ad7ac50.png)

**Comment by sebhildebrandt** [comment]
@julianrinaldi ... so the screenshot if from the project you where talking (system-bridge)? As I do not know which numbers the graphs actually take, I cannot judge on that. But based on your first post and the `/proc/meminfo` the numbers that systeminformation provide are correct.

**Comment by julianrinaldi** [comment]
What is MemFree showing? It's not showing total memory free? It looks like MemAvailable is showing the correct number that I'm looking for.

**Comment by sebhildebrandt** [comment]
@julianrinaldi what I mean: you see the same values in `cat /proc/meminfo` and the values that `systeminformation.mem()` returns. To be more specific:

- **MemFree**: the amount of physical RAM, in kilobytes, left unused by the system.
- **MemAvailable** :  is an estimate of how much memory is available for starting new applications, without swapping.

This is what you also get back from systeminformation. So I do not see any issue here in our code, right?

**Comment by julianrinaldi** [comment]
Yes. I think the developer should be using the MemAvailable value instead of the MemFree value.

**Comment by sebhildebrandt** [comment]
@julianrinaldi ... agree ... still the question is, what data Linux Mints system information is using and in which way. I am confident, that they rely on the same `/proc/meminfo` but unclear what calculation they are using. If they would just take MemTotal - MemAvailable as an estimation of USED memory then this would be 1.83 GiB (not the shown 1.4 GiB) ... 

So as we provide all the raw data in systeminformation, can we consider that there is no bug on our side?

**Comment by julianrinaldi** [comment]
Yes, it doesn't look like a bug on your side. Thanks for the help and sorry about the confusion.

**Comment by sebhildebrandt** [comment]
@julianrinaldi always welcome. Thank you for your support!
