### ISSUE TITLE
memRss is wrong on M1

### ISSUE THREAD

**Issue by vitalipf** [sebhildebrandt/systeminformation#585]
**Describe the bug**
Processes memRss is reported as 10 times lower than in Activity Monitor.

**To Reproduce**
var si = require('systeminformation');
si.processes()
  .then(processes => {
    console.log(processes.list[0].memRss);
  });

**Current Output**
The value is 10 times lower than expected.

**Expected behavior**
Somewhat close to the number in Activity Monitor.

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.3
 - OS: Mac OS on arm64
 - Hardware: Mac mini (M1, 2020)

**Additional context**
The problem lies in the 'ps -axo' output. vsz column header is not aligned to the right.
Changing the command to
if (_darwin) { cmd = 'export LC_ALL=C; ps -axo pid,ppid,pcpu,pmem,pri,vsz=some_long_name,rss,nice,lstart,state,tty,user,command -r; unset LC_ALL'; }
workarounds the problem.

**Comment by sebhildebrandt** [comment]
@vitalipf thank you so much ... discovered the same also for memRss ... fixed both now. Version 5.9.4 just published.

**Comment by vitalipf** [comment]
Thank you for a quick fix.
Taking into account https://github.com/sebhildebrandt/systeminformation/issues/586, is it possible to integrate the memRss fix into 5.7.x?

**Comment by sebhildebrandt** [comment]
I will try to tackle #586 as soon as possible, I guess this would be the better way .. If I cannot solve this within 1-2 days, I will just revert the pull request and publish a new version. Then I have time to concentrate on what the pull request wanted so solve separately.
