### ISSUE TITLE
networkLatency based on ip4 address

### ISSUE THREAD

**Issue by chapster11** [sebhildebrandt/systeminformation#588]
Thank you for this great package. 
I'm looking into using networkLatency but unsure if I should be supplying it with my wifi ip4 address or leave it blank to get my wifi network latency. 

OS version: Windows 10 64 bit OS
systeminformation version: 5.9.4

Here is an example of my ip4 from networkInterfaces.

**networkInterfaces:** 

```
 iface: 'Wi-Fi',
    ifaceName: 'Intel(R) Wi-Fi 6,
    ip4: '142.128.1.81',
    type: 'wireless',
    speed: 758.35,
    dhcp: 'true',
    carrierChanges: 0
    .....
```

**wifiConnections**
```
    id: '........,
    iface: 'Wi-Fi',
    model: 'Intel(R) Wi-Fi 6,
    ssid: 'my-wifi',
    bssid: '2.....',
    channel: 157,
    frequency: 5785,
    signalLevel: '85%',
    txRate: 650 
```

**second question:** 
**networkInterfaces**()- speed will show you the the signed speed of a certain interface
What is the meaning of signed speed above ? 
I'm looking for the actual speed of connected wifi . As in what I would get if I was to run a speed test. 
Would **wifiConnections**()- txRate be what I'm looking for ?

**Comment by sebhildebrandt** [comment]
@chapster11 ... 
First a short answer to `networkInterfaces()` and `wifiConnections()`
sorry .. I mean "designed" (max) speed ... Your interface can then go up to this speed but in case of a WIFI interface the actual connection speed (wifiConnections/ txRate) depend on the router, positioning, etc... 

About network `inetLatency()` ... this function is NOT about network interfaces. It checks your internet latency by trying to connect to an outside host on the internet ... default is googles public DNS `8.8.8.8` and you can change it to your needs.

**Comment by sebhildebrandt** [comment]
@chapster11 can we close this issue?

**Comment by chapster11** [comment]
Yes I'm closing this ticket. Thanks for the help.
