### ISSUE TITLE
Is there a plan to support `si.networkStats()` on Windows ?

### ISSUE THREAD

**Issue by phizaz** [sebhildebrandt/systeminformation#59]
I have tried to use `si.networkStats('Wi-Fi')` on Windows.

It seems the operation is not yet supported on Windows, I got `Error: not supported`.

Kindly ask, any plan and when will you support it ?

**Comment by SlickNutter** [comment]
As a temporary solution use:
`execSync('netstat -s')`
twice with a timestamp and parse each call, from there you can calculate the difference.

With this you can get rx and tx, and calculate rx_sec and tx_sec.

**Comment by sebhildebrandt** [comment]
As I am really interested in providing as much functionality as possible for all platforms, this is of course one of my goals. I am currently on a business trip and I will work on it next week and provide an answer as soon as I have a solution. Ok for you?

**Comment by sebhildebrandt** [comment]
After some investigation I didn't found a proper solution to achieve what I have done for Linux/OSX. It seems, there is no possibility to get per-interface network statistics. The only workaround would be to provide overall network stats with `netstat -s`.

I will implement and release this (limited) functionality in the next few days.

**Comment by sebhildebrandt** [comment]
Already implemented it. Added now windows support for `networkStats()` (no interface option), as well as `networkConnections()`

**Comment by SlickNutter** [comment]
@sebhildebrandt There is a class in [Windows](https://technet.microsoft.com/en-us/security/aa394340(v=vs.80)) that gives this information. I don't know if you actually would like to write an extension in C/++

**Comment by sebhildebrandt** [comment]
@SlickNutter Thank you for your hint. This points me into a good direction. Lets see, if I can manage to get this working.

**Comment by sebhildebrandt** [comment]
OK, seems there is a way to achieve this - a little bit more complicated ... I will provide a solution for this till end of next week.

**Comment by sebhildebrandt** [comment]
Just provided an update with the same functionality for `networkStats()` for windows (per interface). If you like to get network statistics for a specific interface, be sure to provide the correct name for that interface. You find all available names with `si.networkInterfaces()`
