### ISSUE TITLE
WSL2 not being detected as virtual

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#592]
**Describe the bug**
While running this library in a WSL2 environment `system.virtual` is `false`.

**To Reproduce**
1. Install WSL2
2. Use `si.system()` and notice the `virtual: false`

**Current Output**
```
system = {"manufacturer":"","model":"","version":"","serial":"","uuid":"","sku":"-","virtual":false}
os = {"platform":"linux","distro":"Ubuntu","release":"20.04.2 LTS","codename":"Focal Fossa","kernel":"5.10.43.3-microsoft-standard-WSL2","arch":"x64","hostname":"ALEXIS-TOWER","fqdn":"ALEXIS-TOWER.localdomain","codepage":"UTF-8","logofile":"ubuntu","serial":"REDACTED","build":"","servicepack":"","uefi":false}
```

Checking if `kernel` ends in `WSL2` should be a good enough check for this.

**Comment by OmgImAlexis** [comment]
```
#1 SMP Wed Jun 16 23:47:55 UTC 2021
```

**Comment by sebhildebrandt** [comment]
@OmgImAlexis I improved WSL version detection (better detection of WSL1 and WSL2 based on kernel version). In `version`, you should now find `2` (as WSL here is redundant). And WSL1 installations will now find `1` here ... just for information
