### ISSUE TITLE
Converting to ts and promises?

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#593]
Wanted to discuss moving over to typescript and possibly a code cleanup as I'm noticing a lot of the code is heavily nested using a lot of callbacks.

**Comment by OmgImAlexis** [comment]
Sounds good to me. 👍 

Could you close and ping me in this issue once that branch is up?

**Comment by OmgImAlexis** [comment]
@sebhildebrandt could you setup the v6 branch today?

**Comment by OmgImAlexis** [comment]
@sebhildebrandt no worries, just wanting to get working on it. 👍

**Comment by OmgImAlexis** [comment]
Guessing once that's it we'll do a code freeze until we've converted it to ts?

**Comment by OmgImAlexis** [comment]
@sebhildebrandt any updates on the plan yet? 😃

**Comment by sebhildebrandt** [comment]
Very bad timing ... Sick since Saturday evening and currently not able to work. Feeling very poorly at the moment. Will complete transition as soon as I feel better....

**Comment by OmgImAlexis** [comment]
@sebhildebrandt if you’re still not feeling the best is there anything I can help with?

**Comment by sebhildebrandt** [comment]
@OmgImAlexis Thank you so much for asking! Still not recovered (now whole family also ill) ... as said, touched every file, did a lot of restructuring but not finished with it. As soon as I feel better I need to see when I can concentrate on finishing this transition. In the meanwhile I do not think it would make that much sense if you work on it in parallel as we would get completely out of sync... I don't want to waist your valuable resources.

**Comment by OmgImAlexis** [comment]
@sebhildebrandt hope you all pull through.

That's unfortunate. I had been hoping from the start to help as I feel this would have been done in a few days instead of the month it's taken. Don't really have all the much time now as my holidays are over. Had hoped while my holidays were on I could have done this as I originally said..

**Comment by OmgImAlexis** [comment]
@sebhildebrandt just checking in how things are going? If need be I'd be happy to take over v6 and finish the branch off via RP.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis 
Dear Alexis,

First of all once again, thank you for reaching out and asking! I do understand, that our pace working on this is a little different.  also have the feeling that we might have different motivations and goals and this is absolutely fine. I wish that I would be able to deliver how you are expecting it and unfortunately this is not the case. 

My current situation does not allow me to work as much as wanted on this project. And being ill for more than one week didn't improved the situation. My family is still suffering and also all my other projects need a lot of attention! 

So when you proposed to make aa transition to typescript this was a really good idea and maybe we had here a huge misunderstanding. I did not know that you already did a lot of the transition. For me it was anyway clear, that this will be the foundation of the next major release. My approach was maybe not as smart as yours but what I started to do (and what i am still doing) is having a look on every line (not that accurate as you are doing (!) is in terms of code quality). So rethinking why the implementation is like it is and remembering all edge cased that I tried to cover during the last 7 years maintaining this library. 

As already said, I am kind of in the middle (or to be more precise near the end) of this process. Having this next major release in mind, i also have to make several decisions. Sometimes this takes some time (as said, maybe I am not that smart...). I touched nearly every file and of course we are not completely out of sync. I guess we both are absolutely not happy with this situation. I need to finish some more things here before I would like to push all my changes. And as I see that you are a really brilliant programmer, I would love to see you the helping making this much better. 

I am really, really sorry for this situation. Hoping for your understanding, I ask for a little more patience. Thank you once again for all your amazing work help and suggestions for this project!

Best regards
Sebastian

**Comment by OmgImAlexis** [comment]
@sebhildebrandt I think the main thing this comes down to me being too impatient. I'm not use to just sitting back and waiting. I know I can fix this so I want to just get in there and fix the issue.

The other issue is the fact I want to launch a side project of mine for monitoring servers that will heavily use this and needs to be as light as possible so shipping the windows, etc. parts just cant happen so I need v6 done which would allow me to use the os specific builds we talked about. At the moment I'm falling back to using a hacked together version of this that I import locally in my app. I'd love to just import this but v5 is just too heavy.
