### ISSUE TITLE
Typo with POWER_SUPPLY_ENERGY_FULL_DESIGN

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#596]
https://github.com/sebhildebrandt/systeminformation/blob/9ba20d04c915e94733699772b16ebe369e03c7e8/lib/battery.js#L123

Shouldn't this be `util.getValue(lines, 'POWER_SUPPLY_ENERGY_FULL_DESIGN', '=', true, true)` since `=` is the separator.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis ... thank you - my fault - fixed! Version 5.9.7 just released.
