### ISSUE TITLE
Typo in "Thynk you for your understanding."

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#597]
Should be "Thank" instead of "Thynk".

https://github.com/sebhildebrandt/systeminformation/blob/6b4b5e9f196d3e357b9b28914ef232b9ce8cf98f/docs/changes.html#L168

**Comment by sebhildebrandt** [comment]
@OmgImAlexis ... thank you - my fault - fixed! Version 5.9.7 just released.
