### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by lapsio** [sebhildebrandt/systeminformation#6]
It'd be really nice to have some flag indicating level of privilleges, especially for `getAllData` or maybe even autodetect because currently lib is crashing with EACCES on my os if not run as root.

Error: EACCES: permission denied, open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq'

**Comment by tirithen** [comment]
I have the same problem, maybe use information from $ cat /proc/cpuinfo instead as source for CPU?

**Comment by sebhildebrandt** [comment]
I will have a look on it. Update will follow. Please give me some time to correct it ;-)

**Comment by Buzut** [comment]
Seems like using [`accessSync`](https://nodejs.org/api/fs.html#fs_fs_accesssync_path_mode) instead of `existsSync` solves the problem.

**Comment by sebhildebrandt** [comment]
Finalizing V 3.0 of systeminformation where I implemented a solution for that.

**Comment by lapsio** [comment]
I'm not really good at all this fors stuff what's going on are Buzut updates going to be merged into this repo or there are 2 independent forks right now or what?...

**Comment by sebhildebrandt** [comment]
I had to rewrite Buzut suggestions (they were not working on several of my machines) and I was anyway working on version 3 where I made some more changes. Therefore I did not directly merged his updates. But his suggestion showed me the right direction ;-)

New version will be ready and tested this week. 

Sebastian

**Comment by lapsio** [comment]
Nice I can't wait :) 

Also few small notes though:

I looked at source and noticed you have hardcoded 8.8.8.8 IP to check latency. I found it hilarious coincidence because my router is actually hijacking all traffic to 8.8.8.8 and 8.8.8.4 alongside with all port 53 traffic redirecting it to local DNS server with logs enabled so I'm getting almost 0 latency xD. Maybe It'd be good idea to allow user to specify host manually. 

`var cmd = 'netstat -tun | tail -n +3 | wc -l'`
If you get list of all connections anyways, why only count them? It'd be useful to get all info provided by netstat. Anyone could just count connections using array.length. I reamember having to write scripts for connections monitoring some times ago because my firewall logs were capturing some suspicious traffic and I had to investigate which process is sending such weird packets. (hint: don't install Adobe flash on server... too bad it's included in default packages in OpenSUSE)

    > sys.users(cb)
    undefined
    > { '0': 
       [ 'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
    < 9 000 lines later  ... >
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio',
         'lapsio' ] }

ugh... o_o"
"users" suggests rather existing users not currently logged in (ofc it's also useful info) and... duplicated as many times as opened screen/shell sessions?... How about this almost oneliner:

    > var users=['lapsio','lapsio','lapsio','lapsio','root','root','user']; cnt = [0],p=0 ; users.filter(function(s,i,a){++cnt[p];if(a[i+1]!=s){cnt[++p]=0;return true}return false}).map(function(s,i){return {login:s,sessions:cnt[i]}})
    [ { login: 'lapsio', sessions: 4 },
      { login: 'root', sessions: 2 },
      { login: 'user', sessions: 1 } ]
    >

As person obsessed with linux storage stack current storage information looks really, really poor to me. But It's quite big thing I was writing scripts for automated SSD caching / LUKS / RAID setups some time ago and they were pretty huge so maybe I'll try to contribute some code for more complete storage stack information (like SSD cache hit ratio for example which I had to read kernel docs to figure out how to read it or btrfs support).

**Comment by sebhildebrandt** [comment]
Hi,

thank you for your suggestions and comments!!! I’ll have a more detailed look tomorrow. 
Have a nice evening

Sebastian

**Comment by sebhildebrandt** [comment]
Hi again,

I went through your suggestions and here some comments:

1. Latency Check: I agree, hardcoded '8.8.8.8' is not a goot thing. I changed the code, that now you can provide an alternative host against which the latency is checked (8.8.8.8 is only default).

2. networkConnections: Ah, yes I agree, only counting is maybe not the best thing ... I will rewrite this thing to provide more information ;-)

3. users: this should only provide logged in users. I am using the linux 'users' command, which should return 'Output who is currently logged in' (according to man). I will change it to provide more information about logged in users. In this case I will not only count sessions per user as you suggested but provide more information about this session.

4. storage information: completely agree! This is just BASIC. Any further ideas are highly welcome!

Updated code for 1., 2., 3. will be available in version 3 (should be ready and testet and of week).

**Comment by sebhildebrandt** [comment]
Done in Version 3.0:

1. Solved permissions for CPU Frequency
2.`si.inetLatency(host, cb)`: here you now can provide (optional) alternate host against which to check latency
3. `si.networkConnections(cb)`: now returns an array of all connections with detailed information per connection (protocol, local and peer address, state)
4. `si.users(cb)`: now provides an array of objects with users online including detailed session information (login date/time, ip address, terminal, command)
