### ISSUE TITLE
Typo "Workarround"

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#601]
There's quite a few times this happens. It should be "Workaround" not "Workarround".

https://github.com/sebhildebrandt/systeminformation/blob/913d6b53628eb6da834b2fb151acb0b403d5e080/docs/security.html#L65

**Comment by sebhildebrandt** [comment]
@OmgImAlexis ... fixed, website deployed with corrections. Thank you!
