### ISSUE TITLE
It doesn't return currentRefreshRate when I use si.graphics() to get graphics information with two monitor.

### ISSUE THREAD

**Issue by wj007881** [sebhildebrandt/systeminformation#602]
**Describe the bug**
It doesn't return currentRefreshRate when I use si.graphics() to get graphics information with two monitor.

**To Reproduce**
1. used function 'si.graphics()'
2. code snippet '(si.graphics()
  .then(data => res.send(data))
  .catch(error => res.send(error))
  )'
3. start app / code
4. See output/error '....'

**Current Output**
{
    "controllers": [
        {
            "vendor": "Intel Corporation",
            "model": "Intel(R) UHD Graphics",
            "bus": "PCI",
            "vram": 1024,
            "vramDynamic": true,
            "subDeviceId": "22AF17AA"
        }
    ],
    "displays": [
        {
            "vendor": "Lenovo",
            "model": "Wide viewing angle &amp; High density FlexView Display 1920x1080",
            "deviceName": "\\\\.\\DISPLAY1",
            "main": false,
            "builtin": true,
            "connection": "INTERNAL",
            "resolutionX": 1280,
            "resolutionY": 720,
            "sizeX": 29,
            "sizeY": 17,
            "pixelDepth": "32",
            "currentResX": 1280,
            "currentResY": 720,
            "positionX": 2048,
            "positionY": 0
        },
        {
            "vendor": "",
            "model": "",
            "deviceName": "\\\\.\\DISPLAY2",
            "main": true,
            "builtin": false,
            "connection": "DP",
            "resolutionX": 2048,
            "resolutionY": 1152,
            "sizeX": 53,
            "sizeY": 30,
            "pixelDepth": "32",
            "currentResX": 2048,
            "currentResY": 1152,
            "positionX": 0,
            "positionY": 0
        }
    ]
}

**Expected behavior**
{
    "controllers": [
        {
            "vendor": "Intel Corporation",
            "model": "Intel(R) UHD Graphics",
            "bus": "PCI",
            "vram": 1024,
            "vramDynamic": true,
            "subDeviceId": "22AF17AA"
        }
    ],
    "displays": [
        {
            "vendor": "",
            "model": "",
            "deviceName": "\\\\.\\DISPLAY2",
            "main": true,
            "builtin": true,
            "connection": "INTERNAL",
            "resolutionX": 1920,
            "resolutionY": 1080,
            "sizeX": 53,
            "sizeY": 30,
            "pixelDepth": 32,
            "currentResX": 2048,
            "currentResY": 1152,
            "positionX": 0,
            "positionY": 0,
            "currentRefreshRate": 60
        }
    ]
}

**Environment (please complete the following information):**
 - systeminformation package version:5.7
 - OS: [win10]
 - Hardware PC

**Additional context**

**Comment by sebhildebrandt** [comment]
@wj007881 thank you for your findings. Yes this is true, but unfortunately in windows (wmic) the current refresh rate is a property of the controller and therefore it is not reliable, if there are two monitors connected. See also the discussion in #590 ... What I could do, is putting this single value (from the controllers) to all displays to have at least some information here but as said, this is not reliable e.g. if both monitors are configured differently, the results are not correct. And it gets even more complicated if there are two controllers. 

Any ideas here from your side to get reliable data from wmic or any other indicator?

**Comment by wj007881** [comment]
I don't have idea about wmic, 
I think you can use this tool to get monitor information 'https://www.nirsoft.net/utils/dump_edid.html', 
It output like this:
DumpEDID v1.07

Copyright (c) 2006 - 2018 Nir Sofer

Web site: http://www.nirsoft.net



*****************************************************************

Active                   : No

Registry Key             : DISPLAY\LEN4094\4&29f2c365&0&UID265988

Manufacture Week         : 0 / 2018

ManufacturerID           : 44592 (0xAE30)

ProductID                : 16532 (0x4094)

Serial Number (Numeric)  : 0 (0x00000000)

EDID Version             : 1.4

Display Gamma            : 2.20

Image Size               : 29.4 X 16.5 cm (13.3 Inch)

Maximum Image Size       : 29 X 17 cm (13.2 Inch)

Maximum Resolution       : 1920 X 1080

Support Standby Mode     : Yes

Support Suspend Mode     : Yes

Support Low-Power Mode   : Yes

Support Default GTF      : No

Digital                  : Yes



Supported Display Modes  :

    1920 X 1080  60 Hz



*****************************************************************



*****************************************************************

Active                   : Yes

Registry Key             : DISPLAY\LEN66A8\4&29f2c365&0&UID224795

Monitor Name             : Q24h-10

Serial Number            : U5HC1W7V

Manufacture Week         : 11 / 2020

ManufacturerID           : 44592 (0xAE30)

ProductID                : 26280 (0x66A8)

Serial Number (Numeric)  : 0 (0x00000000)

EDID Version             : 1.3

Display Gamma            : 2.20

Vertical Frequency       : 48 - 75 Hz

Horizontal Frequency     : 30 - 112 KHz

Maximum Image Size       : 53 X 30 cm (24.0 Inch)

Maximum Resolution       : 2560 X 1440

Support Standby Mode     : No

Support Suspend Mode     : No

Support Low-Power Mode   : Yes

Support Default GTF      : No

Digital                  : Yes



Supported Display Modes  :

     720 X  400  70 Hz

     640 X  480  60 Hz

     640 X  480  72 Hz

     640 X  480  75 Hz

     800 X  600  56 Hz

     800 X  600  60 Hz

     800 X  600  72 Hz

     800 X  600  75 Hz

     832 X  624  75 Hz

    1024 X  768  60 Hz

    1024 X  768  70 Hz

    1024 X  768  75 Hz

    1440 X  900  60 Hz

    1280 X 1024  60 Hz

    1280 X 1024  75 Hz

    1680 X 1050  60 Hz

    1920 X 1080  60 Hz

    1920 X 1200  60 Hz

    2560 X 1440  60 Hz



*****************************************************************



*****************************************************************

Active                   : No

Registry Key             : DISPLAY\MSH062E\6&1a097cd8&0&UID5527112

Monitor Name             : HyperVMonitor

Manufacture Week         : 255 / 2011

ManufacturerID           : 26678 (0x6836)

ProductID                : 1582 (0x062E)

Serial Number (Numeric)  : 0 (0x00000000)

EDID Version             : 1.4

Display Gamma            : 2.20

Maximum Resolution       : 1024 X 768

Support Standby Mode     : No

Support Suspend Mode     : No

Support Low-Power Mode   : Yes

Support Default GTF      : No

Digital                  : Yes



Supported Display Modes  :

    1024 X  768  60 Hz



*****************************************************************



*****************************************************************

Active                   : No

Registry Key             : DISPLAY\SAM090B\4&29f2c365&0&UID206395

Monitor Name             : SAMSUNG

Manufacture Week         : 42 / 2011

ManufacturerID           : 11596 (0x2D4C)

ProductID                : 2315 (0x090B)

Serial Number (Numeric)  : 1 (0x00000001)

EDID Version             : 1.3

Display Gamma            : 2.20

Vertical Frequency       : 24 - 75 Hz

Horizontal Frequency     : 15 - 81 KHz

Image Size               : 16.0 X 9.0 cm (7.2 Inch)

Maximum Image Size       : 102 X 57 cm (46.0 Inch)

Maximum Resolution       : 1920 X 1080

Support Standby Mode     : No

Support Suspend Mode     : No

Support Low-Power Mode   : No

Support Default GTF      : No

Digital                  : Yes



Supported Display Modes  :

     720 X  400  70 Hz

     640 X  480  60 Hz

     640 X  480  67 Hz

     640 X  480  72 Hz

     640 X  480  75 Hz

     800 X  600  60 Hz

     800 X  600  72 Hz

     800 X  600  75 Hz

     832 X  624  75 Hz

    1024 X  768  60 Hz

    1024 X  768  70 Hz

    1024 X  768  75 Hz

    1280 X  720  60 Hz

    1152 X  864  75 Hz

    1280 X  800  60 Hz

    1440 X  900  60 Hz

    1280 X 1024  60 Hz

    1280 X 1024  75 Hz

    1600 X  900  60 Hz

    1680 X 1050  60 Hz

    1920 X 1080  60 Hz



*****************************************************************
or this tool https://github.com/wj007881/test/blob/master/user_MonitorInfo.exe, but I don't know it how to work, it output like this: 
(1)
Monitor Module: LEN66A8
Resolution List:
800 600 60
800 600 72
800 600 75
800 600 59
1024 768 59
1024 768 60
1024 768 70
1024 768 75
1152 864 59
1152 864 60
1152 864 75
1280 600 59
1280 600 60
1280 600 75
1280 720 50
1280 720 59
1280 720 60
1280 720 75
1280 768 59
1280 768 60
1280 768 75
1280 800 59
1280 800 60
1280 800 75
1280 960 59
1280 960 60
1280 960 75
1280 1024 59
1280 1024 60
1280 1024 75
1360 768 59
1360 768 60
1360 768 75
1366 768 60
1366 768 59
1366 768 75
1400 1050 59
1400 1050 60
1400 1050 75
1440 900 60
1440 900 59
1440 900 75
1600 900 59
1600 900 60
1600 900 75
1600 1200 59
1600 1200 60
1600 1200 75
1680 1050 60
1680 1050 59
1680 1050 75
1792 1344 59
1792 1344 60
1792 1344 75
1856 1392 59
1856 1392 60
1856 1392 75
1920 1080 50
1920 1080 59
1920 1080 60
1920 1080 75
1920 1200 59
1920 1200 60
1920 1200 75
1920 1440 59
1920 1440 60
1920 1440 75
2048 1152 59
2048 1152 60
2048 1152 75
2560 1440 59
2560 1440 60
2560 1440 75
Resolution: 2560 1440 75
Monitor Name: Q24h-10
Year/week of Manufacture: 2020/11 (year/week)
EDID version: 1.3

How many Monitors: 1
Monitor mode: INTERNAL

hope to help you

**Comment by sebhildebrandt** [comment]
@wj007881 for now - as windows do not provide better information for refresh rates - I made the change that the currentRefreshRate is now taken for all monitors from the information windows provides for the controller. This is not optimal but as said, windows does not give back better data. Version 5.14.3 just released.
