### ISSUE TITLE
windows: add si.processes

### ISSUE THREAD

**Issue by reklatsmasters** [sebhildebrandt/systeminformation#61]
This command will show you a list of running processes. Required powershell@v3.
```
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "get-wmiobject win32_process | select ProcessId, Name, @{Name='StartTime'; Expression = { $_.ConvertToDateTime($_.CreationDate) }} | convertto-json -compress"
```
Fields:

| Field | process property | description |
| --- | --- | --- |
| `ProcessId` | `[0].pid` | process pid |
| `Priority` | `[0].priority` | process priotity |
| `PageFileUsage` | `[0].mem_vsz` | process virtual memory size in kb |
| `WorkingSetSize` | `[0].mem_rss` | process mem resident set size in bytes |
| `@{Name='StartTime'; Expression = { $_.ConvertToDateTime($_.CreationDate) }}` | `[0].started` | process start time |
| `@{Name='Owner'; Expression = { $_.GetOwner().User }}` | `[0].user` | user who started process (note: this operation is **very** slow) |
| `CommandLine` | `[0].command` | process starting command |
| `UserModeTime` | - | cpu user time in 100-nanosecond units |
| `KernelModeTime` | - | cpu system time is 100-nanosecond units |

[How to convert 100-nanosecond units to ms](https://msdn.microsoft.com/en-us/library/windows/desktop/dd979590(v=vs.85).aspx)

CPU usage in % (`[0].pcpu`) can be calculated like this:
```
cpu = (UserModeTime + KernelModeTime) / (now - StartTime) * 100
```

You can see this fields in action in my package [process-list](https://github.com/reklatsmasters/node-process-list)

**Comment by sebhildebrandt** [comment]
I just published a version (3.28.0) the also returns process information for Windows
