### ISSUE TITLE
networkInterfaces() returns question character instead of ó

### ISSUE THREAD

**Issue by MariaCamilaCubides** [sebhildebrandt/systeminformation#610]
**Describe the bug**
Hi. I am trying to find out all the interfaces from a device that has selected Spanish as the default language, but the response has a question character instead of ó. I tried to solve it by sending the command through utils.powershell() to use the OutputEncoding that you add recently but it doesn't work. 
**To Reproduce**
1. Run npm run test
2. Select option 3
2. See output

**Current Output**
`[
 ...,
  {
    iface: 'Conexi�n de red Bluetooth',
    ifaceName: 'Bluetooth Device (Personal Area Network)',
    ip4: '',
    ip4subnet: '',
    ip6: '',
    ip6subnet: '',
    mac: '98:01:a7:a7:94:a2',
    virtual: false,
    operstate: 'down',
    type: 'wired',
    duplex: '',
    mtu: '',
    speed: 3,
    dhcp: 'true',
    dnsSuffix: '',
    ieee8021xAuth: 'Unknown',
    ieee8021xState: 'Unknown',
    carrierChanges: 0
  }
]`

**Expected behavior**
`[
 ...,
  {
    iface: 'Conexión de red Bluetooth',
    ifaceName: 'Bluetooth Device (Personal Area Network)',
    ip4: '',
    ip4subnet: '',
    ip6: '',
    ip6subnet: '',
    mac: '98:01:a7:a7:94:a2',
    virtual: false,
    operstate: 'down',
    type: 'wired',
    duplex: '',
    mtu: '',
    speed: 3,
    dhcp: 'true',
    dnsSuffix: '',
    ieee8021xAuth: 'Unknown',
    ieee8021xState: 'Unknown',
    carrierChanges: 0
  }
]`

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.8
 -  VMware7,1
 - Windows 10 pro in spanish
 - CHCP 850

**Comment by sebhildebrandt** [comment]
@MariaCamilaCubides thank you for reporting ... currently ill, will work on it as sonn as I have recovered. One question: which command you tried to send to `util.powershell()`? Thank you in advance.

**Comment by MariaCamilaCubides** [comment]
Hi @sebhildebrandt. I tried sending this command `util.getWmic() + ' nic get /value'` and also I tried through the function `util.wmic()` sending the command `nic get /value`, but both responses were with the question character.

**Comment by sebhildebrandt** [comment]
Thank you @MariaCamilaCubides , quite clear. I guess I know what the problem is. Will try to find a solution as soon as I am fine again.

**Comment by sebhildebrandt** [comment]
@MariaCamilaCubides Can you test this one more time? I made a transition to powerShell also for `networkInterfaces()`. Hope that solves the problem now.

**Comment by MariaCamilaCubides** [comment]
@sebhildebrandt I tested `networkInterfaces()` and it works, now the output said `iface: 'Conexión de red Bluetooth'`. Thank you.
