### ISSUE TITLE
Rebase to use each platform's “native” protocol

### ISSUE THREAD

**Issue by iabtw** [sebhildebrandt/systeminformation#614]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Perhaps a major rewrite/rebase of the entire codebase to use each platform's “native” method of obtaining hardware information with ease. Example, for macOS, it's possible to use an Obj-C <-> Node bridge to interact with the system using the `IOKit` framework, which could easily provide easier, and far cleaner solutions.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sebhildebrandt** [comment]
@iabtw thank you for your idea. I am currently rewriting the whole library (converting to TS and making a lot of smaller improvements) but for the next version I am not planning to do the suggested transitions. I do think that this might be a quite good idea but means a complete rewrite for each platform. As I think that your proposal is quite interesting, I will think of it for the future.

For now I will keep on with the typescript transition, optimization and extending it with further functionality. Those improvements will be available in the upcoming version V6.

**Comment by iabtw** [comment]
👍 

In this case, I will begin writing a library, as I'd like to provide an efficient and “native” solution adjacent to this module. Especially considering the fact that it'd be more accessible if it were to use native protocols of the platform. Thank you for all your efforts, and for your response!
