### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Apollon77** [sebhildebrandt/systeminformation#617]
I have two sentry reports ... kind of same code place ...

https://sentry.iobroker.net/share/issue/7ddc08f5849947dd9948b80f2d8b51bb/
https://sentry.iobroker.net/share/issue/72de446d25da44dabc962eb9a1d3e749/

in fact about:
https://github.com/sebhildebrandt/systeminformation/blob/master/lib/users.js#L300-L303

You miss to check the result of the split :-)

**Comment by sebhildebrandt** [comment]
@Apollon77 thank you for your findings. Fixed. Version 5.9.12 just released

**Comment by Apollon77** [comment]
thank you!
