### ISSUE TITLE
Possibly incorrect timezone name

### ISSUE THREAD

**Issue by OmgImAlexis** [sebhildebrandt/systeminformation#621]
`Intl.DateTimeFormat().resolvedOptions().timeZone` returns `Australia/Adelaide` yet `time().timezoneName` is showing `Australian Central Daylight Time` should this be changed?

**Comment by sebhildebrandt** [comment]
@OmgImAlexis this was introduced in node 8 ... as this package should be compatible with older versions of node, I implemented it this was. But I will make a change to that (so taking this value if this is supported).

**Comment by OmgImAlexis** [comment]
Would it not make sense to drop support for 8 since it's not even LTS anymore and have people that need the older support use the older version of the library?

**Comment by sebhildebrandt** [comment]
@OmgImAlexis I agree partially, but v5 is still used also with older versions. The thing is, that having a view on nodes download numbers by version, this is still somehow important. changing that would be a breaking change.

For version systeminformation v6 the minimum v´nodejs version will be node 8.

**Comment by OmgImAlexis** [comment]
That doesn't make any sense. The minimum for v6 should be the current LTS. If users need older support they should use a compiler.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis I understand what you mean, and I would also do it that way on my side. But still I do not want introduce breaking changes here.

**Comment by OmgImAlexis** [comment]
That's exactly what version 6 should be. I'd suggest you read up on semver. A major version change is when breaking changes should happen. Removing callbacks and dropping the old node versions should both happen.

Otherwise the output of the build is going to need to include a bunch of extra stuff just to help a handful of people who can't be bothered using a compiler themselves.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis I completely agree. As I wrote for V6 I will change the minimal nodes version and here I changed this already. And yes of course, dropping callbacks etc. are breaking changes and therefore part of V6. 

But for version 5 this is not the case. And this is what I was referring to.

**Comment by sebhildebrandt** [comment]
@OmgImAlexis added this also to v5 with previous checking if `Intl` module exists. Version 5.9.13 just released.
