### ISSUE TITLE
function 'cpuCache()' bugs in windows 10

### ISSUE THREAD

**Issue by Asyunelus** [sebhildebrandt/systeminformation#628]
**Describe the bug**

**To Reproduce**
1. used function 'cpuCache()'
2. code snippet 'await si.cpuCache()'
3. start app / code
4. See output/error
                  if (level === '3' && cacheType === '5' && !result.cache.l1i && !result.cache.l1d) {
                                                                          ^
TypeError: Cannot read properties of undefined (reading 'l1i')

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: Windows 10 Insider Preview 22
 - Hardware [Hansung X7967T](https://www.monsterlabs.co.kr/src/category/read.html?pn=34383)

**Additional context**
it seem cpu.js source code mistake.

result object is not have 'cache' field, but this code is used them.

- current code
```nodejs
if (!error) {
  const parts = stdout.split(/\n\s*\n/);
  parts.forEach(function (part) {
    const lines = part.split('\r\n');
    const cacheType = util.getValue(lines, 'CacheType');
    const level = util.getValue(lines, 'Level');
    const installedSize = util.getValue(lines, 'InstalledSize');
    // L1 Instructions
    if (level === '3' && cacheType === '3') {
      result.cache.l1i = parseInt(installedSize, 10);
    }
    // L1 Data
    if (level === '3' && cacheType === '4') {
      result.cache.l1d = parseInt(installedSize, 10);
    }
    // L1 all
    if (level === '3' && cacheType === '5' && !result.cache.l1i && !result.cache.l1d) {
      result.cache.l1i = parseInt(installedSize, 10) / 2;
      result.cache.l1d = parseInt(installedSize, 10) / 2;
    }
  });
}
```

- Code that works when personally modified
```nodejs
if (!error) {
  const parts = stdout.split(/\n\s*\n/);
  parts.forEach(function (part) {
    const lines = part.split('\r\n');
    const cacheType = util.getValue(lines, 'CacheType');
    const level = util.getValue(lines, 'Level');
    const installedSize = util.getValue(lines, 'InstalledSize');
    // L1 Instructions
    if (level === '3' && cacheType === '3') {
      result.l1i = parseInt(installedSize, 10);
    }
    // L1 Data
    if (level === '3' && cacheType === '4') {
      result.l1d = parseInt(installedSize, 10);
    }
    // L1 all
    if (level === '3' && cacheType === '5' && !result.l1i && !result.l1d) {
      result.l1i = parseInt(installedSize, 10) / 2;
      result.l1d = parseInt(installedSize, 10) / 2;
    }
  });
}
```

**Comment by sebhildebrandt** [comment]
@Asyunelus fixed. Version 5.9.15 just released. Can you check it?

**Comment by Asyunelus** [comment]
it's works for me! thx!
