### ISSUE TITLE
Module not found: Error: Can't resolve 'osx-temperature-sensor' on Windows

### ISSUE THREAD

**Issue by JoeyBallentine** [sebhildebrandt/systeminformation#629]
**Describe the bug**
This package seems to be expecting an osx-only package on windows. This causes my app to crash.

**To Reproduce**
1. install
2. import
3. start app on windows

**Current Output**
```WARNING in ./node_modules/systeminformation/lib/cpu.js 1285:20-53
Module not found: Error: Can't resolve 'osx-temperature-sensor' in 'C:\Users\user\Documents\Git\project\frontend\node_modules\systeminformation\lib'  
 @ ./node_modules/systeminformation/lib/index.js 30:12-28
 @ ./src/components/DependencyManager.jsx 9:0-45 11:0-8
 @ ./src/components/Header.jsx 9:0-56 94:56-73
 @ ./src/pages/main.jsx 9:0-46 73:38-44
 @ ./src/app.jsx 6:0-36 12:39-43
 @ ./src/index.jsx 4:0-28 6:50-53
 @ ./src/renderer.js 30:0-21
```

**Expected behavior**
I think it's clear this shouldn't happen

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.15
 - OS: Windows 11
 - Hardware: Dell XPS 15

**Additional context**
None

**Comment by JoeyBallentine** [comment]
Ok so, I guess this only happens when using this in a node-integrated browser process (i.e. through electron/react) and not when used in a regular node environment

**Comment by sebhildebrandt** [comment]
You should be able to use this package also with electron but it needs to be in the `main.js` (or a module you require from there), not in a render process. See also the electron-api-demo (e.g. the power monitor)
