### ISSUE TITLE
CPU info is wrong on Windows?

### ISSUE THREAD

**Issue by Wyuyang** [sebhildebrandt/systeminformation#633]
**Describe the bug**
Hi, I'm a learner of Javascript. The information of Intel 12th CPU seems wrong？

**To Reproduce**
```javascript
const si = require('systeminformation');
si.cpu().then(data => console.log(data));
```

**Current Output**
```json
{
    "manufacturer": "12th",
    "brand": "Gen Intel® Core™ i5-12600K",
    "vendor": "GenuineIntel",
    "family": "6",
    "model": "151",
    "stepping": "2",
    "revision": "",
    "voltage": "",
    "speed": 3.69,
    "speedMin": 3.69,
    "speedMax": 3.69,
    "governor": "",
    "cores": 16,
    "physicalCores": 10,
    "processors": 1,
    "socket": "Other",
    "flags": "de pse tsc msr mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe",
    "virtualization": false,
    "cache": {
        "l1d": 128,
        "l1i": 256,
        "l2": 7864320,
        "l3": 20971520
    }
}
```

**Expected behavior**
Well, I think the correct manufacturer is Intel.

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.17
 - OS: Windows 11 21H2
 - Hardware: 12th Gen Intel(R) Core(TM) i5-12600K

**Comment by sebhildebrandt** [comment]
@Wyuyang I just released a new version (5.10.1) that should fix the problem. Can you test it on your side?
