### ISSUE TITLE
wifiConnections() doesn't return results (Possible OSX Monterey issue)

### ISSUE THREAD

**Issue by robertfirespotter** [sebhildebrandt/systeminformation#635]
**Describe the bug**
Calling si.wifiConnections() on OSX Monterey does not return any results

**To Reproduce**
1.  si.wifiConnections()

**Current Output**
None

**Expected behavior**
The connected endpoint(s) 

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.17
 - OS: macOS 12.1
 - Hardware: MacBook Pro 15

**Additional context**
I believe this is related to this issue: https://github.com/sebhildebrandt/systeminformation/issues/630 Because BSSID isn't returned from "airport -I" in monterey, this line doesn't evaluate to True
https://github.com/sebhildebrandt/systeminformation/blob/master/lib/wifi.js#L578
```
if (ssid && bssid) {
                  result.push({
```

**Comment by sebhildebrandt** [comment]
@robertfirespotter thank you for reporting ... fixed. Version 5.9.18 just released.

**Comment by k-funk** [comment]
Still not working for me:
```
[
  {
    id: 'Wi-Fi',
    iface: 'en0',
    model: 'AirPort',
    ssid: 'MySSIDName',
    bssid: '',
    channel: 157,
    frequency: 5785,
    type: '802.11',
    security: 'wpa2-psk',
    signalLevel: 27,
    txRate: '263'
  }
]
```

### Code
```
import si from 'systeminformation'

const connections = await si.wifiConnections()
const connection = connections.find(connection => connection.iface === 'en0')
console.log(connection)
```

MacOS 12.3.1
Node 17.7.1
@types/systeminformation@3.54.1
systeminformation@5.11.10
