### ISSUE TITLE
HWID

### ISSUE THREAD

**Issue by aledlb8** [sebhildebrandt/systeminformation#636]
Could you guys add a HWID features to get the user HWID ??

**Comment by sebhildebrandt** [comment]
@aledlb8 ...not sure what you mean with HWID. 

- if you mean hardware ID please have a look at the documentation https://systeminformation.io/system.html. Here you habe a function uuid which returns an array of different unique IDs like for the os or HW
- if you mean something different, I would be happy if you can explain what you would expect.

Best regards

**Comment by aledlb8** [comment]
yes, i mean the hardware ID not the uuid there are differents things the HWID is something like this L35B-8X37

**Comment by aledlb8** [comment]
and if you want to see your own HWID go to the terminal and type "vol c:" to see your HWID if the C disk

**Comment by sebhildebrandt** [comment]
@aledlb8 so 

- for the HWID this is exactly what you see in the results of `uuid().hardware` ...  (see docs)
- for drive IDs they are also visible in the according function `diskLayout()` ... here in the property `serialNum`

**Comment by aledlb8** [comment]
uuid().hardware is not what im looking for, when i use it i gave me a giant number and im only looking for a 8 digit number like this one L35B-8X37

**Comment by sebhildebrandt** [comment]
@aledlb8 

1. on which platform are you working?
2. how would you retrieve the expected HWID. What I am doing getting the HW ID is that I am following all recommendations about how to get this ID on each platform
3. did you also checked `si.system()`, `si.bios()`, `si.baseboard()` and `si.chassis()`?

**Comment by aledlb8** [comment]
1 windows
2 wdym?
3 i tried all of them and none of them give me the HWID

**Comment by sebhildebrandt** [comment]
@aledlb8 if you are referring to a number like `L35B-8X37` ... where does this come from?

**Comment by aledlb8** [comment]
from the hardware ID

**Comment by sebhildebrandt** [comment]
@aledlb8 what hardware ID? Please be more specific!

**Comment by aledlb8** [comment]
when you do "vol c:" in the command promt you will get your Harware ID thats what im trying to get using your npm

**Comment by sebhildebrandt** [comment]
@aledlb8 this is the VOLUME ID (not the hardware ID) and this should be also shown when using si.diskLayout(). If not, please provide both outputs here!

**Comment by aledlb8** [comment]
[
  {
    device: 'SCSI\\DISK&VEN_ASMT&PROD_2115\\6&3492D1A3&1&000000',
    type: 'Unspecified',
    name: 'ASMT 2115 SCSI Disk Device',
    vendor: '',
    size: 1000202273280,
    bytesPerSector: 512,
    totalCylinders: 121601,
    totalHeads: 255,
    totalSectors: 1953520065,
    totalTracks: 31008255,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: '0',
    serialNum: 'F10987654321',
    interfaceType: 'USB',
    smartStatus: 'Ok',
    temperature: null
  },
  {
    device: 'SCSI\\DISK&VEN_NVME&PROD_INTEL_SSDPEKNW51\\5&381FFB28&0&000000',
    type: 'SSD',
    name: 'INTEL SSDPEKNW512G8',
    vendor: 'INTEL',
    size: 512105932800,
    bytesPerSector: 512,
    totalCylinders: 62260,
    totalHeads: 255,
    totalSectors: 1000206900,
    totalTracks: 15876300,
    tracksPerCylinder: 255,
    sectorsPerTrack: 63,
    firmwareRevision: '002C',
    serialNum: '0000_0000_0100_0000_E4D2_5C6B_B0E1_4F01.',
    interfaceType: 'NVMe',
    smartStatus: 'Ok',
    temperature: null
  }
]

**Comment by sebhildebrandt** [comment]
@aledlb8 and please also for 

- `si.blockDevices()`
- `vol c:`

??

I need to see where this comes from and if this is NOT shown by systeminformation. To be clear, what you want to see is a VOLUME ID (not hardware ID)!

**Comment by aledlb8** [comment]
si.blockDevices() still doesnt work

**Comment by sebhildebrandt** [comment]
@aledlb8 Output of `vol c:` ?

**Comment by aledlb8** [comment]
Volume Serial Number is 9C5B-8C37

**Comment by sebhildebrandt** [comment]
@aledlb8 `si.blockDevices()` should work ... but if not, what is the output (in PowerShell) of 

`Get-CimInstance -ClassName Win32_LogicalDisk | Format-List *`

**Comment by aledlb8** [comment]
'Get-CimInstance' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sebhildebrandt** [comment]
@aledlb8 

- what windows version?
- what powershell version?

**Comment by aledlb8** [comment]
is working now, here is the output

Status                       :
Availability                 :
DeviceID                     : C:
StatusInfo                   :
Caption                      : C:
Description                  : Local Fixed Disk
InstallDate                  :
Name                         : C:
ConfigManagerErrorCode       :
ConfigManagerUserConfig      :
CreationClassName            : Win32_LogicalDisk
ErrorCleared                 :
ErrorDescription             :
LastErrorCode                :
PNPDeviceID                  :
PowerManagementCapabilities  :
PowerManagementSupported     :
SystemCreationClassName      : Win32_ComputerSystem
SystemName                   : LAPTOP-DE-ALE39
Access                       : 0
BlockSize                    :
ErrorMethodology             :
NumberOfBlocks               :
Purpose                      :
FreeSpace                    : 46720376832
Size                         : 510979805184
Compressed                   : False
DriveType                    : 3
FileSystem                   : NTFS
MaximumComponentLength       : 255
MediaType                    : 12
ProviderName                 :
QuotasDisabled               :
QuotasIncomplete             :
QuotasRebuilding             :
SupportsDiskQuotas           : False
SupportsFileBasedCompression : True
VolumeDirty                  :
VolumeName                   : maicra
VolumeSerialNumber           : 9C5B8C37
PSComputerName               :
CimClass                     : root/cimv2:Win32_LogicalDisk
CimInstanceProperties        : {Caption, Description, InstallDate, Name...}
CimSystemProperties          : Microsoft.Management.Infrastructure.CimSystemProperties

Status                       :
Availability                 :
DeviceID                     : X:
StatusInfo                   :
Caption                      : X:
Description                  : Local Fixed Disk
InstallDate                  :
Name                         : X:
ConfigManagerErrorCode       :
ConfigManagerUserConfig      :
CreationClassName            : Win32_LogicalDisk
ErrorCleared                 :
ErrorDescription             :
LastErrorCode                :
PNPDeviceID                  :
PowerManagementCapabilities  :
PowerManagementSupported     :
SystemCreationClassName      : Win32_ComputerSystem
SystemName                   : LAPTOP-DE-ALE39
Access                       : 0
BlockSize                    :
ErrorMethodology             :
NumberOfBlocks               :
Purpose                      :
FreeSpace                    : 1000048304128
Size                         : 1000186310656
Compressed                   : False
DriveType                    : 3
FileSystem                   : NTFS
MaximumComponentLength       : 255
MediaType                    : 12
ProviderName                 :
QuotasDisabled               :
QuotasIncomplete             :
QuotasRebuilding             :
SupportsDiskQuotas           : False
SupportsFileBasedCompression : True
VolumeDirty                  : False
VolumeName                   : md2
VolumeSerialNumber           : 485EA4B9
PSComputerName               :
CimClass                     : root/cimv2:Win32_LogicalDisk
CimInstanceProperties        : {Caption, Description, InstallDate, Name...}
CimSystemProperties          : Microsoft.Management.Infrastructure.CimSystemProperties

**Comment by aledlb8** [comment]
oh mb si.blockDevices() does work but it shows like this 9C5B8C37 and not like this 9C5B-8C37 and i got confused

**Comment by aledlb8** [comment]
but i have a question

[
  {
    name: 'C:',
    identifier: 'C:',
    type: 'disk',
    fsType: 'ntfs',
    mount: 'C:',
    size: '510979805184',
    physical: 'Local',
    uuid: '9C5B8C37',
    label: 'maicra',
    model: '',
    serial: '9C5B8C37',
    removable: false,
    protocol: ''
  {
    name: 'X:',
    identifier: 'X:',
    type: 'disk',
    fsType: 'ntfs',
    mount: 'X:',
    physical: 'Local',
    uuid: '485EA4B9',
    label: 'md2',
    model: '',
    serial: '485EA4B9',
    removable: false,
    protocol: ''
  }
]

this is the output of si.blockDevices() but when i console.log data.serial it shows undefined

**Comment by sebhildebrandt** [comment]
@aledlb8 as you can see ... it returns an array so you need to console.log `data[0].serial`

Closing this for now.
