### ISSUE TITLE
Either an enhancement or tips welcome

### ISSUE THREAD

**Issue by GerritKuilder** [sebhildebrandt/systeminformation#637]
**Is your feature request related to a problem? Please describe.**
I would like to use the output to be displayed on a webpage. The easiest way would be able to have the output formatted so that it is easier to deal with

**Describe the solution you'd like**
```
{"system": {
        "manufacturer": "ASUSTeK COMPUTER INC.",
        "model": "MINIPC PN51-E1",
        "version": "0302",
        "serial": "-",
        "uuid": "",
        "sku": "-",
        "virtual": false
    }
}

///============

{name: "system", data: {
      name:   "manufacturer", value:  "ASUSTeK COMPUTER INC.",
     name:    "model" , value:  "MINIPC PN51-E1",
     name:    "version": , value: "0302",
    name:     "serial", value:  "-",
    name:     "uuid", value: "",
    name:     "sku", value:  "-",
    name:     "virtual", value:  false
    }
}

```

**Describe alternatives you've considered**
I have been trying to find generic functions to parse an object to the desired output but have no been able to find something that allows me to achieve the desired result, considering the data can contain arrays of objects too 

**Additional context**
Any hints or tips pointing to a generic function to parse an object recursively to end up with name/value pairs would be welcome too.
I can use propertyName in vue to achieve the same result and lots of type checking, but I think working with name/value pairs would be easier.

Kind Regards,

Gerrit Kuilder

**Comment by sebhildebrandt** [comment]
@GerritKuilder as this would be a breaking change for the package and I do not really see big benefits for most of the use cases, I would rather recommend writing a small function that would wrap your data in the desired format like so:

```
cpu = { cpu: "1234", freq: "2GHz" }
mem = [ { size: 1000, type: "DDR4" }, { size: 2000, type: "DDR4" } ]

function wrapDataArray(data) {
	let res = [];
	data.forEach((elem) => {
		res.push(wrapDataObj(elem));
	})
	return res
}
function wrapDataObj(data) {
	const res = [];
	for (let prop in data) {
		res.push({
			name: prop,
			value: data[prop]
		})
	}
	return res
}

console.log(wrapDataObj(cpu));
console.log(wrapDataArray(mem));
```

Of course this is just a starting point but I think, you get the idea ;-) You can wrap the two functions into one with a first check which type of result you got back from systeminformation (object or array) and then call the desired function.

**Comment by GerritKuilder** [comment]
Hi Seb,

I completely understand, I have been looking into this for a day or so now, and I suppose I have to do further testing/coding.

I also realized I made a mistake because the desired output should be an array of name value pairs. I think I want to go from A to Z in one step rather than taking the long and winding road.
