### ISSUE TITLE
Did you remove the apps() 

### ISSUE THREAD

**Issue by mauriciocarvalho01** [sebhildebrandt/systeminformation#649]
Did you remove the apps() function to get the information from the applications?

const valueObject = {
                apps: "*"
            }

si.get(valueObject).then(data => console.log(data.apps)); //===>> undefined ??

**Comment by sebhildebrandt** [comment]
@mauriciocarvalho01 Did we have something like that? Maybe I am confused tonight. I know, that I had the plan to implement something like that but I do not remember that I had this implemented.

In which version you had this function?

**Comment by mauriciocarvalho01** [comment]
Sorry, this role was created by my team.
But it is a good alternative for your library.
Thanks for the answer!

**Comment by sebhildebrandt** [comment]
@mauriciocarvalho01 thank you! What would you expect / like to see when calling `si.apps()`? Any wishes?

**Comment by mauriciocarvalho01** [comment]
Here we implement an apps() function to report on installed apps
Here we implement an apps() function for reporting on installed apps.
We get the following result
`
{
	"apps": [
		{
			id: 85,
			name: 'WindowsAppCertificationKitNativeComponents',
			vendor: 'MicrosoftCorporation',
			version: '10.1.19041.685',
			caption: 'WindowsAppCertificationKitNativeComponents'
		},
		{
			id: 86,
			name: 'MicrosoftVisualC++2022X86DebugRuntime-14.30.30708',
			vendor: 'MicrosoftCorporation',
			version: '14.30.30708',
			caption: 'MicrosoftVisualC++2022X86DebugRuntime-14.30.30708'
		},
	]
}
`
For now, it's only supported by windows
