### ISSUE TITLE
Don't Returns Mac's

### ISSUE THREAD

**Issue by frank-dspeed** [sebhildebrandt/systeminformation#65]
node 8.4
Ubuntu 17.10
```
  { iface: 'wlx803f5d20b751',
    ip4: '192.168.0.17',
    ip6: '',
    mac: '00:00:00:00:00:00',
    internal: false },
  { iface: 'docker0',
    ip4: '172.17.0.1',
    ip6: '',
    mac: '00:00:00:00:00:00',
    internal: false },
  { iface: 'br-79bf4b77c82a',
    ip4: '172.19.0.1',
    ip6: '',
    mac: '00:00:00:00:00:00',
    internal: false } ]

```

**Comment by sebhildebrandt** [comment]
Hi,

does `os.networkInterfaces()` returns mac addresses? Can you post the output?

**Comment by sebhildebrandt** [comment]
Seems to be an node issue, with node 7.x I got correct mac addresses, node 8.4 does not return correct mac addresses. See https://github.com/nodejs/node/issues/13581

**Comment by sebhildebrandt** [comment]
There is already a pull request in the node repo, that should fix this issue.

**Comment by frank-dspeed** [comment]
@sebhildebrandt 
```
13: vetha0a97ab@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 1e:4e:f6:04:7f:f8 brd ff:ff:ff:ff:ff:ff link-netnsid 0
15: veth152eff9@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 7e:98:f7:46:ff:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 1
17: veth628819b@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-79bf4b77c82a state UP group default 
    link/ether be:ea:22:08:05:2e brd ff:ff:ff:ff:ff:ff link-netnsid 3

```

**Comment by sebhildebrandt** [comment]
Yes, os returns it correct but the node built-in function `os.networkInterfaces()` has an issue (which has already a pull request). As soon as this gets into the node core, System Information will again return correct values. Hope that is fine for you.

**Comment by ItsEcholot** [comment]
You could circumvent this issue temporarily till the node bug gets resolved by downgrading to Node v7 as, like @sebhildebrandt mentioned, the mac address detection works like a charm there.

**Comment by sebhildebrandt** [comment]
Anyway, I hope the node team will merge the pull request on their side soon ;-)

**Comment by XadillaX** [comment]
https://github.com/nodejs/node/commit/8485a7c0b71fd1dd36947a6dd02b75387805d9b7

I think you may close this issue now.

**Comment by frank-dspeed** [comment]
I only wanted to report that i don't have any problems i droped this package already in favor of my own class that calls os and does exec

**Comment by XadillaX** [comment]
@sebhildebrandt Maybe you can use https://github.com/node-modules/address to get MAC address. Because it has a fallback solution to get the right MAC address during the wrong version of Node.js.

**Comment by sebhildebrandt** [comment]
I guess you are right, waiting for the pull request on node.js side will anyway not fix the problem that with some node.js you will have wrong MAC addresses. As I want to keep this library dependency free, I will implement a fallback code to get correct MAC versions. I will try to do it next week. And btw. thank you for your comments/suggestions!

**Comment by sebhildebrandt** [comment]
Just published a fix for that ...
