### ISSUE TITLE
OpenBSD: bad param for hostname command

### ISSUE THREAD

**Issue by jonathonfletcher** [sebhildebrandt/systeminformation#651]
**Describe the bug**

systeminformation@5.9.3

osinfo.js line 173

"-f" option is not valid in OpenBSD (tested with 7.0).

suggest breaking out the "if" on line 171 to be more specific.

**To Reproduce**
1. used function '...'
2. code snippet '....'
3. start app / code
4. See output/error '....'

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.3
 - OS: [e.g. macOS] OpenBSD 7.0
 - Hardware [e.g. MacBook Pro 13] N/A

**Additional context**

**Comment by sebhildebrandt** [comment]
@jonathonfletcher thank you! I will correct that tonight a d make a new release!

**Comment by sebhildebrandt** [comment]
@jonathonfletcher Done, Version 5.11.1 just released. Can you check it on your side?
