### ISSUE TITLE
Power Shell Execution Policy Getting Altered To "Unrestricted"

### ISSUE THREAD

**Issue by Omair-Abdul** [sebhildebrandt/systeminformation#655]
With SystemInformation 5.9.4 we see that the PowerShell execution policy is getting Altered to "Unrestricted". This is the PowerShell command getting executed - "powershell.exe -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -"

When using SystemInformation 4.34.17, we did not see a similar behavior. Why is Systeminformation 5.9.4  requiring the policy to be altered to "Unrestricted". Why specifically does SystemInformation 5.9.4 require unrestricted policy - does it need unrestricted policy to run a certain script or get certain info?

We would like to get an understanding of why SystemInformation 5.9.4 requires the "Unrestricted" policy for security purposes? Thank you.

**Comment by sebhildebrandt** [comment]
@Omair-Abdul Thank you for asking and reporting! I will check the situation - the reason for this was issues with some commands that I discovered. Will come back later when the situation is clear on my side.

**Comment by Omair-Abdul** [comment]
Thank You @sebhildebrandt!

**Comment by sebhildebrandt** [comment]
@Omair-Abdul ... I checked the code and my `powershell` implementation always had ` -ExecutionPolicy Unrestricted` (since it was introduced in September 2018). But anyway I do not really see a reason why this is necessary. I removed this flag and published a new version 5.11.4

**Comment by MikeMM70** [comment]
@sebhildebrandt I am using a project (HomeBridge) that uses this library, and it took me what to find out this was the source of the "powershell.exe -NoLogo -InputFormat Text -NoExit -ExecutionPolicy Unrestricted -Command -" wat was showing up in my process list every 5 seconds or so.  Anyway, why was the -Execution Policy added back in?  I didn't see it mentioned in the changelog after the line for 5.11.4.  I took it back out on my local copy of the library and it seems fine.  The "Unrestricted" had me unnerved.
