### ISSUE TITLE
Temperature prop missing in DiskLayoutData interface

### ISSUE THREAD

**Issue by ShapeMess** [sebhildebrandt/systeminformation#659]
**Describe the bug**
`si.diskLayout` is peoperly giving out the `temperature` property, though it's missing on the interface DiskLayoutData (line 225) in type declarations which triggers TS to throw errors.

**Current Output**
![image](https://user-images.githubusercontent.com/80402817/156234016-944bd662-0d84-4b37-afa4-b18f8ce31ae9.png)
`temperature` property missing on the interface:
![image](https://user-images.githubusercontent.com/80402817/156234108-2515785a-3bcf-4b3a-b2c2-610deb3b1681.png)

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.5

**Additional context**
I'm not sure if this is because this feature is planned to be removed or if it's just a mistake that happened during compilation.
Either way I wanted to point this issue out.

**Comment by sebhildebrandt** [comment]
@ShapeMess my fault. Forgot to add it in typings. As soon as SmartNonTools are installed, this value is also available. I fixed the type definitions. Version 5.11.6 just released. Thank you for reporting!
