### ISSUE TITLE
Using Raspbian on a Raspberry pi zero W doesn't retrieve any graphics info

### ISSUE THREAD

**Issue by jjtbsomhorst** [sebhildebrandt/systeminformation#66]
Hi, 

I'm currently using your package for retrieval of the graphics information of the system. On my windows device I get the information I need ( resolution of all connected displays). On my raspberry pi zero W on the other hand I get the following: 

{
    "controllers": [],
    "displays": [
        {
            "connection": "default",
            "main": false,
            "builtin": false
        }
    ]
}

**Comment by sebhildebrandt** [comment]
Let me check it on my raspberry machines... Need to see what the issue can be here ...

**Comment by jjtbsomhorst** [comment]
Could it be because the resolution is set in the /boot/config.txt

**Comment by sebhildebrandt** [comment]
Not sure right now. I will be at my office tomorrow. There I can test several raspberry machines. OK for you?

**Comment by jjtbsomhorst** [comment]
yeah ofcourse. Take your time. I'm just working on a little hobby project 👍

**Comment by ItsEcholot** [comment]
Probing the raspberry pi drivers to retrieve the resolution could present itself as very difficult (semi open-source drivers). The solution that comes to mind is like @jjtbsomhorst mentioned to read out the config file under /boot/config.txt.
This approach only works if the resolution has been set manually, as the pi supports getting the screens resolution over CEC. In that case the user would most likely not have defined any resolution in the config.txt.

**Comment by jjtbsomhorst** [comment]
@ItsEcholot how would you retrieve the screen resolution when the user has not set the reso in the config?

**Comment by ItsEcholot** [comment]
I read somewhere that the pi uses CEC to get information about the timings & resolution from the display. 
So I guess an approach would be to use a library like [libcec ](https://github.com/Pulse-Eight/libcec) to send the appropriate commands to the display and receive the responses. This obviously would only work on devices that support CEC (you also need a "full" hdmi cable, had some problems getting CEC to work last time because of a cheap hdmi cable).

Another approach would be `fbset -s`. Although not sure if that reports the correct resolution reliably.

**Comment by ItsEcholot** [comment]
@jjtbsomhorst Did the approach mentioned by me (`fbset`) work for you? This information will help greatly in fixing this issue.

**Comment by jjtbsomhorst** [comment]
@ItsEcholot  haven't tested it yet. I will come back with my findings when I have time to do so

**Comment by jjtbsomhorst** [comment]
I thought, if I have time to write a reaction that I will do it in the future I could also just fire up my raspberry and see what happens. So When I use the command fbset -s I do get the resolution.

**Comment by sebhildebrandt** [comment]
Setting up a new Raspberry today ... maybe I can come up with some fix here ...

**Comment by sebhildebrandt** [comment]
Just commited a fix on GitHub. Will release the npm package (as new version 4.0 with lot of changes / new features) within the next 2 weeks.

**Comment by sebhildebrandt** [comment]
Should work now. Version 4.0.0 published
