### ISSUE TITLE
CPU Temperature is one constant number

### ISSUE THREAD

**Issue by NoobishSVK** [sebhildebrandt/systeminformation#662]
**Bug description:**
I am trying to extract CPU temperature info, unfortunately the number doesn't change at all, not even after reboot, it's always the same even though other programs report completely different temperatures. It's always 27.8 / 29.8 using this library no matter the load / time. It just always reports the same number.

**Problem reproduction**
1. used function:     si.cpuTemperature().then(data => console.log(data));

**Current Output**
![obrázok](https://user-images.githubusercontent.com/17816750/157498312-1c12436d-e775-44f9-9552-21e7c6ba016a.png)

**Expected behavior**
I would expect the temperatures to be read correctly. The program was started with admin privileges when I did this. Without admin privileges it doesn't show the temperature at all (i'm aware of this from the documentation).

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.6
 - OS: Windows 10 LTSC 21H2
 - Hardware: Custom built PC, i7 4790K, Gigabyte Z97X Gaming 3 

**Additional context**
It might be a hardware specific error, unfortunately I don't have any other HW to test this with as of yet.

**Comment by sebhildebrandt** [comment]
@NoobishSVK can you provide the output of the following command (from powerShell):

```
Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature
```

Would be good if you execute this several times (with no load and under heavy load) to see if windows is aware of temperature changes ... thank you in advance

**Comment by NoobishSVK** [comment]
Tests have been made under different loads at a different time, seems like the result is always the same - even after rebooting. 
I have checked with a Ryzen 7 2700 CPU with a Gigabyte B450M motherboard, same issue except the temperature is reported as ~16.7°

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


PS C:\WINDOWS\system32> Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature

CurrentTemperature
------------------
              3010
              3030


```

**Comment by sebhildebrandt** [comment]
@NoobishSVK so it seems as windows gives back those number, there is not much I can do in this case (when relying on what windows provides). Closing it for now. I anyway fixed one issue related to your report ... the `NaN` value should now no longer be present. Version 5.11.7 just released.
