### ISSUE TITLE
LGA1150 boards are being misreported as LGA1155

### ISSUE THREAD

**Issue by NoobishSVK** [sebhildebrandt/systeminformation#663]
**Describe the bug**
Mentioned it already in the title. I have tried multiple HW configurations with different LGA1150 cpus and motherboards

**To Reproduce**
1. used function      document.getElementById('boardsocket').innerHTML = data.socket;

**Current Output**
It should show LGA1150, it's being misreported as LGA1155, which is for CPUs of 2/3gen, not 4.

**Expected behavior**
I'd expect it to show LGA1150 as that's what the socket is.

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.7 
 - OS: Win 10 Pro / Win 10 LTSC
 - Hardware:
 - 
![obrázok](https://user-images.githubusercontent.com/17816750/157937120-ad9c689c-73da-49dd-8d5f-8f7ada8e6935.png)
![obrázok](https://user-images.githubusercontent.com/17816750/157937139-821488b0-1b6a-44d1-a91a-1ccd55365b1e.png)

**Additional context**
I think there might be some adjusting of filters needed to filter which CPUs are for 1155 and which ones are for 1150. I have tried this with 2 machines with completely different boards, but same generation of CPU.

**Comment by sebhildebrandt** [comment]
@NoobishSVK ... can you provide (from powershell) the output of

```
Get-WmiObject Win32_processor | Select * | fl
```

Thank you in advance

**Comment by NoobishSVK** [comment]
Here's the report:

`PSComputerName                          : MIKUNET-NOOBISH
Availability                            : 3
CpuStatus                               : 1
CurrentVoltage                          : 12
DeviceID                                : CPU0
ErrorCleared                            :
ErrorDescription                        :
LastErrorCode                           :
LoadPercentage                          : 15
Status                                  : OK
StatusInfo                              : 3
AddressWidth                            : 64
DataWidth                               : 64
ExtClock                                : 100
L2CacheSize                             : 1024
L2CacheSpeed                            :
MaxClockSpeed                           : 4000
PowerManagementSupported                : False
ProcessorType                           : 3
Revision                                : 15363
SocketDesignation                       : SOCKET 0
Version                                 :
VoltageCaps                             :
__GENUS                                 : 2
__CLASS                                 : Win32_Processor
__SUPERCLASS                            : CIM_Processor
__DYNASTY                               : CIM_ManagedSystemElement
__RELPATH                               : Win32_Processor.DeviceID="CPU0"
__PROPERTY_COUNT                        : 57
__DERIVATION                            : {CIM_Processor, CIM_LogicalDevice, CIM_LogicalElement, CIM_ManagedSystemEleme
                                          nt}
__SERVER                                : MIKUNET-NOOBISH
__NAMESPACE                             : root\cimv2
__PATH                                  : \\MIKUNET-NOOBISH\root\cimv2:Win32_Processor.DeviceID="CPU0"
Architecture                            : 9
AssetTag                                : Fill By OEM
Caption                                 : Intel64 Family 6 Model 60 Stepping 3
Characteristics                         : 4
ConfigManagerErrorCode                  :
ConfigManagerUserConfig                 :
CreationClassName                       : Win32_Processor
CurrentClockSpeed                       : 4000
Description                             : Intel64 Family 6 Model 60 Stepping 3
Family                                  : 198
InstallDate                             :
L3CacheSize                             : 8192
L3CacheSpeed                            : 0
Level                                   : 6
Manufacturer                            : GenuineIntel
Name                                    : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
NumberOfCores                           : 4
NumberOfEnabledCore                     : 4
NumberOfLogicalProcessors               : 8
OtherFamilyDescription                  :
PartNumber                              : Fill By OEM
PNPDeviceID                             :
PowerManagementCapabilities             :
ProcessorId                             : BFEBFBFF000306C3
Role                                    : CPU
SecondLevelAddressTranslationExtensions : True
SerialNumber                            :
Stepping                                :
SystemCreationClassName                 : Win32_ComputerSystem
SystemName                              : MIKUNET-NOOBISH
ThreadCount                             : 8
UniqueId                                :
UpgradeMethod                           : 36
VirtualizationFirmwareEnabled           : True
VMMonitorModeExtensions                 : True
Scope                                   : System.Management.ManagementScope
Path                                    : \\MIKUNET-NOOBISH\root\cimv2:Win32_Processor.DeviceID="CPU0"
Options                                 : System.Management.ObjectGetOptions
ClassPath                               : \\MIKUNET-NOOBISH\root\cimv2:Win32_Processor
Properties                              : {AddressWidth, Architecture, AssetTag, Availability...}
SystemProperties                        : {__GENUS, __CLASS, __SUPERCLASS, __DYNASTY...}
Qualifiers                              : {dynamic, Locale, provider, UUID}
Site                                    :
Container                               :`

**Comment by sebhildebrandt** [comment]
@NoobishSVK ... I see ... windows reports socket 1155 (the upgradeMethod value of 36 indicates this socket ... due to SMBIOS reference specs). I now added a function that should correct wrong values. As I cannot really test it here, can you test the current code here on GitHub? 

If you clone the current state of the code

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

then just type `c` to get the `cpu()` output. Can you provide this output?

**Comment by NoobishSVK** [comment]
Awesome, it seems to work now - socket is reported as LGA1150.
Thank you very much for your prompt answers!

```
{
  manufacturer: 'Intel',
  brand: 'Core™ i7-4790K',
  vendor: 'GenuineIntel',
  family: '6',
  model: '60',
  stepping: '3',
  revision: '15363',
  voltage: '',
  speed: 4,
  speedMin: 4,
  speedMax: 4,
  governor: '',
  cores: 8,
  physicalCores: 4,
  processors: 1,
  socket: 'LGA1150',
  flags: 'de pse tsc msr mce sep mtrr mca cmov psn clfsh ds acpi mmx fxsr sse sse2 ss htt tm ia64 pbe',
  virtualization: false,
  cache: { l1d: 0, l1i: 0, l2: 1048576, l3: 8388608 }
}
```

**Comment by sebhildebrandt** [comment]
@NoobishSVK thank you for testing!! Version 5.11.8 just released.
