### ISSUE TITLE
Cannot get CPU temperature on Leonov Idea pad 3

### ISSUE THREAD

**Issue by babojamo** [sebhildebrandt/systeminformation#665]
Cannot get the CPU temperature, returns empty

**To Reproduce**
1. used function 'cpuTemperature'
2. code snippet
```
    await siLib.cpuTemperature().then(data=> {
      this.setTemperatureInfo(data);
      this.setTemperatureAlert(data);
    }).catch(error => {
      throw error;
    });
```
    
3. start app / code
4. See output/error
```
{
    "main": null,
    "cores": [],
    "max": null,
    "socket": [],
    "chipset": null
}
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.10.7
 - OS: Windows 10 pro
 - Hardware: Lenovo idea pad 3

**Additional context**
Tried to run the WMI command and the out is like this
```
Get-WmiObject : Not supported
At line:1 char:1
+ Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

**Comment by sebhildebrandt** [comment]
@babojamo ... There are two reasons why this can happen:

1. on some machines this requires to run with admin privileges 
2. on some machines `MSAcpi_ThermalZoneTemperature` is not supported. Not all machines can support reading of the cpu temperature, it's a function of your BIOS software. Sometimes the bios manufacturer will supply dll's that you can reference to call the required function and return the details, when you reboot your computer. 

See also https://systeminformation.io/issues.html
