### ISSUE TITLE
Windows 11 CPU Information Incorrect

### ISSUE THREAD

**Issue by zSchadt** [sebhildebrandt/systeminformation#668]
**the program:**
```
si.<cpuTemperature|cpuCurrentSpeed>()
  .then(data => console.log(data))
  .catch(error => console.error(error));
```

**The thing:**
I always get the exact same response when calling `CPUTemperature` api:
```
{ main: 27.8, cores: [ 27.8 ], max: 27.8, socket: [], chipset: null }
```
And when calling `cpuCurrentSpeed`:
```
{
  min: 3.6,
  max: 3.6,
  avg: 3.6,
  cores: [
    3.6, 3.6, 3.6, 3.6,
    3.6, 3.6, 3.6, 3.6,
    3.6, 3.6, 3.6, 3.6,
    3.6, 3.6, 3.6, 3.6
  ]
}
```

**I want:**
I'd expect to see more individual core temperatures, as well as variations in the temperatures.
```
{ main: 30.5, cores: [ 27.8, 30, 31, 28, ... ], max: 32, socket: [], chipset: null }
```
Similarly for the core speeds to reflect what I'm seeing in other monitoring apps like HWInfo.

**the set up:**
 - Admin windows powershell
 - systeminformation package version: 5.11.8
 - Node: v16.13.2
 - OS: windows 11 10.0.22000
 - CPU: intel i9900k

**Comment by sebhildebrandt** [comment]
@zSchadt ... I wish that Microsoft works on their WMI to provide correct information within the OS ... unfortunately I have to rely on OS functionality in this library. Otherwise this would become a project just for one platform and would then need a lot of implementation specific to different HW settings.

**Comment by sebhildebrandt** [comment]
Closing it for now as I do not see an alternative to the windows system functions.
