### ISSUE TITLE
product_serial and product_uuid require root

### ISSUE THREAD

**Issue by mikelpr** [sebhildebrandt/systeminformation#669]
**Describe the bug**
/sys/devices/virtual/dmi/id/product_{serial,uuid} are only readable by root so systeminformation returns '' for them

**To Reproduce**
· `cat /sys/devices/virtual/dmi/id/product_{serial,uuid}`
· `await require('systeminformation').system().uuid`

**Current Output**
cat fails with Permission denied and systeminformation.system().uuid returns an empty string ''

**Expected behavior**
do something like pkexec for getting the uuid. maybe a separate function for elevated UUID/serial

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.9
 - OS: Fedora 35
 - Hardware: ASUS Prime X470 Pro, Ryzen 7 2700X

**Comment by sebhildebrandt** [comment]
@mikelpr as I do not see any possibility to get data from `/sys/devices/virtual/dmi/id/product_{serial,uuid}` without root privileges I am closing this for now. If you have any other Idea here, please feel free to reopen this issue.
