### ISSUE TITLE
Linux report memories, but with null data

### ISSUE THREAD

**Issue by SagoBno** [sebhildebrandt/systeminformation#670]
**Describe the bug**
When it requires ram information, System Information returns an array with some empty objects and others with real data.

**To Reproduce**
1. used function 'si.memLayout()' with sudo permissions like the following example :
![Captura de pantalla de 2022-03-28 14-43-26](https://user-images.githubusercontent.com/50707624/160475098-b3fb0490-c10b-483c-bbc9-a92fd1d6dd62.png)

**Current Output**
![image](https://user-images.githubusercontent.com/50707624/160476136-376b0305-28b6-4725-a286-9af9495a7881.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/50707624/160476467-15b6098c-fb2f-4fb6-9c03-7a1dafe12eaf.png)

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.6 and latest version
 - OS: Ubuntu, Kubuntu, Lubuntu and Linux Mint
 - Hardware Asus X555QG laptop

**Comment by sebhildebrandt** [comment]
@SagoBno can you provide the output of 

```
cat /proc/meminfo
```

on your machine? Which Linux distribution (and version) are you using?

**Comment by sebhildebrandt** [comment]
@SagoBno I did a research on this one and this seems to be OK as on your machine there seems to be 4 slots, two of them are empty. Closing it for now.
