### ISSUE TITLE
Memory metrics don't correspond with top or htop results

### ISSUE THREAD

**Issue by zmink-pxc** [sebhildebrandt/systeminformation#671]
**Describe the bug**
I'm using the observe function to collect parameters, including the memory of the device. The observe function is set onInterval of 5000ms.  My goal is to reproduce metrics similar to htop.  However, none of the memory metrics returned match the htop results.  For this test scenario, I'm running systeminformation in a container on an amd64 ubuntu host, but receive similarly unintuitive results on every device/environment I have tested.  What calculations should I be using to produce numbers which "match" htop results for memory consumption?

**To Reproduce**
Keys/values I am monitoring via observe:

{
    currentLoad: 'avgLoad,currentLoad,currentLoadNice,currentLoadIdle,currentLoadIrq',
    fsSize: 'fs,size,used,available,mount',
    mem: 'total,free,used,available,swaptotal,swapused,swapfree'
}

An example screenshot of my htop results:
![image](https://user-images.githubusercontent.com/45803332/161620893-3f9cde83-9d19-48be-9295-5937d1953e40.png)

Snapshot of results from systeminformation observe function:

{
  total: 11,735,089,152,    //expected actual "10.9GB"
  free: 253,050,880,
  used: 11,482,038,272,    //expected actual "7.8GB"
  available: 1,892,499,456,
  swaptotal: 2,147,479,552,
  swapused: 1,394,110,464,
  swapfree: 753,369,088,
}

**Current Output**
As listed above, systeminformation returns the following
memory total ~11.7GB
memory used ~11.5GB

**Expected behavior**
I would expect memory total to be ~11GB.
I would expect used total to be ~7.8GB.

I have attempted to use the various memory metrics to attempt to account for the disparities, but none seem to give reasonable results.  Is there math that I am missing for getting htop like metrics?  Alternatively, does the observe method correctly calculate memory values?

**Environment (please complete the following information):**
 - systeminformation package version: 5.6.21
 - OS: Ubuntu 20, running inside arm64 container using qemu
 - Hardware: Intel® Core™ i7-7820HQ CPU @ 2.90GHz × 2

**Comment by Saahilp18** [comment]
Hey, I'm having a similar issue. 
I am more concerned with how it showing I am using over 32GB of memory when I only have 32GB installed.
{
  total: 34359738368,   ~ 32.768 (Should be 32GB)
  free: 65159168,            
  used: 34294579200,   ~32.54790625 (Should be 17GB)
  active: 6319439872,
  available: 28040298496,
  buffers: 0,
  cached: 0,
  slab: 0,
  buffcache: 27975139328,
  swaptotal: 22548578304,
  swapused: 21786787840,
  swapfree: 761790464
}

**Comment by sebhildebrandt** [comment]
Hi @Saahilp18 ... if you have 32GB of ram then this is

1024 * 1024 * 1024 * 32 Bytes 

which is 34359738368 Bytes

So the total amount is correct. Question: what OS / Distribution are you using?

**Comment by Saahilp18** [comment]
I see, thank you. I am using MacOS Monterey V12.1.

**Comment by zmink-pxc** [comment]
I haven't been able to fully account for the total memory discrepancy, but the "htop" issue is clearly my misinterpretation of htop results.  The fractional memory usage is the 'active' memory in systeminformation terminology over the total memory.  The multicolored RAM bar displays active memory in green, blue is buffer and yellow is cache.  In my original post, 'used' memory does more closely match the expected value since used includes active, buffer, and cache.

**Comment by sebhildebrandt** [comment]
@zmink-pxc ... concerning total mem:

11735089152 / (1024 * 1024 * 1024) = 10.92

**Comment by zmink-pxc** [comment]
> @zmink-pxc ... concerning total mem:
> 
> 11735089152 / (1024 * 1024 * 1024) = 10.92

Thanks @sebhildebrandt
