### ISSUE TITLE
si.blockDevices() not support Win7 ?

### ISSUE THREAD

**Issue by Nicholas-Luoyi** [sebhildebrandt/systeminformation#672]
Hi. I am using the systeminformation of version 5.11.9. I want to get the array of all disks on PC and filter the removable disks. So I used the si.blockDevices() function. It works all fine with win 10, MacOS etc. But some of my colleague is still using win 7. And the function list nothing on all win 7 computers. I have read the DOC and it says the function supports win. I just want to check that if this function can be supported on win 7. Thanks!

**Comment by fengqinghuaYA** [comment]
Check your PowerShell version and powershell2.0 not support the 'Get-CimInstance' .

**Comment by xmsz-stu** [comment]
what is the version support win7?

**Comment by sebhildebrandt** [comment]
All windows versions with powerShell 3.0 are supported ... Windows 8 and Windows Server 2012 are shipped with PowerShell 3.0 but you can anyway also install PowerShell 3.0 on Windows 7 SP 1 and above. 

The reason, we had to move from `wmic` and  `get-wmiobject` to `Get-CimInstance` was, that the first two ones are already deprecated

In version 5.9.10 we did the transition from WMIC to PowerShell (using `get-wmiobject`)
In version  5.12.14 we did the transition from `get-wmiobject` to `Get-CimInstance`

Hope this helps. Maybe you try version 5.9.8 (or maybe 5.9.7)

**Comment by xmsz-stu** [comment]
> All windows versions with powerShell 3.0 are supported ... Windows 8 and Windows Server 2012 are shipped with PowerShell 3.0 but you can anyway also install PowerShell 3.0 on Windows 7 SP 1 and above.
> 
> The reason, we had to move from `wmic` and `get-wmiobject` to `Get-CimInstance` was, that the first two ones are already deprecated
> 
> In version 5.9.10 we did the transition from WMIC to PowerShell (using `get-wmiobject`) In version 5.12.14 we did the transition from `get-wmiobject` to `Get-CimInstance`
> 
> Hope this helps. Maybe you try version 5.9.8 (or maybe 5.9.7)

thx
