### ISSUE TITLE
networkStats() causes disturbance to video connection

### ISSUE THREAD

**Issue by glenninn** [sebhildebrandt/systeminformation#673]
**Describe the bug**
I am running a NodeJS video client application on my Macbook Pro running Monterey 12.3.
I added a 5 second loop to poll networkStats() to track the Tx and Rx data rates.  What I
noticed is that when the networkStats() API runs, I get a momentary frozen video image.

Are the systeminformation tests intrusive -- that is -- is it expected that they would impact
currently flowing network traffic? 

**To Reproduce**
1. Create a setInterval() loop that runs every 5 seconds.  At timeout, call networkStats() on the default interface
2.  Here is the relevant code
```
pollCartNetworkStats(periodInMs: number = NETWORK_INFO_PERIOD_MS) {
        this.intervalHandle = setInterval(
            ()=>{
                libSI.networkStats("").then(
                    (niStats)=>{
                        this.logNetworkInfo(ni0)
                    }
                )
            },
            periodInMs
        );
    }
```

**Current Output**
At 5 second intervals, you can observe objects in the video that were in motion, hesitate for 200-300ms, on average.

**Expected behavior**
When I disable this function, the video runs smoothly at all times

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.9
 - OS:  MacOS 12.3
 - Hardware MacBook Pro 15

**Comment by sebhildebrandt** [comment]
@glenninn thank you for reporting. Can you open activity monitor on your machine and see if you have spikes (CPU usage up to 100%) each 5 seconds?

I testet it on my machine with an interval of 0.5 seconds with no issues. Played also several video steams at the same time wish no stuttering. CPU load was at aprox. 4% for the node process. 

Here is my code that I testet (with a simple console.log):

```
const si = require('systeminformation');

setInterval(function() {
	si.networkStats('*').then(data => {
	    console.log(data);
	})
}, 500)
```

Would be fine if you can provide your findings (CPU load etc.).

**Comment by glenninn** [comment]
Hi Sebastian,
  I will try to do more testing, but we are in the middle of a production release so it may be a bit before I can get back to this.  Note that the "video" I was referring to was a video conference.  Basically, what appears to me is that in accessing the network stats it does something to the network for a moment that causes some sort of disruption.

Stay tuned...
-Glenn

**Comment by sebhildebrandt** [comment]
@glenninn Thank you! Will also test it here ... running my code while having video conferences. Tomorrow there is a good chance as I have several online meetings.

**Comment by sebhildebrandt** [comment]
@glenninn ... I tested this today with several video conferences (teams, Skype, zoom) without any problems - setting intervals to 700ms. Also in the activity monitor I do not see any problems or spikes ... maybe - as soon as you have time - can also share your findings. Thank you in advance.

**Comment by glenninn** [comment]
Sebastian,
  I tested the code both when its integral in our video app, and when it runs as a separate process.  What I've found is that the lagginess occurs when I run integral to our process.  Since we have code that does need to run on a regular periodic basis, the laggy behavior implies that the networkStats() module is blocking in some way.

When we run the code in a separate app/process, all things work fine.

So can you look at your implementation and see if there is some code that will sit in a "wait loop" of some sort and not relinquish back to the JS Event Loop?

**Comment by sebhildebrandt** [comment]
@glenninn Can you test the latest version 5.11.13 ... this should fix the problem!

**Comment by sebhildebrandt** [comment]
@glenninn did you had time to test it with the latest version again ... this should work now.

**Comment by glenninn** [comment]
@sebhildebrandt  Hi - Sorry, I'm in the midst of a release cycle and so I've been unable to play more with si... will look into this next week

**Comment by sebhildebrandt** [comment]
@glenninn did you had time to test the latest versions ... should fix the problem. Thank you for any update here.

**Comment by sebhildebrandt** [comment]
@glenninn ... closing it for now. If you still have problems, please let me know.
