### ISSUE TITLE
BSSID could be returned by wifiConnections in Monterey, if `sudo` is used.

### ISSUE THREAD

**Issue by k-funk** [sebhildebrandt/systeminformation#676]
## Problem 
As you know, Monterey doesn't return the BSSID from `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I` anymore. However, if it is called with `sudo`, the BSSID is returned.

## Solution
Call `sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I`. Perhaps an argument can be passed to `si.wifiConnections(() => {...}, { sudo: true })`

## Alternatives
I replaced systeminformation with my own `exec()` of the above command

## Considerations
This does pose a problem of needing to input a password to run this command, but there is a workaround to that:
1. Edit sodoers file: `$ sudo visudo`
2. Paste `{YOUR_UNIX_USERNAME} ALL = NOPASSWD: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport` with `{YOUR_UNIX_USERNAME}` replaced with your username.

**Comment by sebhildebrandt** [comment]
Hi @k-funk 

Thank you for your contribution. Yes, you are right! Calling it with `sudo` will bring back the BSSID (for macOS Monterey) but as you mentioned this will also require entering of the sudo password. As we cannot assume that all applications and scenarios where systeminformation is used are able to do this extra step as mentioned in your comment, I do think that this is a good idea to add this in the code base. If I find a way where no additional steps are required, then I will for sure make a fix for that.
