### ISSUE TITLE
[MacOS] Battery Informations are partial

### ISSUE THREAD

**Issue by anthonybriand** [sebhildebrandt/systeminformation#679]
Hello,
I use this package to recover some information on my mac, however I notice a problem on my Macbook Pro 16"

The data returned by the battery API is invalid

System :
```
Hardware : Macbook Pro 16"
OS : MacOS 12.1
```

Current data provided by SI :
```
{
  "hasBattery":false,
  "cycleCount":132,
  "isCharging":false,
  "designedCapacity":110350,
  "maxCapacity":94042,
  "currentCapacity":0,
  "voltage":12.554,
  "capacityUnit":"mWh",
  "percent":0,
  "timeRemaining":null,
  "acConnected":true,
  "type":"",
  "model":"",
  "manufacturer":"Apple",
  "serial":""
}
```
In this sample it indicates that the battery is at 0 percent however the battery is fully charged, the hasBattery field is also incorrect

If you need more information I can provide you them

**Comment by sebhildebrandt** [comment]
@anthonybriand I have an idea where the problem might be, can you provide the output of (command line):

```
ioreg -n AppleSmartBattery -r | egrep "CycleCount|IsCharging|DesignCapacity|MaxCapacity|CurrentCapacity|BatterySerialNumber|TimeRemaining|Voltage"; pmset -g batt | grep %
```

**Comment by sebhildebrandt** [comment]
@anthonybriand ... can you test the latest version 5.11.13 ... should work now.

**Comment by anthonybriand** [comment]
@sebhildebrandt It works perfectly with the 5.11.13, thank you for the quick fix !
