### ISSUE TITLE
CPU Temperature not working

### ISSUE THREAD

**Issue by BreakTruth** [sebhildebrandt/systeminformation#68]
For whatever reason, the CPU temperature won't show even tho my CPU (AMD FX-4300) does support this, and checked with other programs and they do show it.

**Comment by sebhildebrandt** [comment]
Hi, I guess you are running Windows on your machine, right?
If yes, can you try the following things:

1. please run `wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CriticalTripPoint,CurrentTemperature /value` in your console and post the results here.
2. please also try to run it under admin privileges.
3. did you tried to run your node.js code under admin privileges? If not, please try this.

Thank you in advance.

**Comment by BreakTruth** [comment]
there comes an error saying `not supported`

**Comment by sebhildebrandt** [comment]
OK, this means with wmic I am not able to get the temperature. Not sure how the other apps are getting the temperature. Please give me some time to find a solution for that. Probably I will ask you to test specific code snippets (as I do not have an AMD FX-4300 here).

**Comment by BreakTruth** [comment]
Ok, thanks for going out of your way to help me. :)

**Comment by ItsEcholot** [comment]
AMD temperature sensors are generally speaking a very finicky thing... The tools used by @BreakTruth most definitely call some native ASM commands to get the desired values. 

There are projects like [Open Hardware Monitor](https://github.com/openhardwaremonitor/openhardwaremonitor) that try to provide a library which enables getting these values on multiple platforms and from multiple vendors but are not really well maintained and a hassle to get working. Plus this would also add platform dependent native code, which would be quite ugly for this project.

**Comment by BreakTruth** [comment]
The program that I am using right now to monitor stuff is IOBit SystemCare

**Comment by sebhildebrandt** [comment]
Did not yet found a solution to get temperature on Windows / AMD FX-4300!

As I do not want to add platform specific native code, and as already written, Windows WMI also has problems to retrieve temp, I will close this for now.

But I have it on my list. So as soon I find a solution for that I will publish a solution for that. In the meantime, if anyone has ideas for that, suggestions are very welcome. 

Hope that is OK for you.
