### ISSUE TITLE
si.cpuTemperature() uses inaccurate source on Windows

### ISSUE THREAD

**Issue by jakubiakdev** [sebhildebrandt/systeminformation#682]
**Describe the bug**
cpuTemperature() uses MSAcpi_ThermalZoneTemperature[[1]](https://github.com/sebhildebrandt/systeminformation/blob/69987c5c60ae35ca90e77ff106e1238e26229129/lib/cpu.js#L1212). MSAcpi_ThermalZoneTemperature returns a value of a thermal zone on the motherboard, instead of a temperature of CPU[[2]](https://stackoverflow.com/questions/9101295/msacpi-thermalzonetemperature-class-not-showing-actual-temperature) providing inaccurate results.

**To Reproduce**
1. used function `si.cpuTemperature()`
2. code snippet `si.cpuTemperature().then(data => console.log(data));`
3. start app / code
4. See output/error '....'

**Current Output**
`{ main: 16.8, cores: [ 16.8 ], max: 16.8, socket: [], chipset: null }`

**Expected behavior**
Using HWiNFO I can see that my processor is currently at 54*C, instead of 16. I'm also skeptical of that data source as the output is bellow the ambient temperature

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.14
 - OS: Windows 10 Pro 21H1 19043.1645
 - Hardware: GIGABYTE B450M DS3H, with a Ryzen 5 3600

**Additional context**

**Comment by omarabdelaz1z** [comment]
How did you managed to get some output from `si.cpuTemperature()`?

![image](https://user-images.githubusercontent.com/59033999/165553843-202afe6c-aa00-4ada-ada6-78e19b3540ba.png)

**Comment by wojo1086** [comment]
I have this same issue, except mine is always saying 27.8.

**Comment by ercksen** [comment]
Same problem here:

![image](https://user-images.githubusercontent.com/42444913/168847045-7ca29621-6641-436f-be59-8e484c2a9d73.png)

It would be nice to be able to choose from a list of detected temperature sources.

**Comment by sebhildebrandt** [comment]
Hi @jakubiakdev @wojo1086  @ercksen... as windows Dows not provide any other method than `MSAcpi_ThermalZoneTemperature ` which in some implementations return correct CPU temps (and other not or even nothing), I currently cannot provide more. Otherwise it would be needed to create hardware specific low level code.
