### ISSUE TITLE
Missing property in AudioData interface

### ISSUE THREAD

**Issue by WeijianL1** [sebhildebrandt/systeminformation#685]
https://github.com/sebhildebrandt/systeminformation/blob/69987c5c60ae35ca90e77ff106e1238e26229129/lib/index.d.ts#L872

The `type` property is missing from AudioData interface, as specified here https://github.com/sebhildebrandt/systeminformation/blob/69987c5c60ae35ca90e77ff106e1238e26229129/lib/audio.js#L120

**Comment by sebhildebrandt** [comment]
@WeijianL1 thank you .... should be fixed now. Version 5.11.15 just published
