### ISSUE TITLE
Audio device.type returns empty on Windows

### ISSUE THREAD

**Issue by WeijianL1** [sebhildebrandt/systeminformation#686]
**Describe the bug**
When trying to get the audio device `type` on Windows, it's empty. 

**To Reproduce**
1. On a Windows machine, run the following snippet:
```
const si = require('systeminformation');

// promises style - new since version 3
si.audio()
  .then(data => data.forEach(device => {
  	console.log('---------------------')
  	console.log("DeviceName:", device.name);
  	console.log("DeviceType:", device.type);
  }))
  .catch(error => console.error(error));
```

**Current Output**
```
---------------------
DeviceName: Intel® Smart Sound Technology (Intel® SST)
DeviceType:
---------------------
DeviceName: Intel(R) Display Audio
DeviceType:
---------------------
DeviceName: Realtek High Definition Audio
DeviceType:
---------------------
DeviceName: Intel® Smart Sound Technology (Intel® SST)
DeviceType:
```

**Expected behavior**
Something similar to the output on Mac:
```
---------------------
DeviceName: External Microphone
DeviceType: Phone
---------------------
DeviceName: External Headphones
DeviceType: Phone
---------------------
DeviceName: MacBook Pro Microphone
DeviceType: Phone
---------------------
DeviceName: MacBook Pro Speakers
DeviceType: Speaker
```

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: Windows 10.0.19042
 - Hardware Thinkpad

**Additional context**

**Comment by WeijianL1** [comment]
Ok after reading the implementation I know this is not a bug but more of a feature. It basically uses keywords to match the device name to get a device type. And if no keyword is matched, it goes ahead and check if this device has an audiooutput/input and go from there. Finally if no input/output info is available it will return an empty string. 

My question is: are you aware of any way to tell device type (Speaker VS Headset) without using a keyword-matching approach? I know the [un4seen's bass library ](http://www.un4seen.com/doc/#bass/BASS_DEVICEINFO.html) can return device type but it's not open sourced. Do you know how they are getting the info?

**Comment by sebhildebrandt** [comment]
@WeijianL1 can you provide the full output of 

```
Get-WmiObject Win32_SoundDevice | fl *
```

from this specific windows machine (you need to run this inside PowerShell) ...

Thank you in advance
