### ISSUE TITLE
More GPU data!

### ISSUE THREAD

**Issue by Chinafreak** [sebhildebrandt/systeminformation#69]
It would be nice to get more data from GPU such like temperature (°C), Core Clock (MHz), Memory Clock (MHz) and/or Fan Speed (%)!

**Comment by sebhildebrandt** [comment]
Hi,

I will have a look on it. As fas as I see, gathering information about GPUs is highly dependent on what GPU you are using (at least on Linux). Need to go deeper investigating this feature request.

**Comment by ItsEcholot** [comment]
I would agree with @sebhildebrandt's argument. Getting these details is highly dependent on which driver is being used and the exposed methods this driver offers. Especially if we look beyond windows it seems like a way to difficult task to support every and each of the available drivers out there.

**Comment by Chinafreak** [comment]
If it's too hard, maybe you can use GPU-Z to get more information? I'm pretty sure that mac/linux does have this similar software too. You can run GPU-Z in console.

Also another more data idea: check if the GPU use 32-bit or 64-bit addressing.

**Comment by ItsEcholot** [comment]
@Chinafreak That would introduce a dependency, which @sebhildebrandt wants to prevent. GPU-Z is not open source as far as I know and thus there would most probably be issues with the licence used in this project and keeping it the same.

**Comment by sebhildebrandt** [comment]
Hi again. I didn't yet found a way to retrieve this information consistently throughout all supported operating systems without getting a whole bunch of dependencies. I will close this for now but keep it on my list. Hope that is OK for you.

**Comment by Chinafreak** [comment]
OK. Thank you :)

**Comment by renambot-uic** [comment]
For Nvidia gpus on Linux, it would be nice to extract informations from the nvidia directory /proc/driver/nvidia/gpus Lots of information there in text form.
Otherwise using the 'nvidia-smi' command:
List gpus: nvidia-smi -L
Detailed info: nvidia-smi -q

thanks for this package!
