### ISSUE TITLE
Trying to calculate the diagonal screen size of monitor.

### ISSUE THREAD

**Issue by aminmousavi5147** [sebhildebrandt/systeminformation#691]
I'm trying to calculate the diagonal screen size of monitor (eg. 17.3, 15.6, ...) with the value of 'sizeX' and here is my code : 
```
function gcd(a, b) {
    return (b == 0) ? a : gcd(b, a % b);
}
function calculateDiagonal(width) {
    let screenWidth = screen.width;
    let screenHeight = screen.height;
    let greatestCommonDivisor = gcd(screenWidth, screenHeight);
    let aspectRatioWidth = screenWidth / greatestCommonDivisor;
    let aspectRatioHeight = screenHeight / greatestCommonDivisor;
    var aspectRatioDiagonal = Math.sqrt(Math.pow(aspectRatioWidth, 2) + Math.pow(aspectRatioHeight, 2));
    if (width > 0) {
        var factor = width / aspectRatioWidth;
        var diagonal = aspectRatioDiagonal * factor;
        return diagonal / 2.54;
    }
}
```
And how I use it : 
`Math.round(calculateDiagonal(chdValue.sizeX) * 10) / 10 + ' in'`
The diagonal screen size of my laptop (ASUS ROG G75VW) is 17.3 inches and what my code returns is 17.2 and it's because of the sizeX value that I get!

**Comment by sebhildebrandt** [comment]
@aminmousavi5147 Can you provide the full output of the `si.graphics()`? Maybe I can see then some room for improvement. Thank you in advance.
