### ISSUE TITLE
wifiConnections method not working on Pop OS 22.04

### ISSUE THREAD

**Issue by HadiModarres** [sebhildebrandt/systeminformation#694]
**Describe the bug**
Does not return information about currently active Wifi connection.

**To Reproduce**
invoke `wifiConnections` method on freshly installed Pop OS 22.04

**Current Output**
Empty array: []

**Expected behavior**
Should return info about active Wifi connection

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.16
 - OS: Pop OS 22.04

**Additional context**
It seems that systeminformation is using `iw` command to acquire info about network interfaces, but this package doesn't seem to be installed by default on Pop OS 22.04, and should be installed first.

**Comment by sebhildebrandt** [comment]
@HadiModarres do you know if there is any other lib installed on Pop OS by default with wich we can determine Wifi connections?

**Comment by sebhildebrandt** [comment]
@HadiModarres ... actually I see now the same in one of my ubuntu 22.04 installations. Working on a fix ...

can you confirm that `nmcli` is installed by default in Pop OS?

**Comment by sebhildebrandt** [comment]
@HadiModarres ... can you try the latest version 5.12.11 ... here I made an alternative in case that `iw` is missing. At least here on my Ubuntu 22 it works fine.

**Comment by HadiModarres** [comment]
@sebhildebrandt Sure mate, thanks! will give that a try tonight. Sorry I didnt get back to you earlier, I was swamped.

**Comment by HadiModarres** [comment]
@sebhildebrandt I just removed iw and gave v5.12.11 a try and it works great! Can confirm nmcli is shipped by default on POP. Would be great if we could have a list of external tools used on each platform inside systeminformation, so I could check them in my app and inform the user to install them if they were missing. 
Thanks
