### ISSUE TITLE
fsSize filters out mounted RAID drive

### ISSUE THREAD

**Issue by MauriceNino** [sebhildebrandt/systeminformation#697]
**Describe the bug**
A user on my repo has a bug where his drive is not recognized (MauriceNino/dashdot#40). His output of `df -kPT` is:

```
Filesystem           Type       1024-blocks    Used Available Capacity Mounted on
overlay              overlay    102626232  19481216  77885752  20% /
tmpfs                tmpfs          65536         0     65536   0% /dev
shm                  tmpfs          65536         0     65536   0% /dev/shm
/dev/mapper/ubuntu--vg-ubuntu--lv              ext4       102626232  19481216  77885752  20% /etc/os-release
data-pool            zfs        3771705088 1642311552 2129393536  44% /mnt/host_data
/dev/mapper/ubuntu--vg-ubuntu--lv              ext4       102626232  19481216  77885752  20% /etc/resolv.conf
/dev/mapper/ubuntu--vg-ubuntu--lv              ext4       102626232  19481216  77885752  20% /etc/hostname
/dev/mapper/ubuntu--vg-ubuntu--lv              ext4       102626232  19481216  77885752  20% /etc/hosts
```

This is happening, because it is not the root drive and its name is not starting with a slash, like needed to pass this filter:
https://github.com/sebhildebrandt/systeminformation/blob/445dcfa60fd75c7f980626ba32a8e1cc5a0406c3/lib/filesystem.js#L57

**Current Output**
```js
[ { fs: 'overlay',
    type: 'overlay',
    size: 105089261568,
    used: 19948765184,
    available: 79755010048,
    use: 20.01,
    mount: '/' },
  { fs: '/dev/mapper/ubuntu--vg-ubuntu--lv',
    type: 'ext4',
    size: 105089261568,
    used: 19948765184,
    available: 79755010048,
    use: 20.01,
    mount: '/etc/os-release' } ]
```

**Expected behavior**
That `data-pool` should be included in the output.

Is there any reason, why the fs needs to start with a `/`? Wouldn't it be enough to just filter out any fs types that are not valid (e.g. `tempfs`)?

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.20

**Additional context**
I am opening this issue for @MrAlucardDante

**Comment by sebhildebrandt** [comment]
Hi @MauriceNino ... need to go deeper into this one ... I need to make sure to make this filtering correct without any other side effects. There are several FS `type` that needed to filter out and nit just `tmpfs`. Will try to come up with a solid solution after the weekend (as I am on holiday right now).

**Comment by sebhildebrandt** [comment]
@MauriceNino I just published a new version, hoping this would not introduce other unwanted side effects. Can you test this on your side? Version 5.11.21 just published

**Comment by MauriceNino** [comment]
Hi, thanks for the update! I have tested it with a few computers and could not recognize any errors or inconsistencies. The problem for the user on my project seems to be fixed with this as well. @sebhildebrandt

**Comment by sebhildebrandt** [comment]
@MauriceNino great, thank you for all your tests! Closing it for now.
