### ISSUE TITLE
si.system() and si.bios() returns empty string for every key

### ISSUE THREAD

**Issue by ym13349140** [sebhildebrandt/systeminformation#699]
**Describe the bug**
dear @sebhildebrandt , I'm using systeminformation in my vue application. When I run my web application on different windows10 machines(all these machines are the same), most machines get system information successfully, but there is one machine that cannot get any system information. I ran other functions on this machine, and the value of some keys are also empty string. the response of are as follows.

**Current Output**
If applicable, add output to help explain your problem.
```
si.system() =======  {
  manufacturer: '',
  model: '',
  version: '',
  serial: '',
  uuid: '',
  sku: '',
  virtual: false
}

si.bios() ======= { 
    vendor: '', 
    version: '', 
    releaseDate: '',
     revision: '', 
    serial: '' 
}

si.mem() ======= {
  total: 17006747648,
  free: 9987194880,
  used: 7019552768,
  active: 7019552768,
  available: 9987194880,
  buffers: 0,
  cached: 0,
  slab: 0,
  buffcache: 0,
  swaptotal: 0,
  swapused: 0,
  swapfree: 0
}

si.uuid() ======= {
  os: '36e3e7e8-82d6-4912-8be9-f4af85b8719b',
  hardware: '',
  macs: [ '6c:4b:90:fd:16:39' ]
}
```

**Expected behavior**
On other machines, all the result are not empty. so can you help me to figure out what the problem is?

**Environment (please complete the following information):**
 - systeminformation package version:  5.11.16
 - OS: Windows 10
 - Hardware: Lenovo

**Comment by sebhildebrandt** [comment]
@ym13349140 can you ran e.g the following command (Powershell) on the machines you are targeting (and under the user which you where running the node code) ... if the output is different, then we might have an indication why we habe this problem:

```
Get-WmiObject Win32_ComputerSystemProduct | select Name,Vendor,Version,IdentifyingNumber,UUID | fl
Get-WmiObject MS_Systeminformation -Namespace "root/wmi" | select systemsku | fl
Get-WmiObject Win32_bios | select Version, SerialNumber, SMBIOSBIOSVersion
```

**Comment by ym13349140** [comment]
> @ym13349140 can you ran e.g the following command (Powershell) on the machines you are targeting (and under the user which you where running the node code) ... if the output is different, then we might have an indication why we have this problem:
> 
> ```
> Get-WmiObject Win32_ComputerSystemProduct | select Name,Vendor,Version,IdentifyingNumber,UUID | fl
> Get-WmiObject MS_Systeminformation -Namespace "root/wmi" | select systemsku | fl
> Get-WmiObject Win32_bios | select Version, SerialNumber, SMBIOSBIOSVersion
> ```
> 
> Thank you in advance

Thanks for your  reply, I just tried these command on that target machine, all the system informations are normally returned as follows:
 
![BCD86F496AB44C0951366211C4834E873244925673_IMAGE](https://user-images.githubusercontent.com/17507937/174250744-f4af0511-a8c7-42e4-ba04-1975b7920277.png)

**Comment by sebhildebrandt** [comment]
@ym13349140 as the output of the underlying commands are the same I do not see any reason on our side why this can be. We need to go deeper in to that: 

- do the users have the exact same rights (this is where I would see the problem)
- node version ist the same?
- systeminformation version is the same?
- PowerShell version is the same?

Additionally to that, you could add some `console.log` statements right after calling the upper statements e.g. in file `system.js` right after line 349 (so after `let lines = stdout.split('\r\n');`) 

```
console.log(`lines`)
```

If we get NO console.log or get empty strings, then it is most likely that this is up to the user you are running the node command. Please also be sure to run this on all target machines to see if we have any difference.

**Comment by sebhildebrandt** [comment]
@ym13349140 did you had time to go through the steps I proposed?

**Comment by sebhildebrandt** [comment]
@ym13349140 closing it for now as I do not see anything on my side that I can do. If you provide the information I asked for we can work on it further ...
