### ISSUE TITLE
networkStats rx_sec, tx_sec always at -1 & fsStats rx_sec, wx_sec always at 0

### ISSUE THREAD

**Issue by Buzut** [sebhildebrandt/systeminformation#7]
Hey, thanks for your great module! 

I tried on two different Ubuntu 16.04 machines, with both node 4.4.5 and 6.2.1. 
The realtime metrics for networkStats and fsStats don't seem to work.

Exemple output:

    …
    networkStats: 
     { iface: 'eth0',
       operstate: 'unknown',
       rx: 0,
       tx: 0,
       rx_sec: -1,
       tx_sec: -1 },
    …
    fsStats: { rx: 455069696, wx: 4253657088, rx_sec: 0, wx_sec: 0 },
    …

**Comment by sebhildebrandt** [comment]
Hi, 

the first time you call this function, you will get this results (am I right, you just called this function just once?). 
The second time, you should then get statistics based on the time between the two times … 

Please give me a short feedback, if that worked on your machines.

regards
Sebastian

**Comment by Buzut** [comment]
Hi!

Indeed, I did call it once only. Though I found it quite unusual to have to manually call it twice.

Best,
