### ISSUE TITLE
Raspberry Pi 3 returns defaults for si.system()

### ISSUE THREAD

**Issue by cfrede001** [sebhildebrandt/systeminformation#70]
Response:
{ manufacturer: '',
  model: 'Computer',
  version: '',
  serial: '-',
  uuid: '-' }

**Comment by sebhildebrandt** [comment]
Hi, can you please provide which linux distribution you are using?

And two more thing: can you post the output of 

`dmidecode -t system`

and 

`cat /proc/cpuinfo`

Thank you so much.

**Comment by cfrede001** [comment]
Raspbian Stretch https://www.raspberrypi.org/downloads/raspbian/

Looking at the code it appears to be a logic handling issue because if I execute the underlying grep commands they work:
grep Hardware /proc/cpuinfo; grep Serial /proc/cpuinfo; grep Revision /proc/cpuinfo
Hardware    : BCM2835
Serial        : 0000000019fa485e
Revision    : a22082

dmidecode -t system - I'll update comment after I get it back online in a bit.

**Comment by sebhildebrandt** [comment]
One problem here is, that I need to update model and revision values for Pi 3 and Pi Zero. Right now working on it. Result of `dmidecode -t system` will anyway help. Will then provide an update in one or two days.

**Comment by cfrede001** [comment]
Thanks for the update and it is a very helpful library!

**Comment by sebhildebrandt** [comment]
Just published a fix for that. Can you please verify, if it returns now correct values?

**Comment by rgstephens** [comment]
I'm having this issue on a Raspberry Pi Zero W with version `3.40.1`.

**dmidecode -t system** output:

```
# No SMBIOS nor DMI entry point found, sorry.
```

**cat /proc/cpuinfo** output:

```
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 997.08
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 0000000076f48021
```

**Comment by sebhildebrandt** [comment]
Will have a look on it today.

**Comment by rgstephens** [comment]
Not sure why I'm getting the error with `dmidecode -t system` on the Raspberry Pi but after looking at your source, I'm sure that's where it's failing.  Same issue with `dmidecode` on several Pi Zero W's.

I'm calling `exec` myself on cpuproc for the time being.

**Comment by sebhildebrandt** [comment]
Also `si.cpuFlags()` should now return proper results.

**Comment by rgstephens** [comment]
`si.system` now does not return at all and the `catch` does not fire.  I've posted my test program and the output of the program from a Mac and a Pi Zero W at [rgstephens/sitest](https://github.com/rgstephens/sitest). Look in the **TestRuns** subdirectory for the full output from the Mac & Pi Zero W.

`si.cpuFlags` is a null string for the Pi Zero W.

**Comment by sebhildebrandt** [comment]
Just published a quick fox on both issues (version 3.41.2). I guess I found the two problems. Sorry! Hope that this is fixed now ... can you test it once again? Thank you in advance!!

**Comment by sebhildebrandt** [comment]
Sorry for the inconvenience. Will check it again!

**Comment by rgstephens** [comment]
Here's the output of `cat /proc/cpuinfo` on a Pi Zero W

```
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 9000c1
Serial          : 0000000076f48021
```
