### ISSUE TITLE
Missing package "osx-temperature-sensor"

### ISSUE THREAD

**Issue by kamilernerd** [sebhildebrandt/systeminformation#701]
**Describe the bug**
Missing package "osx-temperature-sensor", when I install this package the warning persist.

**To Reproduce**
1. used function 'cpu()'
2. code snippet 'const cpu = await si.cpu();'
3. start app / code
4. See error 'Module not found: Error Can't resolve 'osx-temperature-sensor' in...'

**Current Output**
`Module not found: Error Can't resolve 'osx-temperature-sensor' in node_modules`

**Expected behavior**
My expectation was to get information about the CPU excluding the temperatures according to this [Known issues](https://www.npmjs.com/package/systeminformation#user-content-known-issues). I need to call `cpuTemperature()` in order to read the temperature which is redundant in my case.

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.21
 - OS: MacOs
 - Hardware: MacBook Pro 13

**Additional context**
Application is built using electron with react and typescript, systeminformation is called from the "node/main" process as a callback in a ipcMain event.

**Comment by Bartel-C8** [comment]
Thanks on the hint on the `alias` webpack (4.x.x) configuration.

But I got a warning on it: 
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
   - configuration.resolve.alias['osx-temperature-sensor'] should be a string.
 ```

So I solved by adding the webpack (4 style, note the API changed from 4 to 5) IgnorePlugin

`new webpack.IgnorePlugin(/osx-temperature-sensor/)`

**Comment by r34son** [comment]
For anyone getting error in nextjs use following in next.config.js:
```ts
  webpack: (config, { webpack }) => {
    config.plugins.push(
      new webpack.IgnorePlugin({ resourceRegExp: /osx-temperature-sensor/ }),
    );
    return config;
  },
```
