### ISSUE TITLE
si.fsStats() returns null

### ISSUE THREAD

**Issue by TrygveDev** [sebhildebrandt/systeminformation#703]
In my code I use:
```
    si.fsStats()
        .then(data => {
            console.log(data)
        })
```
The call returns null and I do not know why. Other calls work just fine.
I am running systeminformation v5.11.14 in a v18.2.0 electron project.

**Comment by sebhildebrandt** [comment]
@TrygveDev please refer to the documentation:

https://systeminformation.io/filesystem.html

If `fsStats()` returns null then it is most likely that this is currently not supported for your OS (currently it is only implemented for linux and macOS). Moreover you should call this in an interval to get correct stats value (see also https://systeminformation.io/statsfunctions.html)

**Comment by TrygveDev** [comment]
Thank you. Read the documentation but did not notice that windows is not supported.
