### ISSUE TITLE
BIOS Information on MAC

### ISSUE THREAD

**Issue by Saahilp18** [sebhildebrandt/systeminformation#704]
Hello,

I was wondering why we are not able to retrieve the information for "Bios Revision" and "Revision Date" for MAC users and if there would be a way to get that information.

Thank you.

**Comment by Saahilp18** [comment]
> @sebhildebrandt Hi, the only way I think I can get this information would be to boot up the MacBook into the bios mode by holding crtl+option+'o'+'f' before the system boots up. I'm not sure if that's helpful but Ill keep looking.

If you type system_profiler in the terminal the firmware version is shown which is the same thing I'm fairly sure.

**Comment by sebhildebrandt** [comment]
@Saahilp18 this is what I am actually doing and I return this back as a version. Here on my machine `system_profiler` returns

```
System Firmware Version: 7459.101.3
```

and i Systeminformation I return:

```
{
  vendor: 'Apple Inc.',
  version: '7459.101.3',
  releaseDate: '',
  revision: ''
}
```

But I do not see any further information that I could give back.

**Comment by Saahilp18** [comment]
Ahh, I see thank you. I was also looking to get the revision & revision date. Is that not a thing on Mac, or do you think it is still possible to get? I can't find anything online.

**Comment by Saahilp18** [comment]
I see, thank you for your help :)

**Comment by sebhildebrandt** [comment]
@Saahilp18 @BitesPotatoBacks closing this for now as we agreed that there is no more data we can get for macOS regarding BIOS.
