### ISSUE TITLE
.fsSize() failing since 5.11.21 if df outputs some errors

### ISSUE THREAD

**Issue by BobbyWibowo** [sebhildebrandt/systeminformation#705]
**To Reproduce**
```js
require('systeminformation').fsSize().then(console.log)
```

**Current Output**
```js
[]
```

**Expected behavior**
The following is output of version `5.11.20`
```js
[
  {
    fs: '/dev/sda2',
    type: 'ext4',
    size: 701440122880,
    used: 368236384256,
    available: 297501302784,
    use: 55.31,
    mount: '/'
  },
  ...
]
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.21
 - OS: linux x64, ubuntu 20.04

**Additional context**
The issue happens because my `df` outputs some errors
```
$ df -lkPTx squashfs
df: /tmp/.mount_appima2ErdiS: Transport endpoint is not connected
df: /run/user/1000/doc: Operation not permitted
Filesystem            Type     1024-blocks       Used Available Capacity Mounted on
udev                  devtmpfs    16318916          0  16318916       0% /dev
tmpfs                 tmpfs        3275716       3680   3272036       1% /run
/dev/sda2             ext4       685000120  359641512 290492948      56% /
tmpfs                 tmpfs       16378564      73748  16304816       1% /dev/shm
tmpfs                 tmpfs           5120          4      5116       1% /run/lock
tmpfs                 tmpfs       16378564          0  16378564       0% /sys/fs/cgroup
/dev/sda1             vfat          523248      38812    484436       8% /boot/efi
/dev/sdc2             fuseblk    976744444  780706436 196038008      80% /mnt/data
/dev/sdb2             fuseblk   1743797244 1654112960  89684284      95% /mnt/firecuda
/dev/mapper/_dev_sdb1 ext4       205373416      61456 196022208       1% /mnt/luks
/home/bobby/.Private  ecryptfs   685000120  359641512 290492948      56% /home/bobby
tmpfs                 tmpfs        3275712         36   3275676       1% /run/user/1000
```
The transport endpoint thingy seems to be an issue with an AppImage somewhere in my system
While the operation not permitted thingy appears to be a Flatpak bug
All in all, those will probably always be unexpected to the end users, and sometimes beyond their controls

It used to work just fine because the library kinda ignored `df` errors with the previous cmd-line that got commented out
https://github.com/sebhildebrandt/systeminformation/blob/577ce3b8256ab4fbc0b4a54c0188ade65427d03c/lib/filesystem.js#L104
It'd instead only error out if `grep` itself did
I can confirm it works immediately if I do `df ... | grep .` to pipe `df` output through `grep` first, since it will cause the exec to not encounter any errors, AND have 0 exit code
There's probably a more elegant solution, but yeah

**Comment by sebhildebrandt** [comment]
@BobbyWibowo I will try to work a a workaround for that ...

**Comment by sebhildebrandt** [comment]
@BobbyWibowo can you check if the patch I made here on GitHub works for you? Just clone the whole repo and inside just run 

```
npm run test
```

Then press `f` and have a look at the results.

Thank you for your feedback on that one.

**Comment by BobbyWibowo** [comment]
@sebhildebrandt Sorry for the delay, been away from the internet in the past couple days

I can confirm latest commit of master branch has nearly identical fs output with version 5.11.20, in the same machine that has a few errors when running df

**Comment by sebhildebrandt** [comment]
@BobbyWibowo Thank you ... you said "nearly" ... can you provide bot systeminformation outputs from version 5.11.20 as well as from the lates version of this master branch?

**Comment by BobbyWibowo** [comment]
@sebhildebrandt Hi there, the only difference between master branch and v5.11.20 is that the following entry is shown on master branch:
```js
[
  ...omitted,
  {
    fs: 'appimaged-711-x86_64.AppImage',
    type: 'fuse.appimaged-711-x86_64.AppImage',
    size: 5242880,
    used: 5242880,
    available: 0,
    use: 100,
    mount: '/tmp/.mount_appimaiicdjG'
  }
]
```
Representative of the following line in `df -lkPTx squashfs`:
```
Filesystem                    Type                               1024-blocks       Used Available Capacity Mounted on
...omitted
appimaged-711-x86_64.AppImage fuse.appimaged-711-x86_64.AppImage        5120       5120         0     100% /tmp/.mount_appimaiicdjG
```

From what I can tell, that behavior is very specific to https://github.com/probonopd/go-appimage instead of all AppImage(s) in general
So I wasn't certain if it should still be within this issue's scope or something else

Aside from that alone, the other entries are identical

**Comment by sebhildebrandt** [comment]
@BobbyWibowo ok, I made one more change here on GitHub. If possible, can you once again pull from the paster branch and rerun the test? Now it should be exactly the same as in v 5.11.20... if yes, I will release this as a new version.

**Comment by BobbyWibowo** [comment]
@sebhildebrandt I can confirm outputs for both latest master commit and v5.11.20 are absolutely identical now :heart:

**Comment by sebhildebrandt** [comment]
@BobbyWibowo Perfect ... currently working also on one other issue and need to get one more feedback. As soon as I have this I will release the new version. THANK YOU for your support on this issue!

**Comment by sebhildebrandt** [comment]
@BobbyWibowo now it should work. Version 5.11.23 just published.
