### ISSUE TITLE
memory max capacity in board

### ISSUE THREAD

**Issue by MosqueraSt3** [sebhildebrandt/systeminformation#709]
**Describe the bug**
System information said that returns memory max capacity in bytes but the command that they are using return the value in kilobytes.

That depends in the SO version.

Microsoft Doc -> https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-physicalmemoryarray

**To Reproduce**
Just call baseboard function.
memMax property

**Current Output**
memory max capacity in kilobytes.

**Expected behavior**
memory max capacity in bytes.

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.22
 - OS: Windows 10 Pro
 - Hardware HP Pavilion Gaming Laptop I5 8th

**Comment by sebhildebrandt** [comment]
@MosqueraSt3 can you provide the full output (from PowerShell) of 

```
Get-WmiObject Win32_physicalmemoryarray | select MaxCapacity, MaxCapacityEx, MemoryDevices | fl
```

The docs state that `MaxCapacity` should return Bytes and `MaxCapacityEx` kBytes ... just want to be sure about the results. Can you also provide the exact HP Pavilion Model Number that I can check what the max capacity should be?

**Comment by MosqueraSt3** [comment]
HP Pavilion Gaming Laptop 15-Cx0xxx
Both properties returns the same value 
![image](https://user-images.githubusercontent.com/61483209/178013479-4e303b3f-5caf-4be4-b316-ff70028c82db.png)

**Comment by kacesensitive** [comment]
@sebhildebrandt 
The docs state
MaxCapacity
> Windows Server 2012 R2, Windows 8.1, Windows Server 2012, Windows 8, Windows Server 2008 R2, Windows 7, Windows Server 2008 and Windows Vista: Maximum memory size (in bytes) installable for this particular memory array. If the size is unknown, the property is given a value of 0 (zero).

I believe this means `MaxCapacity` only represents bytes on those Windows versions above. Otherwise it just reports the same value. It's deprecated for newer versions of windows. SI should probably use MaxCapacity when running from one of these older OSs and MaxCapacityEx otherwise.

**Comment by sebhildebrandt** [comment]
@kacesensitive ... you are absolutely right, this is what I am thinking of. Will provide a patch for that later today.

**Comment by sebhildebrandt** [comment]
@kacesensitive @MosqueraSt3 ... I now implemented this a little different, taking the current windows version into consideration. Can you test this on your side (pull from master branch here on GitHub) ? If you now get back correct values, I will release a new version.

**Comment by sebhildebrandt** [comment]
@kacesensitive @MosqueraSt3 after some tests here I guess that this works correctly. Version 5.11.23 just published.

**Comment by MosqueraSt3** [comment]
@sebhildebrandt All ok. Thank you

**Comment by koraniar** [comment]
@sebhildebrandt, I think it is not working yet. I tested the command on all the available Windows devices I had, and the result is always the same for `MaxCapacity` and `MaxCapacityEx`, and also the result is always in Kibibytes.

In my devices, with PR #710 it is working well.

The following is the list of the devices where I tested it:
- Dell Latitude 3410 | Windows 10 Pro
MaxCapacity   : 67108864
MaxCapacityEx : 67108864
MemoryDevices : 2
- HP Laptop 15-bs0xx | Windows 10 Home Single Language
MaxCapacity   : 33554432
MaxCapacityEx : 33554432
MemoryDevices : 2
- Lenovo 10T8S5W400 | Windows 10 Pro
MaxCapacity   : 33554432
MaxCapacityEx : 33554432
MemoryDevices : 2
- HP EliteDesk 800 G4 SFF | Windows 10 Pro
MaxCapacity   : 67108864
MaxCapacityEx : 67108864
MemoryDevices : 4
- Lenovo 10A8A14H00 | Windows 11 Pro
MaxCapacity   : 33554432
MaxCapacityEx : 33554432
MemoryDevices : 4
- VMware7,1 | Windows 10 Pro
MaxCapacity   : 101711872
MaxCapacityEx : 101711872
MemoryDevices : 64
- Lenovo 20149 | Windows 7 Professional
MaxCapacity   : 16777216
MaxCapacityEx : 
MemoryDevices : 2
- Dell Vostro 3405 | Windows 11 Pro
MaxCapacity   : 134217728
MaxCapacityEx : 134217728
MemoryDevices : 2
- Built | Windows 10 Pro
MaxCapacity   : 134217728
MaxCapacityEx : 134217728
MemoryDevices : 2
