### ISSUE TITLE
CPU temperature on Synology DSM 7

### ISSUE THREAD

**Issue by IngmarStein** [sebhildebrandt/systeminformation#711]
**Describe the bug**
Synology NAS with DSM 7 don't have util-linux installed, so there is no `rev` command available. Because of that, `cpuTemperature` produces an error for this command: https://github.com/sebhildebrandt/systeminformation/blob/f7022c92f0abe41b92120d54f7b8fa4f48a918bf/lib/cpu.js#L1042

**To Reproduce**
1. call `cpuTemperature` on a Synology NAS with DSM 7

**Current Output**
None

**Expected behavior**
The `cpuTemperature` produces a result.

**Environment (please complete the following information):**
 - systeminformation package version: 5.11.14
 - OS: Linux DS920 4.4.180+ #42661 SMP Mon Jun 27 15:07:20 CST 2022 x86_64 GNU/Linux synology_geminilake_920+
 - Hardware: Synology DS920+

**Additional context**
The `rev` command could be replaced by `sed` or `awk`, like so:
```
for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=$(echo $label | sed '/\n/!G;s/\(.\)\(.*\n\)/&\2\1/;//D;s/.//' | cut -c 7- | sed '/\n/!G;s/\(.\)\(.*\n\)/&\2\1/;//D;s/.//')_input; if [ -f "$value" ]; then echo $(cat "$label")___$(cat "$value");  fi; fi; done; done;
```
Ideally, the library would check if `sed` or `awk` are available to avoid a similar issue on other systems or do the string processing outside the shell command.

**Comment by sebhildebrandt** [comment]
@IngmarStein to keep it even simpler ... would this work on your Synology?

```
for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=${label%_*}_input; echo $(cat "$label")___$(cat "$value"); fi; done; done;
```

If yes, no `rev`, `sed` or `awk` would be needed ...

**Comment by IngmarStein** [comment]
Oh, nice! The bash version is 4.4.23 and it does work just fine. Here's an example output:
```
Physical id 0___37000
Core 0___39000
Core 1___38000
Core 2___38000
Core 3___38000
```

**Comment by sebhildebrandt** [comment]
@IngmarStein ok, now it should work. Version 5.11.23 just published.

**Comment by IngmarStein** [comment]
Excellent, thank you!
