### ISSUE TITLE
fsSize() will possibly filter out non-temp mounts

### ISSUE THREAD

**Issue by MauriceNino** [sebhildebrandt/systeminformation#712]
**Describe the bug**
In the commit https://github.com/sebhildebrandt/systeminformation/commit/f3b8a4ad367cf2b91c3481481e88987d100d4430 you have added all mount types that start with `fuse.` to the temp mount list, which removes them from the output AFAIK.

One of the therefore blocked types is [mergerfs](https://github.com/trapexit/mergerfs), which is a mount that combines multiple other mounts. I know that some users of my software depend on this mount being present in their `fsSize()` result.

Is there any specific reason for a block of all types that start with `fuse.`?

**Comment by sebhildebrandt** [comment]
@MauriceNino ... I had another issue with `fsSize()`where I had to remove one more file type from the `df` list ... I added here two possible strings where the second one is now responsible for this issue. I removed it now while still leaving the other in place. This should fix this issue and preserve my intension for the other one. Version 5.11.24 just released.

**Comment by MauriceNino** [comment]
Thank you for the quick fix!
