### ISSUE TITLE
macOS: networkInterfaces() always returns operstate = "up" for all interfaces

### ISSUE THREAD

**Issue by Bartel-C8** [sebhildebrandt/systeminformation#719]
On my system:

macOS Monterrey 12.4 (21F79) the call to `networkInterfaces()` always returns "up" for every `operstate`.
I traced it back to `getDarwinNics`, which calls `'/sbin/ifconfig -v'`.

Which (in my case) returns "inactive" for a interface which is down.
`	status: inactive`
And for active interface: 
`	status: active`

The used check for deriving `operstate` is (https://github.com/sebhildebrandt/systeminformation/blob/69987c5c60ae35ca90e77ff106e1238e26229129/lib/network.js#L497)
`.indexOf('active') > -1 ` which of course matches both `active` AND `inactive`.

There are a few possible fixes I guess:
Given `const status = util.getValue(section, 'status').toLowerCase()`
- Change the comparison from `status > -1` to `status > -1 && status < 2` (Because, the string that will be checked will be " active" or " inactive", with a leading space. With the < 2 , the "in"-part always prevents false parsing)
- Change the comparison to explicit checks: `status.includes("active") && !status.includes("inactive")`

The second one I prefer, as it is more explicit what is being checked.
I don't have any idea which older macOS/OSX versions return for the `ifconfig -v` command, but the second case should match the same intended behaviour as it is now?

**Comment by Bartel-C8** [comment]
Actually, the same logic as here should be used for consistency? (The stats call indeeds works for the correct operstate).

https://github.com/sebhildebrandt/systeminformation/blob/master/lib/network.js#L1294

```
            result.operstate = (stdout.toString().split(':')[1] || '').trim();
            result.operstate = (result.operstate || '').toLowerCase();
            result.operstate = (result.operstate === 'active' ? 'up' : (result.operstate === 'inactive' ? 'down' : 'unknown'));
```

**Comment by sebhildebrandt** [comment]
@Bartel-C8 you are right, my fault. Fixed it as proposed. Version 5.12.3 just released

**Comment by Bartel-C8** [comment]
Tested and works great! Thank you for the quick fix + release!
