### ISSUE TITLE
Would you mind adding `yarn` to the versions information?

### ISSUE THREAD

**Issue by adamreisnz** [sebhildebrandt/systeminformation#72]
It would fit well alongside the `npm` and `node` versions.

**Comment by sebhildebrandt** [comment]
Very good idea. Will do it end of the week.

**Comment by sebhildebrandt** [comment]
Just published a new version (3.30.0) with extended `versions()` information (added `yarn`, `gulp`, `grunt`, `tsc`, `git`)

**Comment by adamreisnz** [comment]
Awesome thank you!
