### ISSUE TITLE
[Linux] CPU avg temp incorrect on 2017 Macbook Air

### ISSUE THREAD

**Issue by ExperiBass** [sebhildebrandt/systeminformation#720]
**Describe the bug**
`systeminformation` returns the wrong average temperature for the cpu. Each core is ~70C and the average returned is closer to 36. Oddly, it also returns the correct core temps.

**To Reproduce**
1. Run `node -e "require('systeminformation').cpuTemperature(t => console.log(t))"`
2. Run `sensors | grep "Core"`
3. Compare the output.

**Current Output**
![Oh no! our average! its broken!](https://user-images.githubusercontent.com/33764485/183264702-18d4257a-4883-47e2-b4c9-a7a63a97d7fa.png)

**Expected behavior**
The average is a proper average of the core temps.

**Environment (please complete the following information):**
 - systeminformation package version: `5.12.3`
 - OS: Arch
 - Hardware: 2017 Macbook Air (`MacBookAir7,2 1.0`)

**Additional Information:**
Current workaround is `( (await si.cpuTemperature()).cores.reduce((a, b) => a + b) ) / numCores`

**Comment by sebhildebrandt** [comment]
Hi @ExperiBass thank you for reporting ... can you run these two commands and post the results (as text) here:

```
for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=${label%_*}_input; echo $(cat "$label")___$(cat "$value"); fi; done; done;
```

and 

```
sensors
```

Thank you in advance

**Comment by ExperiBass** [comment]
for loop
```
temp___36100
Package id 0___78000
Core 0___78000
Core 1___78000
```

`sensors`
```
applesmc-isa-0300
Adapter: ISA adapter
Exhaust  :   4101 RPM  (min = 1200 RPM, max = 6500 RPM)
TB0T:         +35.8°C  
TB1T:         +35.8°C  
TB2T:         +32.5°C  
TBXT:         +35.8°C  
TC0E:         +77.8°C  
TC0F:         +79.2°C  
TC0P:         +63.8°C  
TC1C:         +75.0°C  
TC2C:         +77.0°C  
TCGC:         +74.0°C  
TCHP:         +49.5°C  
TCMX:         +77.2°C  
TCSA:         +73.0°C  
TCXC:         +77.2°C  
TH0A:         +49.8°C  
TH0B:         +49.5°C  
TH0C:         +49.5°C  
TH0F:         -35.5°C  
TH0R:         -35.5°C  
TH0V:         +58.5°C  
TH0a:         +49.8°C  
TH0b:         +49.5°C  
TH0c:         +49.5°C  
THSP:         +45.2°C  
TM0P:         +53.8°C  
TPCD:         +72.0°C  
TS2P:         +54.8°C  
TW0P:         +46.5°C  
Ta0P:         +48.0°C  
Th1H:         +42.2°C  
Tm0P:         +45.8°C  
Ts0P:         +33.8°C  
Ts0S:         +42.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:           8.41 V  
temp:         +36.1°C  
curr1:         0.00 A  (avg =  +0.00 A)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +77.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +74.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +77.0°C  (high = +105.0°C, crit = +105.0°C)

pch_wildcat_point-virtual-0
Adapter: Virtual device
temp1:        +73.0°C  

BAT0-virtual-0
Adapter: Virtual device
temp1:        +36.1°C
```

**Comment by sebhildebrandt** [comment]
@ExperiBass perfect, thank you. Will have a look at it tomorrow morning.

**Comment by sebhildebrandt** [comment]
@ExperiBass  should work now. Version 5.12.4 just released

**Comment by ExperiBass** [comment]
Works, thanks!
