### ISSUE TITLE
Process command is truncated on Windows

### ISSUE THREAD

**Issue by jonas-ah** [sebhildebrandt/systeminformation#722]
**Describe the bug**
Process `command` is truncated on Windows after upgrading from 5.6.22 to 5.12.4.

**To Reproduce**
See https://github.com/jonas-ah/systeminformation-process-command-bug.
This example lists the current process, which is started with a long command line, using the `processes` function.

**Current Output**
Using 5.12.4:
`"C:\\Program Files\\nodejs\\node.exe" .\\src\\ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567`

**Expected behavior**
Using 5.6.22:
`"C:\\Program Files\\nodejs\\node.exe" .\\src\\ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789\\index.mjs`

**Environment (please complete the following information):**
 - systeminformation package version: 5.12.4
 - OS: Windows 10

**Comment by sebhildebrandt** [comment]
@jonas-ah need to make some investigation here … will hopefully come up with a solution as soon as possible.

**Comment by sebhildebrandt** [comment]
@jonas-ah still unsure why this happens ... can you provide the output of 

```
Get-WmiObject Win32_Process | select ProcessId,ParentProcessId,ExecutionState,Caption,CommandLine,ExecutablePath,UserModeTime,KernelModeTime,WorkingSetSize,Priority,PageFileUsage,CreationDate | fl
```

**Comment by sebhildebrandt** [comment]
@jonas-ah ... well I guess I have an idea. Will provide a fix today in the evening.

**Comment by sebhildebrandt** [comment]
@jonas-ah ... version 5.12.8 just released. Can you check it?

**Comment by jonas-ah** [comment]
It's working. Thanks! 😃

**Comment by sebhildebrandt** [comment]
@jonas-ah … thank you for your fast feedback and once again sorry for having not responding so long …
