### ISSUE TITLE
networkConnections always return pid 0 with protocol udp on Windows

### ISSUE THREAD

**Issue by gitmai** [sebhildebrandt/systeminformation#724]
**Describe the bug**
When List networkConnections on windows always return pid 0 on all udp processes. 
After observing the output, I realised that, as the state does not come in windows, it is storing the pid in the state field. Please could you fix this.

**To Reproduce**
1. used function systeminformation.processes.networkConnections

**Current Output**
 {
    protocol: 'udp',
    localAddress: '192.168.56.1',
    localPort: '137',
    peerAddress: '*',
    peerPort: '*',
    state: '4123',
    pid: 0,
    process: ''
  },

**Expected behavior**
 {
    protocol: 'udp',
    localAddress: '192.168.56.1',
    localPort: '137',
    peerAddress: '*',
    peerPort: '*',
    state: '',
    pid: 4124,
    process: 0
  },

**Environment (please complete the following information):**
 - Windows

**Comment by sebhildebrandt** [comment]
@gitmai ok, I guess I see the problem, will fix it in the next few days ...

**Comment by gitmai** [comment]
Thank you very much, your project is a great help.

**Comment by sebhildebrandt** [comment]
@gitmai ... should be fixed, can you test It on your side? Version 5.12.6 just released,
