### ISSUE TITLE
CPU Usage in percentage

### ISSUE THREAD

**Issue by TrygveDev** [sebhildebrandt/systeminformation#725]
**Describe the solution you'd like**
I would like to have a feature that allows you to set an interval and get the current CPU usage in percentage. A constantly updating value.

**Describe alternatives you've considered**
Other node packages, node-os-utils. I am so satisfied with systeminformation that I would love to only use it for my project and not other old and bad packages.

**Comment by KasimAhmic** [comment]
I believe `si.currentLoad()` will give you what you're looking for. Here are the docs for it: https://systeminformation.io/processes.html

**Comment by sebhildebrandt** [comment]
@TrygveDev ... it seems that I prepared an answer but never posted it back ... sorry!

As @KasimAhmic said, the function `is.currentLoad()` is the one that will provide you with CPU usage in percent. 

I have intentionally not implemented a function that reads the values in an interval, because it should be kind of straight forward to do so:

```
const si = require('systeminformation');
setInterval(function() {
	si.currentLoad().then(data => 
		console.log(data));
}, 1000)
```

Or, if you like to have a certain set of values you like to have regulary, the `get()` function could also work:

```
const si = require('systeminformation');
valueObject = {
  currentLoad: 'currentLoad',
  mem: 'free'
}
setInterval(function() {
	si.get(valueObject).then(data => 
		console.log(data));
}, 1000)
```

Would this make sense?? If you want to observe a change of a value there is also the `observe()` function (see https://systeminformation.io/statsfunctions.html)

**Comment by TrygveDev** [comment]
#### Thanks for the help! This is exactly what I was looking for. 😁

#### However, I have two problems.
First, the percentage returned with "currentLoad" fluctuates a lot. From 33-55% in a second while windows task manager is saying that my CPU is at 57-60%. Is "currentLoad" giving me the wrong data or is windows task manager the one that is wrong?

#### Secondly, when i do this;
```js
setInterval(function() {
	si.get(valueObject).then(data => 
		console.log(data));
}, 1000)
```
I get new data every second.
However, if the promise of the call is not resolved within a second and the interval loops again making a new call, the app starts draining CPU percentage. I have an app with 5 calls like the one above (I am making a task manager type app with electron). Now the first couple of seconds are alright, however, the CPU percentage is rising up to 80% usage from my app. I solved this by only making a new call once data is returned. Am I doing something wrong or is it supposed to be like this?

#### Code can be found in my public repository called Centrl if needed.

**Comment by sebhildebrandt** [comment]
@TrygveDev you are right, in Windows things get a little more complicated. 

- the needed calls in windows really eats up resources. Much more than in other environments!
- when running the call every second, this will then lead in to a high overall CPU load
- I highly recommend making the interval much bigger in windows (5 secs) ...
