### ISSUE TITLE
Connect HWINFO64 to the package

### ISSUE THREAD

**Issue by Luminitza-Noptzii** [sebhildebrandt/systeminformation#728]
**Is your feature request related to a problem? Please describe.**
On windows 10 and 11, the package returns a cpu temperature that is under the ambient temp. It messes up my stuff.

**Describe the solution you'd like**
I wish it would be possible to get temperature data from apps like HWINFO64, HWMONITOR, Core Temp, etc in the package

**Describe alternatives you've considered**
Couldn't find any

**Additional context**
I have a minecraft server running on a W10 machine. After the cpu reaches a temperature threshold (70*C), a discord bot gets launched. That bot updates a channel with information related to the temperature of the cpu, but that temp is always 16.8*C. Tried on 2 machines, both ryzen, and it's kinda frustrating knowing that I could create a bot that can do that, but I cant show the correct temperature..

**Comment by sebhildebrandt** [comment]
@Luminitza-Noptzii As I am not familiar with HWINFO64, HWMONITOR, ... are there command line options that I can read out??

**Comment by Luminitza-Noptzii** [comment]
> @Luminitza-Noptzii As I am not familiar with HWINFO64, HWMONITOR, ... are there command line options that I can read out??



@sebhildebrandt Closest I could get for HWINFO64 are forums asking for command-line and a question in this forum which is incomplete
https://www.hwinfo.com/forum/threads/automatic-sensor-logging-via-command-line.8407/
and this for Open Hardware Monitor
https://github.com/openhardwaremonitor/openhardwaremonitor/issues/776

**Comment by sebhildebrandt** [comment]
@Luminitza-Noptzii for now I do not see any easy way to integrate HWINFO64 data ... closing it for now but will continue trying to find a better way to solve this issue.
