### ISSUE TITLE
networkConnections is not returning UDP ports on macOS

### ISSUE THREAD

**Issue by a-gamboa2** [sebhildebrandt/systeminformation#737]
**Describe the bug**
networkConnections on macOS Ventura 13.0 does not return UDP ports, even though it does on Windows. TCP ports are displayed correctly.

**To Reproduce**
1. 'sudo lsof | grep UDP' to check for multiple UDP ports listening
2. 'si.networkConnections()' to check the absence of UDP ports in the output

**Current Output**
TCP ports only on macOS

**Expected behavior**
All connections (TCP and UDP)

**Environment (please complete the following information):**
 - systeminformation package version: 5.12.13
 - OS: macOS Ventura 13.0 (22A380)
 - MacBook Pro 13 - 2017

**Comment by sebhildebrandt** [comment]
As I am using netztet to determine open network connections I now see, that the implementation is different in linux and Mac OS. For some UDP connections linux shows "ESTABLISHED" (even this protocol is stateless) and Mac OS shows no state information. Let me think about it. I will come up with a solution ...

**Comment by sebhildebrandt** [comment]
I pushed some changes here on GitHub (master). Can you check this out and test it if you get the desired results on macOS?

**Comment by a-gamboa2** [comment]
I have tested master and it works correctly! Now the UDP ports are displayed.

The only issue is that some of them are marked as protocol: 'udp46', which I don't know if it is completely correct. Most of them are correctly marked as 'udp4' or 'udp6'.

**Comment by sebhildebrandt** [comment]
@a-gamboa2 thank you for testing!! Not really sure what the `udp46` stands for ... I guess here we have situations where this is not determined if this is udp4 or udp6?

**Comment by a-gamboa2** [comment]
If netstat reports it then it is correct I guess. Thanks to you for the library. Are you going to make a release with the fix?

**Comment by sebhildebrandt** [comment]
@a-gamboa2 fine ;-) ... new version 5.12.15 just released.
