### ISSUE TITLE
Apache main process is not really the main process

### ISSUE THREAD

**Issue by frufin** [sebhildebrandt/systeminformation#738]
Hi, many thanks for such a powerful tool !

An Apache server always starts with a main process owned by root, then creates some child processes.
Calling si.processLoad ('apache2' ,*) within an Ubuntu distribution return a PID which is not that main process (which i can found amongst the additional PIDS). I have two questions about this:
- Have you any idea on how to get the real main one  ?
- What about the cpu and mem results : Are they only related to the first found process, or do they include the additional PIDS ?

**Comment by sebhildebrandt** [comment]
@frufin 

- main PID: here I have to make some research how to determine the main PID (the lowest one is probably not the correct one, right?)
- CPU and MEM: yes this is for all processes.

**Comment by frufin** [comment]
@sebhildebrandt , 
when calling the 'apache2' process, i sometimes get the main process as the PID,  (root owned), and sometimes one of the children processes... 
More, the 'additional PIDs' lists the root process + every child process

**Comment by frufin** [comment]
@sebhildebrandt ,
- from ps -ax | grep apache2  :

  996 ?        S      0:00 sh -c (ps -ax | grep apache2) 2>&1 
  997 ?        S      0:00 sh -c (ps -ax | grep apache2) 2>&1 
  999 ?        S      0:00 grep apache2 
 5893 ?        S      0:00 /usr/sbin/apache2 -k start
 5917 ?        S      0:01 /usr/sbin/apache2 -k start
 5936 ?        S      0:00 /usr/sbin/apache2 -k start
 5940 ?        S      0:00 /usr/sbin/apache2 -k start
 6530 ?        S      0:01 /usr/sbin/apache2 -k start
10839 ?        Ss     7:19 /usr/sbin/apache2 -k start
13402 ?        S      0:01 /usr/sbin/apache2 -k start
14071 ?        S      0:01 /usr/sbin/apache2 -k start
18297 ?        S      0:02 /usr/sbin/apache2 -k start
19773 ?        S      0:01 /usr/sbin/apache2 -k start
23597 ?        S      0:03 /usr/sbin/apache2 -k start

- from si.processLoad :

"processLoad":[{
     "proc":"apache2",
     "pid":5893,
     "pids":[5893,5917,5936,5940,6530,10839,13402,14071,18297,19773,23597],"cpu":0,"mem":11.099999999999998}],"...

- from the Apache "pidFile" where the main.root pid is stored : 10839

- ps -ef | grep apache2 shows that 10839 is root (i don't display results as executed a bit later, children pids have changed

**Comment by frufin** [comment]
I'm thining about what you said about the min pid (just understood now :) )...

Normally, children pids are created after the root pid, so their number should be greater.
I wrote a routine that give pid started time :
0: {pid: '5893', started: '2022-11-17T11:50:12.915Z'}
1: {pid: '5917', started: '2022-11-17T10:20:16.915Z'}
2: {pid: '5936', started: '2022-11-17T11:50:14.915Z'}
3: {pid: '5940', started: '2022-11-17T11:50:14.914Z'}
4: {pid: '6530', started: '2022-11-17T10:20:51.914Z'}
5: {pid: '10839', started: '2022-11-01T14:42:19.914Z'}
6: {pid: '13402', started: '2022-11-17T09:27:09.914Z'}
7: {pid: '14071', started: '2022-11-17T09:27:44.914Z'}
8: {pid: '18297', started: '2022-11-17T08:01:12.914Z'}
9: {pid: '19773', started: '2022-11-17T09:02:56.914Z'}
10: {pid: '23597', started: '2022-11-17T06:35:43.992Z'}

So, the main process 10839 was created 16 days before the children but those have a shorter pid...
Maybe this is because the "graceful restart" Apache action that i use for tests don't kill the main process but the children processes, and the auto-increment pids was resetted  meanwhile?

**Comment by sebhildebrandt** [comment]
@frufin … I am so stupid :-)
I have a super simple solution. Will provide a fix tonight.

**Comment by sebhildebrandt** [comment]
@frufin so I implemented my fix and published a new version 5.13.1. Can you test it on your side?

**Comment by frufin** [comment]
@sebhildebrandt , thank you for such a fast reply !
I'll check the new version, and i will tell you about it.
Best !

**Comment by sebhildebrandt** [comment]
@frufin correct! I do not know why I did not came up with this earlier ;-)
