### ISSUE TITLE
Lan adapter temperature shows instead of CPU.

### ISSUE THREAD

**Issue by rest2t** [sebhildebrandt/systeminformation#739]
**Describe the bug**
The function si.cpuTemperature as the main parameter returns the temperature for the i350bb-pci-0600. This is a LAN adapter.
Below I insert a comparison of the output of the function and the sensors command.

**To Reproduce**
1. used function
`si.cpuTemperature().then(data => console.log(data));`
2. Code output
```
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [],
     [Symbol(kWeak)]: WeakReference {} } }
> { main: 68,
  cores:
   [ 39, 34, 37, 39, 39, 39, 38, 35, 40, 42, 38, 44, 36, 38, 39, 40 ],
  max: 68,
  socket: [],
  chipset: null }
```
3. `sensors` command output:
```
coretemp-isa-0001
Adapter: ISA adapter
Package id 1:  +40.0°C  (high = +79.0°C, crit = +89.0°C)
Core 0:        +36.0°C  (high = +79.0°C, crit = +89.0°C)
Core 1:        +37.0°C  (high = +79.0°C, crit = +89.0°C)
Core 2:        +33.0°C  (high = +79.0°C, crit = +89.0°C)
Core 3:        +38.0°C  (high = +79.0°C, crit = +89.0°C)
Core 4:        +32.0°C  (high = +79.0°C, crit = +89.0°C)
Core 5:        +33.0°C  (high = +79.0°C, crit = +89.0°C)
Core 6:        +34.0°C  (high = +79.0°C, crit = +89.0°C)
Core 7:        +36.0°C  (high = +79.0°C, crit = +89.0°C)

i350bb-pci-0600
Adapter: PCI adapter
loc1:         +69.0°C  (high = +120.0°C, crit = +110.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +39.0°C  (high = +79.0°C, crit = +89.0°C)
Core 0:        +38.0°C  (high = +79.0°C, crit = +89.0°C)
Core 1:        +34.0°C  (high = +79.0°C, crit = +89.0°C)
Core 2:        +37.0°C  (high = +79.0°C, crit = +89.0°C)
Core 3:        +38.0°C  (high = +79.0°C, crit = +89.0°C)
Core 4:        +39.0°C  (high = +79.0°C, crit = +89.0°C)
Core 5:        +39.0°C  (high = +79.0°C, crit = +89.0°C)
Core 6:        +38.0°C  (high = +79.0°C, crit = +89.0°C)
Core 7:        +36.0°C  (high = +79.0°C, crit = +89.0°C)
```

**Expected behavior**
Main parameter should return the temperature of the processor or ambient sensor.

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: Ubuntu 20.04 x86_64
 - Hardware IBM X3650 M4

**Comment by sebhildebrandt** [comment]
@rest2t Thank you for providing detailed information!! I will make further investigation and will try to come up with a solution.

**Comment by sebhildebrandt** [comment]
@rest2t can you provide also the output of:

```
cat /sys/class/thermal/thermal_zone*/type  2>/dev/null; echo "-----"; cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null;
```

and 

```
for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=${label%_*}_input; echo $(cat "$label")___$(cat "$value"); fi; done; done;
```

**Comment by rest2t** [comment]
@sebhildebrandt 
`x86_pkg_temp
x86_pkg_temp
-----
38000
37000
`
and
`loc1___67000
Package id 0___38000
Core 0___37000
Core 1___30000
Core 2___34000
Core 3___35000
Core 4___37000
Core 5___38000
Core 6___35000
Core 7___32000
Package id 1___38000
Core 0___37000
Core 1___35000
Core 2___32000
Core 3___37000
Core 4___29000
Core 5___32000
Core 6___33000
Core 7___35000
`

**Comment by sebhildebrandt** [comment]
@rest2t thank you. I guess I see the problem and will try to fix it.

**Comment by sebhildebrandt** [comment]
@rest2t I implemented a fix for that. Version 5.13.2 just released. Can you check it on your side?

**Comment by rest2t** [comment]
@sebhildebrandt unfortunately. the same problem continues .

`ubuntu@ubuntu:~/ubuntu$ npm update systeminformation`
`+ systeminformation@5.13.2`
`updated 1 package and audited 168 packages in 3.983s`

`9 packages are looking for funding`
`  run 'npm fund' for details`

`found 5 vulnerabilities (2 high, 3 critical)`
`  run 'npm audit fix' to fix them, or `npm audit` for details`
`ubuntu@ubuntu:~/ubuntu$ node`
`> const si = require('systeminformation');`
`undefined`
`> si.cpuTemperature().then(data => console.log(data));`
`Promise {`
`  <pending>,`
`  domain:`
`   Domain {`
`     domain: null,`
`     _events:`
`      [Object: null prototype] {`
`        removeListener: [Function: updateExceptionCapture],`
`        newListener: [Function: updateExceptionCapture],`
`        error: [Function: debugDomainError] },`
`     _eventsCount: 3,`
`     _maxListeners: undefined,`
`     members: [],`
`     [Symbol(kWeak)]: WeakReference {} } }`
`> { main: 69,`
`  cores:`
`   [ 45, 43, 44, 45, 46, 45, 45, 42, 42, 45, 41, 46, 39, 41, 42, 43 ],`
`  max: 69,`
`  socket: [],`
`  chipset: null }`

`(To exit, press ^C again or type .exit)`
`> .exit`
`soseman@dockerownia:~/soseman-client$ sensors`
`coretemp-isa-0001`
`Adapter: ISA adapter`
`Package id 1:  +45.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 0:        +42.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 1:        +43.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 2:        +41.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 3:        +45.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 4:        +38.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 5:        +43.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 6:        +41.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 7:        +43.0°C  (high = +79.0°C, crit = +89.0°C)`

`i350bb-pci-0600`
`Adapter: PCI adapter`
`loc1:         +69.0°C  (high = +120.0°C, crit = +110.0°C)`

`coretemp-isa-0000`
`Adapter: ISA adapter`
`Package id 0:  +45.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 0:        +44.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 1:        +41.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 2:        +42.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 3:        +45.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 4:        +45.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 5:        +44.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 6:        +44.0°C  (high = +79.0°C, crit = +89.0°C)`
`Core 7:        +41.0°C  (high = +79.0°C, crit = +89.0°C)`

**Comment by sebhildebrandt** [comment]
@rest2t thank you for testing ... actually as the other commands I gave you return values, `sensors` output is not needed. So what I would like to see one more time:

can you add the following line in the `node_modules/systeminformation/lib/cpu.js`after line 1040:

```
console.log(lines);
```

and post then again the full output (so the console.log as well as the data spitted out from your code)

**Comment by yatagasaru** [comment]
> Version 5.13.3 just released.

Unrelated to `The function si.cpuTemperature as the main parameter returns the temperature for the i350bb-pci-0600. This is a LAN adapter.`, but the latest version fixed my problem with cpu temperature returning 0.

Thank you so much!

**Comment by sebhildebrandt** [comment]
@rest2t did you had time to test it once again? Then we can close this issue ;-) Thank you in advance!

**Comment by rest2t** [comment]
@sebhildebrandt I just tested the latest version. Everything works as expected, thanks!
