### ISSUE TITLE
Not returning correct external IPv6 address

### ISSUE THREAD

**Issue by adamreisnz** [sebhildebrandt/systeminformation#74]
When I run `si.networkInterfaces()` it returns the incorrect IPv6 address for my interface. Instead of reporting the external address, it reports the [link local address](https://www.cisco.com/c/en/us/support/docs/ip/ip-version-6-ipv6/113328-ipv6-lla.html), starting with `fe80::`. 

These addresses should probably be filtered out, so that the proper external IP address can be selected.

**Comment by adamreisnz** [comment]
The problem seems to be that you run all addresses in a loop and basically overwrite the value. I'll create a PR to address this.

**Comment by sebhildebrandt** [comment]
Fixed in version 3.30.2.
