### ISSUE TITLE
5.12.14 version introduces a régression while retrieving loggedons and users data

### ISSUE THREAD

**Issue by evrico** [sebhildebrandt/systeminformation#740]
**Describe the bug**
Because of using Get-CimInstance instead of Get-WmiObject data format has changed and are no longer correctly parsed.

**To Reproduce**
- using 5.13.13 users.js following code:
if (_windows) {
        try {
          let cmd = 'Get-WmiObject Win32_LogonSession | select LogonId,StartTime | fl' + '; echo \'#-#-#-#\';';
          cmd += 'Get-WmiObject Win32_LoggedOnUser | select antecedent,dependent | fl ' + '; echo \'#-#-#-#\';';
          cmd += 'Get-WmiObject Win32_Process -Filter "name=\'explorer.exe\'" | Select @{Name="sessionid";Expression={$_.SessionId}}, @{Name="domain";Expression={$_.GetOwner().Domain}}, @{Name="username";Expression={$_.GetOwner().User}} | fl' + '; echo \'#-#-#-#\';';
          cmd += 'query user';
          util.powerShell(cmd).then((data) => {
            if (data) {
              data = data.split('#-#-#-#');
              let sessions = parseWinSessions((data[0] || '').split(/\n\s*\n/));
              let loggedons = parseWinLoggedOn((data[1] || '').split(/\n\s*\n/));
              let queryUser = parseWinUsersQuery((data[3] || '').split('\r\n'));
              let users = parseWinUsers((data[2] || '').split(/\n\s*\n/), queryUser);
- using 5.13.14 users.js following code:
if (_windows) {
        try {
          let cmd = 'Get-CimInstance Win32_LogonSession | select LogonId,StartTime | fl' + '; echo \'#-#-#-#\';';
          cmd += 'Get-CimInstance Win32_LoggedOnUser | select antecedent,dependent | fl ' + '; echo \'#-#-#-#\';';
          cmd += 'Get-CimInstance Win32_Process -Filter "name=\'explorer.exe\'" | Select @{Name="sessionid";Expression={$_.SessionId}}, @{Name="domain";Expression={$_.GetOwner().Domain}}, @{Name="username";Expression={$_.GetOwner().User}} | fl' + '; echo \'#-#-#-#\';';
          cmd += 'query user';
          util.powerShell(cmd).then((data) => {
            if (data) {
              data = data.split('#-#-#-#');
              let sessions = parseWinSessions((data[0] || '').split(/\n\s*\n/));
              let loggedons = parseWinLoggedOn((data[1] || '').split(/\n\s*\n/));
              let queryUser = parseWinUsersQuery((data[3] || '').split('\r\n'));
              let users = parseWinUsers((data[2] || '').split(/\n\s*\n/), queryUser);

**Current Output**
- it's 5.13.14 output: 
data: [
  "\r\n\r\nLogonId   : 1134688\r\nStartTime : 17-Nov-22 09:24:49\r\n\r\nLogonId   : 1134646\r\nStartTime : 17-Nov-22 09:24:49\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"1134688\")\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"1134646\")\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nsessionid : 1\r\ndomain    : \r\nusername  : \r\n\r\n\r\n\r\n",
  "\r\n USERNAME              SESSIONNAME        ID  STATE   IDLE TIME  LOGON TIME\r\n>u8004279              console             1  Active      none   17-Nov-22 09:24\r\n",
]
sessions: {
  "1134646": "17-Nov-22 09:24:49",
  "1134688": "17-Nov-22 09:24:49",
}
loggedons: {
  " 1134688)": {
    domain: " U8004279",
    user: " RFT)",
  },
  " 1134646)": {
    domain: " U8004279",
    user: " RFT)",
  },
}
queryUser: [
  {
    user: "u8004279",
    tty: "console",
  },
]
users: [
]

**Expected behavior**
- like 5.13.13 output:
data: [
  "\r\n\r\nLogonId   : 1134688\r\nStartTime : 20221117092449.375756+060\r\n\r\nLogonId   : 1134646\r\nStartTime : 20221117092449.375756+060\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nantecedent : \\\\.\\root\\cimv2:Win32_Account.Domain=\"RFT\",Name=\"U8004279\"\r\ndependent  : \\\\.\\root\\cimv2:Win32_LogonSession.LogonId=\"1134688\"\r\n\r\nantecedent : \\\\.\\root\\cimv2:Win32_Account.Domain=\"RFT\",Name=\"U8004279\"\r\ndependent  : \\\\.\\root\\cimv2:Win32_LogonSession.LogonId=\"1134646\"\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nsessionid : 1\r\ndomain    : RFT\r\nusername  : U8004279\r\n\r\n\r\n\r\n",
  "\r\n USERNAME              SESSIONNAME        ID  STATE   IDLE TIME  LOGON TIME\r\n>u8004279              console             1  Active      none   17-Nov-22 09:24\r\n",
]
sessions: {
  "1134646": "20221117092449.375756+060",
  "1134688": "20221117092449.375756+060",
}
loggedons: {
  "1134646": {
    domain: "RFT",
    user: "U8004279",
  },
  "1134688": {
    domain: "RFT",
    user: "U8004279",
  },
}
queryUser: [
  {
    user: "u8004279",
    tty: "console",
  },
]
users: [
  {
    domain: "RFT",
    user: "U8004279",
    tty: "console",
  },
]

**Environment (please complete the following information):**
 - systeminformation package version: 5.12.14
 - OS: Windows

**Comment by sebhildebrandt** [comment]
@evrico I did some investigation here and I can see the problem. I am working on a fix and will provide it tomorrow. I found two more smaller issues after changing to `Get-CimInstance `. For those I also have a fix.

**Comment by evrico** [comment]
@sebhildebrandt, testing with 5.13.4 version on windows I get:

data: [
  "\r\n\r\nLogonId   : 8726438\r\nStartTime : 2022-11-18 09:35:43\r\n\r\nLogonId   : 8726414\r\nStartTime : 2022-11-18 09:35:43\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"8726438\")\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"8726414\")\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nUser   : U8004279\r\nDomain : RFT\r\n\r\n\r\n\r\n\r\n\r\nSessionId : 1\r\n\r\n\r\n\r\n# -# -# -#\r\n USERNAME              SESSIONNAME        ID  STATE   IDLE TIME  LOGON TIME\r\n>u8004279              console             1  Active      none   18-Nov-22 09:35\r\n",
]
sessions: {
  "8726414": "2022-11-18 09:35:43",
  "8726438": "2022-11-18 09:35:43",
}
loggedons: {
  "8726414": {
    domain: "RFT)",
    user: "U8004279",
  },
  "8726438": {
    domain: "RFT)",
    user: "U8004279",
  },
}
queryUser: [
]
users: [
  {
    domain: "RFT",
    user: "U8004279",
    tty: "",
  },
]

So it seems not to be good for queryUser and users[i].tty
Hope this helps

**Comment by sebhildebrandt** [comment]
@evrico my fault!!! While copying text something got messed up. Now also `tty` should work. Tested it here once again. Version 5.13.5 just released. Can you also test it??

**Comment by sebhildebrandt** [comment]
@sebhildebrandt ... should be there ...
<img width="864" alt="image" src="https://user-images.githubusercontent.com/4717960/202718807-eb0f54cd-2e46-4f76-af0c-e712307d7214.png">

**Comment by evrico** [comment]
I can't see it yet:
![Screenshot 2022-11-18 145757](https://user-images.githubusercontent.com/19262138/202721826-56358128-767a-40c2-8d79-6a7d7b50f4a7.png)
I will try later...

**Comment by evrico** [comment]
got it!
and it's almost ok, see the unwanted parenthesis in loggedons/domains:
data: [
  "\r\n\r\nLogonId   : 8726438\r\nStartTime : 2022-11-18 09:35:43\r\n\r\nLogonId   : 8726414\r\nStartTime : 2022-11-18 09:35:43\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"8726438\")\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"8726414\")\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nUser   : U8004279\r\nDomain : RFT\r\n\r\n\r\n\r\n\r\n\r\nSessionId : 1\r\n\r\n\r\n\r\n",
  "\r\n USERNAME              SESSIONNAME        ID  STATE   IDLE TIME  LOGON TIME\r\n>u8004279              console             1  Active      none   18-Nov-22 09:35\r\n",
]
sessions: {
  "8726414": "2022-11-18 09:35:43",
  "8726438": "2022-11-18 09:35:43",
}
loggedons: {
  "8726414": {
    domain: "RFT)",
    user: "U8004279",
  },
  "8726438": {
    domain: "RFT)",
    user: "U8004279",
  },
}
queryUser: [
  {
    user: "u8004279",
    tty: "console",
  },
]
users: [
  {
    domain: "RFT",
    user: "U8004279",
    tty: "console",
  },
]

**Comment by evrico** [comment]
fixed with your 5.14.4 version:
data: [
  "\r\n\r\nLogonId   : 7350283\r\nStartTime : 2022-11-28 09:35:12\r\n\r\nLogonId   : 7350252\r\nStartTime : 2022-11-28 09:35:12\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"7350283\")\r\n\r\nantecedent : Win32_Account (Name = \"U8004279\", Domain = \"RFT\")\r\ndependent  : Win32_LogonSession (LogonId = \"7350252\")\r\n\r\n\r\n\r\n",
  "\r\n\r\n\r\nUser   : U8004279\r\nDomain : RFT\r\n\r\n\r\n\r\n\r\n\r\nSessionId : 1\r\n\r\n\r\n\r\n",
  "\r\n USERNAME              SESSIONNAME        ID  STATE   IDLE TIME  LOGON TIME\r\n>u8004279              console             1  Active      none   28-Nov-22 09:35\r\n",
]
sessions: {
  "7350252": "2022-11-28 09:35:12",
  "7350283": "2022-11-28 09:35:12",
}
loggedons: {
  "7350252": {
    domain: "RFT",
    user: "U8004279",
  },
  "7350283": {
    domain: "RFT",
    user: "U8004279",
  },
}
queryUser: [
  {
    user: "u8004279",
    tty: "console",
  },
]
users: [
  {
    domain: "RFT",
    user: "U8004279",
    tty: "console",
  },
]
