### ISSUE TITLE
Is it possible to check if file system is mounted as ro or rw? 

### ISSUE THREAD

**Issue by td-krzysiek** [sebhildebrandt/systeminformation#745]
Hello,

Is there an option to check if a file system is mounted as ro or rw, please? I'm trying to find this in the documentation but can't see this option. Apologise if there is one but I haven't noticed it.

Thank you,
Krzysztof

**Comment by sebhildebrandt** [comment]
@td-krzysiek Hi, currently there is no information about mounted rw/ro status in the library. After making a small research, this should be easy to implement (at least for linux). Will provide an extension for that in the next week.

**Comment by td-krzysiek** [comment]
@sebhildebrandt thank you much appreciated, Linux is my use case - under some circumstances OS can remount drive as read-only (due to file system issue or hardware failure), this is something I'm trying to monitor too.

**Comment by sebhildebrandt** [comment]
@td-krzysiek understand ;-) ... as said ... this should be easy to implement ... I would like to do. some further research for Mac OS, BSD and probably windows as I would like to implement all functionality across multiple platforms.

**Comment by td-krzysiek** [comment]
Thank you, I confirm this works as expected on linux & mac.
