### ISSUE TITLE
Any tentative to get rid of calling reg.exe on Windows?

### ISSUE THREAD

**Issue by ThomasMoutel** [sebhildebrandt/systeminformation#747]
Hi,

I have users who tend to be pretty cautious about the processes I spawn, and some pieces of systeminformation (osinfo/uuid & cpu/cpuFlags) are calling reg.exe on Windows.
Have you ever considered using an alternative way to get Windows registry information?

Best regards,
Thomas

**Comment by sebhildebrandt** [comment]
@ThomasMoutel ... thank you for asking! Well I could use also PowerShell `Get-ItemProperty` but this is quite slow because I have to spin up a PowerShell instance ... I currently do not see the benefit as a user could also change registry entries with PowerShell commands? Maybe you can explain, why a change would be better? Thank you in advance

**Comment by ThomasMoutel** [comment]
Hi @sebhildebrandt, sorry for not answering earlier.
I have clients who are very concerned about security matters, and having our software spawning processes such as reg.exe or powershell is not really accepted.
For reg.exe usage in our own code we've started moving to use npm's windows-native-registry module. But we have some dependencies (systeminformation among them) that we cannot change ourselves.
Hope this clarifies my request. :)

**Comment by sebhildebrandt** [comment]
@ThomasMoutel thank you for clarifying ... 

So the whole package relies on build in functionalities of each operating system to retrieve system information (with no external dependencies). For Windows, only `PowerShell` commands (in former versions we used `wmic` which is now deprecated) are available to retrieve those information. To get registry information I also do not see alternatives to use PowerShell `Get-ItemProperty` OR `reg.exe` which both can be "risky" in terms of security considerations if you are able to pass parameters to the package. As no external parameters or environment variables are influencing the behavior of the package and the code is open source and transparent, it normally should pass all security checks for all clients. 

An alternative would off course be to rewrite the whole package for windows using c/c++ functions but this is at the moment out of scope for our development.

One more thing: If security issues are detected (as we had some cases in the past) it is number 1 priority to address and fix such issues. In the current version we do not have any open security issue. 

Closing this for now as I currently do not really see any alternative. If you have further ideas on that, feel free to reopen the issue. Thank you in advance. Regards.
