### ISSUE TITLE
Inconsistent output on `node:16-alpine` container for busybox `ps` and procps `ps`

### ISSUE THREAD

**Issue by simontong** [sebhildebrandt/systeminformation#750]
**Describe the bug**
In addition to multiple props being inconsistent (as seen below in the Current Output), the `started` time results in `NaN-aN-aN NaN:NaN:aN`, when using `systeminformation.processes()`, if a certain amount of process runtime has elapsed. My findings suggest the invalid `started` prop is due to the `etime` output formatting not matching `00:00:00` and instead matches a relative time, i.e. `1h34`.

To remedy this issue, I needed to install `procps`, which then output the `etime` in the expected format.

**To Reproduce**
I've created a [git repo](https://github.com/simontong/systeminformation-issue1) to illustrate the problem.

Steps to run:
```sh
git clone https://github.com/simontong/systeminformation-issue1
cd systeminformation-issue1
docker run --rm -it (docker build -q .)
```

**Current Output**
```sh
===[ busybox ]===
{
  pid: 7,
  parentPid: 1,
  name: 'node',
  cpu: 0,
  cpuu: 0,
  cpus: 0,
  mem: 0,
  priority: 0,
  memVsz: 10,
  memRss: 40,
  nice: 0,
  started: '2022-12-02 23:59:26',
  state: 'running',
  tty: '136.0',
  user: 'root',
  command: 'node'
}
===[ procps ]===
{
  pid: 1,
  parentPid: 0,
  name: 'node',
  cpu: 0.000018171938509184832,
  cpuu: 0.00001465478912031035,
  cpus: 0.0000035171493888744838,
  mem: 0,
  priority: 19,
  memVsz: 10775264,
  memRss: 41636,
  nice: 0,
  started: '2022-12-06 23:59:27',
  state: 'running',
  tty: 'pts/0',
  user: 'root',
  command: 'node index.mjs',
  params: '',
  path: ''
}
```

**Expected behavior**
The return value before and after installing `procps` should be the same. Either that, or outputting an error message suggesting they need to install `procps`.

**Environment (please complete the following information):**

- systeminformation package version: 5.16.1
- Docker OS: node:16-alpine

**Additional context**

n/a

**Comment by sebhildebrandt** [comment]
@simontong thank you for reporting, I will have a closer look on it and provide a fix as soon as possible.

**Comment by sebhildebrandt** [comment]
@simontong busybox `ps` does not support output params `pcpu` and `pmem`, therefore there is a fallback. As this package should work on as much distros as possible without firing error messages and the need of additional installation I did implemented this fallback (where we do not have CPU and MEM values. Hope this makes sense.

**Comment by simontong** [comment]
Thanks for investigating that, appreciate it.

Were you able to reproduce the other issue with the `etime` time formatting? It requires waiting a period of time (possibly around an hour?) and then the formatting switches from `00:00` to `1h00` and the code doesn't parse it correctly anymore.

**Comment by sebhildebrandt** [comment]
Sorry @simontong … seems that I did not really read your issue report correctly. This time format issue is of course something I need to have a look at. I am sure I will find a way to also handle this correctly. Sorry once again for not reading your comment correctly ;-)

**Comment by simontong** [comment]
Don't sweat it :)

**Comment by sebhildebrandt** [comment]
@simontong I now fixed the `started` issue in `si.processes()` and was able to test it on `node:16-alpine`. Seems to be fine now. Version 5.16.4 just released. Can you check it also on your side?

**Comment by simontong** [comment]
Big thanks, @sebhildebrandt. That appears to be working now. I just tested it on a container with around `1d01` as the `etime` and the `started` time is now `2022-12-10 20:6:24`. I assume the single-digit minute is intended (instead of `06`)?

**Comment by sebhildebrandt** [comment]
@simontong single digit is not really intended ... let me check and provide a fix ...  

found it. Version 5.16.6 just published.
