### ISSUE TITLE
si.users() fails on windows (10) when multiple explorer.exe are running

### ISSUE THREAD

**Issue by xavier-deryckere** [sebhildebrandt/systeminformation#751]
Hi

This command:
`Get-CimInstance Win32_Process -Filter "name = 'explorer.exe'"`

Usually returns only one entry, the main explorer process.
But sometimes there may be several of them (don't ask how or why).
To make sure this happens you can go to the folder options and check the "Launch folder windows in a separate process" option.
![image](https://user-images.githubusercontent.com/20986910/206484628-949030bd-633a-45f2-8094-0a5c72563cad.png)
Each explorer you launch will add one extra explorer.exe process.

As a consequence, this:
`$process = (Get-CimInstance Win32_Process -Filter "name = 'explorer.exe'"); Invoke-CimMethod -InputObject $process -MethodName GetOwner | select user, domain | fl; get-process -name explorer | select-object sessionid | fl;`
will fail with an error:
`Invoke-CimMethod : Cannot convert 'System.Object[]' to the type 'Microsoft.Management.Infrastructure.CimInstance' required by parameter 'InputObject'. Specified method is not supported. [...]`

In such a case the whole powershell command is missing data and si.users() returns empty.

I am quite ignorant of powershell but I tried with " ... -InputObject $process**[0]** ..." just for fun, and with any number of explorer.exe processes (including just 1) it "works on my machine" (TM).

**Comment by sebhildebrandt** [comment]
@xavier-deryckere thank you ... will try to add this!!

**Comment by sebhildebrandt** [comment]
@xavier-deryckere fixed ... version 5.16.3 just released. Thank you!
