### ISSUE TITLE
Get position coordinates for additional monitors from their layout

### ISSUE THREAD

**Issue by draeder** [sebhildebrandt/systeminformation#756]
**Is your feature request related to a problem? Please describe.**
I am trying to detect the edges of additional monitors. 

<img width="415" alt="Screen Shot 2022-12-28 at 5 12 31 AM" src="https://user-images.githubusercontent.com/15527661/209803648-4ef743da-70da-473f-b811-ffcf4fcfa0e0.png">

I am using a mouse coordinates position tracker and need to know when I'm left, right, top, bottom for all monitors. Since `positionX` and `positionY` are 0, I am not able to do the math needed to determine the edge coordinates of the secondary monitor.

**Describe the solution you'd like**
Get the position coordinates for additional monitors. If the 2nd monitor is `y = -200` from the primary display, set `positionY = -200`.

**Additional context**
I am trying to build a mouse/keyboard sharing application that uses UDP instead of TCP (Synergy/Barrier) to defeat a mouse / keyboard lag over wifi which is caused by TCP retransmissions. I need to know when I'm at the edge of connected displays so I can send the mouse coordinates, clicks, keypresses, etc. to the other computer(s).

**Comment by sebhildebrandt** [comment]
@draeder can you provide the output of the following command on your system (with the 2 monitors connected)?

```
system_profiler -detailLevel full SPDisplaysDataType
```

Thank you in advance.

**Comment by draeder** [comment]
@sebhildebrandt Sure, here's the output:

```
Graphics/Displays:

    Intel Iris Plus Graphics:

      Chipset Model: Intel Iris Plus Graphics
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel
      Device ID: 0x8a53
      Revision ID: 0x0007
      Metal Family: Supported, Metal GPUFamily macOS 2
      Displays:
        Color LCD:
          Display Type: Built-In Retina LCD
          Resolution: 2560 x 1600 Retina
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Automatically Adjust Brightness: Yes
          Connection Type: Internal
        DELL S2715H:
          Resolution: 1920 x 1080 (1080p FHD - Full High Definition)
          UI Looks like: 1920 x 1080 @ 60.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Display Serial Number: PP92G584449L
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Connection Type: Thunderbolt/DisplayPort
```

**Comment by sebhildebrandt** [comment]
@draeder So unfortunately this does not gives back information about position of screens. I was aware of this but just wanted to be sure that this is the same on your side. 

I have to make a research how we can determine the relative position of the screens in Mac OS ...

**Comment by draeder** [comment]
@sebhildebrandt That command led me to look into other commands that might give more detail. I found this one:

`defaults read /Library/Preferences/com.apple.windowserver.plist > output.txt`

This outputs quite a bit of data, and I found this, which appears to be exactly what I need.

```
                UnmirroredOriginX = 1440;
                UnmirroredOriginY = "-180";
                UnmirroredResolution = 1;
                UnmirroredWidth = 1920;
                Width = 1920;
```

**Comment by sebhildebrandt** [comment]
@draeder wow ... yes this is cool! 

BUT: on my machine there is no `com.apple.windowserver.plist`, I only have a `com.apple.windowserver.displays.plist`. Currently I have no other monitor connected. Need to test how this looks like on my other machines and with connected secondary monitors. As I am on holiday I am not sure, how fast I can provide a reliable solution.

**Comment by draeder** [comment]
@sebhildebrandt Interesting.. I don't have `com.apple.windowserver.displays.plist` on my machine. I have a 13" MacBook Pro 2020 running macOS Monterey (v12.5.1), if that helps.

I'm not in any kind of rush and really appreciate you looking into it whenever you can. I'll also take a look at the code and see if I can do something with it. If so, I'll submit a PR.

**Comment by sebhildebrandt** [comment]
@draeder ok, so then I would make a research on that. I have several MacBooks (Apple Silicon, M1, ...) , a Mac mini, and a desktop machine with multiple monitors. I am pretty much sure to find a solution that will fir for most of the cases ;-) Hope to come up with a solution in the first week of January. 

So from your side no need to invest time for a PR ;-)

**Comment by draeder** [comment]
This does appear to be version related.. See the last comment in this [SO answer](https://stackoverflow.com/a/20115806/1551027)

**Comment by sebhildebrandt** [comment]
@draeder Would you provide the full `output.txt` from your machine ... this would help me a lot ...

**Comment by draeder** [comment]
Here you go: https://gist.github.com/draeder/f605c09f02ff6c30b18a6b804160b51c

**Comment by draeder** [comment]
@sebhildebrandt Would you mind letting me know when you have it? This type of data is used for identity tracking and I would like to remove it when I can.

**Comment by sebhildebrandt** [comment]
@draeder got it ... THANK YOU!

**Comment by sebhildebrandt** [comment]
@draeder I started to work on it. Got also results from max OS Ventura (13.x) which are good to get  the needed information. So basically I will have then two ways of parsing the output (pre and post Ventura) ... Will come up with a solution at the end of the week.

**Comment by sebhildebrandt** [comment]
@draeder ... I just published a first version with new attributes `positionX` and `positionY` in `graphics()` also for mac OS. Tested it on Ventura and Monterey ... can you also test it on your side?

**Comment by sebhildebrandt** [comment]
@draeder ... found one small issue which is now fixed ... Version5.17.1 just released

**Comment by draeder** [comment]
Looking good! Thanks!

```js
{
  controllers: [
    {
      vendor: 'Intel',
      model: 'Intel Iris Plus Graphics',
      bus: 'Built-In',
      vramDynamic: true,
      vram: 1536,
      deviceId: '0x8a53',
      vendorId: '0x8086',
      external: false,
      cores: null,
      metalVersion: 'mac2'
    }
  ],
  displays: [
    {
      vendor: 'Apple',
      vendorId: '610',
      model: 'Color LCD',
      productionYear: '2017',
      serial: null,
      displayId: '4280f80',
      main: true,
      builtin: true,
      connection: 'Internal',
      sizeX: null,
      sizeY: null,
      pixelDepth: 32,
      resolutionX: 2880,
      resolutionY: 1800,
      currentResX: 1440,
      currentResY: 900,
      positionX: 0,
      positionY: 0,
      currentRefreshRate: null
    },
    {
      vendor: 'DELL',
      vendorId: '10ac',
      model: 'DELL S2715H',
      productionYear: '2015',
      serial: '3434394c',
      displayId: '2b10178d',
      main: false,
      builtin: false,
      connection: 'Display Port',
      sizeX: null,
      sizeY: null,
      pixelDepth: 32,
      resolutionX: 1920,
      resolutionY: 1080,
      currentResX: 1920,
      currentResY: 1080,
      positionX: 1440,
      positionY: -180,
      currentRefreshRate: 60
    }
  ]
}
```
