### ISSUE TITLE
[ask for advice] Use of UUID for registration/authentication

### ISSUE THREAD

**Issue by jeremyben** [sebhildebrandt/systeminformation#765]
Hi, thank you for the work on this incredible package.

We want to wrap our web app in an electron container and use this package to move the authentication system to a more "desktop-ish" one, with a **license key tied to a computer**.

My background is with the webs, to make sure a user _is_ the right user, we have password, 2FA, cookies, sessions, and a few unreliable fingerprinting techniques.

I'm not sure in the desktop world what would be a unique and **reliable** identifier to make sure that the license key is used within the right computer.
We handle sensitive data, so it's more of a security issue than a business one. We must be sure that our client _is_ our client.

I see methods in this package that could be used for fingerprinting.
I'm kindly asking for advice from anyone who have successfully implemented such a security feature, pros and cons of using these values.

- My instinct would go for `si.uuid()`, but should I go for hardware UUID only ? Is this value linked to the motherboard, the CPU, the hard drive ? What kind of hardware replacement would make this value change ?

- Is OS UUID reliable enough on its own ?

- `si.system()` gives a serial number and a uuid. Are these values always available, especially for a generic PC built from scratch ? 

- `si.baseboard()` gives the motherboard serial number, which seems like a reliable and unique value, unlikely to change.

- `si.diskLayout()` gives the hard drive serial number, which I read somewhere is used for fingerprinting.

**Comment by sebhildebrandt** [comment]
@jeremyben ... thank you for your question. 

As you already stated in your comment, some of the UUIDs can be used for fingerprinting. The key point here is, that some of the UUIDs can be manipulated, so there is never a 100% guarantee that this would work. You can use this method only as an additional indicator in your security concept. Be aware that 

- some UUIDs can change 
- can be undefined (especially on generic PC builds you might have empty ore generic strings like `Default String` or `O.E.M. ...`

So one idea to get a fingerprint would be to determine multiple IDs

- from `si.uuid()` -> `os` and `hardware` (which is not linked to the motherboard)
- all serials from `diskLayout()` 
- serials may be also from `baseboard()`, `bios()`
- `model`from `baseboard`

and then check if at least a certain number of IDs did not changed. 

Iy ou ask me: you still should not omit any user authentication just by using this method. You can only use this as an additional method for improving you security.

**Comment by jeremyben** [comment]
Thank you for such a comprehensive answer, keep up the good work.
