### ISSUE TITLE
Security risk: interface names are passed directly to shell command

### ISSUE THREAD

**Issue by lodi-g** [sebhildebrandt/systeminformation#766]
Hey,

Most of the code responsible for returning network interfaces details uses the interface name in shell commands without sanitization, e.g.: https://github.com/sebhildebrandt/systeminformation/blob/21b1d62b2110169488bef7d1c1afa6a62f56b839/lib/network.js#L833

Interface names have no limitations other than 15 characters and no forward slashes nor spaces. It is therefore possible to name an interface `$(reboot)` which would lead to the system rebooting when executing `si.networkInterfaces()`.

The interface name can be sanitized as done here: https://github.com/sebhildebrandt/systeminformation/blob/21b1d62b2110169488bef7d1c1afa6a62f56b839/lib/network.js#L1198-L1204

Thanks

**Comment by sebhildebrandt** [comment]
Hi @lodi-g ... after a very first check: this function does not have the interface `$iface` as a user input. This value actually comes from `os.networkInterfaces()`. So the only way of injecting malicious code would be by overwriting `os.networkInterfaces()`. I now created a fix for that. Version 5.17.4 just released.
