### ISSUE TITLE
Compatibility issue with Node.js v8

### ISSUE THREAD

**Issue by bdcdekimo** [sebhildebrandt/systeminformation#768]
**Describe the bug**
Commit https://github.com/sebhildebrandt/systeminformation/commit/e360fd2c7f4e5876e3a1c146013436a832dabfb8 introduced a change which causes the library to longer be compatible with Node.js 8.

It uses optional catch binding in processes.js
```try {
    res = new Date(current.getTime() - ms);
    result = res.toISOString().substring(0, 10) + ' ' + res.toISOString().substring(11, 19);
  } catch {
    util.noop();
  }
```
and this is only supported since Node.js 10: https://node.green/#ES2019-misc-optional-catch-binding

**To Reproduce**
1. Require systeminformation in a source file
2. Run using Node.js 8

**Current Output**
```
node_modules/systeminformation/lib/processes.js:101
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules/systeminformation/lib/index.js:35:19)
```

**Expected behavior**
Either fix compatibility with Node.js 8 or update package.json to include compatibility with >=10.0.0 only.

**Environment:**
 - systeminformation package version: 5.17.4
 - OS: Linux
 - Node.js v8.17.0

**Comment by sebhildebrandt** [comment]
@bdcdekimo thank you! My fault. Need to make a research on how to get this back ... will provide a fix for that (keeping node 8 compatibility) tonight!

**Comment by sebhildebrandt** [comment]
@bdcdekimo ... ok I think it was just the false catch statement which is fixed now. Version 5.17.6 just released. Can you check it on your side?

**Comment by bdcdekimo** [comment]
@sebhildebrandt that fixes the issue! Thanks for the quick fix
