### ISSUE TITLE
si.services("*") not showing stopped services

### ISSUE THREAD

**Issue by michelseiler** [sebhildebrandt/systeminformation#769]
Systemd services that are enabled and stopped are not found with the `si.services("*")` function on the Ubuntu LTS Server OS.

The command ` systemctl --type=service --no-legend 2> /dev/null` does not return stopped services.
Maybe you could use this command to get all services:
`systemctl --all --type=service --no-legend 2> /dev/null`
But I'm not sure if this solution is good for everyone.

This is the line in the source code:
https://github.com/sebhildebrandt/systeminformation/blob/b82df5427b19cd7ec10774be89c0238cdcdf2a1a/lib/processes.js#L154

Thanks

**Comment by sebhildebrandt** [comment]
@michelseiler ... this would make sense ... the question is if also `not-found` services should be displayed or only the `loaded` once. I tend to tackle only the later ones ... what do you think?

Here some example output:
```
postgresql@12-main.service             loaded    active   running PostgreSQL Cluster 12-main
rbdmap.service                         not-found inactive dead    rbdmap.service
rc-local.service                       loaded    inactive dead    /etc/rc.local Compatibility
redis.service                          not-found inactive dead    redis.service
```

**Comment by michelseiler** [comment]
I agree. Only the loaded once should be displayed.

**Comment by sebhildebrandt** [comment]
@michelseiler ... Version 5.17.5 just published. Can you check it on your side?

**Comment by michelseiler** [comment]
@sebhildebrandt ... works perfectly. Thank you for the work.
