### ISSUE TITLE
Windows users

### ISSUE THREAD

**Issue by MeesMaas** [sebhildebrandt/systeminformation#77]
Sorry the bother you again. But we discovered another issue with users. Use the command ```si.users()```

![electron_2017-10-04_22-03-12](https://user-images.githubusercontent.com/10887960/31197098-4f0eb53c-a950-11e7-9fca-c98dc6914750.png)

As you can see the user in the second Object is "". While the name is listed in tty (elsbeth).
Running ```net user``` returns the following

![mintty_2017-10-04_22-08-49](https://user-images.githubusercontent.com/10887960/31197199-a2fc38b8-a950-11e7-9e2e-48335e113d97.png)

I hope this gives you the information you need.

**Comment by sebhildebrandt** [comment]
No problem! What is the output of `query user` in the console?

**Comment by MeesMaas** [comment]
![mintty_2017-10-04_22-16-06](https://user-images.githubusercontent.com/10887960/31197513-a507e2a0-a951-11e7-81a6-a23ac4d5c17d.png)

**Comment by sebhildebrandt** [comment]
Thank you! OK, very clear. Will provide an update/fix as soon as possible.

**Comment by MeesMaas** [comment]
Thank you very much

**Comment by sebhildebrandt** [comment]
Hi again, I fixed the error. new version 3.30.5 already published. Please recheck if it works now. I discovered, that date and time parsing was also not correct.
