### ISSUE TITLE
networkInterfaces type definition seems broken

### ISSUE THREAD

**Issue by AltarBeastiful** [sebhildebrandt/systeminformation#775]
[In recent commit 21b1d62](https://github.com/sebhildebrandt/systeminformation/blob/bb0431eaf08d390a31b3b0b62a54dac6f3a99d83/lib/index.d.ts#L985), `networkInterfaces()` return type was updated from `Promise<Systeminformation.NetworkInterfacesData[]>` to `Promise<Systeminformation.NetworkInterfacesData[] | Systeminformation.NetworkInterfacesData>` with no apparent changes to implementation. 

Was this change really valid ? The current implementation seems to always return an Array of NetworkInterfacesData. Also the corresponding documentation was not updated.

Note that this breaks typescript compilation in code using the result directly as an array :
```
error TS2339: Property 'find' does not exist on type 'NetworkInterfacesData | NetworkInterfacesData[]'.
  Property 'find' does not exist on type 'NetworkInterfacesData'.
```

**Comment by sebhildebrandt** [comment]
@AltarBeastiful ... in the docs https://systeminformation.io/network.html there is a section __Get Default Interface only__ where you can call the function with the string `default`. Here the function returns just the default interface (not returned in an array).

I am not sure, where your error message occurs. Is it somewhere in your code where you try to find a specific interface?

I am aware that the current solution is not ideal. This will change in version 6 as ta change would be a breaking change.

**Comment by sebhildebrandt** [comment]
@AltarBeastiful closing it for now.

**Comment by Evilu** [comment]
> @AltarBeastiful ... in the docs https://systeminformation.io/network.html there is a section **Get Default Interface only** where you can call the function with the string `default`. Here the function returns just the default interface (not returned in an array).
> 
> I am not sure, where your error message occurs. Is it somewhere in your code where you try to find a specific interface?
> 
> I am aware that the current solution is not ideal. This will change in version 6 as ta change would be a breaking change.

Sorry for commenting in a closed issue,
 your suggested still won't solve the typing issues for me. 

`  const relevantNetwork = await si.networkInterfaces("default");

  const speedBytes = (relevantNetwork.speed * 1000000) / 8;
  //TS2339: Property 'speed' does not exist on type 'NetworkInterfacesData | NetworkInterfacesData[]'.   Property 'speed' does not exist on type 'NetworkInterfacesData[]'.
  `

**Comment by sebhildebrandt** [comment]
@Evilu ... I need to have a look at it. Will provide a fix as soon as possible (sorry for the inconvenience)

**Comment by sebhildebrandt** [comment]
@Evilu , when I am running this code:

```
const si = require('../systeminformation/lib/index.js');

si.networkInterfaces('default').then(data => {
    console.log(data);
})
```

I get:

```
{
  iface: 'en0',
  ifaceName: 'en0',
  default: true,
  ip4: '192.xxx.xxx.xxx',
  ip4subnet: '255.255.255.0',
  ip6: 'fe80::xxxx:xxxx:xxxx:xxxx',
  ip6subnet: 'ffff:ffff:ffff:ffff::',
  mac: 'xx:xx:xx:xx:xx:xx',
  internal: false,
  virtual: false,
  operstate: 'up',
  type: 'wireless',
  duplex: 'full',
  mtu: 1500,
  speed: 130.26,
  dhcp: true,
  dnsSuffix: '',
  ieee8021xAuth: '',
  ieee8021xState: '',
  carrierChanges: 0
}
```

So speed is actually there ... 

Having a look at the interface definition in index.d.ts we have:

```
interface NetworkInterfacesData {
    iface: string;
    ifaceName: string;
    default: boolean;
    ip4: string;
    ip4subnet: string;
    ip6: string;
    ip6subnet: string;
    mac: string;
    internal: boolean;
    virtual: boolean;
    operstate: string;
    type: string;
    duplex: string;
    mtu: number | null;
    speed: number | null;			<--------------
    dhcp: boolean;
    dnsSuffix: string;
    ieee8021xAuth: string;
    ieee8021xState: string;
    carrierChanges: number;
  }

export function networkInterfaces(
  cb?:
    | ((data: Systeminformation.NetworkInterfacesData[] | Systeminformation.NetworkInterfacesData) => any)
    | boolean
    | string,
  rescan?: boolean,
  defaultString?: string
): Promise<Systeminformation.NetworkInterfacesData[] | Systeminformation.NetworkInterfacesData>;
```

So I cannot spot, why we get this error ... do you have any idea?? 
On what OS are you running your code?

**Comment by sebhildebrandt** [comment]
@Evilu ... probably you heed to check, if your result is an array or not ...

```
const relevantNetwork = await si.networkInterfaces("default"); 
if (!Array.isArray(relevantNetwork)) {
    const speedBytes = (relevantNetwork.speed * 1000000) / 8;
}
```

**Comment by Evilu** [comment]
Good idea, also it'll probably shout about speed being null.
Thanks!

`  let speedBytes
  if (!Array.isArray(relevantNetwork) && relevantNetwork.speed) {
    speedBytes = (relevantNetwork.speed * 1000000) / 8;
  }`

**Comment by bwp91** [comment]
Hi, apologies from me for commenting on a closed issue too.

I am using this code:

```js
const networkInterfaces = (await si.networkInterfaces()).filter((adapter) => { ... });
```

and getting a type error

```
 error TS2339: Property 'filter' does not exist on type 'NetworkInterfacesData | NetworkInterfacesData[]'.
  Property 'filter' does not exist on type 'NetworkInterfacesData'.

const networkInterfaces = (await si.networkInterfaces()).filter((adapter) => {
```

Granted, I am not totally confident with typescript, but if networkInterfaces() is returning an array, then surely the filter method should exist? 

This started appearing when I go from: (but not sure which specific version it starts creating this ts error)

```
-    "systeminformation": "5.16.9",
+   "systeminformation": "^5.21.9",
```

Thanks for any input from anyone here!

**Comment by sebhildebrandt** [comment]
@bwp91 ... as it can be a single interface (e.g. when calling `si.networkInterfaces('default')`) OR an array, you need to check first if it is an array ... unfortunately I introduced this some time ago (forgetting to change also the types) and changing it to always return an array would be a breaking change (so a major version bump). In version 6 I corrected it besides some more breaking changes ... but this version is not yet ready and released.

**Comment by bwp91** [comment]
Hi @sebhildebrandt thank you for your quick reply, so just to clarify, if the `'default'` param isnt given, and the only network interfact is the default, this would still be returned as a single array of one object right?

**Comment by sebhildebrandt** [comment]
@bwp91 ... not really, if you have no parameter, you get an array ... but the typescript `types` reflect, that there can be two types of results and therefore it complains about the `.filter` (which would only be available in one of the two types of results) even we are in your case sure, that this is an array. But when you include this check, the typescript error will disappear.

**Comment by bwp91** [comment]
> if you have no parameter, you get an array

I think this what I am trying to confirm - forgetting any issues of typescript now - if I do NOT pass the `default` param, and the ONLY network interface found is the default, then this will be returned in an ARRAY of ONE result? rather than just an OBJECT?

Sorry for caps, is for clarification, not shouting 😁

**Comment by sebhildebrandt** [comment]
@bwp91 correct ... only if you provide the default param, you get an object (and not an array) ... No problem about the caps ;-) ... all fine ... I am sorry that I somehow messed it up with the two types of result. As said, this will be corrected in version 6.

**Comment by bwp91** [comment]
no worries at all appreciate your fast responses. and can just ts-ignore this until next release 😁

appreciate your work on this repo!
