### ISSUE TITLE
Providing a stream of information 

### ISSUE THREAD

**Issue by JijaProGamer** [sebhildebrandt/systeminformation#776]
Instead of calling the function to get the ram, cpu, and temp stats you could provide a stream (using passthrough stream for example).

I guess this wont be that hard, since top and sensors functions already can be set to update every second.

example usage:

let stream = si.getStream([“load”, “memory”, “temps”], 0.5) 

first argument being the events to trigger, and the second argument the interval

stream.on(“load”, load => console.log(load.cpu))

stream.on(“memory”, memory => console.log(memory.used))

stream.on(“temps”, temps => console.log(temps.cpu))

**Comment by sebhildebrandt** [comment]
@JijaProGamer ... for a few functions that might be possible but unfortunately not for most of them and especially not across all platforms. I have already thought about it but then discarded the idea due to the previously mentioned reasons.

**Comment by JijaProGamer** [comment]
Could I see a list of reasons for this being discarded?

**Comment by sebhildebrandt** [comment]
@JijaProGamer ... please read my comment above. As you mentioned, just a few functions (`top`, `sensors`) provide some results as a stream. This is not the case for most of the information this package returns. And on Windows things get even more complicated. Hope you understand why I am currently not considering to implement this. One more reason is, that I am currently rewriting the whole package (TS), adding a lot of more functions. As you can imagine, this is time consuming ;-)
Anyway I appreciate your idea and maybe in the future I will come up with some sort of an implementation.

Best Regards
