### ISSUE TITLE
Apple Mac M2 support?

### ISSUE THREAD

**Issue by techterbium** [sebhildebrandt/systeminformation#778]
**Is your feature request related to a problem? Please describe.**
This is more of a question - does this library work on Mac M2 systems?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I tried to run this library on a M2 mac and it fails silently.

**Comment by sebhildebrandt** [comment]
@techterbium what functions exactly do not work on M2? As far as I know all functions should work fine. Can you be more specific?

**Comment by techterbium** [comment]
I do not have M2 as well. One of my client is using electronJS app on a M2 and as per the logs, the app is unable to past the code which get the system information using `.system()` , `.mem()` and `.osInfo()` calls. Unfortunately, I cannot ask him to run tests on his machine.

**Comment by sebhildebrandt** [comment]
@techterbium ... we need to have tested the package itself on a M2 Mac to confirm that we have an issue here. As said, I do not see any reason why those functions should not work on M2 machines. I would close the issue for now. 

As soon as you (or anyone else) can confirm that the `systeminformation` package really has an issue, please feel free to reopen the ticket. 

One more thing. is your project anywhere available here on GitHub to have a look at the context how your are using the package inside electronJS?
