### ISSUE TITLE
Empty cpu flags on windows

### ISSUE THREAD

**Issue by Jelmerro** [sebhildebrandt/systeminformation#78]
I have been using the systeminformation library for an electron project,
and I'm trying to make a list of cpu flags.
However, the following code only works as expected on linux:
```
si.cpuFlags(function(data) {
    console.log(`flags: ${data}`);
});
```
On windows, data returns as an empty string, and I haven't tested mac.
Let me know if you could fix this, or if there's a reason it won't work on windows.

**Comment by sebhildebrandt** [comment]
Hi Jelmer,
yes, cpuFlags is currently unsupported for Windows (see documentation). I didn't found a way to determine CPU flags till now. But if you have any idea, that would be great. On OSX, Linux `cpuFlags()` is working fine.

**Comment by Jelmerro** [comment]
Hi Sebastian,
I figured it should be possible on windows as well,
so I made a quick implementation for it.
```javascript
let result = '';
if (_windows) {
  exec(`reg query "HKEY_LOCAL_MACHINE\\HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0" /v FeatureSet`, function (error, stdout) {
    if (!error) {
      let flag_hex = stdout.split("0x").pop().trim();
      let flag_bin_unpadded = parseInt(flag_hex, 16).toString(2);
      let flag_bin = "0".repeat(32 - flag_bin_unpadded.length) + flag_bin_unpadded;
      // empty flags are the reserved fields in the CPUID feature bit list
      // as found on wikipedia:
      // https://en.wikipedia.org/wiki/CPUID
      let all_flags = [
        "fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic",
        "", "sep", "mtrr", "pge", "mca", "cmov", "pat", "pse-36", "psn", "clfsh",
        "", "ds", "acpi", "mmx", "fxsr", "sse", "sse2", "ss", "htt", "tm", "ia64", "pbe"
      ]
      for (let f = 0; f < all_flags.length; f++) {
        if (flag_bin[f] === "1" && all_flags[f] !== "") {
          result += " " + all_flags[f];
        }
      }
      result = result.trim();
    }
    if (callback) { callback(result) }
    resolve(result);
  });
}
```
I tried to write the code in a similar way as the surrounding code,
but it can probably be improved/simplified.
Not sure if these are all the flags, but it should give you a basic idea how to get this done :wink:.

**Comment by sebhildebrandt** [comment]
Hi,

Thats GREAT! This is definitely the right direction! I will review it tomorrow and will publish a new version as soon as possible! Thank you so much for your contribution!

**Comment by sebhildebrandt** [comment]
Thank you once again! I added this partial flags support for windows in version 3.31.0. The Windows registry seems only to support the EDX CPUID feature bits. For sure, there are more flags (ECX) which is currently not supported and therefore not reflected in the `cpuFlags()` windows version
