### ISSUE TITLE
cpuTemperature not returning values Linux

### ISSUE THREAD

**Issue by Mailiax** [sebhildebrandt/systeminformation#787]
Running `cpuTemperature` on Linux (Fedora 37) returns `{ main: null, cores: [], max: null, socket: [], chipset: null }`. Any idea why? Already tried running as root and `lm-sensors` seems to work as it should.

**Comment by roddc** [comment]
I have found that the cpu temperature reports are located in /sys/class/hwmon/hwmon* in ubuntu 20.04

**Comment by roddc** [comment]
I have found that the cpu temperature reports are located in /sys/class/hwmon/hwmon* on ubuntu 20.04

**Comment by roddc** [comment]
It seems that AMD use 'Tctl' label for cpu temperature

**Comment by Mailiax** [comment]
Sorry for the late reply. Yes, I am using and AMD, specifically a Ryzen 7 5800x.

**Comment by HoreaM** [comment]
I'm also having the same issue with a Ryzen 5 3600x, if I can help in any way, please let me know.

**Comment by sebhildebrandt** [comment]
@Mailiax @HoreaM sorry for the delay! I was quite busy. Can you provide the output of the following command:

```
cat /sys/class/thermal/thermal_zone*/type  2>/dev/null; echo "-----"; cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null;

for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=${label%_*}_input; echo $(cat "$label")___$(cat "$value"); fi; done; done;

sensors
```

Thank you in advance!

**Comment by HoreaM** [comment]
> @Mailiax @HoreaM sorry for the delay! I was quite busy. Can you provide the output of the following commands:
> 
> ```
> cat /sys/class/thermal/thermal_zone*/type  2>/dev/null; echo "-----"; cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null;
> 
> for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=${label%_*}_input; echo $(cat "$label")___$(cat "$value"); fi; done; done;
> 
> sensors
> ```
> 
> Thank you in advance!

The output is as follows:
```
-----
Tctl___48500
Tccd1___40500
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +48.5°C
Tccd1:        +40.2°C
```
And thank you too!

**Comment by sebhildebrandt** [comment]
@HoreaM ... this is the output of which of the tree commands? Just to be sure ...

**Comment by HoreaM** [comment]
@sebhildebrandt sorry, I should have been more clear:
1st command:
```
cat /sys/class/thermal/thermal_zone*/type  2>/dev/null; echo "-----"; cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null;
```
Returns:
```
-----
```

2nd command:
```
for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=${label%_*}_input; echo $(cat "$label")___$(cat "$value"); fi; done; done;
```
Returns:
```
Tctl___39125
Tccd1___38250
```

3rd command:
```
sensors
```
Returns:
```
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +39.1°C
Tccd1:        +38.2°C
```

**Comment by sebhildebrandt** [comment]
@HoreaM thank you!! Can work with this ;-)

**Comment by sebhildebrandt** [comment]
@HoreaM I guess I have a small fix for that: can you do the following:

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

Then press "T" (capital T) to get temperature.

Press "q" to quit

If this shows now a temperature, we are fine ;-) Then I will release a new patch version.

**Comment by sebhildebrandt** [comment]
@HoreaM @Mailiax @roddc ... I have now implemented a fix that takes tctl (for AMD processors) into account. Version 5.21.2 just published.

**Comment by sebhildebrandt** [comment]
@HoreaM @Mailiax @roddc ... I have adopted it a little now, taking also `Tccd1` into account. This is the more accurate value (but does not exists in all kernel versions). So if `Tccd1` is available, it will take this value, otherwise `Tctl`. Would be great, if you can test it once again. Version 5.21.3 just released
