### ISSUE TITLE
Storage purgeable

### ISSUE THREAD

**Issue by coelhoadler** [sebhildebrandt/systeminformation#79]
Hi, 

How I know the purgeable space in my storage?

Tks

**Comment by sebhildebrandt** [comment]
Hi 

Two questions:

- what do you mean with "purgeable" storage
- what OS are you using

**Comment by coelhoadler** [comment]
Hi @sebhildebrandt, 

purgeable =free space on my disk.

I'm using: macOS High Sierra, version 10.13.

Thanks.

**Comment by sebhildebrandt** [comment]
Hi again,

to get the free space on disk run the following code:

```
const si = require('systeminformation');

si.fsSize()
	.then(data => {
		data.forEach(function (row) {
			console.log('FS: ' + row.fs);
			console.log('Size: ' + row.size);
			console.log('Used: ' + row.used);
			console.log('FREE: ' + (row.size - row.used));
		})
	})
	.catch(error => console.error(error));
```

This will return free space on all values. To get the total free space, you only need to sum up the values.

**Comment by coelhoadler** [comment]
Thank you very much @sebhildebrandt !
