### ISSUE TITLE
The "services" is typed wrong in type "DynamicData"

### ISSUE THREAD

**Issue by mburakdonmez** [sebhildebrandt/systeminformation#794]
**Describe the bug**
`services` is typed wrong in type `DynamicData`. It is typed as `ServicesData` whereas it should be an array of service data `ServicesData[]`

**To Reproduce**
Go into the index.d.ts
Checkout the `services` field in `DynamicData` type

**Comment by sebhildebrandt** [comment]
@mburakdonmez ... fixed. version 5.17.13 just released.
