### ISSUE TITLE
`osInfo` -> `getFQDN` function can print command not found error in console and report incorrect FQDN

### ISSUE THREAD

**Issue by AllySummers** [sebhildebrandt/systeminformation#796]
**Describe the bug**
When fetching the FQDN (in `getFQDN`, fetched as part of `osInfo`), on some Linux systems the command can return a command not found error.

The `fqdn` property, if not successfully retrieved from commands within the function, will also return a function instead of a string.

**To Reproduce**
1. used function 'osInfo' -> `getFQDN`
2. used the following code in the root of the `systeminformation` repo:
```js
// file.js
const {osInfo} = require('./lib/osinfo')

async function main() {
  console.log(await osInfo());
}

main();
```
3. run `node file.js`
4. see output below

**Current Output**
```
/bin/sh: line 1: hostname: command not found
{
  platform: 'linux',
  distro: 'Arch Linux',
  release: 'unknown',
  codename: '',
  kernel: '6.2.10-arch1-1',
  arch: 'x64',
  hostname: 'allys',
  fqdn: [Function: __node_internal_checkError] {
    [Symbol(Symbol.toPrimitive)]: [Function (anonymous)]
  },
  codepage: 'UTF-8',
  logofile: 'arch',
  serial: '<redacted>',
  build: 'rolling',
  servicepack: '',
  uefi: true
}
```

**Expected behavior**
If the FQDN is not able to be retrieved, it should not print any additional errors in the console. It should also match the types defined in `index.d.ts` and always return a string, instead of a function returning a string.

**Environment (please complete the following information):**
 - systeminformation package version: Tested on `5.17.12` and the latest master at the time of writing.
 - OS: Arch Linux (see above)
 - Hardware: Dell Precision 5570

**Additional context**
I will be creating a PR shortly to address the issues.

**Comment by sebhildebrandt** [comment]
@AllySummers thank you for your investigation. Fixed and version 5.17.17 just released.
