### ISSUE TITLE
Bios version always returns "Shuttl - 1072009" (On shuttle computers)

### ISSUE THREAD

**Issue by blieb** [sebhildebrandt/systeminformation#798]
**Describe the bug**
When I read out the Bios on different shuttle computers I always get "Shuttl - 1072009" as bios version. It stays the same even when I update the version of the bios. 

**To Reproduce**
const si = require('systeminformation');
si.bios().then(data => console.log(data['version']));

**Current Output**
Shuttl - 1072009

**Expected behavior**
It should output bios version: 1.03

**Environment (please complete the following information):**
 - systeminformation package version:
 - OS: Windows
 - Hardware: Different shuttle models

**Additional context**
I think version should be SMBIOSBIOSVersion. this shows the correct version number. but can't read this with the library at the moment. 
![Screenshot 2023-04-13 at 14 07 47](https://user-images.githubusercontent.com/540248/231754059-a42a503e-e6d4-418d-b64b-663b571a76fc.png)

**Comment by sebhildebrandt** [comment]
@blieb can you provide the full output of:

```
Get-CimInstance Win32_bios | fl
```

... on this specific machine?

**Comment by sebhildebrandt** [comment]
@blieb I provided a fix, can you test the latest version 5.18.13?

**Comment by blieb** [comment]
> @blieb I provided a fix, can you test the latest version 5.18.13?

We have tested it. It now shows the correct version number. Thanks for the update!
