### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by drbryce** [sebhildebrandt/systeminformation#80]
Hello friend,

Any plans to support freebsd (and other BSD flavors) in the future?

### Specifications 

- package version: 3.30.6
- operating system: FreeBSD 11
- hardware:

**Comment by sebhildebrandt** [comment]
Hi @drbryce,

yes, this is a quite good idea. I will make some investigation on it and provide a comment on that a little later (probably next week).

**Comment by sebhildebrandt** [comment]
@chair300 : working hard on FreeBSD implementation ... more work than I thought ;-) 
Hope to get a first version finished end of next week.

**Comment by sebhildebrandt** [comment]
So, I now implemented first partial FreeBSD support. In this first release I implemented aprox. 70% of all functions (see docs `README.md`).

I had to reimplement nearly every function ;-) but for most of them I only made some basic tests. 

It would be cool, if you can also test them. If you discover issues, please share your discoveries. If possible, please provide also the output of the underlying shell command (which you should find in the code). That would help me improve the implementation
