### ISSUE TITLE
A user interface for system-information

### ISSUE THREAD

**Issue by korkorran** [sebhildebrandt/systeminformation#801]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I'm always frustrated when I start a new Os to not have general information about my system. Sometimes it is unclear to me which devices are connected, which networks are actives, etc.. 
Some commands allow to do it but you have to know them properly or at least make some research on google to know how to do it.

**Describe the solution you'd like**
A graphical user interface based on system information. The interface should show a dozen of page, each one related to system information category. Perhaps to start a few page showing only usb and blutooth devices can be a nice workaround.

**Describe alternatives you've considered**
A few months ago, I have started a new project, Systeminformation GUI, that I have left since
[Systeminformation-GUI](https://github.com/frederic-lang/systeminformation-GUI)

This is an basic electron app implemented with react that show information returned by systeminformation.js

**Additional context**
Do you support this kind of initiative or you think systeminformation should not be used in a GUI as a library. In this case the GUI is a more a wrapper of systeminformation than something really new

**Comment by sebhildebrandt** [comment]
Hi @frederic-lang ... thank you for your initiative here! Of course this is fine. I also thought of creating a project like this but currently working on the package itself consumes a lot of time. And I am about re release a new version 6.0 (rewritten in TypeScript) ... so feel free to continue. And any feedback is of course welcome!
