### ISSUE TITLE
Some duplicate values in network.js/testVirtualNic/virtualMacs?

### ISSUE THREAD

**Issue by ffiirree** [sebhildebrandt/systeminformation#803]
**Describe the bug**
There are some duplicate values, such as '00:0F:4B', '00:21:F6' and '00:24:0B', in network.js/testVirtualNic/virtualMacs.
And `mac.toUpperCase().toUpperCase().startsWith`?

**To Reproduce**
network.js/testVirtualNic/virtualMacs

**Comment by sebhildebrandt** [comment]
@ffiirree thank you for reporting. Fixed. Version 5.18.1 just published.
