### ISSUE TITLE
PowerShell processes hanging due to user profile script

### ISSUE THREAD

**Issue by hanfangAmazon** [sebhildebrandt/systeminformation#805]
**Describe the bug**
When we start a PowerShell session, it typically loads a profile script, which is a script that runs every time you start a session. This script usually sets up your environment, defining functions, variables, aliases, and so on.

However, when running a script in a production environment, we might want to ensure that it's not affected by anything in the user's profile.

Sometimes profile script can take forever to load, and cause all PowerShell processes to hang. 

**To Reproduce**
1. Create a profile script with infinite loop
2. Run some queries from systeminformation

**Current Output**
PowerShell processes hang forever

**Expected behavior**
PowerShell processes are not affected by profile script

**Environment (please complete the following information):**
 - systeminformation package version: 5.17.12
 - OS: Windows

**Comment by hanfangAmazon** [comment]
The `-NoProfile` parameter in PowerShell is used to prevent the loading of user profile scripts when starting the PowerShell environment. 
We can add it to
https://github.com/sebhildebrandt/systeminformation/blob/master/lib/util.js#L380
https://github.com/sebhildebrandt/systeminformation/blob/master/lib/util.js#L453

**Comment by schontz** [comment]
I haven't tested this, but my profile takes ~4 seconds to load because of all my configs. I think skipping profile is a good idea.

**Comment by hanfangAmazon** [comment]
PR: https://github.com/sebhildebrandt/systeminformation/pull/806

**Comment by sebhildebrandt** [comment]
powershell() added NoProfile to speed up powershell ... Version 5.17.15 just published.
