### ISSUE TITLE
`systeminformation.osInfo` macos version with ProductVersionExtra is not correct

### ISSUE THREAD

**Issue by Ikalli** [sebhildebrandt/systeminformation#809]
**Describe the bug**
`systeminformation.osInfo().release` is incorrect in macos with `ProductExtraVersion`

1. I entered `sw_vers; sysctl kern.ostype kern.osrelease kern.osrevision kern.uuid`
    - refer to: https://github.com/sebhildebrandt/systeminformation/blob/master/lib/osinfo.js#LL288C15-L288C83
2. Output:
   ```
    ProductName:            macOS
    ProductVersion:         13.3.1
    ProductVersionExtra:    (a)
    BuildVersion:           22E772610a
    kern.ostype: Darwin
    kern.osrelease: 22.4.0
    kern.osrevision: 199506
    kern.uuid: some_uuid
   ```
3. `getValue()` works weird. This function needs to stop iteration when matched with `ProductVersion`, but it returns value of `ProductVersionExtra` because of `forEach` iteration
    - refer to: https://github.com/sebhildebrandt/systeminformation/blob/master/lib/util.js#L116

**To Reproduce**
1. used function 'osInfo'
3. code snippet
    ```ts
       import systeminformation from 'systeminformation';
       
       const getInfo = async () => {
         const result = await systeminformation.osInfo();
         console.log(result.release);
       };
       
       getInfo();
4. start code
5. See output

**Current Output**
`(a)`

**Expected behavior**
`13.3.1` or `13.3.1 (a)`

**Environment (please complete the following information):**
 - systeminformation package version: 5.17.12
 - OS: macOS
 - Hardware [e.g. MacBook Pro 13]
    - MacBook Air M2, 2022
    - Apple M2 Chip
    - 16GB Memory
    - macOS 13.3.1 (a)
    - build: 22E772610a

**Comment by sebhildebrandt** [comment]
@Ikalli  Thank you for your information! Fixed ...version 5.17.14 just released.
