### ISSUE TITLE
Graphics result incorrect

### ISSUE THREAD

**Issue by Jelmerro** [sebhildebrandt/systeminformation#81]
#### Expected

- Correct vendor and model

#### Actual

```json
bus: ""
model: "icro Devices, Inc. [AMD/ATI] Cape Verde PRO [Radeon HD 7750/8740 / R7 250E] "
vendor: "Advanced M"
vram: 256
vramDynamic: false
```

### Steps to reproduce the problem.

- call `si.graphics` on mint with mesa

### Specifications 

- package version: 3.30.4
- operating system: mint 18 (based on ubuntu 16.04)
- hardware: amd 7750 graphics card

The model and vendor are clearly wrong.
Worth mentioning, is that I'm using the mesa graphics driver.
All other systems I have tested seem to work as expected (couple of windows systems and my laptop with mint 18).

### Problem and possible solution

Looking at the code here, https://github.com/sebhildebrandt/systeminformation/blob/master/lib/graphics.js#L140
the library seems to assume the string contains Corporation,
which in this case it doesn't.

The only reason I'm still getting the fields filled with data,
is because the if statement here:
https://github.com/sebhildebrandt/systeminformation/blob/master/lib/graphics.js#L139
is not correct.
Because: indexOf returns an int (-1 if no match is found),
which means the if statement is always true, unless the index would be 0.

A solution could be, to change it to something like this:
```javascript
if (parts[1].toLowerCase().indexOf('corporation') === -1) {
  // code when no corporation was found in the gpu string
} else {
  // code when corporation was found, the current code inside the if could go here
}
```

**Comment by Jelmerro** [comment]
Also, the model is not trimmed again after is it split with `split('(')[0]`,
hence the trailing space in the model string.

**Comment by sebhildebrandt** [comment]
Thank you Jelmer,

I will check this and provide a solution this weekend.

**Comment by Jelmerro** [comment]
Also, on my laptop the vendor and model are correct,
because it contains corporation (although the model still with a space at the end of course).
But it only finds the integrated gpu and not the dedicated one.
I checked the code and it only checks for "VGA",
but on my laptop the dedicated gpu starts with "3D controller".
Example:
`04:00.0 3D controller: NVIDIA Corporation GK107M [GeForce GT 745M] (rev a1)`

**Comment by sebhildebrandt** [comment]
Hi again,

I just published a new version 3.31.2 which should solve both problems. Can you test it on your machines?

Thank you in advance

**Comment by Jelmerro** [comment]
This looks much better, although

**Comment by Jelmerro** [comment]
I tried it on my laptop, it now also finds the dedicated gpu and not only the integrated intel gpu.
However, the result is pretty empty.
![laptop](https://user-images.githubusercontent.com/1696674/31794065-533dab9a-b521-11e7-9632-c0d70e2f2e03.png)
I think this is probably a separate issue.
A simple fix would be to actually use the _3dcontrollerpos string.
Right here https://github.com/sebhildebrandt/systeminformation/blob/43cde28685bb350435c2467b051d2454d348c1b0/lib/graphics.js#L135 vgapos is used to find a substring, but _3dcontrollerpos isn't used there.
This could be solved by adding this:
```javascript
if (_3dcontrollerpos !== -1) {
  vgapos = _3dcontrollerpos;
}
```
directly above what is currently line 135 (in the snippet).
When added, the output works as expected (although still with trailing spaces 😄):
![laptop2](https://user-images.githubusercontent.com/1696674/31794429-99e5c3a6-b522-11e7-9eb6-45e170b19a09.png)

**Comment by sebhildebrandt** [comment]
You are so right! Sorry, didn't tested it ... Will push a bugfix tomorrow. Thank you so much!

**Comment by sebhildebrandt** [comment]
I yesterday published a bugfix for that. Once again sorry for my incorrect implementation ...
