### ISSUE TITLE
Key "default" missing from network interface data / TypeScript

### ISSUE THREAD

**Issue by Choppel** [sebhildebrandt/systeminformation#810]
**Describe the bug**
The interfaces returned by `await networkInterfaces();` include a key "default" to show whether the interface is the default interface or not. However, the typescript definition is missing this key.

**Current Output**
TS2339: Property 'default' does not exist on type 'NetworkInterfacesData'.

**Expected behavior**
The key should be a valid boolean in the type definition.

**Comment by sebhildebrandt** [comment]
@Choppel will fix it today ... sorry!

**Comment by sebhildebrandt** [comment]
@Choppel ... fixed. version 5.17.13 just released.
