### ISSUE TITLE
Incorrect l1 l2 cache data on i7-13700KF

### ISSUE THREAD

**Issue by Intro1997** [sebhildebrandt/systeminformation#813]
**Describe the bug**
I use cpuCache() api to get cpu cache and got following data:
```
{ l1d: 256, l1i: 512, l2: 8388608, l3: 31457280 }
```
As the description in https://systeminformation.io/cpu.html, the L1 data cache is 256 bytes and L1 instruction cache is 512 bytes. But I found that Task manager shows 1.4MB in L1 cache:
![Windows Task Manager0](https://github.com/sebhildebrandt/systeminformation/assets/29827323/289180f6-5d85-427f-9314-d0d8cb3733e8)
I try to read code and find the data come from "Get-CimInstance Win32_CacheMemory" command in PowerShell. Then I try this command in PowerShell and get the following data:
```
BlockSize      : 1024
CacheSpeed     :
CacheType      : 4
DeviceID       : Cache Memory 0
InstalledSize  : 384
Level          : 3
MaxCacheSize   : 384
NumberOfBlocks : 384
Status         : OK

BlockSize      : 1024
CacheSpeed     :
CacheType      : 3
DeviceID       : Cache Memory 1
InstalledSize  : 256
Level          : 3
MaxCacheSize   : 256
NumberOfBlocks : 256
Status         : OK

BlockSize      : 1024
CacheSpeed     :
CacheType      : 5
DeviceID       : Cache Memory 2
InstalledSize  : 16384
Level          : 4
MaxCacheSize   : 16384
NumberOfBlocks : 16384
Status         : OK

BlockSize      : 1024
CacheSpeed     :
CacheType      : 5
DeviceID       : Cache Memory 3
InstalledSize  : 30720
Level          : 5
MaxCacheSize   : 30720
NumberOfBlocks : 30720
Status         : OK

BlockSize      : 1024
CacheSpeed     :
CacheType      : 4
DeviceID       : Cache Memory 4
InstalledSize  : 256
Level          : 3
MaxCacheSize   : 256
NumberOfBlocks : 256
Status         : OK

BlockSize      : 1024
CacheSpeed     :
CacheType      : 3
DeviceID       : Cache Memory 5
InstalledSize  : 512
Level          : 3
MaxCacheSize   : 512
NumberOfBlocks : 512
Status         : OK

BlockSize      : 1024
CacheSpeed     :
CacheType      : 5
DeviceID       : Cache Memory 6
InstalledSize  : 8192
Level          : 4
MaxCacheSize   : 8192
NumberOfBlocks : 8192
Status         : OK

BlockSize      : 1024
CacheSpeed     :
CacheType      : 5
DeviceID       : Cache Memory 7
InstalledSize  : 30720
Level          : 5
MaxCacheSize   : 30720
NumberOfBlocks : 30720
Status         : OK
```
After comparing with the previous screenshot I found that the unit of output data in PowerShell is KBytes (The Cache Memory 7 should be L3 cache memory and the size is 30720). 
I also comparing the output data in PowerShell with CPU-Z:
![CPU-Z0](https://github.com/sebhildebrandt/systeminformation/assets/29827323/bf655328-acd4-4331-b027-bb6d573bc0a4)
I found that Cache Memory 0's size in PowerShell equals to the 8*48KB in CPU-Z L1 Data:
![CPU-Z1](https://github.com/sebhildebrandt/systeminformation/assets/29827323/443c7566-a9ab-4071-9a1b-780451c19bc4)
The same goes for other data.

**To Reproduce**
Run following code can reproduce:
```javascript
const si = require('systeminformation');
si.cpuCache().then(data => console.log(data));
```

**Current Output**
The L3 cache data is correct
```
{ l1d: 256, l1i: 512, l2: 8388608, l3: 31457280 }
```

**Expected behavior**
The l1d output should be (384+256) * 1024 = 655360
The l1i output should be (256+512) * 1024 = 786432
The l2 output should be (16384+8192) * 1024 = 25165824
```
{ l1d: 655360, l1i: 786432, l2: 25165824, l3: 31457280 }
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.17.16
 - OS: Windows11 Pro 22H2 22621.1702
 - Hardware: i7-13700KF
 - PowerShell: 
 ```
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 ```

**Comment by sebhildebrandt** [comment]
@Intro1997 thank you for reporting. I have to make further investigations on one of my machines and will come back with a solution. If I have further questions, I will contact you, OK?

**Comment by Intro1997** [comment]
Ok, thanks for your reply! I'm looking forward to your solution!

**Comment by sebhildebrandt** [comment]
@Intro1997 ... I refactored the part getting cache information for windows but I am not able to test it right now. Can you check the current master branch?

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

Then press "c" for CPU information ... can you post the results?

**Comment by Intro1997** [comment]
![image](https://github.com/sebhildebrandt/systeminformation/assets/29827323/44a45966-cfab-48c4-88d9-06d2ea5a4a2d)
It's correct now! Thanks for fixing it!

**Comment by sebhildebrandt** [comment]
@Intro1997 ... thank you for testing! Version 5.18.10 just released
