### ISSUE TITLE
Temps coming back as integer, not float

### ISSUE THREAD

**Issue by JoePShoulak** [sebhildebrandt/systeminformation#814]
**Describe the bug**
When running `si.cpu()` and parsing the result, the speeds are reported as integers and not floats. Or at least, they have no decimal points and are all the same value. 

**To Reproduce**
```javascript
const si = require("systeminformation");

si.cpu()
  .then(data => {
    const { speed, speedMin, speedMax } = data;
    console.log({ speed, speedMin, speedMax });
  })
  .catch(error => {
    console.error(error);
  });
``` 

**Current Output**
```bash
$ node info-test.js 
{ speed: 3, speedMin: 3, speedMax: 3 }
```

**Expected behavior**
I would expect these to be floats, like `3.2`, `3.4`, and `3.7`

**Environment (please complete the following information):**
 - systeminformation package version: 5.17.16z
 - OS: Windows 11 v10.0.22621
 - Hardware: Custom Build PC
   - Motherboard: ASRock Z790 Pro RS
   - CPU: Intel Core i9-13900K

**Additional context**
I'm also having issues with [CPU temps returning null](https://github.com/sebhildebrandt/systeminformation/issues/480)

**Comment by sebhildebrandt** [comment]
So in windows, the speed is determined by querying `Win32_processor` and the result is a constant value and does not reflect the current speed of the processor. In your case this value is 3.0 which is (as a number) 3 ... hope this clarifies the issue. But just to be sure: can you provide the output of:

From PowerShell
```
Get-CimInstance Win32_processor | select Name, Revision, L2CacheSize, L3CacheSize, Manufacturer, MaxClockSpeed, Description, UpgradeMethod, Caption, NumberOfLogicalProcessors, NumberOfCores | fl
```

**Comment by sebhildebrandt** [comment]
@JoePShoulak ... I provided an answer without referencing your name - please have a look on GitHub ;-) ... sorry

**Comment by JoePShoulak** [comment]
@sebhildebrandt No problem, thank you for your response! So what is the proper way to query the current speed of the processor, if that's available? 

I like this tool a lot, I'm trying to make a local web server I can run to view some of my sys info on a tablet near my PC! 

I'm also curious, the only other property I'd like to find but seem to be missing is GPU usage, is that available using this API?

Here's the code output you requested:
```shell
Name                      : 13th Gen Intel(R) Core(TM) i9-13900K
Revision                  :
L2CacheSize               : 16384
L3CacheSize               : 36864
Manufacturer              : GenuineIntel
MaxClockSpeed             : 3000
Description               : Intel64 Family 6 Model 183 Stepping 1
UpgradeMethod             : 1
Caption                   : Intel64 Family 6 Model 183 Stepping 1
NumberOfLogicalProcessors : 32
NumberOfCores             : 24
```

**Comment by sebhildebrandt** [comment]
@JoePShoulak ... as you can see: max clock speed is 3000 (MHz) which is then 3 GHz ... 

As Windows does not provide that much detailed information for CPU and GPU like other platforms, we are kind of limited here. The only option would be to write a bunch of C code (which then needs to be adapted for all hardware variations). This is not what we intended to do. 

For Linux and Mac OS the information you would get is much more accurate as those operating systems provide much more possibilities to gather system information.

Closing this issue for now. But if you have any further questions, do not hesitate to open a new issue.
