### ISSUE TITLE
spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by schontz** [sebhildebrandt/systeminformation#817]
**Describe the bug**
Getting an `ENOBUFS` error that crashes the application when the output exceeds the [buffer size allotted to spawnSync](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options). 

**To Reproduce**
I'm not sure the exact command, but the error is being thrown on [graphics.js#L672](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/graphics.js#L672). I asked the user to run `wc -c` on those commands, and the second command returns 1,118,110 bytes, which is larger than the `maxBuffer` default size of 1024 * 1024.

**Current Output**
Application crashes with ENOBUFS error.

**Expected behavior**
Application does not crash

**Environment (please complete the following information):**
 - systeminformation package version:5.17.12
 - OS: macOS 13.4
 - Hardware: Apple M2 Max

**Additional context**
In this case, bumping `maxBuffer` would alleviate the issue, but I might suggest a promise-based wrapper on spawn that does not suffer from this issue, so you do not need to deal with buffer sizes at all, e.g.:

```javascript
// sample code, not tested
function spawnAsync(cmd, args, opts) {
  return new Promise((resolve) => {
    let stdout = '', stderr = '';
    const proc = spawn(cmd, args, opts);
    proc.stdout.on('data', (data) => stdout += data);
    proc.stderr.on('data', (data) => stderr += data);
    proc.on('close', (code) => resolve({ stdout, stderr, code }));
  });
}
```

**Comment by sebhildebrandt** [comment]
@schontz  ... fixed. thank you! Version 5.18.3 just published
I am thinking of replacing all execs with spawns for the next major version.
