### ISSUE TITLE
dockerContainerStats('*') does not return all containers

### ISSUE THREAD

**Issue by Adeloyd** [sebhildebrandt/systeminformation#820]
**Describe the bug**
dockerContainerStats('*') does not return all containers stats

**To Reproduce**
1) Bad code  
const containersStats = await si.dockerContainerStats('*');

2) Working code
   const  containersList = await si.dockerContainers();
   const containersIds = [];
   for(let container of containersList) {
        containersIds.push(container.id.substring(0,12));
    }
    const containersStats = await si.dockerContainerStats(containersIds.join());

**Environment (please complete the following information):**
 - systeminformation package version:
 - systeminformation: "^5.17.12"
 - OS: Ubuntu 22
 - Docker version 20.10.23, build 7155243]

**Comment by Adeloyd** [comment]
This is because Docker sometimes returns IDs of different lengths when getting a list of containers and container statistics.

**Comment by sebhildebrandt** [comment]
@Adeloyd thank you for reporting. As I was not able to reproduce this, can you provide the output of:

```
const si = require('systeminformation');

const containersList = await si.dockerContainers();
for(let container of containersList) {
    console.log('-' + container.id + '-');
}
```

Thank you in advance!

**Comment by Adeloyd** [comment]
@sebhildebrandt I have 100-300 new containers launched every day. This error appeared 2 times in a month and I was able to solve it only when it appeared. There is currently no way to show the error.

**Comment by sebhildebrandt** [comment]
@Adeloyd seems that only the `exited` containers are not shown. Can you confirm this?

**Comment by sebhildebrandt** [comment]
@Adeloyd ... fixed. Version 5.18.4 just released.
