### ISSUE TITLE
Exception 'Cannot use 'in' operator to search for 'BitsPerPixel' in 1' crash the app

### ISSUE THREAD

**Issue by notsecret808** [sebhildebrandt/systeminformation#821]
**Describe the bug**
Exception **`Cannot use 'in' operator to search for 'BitsPerPixel' in 1`** in  'graphics' module sometimes crash the app.

**To Reproduce**
Code line where the exception is thrown:
https://github.com/sebhildebrandt/systeminformation/blob/9f56a268e854bc7d61ed411728aa32297c538069/lib/graphics.js#L698

**Current Output**
`TypeError: Cannot use 'in' operator to search for 'BitsPerPixel' in 1`

**Environment (please complete the following information):**
 - systeminformation package version: 5.17.9
 - OS: macOS 13.3.1

**Comment by sebhildebrandt** [comment]
@notsecret808 can you provide the output ( as text) from this command (terminal):

```
defaults read /Library/Preferences/com.apple.windowserver.plist 2>/dev/null;defaults read /Library/Preferences/com.apple.windowserver.displays.plist 2>/dev/null; echo ""
```

**Comment by sebhildebrandt** [comment]
@notsecret808 can you also provide, what machine you are running on (what type of Mac and Intel or which M1/M2 CPU)?

I also provided a small fix and pushed it to the master branch. So if possible, can you also (besides providing the output above), test this:

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

Then press `g` and post the output

**Comment by sebhildebrandt** [comment]
@notsecret808  Ok, will test my fix here on one of my Intel Macs ...

**Comment by sebhildebrandt** [comment]
@notsecret808 I fixed it and it should work now also if unexpected object values are returned from graphics JSON. Version 5.18.4 just published
