### ISSUE TITLE
cpu() function is not working on arm64 MacOS virtual machines

### ISSUE THREAD

**Issue by ArgishtiAyvazyan** [sebhildebrandt/systeminformation#824]
**Describe the bug**
I have setup macOS virtual machine based on arm64 arch. In this setup I have 2 CPUs and there is no categorization performance and efficiency. That causes this command fail ('`ioreg -c IOPlatformDevice -d 3 -r | grep cluster-type`').

https://github.com/sebhildebrandt/systeminformation/blob/f1eb82d4b79f41115a3c1928ce314c440a2eb1ed/lib/cpu.js#L647)

The part `'ioreg -c IOPlatformDevice -d 3 -r'`  works as expected but `'grep cluster-type`' fails because of no match (additional [info](https://stackoverflow.com/questions/57788813/grep-return-0-if-no-match#:~:text=If%20there's%20no%20match%2C%20that,zero%20if%20it%20does%20not.)).

There are 2 problems:
- The functionality does not work
- There is no mechanism to capture this error and handle it (exception or something like that)

**To Reproduce**
1. used function ' si.cpu()'
2. code snippet '
```js
import si from 'systeminformation';

const dumpCpuInfo = async () => {
    const cpu = await si.cpu();
    console.log(cpu);
};

dumpCpuInfo();
```
'
3. start app / code
4. See output/error 'Command failed: ioreg -c IOPlatformDevice -d 3 -r | grep cluster-type'

**Current Output**
-

**Expected behavior**
Return information about CPUs otherwise throw exception

**Environment (please complete the following information):**
 - systeminformation package version: 5.9.4
 - OS: macOS, arm64
 - Hardware: macOS Virtual machine

**Additional context**

**Comment by sebhildebrandt** [comment]
@ArgishtiAyvazyan should be fixed already ... can you test it in the current version?

**Comment by ArgishtiAyvazyan** [comment]
@sebhildebrandt I tested it and it works. Thank you for responding so quickly.
