### ISSUE TITLE
Missing osInfo.distro on Windows 7

### ISSUE THREAD

**Issue by SanArGuz** [sebhildebrandt/systeminformation#825]
**Describe the bug**
On Windows 7 devices there is no info returning when calling osInfo.distro, it seems to be that Windows 7 doesn't recognize the PowerShell command `Get-CimInstance Win32_OperatingSystem | select Caption,SerialNumber,BuildNumber,ServicePackMajorVersion,ServicePackMinorVersion | fl`

OUTPUT: 

The term 'Get-CimInstance' is not recognized as a name of a cmdlet, function

But it works well with the command:

`Get-WmiObject Win32_OperatingSystem | select Caption,SerialNumber,BuildNumber,ServicePackMajorVersion,ServicePackMinorVersion | fl`

OUTPUT

Caption                 : Microsoft Windows 7 Professional 
SerialNumber            : 00371-***
BuildNumber             : 7601
ServicePackMajorVersion : 1
ServicePackMinorVersion : 0

**Environment (please complete the following information):**
 - systeminformation package version: 5.18.6
 - OS: Windows 7

**Comment by sebhildebrandt** [comment]
@SanArGuz I switched from `Get-WmiObject` to `Get-CimInstance` in all commands due to security concerns of several users. It should be supported in Powershell 3.0 and above. Which powershell version is running on your machine?

**Comment by SanArGuz** [comment]
I'm using PowerShell 2.0

**Comment by sebhildebrandt** [comment]
Ok, so as we had to move to `Get-CimInstance`, this is only supported in Powershell 3.0 and above. Microsoft anyway has ended their support of Windows 7 and Powershell 2.0 in January 2020 (after 10 years). So I am afraid, currently we are also not supporting it any longer.
