### ISSUE TITLE
Does the docker container needs to install nodejs separately?

### ISSUE THREAD

**Issue by varshadqz** [sebhildebrandt/systeminformation#826]
I want to run the Linux docker container with the asp net core project which runs this library and gives system metrics. I have a requirement that Nodejs and related package things should be used from the host, which means I do not need to install the Nodejs in the container separately. Is this possible? 
I tried to run the docker command by using volume like this: 
` docker run -dit -p 8085:44319 -v D:\Projects\SystemInformation\SystemInformation:/app/node --name systemmetrics_4 metric:latest`

But this does not work.

**Comment by sebhildebrandt** [comment]
@varshadqz I am not sure if I understand your question ... 

- which is the HOST machine and the OS on that machine
- where would you like to run the app using systeminformation (on the host or inside the container?)
- the node app, is it exposing an API or what?

Maybe it would be easier if you provide a small graph, that I can easier understand.

**Comment by varshadqz** [comment]
1. The host machine is Windows 11, on the same machine, I have a docker desktop installed.
2. Need to run the app inside the Linux container.
3. App is asp net core, it is exposing restful API which returns the system metrics. 
Let me know if I need to give more information.
I just want to test if the container can use the Nodejs package service from the Windows host machine or need to install separately inside the container.

**Comment by sebhildebrandt** [comment]
@varshadqz so 

- in your docker container, you are running your app that is gathering system metrics, wight?
- this app exposes an API
- you can access this API from outside?

What is unclear to me:
- you want to use node and the package from outside the docker container, so this means from the host?
- this would mean, you need an app on the host. 
- which then is not what you want??
- one more thing: from inside docker, due to security reasons, you do not get the full system metrics

I am still not sure, what you want to achieve ...

**Comment by varshadqz** [comment]
I was trying to achieve, 
1. Run the docker container which exposes the API to get the host machine's system metrics.
2. Will Access the API from inside the container.
3. you want to use node and the package from outside the docker container, so this means from the host? ==> yes
4. this would mean, you need an app on the host. => Okay, I was hoping the app inside a docker container.
Do you mean if I need the host machine's system metrics then the app should be run on the host machine?

**Comment by sebhildebrandt** [comment]
@varshadqz here some things you should consider:

1. have you tried to spin up a docker container with node (e.g. alpine-node) with interactive shell and clone the package and then run `npm run test`... here you would see what system metrics you can see from inside a docker container. As said, this is limited.
2. if you want to use your "node.exe" from outside ... how should this work??? And as this is independent from the package here, you can of course try again the same with an interactive docker container and try to access node that lies outside the container. I do not see how any LINUX container could run a WINDOWS node executable.
3. running docker container is about having an isolated (and predictable) environment. So your concept does not really make sense - at least from my point of view

Closing it for now
