### ISSUE TITLE
remote sensing

### ISSUE THREAD

**Issue by st3b1t** [sebhildebrandt/systeminformation#827]
I am using this great library in a project to monitor the resources of a *nix machine.
Is there any way to measure with SI the resources on a different remote machine(where Nodejs is not installed)? 

Expanding some port remotely? or with tools like netcat,ncat,telnet or other?

**Comment by sebhildebrandt** [comment]
Hi @st3b1t 

The functionality you describe is currently not available. This would be something like in windows WMI remote connections. As far as I know, this is not available in *nix systems. 

This npm package is intended to run only locally with node installed. To be able to get detailed system information on remote *nix machines, you would need to run some kind of local code (node, bash, …) and then a channel to send this to the master. If you are planning to use systeminformation, you need node installed don the remote machine.
