### ISSUE TITLE
how to get graphics() data from wsl2 

### ISSUE THREAD

**Issue by log901108** [sebhildebrandt/systeminformation#829]
**Is your feature request related to a problem? Please describe.**

When using si.graphics() from wsl2 I got data output below. It seems because of wsl2 

output:
{"success":true,"data":{"controllers":[{"vendor":"Microsoft Corporation","model":"Device 008e","bus":"Onboard","busAddress":"c584:00:00.0","vram":null,"vramDynamic":false,"pciID":""}],"displays":[{"vendor":"","model":"","deviceName":"","main":false,"builtin":false,"connection":"XWAYLAND0","sizeX":null,"sizeY":null,"pixelDepth":null,"resolutionX":null,"resolutionY":null,"currentResX":1920,"currentResY":1080,"positionX":0,"positionY":0,"currentRefreshRate":59},{"vendor":"","model":"","main":false,"builtin":false,"connection":"XWAYLAND5","sizeX":null,"sizeY":null,"pixelDepth":null,"resolutionX":null,"resolutionY":null,"currentResX":1920,"currentResY":1080,"positionX":0,"positionY":0,"currentRefreshRate":59},{"vendor":"","model":"","main":false,"builtin":false,"connection":"XWAYLAND6","sizeX":null,"sizeY":null,"pixelDepth":null,"resolutionX":null,"resolutionY":null,"currentResX":1048,"currentResY":1680,"positionX":0,"positionY":0,"currentRefreshRate":59}]}}

**Describe the solution you'd like**
I don't know how to fix it

**Comment by log901108** [comment]
@sebhildebrandt Thank you for your concerns.
The result of command on my wsl2 terminal, you gave:'lspci -vvv  2>/dev/null', is below:

0a57:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 29318492
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at bffe18000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at bffe19000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at bffe1a000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

37c2:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 4081619178
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at 9ffe04000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at 9ffe05000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at 9ffe06000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

709d:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 3065329499
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at bffe20000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at bffe21000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at bffe22000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

7517:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 1158723290
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at bffe1c000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at bffe1d000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at bffe1e000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

78cc:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio console (rev 01)
        Subsystem: Red Hat, Inc. Virtio console
        Physical Slot: 3057868969
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at 9ffe00000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at 9ffe01000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at 9ffe02000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

8eb6:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 1975019411
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at 9ffe0c000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at 9ffe0d000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at 9ffe0e000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

967a:00:00.0 System peripheral: Red Hat, Inc. Virtio file system (rev 01)
        Subsystem: Red Hat, Inc. Virtio file system
        Physical Slot: 778661122
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at e00000000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at e00001000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at c00000000 (64-bit, non-prefetchable) [size=8G]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

a117:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 1050363034
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at 9ffe08000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at 9ffe09000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at 9ffe0a000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

a267:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 779705932
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at bffe14000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at bffe15000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at bffe16000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

c584:00:00.0 3D controller: Microsoft Corporation Device 008e
        Physical Slot: 3288037103
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Capabilities: <access denied>
        Kernel driver in use: dxgkrnl

fdbf:00:00.0 SCSI storage controller: Red Hat, Inc. Virtio filesystem (rev 01)
        Subsystem: Red Hat, Inc. Virtio filesystem
        Physical Slot: 3614163794
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 64
        Region 0: Memory at bffe10000 (64-bit, non-prefetchable) [size=4K]
        Region 2: Memory at bffe11000 (64-bit, non-prefetchable) [size=4K]
        Region 4: Memory at bffe12000 (64-bit, non-prefetchable) [size=4K]
        Capabilities: <access denied>
        Kernel driver in use: virtio-pci

**Comment by sebhildebrandt** [comment]
@log901108 can you also provide information for:

```
dmidecode -t 9
```

As WSL2 is kind of "headless", so no graphics environment (x-windows, Wayland, ...) etc, it would make sense that it does not know about displays.

**Comment by sebhildebrandt** [comment]
@log901108 currently I do not have access to my windows machine. For the next 2 weeks I have just an emulation on Mac ARM, here wsl2 does not work ;-)

**Comment by log901108** [comment]
@sebhildebrandt 

sudo dmidecode -t 9 gives output below: 

# dmidecode 3.3
Scanning /dev/mem for entry point.
# No SMBIOS nor DMI entry point found, sorry.

**Comment by sebhildebrandt** [comment]
@log901108 so as I suspected: wsl2 is a headless virtual machine with no graphical interface. And this is the reason, why we do not get any information here. Closing it for now.
