### ISSUE TITLE
fsSize() [x].rw is null on WIndows (not reflected in docs)

### ISSUE THREAD

**Issue by 4S1ght** [sebhildebrandt/systeminformation#833]
**Describe the bug**
On Windows, systeminformation is using the `Get-WmiObject Win32_logicaldisk | select Caption,FileSystem,FreeSpace,Size | fl` command to gather information for `fsSize` but it doesn't seem to return any information about read/write permissions for the drives
![image](https://github.com/sebhildebrandt/systeminformation/assets/116753476/0ef39068-0d42-488f-8683-a7138396bf69)

When reading the `[x].rw` prop on any objects returned by `fsSize` the resulting value will be `null` despite there being no information about this in the docs. It seems like it's not a bug inside the library but rather an explicit design as seen in `lib/filesystem.js:204`.

I'd strongly suggest to update the docs to reflect that behavior, as it currently says `rw` property is fully supported on Windows - https://systeminformation.io/filesystem.html
![image](https://github.com/sebhildebrandt/systeminformation/assets/116753476/a182bbb7-257a-41f5-8c31-a85ff5afd598)

**To Reproduce**
Simply use `fsSize` and read the `rw` prop - `(await fsSize())[0].rw`

**Current Output**
```js
[
  {
      fs: 'C:',
      type: 'NTFS',
      size: 999535996928,
      used: 604129169408,
      available: 395406827520,
      use: 60.44,
      mount: 'C:',
      rw: null <---
    },
    ...
]
```

**Expected behavior**
The value to be `boolean`

**Environment**
 - systeminformation package version: 5.18.7
 - OS: Windows 10 Pro 21H2 19044.3086
 - Hardware 
     - CPU: x86 (Ryzen platform), 
     - Storage: SSDs, HDDs (Samsung, Seagate, WD, Lexar, and some others)

**Comment by sebhildebrandt** [comment]
@4S1ght ... I am really sorry. Actually this IS supported also in windows, so the docs are correct. This worked till I introduced an issue a few weeks ago. I corrected it and now all should be fine again. Version 5.18.9 just published. Can you test it on your side?
