### ISSUE TITLE
Memory dirty and writeback bytes

### ISSUE THREAD

**Issue by td-michal-kepka** [sebhildebrandt/systeminformation#834]
Is your feature request related to a problem? Please describe.

Yes, my feature request is related to accessing memory-related statistics, specifically "Writeback" and "Dirty" memory values in bytes, using the systeminformation package for Node.js. Currently, the library provides memory information like total, free, used, and cached memory, but it does not offer direct access to "Writeback" and "Dirty" values in bytes, as reported in the /proc/meminfo file in Linux.

Describe the solution you'd like

I would like to see the systeminformation library extended to include properties that expose the "Writeback" and "Dirty" memory values in bytes. Ideally, the library should provide an API that allows developers to retrieve these specific memory statistics directly without having to parse the /proc/meminfo file manually.

For example, a new API could be added to the library that returns an object containing "Writeback" and "Dirty" memory values in bytes, similar to how other memory-related information is accessed through functions like si.mem().

Describe alternatives you've considered

As an alternative, I have tried reading and parsing the /proc/meminfo file directly to obtain the "Writeback" and "Dirty" values in bytes. However, this approach requires additional manual processing and may not be as efficient as accessing the data directly through the systeminformation library.

Additional context

Including direct access to "Writeback" and "Dirty" memory values in bytes in the systeminformation library would provide users with more comprehensive memory information and simplify the process of gathering memory-related statistics in Node.js applications. It would be particularly beneficial for those who require detailed memory usage data and prefer to work with standardized APIs provided by the systeminformation package.

Thank you for considering this feature request. If there are any additional details or screenshots needed to support this request, I'd be happy to provide them.

**Comment by sebhildebrandt** [comment]
@td-michal-kepka ... thank you for your description and your ideas here. I will provide a solution for it in the next few weeks.

**Comment by sebhildebrandt** [comment]
@td-michal-kepka ... as I am currently working already on version 6 of the library (complete rewrite in TS), I implemented this enhancement already for the new version. I am thinking to also apply this to the current version 5 in the upcoming week. JFI

**Comment by td-michal-kepka** [comment]
Great, thank you!

**Comment by sebhildebrandt** [comment]
@td-michal-kepka version 5.20.0 just published and docs are also updated. Can you test it also on your side?
