### ISSUE TITLE
[Bug] It cannot work in node v8

### ISSUE THREAD

**Issue by ZhongJunJimmy** [sebhildebrandt/systeminformation#838]
**Describe the bug**
It cannot work in Nodejs 8 version . The Nodejs 8 version does not support "??"

![image](https://github.com/sebhildebrandt/systeminformation/assets/22812616/cfbd4a71-cbd1-4b50-bd72-e484fa1a202a)

**Comment by chanyk-joseph** [comment]
Node v14 is also not working with systeminformation v5.18.12
`osMounts[line.split(' ')[0]] = osMounts[line.split(' ')[0]] ?? false;
SyntaxError: Invalid or unexpected token
`

**Comment by ZhongJunJimmy** [comment]
https://node.green/
NodeJS v8 does not support nullish coalescing operator (??)

**Comment by sebhildebrandt** [comment]
@ZhongJunJimmy @chanyk-joseph ... sorry!!!! Fixed it. Version 5.18.14 just published
