### ISSUE TITLE
Get all system services using si.services("*")

### ISSUE THREAD

**Issue by kounelios13** [sebhildebrandt/systeminformation#84]
### Expected behavior 

- 
-  Using "*" instead of a service name would return all system services
- 

### Actual behavior

- 
- Using "*" instead of a service name returns `[ { name: '*', running: false, pcpu: 0, pmem: 0 } ] `
- 

### Steps to reproduce the problem

```
si.services("*",function(data,error){
    console.log(data);
});
```

### Specifications 

- package version:3.31.2
- operating system:Ubuntu 17.04
- hardware:

### Problem and possible solution

I would like to ask if there is a way to get all system services using "*" instead of a service name like this:
```
si.services("*",function(data,error){
    console.log(data);
});
```

**Comment by sebhildebrandt** [comment]
Yes, I will think of a modification to get all services. Great Idea!

The problem I see here ist to distinguish between processes running and "true" services (which you probably want to see in the list). 

This could be an approach:

```
ps axfc -o comm  | grep -v '\\'
```

Can you post the output of that command from your machine and describe in the comments if this is a correct list from your perspective?

**Comment by kounelios13** [comment]
```
COMMAND
kthreadd
systemd
systemd-journal
lvmetad
systemd-udevd
systemd-timesyn
avahi-daemon
dbus-daemon
acpid
ModemManager
thermald
accounts-daemon
rsyslogd
bluetoothd
cron
NetworkManager
systemd-logind
cupsd
cups-browsed
smartd
snapd
irqbalance
polkitd
colord
sshd
systemd-resolve
mysqld
lightdm
timidity
agetty
wpa_supplicant
apache2
whoopsie
nmbd
smbd
master
rtkit-daemon
systemd
gnome-keyring-d
ibus-daemon
ibus-x11
pulseaudio
at-spi2-registr
upowerd
gsd-printer
geoclue
udisksd
fwupd
sublime_text
chromium-browse
terminix
packagekitd
anacron
```

**Comment by sebhildebrandt** [comment]
As i can see, there are also some non services listed (sublime-text, ...). What would be the output of 

```
s axfc -o pid,ppid,comm  | grep -v '\\'
```

Maybe this would give some additional information. 

One more comment: I see, that this is not that easy on OSX ...

**Comment by kounelios13** [comment]
```
  PID  PPID COMMAND
    2     0 kthreadd
    1     0 systemd
  348     1 systemd-journal
  367     1 lvmetad
  384     1 systemd-udevd
  994     1 systemd-timesyn
  998     1 avahi-daemon
  999     1 dbus-daemon
 1001     1 acpid
 1002     1 ModemManager
 1003     1 thermald
 1004     1 accounts-daemon
 1005     1 rsyslogd
 1007     1 bluetoothd
 1013     1 cron
 1015     1 NetworkManager
 1029     1 systemd-logind
 1041     1 smartd
 1046     1 snapd
 1089     1 irqbalance
 1115     1 polkitd
 1128     1 colord
 1139     1 sshd
 1146     1 systemd-resolve
 1148     1 mysqld
 1158     1 lightdm
 1213     1 timidity
 1232     1 agetty
 1246     1 wpa_supplicant
 1272     1 apache2
 1285     1 whoopsie
 1291     1 nmbd
 1294     1 smbd
 1540     1 master
 1673     1 rtkit-daemon
 1710     1 systemd
 1730     1 gnome-keyring-d
 1826     1 ibus-daemon
 1850     1 ibus-x11
 1891     1 pulseaudio
 1975     1 at-spi2-registr
 1980     1 upowerd
 1987     1 gsd-printer
 2090     1 geoclue
 2195     1 udisksd
 2483     1 fwupd
 2699     1 sublime_text
 2738     1 chromium-browse
 3914     1 terminix
18521     1 packagekitd
22653     1 cupsd
22654     1 cups-browsed
```
I am using linux by the way

**Comment by sebhildebrandt** [comment]
Thank you! As you already mentioned in your first comment this was supposed to be for linux. The thing is, that I would like to introduce new functionality for all supported platforms (this means also Win and OSX), so I have to make some more investigation for the other two. 

And as we can see, with the proposed approach there is no additional hint to distinguish between services and normal processes (like sublime-text, ...). The process list `processes()` should anyway give you a list of all processes but this is probably not what you thought about, right??

**Comment by kounelios13** [comment]
Yeah it's not.I am making an open source app for ubuntu that lists all services  and adds some buttons toenable/disable and restart a service

**Comment by sebhildebrandt** [comment]
here one more suggestion:

```
ps -C "$(xlsclients | cut -d' ' -f3 | paste - -s -d ',')" --ppid 2 --pid 2 --deselect -o tty,uid,pid,ppid,args | grep ^?
```

just curious if this can lead into the right direction.

**Comment by sebhildebrandt** [comment]
This one could also be useful:

```
service --status-all
```

Can you post the output?

If this shows, what you want to see, I will implement something using this approach.

**Comment by kounelios13** [comment]
@sebhildebrandt I have used the last solution in my app.This shows what I want however I had to maually do some string manipulations to get the status of each service.

**Comment by kounelios13** [comment]
Here's the output for `service --status-all`
```
 [ + ]  acpid
 [ - ]  alsa-utils
 [ - ]  anacron
 [ + ]  apache-htcacheclean
 [ + ]  apache2
 [ + ]  apparmor
 [ + ]  apport
 [ + ]  avahi-daemon
 [ + ]  bluetooth
 [ - ]  console-setup.sh
 [ + ]  cron
 [ - ]  cryptdisks
 [ - ]  cryptdisks-early
 [ + ]  cups
 [ + ]  cups-browsed
 [ + ]  dbus
 [ + ]  grub-common
 [ - ]  hwclock.sh
 [ + ]  irqbalance
 [ - ]  kerneloops
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ - ]  laptop-mode
 [ + ]  lightdm
 [ - ]  lvm2
 [ + ]  lvm2-lvmetad
 [ + ]  lvm2-lvmpolld
 [ + ]  mysql
 [ + ]  network-manager
 [ + ]  networking
 [ + ]  nmbd
 [ - ]  plymouth
 [ - ]  plymouth-log
 [ + ]  postfix
 [ - ]  pppd-dns
 [ + ]  procps
 [ - ]  prometheus
 [ + ]  resolvconf
 [ - ]  rsync
 [ + ]  rsyslog
 [ + ]  samba
 [ - ]  samba-ad-dc
 [ - ]  saned
 [ + ]  smartmontools
 [ + ]  smbd
 [ + ]  speech-dispatcher
 [ + ]  ssh
 [ + ]  thermald
 [ + ]  timidity
 [ + ]  tlp
 [ + ]  udev
 [ + ]  ufw
 [ + ]  unattended-upgrades
 [ - ]  uuidd
 [ + ]  whoopsie
 [ - ]  x11-common
```

**Comment by jeghers** [comment]
+1 this enhancement would be fantastic - specially if some reasonable windows equivalent was possible

**Comment by sebhildebrandt** [comment]
Hi, 

yes for windows this is actually quite easy. I started to work on this ... but as I am a little bit to busy right now, it might take 2 or 3 weeks to complete this.

**Comment by sebhildebrandt** [comment]
Just published a version that supports "*" for all services - but actually at the moment linux only. Windows will follow very soon. For macOS I did not found a way to reliably identify services ...

**Comment by sebhildebrandt** [comment]
Just added also the windows version for this feature request. Version 3.50.1 just published. Closing it for now.
