### ISSUE TITLE
Question: Is this the way for si to get all the information about CPU?  

### ISSUE THREAD

**Issue by liaodalin19903** [sebhildebrandt/systeminformation#840]
When I use systeminformation.cpu() to get CPU information:
```
const si = require('systeminformation');

// promises style - new since version 3
si.cpu()
  .then(data => console.log(data))
  .catch(error => console.error(error));

  
```

The result is as follows:
```
{
  manufacturer: 'Apple',
  brand: 'M1',
  vendor: 'Apple',
  family: '458787763',
  model: '',
  stepping: '2',
  revision: '',
  voltage: '',
  speed: 2.4,
  speedMin: 2.4,
  speedMax: 2.4,
  governor: '',
  cores: 8,
  physicalCores: 8,
  performanceCores: 4,
  efficiencyCores: 4,
  processors: 1,
  socket: 'SOC',
  flags: '',
  virtualization: true,
  cache: { l1d: 131072, l1i: 65536, l2: 4194304, l3: null }
}
```

 Is this the way for si to get all the information about CPU? Is there a way to get more detailed CPU content?

**Comment by sebhildebrandt** [comment]
Hi @liaodalin19903 … what else would you expect? The data structure that you see is platform independent and some fields are not available on some platforms. But anyway … anything you are missing? And any idea how this could be gathered? Regards

**Comment by sebhildebrandt** [comment]
@liaodalin19903 … did you received a notification of my previous comment?? I would need more information, if there is something missing from your perspective. Thank you in advance.

**Comment by liaodalin19903** [comment]
Hi, 
sorry for the late reply, 
what I want to express is that, such as cpu-z application, it can get more information(such as the `Core VID`) than the method as mentioned above, 
![image](https://github.com/sebhildebrandt/systeminformation/assets/12727582/f98dc10a-7fd5-4864-b90b-19331060c8af)

so I just wonder whether I use the correct method of get all the information of CPU in [systeminformation](https://github.com/sebhildebrandt/systeminformation).

**Comment by sebhildebrandt** [comment]
@liaodalin19903 ... cpu-z is written in c and does not rely on information that is available through command line or powershell. So I am afraid that there is no more, I can provide now. If you have any ideas, please just comment it here.

Closing it for now.
