### ISSUE TITLE
Latte Panda CPU Temperature

### ISSUE THREAD

**Issue by crgAdrian** [sebhildebrandt/systeminformation#844]
Hi,

I can't read the CPU temperature on LattePanda v1.

I'm using this library in a ElectronJS Application.

PS: On my personal computer everything is working.

**Comment by sebhildebrandt** [comment]
@crgAdrian thank you for reporting. 

What OS distort are you using? And what systeminformation package version you are using.

You could run `npx systeminformation info` which should give back system, OS and CPU info ....

Can you also run the following commands:

```
cat /sys/class/thermal/thermal_zone*/type  2>/dev/null; echo "-----"; cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null;

for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=${label%_*}_input; echo $(cat "$label")___$(cat "$value"); fi; done; done;

sensors
```

**Comment by crgAdrian** [comment]
I'm using Windows also.

**Comment by crgAdrian** [comment]
At this moment I test on a Windows environment.

I'm using the last version of package (5.18.15)

**Comment by sebhildebrandt** [comment]
@crgAdrian ok, please can you run from PowerShell:

```
Get-CimInstance MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature
```

Thank you in advance.

**Comment by crgAdrian** [comment]
I receive this:

```
CurrentTemperature
------------------
              2732
```

But my electron js app didn't unlock the CPU temperature

```
{
    "main": 0,
    "cores": [
        0
    ],
    "max": null,
    "socket": [],
    "chipset": null
}
```

**Comment by sebhildebrandt** [comment]
@crgAdrian please can you also check the package OUTSIDE of your electron app:

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

then press "T" (capital T) ... and provide the result here.

**Comment by crgAdrian** [comment]
@sebhildebrandt please check this

https://i.gyazo.com/dc9807dc56c3e64bcaf5652838fa1287.png

**Comment by sebhildebrandt** [comment]
@crgAdrian ok, well: as the underlying windows command returns `2732`, where we need to subtract 2732 and divide it by 10 ... the result is 0 degree Celsius. Which is exactly what systeminformation reports. So unfortunately the BIOS on this machine does not support more. Please have a look also here: https://systeminformation.io/issues.html

Btw. it would be easier to paste the results directly (as text) in GH

**Comment by crgAdrian** [comment]
Thanks :)

**Comment by sebhildebrandt** [comment]
@crgAdrian so I am closing this issue ...

**Comment by crgAdrian** [comment]
I have one more thing.

I downloaded another software (core temp) and this one displays the temperature.

**Comment by sebhildebrandt** [comment]
@crgAdrian ... well this software does not use measurements provided by windows ... I guess this is written in C ...

**Comment by crgAdrian** [comment]
@sebhildebrandt any updates?

i'm working on my v2 app :)
