### ISSUE TITLE
wifiConnections doesnt return bssid | macOS

### ISSUE THREAD

**Issue by kursatsmsek** [sebhildebrandt/systeminformation#846]
**Describe the bug**
wifiConnections methods should be return data thats includes bssid as showing systeminformation package docs

[
  {
    id: 'Wi-Fi',
    iface: 'en0',
    name: 'AirPort',
    model: 'AirPort',
    ssid: 'my-own-internet',
    bssid: '01:23:45:67:89:0a',
    channel: 36,
    frequency: 5180,
    type: '802.11',
    security: 'wpa2-psk',
    signalLevel: 46,
    txRate: '405'
  },
  ...
]

but when I tried the function couldnt see bssid for my mac. I know Apple has started this problem for their security policy. However I dont wanna use sudo command. I'll follow your package for this issue but please edit the doc for this warning.

**Comment by sebhildebrandt** [comment]
@kursatsmsek ... you are right. I updated the docs (systeminformation.io) accordingly.
