### ISSUE TITLE
Add serialNum field for cpu info

### ISSUE THREAD

**Issue by tvilkov** [sebhildebrandt/systeminformation#85]
### Expected behavior 

- `si.cpu(...)` will return cpu's serial number

### Actual behavior

- `si.cpu(...)` currently doesn't return cpu's serial number

**Comment by sebhildebrandt** [comment]
Will check it in the next few days.

**Comment by sebhildebrandt** [comment]
@tvilkov 
Hi again, I made some investigations on that and unfortunately a CPU serial number is no ,longer available:

https://en.wikipedia.org/wiki/CPUID#EAX.3D3:_Processor_Serial_Number

> The processor serial number was introduced on Intel Pentium III, but due to privacy concerns, this feature is no longer implemented on later models ... AMD CPUs however, do not implement this feature in any CPU models.

If you are looking for some kind of hardware serial number or UUIDs then I can tell you that I am working on providing such a number. Will provide a solution for that within the next few days. OK for you?

**Comment by tvilkov** [comment]
Hello, Sebastian. Thanks for quick reply. 
Yes, my very specific use case involves binding node js app to machine is was installed on. 
To do this I need to gather some system info (like CPU id, mac address, etc). 
So, I guess, some kind of UUID which doesn't change over time for given machine will do the job.

**Comment by sebhildebrandt** [comment]
@tvilkov Actually you should already get an `UUID` and `serial number` with `si.system()`. Mac addresses are also available with `si.networkInterfaces()`. Please check if this is sufficient for you.

If you do not get meaningful results, please let me know, what OS and hardware you are using.

I will add some additional BIOS and base board information to the library soon but i guess this will not be that helpful.

**Comment by tvilkov** [comment]
@sebhildebrandt, yes I saw `uuid` `si.system()` response but thought it's something to do with software serial (like serial number in Windows).
Just have tried `si.system()` on my Windows machine. Got some GUID-like result. Not sure it's what I need.  Is it hardware or software related? I mean is there a chance this GUID will be equal on two different machine which exact the same hardware configuration?
Need to try on target machine (which is Raspberry Pi device). Just not sure I will be able to do this any time soon. Anyway, will keep you informed. 
Thanks one again.

**Comment by sebhildebrandt** [comment]
@tvilkov This is related to the hardware. On windows I am referring to the `Win32_ComputerSystemProduct` class. Even the documentation is not very clear about, it is not related to the OS - Windows serial number.

On Raspberry Pi (running linux) I have also to test it once again ... I have some specific code here (because dmidecode does not work). So we will keep in touch on that, ok? Closing it for now.
