### ISSUE TITLE
Unexpected battery.timeRemaining in hours

### ISSUE THREAD

**Issue by josuigoa** [sebhildebrandt/systeminformation#852]
**Describe the bug**
I've found two different responses in two scenarios: 

* When the laptop is not charging doing `info.battery()` call, it returns `timeRemaining` in hours, rounded. So if my battery remaining time is 3:59 or 3:01 hours, it will return 3. When the documentation tells it returns minutes.
* When the laptop is charging `info.battery()` returns a very high `timeRemaining`, in a test it returned 3470, for example. Maybe this is not a bug, but it's been courious two see such high values.

**To Reproduce**
1. unplug the laptop
2.  require('systeminformation').battery().then(d => console.log(d.timeRemaining))

**Current Output**
3

**Expected behavior**
Something between 180 (3:00) and 239 (3:59)

**Environment (please complete the following information):**
┌────────────────────────┐
│  SYSTEMINFORMATION                    Version: 5.21.4 │
└────────────────────────┘

Operating System:
──────────────────
Platform         : linux
Distro           : Ubuntu
Release          : 22.04.2 LTS
Codename         : Jammy Jellyfish
Kernel           : 6.2.0-32-generic
Arch             : x64
Hostname         : josu-Latitude-5520
Codepage         : UTF-8
Build            : 

System:
──────────────────
Manufacturer     : Dell Inc.
Model            : Latitude 5520
Version          : 
Virtual          : 

CPU:
──────────────────
Manufacturer     : Intel
Brand            : Gen Intel® Core™ i7-1165G7
Family           : 6
Model            : 140
Stepping         : 1
Speed            : 2.8
Cores            : 8
PhysicalCores    : 4
PerformanceCores : 4
EfficiencyCores  : 
Processors       : 1
Socket           :

**Comment by sebhildebrandt** [comment]
@josuigoa ... thank you for reporting, need to check it on my Dell Laptop ... will come back with a fix for that.

**Comment by sebhildebrandt** [comment]
@josuigoa  can you post the output of the following commands (when charging AND when not charging)

```
cat /sys/class/power_supply/BAT0/uevent
cat /sys/class/power_supply/BAT1/uevent
```

One of them should return some result ...

Thank you in advance ...

**Comment by josuigoa** [comment]
~  $ cat /sys/class/power_supply/BAT0/uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_TYPE=Battery
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-poly
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=15200000
POWER_SUPPLY_VOLTAGE_NOW=14967000
POWER_SUPPLY_CURRENT_NOW=734000
POWER_SUPPLY_CHARGE_FULL_DESIGN=4103000
POWER_SUPPLY_CHARGE_FULL=3383000
POWER_SUPPLY_CHARGE_NOW=1383000
POWER_SUPPLY_CAPACITY=40
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=DELL M033W23
POWER_SUPPLY_MANUFACTURER=BYD
POWER_SUPPLY_SERIAL_NUMBER=4029

cat /sys/class/power_supply/BAT1/uevent doesn't return any results

2023-09-18 08:41 egunean, Sebastian Hildebrandt-(e)k idatzi du:

**Comment by josuigoa** [comment]
sorry, the results from previous response were when NOT charging, I forgot  to give the charging values. Here you have:

~  $ cat /sys/class/power_supply/BAT0/uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_TYPE=Battery
POWER_SUPPLY_STATUS=Charging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-poly
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=15200000
POWER_SUPPLY_VOLTAGE_NOW=15849000
POWER_SUPPLY_CURRENT_NOW=1885000
POWER_SUPPLY_CHARGE_FULL_DESIGN=4103000
POWER_SUPPLY_CHARGE_FULL=3383000
POWER_SUPPLY_CHARGE_NOW=1158000
POWER_SUPPLY_CAPACITY=34
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=DELL M033W23
POWER_SUPPLY_MANUFACTURER=BYD
POWER_SUPPLY_SERIAL_NUMBER=4029

**Comment by sebhildebrandt** [comment]
@josuigoa ... I think I found a solution. Version 5.21.8 just released. Can you test it on your side?

**Comment by josuigoa** [comment]
now it works as expected, thank you!
