### ISSUE TITLE
When trying to get other cpu stats it crashes on linux machines with PM2.

### ISSUE THREAD

**Issue by corteshvictor** [sebhildebrandt/systeminformation#862]
**Describe the bug**
When trying to get other cpu statistics the library fails because the default `execSync,` the value of its encoding is a Buffer and when they want to do the .split('\n') this generates error and goes through the catch by executing the utility `util.noop(); `. Additionally, this utility has no logic, it does nothing and generates empty errors in pm2.

File and line of code with the problem. https://github.com/sebhildebrandt/systeminformation/blob/master/lib/cpu.js#L1604

**To Reproduce**
1. used function '...' [execSync('cat /proc/stat 2>/dev/null | grep cpu')](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/cpu.js#L1607)
2. code snippet '....'
3. start app / code
4. See output/error '....'

**Current Output**
If applicable, add output to help explain your problem.
- Generate empty errors on linux machines with PM2
<img width="695" alt="image" src="https://github.com/sebhildebrandt/systeminformation/assets/17968316/5f28e5ff-ca70-4974-b9c4-8367ace463f6">

**Expected behavior**
It should not generate the empty error, but get the values from the CPU.

**Environment (please complete the following information):**
 - systeminformation package version: 5.21.13
 - OS: linux
 - Hardware linux

To get all needed environment information, please run the following command:

```
  npx systeminformation info
```

**Additional context**
- This was the commit where they added the new way to get CPU values. https://github.com/sebhildebrandt/systeminformation/commit/e3dc1bfec5db922d8205a9bcf4daf42e3c28357e

**Comment by corteshvictor** [comment]
Proposal to solve the issues. https://github.com/sebhildebrandt/systeminformation/pull/861

**Comment by sebhildebrandt** [comment]
@corteshvictor ... this is interesting, I now added the encoding to most of the calls in linux. If this is really the problem, this should have also caused other issued. Nit sure if this really fixes this issue. But anyway thank you! Version 5.21.14 just published.

**Comment by victorhcortesp** [comment]
Hi @sebhildebrandt, I was looking at the commit of the changes, I see that the encoding was added to all the execSync.
But in most you had the .toString that converted the buffer to string, in those cases I think it was not necessary to add the encoding.
Thank you very much for releasing I will test.

**Comment by corteshvictor** [comment]
Hi @sebhildebrandt, I was looking at the commit of the changes, I see that the encoding was added to all the execSync.
But in most you had the .toString that converted the buffer to string, in those cases I think it was not necessary to add the encoding.
Thank you very much for releasing I will test.

**Comment by sebhildebrandt** [comment]
@corteshvictor ... basically what would also be possible to remove again the encodings and just add a `toString()` here, right? This would make it more consistent and feels more the right way to do it. Can you try replacing this one line (1607):

```
            const lines = execSync('cat /proc/stat 2>/dev/null | grep cpu').toString().split('\n');
```

and see if you stille get your error (I expect that this should no longer happen).

**Comment by sebhildebrandt** [comment]
@corteshvictor If the `.toString()` works on your side, I will revert my previous commit and replace it with the `.toString()` :-)

**Comment by sebhildebrandt** [comment]
@corteshvictor Version 5.21.15 just published with the `toString()` correction ...

**Comment by corteshvictor** [comment]
@sebhildebrandt Hello, what a pity not to answer sooner and to test.
But now I'm checking that in this new version the console.log started to be empty again.
I think the best thing to do is to remove the `.toString` and add the `{encoding: 'utf8'}`

**Comment by sebhildebrandt** [comment]
@corteshvictor ok, not clear why this happens but I will add it again. Are we sure that this is the ONLY spot where this is needed?

**Comment by sebhildebrandt** [comment]
@corteshvictor Version 5.21.16 just release, can you retest it?

**Comment by victorhcortesp** [comment]
@sebhildebrandt This new version fixes the empty log.
It seems that transforming the buffer with `.toString` does something different than when you use the `encoding: 'utf8'` because the latter tells NodeJS to interpret it as a string and the other transforms it. There may be some difference that in some cases it is not convenient to transform the buffer but to interpret it.
