### ISSUE TITLE
networkStats  RX/TX  bytes/sec shows -1

### ISSUE THREAD

**Issue by weiofcn** [sebhildebrandt/systeminformation#87]
```
const si = require('systeminformation');

si.networkStats('eth0', function(data) {
   console.log('Network Interface Stats (eth1):');
   console.log('- is up: ' + data.operstate);
   console.log('- RX bytes overall: ' + data.rx);
   console.log('- TX bytes overall: ' + data.tx);
   console.log('- RX bytes/sec: ' + data.rx_sec);
   console.log('- TX bytes/sec: ' + data.tx_sec);
})

```

### Actual behavior
```
Network Interface Stats (eth1):
- is up: up
- RX bytes overall: 260929676
- TX bytes overall: 19783385
- RX bytes/sec: -1
- TX bytes/sec: -1
```

### Specifications 

- package version: node 8.2.1, systeminformation latest
- operating system: Ubuntu 14.04.5 LTS

### Problem and possible solution

The problem that I met here is the section of RX bytes/sec: -1 and TX bytes/sec: -1. 
I tried [nload](https://linux.die.net/man/1/nload) and it showed I had fluctuated RX and TX numbers.

**Comment by sebhildebrandt** [comment]
Hi @weiofcn 

the first time you call this function, you will get this results (am I right, you just called this function just once?). The second time, you should then get statistics based on the time between the two times …

So basically, if you need a values for network stats every second, your code should look like this:

```
const si = require('systeminformation');

setInterval(function() {
	si.networkStats().then(data => {
	    console.log('-----------------------------');
	    console.log(data);
	})
}, 1000)
```

I should state this more explicitly in the documentation.
Please give me a short feedback, if that worked on your machines.

regards
Sebastian

**Comment by weiofcn** [comment]
Thank you for the swift replying.

It's working as exact as you said. 

Thanks again.
