### ISSUE TITLE
cpu usage in si.services()

### ISSUE THREAD

**Issue by td-michal-kepka** [sebhildebrandt/systeminformation#874]
**In documentation there is information:**
In currentLoad() the results are calculated correctly beginning with the second call of the function. It is determined by calculating the difference of cpu ticks between two calls of the function.

The first time you are calling one of this functions, you will get the load since cpu uptime. The second time, you should then get statistics based on cpu ticks between the two calls ...

**Is this true for cpu usage of each service returned by si.services()?**

**Comment by sebhildebrandt** [comment]
@td-michal-kepka ... right. at least this is how I intended to to be. If you discover any problems, just re-open this issue here.
