### ISSUE TITLE
hypervisor is listed twice in OsData interface

### ISSUE THREAD

**Issue by Soviut** [sebhildebrandt/systeminformation#875]
**Describe the bug**

In the `OsData` interface, `hypervisor` occurs twice.

**To Reproduce**

1. Visit https://github.com/sebhildebrandt/systeminformation/blob/master/lib/index.d.ts#L381
2. Observe `hypervisor?: boolean;` twice in `interface OsData`

**Current Output**

N/A

**Expected behavior**

N/A

**Environment (please complete the following information):**

N/A

To get all needed environment information, please run the following command:

N/A

**Additional context**

N/A

**Comment by sebhildebrandt** [comment]
@Soviut thank you!! Fixed, Version 5.21.19 just published
