### ISSUE TITLE
Cant use fsSize in mas/mas-dev build - 'could not start up a diskmanagement session'

### ISSUE THREAD

**Issue by Zedbyte-corp** [sebhildebrandt/systeminformation#877]
**Describe the bug**

**To Reproduce**
1. used function 'fsSize()'
2. code snippet
```
ipcMain.on('check-storage', async (event, arg) => {
  console.log('fsSize', parse(arg.path).root)
  const parsedPath =
    process.platform === 'win32' ? parse(arg.path).root.slice(0, -1) : parse(arg.path).root
  await fsSize(parsedPath).then((data) => {
    console.log('fsSize', data, arg)
    for (var i = 0; i < data.length; i++) {
      if (data[i]['mount'].startsWith('/System')) {
        continue
      }
      if (data[i].available > arg.totalBytes) {
        event.sender.send('available-storage', true)
      } else {
        event.sender.send('available-storage', false)
      }
      break
    }
  })
})
```
3. start app / code
```
window.electron.send('check-storage', {path: downloadPath.download_path, totalBytes: tempSize})
```
4. See output/error 'could not start up a diskmanagement session'

**Current Output**
'could not start up a diskmanagement session'

**Expected behavior**
Need to access fsSize() in production build with all the disk properties

**Environment (please complete the following information):**
 - systeminformation package version: 5.21.20
 - OS: macOS Sonoma 14.2
 - Hardware Mac Mini 2018

To get all needed environment information, please run the following command:

```
  npx systeminformation info
```

**Comment by sebhildebrandt** [comment]
@Zedbyte-corp can you confirm, that the `fsSize()` function works outside of electron on your machine?

```
const si = require('systeminformation');
si.fsSize().then(data => console.log(data));
``` 

Does this produce meaningful output? If yes, I suppose that this is not a problem related to `systeminformation`

**Comment by Zedbyte-corp** [comment]
> @Zedbyte-corp can you confirm, that the `fsSize()` function works outside of electron on your machine?
> 
> ```
> const si = require('systeminformation');
> si.fsSize().then(data => console.log(data));
> ```
> 
> Does this produce meaningful output? If yes, I suppose that this is not a problem related to `systeminformation`

it produces correct output, but in electron production build it doesn't but only if i pass path to the drive.

**Comment by sebhildebrandt** [comment]
@Zedbyte-corp can you pass the same drive parameter to the sample code above (outside electron)?

**Comment by Zedbyte-corp** [comment]
Add this entitlement
```
<key>com.apple.security.files.downloads.read-write</key>
<true/>
```

even though you have this
```
<key>com.apple.security.files.user-selected.read-write</key>
<true/>
```

the irony
