### ISSUE TITLE
cpuTemprature() always returns same temprature

### ISSUE THREAD

**Issue by ElsevarAsadov** [sebhildebrandt/systeminformation#879]
I always get same temprature when i call method.

```js
const si = require("systeminformation");
si.cpuTemperature().then(data=>console.log(data));
```
EDIT: i also tested using admin privileged command line still same.in windows 11 i cannot event get any value without admin access with admin access i get the same value everytime

 - systeminformation package version: ^5.21.22
 - OS: i tested both win 10 and 11

**Comment by sebhildebrandt** [comment]
@ElsevarAsadov please have a look at the documentation (https://systeminformation.io/issues.html). Not all BIOS driver implementations return proper values. So if Windows cannot determine the correct values (see also underlying powershell command), we cannot display correct values here. You can test, if windows can get valid values by running (in powershell):

```
Get-CimInstance MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select CurrentTemperature
```
