### ISSUE TITLE
The signal level returned from wifiConnections() is faulty.

### ISSUE THREAD

**Issue by priyankasrs** [sebhildebrandt/systeminformation#889]
**Describe the bug**
The object returned from wifiConnections() contains signal level in units of '%' (signal quality) not dBm (rssi) as mentioned in the documentation. It is also typed as a number when in fact it is returned as a string with the '%' char attached to it. Also, signal quality is not returned in the object as per the documentation.

**To Reproduce**
1. Call si.wifiConnections()
2. Display the object returned from wifiConnections() in the console
3. You will see the output in the console

**Environment (please complete the following information):**
 - systeminformation package version: 5.21.24
 - OS: Windows 10
 - Hardware Lenovo ThinkPad P15 Gen 2
To get all needed environment information, please run the following command:

```
  npx systeminformation info
```

**Comment by sebhildebrandt** [comment]
Hi @priyankasrs ... I will have a look on it. I guess you are right ... will try to provide a solution.

**Comment by sebhildebrandt** [comment]
@priyankasrs should be solved now. Sorry, my fault. Version 5.21.25 just published. Can you test it on your side?

**Comment by sebhildebrandt** [comment]
@priyankasrs I now added "quality" as an extra attribute, so.now you should have:

- signalLevel (in DB) as expected
- quality (in %)

So basically the same what we also see in the `wifiNetwork()` function. Don't know why I did not implemented it here in `wifiConnections()` but now it should be fine. I would be happy if you can test it on your side. Version 5.22.0 just released.

**Comment by priyankasrs** [comment]
@sebhildebrandt Will check this in a couple of days and get back. Thanks!

**Comment by priyankasrs** [comment]
@sebhildebrandt  It works. Thanks!
