### ISSUE TITLE
Temperature on windows

### ISSUE THREAD

**Issue by MeesMaas** [sebhildebrandt/systeminformation#89]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- Showing temperature

### Actual behavior

- Not doing it

### Steps to reproduce the problem

- Type the code in.

### Specifications 

- package version: latest
- operating system: windhoos

### Problem and possible solution

Hello there again!

We have a solution for you:
https://gist.github.com/jeffa00/9577816

Enjoy and have a nice evening!

**Comment by sebhildebrandt** [comment]
Hi again. Thank you for your suggestions! Will check it later this weekend.

**Comment by sebhildebrandt** [comment]
Just to be sure: as I already stated in https://github.com/sebhildebrandt/systeminformation/issues/76, for some versions of windows you need to run this with admin privileges to get proper results.

Did you checked on this specific installation? On the GIST you provided, it also states to run this with admin privileges.

Please can you run the following two commands and provide the results here?

```
wmic /namespace:\\\\root\\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
```

and 

```
powershell.exe Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi"
```

**Comment by fabiaant** [comment]
Hi, it turns out that to have the temperature work, admin privileges are indeed needed. I had to run git bash as admin and then start the project for the temperature to show up. I suppose admin is simply always necessary on windows to access the temperature?

**Comment by fabiaant** [comment]
![image](https://user-images.githubusercontent.com/8672067/32972041-791a6c3c-cbf0-11e7-922d-105ee59b5f26.png)
Here are the results for the two commands you listed.

**Comment by sebhildebrandt** [comment]
Hi @fabiaant 
Thank you for testing it. It really depends on the installation. In some cases admin privileges are needed in some other cases not.

Concerning the test of the two commands, in the first one I had to much escaping ;-) 
The correct command should be:

```
wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CurrentTemperature
```

Can you retry to run this one again? Thank you in advance.

**Comment by fabiaant** [comment]
![image](https://user-images.githubusercontent.com/8672067/32979542-33708178-cc57-11e7-953e-c4c54f69baaf.png)
There you go. Once again an "acces denied" error when it's not ran as admin however.

**Comment by sebhildebrandt** [comment]
Thank you @fabiaant ! As expected. This means, `si.cpuTemperature()` returns the right values if it is called with admin privileges, right? Otherwise Windows will not give me a chance to get the temperature. Can you confirm that?

**Comment by fabiaant** [comment]
Yes, that is correct

**Comment by sebhildebrandt** [comment]
OK, then I am closing this ...
