### ISSUE TITLE
chassis.type is not available in macos

### ISSUE THREAD

**Issue by narmatha291289** [sebhildebrandt/systeminformation#892]
**Describe the bug**
`chassis.type` is empty in macos.

**Solution**
MacBookAir -> type = Notebook
MacBookPro -> type = Laptop
MacBook -> type = Notebook
macMini -> type = Desktop
imac -> type = Desktop
macStudio -> type = Desktop
macPro -> type = Tower

**Comment by sebhildebrandt** [comment]
@narmatha291289 I now added type as well as sku to the `chassis()` function. Thank you for this idea. Version 5.22.2 just published.
