### ISSUE TITLE
Same bank label for two ram strips

### ISSUE THREAD

**Issue by Aspedm** [sebhildebrandt/systeminformation#894]
**Describe the bug**
The `si.memLayout` method returns two RAM strips, both with identical bankLabels. The raw request yielded the same information.

**Current Output**
![Screenshot 2024-03-07 233633](https://github.com/sebhildebrandt/systeminformation/assets/8427994/308abd71-112a-45f1-bf62-e956729e202b)
![Screenshot 2024-03-07 233654](https://github.com/sebhildebrandt/systeminformation/assets/8427994/6d24dd9f-7079-4296-bb14-94392ad86f5b)

**Expected behavior**
This ram strips have 2 and 4 slots.
![Screenshot 2024-03-07 234049](https://github.com/sebhildebrandt/systeminformation/assets/8427994/deef4c81-0aa3-4b31-a499-ac9c5665b074)
![Screenshot 2024-03-07 234101](https://github.com/sebhildebrandt/systeminformation/assets/8427994/53466395-2b92-4d05-89a1-a810310d7a22)
![Screenshot 2024-03-07 234116](https://github.com/sebhildebrandt/systeminformation/assets/8427994/851f8223-ba8c-479b-9bd6-258e81a691b1)
![Screenshot 2024-03-07 234127](https://github.com/sebhildebrandt/systeminformation/assets/8427994/1d6eef74-0f28-4f3a-8ab9-8f0c8eb31cb3)

**Environment (please complete the following information):**
 - systeminformation package version: 5.22.0
 - OS: Windows 11

**Comment by Aspedm** [comment]
I modified command and added field `tag`. It's match with physical slots.
` Get-CimInstance Win32_PhysicalMemory | select DataWidth,TotalWidth,Capacity,BankLabel,MemoryType,SMBIOSMemoryType,ConfiguredClockSpeed,FormFactor,Manufacturer,PartNumber,SerialNumber,ConfiguredVoltage,MinVoltage,MaxVoltage,Tag | fl`

```
```

**Comment by sebhildebrandt** [comment]
@Aspedm for now I added tag number to the bank to avoid adding an extra property (for windows only). Version 5.22.3 just released.
