### ISSUE TITLE
wifiConnections/wifiNetworks, no results on Mac Sonoma 14.4

### ISSUE THREAD

**Issue by tacomanator** [sebhildebrandt/systeminformation#895]
**Describe the bug**
`wifiConnections()` and `wifiNetworks` both returning no results (despite being connected to wifi).

**To Reproduce**
```js
const systeminformation = require("systeminformation");

(async () => {
  console.log(await systeminformation.wifiInterfaces());
  // always outputting [] for me
})();
```

**Current Output**
both currently return an empty array despite being connected to a wifi network.

**Expected behavior**

**Environment (please complete the following information):**
SYSTEMINFORMATION Version: 5.22.0

Operating System:
──────────────────────────────────────
Platform         : darwin
Distro           : macOS
Release          : 14.4
Codename         : macOS Sonoma
Kernel           : 23.4.0
Arch             : arm64
Codepage         : UTF-8
Build            : 23E214

System:
──────────────────────────────────────

Manufacturer     : Apple Inc.
Model            : MacBookPro18,2
Version          : 
Virtual          : 

CPU:
──────────────────────────────────────
Manufacturer     : Apple
Brand            : M1 Max
Family           : 458787763
Model            : 
Stepping         : 5
Speed            : 2.4
Cores            : 10
PhysicalCores    : 10
PerformanceCores : 8
EfficiencyCores  : 2
Processors       : 1
Socket           : SOC

**Additional context**
Possible that the issue coincided with recent upgrade to Sonoma 14.4

**Comment by sebhildebrandt** [comment]
Hi @tacomanator thank you for reporting. This is not good news. I am currently still on 14.2 so I did not realized that there is a change in 14.4. Need to go deeper into it to find out what options we have now. Thank you once again.

**Comment by sebhildebrandt** [comment]
@tacomanator I made some investigations and partially I can get information for `wifiConnections()` but for `wifiNetworks()` I was not yet able to find anything ... give me some time to provide at least for the first one a solution.

**Comment by tacomanator** [comment]
@sebhildebrandt thank you, I appreciate you. I am only using `wifiConnections()` anyway, but reported `wifiNetworks()` for the sake of completeness.

**Comment by sebhildebrandt** [comment]
@tacomanator I added a patch for `wifiConnections()` here on the master branch. Can you clone master branch and test it?

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
npm run test
```

And now press `x` ... hopefully you have (partial) results now ... can you confirm that?

**Comment by sebhildebrandt** [comment]
@tacomanator did you had time to test the fix as described above?

**Comment by tacomanator** [comment]
@sebhildebrandt I'm sorry I haven’t yet but I will as soon as I get in front of my computer

**Comment by tacomanator** [comment]
@sebhildebrandt Sorry for the delay I finally was able to confirm, and`wifiConnections()` is giving some results!

<img width="1106" alt="スクリーンショット 0006-03-12 19 31 43" src="https://github.com/sebhildebrandt/systeminformation/assets/63794/b42eaf10-5a5f-4264-8111-416c7f3c33df">

**Comment by sebhildebrandt** [comment]
@tacomanator  Exactly was I was hoping to see :-) ... thank you for testing. Version 5.22.1 just published.

**Comment by tacomanator** [comment]
Upgrade and good to go. Thank you for a quick turnaround and for a very useful library!

**Comment by shaguarger** [comment]
Hi folks, sadly this issue still persist for me with wifiNetworks after the update to Mac Sonoma 14.4 and 5.22.5. :( Any ideas?

![Screenshot 2024-03-19 at 15 09 57](https://github.com/sebhildebrandt/systeminformation/assets/16501863/55576764-189b-477f-b783-bd3cdfc29346)

**Comment by sebhildebrandt** [comment]
@shaguarger can you provide the output of

```
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I 
```

and 

```
ioreg -n AppleBCMWLANSkywalkInterface -r
```

Thank you in advance

**Comment by shaguarger** [comment]
![Screenshot 2024-03-20 at 09 48 08](https://github.com/sebhildebrandt/systeminformation/assets/16501863/85a0bebc-cc44-4db8-be6b-f192a37159a6)

Here you go. Thanks!

**Comment by sebhildebrandt** [comment]
@shaguarger Can you provide this as text (you can just "XXXX" the parts that you don't want to show). Than I can take this as a mock input and see what is happening. Thank you in advance.

**Comment by shaguarger** [comment]
```➜  ~ /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I 
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
➜  ~ ioreg -n AppleBCMWLANSkywalkInterface -r
+-o AppleBCMWLANSkywalkInterface  <class AppleBCMWLANSkywalkInterface, id 0x1000006e6, registered, matched, active, busy 0 (19 ms), retain 35>
  | {
  |   "mDNS_KEY" = "2009-07-30"
  |   "mDNS_Keepalive" = Yes
  |   "IO80211Channel" = 108
  |   "IO80211Band" = "5 GHz"
  |   "IO80211BSSID" = <1ced6f000000>
  |   "IO80211InterfaceRole" = "Infrastructure"
  |   "IO80211ChannelBandwidth" = 80
  |   "IO80211SSID" = "SomeSSID"
  |   "IOPowerManagement" = {"ChildrenPowerState"=1,"DevicePowerState"=1,"CurrentPowerState"=1,"CapabilityFlags"=32770,"MaxPowerState"=1,"DriverPowerState"=0}
  |   "built-in" = <00>
  |   "IO80211DriverVersion" = "wl0: Jul 10 2023 12:53:18 version 9.30.503.0.32.5.92 FWID 01-c06f991b"
  |   "IOInterfaceName" = "en0"
  |   "IOInterfaceUnit" = 0
  |   "IO80211Locale" = "ETSI"
  |   "IOMACAddress" = <147dda74beee>
  |   "IOInterfaceType" = 6
  |   "IO80211CountryCode" = "DE"
  |   "IO80211RSNDone" = No
  |   "IO80211ChannelFrequency" = 5540
  |   "IO80211HardwareVersion" = "vendorid: 0x14e4 deviceid: 0x1111 radiorev: 0x422069 chipnum: 0x4364 chiprev: 0x4 corerev: 0x3a boardid: 0x81d boardvendor: 0x14e4 boardrev: 0x1770 driv$
  |   "IOInterfaceNamePrefix" = "en"
  | }
  | 
  +-o IOSkywalkLegacyEthernet  <class IOSkywalkLegacyEthernet, id 0x1000000f3, !registered, !matched, active, busy 0 (0 ms), retain 8>
  | +-o en0  <class IOSkywalkLegacyEthernetInterface, id 0x1000000f5, registered, matched, active, busy 0 (0 ms), retain 12>
  |   +-o IONetworkStack  <class IONetworkStack, id 0x1000000c0, registered, matched, active, busy 0 (0 ms), retain 20>
  |     +-o IONetworkStackUserClient  <class IONetworkStackUserClient, id 0x1000000a7, !registered, !matched, active, busy 0, retain 5>
  +-o IOSkywalkNetworkBSDClient  <class IOSkywalkNetworkBSDClient, id 0x10000008d, registered, matched, active, busy 0 (0 ms), retain 9>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 6>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 6>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 6>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 6>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
  +-o IO80211APIUserClient  <class IO80211APIUserClient, id 0x100000123, !registered, !matched, active, busy 0, retain 5>
```

**Comment by shaguarger** [comment]
Overall I am missing the "SomeSSID Gastzugang" and another wifi name in the output.

**Comment by sebhildebrandt** [comment]
@shaguarger `wifiConnections()` can only show one active WIFI connection and with the data you provided I get:

```
┌────────────────────────────────────────────────┐
│  WIFI Connections                    v: 5.22.6 │
└────────────────────────────────────────────────┘
[
  {
    id: 'Wi-Fi',
    iface: 'en0',
    model: 'AirPort',
    ssid: 'SomeSSID',
    bssid: '1c:ed:6f:00:00:00',
    channel: 108,
    frequency: 5540,
    type: '802.11',
    security: '',
    signalLevel: -1,
    quality: -1,
    txRate: -1
  }
]
Time to complete: 354.249ms
```

Can you please recheck on your side?

**Comment by sebhildebrandt** [comment]
@shaguarger ... and for `wifiNetworks()` this is actually no longer supported (`airport` command deprecated in Sonoma 14.4) ... as I do not see any alternative to the `airport` command. If you know something that does not require elevated privileges, please let me know.

**Comment by sebhildebrandt** [comment]
@shaguarger thank you for checking!! Would be great to get this back into the library. So if you find something, just provide the command, I will then implement a solution ;-)
