### ISSUE TITLE
Alternative location for machine-id is not resolved properly

### ISSUE THREAD

**Issue by mhirsch** [sebhildebrandt/systeminformation#896]
If you're looking for the os uuid in Linux and call `uuid()` under Fedora you get an empty string.

In the systeminformation source, here I see the shell commands used to extract the machine id. 

https://github.com/sebhildebrandt/systeminformation/blame/356bb7a505b92ac66f4d0c8045cb8c25015190a0/lib/osinfo.js#L1126

Feodra does not provide the entry at `/var/lib/dbus/machine-id`, only at `/etc/machine-id`. While the 2nd location is included in the shell command it's not properly extracted with `util.getValue()`. The result of the `exec` call looks something like this:

```
[
  'os: ',
  'os: <uuid>',
  '',
  'hardware: <uuid>',
  '',
  ''
]
```

But `util.getValue()` returns an empty string, not finding the 2nd entry there.

I'm not sure what the logic of `getValue` is supposed to be, and it seems to be used in many places in the code, so I don't want to change it.

The simplest fix would be to change the shell code to this:

```
echo -n "os: "; cat /var/lib/dbus/machine-id 2> /dev/null ||
cat /etc/machine-id 2> /dev/null; echo;
echo -n "hardware: "; cat /sys/class/dmi/id/product_uuid 2> /dev/null; echo;
```

Should I submit a patch for this, or is there a different preferred solution?

**Comment by sebhildebrandt** [comment]
@mhirsch thank you for reporting. No need to provide a patch, will work on it and provide a new release tomorrow.

**Comment by sebhildebrandt** [comment]
@mhirsch I implemented a patch on main branch (not yet published as NPM package). Can you give it a try?

```
git clone https://github.com/sebhildebrandt/systeminformation.git
cd systeminformation
git pull
npm run test
```

Then in the menu press (capital) `U` to see if it works. Thank you in advance for testing and feedback.

**Comment by mhirsch** [comment]
Thanks for the quick fix! I've run the above test with only `/etc/machine-id` present, and with `/etc/machine-id` and `/var/lib/dbus/machine-id` present on Fedora 39 and it works for me in both cases.

**Comment by sebhildebrandt** [comment]
@mhirsch Version 5.22.4 just published.
