### ISSUE TITLE
Abnormal Network Interface Speed Reporting on Windows

### ISSUE THREAD

**Issue by MariaCamilaCubides** [sebhildebrandt/systeminformation#897]
**Describe the bug**
When utilizing the si.networkInterfaces() function on Windows, an abnormal network interface speed value was observed. The reported speed for an Ethernet interface was 9223372036854.775 Mbit/s, which is significantly higher than expected for a standard network interface. Upon further investigation, it was noticed that when the interface is not connected to a network, no speed value is displayed, potentially leading to the abnormal reported value

**To Reproduce**
1. Ensure the device has both Wi-Fi and Ethernet interfaces.
2. Disconnect the Ethernet interface while maintaining a connection to a Wi-Fi network.
3. Execute the si.networkInterfaces() function on a Windows system.
4. Observe the reported speed value for the Ethernet interface.

**Current Output**
I performed the test in several scenarios. The first scenario consisted of connecting to a Wi-Fi network and not connecting an Ethernet cable. In this scenario, the  Wi-Fi hardware properties that were displayed were those shown in the image.
![image](https://github.com/sebhildebrandt/systeminformation/assets/70594665/11660474-05c9-4f4e-9453-a639bd825965)
The ethernet properties were 
<img width="412" alt="image" src="https://github.com/sebhildebrandt/systeminformation/assets/70594665/d9a9a1df-81bd-4321-84b3-2708e1e2f189">
And the network interfaces result was
```
[
  {
	iface: 'Wi-Fi',
	ifaceName: 'Intel(R) Dual Band Wireless-AC 8260',
	ip4: '192.168.0.4',
	ip4subnet: '255.255.255.0',
	ip6: 'fe80::65d9:cf0b:fd71:de26',
	ip6subnet: 'ffff:ffff:ffff:ffff::',
	mac: 'f8:94:c2:af:44:f7',
	internal: false,
	virtual: false,
	operstate: 'up',
	type: 'wireless',
	duplex: '',
	mtu: '',
	speed: 866.7,
	dhcp: true,
	dnsSuffix: '',
	ieee8021xAuth: 'Unknown',
	ieee8021xState: 'Unknown',
	carrierChanges: 0
  },
  {
	iface: 'Ethernet',
	ifaceName: 'Intel(R) Ethernet Connection I219-V',
	ip4: '',
	ip4subnet: '',
	ip6: '',
	ip6subnet: '',
	mac: '54:e1:ad:a7:7b:81',
	internal: undefined,
	virtual: false,
	operstate: 'down',
	type: 'wired',
	duplex: '',
	mtu: '',
	speed: 9223372036854.775,
	dhcp: true,
	dnsSuffix: '',
	ieee8021xAuth: 'Unknown',
	ieee8021xState: 'Unknown',
	carrierChanges: 0
  }
]
```
In the second scenario, I disconnected the device from the Wi-Fi network and connected it via Ethernet. In that case, the hardware properties of the Wi-Fi interface were removed, leaving only the manufacturer, description, driver version, and MAC. On the other hand, the hardware properties of the Ethernet interface increased, and the speed began to be displayed. In the System Information result, it was displayed that the speed value for the Wi-Fi interface changed to 6, while for Ethernet it changed to 1000.

Finally, connecting the Wi-Fi interface to a network and the Ethernet interface showed that the speed was displayed in the hardware properties of both interfaces, and the result matched that of System Information, being 866.7 for Wi-Fi and 1000 for Ethernet.

**Expected behavior**
When the network interface is not connected to a network, the speed value should be null or undefined rather than reporting an abnormal value.

**Environment (please complete the following information):**
 - systeminformation package version: 5.22.0
 - OS: Windows 10 enterprise
 - Hardware: Lenovo Thinkpad 
 -  Node 16

**Comment by MariaCamilaCubides** [comment]
Hi @sebhildebrandt. I've tested the change on the device, and it works. Now it returns 0 when the interface is not connected to a network. Thank you very much for the prompt review.

**Comment by sebhildebrandt** [comment]
Thank you @MariaCamilaCubides for testing! Version 5.22.6 just released.
