### ISSUE TITLE
MacOS when IO80211BSSID is empty, si crashes.

### ISSUE THREAD

**Issue by parthiganesh** [sebhildebrandt/systeminformation#898]
**Describe the bug**
MacOS when IO80211BSSID is empty, si crashes.

**To Reproduce**
in wifiConnections(), while parsing IO80211BSSID, if the parameter is empty of <>, formatBssid function throws error

**Current Output**
```Uncaught TypeError: Cannot read properties of null (reading 'join')```

**Expected behavior**
Error should be handled

**Code Fix**
```js
function formatBssid(s) {
  s = s.replace(/</g, '').replace(/>/g, '').match(/.{1,2}/g) || [];
  return s.join(':');
}
```
**Environment (please complete the following information):**
 - systeminformation package version: 5.22.4
 - OS: macOS
 - Hardware MacBook Air M1

**Comment by sebhildebrandt** [comment]
@parthiganesh sorry, my fault. Fixed, Version 5.22.5 just published
