### ISSUE TITLE
SWAP is NaN

### ISSUE THREAD

**Issue by Buzut** [sebhildebrandt/systeminformation#9]
Because `free` in version 3.3.10 doesn't display `-/+ buffers/cache` any more, there's only two columns and line 3 (for swap) just doesn't exist.

A simple fix could be to count number of lines and act consequently…

**Comment by sebhildebrandt** [comment]
Thank you for your bug report!
I will make a fix for that next week ... super simple - as you pointed out :-)

**Comment by sebhildebrandt** [comment]
Ahhhhh I see, you already made a pull request for that also! Thank you!

**Comment by Buzut** [comment]
Not yet, but it's coming ;) 
Actually I patched my fork, but I don't really know how to proceed here. Fork again and fix at your point on master or what?

**Comment by sebhildebrandt** [comment]
OK, I will do it …
As i saw, the last column (1st line) also changed the meaning, So I anyway have to make a more deeper investigation. I am thinking maybe to access also /proc/meminfo … so this will take a bit to make that work again as wanted. 

I will let you know, when it is done.
Thank you once again for your report

Sebastian

**Comment by Buzut** [comment]
You're welcome!

**Comment by sebhildebrandt** [comment]
I still did not found the time to finalize/fix all  ... sorry (but I am working on it)

**Comment by Buzut** [comment]
No worries!

**Comment by sebhildebrandt** [comment]
Finalizing V 3.0 of systeminformation. I now have a proper implementation for both versions of `free`. Thank you for your support on this!

**Comment by sebhildebrandt** [comment]
`mem` is now also supporting changed output of free from procps-ng 3.3.10
