### ISSUE TITLE
How to add further support for CentOS 6?

### ISSUE THREAD

**Issue by jeghers** [sebhildebrandt/systeminformation#90]
Yes, I know CentOS 6 is an older version, but I'd love to add a few missing pieces there if it's not too hard to do, since I'll be using this server box for some time longer.  If someone can point me to the right part of the code, maybe I could help if you need.

In particular, it'd be great to add the OS-Information needs "distro" and "release" filled in, and I'd like to get something other than 'unknown' in network interface "operstate".

If I can help, let me know please.

**Comment by sebhildebrandt** [comment]
OK, I need to create a virtual machine with CentOS 6 to work on that. Please give me some time ... maybe I will have time for that during Christmas holiday season ... I will come back to you to test my changes ... OK for you?

**Comment by jeghers** [comment]
Sounds great, thanks!

**Comment by sebhildebrandt** [comment]
@jeghers Sorry I never got back to you. As now 3 years later, is there still a need for CentOS 6 support? If yes, I will try to work on it. But for now, I will close this issue.

FYI: I just released a new version 5.0. Be aware: Version 5 is NOT fully backwards compatible to version 5 ... see https://systeminformation.io/changes.html to get an overview over all breaking changes.

**Comment by jeghers** [comment]
Well, being on CentOS 7 now, and planning to go to RHEL or Ubuntu soon, it's not too pressing at this point.  If you have other users on CentOS 6 you might want to consider supporting it for them maybe.
