### ISSUE TITLE
Compatibility issue systeminformation v5

### ISSUE THREAD

**Issue by jpeig** [sebhildebrandt/systeminformation#902]
npx systeminformation info

Returns:

  "cpu": {
    "manufacturer": "",
    "brand": "",
    "vendor": "",
    "family": "",
    "model": "",
    "stepping": "",
    "revision": "",
    "voltage": "",
    "speed": null,
    "speedMin": null,
    "speedMax": null,
    "governor": "",
    "cores": 24,
    "physicalCores": 24,
    "performanceCores": 24,
    "efficiencyCores": 0,
    "processors": 1,
    "socket": "",
    "flags": "de pse tsc sep mtrr mca cmov psn clfsh ds mmx fxsr sse sse2 ss htt tm ia64 pbe",
    "virtualization": false,
    "cache": {
      "l1d": 0,
      "l1i": 0,
      "l2": 0,
      "l3": 0
    }
  }

npx systeminformation@4 info

Returns:

  "cpu": {
    "manufacturer": "AMD",
    "brand": "Ryzen 9 5900X 12-Core Processor",
    "vendor": "AuthenticAMD",
    "family": "25",
    "model": "33",
    "stepping": "2",
    "revision": "8450",
    "voltage": "",
    "speed": "3.70",
    "speedmin": "",
    "speedmax": "3.70",
    "governor": "",
    "cores": 24,
    "physicalCores": 12,
    "processors": 1,
    "socket": "AM4",
    "cache": {
      "l1d": 0,
      "l1i": 0,
      "l2": 6291456,
      "l3": 67108864
    },
    "flags": "de pse tsc sep mtrr mca cmov psn clfsh ds mmx fxsr sse sse2 ss htt tm ia64 pbe"
  },

Appears to be some sort of compatbility issue.
Any known reasons? I am using Windows.

**Comment by sebhildebrandt** [comment]
@jpeig this probably due to `wmic` deprecation on windows side. We had to switch to powershell to determine system stats. Here the version of powershell is also important ... :-( 

Can you provide your exact windows version and powershell version to prove that this is the reason?

**Comment by sebhildebrandt** [comment]
Closing it for now ... no further information provided by reporter ...
If you have further information oj this, feel free to reopen this issue.
