### ISSUE TITLE
si.diskLayout and si.memLayout

### ISSUE THREAD

**Issue by ubikOne** [sebhildebrandt/systeminformation#92]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

Run in electron app and show information about disk and ram

### Actual behavior

in case of disk
in browser console output error:

/home/ubikone/Projekty/kontrolki/node_modules/systeminformation/lib/filesystem.js:587 Uncaught TypeError: Cannot read property '1' of null
    at /home/ubikone/Projekty/kontrolki/node_modules/systeminformation/lib/filesystem.js:587:64
    at Array.forEach (native)
    at /home/ubikone/Projekty/kontrolki/node_modules/systeminformation/lib/filesystem.js:577:21
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)

in terminal output:

cat: /sys/block/cdrom/queue/rotational: Nie ma takiego pliku ani katalogu

incase of ram:
there ids no output and error

### Steps to reproduce the problem

full code at https://gitlab.com/ubikOne/kontrolki/tree/master/js

problem is with funtcion at line 133 driveShow and line 105 ramShow in sysinfo.js

### Specifications 

- package version: 3.33.6 
- operating system: Ubuntu 16.04 4.14.0-041400-generic
- hardware: A8-4500M APU with Radeon(tm) HD Graphics, 8 GB RAM, SSD

### Problem and possible solution

about disk i can have problem with: const sizeValue = sizeString.match(/\(([^)]+)\)/)[1];
line 587 in lib/filesystem.js

about ram i have no idea what is going on.

on windows 10 it's working ok

**Comment by sebhildebrandt** [comment]
Hi, I published a fix for the `diskLayout()` yesterday (v3.33.7). Can you recheck, if this is working on your side? For the `memLayout()` I will try to find a solution asap ...

**Comment by ubikOne** [comment]
I'll check diskLayout in evening, and replay with information.

**Comment by ubikOne** [comment]
there is a little progress... no errors on browser console, but still display anything, and system terminal returns the same problem.
![kontrolki](https://user-images.githubusercontent.com/13407713/33456689-694878aa-d620-11e7-972e-a1c0c8d18075.png)

**Comment by sebhildebrandt** [comment]
Hi again,

can you post (for disk layout) the output of 

```export LC_ALL=C; lshw -class disk; unset LC_ALL```

and (for mem layout) of

```
dmidecode -t memory
```

in a bash console?

Thank you in advance

**Comment by ubikOne** [comment]
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.

Handle 0x0005, DMI type 5, 20 bytes
Memory Controller Information
	Error Detecting Method: None
	Error Correcting Capabilities:
		None
	Supported Interleave: One-way Interleave
	Current Interleave: One-way Interleave
	Maximum Memory Module Size: 8192 MB
	Maximum Total Memory Size: 16384 MB
	Supported Speeds:
		Other
		Unknown
		70 ns
		60 ns
		50 ns
	Supported Memory Types:
		Other
		Unknown
		Standard
		FPM
		SIMM
		Burst EDO
	Memory Module Voltage: 3.3 V
	Associated Memory Slots: 2
		0x0006
		0x0007
	Enabled Error Correcting Capabilities:
		None
		Single-bit Error Correcting
		Double-bit Error Correcting
		Error Scrubbing

Handle 0x0006, DMI type 6, 12 bytes
Memory Module Information
	Socket Designation: DIMM 0
	Bank Connections: None
	Current Speed: 1 ns
	Type: DIMM
	Installed Size: 4096 MB (Single-bank Connection)
	Enabled Size: 4096 MB (Single-bank Connection)
	Error Status: OK

Handle 0x0007, DMI type 6, 12 bytes
Memory Module Information
	Socket Designation: DIMM 0
	Bank Connections: None
	Current Speed: 1 ns
	Type: DIMM
	Installed Size: 4096 MB (Single-bank Connection)
	Enabled Size: 4096 MB (Single-bank Connection)
	Error Status: OK

Handle 0x0022, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: None
	Maximum Capacity: 8 GB
	Error Information Handle: 0x0027
	Number Of Devices: 2

Handle 0x0023, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x0022
	Error Information Handle: 0x0025
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 4096 MB
	Form Factor: SODIMM
	Set: None
	Locator: DIMM 0
	Bank Locator: CHANNEL A
	Type: DDR3
	Type Detail: Synchronous Unbuffered (Unregistered)
	Speed: 667 MHz
	Manufacturer: Not Specified
	Serial Number: 00000000
	Asset Tag: Asset Tag: 
	Part Number: GR1333S364L9S/4G
	Rank: 1
	Configured Clock Speed: 667 MHz

Handle 0x0024, DMI type 17, 34 bytes
Memory Device
	Array Handle: 0x0022
	Error Information Handle: 0x0026
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 4096 MB
	Form Factor: SODIMM
	Set: None
	Locator: DIMM 0
	Bank Locator: CHANNEL B
	Type: DDR3
	Type Detail: Synchronous Unbuffered (Unregistered)
	Speed: 667 MHz
	Manufacturer: Not Specified
	Serial Number: 00000000
	Asset Tag: Asset Tag: 
	Part Number: GR1333S364L9S/4G
	Rank: 1
	Configured Clock Speed: 667 MHz

**Comment by ubikOne** [comment]
![lc](https://user-images.githubusercontent.com/13407713/33479410-41184cb2-d68d-11e7-980d-a931ccdcb812.png)

**Comment by sebhildebrandt** [comment]
And if you call `diskLayout()` and `memLayout()` directly from node ... what is the exact output?

Like so: 

``` 
const si = require('systeminformation');

si.diskLayout()
	.then(data => console.log(data))
	.catch(error => console.error(error));
```

**Comment by ubikOne** [comment]
![test](https://user-images.githubusercontent.com/13407713/33479992-7ff933f4-d68f-11e7-92cb-61bdf8ca06a1.png)

**Comment by sebhildebrandt** [comment]
Thank you ... and for `memLayout()`?

**Comment by sebhildebrandt** [comment]
... and one more question ... did you try to run the above node.js code as root? Like you did with the underlying commands (previous email)

**Comment by ubikOne** [comment]
diskLaout() with sudo works

![sudo](https://user-images.githubusercontent.com/13407713/33480177-7a59fa7c-d690-11e7-8e3b-6ac94a39fb8f.png)

**Comment by ubikOne** [comment]
memLaout() without sudo 

![without](https://user-images.githubusercontent.com/13407713/33480240-b77a4bdc-d690-11e7-803b-f73eddb77a75.png)

with sudo 

![with](https://user-images.githubusercontent.com/13407713/33480245-c0556124-d690-11e7-8b1c-74a28f2887fe.png)

**Comment by sebhildebrandt** [comment]
So I need to check, if I find a solution non non-sudos ... Will provide an answer this weekend, OK?

**Comment by ubikOne** [comment]
Fine for me

**Comment by ubikOne** [comment]
bois() the same story as memLayuot() and diskLayout(), no visible without sudo

**Comment by sebhildebrandt** [comment]
I am closing this for now as I do not see this really as a bug. There are several functions that - depending on which OS - might need root or admin privileges. I try to keep this as low as possible but where I didn't (yet) found a solution without admin privileges I at least implemented a version the can get correct values with admin privileges. Anyway I will investigate, if I can get values (at least some of them) without being admin.
