### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by OnlyForward0613** [sebhildebrandt/systeminformation#926]
I am trying to use this module in electron + next.js to get cpu information.
But got failed due to can't find module error about child_process but I installed that module correctly.
How can i fix that?

**Comment by sebhildebrandt** [comment]
@OnlyForward0613  Please have a look on some other issues opened here with errors in electron. Mostly this is a version problem not really related to the implementation of this package. If you find a solution, feel free to post your findings here so that others also can find it.
