### ISSUE TITLE
windows 24H2 version not support

### ISSUE THREAD

**Issue by xwenzheng** [sebhildebrandt/systeminformation#938]
**Describe the bug**

in latest windows system call error：invoking remote method "get-machines-info": Error : Command failed: failed wmic path win32_VideoController

**To Reproduce**
1. used function '...'
2. code snippet '....'
3. start app / code
4. See output/error '....'

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
 - systeminformation package version: "5.23.5",
 - OS: Windows11 24H2
 - Hardware [e.g. MacBook Pro 13]

To get all needed environment information, please run the following command:

```
  npx systeminformation info
```

**Additional context**

**Comment by wald-tq** [comment]
Sorry to read that. 
Seems that systeminformation is also using wmic which is deprecated in 24H2: 

https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242

I am also looking for a solution to read wmi with nodejs without wmic with nodejs / electron.

**Comment by sebhildebrandt** [comment]
@wald-tq @xwenzheng ... since version  5.9.7. we removed the use of `wmic` (as it is deprecated - see also https://github.com/sebhildebrandt/systeminformation/issues/616). Anyway, there seems to be an issue in `powershell` calling:

```
Get-CimInstance win32_VideoController | fl *
```

Can you confirm that this is not longer working (when calling this from powershell)?

Thank you for testing.

**Comment by wald-tq** [comment]
@sebhildebrandt thanks, I solved it in my app by calling powershell. I didn't know that you already solved that in your library.


    Get-CimInstance win32_VideoController | fl *


This command works on my laptop with Windows 10

**Comment by Spartan-Hex-Shadow** [comment]
@sebhildebrandt will this issue be resolved in the complete rewrite (6.0)?

**Comment by sebhildebrandt** [comment]
@Spartan-Hex-Shadow @xwenzheng @wald-tq ... the latest version 5.23.11 does not use `wmic`. I am using `Get-CimInstance win32_VideoController | fl *` (see line 831) ... can you try it once again and provide the full error message?

**Comment by Spartan-Hex-Shadow** [comment]
> @Spartan-Hex-Shadow @xwenzheng @wald-tq ... the latest version 5.23.11 does not use `wmic`. I am using `Get-CimInstance win32_VideoController | fl *` (see line 831) ... can you try it once again and provide the full error message?

Just realized i was running on an old version. I do not see the error anymore, thank you!

**Comment by sebhildebrandt** [comment]
@wald-tq @Spartan-Hex-Shadow @xwenzheng ... then I can close this issue, right. If you still have any errors, please feel free to reopen this ticket.
