### ISSUE TITLE
osInfo does not return FQDN

### ISSUE THREAD

**Issue by VeloAddict** [sebhildebrandt/systeminformation#939]
https://github.com/sebhildebrandt/systeminformation/blob/3a92931c7d46605ffddc1aacb97a9727273b2888/lib/osinfo.js#L171

`hostnamectl` does not provide the Fully Qualified Domain Name (FQDN) or domain name directly when you query it. It only deals with the static hostname (short hostname), pretty hostname, and transient hostname.

For linux use the `hostname -f` command to get the Fully Qualified Domain Name.

**Comment by sebhildebrandt** [comment]
@VeloAddict ... fixed. Version 5.23.21 just released. Can you check it on your side?
