### ISSUE TITLE
Source of process memory information on Windows

### ISSUE THREAD

**Issue by paul-bell** [sebhildebrandt/systeminformation#94]
Hello again, Sebastian.

I've begun using si under Windows Server 2016 and noticed some differences between the process memory usage reported by Windows Task Manager and the mem_vsz/mem_rsz values that si reports as properties in the list of processes returned by si.processes().

An example: si reports "Process A" as follows: 

mem_vsz: 16980
mem_rss:  24100

But Task Manager reports "Memory (private working set)" for the same process as 13572K.

No obvious relationship among these numbers jumps out at me. That said, I suppose the fact that Windows is running under VMware might have an adulterating effect, but I am not sure of this.

Can you tell me from where these mem_vsz/mem_rss values come?

### Specifications 

- package version: 3.33.6
- operating system: Windows Server 2016
- hardware: 

Thank you.

-Paul

**Comment by sebhildebrandt** [comment]
So after some time I made again a research on that:

- mem_rss is the WorkingSetSize (in Task Manager the "Memory – Working Set", not the "Memory – Private Working Set" shown as a default) ... both should be the same (which is the case on my machine).
- mem_vsz is the PageFileUsage = amount of page file space that a process is using currently, not shown in the task manager.

Both are in kb. So this should be correct ... at least as I could find out.
