### ISSUE TITLE
wifiConnections() returns empty array on windows 11

### ISSUE THREAD

**Issue by lak-16** [sebhildebrandt/systeminformation#943]
**Describe the bug**
Hi, wifiConnections() returns empty array on windows 11 and wifiNetworks() returns all the wifi networks available. Is there a way to know to which wifi system is connected as well?

**To Reproduce**
Try run below from windows 11 machine from node js app.
const si = require('systeminformation');
async function main() {
    const wifis = await si.wifiConnections();
    const wifisNet = await si.wifiNetworks()
    console.log(wifis, "wifi conections");
    console.log(wifisNet, "wifi networks");
}
main(); 

**Current Output**
There is no way to know to which network system is connected to.

**Expected behavior**
Need connected status for networks available

**Environment (please complete the following information):**
 - systeminformation package version: 5.23.5
 - OS: Windows 11
 - Hardware: LENOVO, ThinkPad P14s Gen 4

**Comment by parthiganesh** [comment]
@sebhildebrandt 

## Root cause
Windows command `netsh wlan show interfaces` returns BSSID with label `AP BSSID`

![image](https://github.com/user-attachments/assets/383e29c0-a8b6-4825-b218-6c2315257f82)



## Solution
File wifi.js
Function: wifiConnections
Line: 703
```js
const bssid = util.getValue(lines, 'BSSID', ':', true) || util.getValue(lines, 'AP BSSID', ':', true);
```

**Comment by sebhildebrandt** [comment]
@lak-16 @parthiganesh ... I have never seen `AP BSSID` as a label since now. So 2 questions:

@lak-16 : can you confirm, that o your machine it is also labeled the way
@parthiganesh : any idea WHY it has this label?

Thank you in advance

**Comment by sebhildebrandt** [comment]
@lak-16 @parthiganesh ... Version 5.23.13 just released, can you test it on your side? 

@lak-16 : If it does not work on your side, can you provide the output (powershell) of 

```
netsh clan show interfaces
```

Thank you in advance.
