### ISSUE TITLE
<SSID Redacted>

### ISSUE THREAD

**Issue by Hujinna** [sebhildebrandt/systeminformation#945]
**Describe the bug**
MacOS 15.0 cannot get current ssid return  SSID Redacted

**To Reproduce**
run command
`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I 2>/dev/null; echo "######" ; ioreg -n AppleBCMWLANSkywalkInterface -r 2>/dev/null `

ssid value return  SSID Redacted

**Environment (please complete the following information):**
 - systeminformation package version:5.22.7
 - OS Sequoia 15.0
 - Hardware MacBook M1 Pro

**Comment by parthiganesh** [comment]
@sebhildebrandt 

You can use the following alternate command:
```
system_profiler SPAirPortDataType | awk '/Current Network/ {getline;$1=$1;print $0 | "tr -d ':'";exit}'
```

Also Airport command is deprecated. 
```
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport   
WARNING: The airport command line tool is deprecated and will be removed in a future release.
```
