### ISSUE TITLE
inetChecksite does not work on Alpine Linux Docker Image

### ISSUE THREAD

**Issue by timheerwagen** [sebhildebrandt/systeminformation#949]
**Describe the bug**
Within a Nodejs environment on a 22-alpine Docker image, the `inetChecksite` always returns 404. 

I'm trying to check the availability of a different domain on the same server in a different Docker image. Say, from nodejs backend of admin.example.com I am trying to check if example.com is available.

Also when I try to check if http://localhost:3000 is available, I get 404.

I have written a small script myself with the https package that works on Alpine.

```ts
import https from "https";

const checkWebsite = async (url: string): Promise<boolean> => {
  return new Promise((resolve) => {
    https
      .get(url, function ({ statusCode }) {
        resolve(
          statusCode === 200 ||
            statusCode === 301 ||
            statusCode === 302 ||
            statusCode === 304
        );
      })
      .on("error", function (e) {
        resolve(false);
      });
  });
};
```

**To Reproduce**
1. Host a nodejs app on node/22-alpine image
2. use inetChecksite

**Current Output**
```json
{"url":"https://example.com","ok":false,"status":404,"ms":null}
```

**Expected behavior**
Correct status and ok: true

**Environment (please complete the following information):**
 - systeminformation package version: ^5.23.5
 - OS: Alpine Linux
 - Hardware VPS

**Comment by sebhildebrandt** [comment]
Hi @timheerwagen, well yes, Alpine Linux does not include `curl` ... so I will rewrite this function to use nodes `http` and `https` ... then it is also more easy as I do not have to distinguish OS versions. Will provide a fix tomorrow.

**Comment by sebhildebrandt** [comment]
@timheerwagen Version 5.23.19 just released ... Can you test it on your side? 
Happy holidays ...

**Comment by timheerwagen** [comment]
Thank you for your great work, I will have a look at it in the next few days. Happy holidays.
