### ISSUE TITLE
The Win7 system uses the diskLayout method to return an empty array

### ISSUE THREAD

**Issue by yangbin11** [sebhildebrandt/systeminformation#950]
**Describe the bug**
使用si.diskLayout() 函数查出空数组

**To Reproduce**
si.diskLayout()

**Current Output**
If applicable, add output to help explain your problem.

**Expected behavior**

**Environment (please complete the following information):**
systeminformation :4.0.7
platform:window
release:6.1.7601
kernel:6.1 .7601
arch:X64
hostname:USER-ONVAR3H3DM

To get all needed environment information, please run the following command:

```
  npx systeminformation info
```

**Additional context**

**Comment by sebhildebrandt** [comment]
@yangbin11 can you describe the problem in English ? My Chinese is actually not good enough. Please change title ad add a clear description. Thank you in advance!

**Comment by yangbin11** [comment]
> 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！



> 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！

Use the si.diskLayout function to find empty arrays, system information version 4.0.7

**Comment by yangbin11** [comment]
> > 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！
> 
> > 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！
> 
> 使用 si.diskLayout 函数查找空数组，系统信息版本 4.0.7



> > 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！
> 
> > 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！
> 
> 使用 si.diskLayout 函数查找空数组，系统信息版本 4.0.7



> > 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！
> 
> > 你能用英语描述一下问题吗？我的中文其实还不够好。请更改标题广告添加清晰的描述。提前感谢您！
> 
> Use the si.diskLayout function to find empty arrays, system information version 4.0.7

My description is incorrect. When I do not insert the recording pen device, it can recognize the disk array information. After inserting the recording pen, it returns an empty array

**Comment by yangbin11** [comment]
@sebhildebrandt  Brother, I'm sorry.. Why haven't you replied to me yet? I understand that Win7 supports up to Node13 version, but currently my application is installed on version 16. I'm not sure if this issue is causing it

**Comment by sebhildebrandt** [comment]
@yangbin11 ... when you are using version 4.0.7 of systeminformation, this is a 6 year old version. Can you check it also with the latest version?

**Comment by yangbin11** [comment]
@sebhildebrandt I am glad to receive your reply. In fact, I have tested version 5.23, but unfortunately using diskLayout returns an empty array. When I use version 4.0.7 without inserting a recording pen USB device, the expected disk array information can be returned on Win7, while debugging with a recording pen USB device returns an empty array. I'm not sure if my description is clear...

**Comment by sebhildebrandt** [comment]
@yangbin11 can you exec (powershell) the following two commands (and post the output as text here) ... two times - WITHOUT your USB stick and WITH your USB stick connected:

```
Get-CimInstance Win32_DiskDrive | select * | fl
Get-PhysicalDisk | select * | fl
```

Thank you in advance!

**Comment by yangbin11** [comment]
@sebhildebrandt  On my Windows 7 computer, neither of these commands can be recognized

+ Get-CimInstance <<<<  Win32_DiskDrive | select * | fl
    + CategoryInfo          : ObjectNotFound: (Get-CimInstance:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
    + Get-CimInstance <<<<  Win32_DiskDrive | select * | fl
    + CategoryInfo          : ObjectNotFound: (Get-CimInstance:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sebhildebrandt** [comment]
@yangbin11 can you check your powershell version? In powerchell execute:

```
$PSVersionTable
```

**Comment by yangbin11** [comment]
@sebhildebrandt 


 PS C:\Users\Administrator> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1

**Comment by sebhildebrandt** [comment]
Ok, you need to upgrade to at lease Powershell Version 3. Version 2 is outdated:

Release Dates

| Version | Release Date |
|----|----|
| Windows PowerShell 3.0 | Oct-2012 |
| Windows PowerShell 2.0 | Jul-2009 |

**Comment by yangbin11** [comment]
@sebhildebrandt Unfortunately, I am unable to inform the user to perform the upgrade operation. Do I have any solutions to handle compatibility with lower versions

**Comment by sebhildebrandt** [comment]
@yangbin11 unfortunately not. As I had to move to powershell commands due to `WMIC` deprecation in Windows 10, I cannot support older versions...

**Comment by yangbin11** [comment]
@sebhildebrandt Understood, thank you
