### ISSUE TITLE
si.time() doesn't react on timezone change

### ISSUE THREAD

**Issue by NikitaMikhaliuk** [sebhildebrandt/systeminformation#952]
**Describe the bug**
si.time() doesn't react on timezone change if called in the same node process after timezone set

**To Reproduce**
1. Make sure you have the latest systeminformation version installed:
```
npm install systeminformation
```
2. Open Terminal, run Node.js as a REPL with `node` command
3. Run following code in REPL to display your current timezone:
```
const si = require("systeminformation");
si.time();
```
it will print the following object: 
```
{
  current: 1733843689750,
  uptime: 1208122.15,
  timezone: 'GMT+0100',
  timezoneName: 'Europe/Warsaw'
}
```
4. In another terminal window change your timezone via `timedatectl` to any other (e.g. UTC):
```
sudo timedatectl set-timezone UTC
```
6. In the first terminal window repeat the `si.time()` command

**Current Output**
```
> si.time()
{
  current: 1733843765711,
  uptime: 1208198.11,
  timezone: 'GMT+0100',
  timezoneName: 'Europe/Warsaw'
}
```

**Expected behavior**
Should display the changed timezone
```
> si.time()
{
  current: 1733843802973,
  uptime: 1208235.37,
  timezone: 'GMT+0000',
  timezoneName: 'UTC'
}
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.23.8
 - OS: Ubuntu 22.04.5 LTS
 - Hardware:
    Manufacturer: Dell Inc.
    Model: Vostro 3500
    Manufacturer     : Intel
    Brand            : Gen Intel® Core™ i7-1165G7
    Family           : 6
    Model            : 140
    Cores            : 8
    Physical Cores    : 4
    Performance Cores : 4
    Efficiency Cores  : 
    Processors       : 1

**Additional context**
1. If I exit the node REPL, start it again and run the same code from step 3., it displays the changed timezone, so it seems like some sort of caching issue
2. Had a look at the source code, it reads `current`, `timezone` and `timezoneName` values from the built-in Date object:
```
function time() {
  let t = new Date().toString().split(' ');
  return {
    current: Date.now(),
    uptime: os.uptime(),
    timezone: (t.length >= 7) ? t[5] : '',
    timezoneName: Intl ? Intl.DateTimeFormat().resolvedOptions().timeZone : (t.length >= 7) ? t.slice(6).join(' ').replace(/\(/g, '').replace(/\)/g, '') : ''
  };
}
```
And it looks like Node.js is caching the timezone value when starting a node process:
[node process does not reflect timezone changes #33805](https://github.com/nodejs/node/issues/33805)
[is it a bug? setting up process.env.TZ depends on order of execution. #3449](https://github.com/nodejs/node/issues/3449)

Is there some way to read the timezone directly from os instead of Node.js Date/TZ env var?

**Comment by sebhildebrandt** [comment]
@NikitaMikhaliuk ... thank you for discovering this and your initial research! Sure, reading TZ from the os would be the best way. Give me one day to publish a new release. Regards.

**Comment by sebhildebrandt** [comment]
@NikitaMikhaliuk I already have implemented it ad will test ist today. Release should be ready by tomorrow.

**Comment by sebhildebrandt** [comment]
@NikitaMikhaliuk Version 5.23.10 just released, can you test it on your side?

**Comment by NikitaMikhaliuk** [comment]
@sebhildebrandt Great, thanks for your work. Was able to test on my system. `timezoneName` is updated correctly, but there are some issues with the `timezone` property:
```
> const si = require('systeminformation')
undefined
> si.time()
{
  current: 1734000335426,
  uptime: 1364767.82,
  timezone: 'UTC+0000',
  timezoneName: 'UTC'
}
> si.time()
{
  current: 1734000360592,
  uptime: 1364792.99,
  timezone: 'CET+0100',
  timezoneName: 'Europe/Warsaw'
}
> si.time()
{
  current: 1734000372192,
  uptime: 1364804.59,
  timezone: '+03+0300',
  timezoneName: 'Europe/Minsk'
}
> si.time()
{
  current: 1734000383493,
  uptime: 1364815.89,
  timezone: '+04+0400',
  timezoneName: 'Asia/Tbilisi'
}
```
Looks like it has duplicated output in some cases

**Comment by sebhildebrandt** [comment]
Hi @NikitaMikhaliuk can you provide the output of 

```
date +%Z && date +%z && ls -l /etc/localtime
```

in those cases on your machine as I was not able to reproduce it?

Thank you in advance.

**Comment by NikitaMikhaliuk** [comment]
@NikitaMikhaliuk I would rather ignore it, or just add general "GMT'' prefix

**Comment by NikitaMikhaliuk** [comment]
@sebhildebrandt  I would rather ignore it, or just add general "GMT'' prefix

**Comment by sebhildebrandt** [comment]
@NikitaMikhaliuk Version 5.23.11. just released. Should be fine now. Can you once again try it on your side?

**Comment by NikitaMikhaliuk** [comment]
@sebhildebrandt Was able to test - working as expected. Thanks for your work!
