### ISSUE TITLE
Command failed: date +%Z && date +%z && ls -l /etc/localtime 2>/dev/null

### ISSUE THREAD

**Issue by SheldonWBM** [sebhildebrandt/systeminformation#954]
**Describe the bug**
`Command failed: date +%Z && date +%z && ls -l /etc/localtime 2>/dev/null`

caused by: 
```
import si from 'systeminformation'
...
const time = await si.time().current;
```

**Environment (please complete the following information):**
 - systeminformation package version: "^5.23.10"
 - OS: Ubuntu Linux

**Additional context**
Error after bumping package to `5.23.10`.
systeminformation: `^5.23.9` has no issues.
This is likely caused by "time() changed retrieval of timezones (linux, macOS)"
https://github.com/sebhildebrandt/systeminformation/commit/5993adeb796651c5865632136d021aac91a3b935

**Comment by sebhildebrandt** [comment]
@SheldonWBM ... spult be fixed now. Version 5.23.11 just released. Can you try it on your side?

**Comment by SheldonWBM** [comment]
It is fixed. Thank you :+1:
