### ISSUE TITLE
MacBook Model and Chassis Type is not identified correctly since apple M2

### ISSUE THREAD

**Issue by parthiganesh** [sebhildebrandt/systeminformation#955]
**Describe the bug**
Prior to Apple M2, model identifier had keyword `MacBookAir` (eg: MacBookAir10,1) which helped systeminformation.io to categorize chassis type as Notebook. Now, we should maintain a mapping to match the model identifier to find chassis type and model.

```sh
# MacBook Air (M1, 2020)
ioreg -c IOPlatformExpertDevice -d 2 | grep \"model\"
"model" = <"MacBookAir10,1">
```
```sh
# MacBook Air (13-inch, M3, 2024)
ioreg -c IOPlatformExpertDevice -d 2 | grep \"model\"
"model" = <"Mac15,12">
```

**References:** 
1. MacBook Air models: https://support.apple.com/en-ae/102869
2. MacBook Pro models: https://support.apple.com/en-ae/108052
3. MacBook models: https://support.apple.com/en-ae/103257
4. Mac Studio models: https://support.apple.com/en-ae/102231
5. Mac Mini models: https://support.apple.com/en-ae/102852
6. iMac models: https://support.apple.com/en-ae/108054
7. Mac Pro models: https://support.apple.com/en-ae/102887

**To Reproduce**
Following function needs update
1. macOsChassisType()
2. chassis()

**Current Output**
```js
chassis.model = Mac
chassis.type = Other
chassis.version = Mac15,12
```

**Expected behavior**
```js
chassis.model = MacBookAir
chassis.type = Notebook
chassis.version = MacBook Air (13-inch, M3, 2024)
```

**Environment (please complete the following information):**
 - systeminformation package version: 5.23.13
 - OS: [e.g. macOS]
 - Hardware [e.g. MacBook Air 13, M3]

**Comment by sebhildebrandt** [comment]
@parthiganesh Thank you! Will provide a fix for this tomorrow!

**Comment by parthiganesh** [comment]
@sebhildebrandt 
I have compiled the mac models in json format. Hope this helps
[mac_models.json](https://github.com/user-attachments/files/18149987/mac_models.json)

**Comment by sebhildebrandt** [comment]
@parthiganesh I made a first version with something like this as a return value:

```
{
  manufacturer: 'Apple Inc.',
  model: 'MacBook Pro',
  type: 'Notebook',
  version: 'MacBook Pro (14-inch, M1 Pro, 2021)',
  serial: '..........',
  assetTag: '....',
  sku: '....'
}
```

Not yet published but in the master branch. Can you test it on your side?

**Comment by sebhildebrandt** [comment]
@parthiganesh ... I thought a little bit about that. I think it would be better to return the model key in `model` ... which would then be:

```
{
  manufacturer: 'Apple Inc.',
  model: 'MacBookPro18,3',
  type: 'Notebook',
  version: 'MacBook Pro (14-inch, M1 Pro, 2021)',
  serial: '..........',
  assetTag: '....',
  sku: '....'
}
```

... as the name is anyway there in `version`.

**Comment by sebhildebrandt** [comment]
@parthiganesh version 5.23.14 just released. Can you check it on your side?

**Comment by parthiganesh** [comment]
@sebhildebrandt fixed. thank you.
