### ISSUE TITLE
/format=csv not working on Win7 and some Win 8/8.1/10

### ISSUE THREAD

**Issue by itpimp** [sebhildebrandt/systeminformation#96]
### Issue Type

* Bug

### Expected behavior 
- Return the WMIC calls.

### Actual behavior
- Throws error and returns nothing

### Steps to reproduce the problem
- Using Windows 7 Ultimate SP1

### Specifications 

- package version: 3.33.8
- operating system: Windows 7 Ultimate
- hardware: I7 / 8GB RAM / 250GB SSD

### Problem and possible solution
https://stackoverflow.com/questions/9673057/wmic-error-invalid-xsl-format-in-windows7
https://social.msdn.microsoft.com/Forums/en-US/a9beeed3-99f0-4627-ba1e-aa0161fa58c9/wmic-invalid-xsl-format-or-file-name?forum=windowsgeneraldevelopmentissues#be9e599a-5cd8-4238-9918-df650a98c66b

Option 1: Use rawxml instead of CSV. Best option, as all come with the XML format.
Option 2: Ship the CSV with the app. Not good, as it'll cause future incompatibilities.
Option 3: Use standard tabular / plaintext output and parse from there.
Option 4: Apply the fix in SO link. Problem here is not everybody is on en-US.
Option 5: Change the return format to exclude /format and parse the plaintext response.

**Comment by sebhildebrandt** [comment]
Can you provide more information?
- which function you are calling
- what is the output of the error

**Comment by sebhildebrandt** [comment]
And - if possible - what is the output of the underlying WMIC-Command (the way I am calling it from within systeminformation.

**Comment by sebhildebrandt** [comment]
The reason, why I am asking is, that I also tested on Win 7 without any problems

**Comment by sebhildebrandt** [comment]
As far as I see, there is only one WMIC call with /format ...`blockDevices()`. So can you provide the output (from your console) of:

```
wmic logicaldisk get Caption,Description,DeviceID,DriveType /format:csv
```

as well as 

```
wmic logicaldisk get Caption,Description,DeviceID,DriveType /value
```

Thank you in advance.

**Comment by itpimp** [comment]
Thanks for quick response!

I run CLI:
C:\Users\Richard>wmic logicaldisk get Caption,Description,DeviceID,DriveType,FileSystem,FreeSpace,Name,Size,VolumeName,VolumeSerialNumber /format:csv
Invalid XSL format (or) file name.

**Comment by sebhildebrandt** [comment]
Can you also try the second one ...

```
wmic logicaldisk get Caption,Description,DeviceID,DriveType /value
```

**Comment by itpimp** [comment]
Comes through perfect

**Comment by itpimp** [comment]
C:\Users\Richard>wmic logicaldisk get Caption,Description,DeviceID,DriveType /va
lue


Caption=B:
Description=Network Connection
DeviceID=B:
DriveType=4


Caption=C:
Description=Local Fixed Disk
DeviceID=C:
DriveType=3


Caption=D:
Description=Local Fixed Disk
DeviceID=D:
DriveType=3


Caption=E:
Description=CD-ROM Disc
DeviceID=E:
DriveType=5

**Comment by sebhildebrandt** [comment]
OK. Will rewrite the function to use /value ... expect a version patch by tomorrow. OK?

**Comment by itpimp** [comment]
You're the MAN! Thanks!

**Comment by sebhildebrandt** [comment]
Already fixed. Version 3.33.10 published

**Comment by itpimp** [comment]
Awesome! Testing. Thanks.
