### ISSUE TITLE
missing bios data

### ISSUE THREAD

**Issue by ocpra** [sebhildebrandt/systeminformation#98]
### Issue Type

* [x ] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
  bios:
   { vendor: 'innotek GmbH',
     version: 'VirtualBox',
     releaseDate: '12/01/2006',
     revision: '' },
- 
- 
- 

### Actual behavior
  bios:
   { vendor: 'innotek GmbH',
     version: 'VirtualBox',
     releaseDate: ,
     revision: '' },
- 
- 
- 

### Steps to reproduce the problem
node
> var si=require("systeminformation")
undefined
> si.getStaticData(function(data) { console.log(data) });
-
-
-

### Specifications 

- package version:> '3.33.11'
- operating system: Ubuntu 16.04.3
- hardware:Virtualbox

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ... 

Seem to have couple issues
First I guess is OS specific that dmidecode is required to be setuid root

2nd seems to be bug in system.js and util.js and following patch should fix it

$ diff -Naur systeminformation systeminformation.new/
diff -Naur systeminformation/lib/system.js systeminformation.new/lib/system.js
--- systeminformation/lib/system.js	2017-12-25 15:24:37.892460459 -0500
+++ systeminformation.new/lib/system.js	2017-12-25 15:19:38.645901745 -0500
@@ -207,7 +207,7 @@
             result.vendor = util.getValue(lines, 'Vendor');
             result.version = util.getValue(lines, 'Version');
             const datetime = util.getValue(lines, 'Release Date');
-            result.releaseDate = datetime.date;
+            result.releaseDate = datetime.date || datetime;
             result.revision = util.getValue(lines, 'BIOS Revision');
           }

diff -Naur systeminformation/lib/util.js systeminformation.new/lib/util.js
--- systeminformation/lib/util.js	2017-12-25 15:24:17.628004833 -0500
+++ systeminformation.new/lib/util.js	2017-12-25 15:21:08.847835491 -0500
@@ -66,7 +66,7 @@
   trimmed = trimmed || false;
   for (let i = 0; i < lines.length; i++) {
     let line = lines[i].toLowerCase();
-    if (trimmed) {
+    if (!trimmed) {
       line = line.trim();
     }
     if (line.toLowerCase().startsWith(property)) {

**Comment by sebhildebrandt** [comment]
So this is actually really a bug. Found the problem. I will release this next week.

**Comment by sebhildebrandt** [comment]
Fixed in version 3.34.0
As I made a lot of changes in this commit, can you confirm that this is now working on your side?
