### ISSUE TITLE
add freebsd support

### ISSUE THREAD

**Issue by chair300** [sebhildebrandt/systeminformation#99]
### Issue Type

* [ ] Bug
* [x ] Feature Request
* [ ] Question

### Expected behavior 

- using the module I would expect to have some bsd support
- 
- 

### Actual behavior

-  none is found
- 
- 

### Steps to reproduce the problem

- run code on freebsd system
-
-

### Specifications 

- package version: 3.x
- operating system: freebsd
- hardware: x86 x86_64

### Problem and possible solution

If you have a solution in mind (or any idea what could cause this issue), we would be happy, if you can describe it here ... 

I would recommend using dmidecode for system info instead of lspci for linux.   dmidecode allows for a full system pull from the BMC.

**Comment by sebhildebrandt** [comment]
Hi, I am currently working on some freebsd support. Will take some more time to make my first release with basic freebsd support. I saw also your pull request... will need to integrate to what I already did here. I will come back to you as soon as I have something to test, OK?

**Comment by chair300** [comment]
Thats great news about freebsd support.   My update was really more to  add
simple dmidecode support.   Dmidecode is really cross platform.

**Comment by yzgyyang** [comment]
Great to hear that you are adding support for FreeBSD. It will enable a lot of modules that depend on systeminformation to run on FreeBSD.

**Comment by sebhildebrandt** [comment]
Working hard on FreeBSD implementation ... more work than I thought ;-) 
Hope to get a first version finished end of next week.

**Comment by yzgyyang** [comment]
@sebhildebrandt Please let me know! I was working on porting some system tools to FreeBSD, and this could be achieved if your work of systeminformation FreeBSD support is done :-)

**Comment by sebhildebrandt** [comment]
So, I now implemented first partial FreeBSD support. In this first release I implemented aprox. 70% of all functions (see docs `README.md`).

I had to reimplement nearly every function ;-) but for most of them I only made some basic tests. 

It would be cool, if you can also test them. If you discover issues, please share your discoveries. If possible, please provide also the output of the underlying shell command (which you should find in the code). That would help me improve the implementation

**Comment by yzgyyang** [comment]
I can definitely help testing that. Thanks for the work! @sebhildebrandt
